.TH "fsal_errors.c" 3 "31 Mar 2009" "Version 0.1" "File System Abstraction Layer (POSIX) library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fsal_errors.c \- Routines for handling errors.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include 'fsal.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "fsal_boolean_t \fBfsal_is_retryable\fP (fsal_status_t status)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Routines for handling errors. 

\fBAuthor:\fP
.RS 4
.RE
.PP
\fBAuthor\fP.RS 4
leibovic 
.RE
.PP
\fBDate:\fP
.RS 4
.RE
.PP
\fBDate\fP.RS 4
2005/07/27 13:30:26 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision\fP.RS 4
1.3 
.RE
.PP

.PP
Definition in file \fBfsal_errors.c\fP.
.SH "Function Documentation"
.PP 
.SS "fsal_boolean_t fsal_is_retryable (fsal_status_t status)"
.PP
fsal_is_retryable: Indicates if an FSAL error is retryable, i.e. if the caller has a chance of succeeding if it tries to call again the function that returned such an error code.
.PP
\fBParameters:\fP
.RS 4
\fIstatus(input),:\fP The fsal status whom retryability is to be tested.
.RE
.PP
\fBReturns:\fP
.RS 4
- TRUE if the error is retryable.
.IP "\(bu" 2
FALSE if the error is NOT retryable. 
.PP
.RE
.PP

.PP
\fBTodo\fP
.RS 4
: ERR_FSAL_DELAY : The only retryable error ? 
.RE
.PP

.PP
Definition at line 34 of file fsal_errors.c.
.PP
Referenced by fsal_increment_nbcall().
.SH "Author"
.PP 
Generated automatically by Doxygen for File System Abstraction Layer (POSIX) library from the source code.
