.TH "fsal_objectres.c" 3 "31 Mar 2009" "Version 0.1" "File System Abstraction Layer (POSIX) library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fsal_objectres.c \- FSAL remanent resources management routines.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include 'fsal.h'\fP
.br
\fC#include 'fsal_internal.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "fsal_status_t \fBFSAL_CleanObjectResources\fP (fsal_handle_t *in_fsal_handle)"
.br
.in -1c
.SH "Detailed Description"
.PP 
FSAL remanent resources management routines. 

\fBAuthor:\fP
.RS 4
$Author$ 
.RE
.PP
\fBDate:\fP
.RS 4
$Date$ 
.RE
.PP
\fBVersion:\fP
.RS 4
$Revision$ 
.RE
.PP

.PP
Definition in file \fBfsal_objectres.c\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for File System Abstraction Layer (POSIX) library from the source code.
