.TH "fsal_strings.c" 3 "31 Mar 2009" "Version 0.1" "File System Abstraction Layer (POSIX) library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fsal_strings.c \- FSAL names handling functions.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include 'fsal.h'\fP
.br
\fC#include 'fsal_internal.h'\fP
.br
\fC#include <string.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "fsal_status_t \fBFSAL_str2name\fP (const char *string, fsal_mdsize_t in_str_maxlen, fsal_name_t *name)"
.br
.ti -1c
.RI "fsal_status_t \fBFSAL_str2path\fP (char *string, fsal_mdsize_t in_str_maxlen, fsal_path_t *p_path)"
.br
.ti -1c
.RI "fsal_status_t \fBFSAL_name2str\fP (fsal_name_t *p_name, char *string, fsal_mdsize_t out_str_maxlen)"
.br
.ti -1c
.RI "fsal_status_t \fBFSAL_path2str\fP (fsal_path_t *p_path, char *string, fsal_mdsize_t out_str_maxlen)"
.br
.ti -1c
.RI "int \fBFSAL_namecmp\fP (fsal_name_t *p_name1, fsal_name_t *p_name2)"
.br
.ti -1c
.RI "int \fBFSAL_pathcmp\fP (fsal_path_t *p_path1, fsal_path_t *p_path2)"
.br
.ti -1c
.RI "fsal_status_t \fBFSAL_namecpy\fP (fsal_name_t *p_tgt_name, fsal_name_t *p_src_name)"
.br
.ti -1c
.RI "fsal_status_t \fBFSAL_pathcpy\fP (fsal_path_t *p_tgt_path, fsal_path_t *p_src_path)"
.br
.ti -1c
.RI "fsal_status_t \fBFSAL_buffdesc2name\fP (fsal_buffdesc_t *in_buf, fsal_name_t *out_name)"
.br
.ti -1c
.RI "fsal_status_t \fBFSAL_buffdesc2path\fP (fsal_buffdesc_t *in_buf, fsal_path_t *out_path)"
.br
.ti -1c
.RI "fsal_status_t \fBFSAL_path2buffdesc\fP (fsal_path_t *in_path, fsal_buffdesc_t *out_buff)"
.br
.ti -1c
.RI "fsal_status_t \fBFSAL_name2buffdesc\fP (fsal_name_t *in_name, fsal_buffdesc_t *out_buff)"
.br
.in -1c
.SH "Detailed Description"
.PP 
FSAL names handling functions. 

\fBAuthor:\fP
.RS 4
.RE
.PP
\fBAuthor\fP.RS 4
leibovic 
.RE
.PP
\fBDate:\fP
.RS 4
.RE
.PP
\fBDate\fP.RS 4
2006/01/18 08:30:37 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision\fP.RS 4
1.5 
.RE
.PP

.PP
Definition in file \fBfsal_strings.c\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for File System Abstraction Layer (POSIX) library from the source code.
