.TH "test_fsal.c" 3 "15 Sep 2010" "Version 0.1" "File System Abstraction Layer (POSIX) library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_fsal.c \- 
.PP
Program for testing fsal.  

.SH SYNOPSIS
.br
.PP
\fC#include 'fsal.h'\fP
.br
\fC#include 'log_macros.h'\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <sys/types.h>\fP
.br
\fC#include 'BuddyMalloc.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBREADDIR_SIZE\fP   5"
.br
.ti -1c
.RI "#define \fBCHANGE_ATTRS\fP(str_nom, nom, flag, new_val)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprintmask\fP (fsal_attrib_mask_t mask)"
.br
.ti -1c
.RI "char * \fBstrtype\fP (fsal_nodetype_t type)"
.br
.ti -1c
.RI "void \fBprintattributes\fP (fsal_attrib_list_t attrs)"
.br
.ti -1c
.RI "void \fBusage\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Program for testing fsal. 

\fBAuthor:\fP
.RS 4
.RE
.PP
\fBAuthor\fP.RS 4
leibovic 
.RE
.PP
\fBDate:\fP
.RS 4
.RE
.PP
\fBDate\fP.RS 4
2006/02/09 12:40:52 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision\fP.RS 4
1.25 
.RE
.PP

.PP
Definition in file \fBtest_fsal.c\fP.
.SH "Define Documentation"
.PP 
.SS "#define CHANGE_ATTRS(str_nom, nom, flag, new_val)"\fBValue:\fP
.PP
.nf
do {\
  memset(&attr_set, 0, sizeof(fsal_attrib_list_t) );    \
  Logtest('\nTry to change '%s' :',str_nom);           \
  FSAL_SET_MASK( attr_set.asked_attributes , flag );    \
  attr_set.nom = new_val;                               \
  attribs.asked_attributes = attr_set.asked_attributes; \
/*  attribs.asked_attributes = mask;                      */\
  st = FSAL_setattrs( &dir_hdl, &op_ctx, &attr_set, &attribs );\
  if ( FSAL_IS_ERROR(st) )                              \
    LogError(COMPONENT_FSAL,ERR_FSAL,st.major,st.minor);\
  else                                                  \
    printattributes( attribs );                         \
  } while(0)
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for File System Abstraction Layer (POSIX) library from the source code.
