.TH "todo" 3 "31 Mar 2009" "Version 0.1" "File System Abstraction Layer (POSIX) library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
 
.IP "\fBMember \fBposix2fsal_error\fP \fP" 1c
: The EBADF error also happens when file is opened for reading, and we try writting in it. In this case, we return ERR_FSAL_NOT_OPENED, but it doesn't seems to be a correct error translation. 
.PP
.PP
 
.IP "\fBMember \fBfsal_is_retryable\fP \fP" 1c
: ERR_FSAL_DELAY : The only retryable error ? 
.PP
.PP
 
.IP "\fBMember \fBFSAL_read\fP \fP" 1c
: manage fsal_size_t to size_t convertion 
.PP
.PP
 
.IP "\fBMember \fBFSAL_read\fP \fP" 1c
: manage ssize_t to fsal_size_t convertion 
.PP
.PP
 
.IP "\fBMember \fBFSAL_write\fP \fP" 1c
: manage fsal_size_t to size_t convertion 
.PP
.PP
 
.IP "\fBMember \fBFSAL_write\fP \fP" 1c
: manage ssize_t to fsal_size_t convertion 
.PP
.PP
 
.IP "\fBMember \fBFSAL_lookupPath\fP \fP" 1c
: Be carefull about junction crossing, symlinks, hardlinks,... 
.PP

