.TH "Audata" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Audata \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "opaque_auth \fBau_origcred\fP"
.br
.ti -1c
.RI "opaque_auth \fBau_shcred\fP"
.br
.ti -1c
.RI "u_long \fBau_shfaults\fP"
.br
.ti -1c
.RI "char \fBau_marshed\fP [MAX_AUTH_BYTES]"
.br
.ti -1c
.RI "u_int \fBau_mpos\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char \fBAudata::au_marshed\fP[MAX_AUTH_BYTES]"
.PP
Definition at line 105 of file Auth_unix.c.
.SS "u_int \fBAudata::au_mpos\fP"
.PP
Definition at line 106 of file Auth_unix.c.
.SS "struct opaque_auth \fBAudata::au_origcred\fP"
.PP
Definition at line 102 of file Auth_unix.c.
.PP
Referenced by Authunix_create().
.SS "struct opaque_auth \fBAudata::au_shcred\fP"
.PP
Definition at line 103 of file Auth_unix.c.
.PP
Referenced by Authunix_create().
.SS "u_long \fBAudata::au_shfaults\fP"
.PP
Definition at line 104 of file Auth_unix.c.
.PP
Referenced by Authunix_create().

.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
