.TH "Authgss_prot.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Authgss_prot.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <stdarg.h>\fP
.br
\fC#include 'Xdr.h'\fP
.br
\fC#include 'Auth.h'\fP
.br
\fC#include 'Auth_gss.h'\fP
.br
\fC#include 'Rpc.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
