.TH "Auth_unix.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Auth_unix.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include 'Auth.h'\fP
.br
\fC#include 'Auth_unix.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBAudata\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBAUTH_PRIVATE\fP(auth)   ((struct \fBAudata\fP *)auth->ah_private)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "AUTH * \fBAuthunix_create\fP (char *machname, uid_t uid, gid_t gid, int len, gid_t *aup_gids)"
.br
.ti -1c
.RI "AUTH * \fBAuthunix_create_default\fP ()"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define AUTH_PRIVATE(auth)   ((struct \fBAudata\fP *)auth->ah_private)"
.PP
Definition at line 108 of file Auth_unix.c.
.SH "Function Documentation"
.PP 
.SS "AUTH* Authunix_create (char * machname, uid_t uid, gid_t gid, int len, gid_t * aup_gids)"
.PP
Definition at line 117 of file Auth_unix.c.
.PP
References Audata::au_origcred, Audata::au_shcred, Audata::au_shfaults, Xdr_Authunix_parms(), and Xdrmem_create().
.PP
Referenced by Authunix_create_default().
.SS "AUTH* Authunix_create_default ()"
.PP
Definition at line 201 of file Auth_unix.c.
.PP
References Authunix_create().
.PP
Referenced by Clnt_broadcast().
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
