.TH "Authuxprot.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Authuxprot.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <errno.h>\fP
.br
\fC#include 'Types.h'\fP
.br
\fC#include 'Xdr.h'\fP
.br
\fC#include 'Rpc.h'\fP
.br
\fC#include 'Auth.h'\fP
.br
\fC#include 'Auth_unix.h'\fP
.br
\fC#include 'Clnt.h'\fP
.br
\fC#include <netinet/in.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool_t \fBXdr_Authunix_parms\fP (register XDR *xdrs, register struct Authunix_parms *p)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool_t Xdr_Authunix_parms (register XDR * xdrs, register struct Authunix_parms * p)"
.PP
Definition at line 83 of file Authuxprot.c.
.PP
References Xdr_array(), Xdr_string(), Xdr_u_int(), Xdr_u_long(), and Xdr_u_short().
.PP
Referenced by Authunix_create(), and Svcauth_unix().
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
