.TH "client-gss.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
client-gss.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sys/time.h>\fP
.br
\fC#include <sys/param.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <ctype.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <fcntl.h>\fP
.br
\fC#include <errno.h>\fP
.br
\fC#include <signal.h>\fP
.br
\fC#include <sys/socket.h>\fP
.br
\fC#include <netdb.h>\fP
.br
\fC#include <netinet/in.h>\fP
.br
\fC#include <netinet/tcp.h>\fP
.br
\fC#include <gssapi/gssapi.h>\fP
.br
\fC#include <gssapi/gssapi_generic.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBTOKEN_NOOP\fP   (1<<0)"
.br
.ti -1c
.RI "#define \fBTOKEN_CONTEXT\fP   (1<<1)"
.br
.ti -1c
.RI "#define \fBTOKEN_DATA\fP   (1<<2)"
.br
.ti -1c
.RI "#define \fBTOKEN_MIC\fP   (1<<3)"
.br
.ti -1c
.RI "#define \fBTOKEN_CONTEXT_NEXT\fP   (1<<4)"
.br
.ti -1c
.RI "#define \fBTOKEN_WRAPPED\fP   (1<<5)"
.br
.ti -1c
.RI "#define \fBTOKEN_ENCRYPTED\fP   (1<<6)"
.br
.ti -1c
.RI "#define \fBTOKEN_SEND_MIC\fP   (1<<7)"
.br
.ti -1c
.RI "#define \fBKRB5OID\fP   '1.2.840.113554.1.2.2'"
.br
.ti -1c
.RI "#define \fBLENMSG\fP   256"
.br
.ti -1c
.RI "#define \fBTraduireAdresse\fP(adresse, dest)"
.br
.ti -1c
.RI "#define \fBSNAME_DEFAUT\fP   'toto'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsperror_gss\fP (char *str, OM_uint32 major, OM_uint32 minor)"
.br
.ti -1c
.RI "int \fBwrite_tok\fP (int s, gss_buffer_t tok)"
.br
.ti -1c
.RI "int \fBread_tok\fP (int s, gss_buffer_t tok)"
.br
.ti -1c
.RI "int \fBCreerSocket\fP (unsigned int adresse, unsigned short port)"
.br
.ti -1c
.RI "int \fBnegociation_client\fP (int sockfd, char *service_name, gss_OID oid)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBrcsid\fP [] = '$Id: client-gss.c,v 1.1 2005/04/13 13:45:49 deniel Exp $'"
.br
.ti -1c
.RI "gss_OID_desc \fBkrb5oid\fP"
.br
.ti -1c
.RI "char \fBoptions\fP [] = 'hd:P:M:S:'"
.br
.ti -1c
.RI "char \fButilisation\fP []"
.br
.ti -1c
.RI "OM_uint32 \fBdeleg_flag\fP = 0"
.br
.ti -1c
.RI "gss_ctx_id_t \fBgss_context\fP"
.br
.ti -1c
.RI "gss_OID \fBg_mechOid\fP"
.br
.ti -1c
.RI "char \fBsname\fP [256]"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define KRB5OID   '1.2.840.113554.1.2.2'"
.PP
Definition at line 48 of file client-gss.c.
.SS "#define LENMSG   256"
.PP
Definition at line 54 of file client-gss.c.
.PP
Referenced by main().
.SS "#define SNAME_DEFAUT   'toto'"
.PP
Definition at line 61 of file client-gss.c.
.PP
Referenced by main().
.SS "#define TOKEN_CONTEXT   (1<<1)"
.PP
Definition at line 36 of file client-gss.c.
.PP
Referenced by negociation_client(), and negociation_server().
.SS "#define TOKEN_CONTEXT_NEXT   (1<<4)"
.PP
Definition at line 39 of file client-gss.c.
.PP
Referenced by negociation_client().
.SS "#define TOKEN_DATA   (1<<2)"
.PP
Definition at line 37 of file client-gss.c.
.PP
Referenced by send_msg().
.SS "#define TOKEN_ENCRYPTED   (1<<6)"
.PP
Definition at line 41 of file client-gss.c.
.PP
Referenced by send_msg().
.SS "#define TOKEN_MIC   (1<<3)"
.PP
Definition at line 38 of file client-gss.c.
.PP
Referenced by recv_msg().
.SS "#define TOKEN_NOOP   (1<<0)"
.PP
Definition at line 35 of file client-gss.c.
.PP
Referenced by negociation_client().
.SS "#define TOKEN_SEND_MIC   (1<<7)"
.PP
Definition at line 42 of file client-gss.c.
.SS "#define TOKEN_WRAPPED   (1<<5)"
.PP
Definition at line 40 of file client-gss.c.
.PP
Referenced by send_msg().
.SS "#define TraduireAdresse(adresse, dest)"
.PP
\fBValue:\fP
.PP
.nf
sprintf( dest, '%d.%d.%d.%d',                   \
                  ( ntohl( adresse ) & 0xFF000000 ) >> 24, \
                  ( ntohl( adresse ) & 0x00FF0000 ) >> 16, \
                  ( ntohl( adresse ) & 0x0000FF00 ) >> 8,  \
                  ( ntohl( adresse ) & 0x000000FF ) )
.fi
.PP
Definition at line 55 of file client-gss.c.
.PP
Referenced by main().
.SH "Function Documentation"
.PP 
.SS "int CreerSocket (unsigned int adresse, unsigned short port)"
.PP
Definition at line 86 of file client-gss.c.
.PP
Referenced by main().
.SS "int main (int argc, char * argv[])"
.PP
Definition at line 242 of file client-gss.c.
.PP
References CreerSocket(), g_mechOid, LENMSG, negociation_client(), options, sname, SNAME_DEFAUT, TraduireAdresse, and utilisation.
.SS "int negociation_client (int sockfd, char * service_name, gss_OID oid)"
.PP
Definition at line 120 of file client-gss.c.
.PP
References deleg_flag, gss_context, recv_token(), send_token(), sperror_gss(), TOKEN_CONTEXT, TOKEN_CONTEXT_NEXT, and TOKEN_NOOP.
.PP
Referenced by main().
.SS "int read_tok (int s, gss_buffer_t tok)"
.PP
.SS "void sperror_gss (char * str, OM_uint32 major, OM_uint32 minor)"
.PP
Definition at line 80 of file tools-gss.c.
.SS "int write_tok (int s, gss_buffer_t tok)"
.PP
.SH "Variable Documentation"
.PP 
.SS "OM_uint32 \fBdeleg_flag\fP = 0"
.PP
Definition at line 77 of file client-gss.c.
.PP
Referenced by negociation_client().
.SS "gss_OID \fBg_mechOid\fP"
.PP
Definition at line 79 of file client-gss.c.
.PP
Referenced by main().
.SS "gss_ctx_id_t \fBgss_context\fP"
.PP
Definition at line 78 of file client-gss.c.
.PP
Referenced by negociation_client().
.SS "gss_OID_desc \fBkrb5oid\fP"
.PP
\fBInitial value:\fP
.PP
.nf
 {
        20, KRB5OID
}
.fi
.PP
Definition at line 50 of file client-gss.c.
.SS "char \fBoptions\fP[] = 'hd:P:M:S:'"
.PP
Definition at line 64 of file client-gss.c.
.PP
Referenced by main().
.SS "char \fBrcsid\fP[] = '$Id: client-gss.c,v 1.1 2005/04/13 13:45:49 deniel Exp $'"
.PP
Definition at line 14 of file client-gss.c.
.SS "char \fBsname\fP[256]"
.PP
Definition at line 80 of file client-gss.c.
.PP
Referenced by main().
.SS "char \fButilisation\fP[]"
.PP
\fBInitial value:\fP
.PP
.nf

'Utilisation: %s [-hdPM] message\n'
'\t[-h]                   affiche cet aide en ligbe\n'
'\t[-d <machine>]         indique la machine serveur\n'
'\t[-P <port ou service>] le port ou le service ou le daemon ecoute\n'
'\t[-M <Mecanisme Auth>]  le mecanisme utilise par ls GSS-API\n' 
'\t[-S <Mecanisme Auth>]  le service utilise par ls GSS-API\n'
.fi
.PP
Definition at line 67 of file client-gss.c.
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
