.TH "Clnt_generic.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Clnt_generic.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string.h>\fP
.br
\fC#include 'Rpc.h'\fP
.br
\fC#include <sys/socket.h>\fP
.br
\fC#include <sys/errno.h>\fP
.br
\fC#include <netdb.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "Client * \fBClnt_create\fP (char *hostname, u_long prog, u_long vers, char *proto)"
.br
.ti -1c
.RI "bool_t \fBClientwrap_args\fP (Client *clnt, XDR *xdrs, Xdrproc_t xdr_args, caddr_t args_ptr)"
.br
.ti -1c
.RI "bool_t \fBClientunwrap_args\fP (Client *clnt, XDR *xdrs, Xdrproc_t xdr_args, caddr_t args_ptr)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool_t Clientunwrap_args (Client * clnt, XDR * xdrs, Xdrproc_t xdr_args, caddr_t args_ptr)"
.PP
Definition at line 107 of file Clnt_generic.c.
.SS "bool_t Clientwrap_args (Client * clnt, XDR * xdrs, Xdrproc_t xdr_args, caddr_t args_ptr)"
.PP
Definition at line 102 of file Clnt_generic.c.
.SS "Client* Clnt_create (char * hostname, u_long prog, u_long vers, char * proto)"
.PP
Definition at line 44 of file Clnt_generic.c.
.PP
References Clnttcp_create(), and Clntudp_create().
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
