.TH "Clnt_perror.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Clnt_perror.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include 'Rpc.h'\fP
.br
\fC#include 'Types.h'\fP
.br
\fC#include 'Auth.h'\fP
.br
\fC#include 'Clnt.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBCLNT_PERROR_BUFLEN\fP   256"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBClnt_sperrno\fP (enum Clnt_stat stat)"
.br
.ti -1c
.RI "void \fBClnt_perrno\fP (enum Clnt_stat num)"
.br
.ti -1c
.RI "char * \fBClnt_sperror\fP (Client *rpch, char *s)"
.br
.ti -1c
.RI "void \fBClnt_perror\fP (Client *rpch, char *s)"
.br
.ti -1c
.RI "char * \fBClnt_spcreateerror\fP (char *s)"
.br
.ti -1c
.RI "void \fBClnt_pcreateerror\fP (char *s)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define CLNT_PERROR_BUFLEN   256"
.PP
Definition at line 45 of file Clnt_perror.c.
.PP
Referenced by Clnt_spcreateerror(), and Clnt_sperror().
.SH "Function Documentation"
.PP 
.SS "void Clnt_pcreateerror (char * s)"
.PP
Definition at line 223 of file Clnt_perror.c.
.SS "void Clnt_perrno (enum Clnt_stat num)"
.PP
Definition at line 94 of file Clnt_perror.c.
.SS "void Clnt_perror (Client * rpch, char * s)"
.PP
Definition at line 186 of file Clnt_perror.c.
.SS "char* Clnt_spcreateerror (char * s)"
.PP
Definition at line 193 of file Clnt_perror.c.
.PP
References CLNT_PERROR_BUFLEN.
.SS "char* Clnt_sperrno (enum Clnt_stat stat)"
.PP
Definition at line 84 of file Clnt_perror.c.
.SS "char* Clnt_sperror (Client * rpch, char * s)"
.PP
Definition at line 102 of file Clnt_perror.c.
.PP
References CLNT_PERROR_BUFLEN.
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
