.TH "Clnt_tcp.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Clnt_tcp.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include 'Rpc.h'\fP
.br
\fC#include <sys/param.h>\fP
.br
\fC#include <sys/socket.h>\fP
.br
\fC#include <netdb.h>\fP
.br
\fC#include <errno.h>\fP
.br
\fC#include 'Types.h'\fP
.br
\fC#include 'stuff_alloc.h'\fP
.br
\fC#include 'Auth.h'\fP
.br
\fC#include 'Auth_none.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCt_data\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBNFDBITS\fP   (sizeof(long) * 8)"
.br
.ti -1c
.RI "#define \fBMCALL_MSG_SIZE\fP   24"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Client * \fBClnttcp_create\fP (struct sockaddr_in *raddr, u_long prog, u_long vers, register int *sockp, u_int sendsz, u_int recvsz)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define MCALL_MSG_SIZE   24"
.PP
Definition at line 69 of file Clnt_tcp.c.
.SS "#define NFDBITS   (sizeof(long) * 8)"
.PP
Definition at line 66 of file Clnt_tcp.c.
.SH "Function Documentation"
.PP 
.SS "Client* Clnttcp_create (struct sockaddr_in * raddr, u_long prog, u_long vers, register int * sockp, u_int sendsz, u_int recvsz)"
.PP
Definition at line 116 of file Clnt_tcp.c.
.PP
References Authnone_create(), Ct_data::ct_addr, Ct_data::ct_closeit, Ct_data::ct_mpos, Ct_data::ct_sock, Ct_data::ct_wait, Ct_data::ct_waitset, MCALL_MSG_SIZE, Xdr_callhdr(), Xdrmem_create(), and Xdrrec_create().
.PP
Referenced by Clnt_create(), Creer_RPCClient(), and Pmap_getport().
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
