.TH "Clnt_raw.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Clnt_raw.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Rpc.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBClntraw_private\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMCALL_MSG_SIZE\fP   24"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsvc_getreq\fP ()"
.br
.ti -1c
.RI "CLIENT * \fBClntraw_create\fP (u_long prog, u_long vers)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define MCALL_MSG_SIZE   24"
.PP
Definition at line 75 of file Clnt_raw.c.
.PP
Referenced by Clntraw_create(), and Clnttcp_create().
.SH "Function Documentation"
.PP 
.SS "CLIENT* Clntraw_create (u_long prog, u_long vers)"
.PP
Definition at line 110 of file Clnt_raw.c.
.PP
References MCALL_MSG_SIZE, UDPMSGSIZE, Xdr_callhdr(), and Xdrmem_create().
.SS "void svc_getreq ()"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
