.TH "Ct_data" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ct_data \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBct_sock\fP"
.br
.ti -1c
.RI "bool_t \fBct_closeit\fP"
.br
.ti -1c
.RI "timeval \fBct_wait\fP"
.br
.ti -1c
.RI "bool_t \fBct_waitset\fP"
.br
.ti -1c
.RI "sockaddr_in \fBct_addr\fP"
.br
.ti -1c
.RI "Rpc_err \fBct_error\fP"
.br
.ti -1c
.RI "char \fBct_mcall\fP [MCALL_MSG_SIZE]"
.br
.ti -1c
.RI "u_int \fBct_mpos\fP"
.br
.ti -1c
.RI "XDR \fBct_xdrs\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct sockaddr_in \fBCt_data::ct_addr\fP"
.PP
Definition at line 95 of file Clnt_tcp.c.
.PP
Referenced by Clnttcp_create().
.SS "bool_t \fBCt_data::ct_closeit\fP"
.PP
Definition at line 92 of file Clnt_tcp.c.
.PP
Referenced by Clnttcp_create().
.SS "struct Rpc_err \fBCt_data::ct_error\fP"
.PP
Definition at line 96 of file Clnt_tcp.c.
.SS "char \fBCt_data::ct_mcall\fP[MCALL_MSG_SIZE]"
.PP
Definition at line 97 of file Clnt_tcp.c.
.SS "u_int \fBCt_data::ct_mpos\fP"
.PP
Definition at line 98 of file Clnt_tcp.c.
.PP
Referenced by Clnttcp_create().
.SS "int \fBCt_data::ct_sock\fP"
.PP
Definition at line 91 of file Clnt_tcp.c.
.PP
Referenced by Clnttcp_create().
.SS "struct timeval \fBCt_data::ct_wait\fP"
.PP
Definition at line 93 of file Clnt_tcp.c.
.PP
Referenced by Clnttcp_create().
.SS "bool_t \fBCt_data::ct_waitset\fP"
.PP
Definition at line 94 of file Clnt_tcp.c.
.PP
Referenced by Clnttcp_create().
.SS "XDR \fBCt_data::ct_xdrs\fP"
.PP
Definition at line 99 of file Clnt_tcp.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
