.TH "Cu_data" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cu_data \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcu_sock\fP"
.br
.ti -1c
.RI "bool_t \fBcu_closeit\fP"
.br
.ti -1c
.RI "sockaddr_in \fBcu_raddr\fP"
.br
.ti -1c
.RI "int \fBcu_rlen\fP"
.br
.ti -1c
.RI "timeval \fBcu_wait\fP"
.br
.ti -1c
.RI "timeval \fBcu_total\fP"
.br
.ti -1c
.RI "Rpc_err \fBcu_error\fP"
.br
.ti -1c
.RI "XDR \fBcu_outxdrs\fP"
.br
.ti -1c
.RI "u_int \fBcu_xdrpos\fP"
.br
.ti -1c
.RI "u_int \fBcu_sendsz\fP"
.br
.ti -1c
.RI "char * \fBcu_outbuf\fP"
.br
.ti -1c
.RI "u_int \fBcu_recvsz\fP"
.br
.ti -1c
.RI "char \fBcu_inbuf\fP [1]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "bool_t \fBCu_data::cu_closeit\fP"
.PP
Definition at line 82 of file Clnt_udp.c.
.PP
Referenced by Clntudp_bufcreate().
.SS "struct Rpc_err \fBCu_data::cu_error\fP"
.PP
Definition at line 87 of file Clnt_udp.c.
.SS "char \fBCu_data::cu_inbuf\fP[1]"
.PP
Definition at line 93 of file Clnt_udp.c.
.PP
Referenced by Clntudp_bufcreate().
.SS "char* \fBCu_data::cu_outbuf\fP"
.PP
Definition at line 91 of file Clnt_udp.c.
.PP
Referenced by Clntudp_bufcreate().
.SS "XDR \fBCu_data::cu_outxdrs\fP"
.PP
Definition at line 88 of file Clnt_udp.c.
.SS "struct sockaddr_in \fBCu_data::cu_raddr\fP"
.PP
Definition at line 83 of file Clnt_udp.c.
.PP
Referenced by Clntudp_bufcreate().
.SS "u_int \fBCu_data::cu_recvsz\fP"
.PP
Definition at line 92 of file Clnt_udp.c.
.PP
Referenced by Clntudp_bufcreate().
.SS "int \fBCu_data::cu_rlen\fP"
.PP
Definition at line 84 of file Clnt_udp.c.
.PP
Referenced by Clntudp_bufcreate().
.SS "u_int \fBCu_data::cu_sendsz\fP"
.PP
Definition at line 90 of file Clnt_udp.c.
.PP
Referenced by Clntudp_bufcreate().
.SS "int \fBCu_data::cu_sock\fP"
.PP
Definition at line 81 of file Clnt_udp.c.
.PP
Referenced by Clntudp_bufcreate().
.SS "struct timeval \fBCu_data::cu_total\fP"
.PP
Definition at line 86 of file Clnt_udp.c.
.PP
Referenced by Clntudp_bufcreate().
.SS "struct timeval \fBCu_data::cu_wait\fP"
.PP
Definition at line 85 of file Clnt_udp.c.
.PP
Referenced by Clntudp_bufcreate().
.SS "u_int \fBCu_data::cu_xdrpos\fP"
.PP
Definition at line 89 of file Clnt_udp.c.
.PP
Referenced by Clntudp_bufcreate().

.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
