.TH "Get_myaddress.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Get_myaddress.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Rpc.h'\fP
.br
\fC#include 'Auth.h'\fP
.br
\fC#include <sys/socket.h>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <net/if.h>\fP
.br
\fC#include <sys/ioctl.h>\fP
.br
\fC#include <netinet/in.h>\fP
.br
\fC#include <arpa/inet.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMY_PMAPPORT\fP   ((u_short)111)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBGet_myaddress\fP (struct sockaddr_in *addr)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define MY_PMAPPORT   ((u_short)111)"
.PP
Definition at line 48 of file Get_myaddress.c.
.PP
Referenced by Get_myaddress().
.SH "Function Documentation"
.PP 
.SS "int Get_myaddress (struct sockaddr_in * addr)"
.PP
Definition at line 57 of file Get_myaddress.c.
.PP
References MY_PMAPPORT.
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
