.TH "onc_rpc_client.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
onc_rpc_client.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <sys/types.h>\fP
.br
\fC#include <pwd.h>\fP
.br
\fC#include <sys/param.h>\fP
.br
\fC#include <netdb.h>\fP
.br
\fC#include <netinet/in.h>\fP
.br
\fC#include <netinet/tcp.h>\fP
.br
\fC#include <sys/socket.h>\fP
.br
\fC#include <errno.h>\fP
.br
\fC#include 'Rpc.h'\fP
.br
\fC#include 'Pmap_clnt.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBTraduireAdresse\fP(adresse, dest)"
.br
.ti -1c
.RI "#define \fBTIMEOUT_SEC\fP   25"
.br
.ti -1c
.RI "#define \fBDEFAULT_RPC_SERVICE\fP   300400"
.br
.ti -1c
.RI "#define \fBRECV_SIZE\fP   2048"
.br
.ti -1c
.RI "#define \fBSEND_SIZE\fP   2048"
.br
.ti -1c
.RI "#define \fBV1\fP   1"
.br
.ti -1c
.RI "#define \fBPROC_NULL\fP   0"
.br
.ti -1c
.RI "#define \fBPROC_PLUS1\fP   1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "CLIENT * \fBCreer_RPCClient\fP (unsigned int adresse, unsigned int programme, unsigned int version, unsigned short port, int sockfd)"
.br
.ti -1c
.RI "\fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "gss_OID_desc \fBkrb5oid\fP"
.br
.ti -1c
.RI "char \fBoptions\fP [] = 'hd:s:'"
.br
.ti -1c
.RI "char \fButilisation\fP []"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define DEFAULT_RPC_SERVICE   300400"
.PP
Definition at line 35 of file onc_rpc_client.c.
.SS "#define PROC_NULL   0"
.PP
Definition at line 39 of file onc_rpc_client.c.
.PP
Referenced by dispatch().
.SS "#define PROC_PLUS1   1"
.PP
Definition at line 40 of file onc_rpc_client.c.
.PP
Referenced by dispatch(), and main().
.SS "#define RECV_SIZE   2048"
.PP
Definition at line 36 of file onc_rpc_client.c.
.PP
Referenced by Creer_RPCClient(), and main().
.SS "#define SEND_SIZE   2048"
.PP
Definition at line 37 of file onc_rpc_client.c.
.PP
Referenced by Creer_RPCClient(), and main().
.SS "#define TIMEOUT_SEC   25"
.PP
Definition at line 34 of file onc_rpc_client.c.
.SS "#define TraduireAdresse(adresse, dest)"
.PP
\fBValue:\fP
.PP
.nf
sprintf( dest, '%d.%d.%d.%d',                   \
                  ( ntohl( adresse ) & 0xFF000000 ) >> 24, \
                  ( ntohl( adresse ) & 0x00FF0000 ) >> 16, \
                  ( ntohl( adresse ) & 0x0000FF00 ) >> 8,  \
                  ( ntohl( adresse ) & 0x000000FF ) )
.fi
.PP
Definition at line 28 of file onc_rpc_client.c.
.SS "#define V1   1"
.PP
Definition at line 38 of file onc_rpc_client.c.
.PP
Referenced by main().
.SH "Function Documentation"
.PP 
.SS "CLIENT* Creer_RPCClient (unsigned int adresse, unsigned int programme, unsigned int version, unsigned short port, int sockfd)"
.PP
Definition at line 56 of file onc_rpc_client.c.
.PP
References Clnttcp_create(), RECV_SIZE, and SEND_SIZE.
.SS "main (int argc, char * argv[])"
.PP
Definition at line 112 of file onc_rpc_client.c.
.PP
References Clnt_perror(), Creer_RPCClient(), options, PROC_PLUS1, rpc_service_num, utilisation, V1, and Xdr_int().
.SH "Variable Documentation"
.PP 
.SS "gss_OID_desc \fBkrb5oid\fP"
.PP
Definition at line 50 of file client-gss.c.
.SS "char \fBoptions\fP[] = 'hd:s:'"
.PP
Definition at line 46 of file onc_rpc_client.c.
.SS "char \fButilisation\fP[]"
.PP
\fBInitial value:\fP
.PP
.nf

'Utilisation: %s [-hds] message\n'
'\t[-h]                   affiche cet aide en ligbe\n'
'\t[-d <machine>]         indique la machine serveur\n'
'\t[-s <service RPC>]     indique le port ou le service a utiliser\n'
.fi
.PP
Definition at line 47 of file onc_rpc_client.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
