.TH "onc_rpc_server.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
onc_rpc_server.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <sys/errno.h>\fP
.br
\fC#include <sys/param.h>\fP
.br
\fC#include <sys/types.h>\fP
.br
\fC#include <sys/socket.h>\fP
.br
\fC#include <netdb.h>\fP
.br
\fC#include <netinet/in.h>\fP
.br
\fC#include <netinet/tcp.h>\fP
.br
\fC#include 'Rpc.h'\fP
.br
\fC#include 'Pmap_clnt.h'\fP
.br
\fC#include 'gssapi/gssapi.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBLOGFILE_DEFAUT\fP   './toto-\fBserver\fP.log'"
.br
.ti -1c
.RI "#define \fBTraduireAdresse\fP(adresse, dest)"
.br
.ti -1c
.RI "#define \fBTIMEOUT_SEC\fP   25"
.br
.ti -1c
.RI "#define \fBDEFAULT_RPC_SERVICE\fP   300400"
.br
.ti -1c
.RI "#define \fBRECV_SIZE\fP   2048"
.br
.ti -1c
.RI "#define \fBSEND_SIZE\fP   2048"
.br
.ti -1c
.RI "#define \fBV1\fP   1"
.br
.ti -1c
.RI "#define \fBPROC_NULL\fP   0"
.br
.ti -1c
.RI "#define \fBPROC_PLUS1\fP   1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdispatch\fP (struct Svc_req *ptr_req, SVCXPRT *ptr_svc)"
.br
.ti -1c
.RI "\fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBoptions\fP [] = 'hL:N:s:'"
.br
.ti -1c
.RI "char \fButilisation\fP []"
.br
.ti -1c
.RI "unsigned int \fBrpc_service_num\fP = DEFAULT_RPC_SERVICE"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define DEFAULT_RPC_SERVICE   300400"
.PP
Definition at line 39 of file onc_rpc_server.c.
.SS "#define LOGFILE_DEFAUT   './toto-\fBserver\fP.log'"
.PP
Definition at line 31 of file onc_rpc_server.c.
.PP
Referenced by main().
.SS "#define PROC_NULL   0"
.PP
Definition at line 43 of file onc_rpc_server.c.
.SS "#define PROC_PLUS1   1"
.PP
Definition at line 44 of file onc_rpc_server.c.
.SS "#define RECV_SIZE   2048"
.PP
Definition at line 40 of file onc_rpc_server.c.
.SS "#define SEND_SIZE   2048"
.PP
Definition at line 41 of file onc_rpc_server.c.
.SS "#define TIMEOUT_SEC   25"
.PP
Definition at line 38 of file onc_rpc_server.c.
.SS "#define TraduireAdresse(adresse, dest)"
.PP
\fBValue:\fP
.PP
.nf
sprintf( dest, '%d.%d.%d.%d',                   \
                  ( ntohl( adresse ) & 0xFF000000 ) >> 24, \
                  ( ntohl( adresse ) & 0x00FF0000 ) >> 16, \
                  ( ntohl( adresse ) & 0x0000FF00 ) >> 8,  \
                  ( ntohl( adresse ) & 0x000000FF ) )
.fi
.PP
Definition at line 32 of file onc_rpc_server.c.
.SS "#define V1   1"
.PP
Definition at line 42 of file onc_rpc_server.c.
.SH "Function Documentation"
.PP 
.SS "void dispatch (struct Svc_req * ptr_req, SVCXPRT * ptr_svc)"
.PP
Definition at line 63 of file onc_rpc_server.c.
.PP
References PROC_NULL, PROC_PLUS1, Svc_sendreply(), Svcerr_decode(), Xdr_int(), and Xdr_void().
.PP
Referenced by main().
.SS "main (int argc, char * argv[])"
.PP
Definition at line 105 of file onc_rpc_server.c.
.PP
References dispatch(), LOGFILE_DEFAUT, options, Pmap_unset(), RECV_SIZE, rpc_service_num, SEND_SIZE, Svc_register(), Svc_run(), Svcauth_gss_tab_creds_alloc(), Svctcp_create(), utilisation, and V1.
.SH "Variable Documentation"
.PP 
.SS "char \fBoptions\fP[] = 'hL:N:s:'"
.PP
Definition at line 48 of file onc_rpc_server.c.
.SS "unsigned int \fBrpc_service_num\fP = DEFAULT_RPC_SERVICE"
.PP
Definition at line 60 of file onc_rpc_server.c.
.PP
Referenced by main().
.SS "char \fButilisation\fP[]"
.PP
\fBInitial value:\fP
.PP
.nf
 
'Utilisation: %s [-hLs] \n'
'\t[-h]                   affiche cet aide en ligne\n'
'\t[-L <logfile>]         indique le fichier de log\n'
'\t[-N <NivDebug>]        indique le niveau de debug pour les journaux\n' 
'\t[-s <service RPC>]     indique le port ou le service a utiliser\n'
.fi
.PP
Definition at line 51 of file onc_rpc_server.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
