.TH "Pm_getport.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pm_getport.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdbool.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include 'Rpc.h'\fP
.br
\fC#include 'Pmap_prot.h'\fP
.br
\fC#include 'Pmap_clnt.h'\fP
.br
\fC#include <sys/socket.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "u_short \fBPmap_getport\fP (struct sockaddr_in *address, u_long program, u_long version, u_int protocol)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "u_short Pmap_getport (struct sockaddr_in * address, u_long program, u_long version, u_int protocol)"
.PP
Definition at line 53 of file Pm_getport.c.
.PP
References Clnt_perror(), Clnttcp_create(), Clntudp_bufcreate(), Xdr_Pmap(), and Xdr_u_short().
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
