.TH "Pmap_rmt.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pmap_rmt.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <unistd.h>\fP
.br
\fC#include 'Rpc.h'\fP
.br
\fC#include 'Auth_unix.h'\fP
.br
\fC#include 'Pmap_prot.h'\fP
.br
\fC#include 'Pmap_clnt.h'\fP
.br
\fC#include 'Pmap_rmt.h'\fP
.br
\fC#include <sys/socket.h>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <errno.h>\fP
.br
\fC#include <sys/param.h>\fP
.br
\fC#include <net/if.h>\fP
.br
\fC#include <sys/ioctl.h>\fP
.br
\fC#include <arpa/inet.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMAX_BROADCAST_SIZE\fP   1400"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "enum Clnt_stat \fBPmap_rmtcall\fP (struct sockaddr_in *addr, u_long prog, u_long vers, u_long proc, Xdrproc_t xdrargs, caddr_t argsp, Xdrproc_t xdrres, caddr_t resp, struct timeval tout, u_long *port_ptr)"
.br
.ti -1c
.RI "bool_t \fBXdr_Rmtcall_args\fP (XDR *xdrs, struct Rmtcallargs *cap)"
.br
.ti -1c
.RI "bool_t \fBXdr_Rmtcallres\fP (XDR *xdrs, struct Rmtcallres *crp)"
.br
.ti -1c
.RI "enum Clnt_stat \fBClnt_broadcast\fP (u_long prog, u_long vers, u_long proc, Xdrproc_t xargs, caddr_t argsp, Xdrproc_t xresults, caddr_t resultsp, resultproc_t eachresult)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define MAX_BROADCAST_SIZE   1400"
.PP
Definition at line 83 of file Pmap_rmt.c.
.PP
Referenced by Clnt_broadcast().
.SH "Function Documentation"
.PP 
.SS "enum Clnt_stat Clnt_broadcast (u_long prog, u_long vers, u_long proc, Xdrproc_t xargs, caddr_t argsp, Xdrproc_t xresults, caddr_t resultsp, resultproc_t eachresult)"
.PP
Definition at line 208 of file Pmap_rmt.c.
.PP
References Authunix_create_default(), MAX_BROADCAST_SIZE, UDPMSGSIZE, Xdr_callmsg(), Xdr_replymsg(), Xdr_Rmtcall_args(), and Xdrmem_create().
.SS "enum Clnt_stat Pmap_rmtcall (struct sockaddr_in * addr, u_long prog, u_long vers, u_long proc, Xdrproc_t xdrargs, caddr_t argsp, Xdrproc_t xdrres, caddr_t resp, struct timeval tout, u_long * port_ptr)"
.PP
Definition at line 97 of file Pmap_rmt.c.
.PP
References Clntudp_create(), Xdr_Rmtcall_args(), and Xdr_Rmtcallres().
.SS "bool_t Xdr_Rmtcall_args (XDR * xdrs, struct Rmtcallargs * cap)"
.PP
Definition at line 141 of file Pmap_rmt.c.
.PP
References Xdr_u_long().
.PP
Referenced by Clnt_broadcast(), and Pmap_rmtcall().
.SS "bool_t Xdr_Rmtcallres (XDR * xdrs, struct Rmtcallres * crp)"
.PP
Definition at line 169 of file Pmap_rmt.c.
.PP
References Xdr_reference(), and Xdr_u_long().
.PP
Referenced by Pmap_rmtcall().
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
