.TH "Pmap_prot.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pmap_prot.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Rpc.h'\fP
.br
\fC#include 'Clnt.h'\fP
.br
\fC#include 'Pmap_prot.h'\fP
.br
\fC#include 'Xdr.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool_t \fBXdr_Pmap\fP (XDR *xdrs, struct Pmap *regs)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool_t Xdr_Pmap (XDR * xdrs, struct Pmap * regs)"
.PP
Definition at line 73 of file Pmap_prot.c.
.PP
References Xdr_u_long().
.PP
Referenced by Pmap_getport(), Pmap_set(), and Pmap_unset().
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
