.TH "rec_strm" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rec_strm \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "caddr_t \fBtcp_handle\fP"
.br
.ti -1c
.RI "caddr_t \fBthe_buffer\fP"
.br
.ti -1c
.RI "int(* \fBwriteit\fP )(caddr_t, caddr_t, int)"
.br
.ti -1c
.RI "caddr_t \fBout_base\fP"
.br
.ti -1c
.RI "caddr_t \fBout_finger\fP"
.br
.ti -1c
.RI "caddr_t \fBout_boundry\fP"
.br
.ti -1c
.RI "u_int32_t * \fBfrag_header\fP"
.br
.ti -1c
.RI "bool_t \fBfrag_sent\fP"
.br
.ti -1c
.RI "int(* \fBreadit\fP )(caddr_t, caddr_t, int)"
.br
.ti -1c
.RI "u_long \fBin_size\fP"
.br
.ti -1c
.RI "caddr_t \fBin_base\fP"
.br
.ti -1c
.RI "caddr_t \fBin_finger\fP"
.br
.ti -1c
.RI "caddr_t \fBin_boundry\fP"
.br
.ti -1c
.RI "long \fBfbtbc\fP"
.br
.ti -1c
.RI "bool_t \fBlast_frag\fP"
.br
.ti -1c
.RI "u_int \fBsendsize\fP"
.br
.ti -1c
.RI "u_int \fBrecvsize\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "long \fBrec_strm::fbtbc\fP"
.PP
Definition at line 119 of file Xdr_rec.c.
.PP
Referenced by Xdrrec_create(), Xdrrec_eof(), and Xdrrec_skiprecord().
.SS "u_int32_t* \fBrec_strm::frag_header\fP"
.PP
Definition at line 109 of file Xdr_rec.c.
.PP
Referenced by Xdrrec_create(), and Xdrrec_endofrecord().
.SS "bool_t \fBrec_strm::frag_sent\fP"
.PP
Definition at line 110 of file Xdr_rec.c.
.PP
Referenced by Xdrrec_create(), and Xdrrec_endofrecord().
.SS "caddr_t \fBrec_strm::in_base\fP"
.PP
Definition at line 116 of file Xdr_rec.c.
.PP
Referenced by Xdrrec_create().
.SS "caddr_t \fBrec_strm::in_boundry\fP"
.PP
Definition at line 118 of file Xdr_rec.c.
.PP
Referenced by Xdrrec_create(), and Xdrrec_eof().
.SS "caddr_t \fBrec_strm::in_finger\fP"
.PP
Definition at line 117 of file Xdr_rec.c.
.PP
Referenced by Xdrrec_create(), and Xdrrec_eof().
.SS "u_long \fBrec_strm::in_size\fP"
.PP
Definition at line 115 of file Xdr_rec.c.
.PP
Referenced by Xdrrec_create().
.SS "bool_t \fBrec_strm::last_frag\fP"
.PP
Definition at line 120 of file Xdr_rec.c.
.PP
Referenced by Xdrrec_create(), Xdrrec_eof(), and Xdrrec_skiprecord().
.SS "caddr_t \fBrec_strm::out_base\fP"
.PP
Definition at line 106 of file Xdr_rec.c.
.PP
Referenced by Xdrrec_create().
.SS "caddr_t \fBrec_strm::out_boundry\fP"
.PP
Definition at line 108 of file Xdr_rec.c.
.PP
Referenced by Xdrrec_create(), and Xdrrec_endofrecord().
.SS "caddr_t \fBrec_strm::out_finger\fP"
.PP
Definition at line 107 of file Xdr_rec.c.
.PP
Referenced by Xdrrec_create(), and Xdrrec_endofrecord().
.SS "int(* \fBrec_strm::readit\fP)(caddr_t, caddr_t, int)"
.PP
Referenced by Xdrrec_create().
.SS "u_int \fBrec_strm::recvsize\fP"
.PP
Definition at line 122 of file Xdr_rec.c.
.PP
Referenced by Xdrrec_create().
.SS "u_int \fBrec_strm::sendsize\fP"
.PP
Definition at line 121 of file Xdr_rec.c.
.PP
Referenced by Xdrrec_create().
.SS "caddr_t \fBrec_strm::tcp_handle\fP"
.PP
Definition at line 100 of file Xdr_rec.c.
.PP
Referenced by Xdrrec_create().
.SS "caddr_t \fBrec_strm::the_buffer\fP"
.PP
Definition at line 101 of file Xdr_rec.c.
.PP
Referenced by Xdrrec_create().
.SS "int(* \fBrec_strm::writeit\fP)(caddr_t, caddr_t, int)"
.PP
Referenced by Xdrrec_create().

.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
