.TH "Rpc_prot.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Rpc_prot.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sys/param.h>\fP
.br
\fC#include 'Rpc.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBXdr_u_int32_t\fP(x, a)   Xdr_u_int( x, (u_int *)a )"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool_t \fBXdr_opaque_auth\fP (XDR *xdrs, struct opaque_auth *ap)"
.br
.ti -1c
.RI "bool_t \fBXdr_des_block\fP (XDR *xdrs, des_block *blkp)"
.br
.ti -1c
.RI "bool_t \fBXdr_accepted_reply\fP (XDR *xdrs, struct accepted_reply *ar)"
.br
.ti -1c
.RI "bool_t \fBXdr_rejected_reply\fP (XDR *xdrs, struct rejected_reply *rr)"
.br
.ti -1c
.RI "bool_t \fBXdr_replymsg\fP (XDR *xdrs, struct Rpc_msg *rmsg)"
.br
.ti -1c
.RI "bool_t \fBXdr_callhdr\fP (XDR *xdrs, struct Rpc_msg *cmsg)"
.br
.ti -1c
.RI "void \fB_seterr_reply\fP (struct Rpc_msg *msg, struct Rpc_err *error)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define Xdr_u_int32_t(x, a)   Xdr_u_int( x, (u_int *)a )"
.PP
Definition at line 47 of file Rpc_prot.c.
.PP
Referenced by Xdr_accepted_reply(), Xdr_callhdr(), Xdr_rejected_reply(), and Xdr_replymsg().
.SH "Function Documentation"
.PP 
.SS "void _seterr_reply (struct Rpc_msg * msg, struct Rpc_err * error)"
.PP
Definition at line 216 of file Rpc_prot.c.
.SS "bool_t Xdr_accepted_reply (XDR * xdrs, struct accepted_reply * ar)"
.PP
Definition at line 77 of file Rpc_prot.c.
.PP
References Xdr_enum(), Xdr_opaque_auth(), and Xdr_u_int32_t.
.SS "bool_t Xdr_callhdr (XDR * xdrs, struct Rpc_msg * cmsg)"
.PP
Definition at line 143 of file Rpc_prot.c.
.PP
References Xdr_enum(), and Xdr_u_int32_t.
.PP
Referenced by Clntraw_create(), Clnttcp_create(), and Clntudp_bufcreate().
.SS "bool_t Xdr_des_block (XDR * xdrs, des_block * blkp)"
.PP
Definition at line 67 of file Rpc_prot.c.
.PP
References Xdr_opaque().
.SS "bool_t Xdr_opaque_auth (XDR * xdrs, struct opaque_auth * ap)"
.PP
Definition at line 55 of file Rpc_prot.c.
.PP
References Xdr_bytes(), and Xdr_enum().
.PP
Referenced by Authnone_create(), Xdr_accepted_reply(), and Xdr_callmsg().
.SS "bool_t Xdr_rejected_reply (XDR * xdrs, struct rejected_reply * rr)"
.PP
Definition at line 101 of file Rpc_prot.c.
.PP
References Xdr_enum(), and Xdr_u_int32_t.
.SS "bool_t Xdr_replymsg (XDR * xdrs, struct Rpc_msg * rmsg)"
.PP
Definition at line 127 of file Rpc_prot.c.
.PP
References Xdr_enum(), Xdr_u_int32_t, and Xdr_union().
.PP
Referenced by Clnt_broadcast().
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
