.TH "server-gss.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server-gss.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sys/param.h>\fP
.br
\fC#include <sys/time.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <ctype.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <fcntl.h>\fP
.br
\fC#include <errno.h>\fP
.br
\fC#include <signal.h>\fP
.br
\fC#include <sys/socket.h>\fP
.br
\fC#include <netdb.h>\fP
.br
\fC#include <netinet/in.h>\fP
.br
\fC#include <netinet/tcp.h>\fP
.br
\fC#include <gssapi/gssapi.h>\fP
.br
\fC#include <gssapi/gssapi_generic.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBTraduireAdresse\fP(adresse, dest)"
.br
.ti -1c
.RI "#define \fBLOGFILE_DEFAUT\fP   './toto-\fBserver\fP.log'"
.br
.ti -1c
.RI "#define \fBMAX_CONN\fP   32"
.br
.ti -1c
.RI "#define \fBLENMSG\fP   256"
.br
.ti -1c
.RI "#define \fBSTRLEN\fP   256"
.br
.ti -1c
.RI "#define \fBGSS_SERVICE_DEFAUT\fP   'toto'"
.br
.ti -1c
.RI "#define \fBTOKEN_NOOP\fP   (1<<0)"
.br
.ti -1c
.RI "#define \fBTOKEN_CONTEXT\fP   (1<<1)"
.br
.ti -1c
.RI "#define \fBTOKEN_DATA\fP   (1<<2)"
.br
.ti -1c
.RI "#define \fBTOKEN_MIC\fP   (1<<3)"
.br
.ti -1c
.RI "#define \fBTOKEN_CONTEXT_NEXT\fP   (1<<4)"
.br
.ti -1c
.RI "#define \fBTOKEN_WRAPPED\fP   (1<<5)"
.br
.ti -1c
.RI "#define \fBTOKEN_ENCRYPTED\fP   (1<<6)"
.br
.ti -1c
.RI "#define \fBTOKEN_SEND_MIC\fP   (1<<7)"
.br
.ti -1c
.RI "#define \fBTOKEN_NOOP\fP   (1<<0)"
.br
.ti -1c
.RI "#define \fBTOKEN_CONTEXT\fP   (1<<1)"
.br
.ti -1c
.RI "#define \fBTOKEN_DATA\fP   (1<<2)"
.br
.ti -1c
.RI "#define \fBTOKEN_MIC\fP   (1<<3)"
.br
.ti -1c
.RI "#define \fBTOKEN_CONTEXT_NEXT\fP   (1<<4)"
.br
.ti -1c
.RI "#define \fBTOKEN_WRAPPED\fP   (1<<5)"
.br
.ti -1c
.RI "#define \fBTOKEN_ENCRYPTED\fP   (1<<6)"
.br
.ti -1c
.RI "#define \fBTOKEN_SEND_MIC\fP   (1<<7)"
.br
.ti -1c
.RI "#define \fBKEYTAB\fP   '/var/hpss/etc/hpss.keytab'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBrecv_token\fP (int s, int *flags, gss_buffer_t tok)"
.br
.ti -1c
.RI "int \fBsend_token\fP (int s, int flags, gss_buffer_t tok)"
.br
.ti -1c
.RI "void \fBsperror_gss\fP (char *str, OM_uint32 major, OM_uint32 minor)"
.br
.ti -1c
.RI "int \fBobtention_creds\fP (char *service_name, gss_cred_id_t *pcreds)"
.br
.ti -1c
.RI "int \fBnegociation_server\fP (int sockfd)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBrcsid\fP [] = '$Id: \fBserver\fP-gss.c,v 1.1 2005/04/13 13:45:49 deniel Exp $'"
.br
.ti -1c
.RI "char \fBoptions\fP [] = 'hL:N:P:S:'"
.br
.ti -1c
.RI "char \fButilisation\fP []"
.br
.ti -1c
.RI "unsigned short \fBbinding_port\fP = 0"
.br
.ti -1c
.RI "char \fBgss_service\fP [STRLEN]"
.br
.ti -1c
.RI "gss_cred_id_t \fBcreds\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define GSS_SERVICE_DEFAUT   'toto'"
.PP
Definition at line 39 of file server-gss.c.
.PP
Referenced by main().
.SS "#define KEYTAB   '/var/hpss/etc/hpss.keytab'"
.PP
Definition at line 58 of file server-gss.c.
.PP
Referenced by obtention_creds().
.SS "#define LENMSG   256"
.PP
Definition at line 37 of file server-gss.c.
.SS "#define LOGFILE_DEFAUT   './toto-\fBserver\fP.log'"
.PP
Definition at line 35 of file server-gss.c.
.SS "#define MAX_CONN   32"
.PP
Definition at line 36 of file server-gss.c.
.PP
Referenced by main(), and Svctcp_create().
.SS "#define STRLEN   256"
.PP
Definition at line 38 of file server-gss.c.
.SS "#define TOKEN_CONTEXT   (1<<1)"
.PP
Definition at line 50 of file server-gss.c.
.SS "#define TOKEN_CONTEXT   (1<<1)"
.PP
Definition at line 50 of file server-gss.c.
.SS "#define TOKEN_CONTEXT_NEXT   (1<<4)"
.PP
Definition at line 53 of file server-gss.c.
.SS "#define TOKEN_CONTEXT_NEXT   (1<<4)"
.PP
Definition at line 53 of file server-gss.c.
.SS "#define TOKEN_DATA   (1<<2)"
.PP
Definition at line 51 of file server-gss.c.
.SS "#define TOKEN_DATA   (1<<2)"
.PP
Definition at line 51 of file server-gss.c.
.SS "#define TOKEN_ENCRYPTED   (1<<6)"
.PP
Definition at line 55 of file server-gss.c.
.SS "#define TOKEN_ENCRYPTED   (1<<6)"
.PP
Definition at line 55 of file server-gss.c.
.SS "#define TOKEN_MIC   (1<<3)"
.PP
Definition at line 52 of file server-gss.c.
.SS "#define TOKEN_MIC   (1<<3)"
.PP
Definition at line 52 of file server-gss.c.
.SS "#define TOKEN_NOOP   (1<<0)"
.PP
Definition at line 49 of file server-gss.c.
.SS "#define TOKEN_NOOP   (1<<0)"
.PP
Definition at line 49 of file server-gss.c.
.SS "#define TOKEN_SEND_MIC   (1<<7)"
.PP
Definition at line 56 of file server-gss.c.
.SS "#define TOKEN_SEND_MIC   (1<<7)"
.PP
Definition at line 56 of file server-gss.c.
.SS "#define TOKEN_WRAPPED   (1<<5)"
.PP
Definition at line 54 of file server-gss.c.
.SS "#define TOKEN_WRAPPED   (1<<5)"
.PP
Definition at line 54 of file server-gss.c.
.SS "#define TraduireAdresse(adresse, dest)"
.PP
\fBValue:\fP
.PP
.nf
sprintf( dest, '%d.%d.%d.%d',                   \
                  ( ntohl( adresse ) & 0xFF000000 ) >> 24, \
                  ( ntohl( adresse ) & 0x00FF0000 ) >> 16, \
                  ( ntohl( adresse ) & 0x0000FF00 ) >> 8,  \
                  ( ntohl( adresse ) & 0x000000FF ) )
.fi
.PP
Definition at line 28 of file server-gss.c.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"
.PP
Definition at line 271 of file server-gss.c.
.PP
References binding_port, creds, gss_service, GSS_SERVICE_DEFAUT, LENMSG, LOGFILE_DEFAUT, MAX_CONN, negociation_server(), obtention_creds(), options, TraduireAdresse, and utilisation.
.SS "int negociation_server (int sockfd)"
.PP
Definition at line 149 of file server-gss.c.
.PP
References creds, recv_token(), send_token(), sperror_gss(), and TOKEN_CONTEXT.
.PP
Referenced by main().
.SS "int obtention_creds (char * service_name, gss_cred_id_t * pcreds)"
.PP
Definition at line 87 of file server-gss.c.
.PP
References KEYTAB, and sperror_gss().
.PP
Referenced by main().
.SS "int recv_token (int s, int * flags, gss_buffer_t tok)"
.PP
Definition at line 218 of file tools-gss.c.
.SS "int send_token (int s, int flags, gss_buffer_t tok)"
.PP
Definition at line 149 of file tools-gss.c.
.PP
Referenced by negociation_client(), negociation_server(), recv_msg(), and send_msg().
.SS "void sperror_gss (char * str, OM_uint32 major, OM_uint32 minor)"
.PP
Definition at line 80 of file tools-gss.c.
.SH "Variable Documentation"
.PP 
.SS "unsigned short \fBbinding_port\fP = 0"
.PP
Definition at line 79 of file server-gss.c.
.PP
Referenced by main().
.SS "gss_cred_id_t \fBcreds\fP"
.PP
Definition at line 81 of file server-gss.c.
.PP
Referenced by main(), and negociation_server().
.SS "char \fBgss_service\fP[STRLEN]"
.PP
Definition at line 80 of file server-gss.c.
.PP
Referenced by main().
.SS "char \fBoptions\fP[] = 'hL:N:P:S:'"
.PP
Definition at line 66 of file server-gss.c.
.SS "char \fBrcsid\fP[] = '$Id: \fBserver\fP-gss.c,v 1.1 2005/04/13 13:45:49 deniel Exp $'"
.PP
Definition at line 6 of file server-gss.c.
.SS "char \fButilisation\fP[]"
.PP
\fBInitial value:\fP
.PP
.nf
 
'Utilisation: %s [-hLPM] \n'
'\t[-h]                   affiche cet aide en ligne\n'
'\t[-L <logfile>]         indique le fichier de log\n'
'\t[-N <NivDebug>]        indique le niveau de debug pour les journaux\n' 
'\t[-P <port ou service>] indique le port ou le service a utiliser\n'
'\t[-S <service Auth>]    le service utilise par ls GSS-API\n'
.fi
.PP
Definition at line 69 of file server-gss.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
