.TH "Svc.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Svc.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <sys/errno.h>\fP
.br
\fC#include 'Rpc.h'\fP
.br
\fC#include 'Clnt.h'\fP
.br
\fC#include 'Pmap_clnt.h'\fP
.br
\fC#include 'Svc.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBsvc_callout\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBNULL_SVC\fP   ((struct svc_callout *)0)"
.br
.ti -1c
.RI "#define \fBRQCRED_SIZE\fP   400"
.br
.ti -1c
.RI "#define \fBmax\fP(a, b)   (a > b ? a : b)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBXprt_register\fP (SVCXPRT *xprt)"
.br
.ti -1c
.RI "void \fBXprt_unregister\fP (SVCXPRT *xprt)"
.br
.ti -1c
.RI "bool_t \fBSvc_register\fP (SVCXPRT *xprt, u_long prog, u_long vers, void(*dispatch)(), int protocol)"
.br
.ti -1c
.RI "void \fBSvc_unregister\fP (u_long prog, u_long vers)"
.br
.ti -1c
.RI "void \fBSvc_getreqset\fP (fd_set *readfds)"
.br
.ti -1c
.RI "bool_t \fBSvc_sendreply\fP (register SVCXPRT *xprt, Xdrproc_t xdr_results, caddr_t xdr_location)"
.br
.ti -1c
.RI "void \fBSvcerr_noproc\fP (register SVCXPRT *xprt)"
.br
.ti -1c
.RI "void \fBSvcerr_decode\fP (register SVCXPRT *xprt)"
.br
.ti -1c
.RI "void \fBSvcerr_systemerr\fP (register SVCXPRT *xprt)"
.br
.ti -1c
.RI "void \fBSvcerr_auth\fP (SVCXPRT *xprt, enum Auth_stat why)"
.br
.ti -1c
.RI "void \fBSvcerr_weakauth\fP (SVCXPRT *xprt)"
.br
.ti -1c
.RI "void \fBSvcerr_noprog\fP (register SVCXPRT *xprt)"
.br
.ti -1c
.RI "void \fBSvcerr_progvers\fP (register SVCXPRT *xprt, u_long low_vers, u_long high_vers)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "SVCXPRT ** \fBXports\fP"
.br
.ti -1c
.RI "unsigned int \fBsvc_maxfd\fP"
.br
.ti -1c
.RI "fd_set \fBSvc_fdset\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define max(a, b)   (a > b ? a : b)"
.PP
Definition at line 16 of file Svc.c.
.PP
Referenced by Xprt_register().
.SS "#define NULL_SVC   ((struct svc_callout *)0)"
.PP
Definition at line 13 of file Svc.c.
.SS "#define RQCRED_SIZE   400"
.PP
Definition at line 14 of file Svc.c.
.SH "Function Documentation"
.PP 
.SS "void Svc_getreqset (fd_set * readfds)"
.PP
Definition at line 171 of file Svc.c.
.PP
References Svc_authenticate(), and Xports.
.PP
Referenced by Svc_run().
.SS "bool_t Svc_register (SVCXPRT * xprt, u_long prog, u_long vers, void(*)() dispatch, int protocol)"
.PP
Definition at line 103 of file Svc.c.
.PP
References Pmap_set().
.PP
Referenced by main().
.SS "bool_t Svc_sendreply (register SVCXPRT * xprt, Xdrproc_t xdr_results, caddr_t xdr_location)"
.PP
Definition at line 271 of file Svc.c.
.PP
Referenced by dispatch().
.SS "void Svc_unregister (u_long prog, u_long vers)"
.PP
Definition at line 134 of file Svc.c.
.PP
References Pmap_unset().
.SS "void Svcerr_auth (SVCXPRT * xprt, enum Auth_stat why)"
.PP
Definition at line 330 of file Svc.c.
.SS "void Svcerr_decode (register SVCXPRT * xprt)"
.PP
Definition at line 302 of file Svc.c.
.PP
Referenced by dispatch().
.SS "void Svcerr_noproc (register SVCXPRT * xprt)"
.PP
Definition at line 287 of file Svc.c.
.SS "void Svcerr_noprog (register SVCXPRT * xprt)"
.PP
Definition at line 353 of file Svc.c.
.SS "void Svcerr_progvers (register SVCXPRT * xprt, u_long low_vers, u_long high_vers)"
.PP
Definition at line 367 of file Svc.c.
.SS "void Svcerr_systemerr (register SVCXPRT * xprt)"
.PP
Definition at line 316 of file Svc.c.
.SS "void Svcerr_weakauth (SVCXPRT * xprt)"
.PP
Definition at line 344 of file Svc.c.
.PP
Referenced by dispatch().
.SS "void Xprt_register (SVCXPRT * xprt)"
.PP
Definition at line 51 of file Svc.c.
.PP
References max, Svc_fdset, svc_maxfd, and Xports.
.PP
Referenced by Svctcp_create(), and Svcudp_bufcreate().
.SS "void Xprt_unregister (SVCXPRT * xprt)"
.PP
Definition at line 76 of file Svc.c.
.PP
References Svc_fdset, svc_maxfd, and Xports.
.SH "Variable Documentation"
.PP 
.SS "fd_set \fBSvc_fdset\fP"
.PP
Definition at line 43 of file Svc.c.
.PP
Referenced by Xprt_register(), and Xprt_unregister().
.SS "unsigned int \fBsvc_maxfd\fP"
.PP
Definition at line 41 of file Svc.c.
.PP
Referenced by Xprt_register(), and Xprt_unregister().
.SS "SVCXPRT** \fBXports\fP"
.PP
Definition at line 11 of file Svc.c.
.PP
Referenced by Svc_getreqset(), Xprt_register(), and Xprt_unregister().
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
