.TH "Svc_raw.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Svc_raw.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Rpc.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSvcraw_private\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "SVCXPRT * \fBSvcraw_create\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "SVCXPRT* Svcraw_create ()"
.PP
Definition at line 100 of file Svc_raw.c.
.PP
References UDPMSGSIZE, and Xdrmem_create().
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
