.TH "Svc_auth_gss.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Svc_auth_gss.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include 'Rpc.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBg_OID_equal\fP(o1, o2)"
.br
.ti -1c
.RI "#define \fBOID_EQ\fP   1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "enum Auth_stat \fBSvcauth_gss\fP (struct Svc_req *rqst, struct Rpc_msg *msg)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define g_OID_equal(o1, o2)"
.PP
\fBValue:\fP
.PP
.nf
(((o1)->length == (o2)->length) && \
    ((o1)->elements != 0) && ((o2)->elements != 0) && \
    (memcmp((o1)->elements,(o2)->elements,(int) (o1)->length) == 0))
.fi
.PP
Definition at line 53 of file Svc_auth_gss.c.
.SS "#define OID_EQ   1"
.PP
Definition at line 57 of file Svc_auth_gss.c.
.SH "Function Documentation"
.PP 
.SS "enum Auth_stat Svcauth_gss (struct Svc_req * rqst, struct Rpc_msg * msg)"
.PP
Definition at line 730 of file Svc_auth_gss.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
