.TH "Svc_udp.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Svc_udp.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include 'Rpc.h'\fP
.br
\fC#include 'Clnt.h'\fP
.br
\fC#include 'Svc.h'\fP
.br
\fC#include <sys/socket.h>\fP
.br
\fC#include <errno.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSvcudp_data\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBUDPMSGSIZE\fP   8800"
.br
.ti -1c
.RI "#define \fBrpc_buffer\fP(xprt)   ((xprt)->xp_p1)"
.br
.ti -1c
.RI "#define \fBSu_data\fP(xprt)   ((struct \fBSvcudp_data\fP *)(xprt->xp_p2))"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "SVCXPRT * \fBSvcudp_bufcreate\fP (register int sock, u_int sendsz, u_int recvsz)"
.br
.ti -1c
.RI "SVCXPRT * \fBSvcudp_create\fP (int sock)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define rpc_buffer(xprt)   ((xprt)->xp_p1)"
.PP
Definition at line 16 of file Svc_udp.c.
.PP
Referenced by Svcudp_bufcreate().
.SS "#define Su_data(xprt)   ((struct \fBSvcudp_data\fP *)(xprt->xp_p2))"
.PP
Definition at line 44 of file Svc_udp.c.
.SS "#define UDPMSGSIZE   8800"
.PP
Definition at line 13 of file Svc_udp.c.
.PP
Referenced by Clnt_broadcast(), Clntraw_create(), Clntudp_create(), Svcraw_create(), and Svcudp_create().
.SH "Function Documentation"
.PP 
.SS "SVCXPRT* Svcudp_bufcreate (register int sock, u_int sendsz, u_int recvsz)"
.PP
Definition at line 60 of file Svc_udp.c.
.PP
References rpc_buffer, Svcudp_data::su_iosz, Svcudp_data::su_verfbody, Xdrmem_create(), and Xprt_register().
.PP
Referenced by Svcudp_create().
.SS "SVCXPRT* Svcudp_create (int sock)"
.PP
Definition at line 146 of file Svc_udp.c.
.PP
References Svcudp_bufcreate(), and UDPMSGSIZE.
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
