.TH "Svc_auth_none.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Svc_auth_none.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Rpc.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "enum Auth_stat \fBSvcauth_none\fP (struct Svc_req *rqst, struct Rpc_msg *msg)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "Svc_auth_ops \fBSvc_auth_none_ops\fP"
.br
.ti -1c
.RI "SVCAUTH \fBSvc_auth_none\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "enum Auth_stat Svcauth_none (struct Svc_req * rqst, struct Rpc_msg * msg)"
.PP
Definition at line 27 of file Svc_auth_none.c.
.SH "Variable Documentation"
.PP 
.SS "SVCAUTH \fBSvc_auth_none\fP"
.PP
\fBInitial value:\fP
.PP
.nf
 {
        &Svc_auth_none_ops,
        NULL,
}
.fi
.PP
Definition at line 12 of file Svc_auth_none.c.
.SS "struct Svc_auth_ops \fBSvc_auth_none_ops\fP"
.PP
\fBInitial value:\fP
.PP
.nf
 {
        Svcauth_none_wrap,
        Svcauth_none_wrap,
        Svcauth_none_destroy
}
.fi
.PP
Definition at line 6 of file Svc_auth_none.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
