.TH "Svc_tcp.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Svc_tcp.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sys/types.h>\fP
.br
\fC#include <sys/poll.h>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include 'Rpc.h'\fP
.br
\fC#include 'Clnt.h'\fP
.br
\fC#include 'Svc.h'\fP
.br
\fC#include <sys/socket.h>\fP
.br
\fC#include <errno.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtcp_rendezvous\fP"
.br
.ti -1c
.RI "struct \fBtcp_conn\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMAX_CONN\fP   32"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBReadtcp\fP ()"
.br
.ti -1c
.RI "int \fBWritetcp\fP ()"
.br
.ti -1c
.RI "SVCXPRT * \fBSvctcp_create\fP (register int sock, u_int sendsize, u_int recvsize)"
.br
.ti -1c
.RI "SVCXPRT * \fBSvcfd_create\fP (int fd, u_int sendsize, u_int recvsize)"
.br
.ti -1c
.RI "int \fBReadtcp\fP (register SVCXPRT *xprt, caddr_t buf, register int len)"
.br
.ti -1c
.RI "int \fBWritetcp\fP (register SVCXPRT *xprt, caddr_t buf, int len)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define MAX_CONN   32"
.PP
Definition at line 15 of file Svc_tcp.c.
.SH "Function Documentation"
.PP 
.SS "int Readtcp (register SVCXPRT * xprt, caddr_t buf, register int len)"
.PP
Definition at line 252 of file Svc_tcp.c.
.SS "int Readtcp ()"
.PP
.SS "SVCXPRT* Svcfd_create (int fd, u_int sendsize, u_int recvsize)"
.PP
Definition at line 153 of file Svc_tcp.c.
.SS "SVCXPRT* Svctcp_create (register int sock, u_int sendsize, u_int recvsize)"
.PP
Definition at line 87 of file Svc_tcp.c.
.PP
References MAX_CONN, tcp_rendezvous::recvsize, tcp_rendezvous::sendsize, and Xprt_register().
.PP
Referenced by main().
.SS "int Writetcp (register SVCXPRT * xprt, caddr_t buf, int len)"
.PP
Definition at line 290 of file Svc_tcp.c.
.SS "int Writetcp ()"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
