.TH "Svc_run.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Svc_run.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sys/param.h>\fP
.br
\fC#include <sys/errno.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <errno.h>\fP
.br
\fC#include 'Rpc.h'\fP
.br
\fC#include <sys/select.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSvc_run\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "fd_set \fBSvc_fdset\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Svc_run (void)"
.PP
Svc_run: boucle principale d'attente de la lib svc
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP aucun argument en entree
.RE
.PP
\fBReturns:\fP
.RS 4
rien du tout (void)
.RE
.PP
\fBSee also:\fP
.RS 4
\fBSvc_register()\fP 
.PP
\fBSvcudp_create()\fP 
.PP
\fBSvcudp_bufcreate()\fP 
.PP
\fBSvctcp_create()\fP 
.RE
.PP

.PP
Definition at line 65 of file Svc_run.c.
.PP
References Svc_getreqset().
.PP
Referenced by main().
.SH "Variable Documentation"
.PP 
.SS "fd_set \fBSvc_fdset\fP"
.PP
Definition at line 43 of file Svc.c.
.PP
Referenced by Xprt_register(), and Xprt_unregister().
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
