.TH "Svc_rpc_gss_data" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Svc_rpc_gss_data \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool_t \fBestablished\fP"
.br
.ti -1c
.RI "gss_ctx_id_t \fBctx\fP"
.br
.ti -1c
.RI "Rpc_gss_sec \fBsec\fP"
.br
.ti -1c
.RI "gss_buffer_desc \fBcname\fP"
.br
.ti -1c
.RI "u_int \fBseq\fP"
.br
.ti -1c
.RI "u_int \fBwin\fP"
.br
.ti -1c
.RI "u_int \fBseqlast\fP"
.br
.ti -1c
.RI "unsigned int \fBseqmask\fP"
.br
.ti -1c
.RI "gss_name_t \fBclient_name\fP"
.br
.ti -1c
.RI "rpc_gss_sec \fBsec\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "gss_name_t \fBSvc_rpc_gss_data::client_name\fP"
.PP
Definition at line 76 of file rpcsec_gss_server.natif.c.
.PP
Referenced by dispatch().
.SS "gss_buffer_desc \fBSvc_rpc_gss_data::cname\fP"
.PP
Definition at line 71 of file rpcsec_gss_server.natif.c.
.SS "gss_ctx_id_t \fBSvc_rpc_gss_data::ctx\fP"
.PP
Definition at line 69 of file rpcsec_gss_server.natif.c.
.SS "bool_t \fBSvc_rpc_gss_data::established\fP"
.PP
Definition at line 68 of file rpcsec_gss_server.natif.c.
.SS "struct rpc_gss_sec \fBSvc_rpc_gss_data::sec\fP"
.PP
Definition at line 70 of file rpcsec_gss_server.natif.c.
.SS "struct Rpc_gss_sec \fBSvc_rpc_gss_data::sec\fP"
.PP
Definition at line 69 of file rpcsec_gss_server.c.
.PP
Referenced by dispatch().
.SS "u_int \fBSvc_rpc_gss_data::seq\fP"
.PP
Definition at line 72 of file rpcsec_gss_server.natif.c.
.SS "u_int \fBSvc_rpc_gss_data::seqlast\fP"
.PP
Definition at line 74 of file rpcsec_gss_server.natif.c.
.SS "unsigned int \fBSvc_rpc_gss_data::seqmask\fP"
.PP
Definition at line 75 of file rpcsec_gss_server.natif.c.
.SS "u_int \fBSvc_rpc_gss_data::win\fP"
.PP
Definition at line 73 of file rpcsec_gss_server.natif.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
