.TH "Svc_auth.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Svc_auth.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Rpc.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBAUTH_MAX\fP   6"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "enum Auth_stat \fBSvcauth_none\fP ()"
.br
.ti -1c
.RI "enum Auth_stat \fBSvcauth_unix\fP ()"
.br
.ti -1c
.RI "enum Auth_stat \fBSvcauth_short\fP ()"
.br
.ti -1c
.RI "enum Auth_stat \fBSvcauth_gss\fP ()"
.br
.ti -1c
.RI "enum Auth_stat \fBSvc_authenticate\fP (register struct Svc_req *rqst, struct Rpc_msg *msg)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define AUTH_MAX   6"
.PP
Definition at line 70 of file Svc_auth.c.
.SH "Function Documentation"
.PP 
.SS "enum Auth_stat Svc_authenticate (register struct Svc_req * rqst, struct Rpc_msg * msg)"
.PP
Definition at line 90 of file Svc_auth.c.
.PP
Referenced by Svc_getreqset().
.SS "enum Auth_stat Svcauth_gss ()"
.PP
.SS "enum Auth_stat Svcauth_none ()"
.PP
.SS "enum Auth_stat Svcauth_short ()"
.PP
.SS "enum Auth_stat Svcauth_unix ()"
.PP
.SH "Variable Documentation"
.PP 
.SS "enum Auth_stat(* \fBauthenticator\fP)()"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
