.TH "Svc_auth_unix.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Svc_auth_unix.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include 'Rpc.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "enum Auth_stat \fBSvcauth_unix\fP (register struct Svc_req *rqst, register struct Rpc_msg *msg)"
.br
.ti -1c
.RI "enum Auth_stat \fBSvcauth_short\fP (struct Svc_req *rqst, struct Rpc_msg *msg)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "SVCAUTH \fBSvc_auth_none\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "enum Auth_stat Svcauth_short (struct Svc_req * rqst, struct Rpc_msg * msg)"
.PP
Definition at line 98 of file Svc_auth_unix.c.
.SS "enum Auth_stat Svcauth_unix (register struct Svc_req * rqst, register struct Rpc_msg * msg)"
.PP
Definition at line 21 of file Svc_auth_unix.c.
.PP
References Xdr_Authunix_parms().
.SH "Variable Documentation"
.PP 
.SS "SVCAUTH \fBSvc_auth_none\fP"
.PP
Definition at line 12 of file Svc_auth_none.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
