.TH "Svcudp_data" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Svcudp_data \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "u_int \fBsu_iosz\fP"
.br
.ti -1c
.RI "u_long \fBsu_xid\fP"
.br
.ti -1c
.RI "XDR \fBsu_xdrs\fP"
.br
.ti -1c
.RI "char \fBsu_verfbody\fP [MAX_AUTH_BYTES]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "u_int \fBSvcudp_data::su_iosz\fP"
.PP
Definition at line 39 of file Svc_udp.c.
.PP
Referenced by Svcudp_bufcreate().
.SS "char \fBSvcudp_data::su_verfbody\fP[MAX_AUTH_BYTES]"
.PP
Definition at line 42 of file Svc_udp.c.
.PP
Referenced by Svcudp_bufcreate().
.SS "XDR \fBSvcudp_data::su_xdrs\fP"
.PP
Definition at line 41 of file Svc_udp.c.
.SS "u_long \fBSvcudp_data::su_xid\fP"
.PP
Definition at line 40 of file Svc_udp.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
