.TH "tcp_rendezvous" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tcp_rendezvous \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "u_int \fBsendsize\fP"
.br
.ti -1c
.RI "u_int \fBrecvsize\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "u_int \fBtcp_rendezvous::recvsize\fP"
.PP
Definition at line 56 of file Svc_tcp.c.
.PP
Referenced by Svctcp_create().
.SS "u_int \fBtcp_rendezvous::sendsize\fP"
.PP
Definition at line 55 of file Svc_tcp.c.
.PP
Referenced by Svctcp_create().

.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
