.TH "tcp_conn" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tcp_conn \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "u_long \fBx_id\fP"
.br
.ti -1c
.RI "XDR \fBxdrs\fP"
.br
.ti -1c
.RI "char \fBverf_body\fP [MAX_AUTH_BYTES]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char \fBtcp_conn::verf_body\fP[MAX_AUTH_BYTES]"
.PP
Definition at line 63 of file Svc_tcp.c.
.SS "u_long \fBtcp_conn::x_id\fP"
.PP
Definition at line 61 of file Svc_tcp.c.
.SS "XDR \fBtcp_conn::xdrs\fP"
.PP
Definition at line 62 of file Svc_tcp.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
