.TH "tools-gss.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tools-gss.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sys/time.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <ctype.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <fcntl.h>\fP
.br
\fC#include <errno.h>\fP
.br
\fC#include <signal.h>\fP
.br
\fC#include <sys/socket.h>\fP
.br
\fC#include <netdb.h>\fP
.br
\fC#include <netinet/in.h>\fP
.br
\fC#include <netinet/tcp.h>\fP
.br
\fC#include <gssapi/gssapi.h>\fP
.br
\fC#include <gssapi/gssapi_generic.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBgss_wrap\fP   gss_seal"
.br
.ti -1c
.RI "#define \fBgss_unwrap\fP   gss_unseal"
.br
.ti -1c
.RI "#define \fBgss_get_mic\fP   gss_sign"
.br
.ti -1c
.RI "#define \fBgss_verify_mic\fP   gss_verify"
.br
.ti -1c
.RI "#define \fBgss_qop_t\fP   OM_uint32"
.br
.ti -1c
.RI "#define \fBTOKEN_NOOP\fP   (1<<0)"
.br
.ti -1c
.RI "#define \fBTOKEN_CONTEXT\fP   (1<<1)"
.br
.ti -1c
.RI "#define \fBTOKEN_DATA\fP   (1<<2)"
.br
.ti -1c
.RI "#define \fBTOKEN_MIC\fP   (1<<3)"
.br
.ti -1c
.RI "#define \fBTOKEN_CONTEXT_NEXT\fP   (1<<4)"
.br
.ti -1c
.RI "#define \fBTOKEN_WRAPPED\fP   (1<<5)"
.br
.ti -1c
.RI "#define \fBTOKEN_ENCRYPTED\fP   (1<<6)"
.br
.ti -1c
.RI "#define \fBTOKEN_SEND_MIC\fP   (1<<7)"
.br
.ti -1c
.RI "#define \fBTOKEN_NOOP\fP   (1<<0)"
.br
.ti -1c
.RI "#define \fBTOKEN_CONTEXT\fP   (1<<1)"
.br
.ti -1c
.RI "#define \fBTOKEN_DATA\fP   (1<<2)"
.br
.ti -1c
.RI "#define \fBTOKEN_MIC\fP   (1<<3)"
.br
.ti -1c
.RI "#define \fBTOKEN_CONTEXT_NEXT\fP   (1<<4)"
.br
.ti -1c
.RI "#define \fBTOKEN_WRAPPED\fP   (1<<5)"
.br
.ti -1c
.RI "#define \fBTOKEN_ENCRYPTED\fP   (1<<6)"
.br
.ti -1c
.RI "#define \fBTOKEN_SEND_MIC\fP   (1<<7)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsperror_gss_1\fP (char *str, OM_uint32 code, int type)"
.br
.ti -1c
.RI "void \fBsperror_gss\fP (char *str, OM_uint32 maj_stat, OM_uint32 min_stat)"
.br
.ti -1c
.RI "int \fBsend_token\fP (int s, int flags, gss_buffer_t tok)"
.br
.ti -1c
.RI "int \fBrecv_token\fP (int s, int *flags, gss_buffer_t tok)"
.br
.ti -1c
.RI "int \fBsend_msg\fP (int fd, char *msg, gss_ctx_id_t context, char *errbuff)"
.br
.ti -1c
.RI "int \fBrecv_msg\fP (int fd, char *msg, gss_ctx_id_t context, char *errbuff)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBrcsid_tools\fP [] = '$Id: tools-gss.c,v 1.1 2005/04/13 13:45:49 deniel Exp $'"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define gss_get_mic   gss_sign"
.PP
Definition at line 29 of file tools-gss.c.
.SS "#define gss_qop_t   OM_uint32"
.PP
Definition at line 31 of file tools-gss.c.
.SS "#define gss_unwrap   gss_unseal"
.PP
Definition at line 28 of file tools-gss.c.
.SS "#define gss_verify_mic   gss_verify"
.PP
Definition at line 30 of file tools-gss.c.
.SS "#define gss_wrap   gss_seal"
.PP
Definition at line 27 of file tools-gss.c.
.SS "#define TOKEN_CONTEXT   (1<<1)"
.PP
Definition at line 42 of file tools-gss.c.
.SS "#define TOKEN_CONTEXT   (1<<1)"
.PP
Definition at line 42 of file tools-gss.c.
.SS "#define TOKEN_CONTEXT_NEXT   (1<<4)"
.PP
Definition at line 45 of file tools-gss.c.
.SS "#define TOKEN_CONTEXT_NEXT   (1<<4)"
.PP
Definition at line 45 of file tools-gss.c.
.SS "#define TOKEN_DATA   (1<<2)"
.PP
Definition at line 43 of file tools-gss.c.
.SS "#define TOKEN_DATA   (1<<2)"
.PP
Definition at line 43 of file tools-gss.c.
.SS "#define TOKEN_ENCRYPTED   (1<<6)"
.PP
Definition at line 47 of file tools-gss.c.
.SS "#define TOKEN_ENCRYPTED   (1<<6)"
.PP
Definition at line 47 of file tools-gss.c.
.SS "#define TOKEN_MIC   (1<<3)"
.PP
Definition at line 44 of file tools-gss.c.
.SS "#define TOKEN_MIC   (1<<3)"
.PP
Definition at line 44 of file tools-gss.c.
.SS "#define TOKEN_NOOP   (1<<0)"
.PP
Definition at line 41 of file tools-gss.c.
.SS "#define TOKEN_NOOP   (1<<0)"
.PP
Definition at line 41 of file tools-gss.c.
.SS "#define TOKEN_SEND_MIC   (1<<7)"
.PP
Definition at line 48 of file tools-gss.c.
.SS "#define TOKEN_SEND_MIC   (1<<7)"
.PP
Definition at line 48 of file tools-gss.c.
.SS "#define TOKEN_WRAPPED   (1<<5)"
.PP
Definition at line 46 of file tools-gss.c.
.SS "#define TOKEN_WRAPPED   (1<<5)"
.PP
Definition at line 46 of file tools-gss.c.
.SH "Function Documentation"
.PP 
.SS "int recv_msg (int fd, char * msg, gss_ctx_id_t context, char * errbuff)"
.PP
Definition at line 348 of file tools-gss.c.
.PP
References gss_get_mic, gss_unwrap, recv_token(), send_token(), sperror_gss(), and TOKEN_MIC.
.SS "int recv_token (int s, int * flags, gss_buffer_t tok)"
.PP
Definition at line 218 of file tools-gss.c.
.PP
Referenced by negociation_client(), negociation_server(), recv_msg(), and send_msg().
.SS "int send_msg (int fd, char * msg, gss_ctx_id_t context, char * errbuff)"
.PP
Definition at line 285 of file tools-gss.c.
.PP
References gss_qop_t, gss_verify_mic, gss_wrap, recv_token(), send_token(), sperror_gss(), TOKEN_DATA, TOKEN_ENCRYPTED, and TOKEN_WRAPPED.
.SS "int send_token (int s, int flags, gss_buffer_t tok)"
.PP
Definition at line 149 of file tools-gss.c.
.PP
Referenced by negociation_client(), negociation_server(), recv_msg(), and send_msg().
.SS "void sperror_gss (char * str, OM_uint32 maj_stat, OM_uint32 min_stat)"
.PP
Definition at line 80 of file tools-gss.c.
.PP
References sperror_gss_1().
.PP
Referenced by negociation_client(), negociation_server(), obtention_creds(), recv_msg(), and send_msg().
.SS "void sperror_gss_1 (char * str, OM_uint32 code, int type)"
.PP
Definition at line 54 of file tools-gss.c.
.PP
Referenced by sperror_gss().
.SH "Variable Documentation"
.PP 
.SS "char \fBrcsid_tools\fP[] = '$Id: tools-gss.c,v 1.1 2005/04/13 13:45:49 deniel Exp $'"
.PP
Definition at line 7 of file tools-gss.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
