.TH "Xdr.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Xdr.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include 'Types.h'\fP
.br
\fC#include 'Xdr.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBXDR_FALSE\fP   ((long) 0)"
.br
.ti -1c
.RI "#define \fBXDR_TRUE\fP   ((long) 1)"
.br
.ti -1c
.RI "#define \fBLASTUNSIGNED\fP   ((u_int) 0-1)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBXdr_free\fP (Xdrproc_t proc, char *objp)"
.br
.ti -1c
.RI "bool_t \fBXdr_void\fP ()"
.br
.ti -1c
.RI "bool_t \fBXdr_int\fP (XDR *xdrs, int *ip)"
.br
.ti -1c
.RI "bool_t \fBXdr_u_int\fP (XDR *xdrs, u_int *up)"
.br
.ti -1c
.RI "bool_t \fBXdr_long\fP (XDR *xdrs, long *lp)"
.br
.ti -1c
.RI "bool_t \fBXdr_u_long\fP (XDR *xdrs, u_long *ulp)"
.br
.ti -1c
.RI "bool_t \fBXdr_int_32_t\fP (XDR *xdrs, int32_t *int32_p)"
.br
.ti -1c
.RI "bool_t \fBXdr_u_int_32_t\fP (XDR *xdrs, u_int32_t *u_int32_p)"
.br
.ti -1c
.RI "bool_t \fBXdr_short\fP (XDR *xdrs, short *sp)"
.br
.ti -1c
.RI "bool_t \fBXdr_u_short\fP (XDR *xdrs, u_short *usp)"
.br
.ti -1c
.RI "bool_t \fBXdr_int16_t\fP (XDR *xdrs, int16_t *int16_p)"
.br
.ti -1c
.RI "bool_t \fBXdr_u_int16_t\fP (XDR *xdrs, u_int16_t *u_int16_p)"
.br
.ti -1c
.RI "bool_t \fBXdr_char\fP (XDR *xdrs, char *cp)"
.br
.ti -1c
.RI "bool_t \fBXdr_u_char\fP (XDR *xdrs, u_char *cp)"
.br
.ti -1c
.RI "bool_t \fBXdr_bool\fP (XDR *xdrs, bool_t *bp)"
.br
.ti -1c
.RI "bool_t \fBXdr_enum\fP (XDR *xdrs, enum_t *ep)"
.br
.ti -1c
.RI "bool_t \fBXdr_opaque\fP (XDR *xdrs, caddr_t cp, u_int cnt)"
.br
.ti -1c
.RI "bool_t \fBXdr_bytes\fP (XDR *xdrs, char **cpp, u_int *sizep, u_int maxsize)"
.br
.ti -1c
.RI "bool_t \fBXdr_netobj\fP (XDR *xdrs, struct netobj *np)"
.br
.ti -1c
.RI "bool_t \fBXdr_union\fP (XDR *xdrs, enum_t *dscmp, char *unp, struct Xdr_discrim *choices, Xdrproc_t dfault)"
.br
.ti -1c
.RI "bool_t \fBXdr_string\fP (XDR *xdrs, char **cpp, u_int maxsize)"
.br
.ti -1c
.RI "bool_t \fBXdr_wrapstring\fP (XDR *xdrs, char **cpp)"
.br
.ti -1c
.RI "bool_t \fBXdr_u_longlong_t\fP (register XDR *xdrs, u_longlong_t *objp)"
.br
.ti -1c
.RI "bool_t \fBXdr_longlong_t\fP (register XDR *xdrs, longlong_t *objp)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define LASTUNSIGNED   ((u_int) 0-1)"
.PP
Definition at line 52 of file Xdr.c.
.PP
Referenced by Xdr_wrapstring().
.SS "#define XDR_FALSE   ((long) 0)"
.PP
Definition at line 50 of file Xdr.c.
.SS "#define XDR_TRUE   ((long) 1)"
.PP
Definition at line 51 of file Xdr.c.
.PP
Referenced by Xdr_bool().
.SH "Function Documentation"
.PP 
.SS "bool_t Xdr_bool (XDR * xdrs, bool_t * bp)"
.PP
Definition at line 407 of file Xdr.c.
.PP
References XDR_TRUE.
.PP
Referenced by Pmap_set(), Pmap_unset(), and Xdr_pointer().
.SS "bool_t Xdr_bytes (XDR * xdrs, char ** cpp, u_int * sizep, u_int maxsize)"
.PP
Definition at line 526 of file Xdr.c.
.PP
References Xdr_opaque(), and Xdr_u_int().
.PP
Referenced by Xdr_netobj(), and Xdr_opaque_auth().
.SS "bool_t Xdr_char (XDR * xdrs, char * cp)"
.PP
Definition at line 371 of file Xdr.c.
.PP
References Xdr_int().
.SS "bool_t Xdr_enum (XDR * xdrs, enum_t * ep)"
.PP
Definition at line 436 of file Xdr.c.
.PP
References Xdr_int(), Xdr_long(), and Xdr_short().
.PP
Referenced by Xdr_accepted_reply(), Xdr_callhdr(), Xdr_callmsg(), Xdr_opaque_auth(), Xdr_rejected_reply(), Xdr_replymsg(), and Xdr_union().
.SS "void Xdr_free (Xdrproc_t proc, char * objp)"
.PP
Definition at line 64 of file Xdr.c.
.SS "bool_t Xdr_int (XDR * xdrs, int * ip)"
.PP
Definition at line 91 of file Xdr.c.
.PP
Referenced by dispatch(), main(), Xdr_char(), and Xdr_enum().
.SS "bool_t Xdr_int16_t (XDR * xdrs, int16_t * int16_p)"
.PP
Definition at line 312 of file Xdr.c.
.SS "bool_t Xdr_int_32_t (XDR * xdrs, int32_t * int32_p)"
.PP
Definition at line 193 of file Xdr.c.
.SS "bool_t Xdr_long (XDR * xdrs, long * lp)"
.PP
Definition at line 151 of file Xdr.c.
.PP
Referenced by Xdr_enum().
.SS "bool_t Xdr_longlong_t (register XDR * xdrs, longlong_t * objp)"
.PP
Definition at line 787 of file Xdr.c.
.PP
References Xdr_u_longlong_t().
.SS "bool_t Xdr_netobj (XDR * xdrs, struct netobj * np)"
.PP
Definition at line 596 of file Xdr.c.
.PP
References Xdr_bytes().
.SS "bool_t Xdr_opaque (XDR * xdrs, caddr_t cp, u_int cnt)"
.PP
Definition at line 468 of file Xdr.c.
.PP
Referenced by Xdr_bytes(), Xdr_callmsg(), Xdr_des_block(), and Xdr_string().
.SS "bool_t Xdr_short (XDR * xdrs, short * sp)"
.PP
Definition at line 253 of file Xdr.c.
.PP
Referenced by Xdr_enum().
.SS "bool_t Xdr_string (XDR * xdrs, char ** cpp, u_int maxsize)"
.PP
Definition at line 665 of file Xdr.c.
.PP
References Xdr_opaque(), and Xdr_u_int().
.PP
Referenced by Xdr_Authunix_parms(), and Xdr_wrapstring().
.SS "bool_t Xdr_u_char (XDR * xdrs, u_char * cp)"
.PP
Definition at line 389 of file Xdr.c.
.PP
References Xdr_u_int().
.SS "bool_t Xdr_u_int (XDR * xdrs, u_int * up)"
.PP
Definition at line 120 of file Xdr.c.
.PP
Referenced by Xdr_array(), Xdr_Authunix_parms(), Xdr_bytes(), Xdr_callmsg(), Xdr_string(), and Xdr_u_char().
.SS "bool_t Xdr_u_int16_t (XDR * xdrs, u_int16_t * u_int16_p)"
.PP
Definition at line 341 of file Xdr.c.
.SS "bool_t Xdr_u_int_32_t (XDR * xdrs, u_int32_t * u_int32_p)"
.PP
Definition at line 223 of file Xdr.c.
.SS "bool_t Xdr_u_long (XDR * xdrs, u_long * ulp)"
.PP
Definition at line 172 of file Xdr.c.
.PP
Referenced by Xdr_Authunix_parms(), Xdr_callmsg(), Xdr_Pmap(), Xdr_Rmtcall_args(), and Xdr_Rmtcallres().
.SS "bool_t Xdr_u_longlong_t (register XDR * xdrs, u_longlong_t * objp)"
.PP
Definition at line 745 of file Xdr.c.
.PP
Referenced by Xdr_longlong_t().
.SS "bool_t Xdr_u_short (XDR * xdrs, u_short * usp)"
.PP
Definition at line 282 of file Xdr.c.
.PP
Referenced by Pmap_getport(), and Xdr_Authunix_parms().
.SS "bool_t Xdr_union (XDR * xdrs, enum_t * dscmp, char * unp, struct Xdr_discrim * choices, Xdrproc_t dfault)"
.PP
Definition at line 616 of file Xdr.c.
.PP
References Xdr_enum().
.PP
Referenced by Xdr_replymsg().
.SS "bool_t Xdr_void ()"
.PP
Definition at line 78 of file Xdr.c.
.PP
Referenced by dispatch().
.SS "bool_t Xdr_wrapstring (XDR * xdrs, char ** cpp)"
.PP
Definition at line 737 of file Xdr.c.
.PP
References LASTUNSIGNED, and Xdr_string().
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
