.TH "Xdr_rec.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Xdr_rec.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include 'Types.h'\fP
.br
\fC#include 'Xdr.h'\fP
.br
\fC#include <netinet/in.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBrec_strm\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBLAST_FRAG\fP   ((u_int32_t)(1 << 31))"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBrec_strm\fP \fBRECSTREAM\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBXdrrec_create\fP (XDR *xdrs, u_int sendsize, u_int recvsize, caddr_t tcp_handle, int(*readit)(), int(*writeit)())"
.br
.ti -1c
.RI "bool_t \fBXdrrec_skiprecord\fP (XDR *xdrs)"
.br
.ti -1c
.RI "bool_t \fBXdrrec_eof\fP (XDR *xdrs)"
.br
.ti -1c
.RI "bool_t \fBXdrrec_endofrecord\fP (XDR *xdrs, bool_t sendnow)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define LAST_FRAG   ((u_int32_t)(1 << 31))"
.PP
Definition at line 97 of file Xdr_rec.c.
.PP
Referenced by Xdrrec_endofrecord().
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBrec_strm\fP  \fBRECSTREAM\fP"
.PP
Referenced by Xdrrec_create(), Xdrrec_endofrecord(), Xdrrec_eof(), and Xdrrec_skiprecord().
.SH "Function Documentation"
.PP 
.SS "void Xdrrec_create (XDR * xdrs, u_int sendsize, u_int recvsize, caddr_t tcp_handle, int (*)() readit, int (*)() writeit)"
.PP
Definition at line 136 of file Xdr_rec.c.
.PP
References rec_strm::fbtbc, rec_strm::frag_header, rec_strm::frag_sent, rec_strm::in_base, rec_strm::in_boundry, rec_strm::in_finger, rec_strm::in_size, rec_strm::last_frag, rec_strm::out_base, rec_strm::out_boundry, rec_strm::out_finger, rec_strm::readit, RECSTREAM, rec_strm::recvsize, rec_strm::sendsize, rec_strm::tcp_handle, rec_strm::the_buffer, and rec_strm::writeit.
.PP
Referenced by Clnttcp_create().
.SS "bool_t Xdrrec_endofrecord (XDR * xdrs, bool_t sendnow)"
.PP
Definition at line 475 of file Xdr_rec.c.
.PP
References rec_strm::frag_header, rec_strm::frag_sent, LAST_FRAG, rec_strm::out_boundry, rec_strm::out_finger, and RECSTREAM.
.SS "bool_t Xdrrec_eof (XDR * xdrs)"
.PP
Definition at line 451 of file Xdr_rec.c.
.PP
References rec_strm::fbtbc, rec_strm::in_boundry, rec_strm::in_finger, rec_strm::last_frag, and RECSTREAM.
.SS "bool_t Xdrrec_skiprecord (XDR * xdrs)"
.PP
Definition at line 429 of file Xdr_rec.c.
.PP
References rec_strm::fbtbc, rec_strm::last_frag, and RECSTREAM.
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
