.TH "Xdr_array.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Xdr_array.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include 'Types.h'\fP
.br
\fC#include 'Xdr.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool_t \fBXdr_array\fP (XDR *xdrs, caddr_t *addrp, u_int *sizep, u_int maxsize, u_int elsize, Xdrproc_t elproc)"
.br
.ti -1c
.RI "bool_t \fBXdr_vector\fP (XDR *xdrs, char *basep, u_int nelem, u_int elemsize, Xdrproc_t xdr_elem)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool_t Xdr_array (XDR * xdrs, caddr_t * addrp, u_int * sizep, u_int maxsize, u_int elsize, Xdrproc_t elproc)"
.PP
Definition at line 59 of file Xdr_array.c.
.PP
References Xdr_u_int().
.PP
Referenced by Xdr_Authunix_parms().
.SS "bool_t Xdr_vector (XDR * xdrs, char * basep, u_int nelem, u_int elemsize, Xdrproc_t xdr_elem)"
.PP
Definition at line 143 of file Xdr_array.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
