.TH "Xdr_stdio.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Xdr_stdio.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Types.h'\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include 'Xdr.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBXdrstdio_create\fP (XDR *xdrs, FILE *file, enum Xdr_op op)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Xdrstdio_create (XDR * xdrs, FILE * file, enum Xdr_op op)"
.PP
Definition at line 80 of file Xdr_stdio.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
