.TH "Xdr_float.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Xdr_float.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <sys/types.h>\fP
.br
\fC#include <sys/param.h>\fP
.br
\fC#include 'Types.h'\fP
.br
\fC#include 'Xdr.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool_t \fBXdr_float\fP (XDR *xdrs, float *fp)"
.br
.ti -1c
.RI "bool_t \fBXdr_double\fP (XDR *xdrs, double *dp)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool_t Xdr_double (XDR * xdrs, double * dp)"
.PP
Definition at line 204 of file Xdr_float.c.
.SS "bool_t Xdr_float (XDR * xdrs, float * fp)"
.PP
Definition at line 97 of file Xdr_float.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
