.TH "Xdr_reference.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Xdr_reference.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include 'Types.h'\fP
.br
\fC#include 'Xdr.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool_t \fBXdr_reference\fP (XDR *xdrs, caddr_t *pp, u_int size, Xdrproc_t proc)"
.br
.ti -1c
.RI "bool_t \fBXdr_pointer\fP (XDR *xdrs, char **objpp, u_int obj_size, Xdrproc_t xdr_obj)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool_t Xdr_pointer (XDR * xdrs, char ** objpp, u_int obj_size, Xdrproc_t xdr_obj)"
.PP
Definition at line 123 of file Xdr_reference.c.
.PP
References Xdr_bool(), and Xdr_reference().
.SS "bool_t Xdr_reference (XDR * xdrs, caddr_t * pp, u_int size, Xdrproc_t proc)"
.PP
Definition at line 59 of file Xdr_reference.c.
.PP
Referenced by Xdr_pointer(), and Xdr_Rmtcallres().
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
