.TH "Xdr_mem.c" 3 "22 Dec 2006" "Version 0.1" "RPCSEC_GSS Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Xdr_mem.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string.h>\fP
.br
\fC#include 'Types.h'\fP
.br
\fC#include 'Xdr.h'\fP
.br
\fC#include <netinet/in.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBXdrmem_create\fP (XDR *xdrs, caddr_t addr, u_int size, enum Xdr_op op)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Xdrmem_create (XDR * xdrs, caddr_t addr, u_int size, enum Xdr_op op)"
.PP
Definition at line 90 of file Xdr_mem.c.
.PP
Referenced by Authnone_create(), Authunix_create(), Clnt_broadcast(), Clntraw_create(), Clnttcp_create(), Clntudp_bufcreate(), Svcraw_create(), and Svcudp_bufcreate().
.SH "Author"
.PP 
Generated automatically by Doxygen for RPCSEC_GSS Library from the source code.
