nfs3_Readdirplus.c File Reference
Routines used for managing the NFS4 COMPOUND functions.
#include <stdio.h>
#include <string.h>
#include <pthread.h>
#include <fcntl.h>
#include <sys/file.h>
#include `HashData.h`
#include `HashTable.h`
#include <rpc/types.h>
#include <rpc/rpc.h>
#include <rpc/auth.h>
#include <rpc/pmap_clnt.h>
#include `log_functions.h`
#include `stuff_alloc.h`
#include `nfs23.h`
#include `nfs4.h`
#include `mount.h`
#include `nfs_core.h`
#include `cache_inode.h`
#include `cache_content.h`
#include `nfs_exports.h`
#include `nfs_creds.h`
#include `nfs_proto_functions.h`
#include `nfs_tools.h`
#include `nfs_file_handle.h`
#include `nfs_proto_tools.h`
Defines
#define RES_READDIRPLUS_REPLY pres $\rightarrow$ res_readdirplus3.READDIRPLUS3res_u.resok.reply
#define PRESREADDIRPLUSREPLY resp $\rightarrow$ res_readdirplus3.READDIRPLUS3res_u.resok.reply
Functions
int nfs3_Readdirplus (nfs_arg_t *parg, exportlist_t *pexport, fsal_op_context_t *pcontext, cache_inode_client_t *pclient, hash_table_t *ht, struct svc_req *preq, nfs_res_t *pres)
void nfs3_Readdirplus_Free (nfs_res_t *resp)
Detailed Description
Routines used for managing the NFS4 COMPOUND functions.
Author:
Author deniel
Date:
Date 2005/11/28 17:02:49
Version:
Revision 1.37
nfs3_Readdirplus.c(p.) : Routines used for managing the NFS4 COMPOUND functions.
Definition in file nfs3_Readdirplus.c.
Define Documentation
#define PRESREADDIRPLUSREPLY resp $\rightarrow$ res_readdirplus3.READDIRPLUS3res_u.resok.reply
Referenced by nfs3_Readdirplus_Free().
#define RES_READDIRPLUS_REPLY pres $\rightarrow$ res_readdirplus3.READDIRPLUS3res_u.resok.reply
Referenced by nfs3_Readdirplus().
Function Documentation
int nfs3_Readdirplus (nfs_arg_t * parg, exportlist_t * pexport, fsal_op_context_t * pcontext, cache_inode_client_t * pclient, hash_table_t * ht, struct svc_req * preq, nfs_res_t * pres)
nfs_Readdir: The NFS PROC2 and PROC3 READDIR
Implements the NFS PROC CREATE function (for V2 and V3).
Parameters:
parg [IN] pointer to nfs arguments union
pexport [IN] pointer to nfs export list
pcontext [IN] credentials to be used for this request
pclient [INOUT] client resource to be used
ht [INOUT] cache inode hash table
preq [IN] pointer to SVC request related to this call
pres [OUT] pointer to the structure to contain the result of the call
Returns: NFS_REQ_OK if successfull
 NFS_REQ_DROP if failed but retryable
 NFS_REQ_FAILED if failed and not retryable.
Definition at line 147 of file nfs3_Readdirplus.c.
References nfs3_Errno(), nfs_FhandleToCache(), nfs_RetryableError(), nfs_SetFailedStatus(), nfs_SetPostOpAttr(), and RES_READDIRPLUS_REPLY.
void nfs3_Readdirplus_Free (nfs_res_t * resp)
nfs3_Readdirplus_Free: Frees the result structure allocated for nfs3_Readdirplus.
Frees the result structure allocated for nfs3_Readdirplus.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 732 of file nfs3_Readdirplus.c.
References PRESREADDIRPLUSREPLY.