nfs4_op_rename.c File Reference
Routines used for managing the NFS4 COMPOUND functions.
#include <stdio.h>
#include <string.h>
#include <pthread.h>
#include <fcntl.h>
#include <sys/file.h>
#include `HashData.h`
#include `HashTable.h`
#include <rpc/types.h>
#include <rpc/rpc.h>
#include <rpc/auth.h>
#include <rpc/pmap_clnt.h>
#include `log_functions.h`
#include `stuff_alloc.h`
#include `nfs23.h`
#include `nfs4.h`
#include `mount.h`
#include `nfs_core.h`
#include `cache_inode.h`
#include `cache_content.h`
#include `nfs_exports.h`
#include `nfs_creds.h`
#include `nfs_proto_functions.h`
#include `nfs_tools.h`
#include `nfs_file_handle.h`
Defines
#define arg_RENAME4 op $\rightarrow$ nfs_argop4_u.oprename
#define res_RENAME4 resp $\rightarrow$ nfs_resop4_u.oprename
Functions
int nfs4_op_rename (struct nfs_argop4 *op, compound_data_t *data, struct nfs_resop4 *resp)
void nfs4_op_rename_Free (RENAME4res *resp)
Detailed Description
Routines used for managing the NFS4 COMPOUND functions.
Author:
Author deniel
Date:
Date 2005/11/28 17:02:51
Version:
Revision 1.15
nfs4_op_rename.c(p.) : Routines used for managing the NFS4 COMPOUND functions.
Definition in file nfs4_op_rename.c.
Define Documentation
#define arg_RENAME4 op $\rightarrow$ nfs_argop4_u.oprename
nfs4_op_rename: The NFS4_OP_RENAME operation.
This functions handles the NFS4_OP_RENAME operation in NFSv4. This function can be called only from nfs4_Compound
Parameters:
op [IN] pointer to nfs4_op arguments
data [INOUT] Pointer to the compound request's data
resp [IN] Pointer to nfs4_op results
Returns: NFS4_OK if successfull, other values show an error.
Definition at line 138 of file nfs4_op_rename.c.
Referenced by nfs4_op_rename().
#define res_RENAME4 resp $\rightarrow$ nfs_resop4_u.oprename
Definition at line 139 of file nfs4_op_rename.c.
Referenced by nfs4_op_rename().
Function Documentation
int nfs4_op_rename (struct nfs_argop4 * op, compound_data_t * data, struct nfs_resop4 * resp)
Definition at line 141 of file nfs4_op_rename.c.
References arg_RENAME4, nfs4_Errno(), nfs4_SetCompoundExport(), and res_RENAME4.
void nfs4_op_rename_Free (RENAME4res * resp)
nfs4_op_rename_Free: frees what was allocared to handle nfs4_op_rename.
Frees what was allocared to handle nfs4_op_rename.
Parameters:
resp [INOUT] Pointer to nfs4_op results
Returns: nothing (void function)
Definition at line 514 of file nfs4_op_rename.c.
Referenced by nfs4_Compound_Free().