nfs4_op_putfh.c File Reference
Routines used for managing the NFS4_OP_PUTFH operation.
#include <stdio.h>
#include <string.h>
#include <pthread.h>
#include <fcntl.h>
#include <sys/file.h>
#include `HashData.h`
#include `HashTable.h`
#include <rpc/types.h>
#include <rpc/rpc.h>
#include <rpc/auth.h>
#include <rpc/pmap_clnt.h>
#include `log_functions.h`
#include `stuff_alloc.h`
#include `nfs23.h`
#include `nfs4.h`
#include `mount.h`
#include `nfs_core.h`
#include `cache_inode.h`
#include `cache_content.h`
#include `nfs_exports.h`
#include `nfs_creds.h`
#include `nfs_proto_functions.h`
#include `nfs_tools.h`
#include `nfs_proto_tools.h`
Defines
#define arg_PUTFH4 op $\rightarrow$ nfs_argop4_u.opputfh
#define res_PUTFH4 resp $\rightarrow$ nfs_resop4_u.opputfh
Functions
int nfs4_op_putfh (struct nfs_argop4 *op, compound_data_t *data, struct nfs_resop4 *resp)
void nfs4_op_putfh_Free (PUTFH4res *resp)
Detailed Description
Routines used for managing the NFS4_OP_PUTFH operation.
Author:
Author deniel
Date:
Date 2006/01/16 16:25:44
Version:
Revision 1.11
nfs4_op_putfh.c(p.) : Routines used for managing the NFS4_OP_PUTFH operation.
Definition in file nfs4_op_putfh.c.
Define Documentation
#define arg_PUTFH4 op $\rightarrow$ nfs_argop4_u.opputfh
Definition at line 124 of file nfs4_op_putfh.c.
Referenced by nfs4_op_putfh().
#define res_PUTFH4 resp $\rightarrow$ nfs_resop4_u.opputfh
Definition at line 125 of file nfs4_op_putfh.c.
Referenced by nfs4_op_putfh().
Function Documentation
int nfs4_op_putfh (struct nfs_argop4 * op, compound_data_t * data, struct nfs_resop4 * resp)
nfs4_op_putfh: The NFS4_OP_PUTFH operation
Sets the current FH with the value given in argument.
Parameters:
op [IN] pointer to nfs4_op arguments
data [INOUT] Pointer to the compound request's data
resp [IN] Pointer to nfs4_op results
Returns: NFS4_OK if successfull, other values show an error.
See also: all the nfs4_op_<*> function
nfs4_Compound(p.)
Definition at line 144 of file nfs4_op_putfh.c.
References arg_PUTFH4, nfs4_AllocateFH(), nfs4_SetCompoundExport(), nfs_FhandleToCache(), and res_PUTFH4.
void nfs4_op_putfh_Free (PUTFH4res * resp)
nfs4_op_create_Free: frees what was allocared to handle nfs4_op_create.
Frees what was allocared to handle nfs4_op_create.
Parameters:
resp [INOUT] Pointer to nfs4_op results
Returns: nothing (void function)
Definition at line 272 of file nfs4_op_putfh.c.
Referenced by nfs4_Compound_Free().