nfs4_op_putrootfh.c File Reference
Routines used for managing the NFS4_OP_PUTROOTFH operation.
#include <stdio.h>
#include <string.h>
#include <pthread.h>
#include <fcntl.h>
#include <sys/file.h>
#include `HashData.h`
#include `HashTable.h`
#include <rpc/types.h>
#include <rpc/rpc.h>
#include <rpc/auth.h>
#include <rpc/pmap_clnt.h>
#include `log_functions.h`
#include `stuff_alloc.h`
#include `nfs23.h`
#include `nfs4.h`
#include `mount.h`
#include `nfs_core.h`
#include `cache_inode.h`
#include `cache_content.h`
#include `nfs_exports.h`
#include `nfs_creds.h`
#include `nfs_proto_functions.h`
#include `nfs_file_handle.h`
#include `nfs_tools.h`
Defines
#define arg_PUTROOTFH4 op $\rightarrow$ nfs_argop4_u.opputrootfh
#define res_PUTROOTFH4 resp $\rightarrow$ nfs_resop4_u.opputrootfh
Functions
int CreateROOTFH4 (nfs_fh4 *fh, compound_data_t *data)
int nfs4_op_putrootfh (struct nfs_argop4 *op, compound_data_t *data, struct nfs_resop4 *resp)
void nfs4_op_putrootfh_Free (PUTROOTFH4res *resp)
Detailed Description
Routines used for managing the NFS4_OP_PUTROOTFH operation.
Author:
Author deniel
Date:
Date 2005/12/20 10:52:14
Version:
Revision 1.13
nfs4_op_restorefh.c(p.) : Routines used for managing the NFS4_OP_PUTROOTFH operation.
Definition in file nfs4_op_putrootfh.c.
Define Documentation
#define arg_PUTROOTFH4 op $\rightarrow$ nfs_argop4_u.opputrootfh
nfs4_op_putroothfh: The NFS4_OP_PUTROOTFH operation.
This functions handles the NFS4_OP_PUTROOTFH operation in NFSv4. This function can be called only from nfs4_Compound.
Parameters:
op [IN] pointer to nfs4_op arguments
data [INOUT] Pointer to the compound request's data
resp [IN] Pointer to nfs4_op results
Returns: NFS4_OK if successfull, other values show an error.
See also: CreateROOTFH4(p.)
Definition at line 184 of file nfs4_op_putrootfh.c.
#define res_PUTROOTFH4 resp $\rightarrow$ nfs_resop4_u.opputrootfh
Definition at line 185 of file nfs4_op_putrootfh.c.
Referenced by nfs4_op_putrootfh().
Function Documentation
int CreateROOTFH4 (nfs_fh4 * fh, compound_data_t * data)
CreateROOTFH4: create the pseudo fs root filehandle .
Creates the pseudo fs root filehandle .
Parameters:
fh [OUT] the file handle to be built.
data [INOUT] request compound data
Returns: NFS4_OK is successful, NFS4ERR_BADHANDLE otherwise (for an error).
See also: nfs4_op_putrootfh(p.)
Definition at line 140 of file nfs4_op_putrootfh.c.
References nfs4_AllocateFH(), and nfs4_PseudoToFhandle().
Referenced by nfs4_op_putrootfh().
int nfs4_op_putrootfh (struct nfs_argop4 * op, compound_data_t * data, struct nfs_resop4 * resp)
Definition at line 187 of file nfs4_op_putrootfh.c.
References CreateROOTFH4(), nfs4_AllocateFH(), and res_PUTROOTFH4.
void nfs4_op_putrootfh_Free (PUTROOTFH4res * resp)
nfs4_op_putrootfh_Free: frees what was allocared to handle nfs4_op_putrootfh.
Frees what was allocared to handle nfs4_op_putrootfh.
Parameters:
resp [INOUT] Pointer to nfs4_op results
Returns: nothing (void function)
Definition at line 276 of file nfs4_op_putrootfh.c.