nfs4_op_create.c File Reference
Routines used for managing the NFS4 COMPOUND functions.
#include <stdio.h>
#include <string.h>
#include <pthread.h>
#include <fcntl.h>
#include <sys/file.h>
#include `HashData.h`
#include `HashTable.h`
#include <rpc/types.h>
#include <rpc/rpc.h>
#include <rpc/auth.h>
#include <rpc/pmap_clnt.h>
#include `log_functions.h`
#include `stuff_alloc.h`
#include `nfs23.h`
#include `nfs4.h`
#include `mount.h`
#include `nfs_core.h`
#include `cache_inode.h`
#include `cache_content.h`
#include `nfs_exports.h`
#include `nfs_creds.h`
#include `nfs_proto_functions.h`
#include `nfs_tools.h`
#include `nfs_file_handle.h`
Defines
#define arg_CREATE4 op $\rightarrow$ nfs_argop4_u.opcreate
#define res_CREATE4 resp $\rightarrow$ nfs_resop4_u.opcreate
Functions
int nfs4_op_create (struct nfs_argop4 *op, compound_data_t *data, struct nfs_resop4 *resp)
void nfs4_op_create_Free (CREATE4res *resp)
Detailed Description
Routines used for managing the NFS4 COMPOUND functions.
Author:
Author deniel
Date:
Date 2005/11/28 17:02:50
Version:
Revision 1.18
nfs4_op_create.c(p.) : Routines used for managing the NFS4 COMPOUND functions.
Definition in file nfs4_op_create.c.
Define Documentation
#define arg_CREATE4 op $\rightarrow$ nfs_argop4_u.opcreate
nfs4_op_create: NFS4_OP_CREATE, creates a non-regular entry.
NFS4_OP_CREATE, creates a non-regular entry.
Parameters:
op [IN] pointer to nfs4_op arguments
data [INOUT] Pointer to the compound request's data
resp [IN] Pointer to nfs4_op results
Returns: NFS4_OK if successfull, other values show an error.
Definition at line 138 of file nfs4_op_create.c.
Referenced by nfs4_op_create().
#define res_CREATE4 resp $\rightarrow$ nfs_resop4_u.opcreate
Definition at line 139 of file nfs4_op_create.c.
Referenced by nfs4_op_create().
Function Documentation
int nfs4_op_create (struct nfs_argop4 * op, compound_data_t * data, struct nfs_resop4 * resp)
Definition at line 141 of file nfs4_op_create.c.
References arg_CREATE4, nfs4_AllocateFH(), nfs4_Errno(), nfs4_Fattr_Check_Access(), nfs4_Fattr_Supported(), nfs4_Fattr_To_FSAL_attr(), res_CREATE4, and utf82str().
void nfs4_op_create_Free (CREATE4res * resp)
nfs4_op_create_Free: frees what was allocared to handle nfs4_op_create.
Frees what was allocared to handle nfs4_op_create.
Parameters:
resp [INOUT] Pointer to nfs4_op results
Returns: nothing (void function)
Definition at line 612 of file nfs4_op_create.c.
Referenced by nfs4_Compound_Free().