nfs4_op_open.c File Reference
Routines used for managing the NFS4 COMPOUND functions.
#include <stdio.h>
#include <string.h>
#include <pthread.h>
#include <fcntl.h>
#include <sys/file.h>
#include `HashData.h`
#include `HashTable.h`
#include <rpc/types.h>
#include <rpc/rpc.h>
#include <rpc/auth.h>
#include <rpc/pmap_clnt.h>
#include `log_functions.h`
#include `stuff_alloc.h`
#include `nfs23.h`
#include `nfs4.h`
#include `mount.h`
#include `nfs_core.h`
#include `cache_inode.h`
#include `cache_content.h`
#include `nfs_exports.h`
#include `nfs_creds.h`
#include `nfs_proto_functions.h`
#include `nfs_proto_tools.h`
#include `nfs_tools.h`
#include `nfs_file_handle.h`
Defines
#define arg_OPEN4 op $\rightarrow$ nfs_argop4_u.opopen
#define res_OPEN4 resp $\rightarrow$ nfs_resop4_u.opopen
Functions
int nfs4_op_open (struct nfs_argop4 *op, compound_data_t *data, struct nfs_resop4 *resp)
void nfs4_op_open_Free (OPEN4res *resp)
Variables
nfs_parameter_t nfs_param
time_t ServerBootTime
Detailed Description
Routines used for managing the NFS4 COMPOUND functions.
Author:
Author deniel
Date:
Date 2005/11/28 17:02:51
Version:
Revision 1.18
nfs4_op_open.c(p.) : Routines used for managing the NFS4 COMPOUND functions.
Definition in file nfs4_op_open.c.
Define Documentation
#define arg_OPEN4 op $\rightarrow$ nfs_argop4_u.opopen
Definition at line 144 of file nfs4_op_open.c.
Referenced by nfs4_op_open().
#define res_OPEN4 resp $\rightarrow$ nfs_resop4_u.opopen
Definition at line 145 of file nfs4_op_open.c.
Referenced by nfs4_op_open().
Function Documentation
int nfs4_op_open (struct nfs_argop4 * op, compound_data_t * data, struct nfs_resop4 * resp)
Todo : BUGAZOMEU: remove this line if(arg_OPEN4.openhow.openflag4_u.how.mode != UNCHECKED4 && cache_status != CACHE_INODE_ENTRY_EXISTS)
Definition at line 147 of file nfs4_op_open.c.
References arg_OPEN4, nfs4_AllocateFH(), nfs4_Errno(), nfs4_Fattr_Check_Access(), nfs4_Fattr_Supported(), nfs4_Fattr_To_FSAL_attr(), nfs_FhandleToCache(), and res_OPEN4.
void nfs4_op_open_Free (OPEN4res * resp)
nfs4_op_open_Free: frees what was allocared to handle nfs4_op_open.
Frees what was allocared to handle nfs4_op_open.
Parameters:
resp [INOUT] Pointer to nfs4_op results
Returns: nothing (void function)
Definition at line 791 of file nfs4_op_open.c.
Referenced by nfs4_Compound_Free().
Variable Documentation
nfs_parameter_t nfs_param
time_t ServerBootTime
nfs4_op_open: NFS4_OP_OPEN, opens and eventually creates a regular file.
NFS4_OP_OPEN, opens and eventually creates a regular file.
Parameters:
op [IN] pointer to nfs4_op arguments
data [INOUT] Pointer to the compound request's data
resp [IN] Pointer to nfs4_op results
Returns: NFS4_OK if successfull, other values show an error.
Referenced by nfs4_op_readdir_pseudo(), nfs4_op_setclientid(), and nfs4_PseudoToFattr().