nfs4_op_link.c File Reference
Routines used for managing the NFS4 COMPOUND functions.
#include <stdio.h>
#include <string.h>
#include <pthread.h>
#include <fcntl.h>
#include <sys/file.h>
#include `HashData.h`
#include `HashTable.h`
#include <rpc/types.h>
#include <rpc/rpc.h>
#include <rpc/auth.h>
#include <rpc/pmap_clnt.h>
#include `log_functions.h`
#include `stuff_alloc.h`
#include `nfs23.h`
#include `nfs4.h`
#include `mount.h`
#include `nfs_core.h`
#include `cache_inode.h`
#include `cache_content.h`
#include `nfs_exports.h`
#include `nfs_creds.h`
#include `nfs_proto_functions.h`
#include `nfs_tools.h`
#include `nfs_file_handle.h`
Defines
#define arg_LINK4 op $\rightarrow$ nfs_argop4_u.oplink
#define res_LINK4 resp $\rightarrow$ nfs_resop4_u.oplink
Functions
int nfs4_op_link (struct nfs_argop4 *op, compound_data_t *data, struct nfs_resop4 *resp)
void nfs4_op_link_Free (LINK4res *resp)
Detailed Description
Routines used for managing the NFS4 COMPOUND functions.
Author:
Author deniel
Date:
Date 2005/11/28 17:02:50
Version:
Revision 1.11
nfs4_op_link.c(p.) : Routines used for managing the NFS4 COMPOUND functions.
Definition in file nfs4_op_link.c.
Define Documentation
#define arg_LINK4 op $\rightarrow$ nfs_argop4_u.oplink
nfs4_op_link: The NFS4_OP_LINK operation.
This functions handles the NFS4_OP_LINK operation in NFSv4. This function can be called only from nfs4_Compound.
Parameters:
op [IN] pointer to nfs4_op arguments
data [INOUT] Pointer to the compound request's data
resp [IN] Pointer to nfs4_op results
Returns: NFS4_OK if successfull, other values show an error.
Definition at line 138 of file nfs4_op_link.c.
Referenced by nfs4_op_link().
#define res_LINK4 resp $\rightarrow$ nfs_resop4_u.oplink
Definition at line 139 of file nfs4_op_link.c.
Referenced by nfs4_op_link().
Function Documentation
int nfs4_op_link (struct nfs_argop4 * op, compound_data_t * data, struct nfs_resop4 * resp)
Definition at line 141 of file nfs4_op_link.c.
References arg_LINK4, nfs4_Errno(), nfs4_SetCompoundExport(), and res_LINK4.
void nfs4_op_link_Free (LINK4res * resp)
nfs4_op_link_Free: frees what was allocared to handle nfs4_op_link.
Frees what was allocared to handle nfs4_op_link.
Parameters:
resp [INOUT] Pointer to nfs4_op results
Returns: nothing (void function)
Definition at line 328 of file nfs4_op_link.c.
Referenced by nfs4_Compound_Free().