nfs4_op_readdir.c File Reference
#include <stdio.h>
#include <string.h>
#include <pthread.h>
#include <fcntl.h>
#include <sys/file.h>
#include `HashData.h`
#include `HashTable.h`
#include <rpc/types.h>
#include <rpc/rpc.h>
#include <rpc/auth.h>
#include <rpc/pmap_clnt.h>
#include `log_functions.h`
#include `stuff_alloc.h`
#include `nfs23.h`
#include `nfs4.h`
#include `mount.h`
#include `nfs_core.h`
#include `cache_inode.h`
#include `cache_content.h`
#include `nfs_exports.h`
#include `nfs_creds.h`
#include `nfs_proto_functions.h`
#include `nfs_file_handle.h`
Defines
#define arg_READDIR4 op $\rightarrow$ nfs_argop4_u.opreaddir
#define res_READDIR4 resp $\rightarrow$ nfs_resop4_u.opreaddir
Functions
int nfs4_op_readdir (struct nfs_argop4 *op, compound_data_t *data, struct nfs_resop4 *resp)
void nfs4_op_readdir_Free (READDIR4res *resp)
Variables
time_t ServerBootTime
Define Documentation
#define arg_READDIR4 op $\rightarrow$ nfs_argop4_u.opreaddir
Definition at line 109 of file nfs4_op_readdir.c.
Referenced by nfs4_op_readdir(), and nfs4_op_readdir_pseudo().
#define res_READDIR4 resp $\rightarrow$ nfs_resop4_u.opreaddir
Definition at line 110 of file nfs4_op_readdir.c.
Referenced by nfs4_op_readdir(), and nfs4_op_readdir_pseudo().
Function Documentation
int nfs4_op_readdir (struct nfs_argop4 * op, compound_data_t * data, struct nfs_resop4 * resp)
nfs4_op_readdir: The NFS4_OP_READDIR.
Implements the NFS4_OP_READDIR. If fh is a pseudo FH, then call is routed to routine nfs4_op_readdir_pseudo
Parameters:
op [IN] pointer to nfs4_op arguments
data [INOUT] Pointer to the compound request's data
resp [IN] Pointer to nfs4_op results
Returns: NFS4_OK if ok, any other value show an error.
Definition at line 126 of file nfs4_op_readdir.c.
References arg_READDIR4, nfs4_AllocateFH(), nfs4_Errno(), nfs4_Fattr_Check_Access_Bitmap(), nfs4_FSALattr_To_Fattr(), nfs4_op_readdir_pseudo(), res_READDIR4, and str2utf8().
Referenced by nfs4_op_readdir_pseudo().
void nfs4_op_readdir_Free (READDIR4res * resp)
nfs4_op_readdir_Free: frees what was allocared to handle nfs4_op_readdir.
Frees what was allocared to handle nfs4_op_readdir.
Parameters:
resp [INOUT] Pointer to nfs4_op results
Returns: nothing (void function)
Definition at line 463 of file nfs4_op_readdir.c.
Referenced by nfs4_Compound_Free().
Variable Documentation
time_t ServerBootTime