nfs4_op_lookup.c File Reference
Routines used for managing the NFS4 COMPOUND functions.
#include <stdio.h>
#include <string.h>
#include <pthread.h>
#include <fcntl.h>
#include <sys/file.h>
#include `HashData.h`
#include `HashTable.h`
#include <rpc/types.h>
#include <rpc/rpc.h>
#include <rpc/auth.h>
#include <rpc/pmap_clnt.h>
#include `log_functions.h`
#include `stuff_alloc.h`
#include `nfs23.h`
#include `nfs4.h`
#include `mount.h`
#include `nfs_core.h`
#include `cache_inode.h`
#include `cache_content.h`
#include `nfs_exports.h`
#include `nfs_creds.h`
#include `nfs_proto_functions.h`
#include `nfs_tools.h`
#include `nfs_proto_tools.h`
Defines
#define arg_LOOKUP4 op $\rightarrow$ nfs_argop4_u.oplookup
#define res_LOOKUP4 resp $\rightarrow$ nfs_resop4_u.oplookup
Functions
int nfs4_op_lookup (struct nfs_argop4 *op, compound_data_t *data, struct nfs_resop4 *resp)
void nfs4_op_lookup_Free (LOOKUP4res *resp)
Detailed Description
Routines used for managing the NFS4 COMPOUND functions.
Author:
Author deniel
Date:
Date 2006/01/16 16:25:44
Version:
Revision 1.18
nfs4_op_lookup.c(p.) : Routines used for managing the NFS4 COMPOUND functions.
Definition in file nfs4_op_lookup.c.
Define Documentation
#define arg_LOOKUP4 op $\rightarrow$ nfs_argop4_u.oplookup
nfs4_op_lookup: looks up into theFSAL.
looks up into the FSAL. If a junction is crossed, does what is necessary.
Parameters:
op [IN] pointer to nfs4_op arguments
data [INOUT] Pointer to the compound request's data
resp [IN] Pointer to nfs4_op results
Returns: NFS4_OK if successfull, other values show an error.
Definition at line 137 of file nfs4_op_lookup.c.
Referenced by nfs4_op_lookup(), and nfs4_op_lookup_pseudo().
#define res_LOOKUP4 resp $\rightarrow$ nfs_resop4_u.oplookup
Definition at line 138 of file nfs4_op_lookup.c.
Referenced by nfs4_op_lookup(), and nfs4_op_lookup_pseudo().
Function Documentation
int nfs4_op_lookup (struct nfs_argop4 * op, compound_data_t * data, struct nfs_resop4 * resp)
Definition at line 140 of file nfs4_op_lookup.c.
References arg_LOOKUP4, nfs4_Errno(), nfs4_op_lookup_pseudo(), and res_LOOKUP4.
void nfs4_op_lookup_Free (LOOKUP4res * resp)
nfs4_op_lookup_Free: frees what was allocared to handle nfs4_op_lookup.
Frees what was allocared to handle nfs4_op_lookup.
Parameters:
resp [INOUT] Pointer to nfs4_op results
Returns: nothing (void function)
Definition at line 305 of file nfs4_op_lookup.c.
Referenced by nfs4_Compound_Free().