nfs4_op_nverify.c File Reference
Routines used for managing the NFS4 COMPOUND functions.
#include <stdio.h>
#include <string.h>
#include <pthread.h>
#include <fcntl.h>
#include <sys/file.h>
#include `HashData.h`
#include `HashTable.h`
#include <rpc/types.h>
#include <rpc/rpc.h>
#include <rpc/auth.h>
#include <rpc/pmap_clnt.h>
#include `log_functions.h`
#include `stuff_alloc.h`
#include `nfs23.h`
#include `nfs4.h`
#include `mount.h`
#include `nfs_core.h`
#include `cache_inode.h`
#include `cache_content.h`
#include `nfs_exports.h`
#include `nfs_creds.h`
#include `nfs_proto_functions.h`
#include `nfs_tools.h`
#include `nfs_file_handle.h`
Defines
#define arg_NVERIFY4 op $\rightarrow$ nfs_argop4_u.opnverify
#define res_NVERIFY4 resp $\rightarrow$ nfs_resop4_u.opnverify
Functions
int nfs4_op_nverify (struct nfs_argop4 *op, compound_data_t *data, struct nfs_resop4 *resp)
void nfs4_op_nverify_Free (NVERIFY4res *resp)
Detailed Description
Routines used for managing the NFS4 COMPOUND functions.
Author:
Author deniel
Date:
Date 2006/01/05 15:14:52
Version:
Revision 1.12
nfs4_op_nverify.c(p.) : Routines used for managing the NFS4 COMPOUND functions.
Definition in file nfs4_op_nverify.c.
Define Documentation
#define arg_NVERIFY4 op $\rightarrow$ nfs_argop4_u.opnverify
nfs4_op_nverify: Implemtation of NFS4_OP_NVERIFY
Implemtation of NFS4_OP_NVERIFY. This is usually made for cache validator implementation.
Parameters:
op [IN] pointer to nfs4_op arguments
data [INOUT] Pointer to the compound request's data
resp [IN] Pointer to nfs4_op results
Returns: NFS4_OK
Definition at line 140 of file nfs4_op_nverify.c.
Referenced by nfs4_op_nverify().
#define res_NVERIFY4 resp $\rightarrow$ nfs_resop4_u.opnverify
Definition at line 141 of file nfs4_op_nverify.c.
Referenced by nfs4_op_nverify().
Function Documentation
int nfs4_op_nverify (struct nfs_argop4 * op, compound_data_t * data, struct nfs_resop4 * resp)
Definition at line 143 of file nfs4_op_nverify.c.
References arg_NVERIFY4, nfs4_Fattr_Check_Access(), nfs4_Fattr_cmp(), nfs4_Fattr_Supported(), nfs4_FSALattr_To_Fattr(), and res_NVERIFY4.
void nfs4_op_nverify_Free (NVERIFY4res * resp)
nfs4_op_nverify_Free: frees what was allocared to handle nfs4_op_nverify.
Frees what was allocared to handle nfs4_op_nverify.
Parameters:
resp [INOUT] Pointer to nfs4_op results
Returns: nothing (void function)
Definition at line 253 of file nfs4_op_nverify.c.
Referenced by nfs4_Compound_Free().