nfs4_op_setattr.c File Reference
Routines used for managing the NFS4 COMPOUND functions.
#include <stdio.h>
#include <string.h>
#include <pthread.h>
#include <fcntl.h>
#include <sys/file.h>
#include `HashData.h`
#include `HashTable.h`
#include <rpc/types.h>
#include <rpc/rpc.h>
#include <rpc/auth.h>
#include <rpc/pmap_clnt.h>
#include `log_functions.h`
#include `stuff_alloc.h`
#include `nfs23.h`
#include `nfs4.h`
#include `mount.h`
#include `nfs_core.h`
#include `cache_inode.h`
#include `cache_content.h`
#include `nfs_exports.h`
#include `nfs_creds.h`
#include `nfs_proto_functions.h`
#include `nfs_tools.h`
#include `nfs_file_handle.h`
Defines
#define arg_SETATTR4 op $\rightarrow$ nfs_argop4_u.opsetattr
#define res_SETATTR4 resp $\rightarrow$ nfs_resop4_u.opsetattr
Functions
int nfs4_op_setattr (struct nfs_argop4 *op, compound_data_t *data, struct nfs_resop4 *resp)
void nfs4_op_setattr_Free (SETATTR4res *resp)
Detailed Description
Routines used for managing the NFS4 COMPOUND functions.
Author:
Author deniel
Date:
Date 2005/11/28 17:02:52
Version:
Revision 1.15
nfs4_op_setattr.c(p.) : Routines used for managing the NFS4 COMPOUND functions.
Definition in file nfs4_op_setattr.c.
Define Documentation
#define arg_SETATTR4 op $\rightarrow$ nfs_argop4_u.opsetattr
nfs4_op_rename: The NFS4_OP_SETATTR operation.
This functions handles the NFS4_OP_SETATTR operation in NFSv4. This function can be called only from nfs4_Compound
Parameters:
op [IN] pointer to nfs4_op arguments
data [INOUT] Pointer to the compound request's data
resp [IN] Pointer to nfs4_op results
Returns: NFS4_OK if successfull, other values show an error.
Definition at line 139 of file nfs4_op_setattr.c.
Referenced by nfs4_op_setattr().
#define res_SETATTR4 resp $\rightarrow$ nfs_resop4_u.opsetattr
Definition at line 140 of file nfs4_op_setattr.c.
Referenced by nfs4_op_setattr().
Function Documentation
int nfs4_op_setattr (struct nfs_argop4 * op, compound_data_t * data, struct nfs_resop4 * resp)
Definition at line 142 of file nfs4_op_setattr.c.
References arg_SETATTR4, nfs4_Errno(), nfs4_Fattr_Check_Access(), nfs4_Fattr_Supported(), nfs4_Fattr_To_FSAL_attr(), and res_SETATTR4.
void nfs4_op_setattr_Free (SETATTR4res * resp)
nfs4_op_setattr_Free: frees what was allocared to handle nfs4_op_setattr.
Frees what was allocared to handle nfs4_op_setattr.
Parameters:
resp [INOUT] Pointer to nfs4_op results
Returns: nothing (void function)
Definition at line 327 of file nfs4_op_setattr.c.