nfs4_op_putpubfh.c File Reference
Routines used for managing the NFS4_OP_PUTPUBFH operation.
#include <stdio.h>
#include <string.h>
#include <pthread.h>
#include <fcntl.h>
#include <sys/file.h>
#include `HashData.h`
#include `HashTable.h`
#include <rpc/types.h>
#include <rpc/rpc.h>
#include <rpc/auth.h>
#include <rpc/pmap_clnt.h>
#include `log_functions.h`
#include `stuff_alloc.h`
#include `nfs23.h`
#include `nfs4.h`
#include `mount.h`
#include `nfs_core.h`
#include `cache_inode.h`
#include `cache_content.h`
#include `nfs_exports.h`
#include `nfs_creds.h`
#include `nfs_proto_functions.h`
#include `nfs_tools.h`
#include `nfs_proto_tools.h`
Defines
#define arg_PUTPUBFH4 op $\rightarrow$ nfs_argop4_u.opputpubfh
#define res_PUTPUBFH4 resp $\rightarrow$ nfs_resop4_u.opputpubfh
Functions
int CreatePUBFH4 (nfs_fh4 *fh, compound_data_t *data)
int nfs4_op_putpubfh (struct nfs_argop4 *op, compound_data_t *data, struct nfs_resop4 *resp)
void nfs4_op_putpubfh_Free (PUTPUBFH4res *resp)
Detailed Description
Routines used for managing the NFS4_OP_PUTPUBFH operation.
Author:
Author deniel
Date:
Date 2005/11/28 17:02:51
Version:
Revision 1.11
nfs4_op_getfh.c(p.) : Routines used for managing the NFS4_OP_PUTPUBFH operation.
Definition in file nfs4_op_putpubfh.c.
Define Documentation
#define arg_PUTPUBFH4 op $\rightarrow$ nfs_argop4_u.opputpubfh
nfs4_op_putpubfh: The NFS4_OP_PUTFH operation
Sets the publicFH for the current compound requests as the current FH.
Parameters:
op [IN] pointer to nfs4_op arguments
data [INOUT] Pointer to the compound request's data
resp [IN] Pointer to nfs4_op results
Returns: NFS4_OK if successfull, other values show an error.
See also: all the nfs4_op_<*> function
nfs4_Compound(p.)
Definition at line 185 of file nfs4_op_putpubfh.c.
#define res_PUTPUBFH4 resp $\rightarrow$ nfs_resop4_u.opputpubfh
Definition at line 186 of file nfs4_op_putpubfh.c.
Referenced by nfs4_op_putpubfh().
Function Documentation
int CreatePUBFH4 (nfs_fh4 * fh, compound_data_t * data)
CreatePUBFH4: create the pseudo fs public filehandle .
Creates the pseudo fs root filehandle .
Parameters:
fh [OUT] the file handle to be built.
data [INOUT] request compound data
Returns: NFS4_OK is successful, NFS4ERR_BADHANDLE otherwise (for an error).
See also: nfs4_op_putrootfh(p.)
Definition at line 141 of file nfs4_op_putpubfh.c.
References nfs4_AllocateFH(), and nfs4_PseudoToFhandle().
Referenced by nfs4_op_putpubfh().
int nfs4_op_putpubfh (struct nfs_argop4 * op, compound_data_t * data, struct nfs_resop4 * resp)
Definition at line 188 of file nfs4_op_putpubfh.c.
References CreatePUBFH4(), nfs4_AllocateFH(), and res_PUTPUBFH4.
void nfs4_op_putpubfh_Free (PUTPUBFH4res * resp)
nfs4_op_putpubfh_Free: frees what was allocared to handle nfs4_op_putpubfh.
Frees what was allocared to handle nfs4_op_putpubfh.
Parameters:
resp [INOUT] Pointer to nfs4_op results
Returns: nothing (void function)
Definition at line 266 of file nfs4_op_putpubfh.c.