nfs4_op_lookupp.c File Reference
Routines used for managing the NFS4 COMPOUND functions.
#include <stdio.h>
#include <string.h>
#include <pthread.h>
#include <fcntl.h>
#include <sys/file.h>
#include `HashData.h`
#include `HashTable.h`
#include <rpc/types.h>
#include <rpc/rpc.h>
#include <rpc/auth.h>
#include <rpc/pmap_clnt.h>
#include `log_functions.h`
#include `stuff_alloc.h`
#include `nfs23.h`
#include `nfs4.h`
#include `mount.h`
#include `nfs_core.h`
#include `cache_inode.h`
#include `cache_content.h`
#include `nfs_exports.h`
#include `nfs_creds.h`
#include `nfs_proto_functions.h`
#include `nfs_tools.h`
#include `nfs_file_handle.h`
Defines
#define arg_LOOKUPP4 op $\rightarrow$ nfs_argop4_u.oplookupp
#define res_LOOKUPP4 resp $\rightarrow$ nfs_resop4_u.oplookupp
Functions
int nfs4_op_lookupp (struct nfs_argop4 *op, compound_data_t *data, struct nfs_resop4 *resp)
void nfs4_op_lookupp_Free (LOOKUPP4res *resp)
Detailed Description
Routines used for managing the NFS4 COMPOUND functions.
Author:
Author deniel
Date:
Date 2006/01/16 16:25:44
Version:
Revision 1.16
nfs4_op_lookupp.c(p.) : Routines used for managing the NFS4 COMPOUND functions.
Definition in file nfs4_op_lookupp.c.
Define Documentation
#define arg_LOOKUPP4 op $\rightarrow$ nfs_argop4_u.oplookupp
nfs4_op_lookupp: looks up for the parent into theFSAL.
looks up for the parent into the FSAL.In NFSv4 this is to be used instead of `LOOKUP('..')` .
Parameters:
op [IN] pointer to nfs4_op arguments
data [INOUT] Pointer to the compound request's data
resp [IN] Pointer to nfs4_op results
Returns: NFS4_OK if successfull, other values show an error.
Definition at line 168 of file nfs4_op_lookupp.c.
#define res_LOOKUPP4 resp $\rightarrow$ nfs_resop4_u.oplookupp
Definition at line 169 of file nfs4_op_lookupp.c.
Referenced by nfs4_op_lookupp(), and nfs4_op_lookupp_pseudo().
Function Documentation
int nfs4_op_lookupp (struct nfs_argop4 * op, compound_data_t * data, struct nfs_resop4 * resp)
Definition at line 171 of file nfs4_op_lookupp.c.
References nfs4_Errno(), nfs4_op_lookupp_pseudo(), nfs4_SetCompoundExport(), and res_LOOKUPP4.
void nfs4_op_lookupp_Free (LOOKUPP4res * resp)
nfs4_op_lookupp_Free: frees what was allocared to handle nfs4_op_lookupp.
Frees what was allocared to handle nfs4_op_lookupp.
Parameters:
resp [INOUT] Pointer to nfs4_op results
Returns: nothing (void function)
Definition at line 295 of file nfs4_op_lookupp.c.
Referenced by nfs4_Compound_Free().