nfs4_Compound.c File Reference
Routines used for managing the NFS4 COMPOUND functions.
#include <stdio.h>
#include <string.h>
#include <pthread.h>
#include <fcntl.h>
#include <sys/file.h>
#include `HashData.h`
#include `HashTable.h`
#include <rpc/types.h>
#include <rpc/rpc.h>
#include <rpc/auth.h>
#include <rpc/pmap_clnt.h>
#include `log_functions.h`
#include `stuff_alloc.h`
#include `nfs23.h`
#include `nfs4.h`
#include `mount.h`
#include `nfs_core.h`
#include `cache_inode.h`
#include `cache_content.h`
#include `nfs_exports.h`
#include `nfs_creds.h`
#include `nfs_proto_functions.h`
Classes
struct nfs4_op_desc__
Defines
#define COMPOUND4_ARRAY parg $\rightarrow$ arg_compound4.argarray
Typedefs
typedef nfs4_op_desc__ nfs4_op_desc_t
Functions
int nfs4_Compound (nfs_arg_t *parg, exportlist_t *pexport, fsal_op_context_t *pcontext, cache_inode_client_t *pclient, hash_table_t *ht, struct svc_req *preq, nfs_res_t *pres)
void nfs4_Compound_Free (nfs_res_t *pres)
void compound_data_Free (compound_data_t *data)
Variables
const int optab4index []
Detailed Description
Routines used for managing the NFS4 COMPOUND functions.
Author:
Author deniel
Date:
Date 2006/01/16 16:25:44
Version:
Revision 1.24
nfs4_Compound.c(p.) : Routines used for managing the NFS4 COMPOUND functions.
Definition in file nfs4_Compound.c.
Define Documentation
#define COMPOUND4_ARRAY parg $\rightarrow$ arg_compound4.argarray
Referenced by nfs4_Compound().
Typedef Documentation
typedef struct nfs4_op_desc__ nfs4_op_desc_t
Function Documentation
void compound_data_Free (compound_data_t * data)
compound_data_Free: Mem_Frees the compound data structure.
Mem_Frees the compound data structure..
Parameters:
data pointer to be Mem_Freed
Returns: nothing (void function).
See also: nfs4_op_getfh(p.)
Definition at line 548 of file nfs4_Compound.c.
int nfs4_Compound (nfs_arg_t * parg, exportlist_t * pexport, fsal_op_context_t * pcontext, cache_inode_client_t * pclient, hash_table_t * ht, struct svc_req * preq, nfs_res_t * pres)
nfs4_COMPOUND: The NFS PROC4 COMPOUND
Implements the NFS PROC4 COMPOUND. This routine processes the content of the nfsv4 operation list and composes the result. On this aspect it is a little similar to a dispatch routine. Operation and functions necessary to process them are defined in array optab4 .
Parameters:
parg [IN] generic nfs arguments
pexportlist [IN] the full export list
pcontex [IN] context for the FSAL (unused but kept for nfs functions prototype homogeneity)
pclient [INOUT] client resource for request management
ht [INOUT] cache inode hash table
preq [IN] RPC svc request
pres [OUT] generic nfs reply
See also: nfs4_op_<*> functions
nfs4_GetPseudoFs(p.)
Todo BUGAZOMEU: Reminder: Stats on NFSv4 operations are to be set here
Definition at line 202 of file nfs4_Compound.c.
References COMPOUND4_ARRAY, nfs4_op_desc__::funct, nfs4_op_desc__::name, nfs4_GetPseudoFs(), optab4index, utf82str(), and nfs4_op_desc__::val.
void nfs4_Compound_Free (nfs_res_t * pres)
nfs4_Compound_Free: Mem_Free the result for NFS4PROC_COMPOUND
Mem_Free the result for NFS4PROC_COMPOUND.
Parameters:
resp pointer to be Mem_Freed
Returns: nothing (void function).
See also: nfs4_op_getfh(p.)
Definition at line 382 of file nfs4_Compound.c.
References nfs4_op_access_Free(), nfs4_op_close_Free(), nfs4_op_commit_Free(), nfs4_op_create_Free(), nfs4_op_delegpurge_Free(), nfs4_op_delegreturn_Free(), nfs4_op_getattr_Free(), nfs4_op_illegal_Free(), nfs4_op_link_Free(), nfs4_op_lock_Free(), nfs4_op_lockt_Free(), nfs4_op_locku_Free(), nfs4_op_lookup_Free(), nfs4_op_lookupp_Free(), nfs4_op_nverify_Free(), nfs4_op_open_confirm_Free(), nfs4_op_open_downgrade_Free(), nfs4_op_open_Free(), nfs4_op_openattr_Free(), nfs4_op_putfh_Free(), nfs4_op_read_Free(), nfs4_op_readdir_Free(), nfs4_op_release_lockowner_Free(), nfs4_op_remove_Free(), nfs4_op_rename_Free(), nfs4_op_renew_Free(), nfs4_op_secinfo_Free(), nfs4_op_setclientid_Free(), nfs4_op_verify_Free(), and nfs4_op_write_Free().
Variable Documentation
const int optab4index[]
Initial value:
 { 0,0,0,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,
                            24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39 }
Definition at line 133 of file nfs4_Compound.c.
Referenced by nfs4_Compound().