nfs4_op_getattr.c File Reference
Routines used for managing the NFS4 COMPOUND functions.
#include <stdio.h>
#include <string.h>
#include <pthread.h>
#include <fcntl.h>
#include <sys/file.h>
#include `HashData.h`
#include `HashTable.h`
#include <rpc/types.h>
#include <rpc/rpc.h>
#include <rpc/auth.h>
#include <rpc/pmap_clnt.h>
#include `log_functions.h`
#include `stuff_alloc.h`
#include `nfs23.h`
#include `nfs4.h`
#include `mount.h`
#include `nfs_core.h`
#include `cache_inode.h`
#include `cache_content.h`
#include `nfs_exports.h`
#include `nfs_creds.h`
#include `nfs_proto_functions.h`
#include `nfs_tools.h`
#include `nfs_proto_tools.h`
#include `nfs_file_handle.h`
Defines
#define arg_GETATTR4 op $\rightarrow$ nfs_argop4_u.opgetattr
#define res_GETATTR4 resp $\rightarrow$ nfs_resop4_u.opgetattr
#define res_FATTR4 res_GETATTR4.GETATTR4res_u.resok4.obj_attributes
Functions
int nfs4_op_getattr (struct nfs_argop4 *op, compound_data_t *data, struct nfs_resop4 *resp)
void nfs4_op_getattr_Free (GETATTR4res *resp)
Detailed Description
Routines used for managing the NFS4 COMPOUND functions.
Author:
Author deniel
Date:
Date 2006/01/05 15:14:52
Version:
Revision 1.17
nfs4_op_getattr.c(p.) : Routines used for managing the NFS4 COMPOUND functions.
Definition in file nfs4_op_getattr.c.
Define Documentation
#define arg_GETATTR4 op $\rightarrow$ nfs_argop4_u.opgetattr
Definition at line 125 of file nfs4_op_getattr.c.
Referenced by nfs4_op_getattr(), and nfs4_op_getattr_pseudo().
#define res_FATTR4 res_GETATTR4.GETATTR4res_u.resok4.obj_attributes
Definition at line 127 of file nfs4_op_getattr.c.
#define res_GETATTR4 resp $\rightarrow$ nfs_resop4_u.opgetattr
Definition at line 126 of file nfs4_op_getattr.c.
Referenced by nfs4_op_getattr(), and nfs4_op_getattr_pseudo().
Function Documentation
int nfs4_op_getattr (struct nfs_argop4 * op, compound_data_t * data, struct nfs_resop4 * resp)
nfs4_op_getattr: Gets attributes for an entry in the FSAL.
Gets attributes for an entry in the FSAL.
Parameters:
op [IN] pointer to nfs4_op arguments
data [INOUT] Pointer to the compound request's data
resp [IN] Pointer to nfs4_op results
Returns: NFS4_OK
Definition at line 143 of file nfs4_op_getattr.c.
References arg_GETATTR4, nfs4_Errno(), nfs4_Fattr_Check_Access_Bitmap(), nfs4_Fattr_Supported_Bitmap(), nfs4_FSALattr_To_Fattr(), nfs4_op_getattr_pseudo(), and res_GETATTR4.
void nfs4_op_getattr_Free (GETATTR4res * resp)
nfs4_op_getattr_Free: frees what was allocared to handle nfs4_op_getattr.
Frees what was allocared to handle nfs4_op_getattr.
Parameters:
resp [INOUT] Pointer to nfs4_op results
Returns: nothing (void function)
Definition at line 250 of file nfs4_op_getattr.c.
Referenced by nfs4_Compound_Free().