nfs_Write.c File Reference
Routines used for managing the Write requests.
#include <stdio.h>
#include <string.h>
#include <pthread.h>
#include <fcntl.h>
#include <sys/file.h>
#include `HashData.h`
#include `HashTable.h`
#include <rpc/types.h>
#include <rpc/rpc.h>
#include <rpc/auth.h>
#include <rpc/pmap_clnt.h>
#include `log_functions.h`
#include `stuff_alloc.h`
#include `nfs23.h`
#include `nfs4.h`
#include `mount.h`
#include `nfs_core.h`
#include `cache_inode.h`
#include `cache_content.h`
#include `cache_content_policy.h`
#include `nfs_exports.h`
#include `nfs_creds.h`
#include `nfs_proto_functions.h`
#include `nfs_tools.h`
#include `nfs_proto_tools.h`
Functions
int nfs_Write (nfs_arg_t *parg, exportlist_t *pexport, fsal_op_context_t *pcontext, cache_inode_client_t *pclient, hash_table_t *ht, struct svc_req *preq, nfs_res_t *pres)
void nfs_Write_Free (nfs_res_t *resp)
Variables
writeverf3 NFS3_write_verifier
Detailed Description
Routines used for managing the Write requests.
Author:
Author deniel
Date:
Date 2005/11/28 17:02:54
Version:
Revision 1.14
nfs_Write.c(p.) : Routines used for managing the NFS4 COMPOUND functions.
Definition in file nfs_Write.c.
Function Documentation
int nfs_Write (nfs_arg_t * parg, exportlist_t * pexport, fsal_op_context_t * pcontext, cache_inode_client_t * pclient, hash_table_t * ht, struct svc_req * preq, nfs_res_t * pres)
Definition at line 148 of file nfs_Write.c.
References nfs2_FSALattr_To_Fattr(), NFS3_write_verifier, nfs_FhandleToCache(), nfs_RetryableError(), nfs_SetFailedStatus(), and nfs_SetWccData().
void nfs_Write_Free (nfs_res_t * resp)
nfs_Write_Free: Frees the result structure allocated for nfs_Write.
Frees the result structure allocated for nfs_Write.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 508 of file nfs_Write.c.
Variable Documentation
writeverf3 NFS3_write_verifier
nfs_Write: The NFS PROC2 and PROC3 WRITE
Implements the NFS PROC WRITE function (for V2 and V3).
Parameters:
parg [IN] pointer to nfs arguments union
pexport [IN] pointer to nfs export list
pcontext [IN] credentials to be used for this request
pclient [INOUT] client resource to be used
ht [INOUT] cache inode hash table
preq [IN] pointer to SVC request related to this call
pres [OUT] pointer to the structure to contain the result of the call
Returns: NFS_REQ_OK if successfull
 NFS_REQ_DROP if failed but retryable
 NFS_REQ_FAILED if failed and not retryable.