nfs_Lookup.c File Reference
#include <stdio.h>
#include <string.h>
#include <pthread.h>
#include <fcntl.h>
#include <sys/file.h>
#include `HashData.h`
#include `HashTable.h`
#include <rpc/types.h>
#include <rpc/rpc.h>
#include <rpc/auth.h>
#include <rpc/pmap_clnt.h>
#include `log_functions.h`
#include `stuff_alloc.h`
#include `nfs23.h`
#include `nfs4.h`
#include `mount.h`
#include `nfs_core.h`
#include `cache_inode.h`
#include `cache_content.h`
#include `nfs_exports.h`
#include `nfs_creds.h`
#include `nfs_proto_functions.h`
#include `nfs_tools.h`
#include `nfs_proto_tools.h`
Functions
int nfs_Lookup (nfs_arg_t *parg, exportlist_t *pexport, fsal_op_context_t *pcontext, cache_inode_client_t *pclient, hash_table_t *ht, struct svc_req *preq, nfs_res_t *pres)
void nfs3_Lookup_Free (nfs_res_t *resp)
void nfs2_Lookup_Free (nfs_res_t *resp)
Function Documentation
void nfs2_Lookup_Free (nfs_res_t * resp)
nfs_Lookup_Free: Frees the result structure allocated for nfs_Lookup.
Frees the result structure allocated for nfs_Lookup.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 309 of file nfs_Lookup.c.
void nfs3_Lookup_Free (nfs_res_t * resp)
nfs_Lookup_Free: Frees the result structure allocated for nfs_Lookup.
Frees the result structure allocated for nfs_Lookup.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 295 of file nfs_Lookup.c.
int nfs_Lookup (nfs_arg_t * parg, exportlist_t * pexport, fsal_op_context_t * pcontext, cache_inode_client_t * pclient, hash_table_t * ht, struct svc_req * preq, nfs_res_t * pres)
nfs_Lookup: The NFS PROC2 and PROC3 LOOKUP
Implements the NFS PROC LOOKUP function (for V2 and V3).
Parameters:
parg [IN] pointer to nfs arguments union
pexport [IN] pointer to nfs export list
pcontext [IN] credentials to be used for this request
pclient [INOUT] client resource to be used
ht [INOUT] cache inode hash table
preq [IN] pointer to SVC request related to this call
pres [OUT] pointer to the structure to contain the result of the call
Returns: always NFS_REQ_OK (this routine does nothing)
Definition at line 144 of file nfs_Lookup.c.
References nfs2_FSALattr_To_Fattr(), nfs_FhandleToCache(), nfs_RetryableError(), nfs_SetFailedStatus(), and nfs_SetPostOpAttr().