nfs_proto_tools.c File Reference
A set of functions used to managed NFS.
#include <stdio.h>
#include <string.h>
#include <pthread.h>
#include <fcntl.h>
#include <sys/file.h>
#include <pwd.h>
#include <grp.h>
#include `HashData.h`
#include `HashTable.h`
#include <rpc/types.h>
#include <rpc/rpc.h>
#include <rpc/auth.h>
#include <rpc/pmap_clnt.h>
#include `log_functions.h`
#include `stuff_alloc.h`
#include `nfs23.h`
#include `nfs4.h`
#include `mount.h`
#include `nfs_core.h`
#include `cache_inode.h`
#include `cache_content.h`
#include `nfs_exports.h`
#include `nfs_creds.h`
#include `nfs_proto_functions.h`
#include `nfs_tools.h`
#include `nfs_file_handle.h`
#include `nfs_proto_tools.h`
Functions
cache_entry_t * nfs_FhandleToCache (u_long rq_vers, fhandle2 *pfh2, nfs_fh3 *pfh3, nfs_fh4 *pfh4, nfsstat2 *pstatus2, nfsstat3 *pstatus3, nfsstat4 *pstatus4, fsal_attrib_list_t *pattr, fsal_op_context_t *pcontext, cache_inode_client_t *pclient, hash_table_t *ht, int *prc)
int nfs_SetPostOpAttr (fsal_op_context_t *pcontext, exportlist_t *pexport, cache_entry_t *pentry, fsal_attrib_list_t *pfsal_attr, post_op_attr *presult)
void nfs_SetPreOpAttr (fsal_attrib_list_t *pfsal_attr, pre_op_attr *pattr)
void nfs_SetWccData (fsal_op_context_t *pcontext, exportlist_t *pexport, cache_entry_t *pentry, fsal_attrib_list_t *pbefore_attr, fsal_attrib_list_t *pafter_attr, wcc_data *pwcc_data)
int nfs_RetryableError (cache_inode_status_t cache_status)
void nfs_SetFailedStatus (fsal_op_context_t *pcontext, exportlist_t *pexport, int version, cache_inode_status_t status, nfsstat2 *pstatus2, nfsstat3 *pstatus3, cache_entry_t *pentry0, post_op_attr *ppost_op_attr, cache_entry_t *pentry1, fsal_attrib_list_t *ppre_vattr1, wcc_data *pwcc_data1, cache_entry_t *pentry2, fsal_attrib_list_t *ppre_vattr2, wcc_data *pwcc_data2)
int nfs4_FSALattr_To_Fattr (exportlist_t *pexport, fsal_attrib_list_t *pattr, fattr4 *Fattr, compound_data_t *data, nfs_fh4 *objFH, bitmap4 *Bitmap)
int nfs3_Sattr_To_FSALattr (fsal_attrib_list_t *pFSAL_attr, sattr3 *psattr)
int nfs2_FSALattr_To_Fattr (exportlist_t *pexport, fsal_attrib_list_t *pFSAL_attr, fattr2 *pFattr)
int nfs4_SetCompoundExport (compound_data_t *data)
int nfs4_FhandleToExId (nfs_fh4 *fh4p, unsigned short *ExIdp)
void nfs4_stringid_split (char *buff, char *uidname, char *domainname)
int utf82str (char *str, utf8string *utf8str)
int str2utf8 (char *str, utf8string *utf8str)
seqid4 nfs4_NextSeqId (seqid4 seqid)
void nfs4_bitmap4_to_list (bitmap4 *b, uint_t *plen, uint32_t *pval)
void nfs4_list_to_bitmap4 (bitmap4 *b, uint_t *plen, uint32_t *pval)
int nfs3_FSALattr_To_Fattr (exportlist_t *pexport, fsal_attrib_list_t *FSAL_attr, fattr3 *Fattr)
int nfs2_Sattr_To_FSALattr (fsal_attrib_list_t *pFSAL_attr, sattr2 *Fattr)
int nfs4_Fattr_Check_Access (fattr4 *Fattr, int access)
int nfs4_Fattr_Check_Access_Bitmap (bitmap4 *pbitmap, int access)
int nfs4_Fattr_Supported (fattr4 *Fattr)
int nfs4_Fattr_Supported_Bitmap (bitmap4 *pbitmap)
int nfs4_Fattr_cmp (fattr4 *Fattr1, fattr4 *Fattr2)
int nfs4_Fattr_To_FSAL_attr (fsal_attrib_list_t *pFSAL_attr, fattr4 *Fattr)
nfsstat4 nfs4_Errno (cache_inode_status_t error)
nfsstat3 nfs3_Errno (cache_inode_status_t error)
nfsstat2 nfs2_Errno (cache_inode_status_t error)
int nfs4_AllocateFH (nfs_fh4 *fh)
int nfs4_MakeCred (compound_data_t *data)
Variables
nfs_parameter_t nfs_param
Detailed Description
A set of functions used to managed NFS.
Author:
Author leibovic
Date:
Date 2006/01/31 10:06:00
Version:
Revision 1.48
nfs_proto_tools.c(p.) - A set of functions used to managed NFS.
Definition in file nfs_proto_tools.c.
Function Documentation
nfsstat2 nfs2_Errno (cache_inode_status_t error)
nfs2_Errno: Converts a cache_inode status to a nfsv2 status.
Converts a cache_inode status to a nfsv2 status.
Parameters:
error [IN] Input cache inode ewrror.
Returns: the converted NFSv2 status.
Definition at line 3262 of file nfs_proto_tools.c.
Referenced by nfs_Readdir(), and nfs_SetFailedStatus().
int nfs2_FSALattr_To_Fattr (exportlist_t * pexport, fsal_attrib_list_t * pFSAL_attr, fattr2 * pFattr)
nfs2_FSALattr_To_Fattr: Converts FSAL Attributes to NFSv2 attributes.
Converts FSAL Attributes to NFSv2 attributes.
Parameters:
pexport [IN] the related export entry.
FSAL_attr [IN] pointer to FSAL attributes.
Fattr [OUT] pointer to NFSv2 attributes.
Returns: 1 if successful, 0 otherwise.
Todo mode mask ?
mode mask ?
Definition at line 1614 of file nfs_proto_tools.c.
Referenced by nfs_Create(), nfs_Getattr(), nfs_Lookup(), nfs_Mkdir(), nfs_Read(), nfs_Setattr(), and nfs_Write().
int nfs2_Sattr_To_FSALattr (fsal_attrib_list_t * pFSAL_attr, sattr2 * Fattr)
nfs2_Sattr_To_FSALattr: Converts NFSv2 Set Attributes to FSAL attributes.
Converts NFSv2 Set Attributes to FSAL attributes.
Parameters:
FSAL_attr [IN] pointer to FSAL attributes.
Fattr [OUT] pointer to NFSv2 set attributes.
Returns: 1 if successful, 0 otherwise.
Definition at line 2168 of file nfs_proto_tools.c.
Referenced by nfs_Create(), and nfs_Setattr().
nfsstat3 nfs3_Errno (cache_inode_status_t error)
nfs3_Errno: Converts a cache_inode status to a nfsv3 status.
Converts a cache_inode status to a nfsv3 status.
Parameters:
error [IN] Input cache inode ewrror.
Returns: the converted NFSv3 status.
Todo : Check if this works by making stress tests
Definition at line 3147 of file nfs_proto_tools.c.
Referenced by nfs3_Pathconf(), nfs3_Readdirplus(), nfs_Readdir(), and nfs_SetFailedStatus().
int nfs3_FSALattr_To_Fattr (exportlist_t * pexport, fsal_attrib_list_t * FSAL_attr, fattr3 * Fattr)
nfs3_FSALattr_To_Fattr: Converts FSAL Attributes to NFSv3 attributes.
Converts FSAL Attributes to NFSv3 attributes.
Parameters:
pexport [IN] the related export entry
FSAL_attr [IN] pointer to FSAL attributes.
Fattr [OUT] pointer to NFSv3 attributes.
Returns: 1 if successful, 0 otherwise.
Definition at line 2072 of file nfs_proto_tools.c.
Referenced by nfs_Getattr(), nfs_Setattr(), and nfs_SetPostOpAttr().
int nfs3_Sattr_To_FSALattr (fsal_attrib_list_t * pFSAL_attr, sattr3 * psattr)
nfs3_Sattr_To_FSALattr: Converts NFSv3 Sattr to FSAL Attributes.
Converts NFSv3 Sattr to FSAL Attributes.
Parameters:
pFSAL_attr [OUT] computed FSAL attributes.
psattr [IN] NFSv3 sattr to be set.
Returns: 0 if failed, 1 if successful.
Definition at line 1506 of file nfs_proto_tools.c.
Referenced by nfs_Create(), and nfs_Setattr().
int nfs4_AllocateFH (nfs_fh4 * fh)
nfs4_AllocateFH: Allocates a buffer to be used for storing a NFSv4 filehandle.
Allocates a buffer to be used for storing a NFSv4 filehandle.
Parameters:
fh [INOUT] the filehandle to manage.
Returns: NFS4_OK if successful, NFS3ERR_SERVERFAULT, NFS4ERR_RESOURCE or NFS4ERR_STALE otherwise.
Definition at line 3365 of file nfs_proto_tools.c.
Referenced by CreatePUBFH4(), CreateROOTFH4(), nfs4_CreateROOTFH4(), nfs4_op_create(), nfs4_op_getfh(), nfs4_op_lookup_pseudo(), nfs4_op_open(), nfs4_op_putfh(), nfs4_op_putpubfh(), nfs4_op_putrootfh(), nfs4_op_readdir(), nfs4_op_readdir_pseudo(), and nfs4_op_savefh().
void nfs4_bitmap4_to_list (bitmap4 * b, uint_t * plen, uint32_t * pval)
nfs_bitmap4_to_list: convert an attribute's bitmap to a list of attributes.
Convert an attribute's bitmap to a list of attributes.
Parameters:
b [IN] bitmap to convert.
plen [OUT] list's length.
plval [OUT] list's values.
Returns: nothing (void function)
Definition at line 1949 of file nfs_proto_tools.c.
Referenced by nfs4_Fattr_Check_Access(), nfs4_Fattr_Check_Access_Bitmap(), nfs4_Fattr_cmp(), nfs4_Fattr_Supported(), nfs4_Fattr_Supported_Bitmap(), nfs4_Fattr_To_FSAL_attr(), nfs4_FSALattr_To_Fattr(), and nfs4_PseudoToFattr().
nfsstat4 nfs4_Errno (cache_inode_status_t error)
nfs4_Errno: Converts a cache_inode status to a nfsv4 status.
Converts a cache_inode status to a nfsv4 status.
Parameters:
error [IN] Input cache inode ewrror.
Returns: the converted NFSv4 status.
Definition at line 3031 of file nfs_proto_tools.c.
Referenced by nfs4_op_access(), nfs4_op_close(), nfs4_op_create(), nfs4_op_getattr(), nfs4_op_link(), nfs4_op_lock(), nfs4_op_lookup(), nfs4_op_lookupp(), nfs4_op_open(), nfs4_op_read(), nfs4_op_readdir(), nfs4_op_readlink(), nfs4_op_remove(), nfs4_op_rename(), nfs4_op_setattr(), and nfs4_op_write().
int nfs4_Fattr_Check_Access (fattr4 * Fattr, int access)
nfs4_Fattr_Check_Access: checks if attributes have READ or WRITE access.
Checks if attributes have READ or WRITE access.
Parameters:
Fattr [IN] pointer to NFSv4 attributes.
access [IN] access to be checked, either FATTR4_ATTR_READ or FATTR4_ATTR_WRITE
Returns: 1 if successful, 0 otherwise.
Definition at line 2264 of file nfs_proto_tools.c.
References nfs4_bitmap4_to_list().
Referenced by nfs4_op_create(), nfs4_op_nverify(), nfs4_op_open(), nfs4_op_setattr(), and nfs4_op_verify().
int nfs4_Fattr_Check_Access_Bitmap (bitmap4 * pbitmap, int access)
nfs4_Fattr_Check_Access_Bitmap: checks if attributes bitmaps have READ or WRITE access.
Checks if attributes have READ or WRITE access.
Parameters:
pbitmap [IN] pointer to NFSv4 attributes.
access [IN] access to be checked, either FATTR4_ATTR_READ or FATTR4_ATTR_WRITE
Returns: 1 if successful, 0 otherwise.
Definition at line 2311 of file nfs_proto_tools.c.
References nfs4_bitmap4_to_list().
Referenced by nfs4_op_getattr(), and nfs4_op_readdir().
int nfs4_Fattr_cmp (fattr4 * Fattr1, fattr4 * Fattr2)
nfs4_Fattr_cmp: compares 2 fattr4 buffers.
Compares 2 fattr4 buffers.
Parameters:
Fattr1 [IN] pointer to NFSv4 attributes.
Fattr2 [IN] pointer to NFSv4 attributes.
Returns: TRUE if attributes are the same, FALSE otherwise, but -1 if RDATTR_ERROR is set
Definition at line 2451 of file nfs_proto_tools.c.
References nfs4_bitmap4_to_list().
Referenced by nfs4_op_nverify(), and nfs4_op_verify().
int nfs4_Fattr_Supported (fattr4 * Fattr)
nfs4_Fattr_Supported: Checks if an attribute is supported.
Checks if an attribute is supported.
Parameters:
Fattr [IN] pointer to NFSv4 attributes.
Returns: 1 if successful, 0 otherwise.
Definition at line 2357 of file nfs_proto_tools.c.
References nfs4_bitmap4_to_list().
Referenced by nfs4_op_create(), nfs4_op_nverify(), nfs4_op_open(), nfs4_op_setattr(), and nfs4_op_verify().
int nfs4_Fattr_Supported_Bitmap (bitmap4 * pbitmap)
nfs4_Fattr_Supported: Checks if an attribute is supported.
Checks if an attribute is supported.
Parameters:
Fattr [IN] pointer to NFSv4 attributes.
Returns: 1 if successful, 0 otherwise.
Definition at line 2404 of file nfs_proto_tools.c.
References nfs4_bitmap4_to_list().
Referenced by nfs4_op_getattr().
int nfs4_Fattr_To_FSAL_attr (fsal_attrib_list_t * pFSAL_attr, fattr4 * Fattr)
nfs4_Fattr_To_FSAL_attr: Converts NFSv4 attributes buffer to a FSAL attributes structure.
Converts NFSv4 attributes buffer to a FSAL attributes structure.
Parameters:
pFSAL_attr [OUT] pointer to FSAL attributes.
Fattr [IN] pointer to NFSv4 attributes.
Returns: 1 if successful, 0 if not supported, -1 if argument is badly formed
Definition at line 2621 of file nfs_proto_tools.c.
References nfs4_bitmap4_to_list().
Referenced by nfs4_op_create(), nfs4_op_open(), and nfs4_op_setattr().
int nfs4_FhandleToExId (nfs_fh4 * fh4p, unsigned short * ExIdp)
nfs4_FhandleToExId
This routine extracts the export id from the filehandle
Parameters:
fh4p [IN] pointer to file handle to be used.
ExIdp [OUT] pointer to buffer in which found export id will be stored.
Returns: TRUE is successful, FALSE otherwise.
Definition at line 1758 of file nfs_proto_tools.c.
int nfs4_FSALattr_To_Fattr (exportlist_t * pexport, fsal_attrib_list_t * pattr, fattr4 * Fattr, compound_data_t * data, nfs_fh4 * objFH, bitmap4 * Bitmap)
nfs4_FSALattr_To_Fattr: Converts FSAL Attributes to NFSv4 Fattr buffer.
Converts FSAL Attributes to NFSv4 Fattr buffer.
Parameters:
pexport [IN] the related export entry.
pattr [IN] pointer to FSAL attributes.
Fattr [OUT] NFSv4 Fattr buffer
data [IN] NFSv4 compoud request's data.
Bitmap [OUT] NFSv4 attributes bitmap to the Fattr buffer.
Returns: -1 if failed, 0 if successful.
Todo : not the right answer, actual quotas should be implemented
: not the right answer, actual quotas should be implemented
Definition at line 505 of file nfs_proto_tools.c.
References nfs4_bitmap4_to_list(), nfs4_list_to_bitmap4(), and nfs_param.
Referenced by nfs4_op_getattr(), nfs4_op_nverify(), nfs4_op_readdir(), and nfs4_op_verify().
void nfs4_list_to_bitmap4 (bitmap4 * b, uint_t * plen, uint32_t * pval)
nfs4_list_to_bitmap4: convert a list of attributes to an attributes's bitmap.
Convert a list of attributes to an attributes's bitmap.
Parameters:
b [OUT] computed bitmap
plen [IN] list's length
pval [IN] list's array
Returns: nothing (void function).
Definition at line 2027 of file nfs_proto_tools.c.
Referenced by nfs4_FSALattr_To_Fattr(), and nfs4_PseudoToFattr().
int nfs4_MakeCred (compound_data_t * data)
nfs4_MakeCred
This routine fills in the pcontext field in the compound data.
Parameters:
pfh [INOUT] pointer to compound data to be used. NOT YET IMPLEMENTED
Returns: NFS4_OK if successful, NFS4ERR_WRONGSEC otherwise.
Definition at line 3402 of file nfs_proto_tools.c.
References nfs_param.
Referenced by nfs4_op_lookup_pseudo(), nfs4_op_readdir_pseudo(), and nfs4_SetCompoundExport().
seqid4 nfs4_NextSeqId (seqid4 seqid)
nfs4_NextSeqId: compute the next nfsv4 sequence id.
Compute the next nfsv4 sequence id.
Parameters:
seqid [IN] previous sequence number.
Returns: the requested sequence number.
Definition at line 1892 of file nfs_proto_tools.c.
int nfs4_SetCompoundExport (compound_data_t * data)
nfs4_SetCompoundExport
This routine fills in the pexport field in the compound data.
Parameters:
pfh [OUT] pointer to compound data to be used.
Returns: NFS4_OK if successfull. Possible errors are NFS4ERR_BADHANDLE and NFS4ERR_WRONGSEC.
Definition at line 1721 of file nfs_proto_tools.c.
References nfs4_MakeCred().
Referenced by nfs4_op_link(), nfs4_op_lookupp(), nfs4_op_putfh(), nfs4_op_rename(), and nfs4_op_restorefh().
void nfs4_stringid_split (char * buff, char * uidname, char * domainname)
nfs4_stringid_split: Splits a domain stamped name in two different parts.
Splits a domain stamped name in two different parts.
Parameters:
buff [IN] the input string
uidname [OUT] the extracted uid name
domainname [OUT] the extracted fomain name
Returns: nothing (void function)
Definition at line 1790 of file nfs_proto_tools.c.
cache_entry_t* nfs_FhandleToCache (u_long rq_vers, fhandle2 * pfh2, nfs_fh3 * pfh3, nfs_fh4 * pfh4, nfsstat2 * pstatus2, nfsstat3 * pstatus3, nfsstat4 * pstatus4, fsal_attrib_list_t * pattr, fsal_op_context_t * pcontext, cache_inode_client_t * pclient, hash_table_t * ht, int * prc)
nfs_FhandleToCache: Gets a cache entry using a file handle (v2 or v3) as input.
Gets a cache entry using a file handle (v2 or v3) as input.
Parameters:
rq_vers [IN] version of the NFS protocol to be used
pfh2 [IN] NFSv2 file handle or NULL
pfh3 [IN] NFSv3 file handle or NULL
pfh4 [IN] NFSv4 file handle or NULL
pstatus2 [OUT] pointer to NFSv2 status or NULL
pstatus3 [OUT] pointer to NFSv3 status or NULL
pstatus4 [OUT] pointer to NFSv4 status or NULL
pattr [OUT] FSAL attributes related to this cache entry
pcontext [IN] client's FSAL credentials
pclient [IN] client's ressources to be used for accessing the Cache Inode
ht [INOUT] Hash Table used to address the Cache Inode
prc [OUT] internal status for the request (NFS_REQ_DROP or NFS_REQ_OK)
Returns: a pointer to the related pentry if successful, NULL is returned in case of a failure.
Definition at line 153 of file nfs_proto_tools.c.
Referenced by nfs3_Mknod(), nfs3_Readdirplus(), nfs4_op_open(), nfs4_op_putfh(), nfs_Create(), nfs_Fsstat(), nfs_Getattr(), nfs_Link(), nfs_Lookup(), nfs_Mkdir(), nfs_Read(), nfs_Readdir(), nfs_Readlink(), nfs_Remove(), nfs_Rename(), nfs_Rmdir(), nfs_Setattr(), nfs_Symlink(), and nfs_Write().
int nfs_RetryableError (cache_inode_status_t cache_status)
nfs_RetryableError: Indicates if an error is retryable or not.
Indicates if an error is retryable or not.
Parameters:
cache_status [IN] input Cache Inode Status value, to be tested.
Returns: TRUE if retryable, FALSE otherwise.
Todo : Not implemented for NOW BUGAZEOMEU
Definition at line 369 of file nfs_proto_tools.c.
References nfs_param.
Referenced by nfs3_Access(), nfs3_Mknod(), nfs3_Readdirplus(), nfs_Create(), nfs_Fsstat(), nfs_Link(), nfs_Lookup(), nfs_Mkdir(), nfs_Read(), nfs_Readdir(), nfs_Readlink(), nfs_Remove(), nfs_Rename(), nfs_Rmdir(), nfs_Setattr(), nfs_Symlink(), and nfs_Write().
void nfs_SetFailedStatus (fsal_op_context_t * pcontext, exportlist_t * pexport, int version, cache_inode_status_t status, nfsstat2 * pstatus2, nfsstat3 * pstatus3, cache_entry_t * pentry0, post_op_attr * ppost_op_attr, cache_entry_t * pentry1, fsal_attrib_list_t * ppre_vattr1, wcc_data * pwcc_data1, cache_entry_t * pentry2, fsal_attrib_list_t * ppre_vattr2, wcc_data * pwcc_data2)
Definition at line 451 of file nfs_proto_tools.c.
References nfs2_Errno(), nfs3_Errno(), nfs_SetPostOpAttr(), and nfs_SetWccData().
Referenced by nfs3_Access(), nfs3_Mknod(), nfs3_Readdirplus(), nfs_Create(), nfs_Fsstat(), nfs_Getattr(), nfs_Link(), nfs_Lookup(), nfs_Mkdir(), nfs_Read(), nfs_Readdir(), nfs_Readlink(), nfs_Remove(), nfs_Rename(), nfs_Rmdir(), nfs_Setattr(), nfs_Symlink(), and nfs_Write().
int nfs_SetPostOpAttr (fsal_op_context_t * pcontext, exportlist_t * pexport, cache_entry_t * pentry, fsal_attrib_list_t * pfsal_attr, post_op_attr * presult)
nfs_SetPostOpAttr: Converts FSAL Attributes to NFSv3 PostOp Attributes structure.
Converts FSAL Attributes to NFSv3 PostOp Attributes structure.
Parameters:
pexport [IN] the related export entry
pfsal_attr [IN] FSAL attributes
pattr [OUT] NFSv3 PostOp structure attributes.
Returns: 0 in all cases (making it a void function maybe a good idea)
Definition at line 258 of file nfs_proto_tools.c.
References nfs3_FSALattr_To_Fattr().
Referenced by nfs3_Access(), nfs3_Fsinfo(), nfs3_Mknod(), nfs3_Pathconf(), nfs3_Readdirplus(), nfs_Create(), nfs_Fsstat(), nfs_Link(), nfs_Lookup(), nfs_Mkdir(), nfs_Read(), nfs_Readdir(), nfs_Readlink(), nfs_SetFailedStatus(), nfs_SetWccData(), and nfs_Symlink().
void nfs_SetPreOpAttr (fsal_attrib_list_t * pfsal_attr, pre_op_attr * pattr)
nfs_SetPreOpAttr: Converts FSAL Attributes to NFSv3 PreOp Attributes structure.
Converts FSAL Attributes to NFSv3 PreOp Attributes structure.
Parameters:
pfsal_attr [IN] FSAL attributes.
pattr [OUT] NFSv3 PreOp structure attributes.
Returns: nothing (void function)
Definition at line 297 of file nfs_proto_tools.c.
Referenced by nfs_SetWccData().
void nfs_SetWccData (fsal_op_context_t * pcontext, exportlist_t * pexport, cache_entry_t * pentry, fsal_attrib_list_t * pbefore_attr, fsal_attrib_list_t * pafter_attr, wcc_data * pwcc_data)
nfs_SetWccData: Sets NFSv3 Weak Cache Coherency structure.
Sets NFSv3 Weak Cache Coherency structure.
Parameters:
pcontext [IN] credentials
pentry [IN] related pentry
pbefore_attr [IN] the attributes before the operation.
pafter_attr [IN] the attributes after the operation
pwcc_data [OUT] the Weak Cache Coherency structure
Returns: nothing (void function).
Definition at line 335 of file nfs_proto_tools.c.
References nfs_SetPostOpAttr(), and nfs_SetPreOpAttr().
Referenced by nfs3_Commit(), nfs3_Mknod(), nfs_Create(), nfs_Link(), nfs_Mkdir(), nfs_Remove(), nfs_Rename(), nfs_Rmdir(), nfs_Setattr(), nfs_SetFailedStatus(), nfs_Symlink(), and nfs_Write().
int str2utf8 (char * str, utf8string * utf8str)
str2utf8: converts a string buffer into a UTF8 string descriptor.
Converts a string buffer into a UTF8 string descriptor.
Parameters:
str [IN] input string
utf8str [OUT] computed UTF8 string
Returns: -1 if failed, 0 if successful.
Definition at line 1852 of file nfs_proto_tools.c.
Referenced by nfs4_op_readdir(), and nfs4_op_readlink().
int utf82str (char * str, utf8string * utf8str)
utf82str: converts a UTF8 string buffer into a string descriptor.
Converts a UTF8 string buffer into a string descriptor.
Parameters:
str [OUT] computed output string
utf8str [IN] input UTF8 string
Returns: -1 if failed, 0 if successful.
Definition at line 1821 of file nfs_proto_tools.c.
Referenced by nfs4_Compound(), and nfs4_op_create().
Variable Documentation
nfs_parameter_t nfs_param