test_mnt_proto.c File Reference
Tests for testing the mount protocol routines.
#include <stdio.h>
#include <string.h>
#include <pthread.h>
#include <fcntl.h>
#include <sys/file.h>
#include <sys/socket.h>
#include `HashData.h`
#include `HashTable.h`
#include <rpc/types.h>
#include <rpc/rpc.h>
#include <rpc/auth.h>
#include <rpc/pmap_clnt.h>
#include `log_functions.h`
#include `stuff_alloc.h`
#include `nfs23.h`
#include `nfs4.h`
#include `mount.h`
#include `nfs_core.h`
#include `cache_inode.h`
#include `cache_content.h`
#include `nfs_exports.h`
#include `nfs_creds.h`
#include `nfs_proto_functions.h`
#include `nfs_tools.h`
Defines
#define NB_EXPORT_ENTRIES 5
#define Maketest(func, name)
Functions
void print_export_list (exports export_list)
int test_mnt_Null ()
int test_mnt_Export ()
int main (int argc, char **argv)
Detailed Description
Tests for testing the mount protocol routines.
Author:
Author deniel
Date:
Date 2005/12/20 10:52:15
Version:
Revision 1.8
Definition in file test_mnt_proto.c.
Define Documentation
#define Maketest(func, name)
Value:
do {                      \
  int rc;                                             \
  printf("\n======== TEST %s =========\n\n",name);    \
  rc = func();                                        \
  if (rc)                                             \
    printf("\n-------- %s : %d ---------\n",name,rc); \
  else                                                \
    printf("\n-------- %s : OK ---------\n",name); \
  } while (0)
Definition at line 311 of file test_mnt_proto.c.
Referenced by main().
#define NB_EXPORT_ENTRIES 5
Definition at line 165 of file test_mnt_proto.c.
Function Documentation
int main (int argc, char ** argv)
Definition at line 321 of file test_mnt_proto.c.
References Maketest, test_mnt_Export(), and test_mnt_Null().
void print_export_list (exports export_list)
Definition at line 124 of file test_mnt_proto.c.
Referenced by test_mnt_Export().
int test_mnt_Export ()
Definition at line 166 of file test_mnt_proto.c.
References mnt_Export(), and print_export_list().
Referenced by main().
int test_mnt_Null ()
Definition at line 148 of file test_mnt_proto.c.
References mnt_Null().
Referenced by main().