.TH "nfs_stat_mgmt.c" 3 "31 Mar 2009" "Version 0.1" "Support routines layer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfs_stat_mgmt.c \- routines for managing the nfs statistics.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <pthread.h>\fP
.br
\fC#include <fcntl.h>\fP
.br
\fC#include <sys/file.h>\fP
.br
\fC#include 'HashData.h'\fP
.br
\fC#include 'HashTable.h'\fP
.br
\fC#include <rpc/types.h>\fP
.br
\fC#include <rpc/rpc.h>\fP
.br
\fC#include <rpc/auth.h>\fP
.br
\fC#include <rpc/pmap_clnt.h>\fP
.br
\fC#include 'log_functions.h'\fP
.br
\fC#include 'stuff_alloc.h'\fP
.br
\fC#include 'nfs23.h'\fP
.br
\fC#include 'nfs4.h'\fP
.br
\fC#include 'mount.h'\fP
.br
\fC#include 'nfs_core.h'\fP
.br
\fC#include 'cache_inode.h'\fP
.br
\fC#include 'cache_content.h'\fP
.br
\fC#include 'nfs_exports.h'\fP
.br
\fC#include 'nfs_creds.h'\fP
.br
\fC#include 'nfs_proto_functions.h'\fP
.br
\fC#include 'nfs_tools.h'\fP
.br
\fC#include 'nfs_proto_tools.h'\fP
.br
\fC#include 'nfs_stat.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBnfs_stat_update\fP (nfs_stat_type_t type, nfs_request_stat_t *pstat_req, struct svc_req *preq)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "nfs_parameter_t \fBnfs_param\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
routines for managing the nfs statistics. 

\fBAuthor:\fP
.RS 4
.RE
.PP
\fBAuthor\fP.RS 4
deniel 
.RE
.PP
\fBDate:\fP
.RS 4
.RE
.PP
\fBDate\fP.RS 4
2005/11/28 17:03:03 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision\fP.RS 4
1.4 
.RE
.PP
\fBnfs_stat_mgmt.c\fP : routines for managing the nfs statistics.
.PP
\fBHeader\fP.RS 4
/cea/S/home/cvs/cvs/SHERPA/BaseCvs/GANESHA/src/support/nfs_stat_mgmt.c,v 1.4 2005/11/28 17:03:03 deniel Exp 
.RE
.PP
.PP
\fBLog\fP.RS 4
\fBnfs_stat_mgmt.c\fP,v 
.RE
.PP
Revision 1.4 2005/11/28 17:03:03 deniel Added CeCILL headers
.PP
Revision 1.3 2005/09/30 15:50:19 deniel Support for mount and nfs protocol different from the default
.PP
Revision 1.2 2005/09/30 14:27:34 deniel Adding some configurationsa items in nfs_core
.PP
Revision 1.1 2005/08/11 12:37:28 deniel Added statistics management 
.PP
Definition in file \fBnfs_stat_mgmt.c\fP.
.SH "Function Documentation"
.PP 
.SS "void nfs_stat_update (nfs_stat_type_t type, nfs_request_stat_t * pstat_req, struct svc_req * preq)"
.PP
nfs_stat_update: Update a client's statistics.
.PP
Update a client's statistics.
.PP
\fBParameters:\fP
.RS 4
\fItype\fP [IN] type of the stat to dump 
.br
\fIpclient\fP [INOUT] client resource to be used 
.br
\fIpreq\fP [IN] pointer to SVC request related to this call
.RE
.PP
\fBReturns:\fP
.RS 4
nothing (void function) 
.RE
.PP

.PP
Definition at line 160 of file nfs_stat_mgmt.c.
.SH "Variable Documentation"
.PP 
.SS "nfs_parameter_t \fBnfs_param\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Support routines layer from the source code.
