.TH "todo" 3 "31 Mar 2009" "Version 0.1" "Support routines layer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
 
.IP "\fBMember \fBFLAG_EXPORT_ID\fP \fP" 1c
: add encrypt handles option 
.PP
.PP
 
.IP "\fBMember \fBBuildDefaultExport\fP \fP" 1c
set default values here 
.PP
.PP
 
.IP "\fBMember \fBBuildDefaultExport\fP \fP" 1c
BUGAZOMEU : temporaire, bug de parsing MaxRead/MaxWrite 
.PP

