cache_content_gc.c File Reference
Management of the file content cache: initialisation.
#include `stuff_alloc.h`
#include `LRU_List.h`
#include `log_functions.h`
#include `HashData.h`
#include `HashTable.h`
#include `fsal.h`
#include `cache_inode.h`
#include `cache_content.h`
#include <unistd.h>
#include <sys/types.h>
#include <sys/param.h>
#include <sys/vfs.h>
#include <time.h>
#include <pthread.h>
#include <errno.h>
Functions
void cache_content_set_gc_policy (cache_content_gc_policy_t policy)
cache_content_gc_policy_t cache_content_get_gc_policy (void)
int cache_content_gc_function (LRU_entry_t *plru_entry, void *addparam)
int cache_content_sync_function (LRU_entry_t *plru_entry, void *addparam)
cache_content_status_t cache_content_gc (cache_content_client_t *pclient, cache_content_status_t *pstatus)
cache_content_status_t cache_content_sync (cache_content_client_t *pclient, cache_content_status_t *pstatus)
int cache_content_invalidate_flushed (LRU_entry_t *plru_entry, void *addparam)
Variables
cache_content_gc_policy_t cache_content_gc_policy
Detailed Description
Management of the file content cache: initialisation.
Author:
Author deniel
Date:
Date 2005/11/28 17:02:33
Version:
Revision 1.8
cache_content.c : Management of the file content cache: initialisation.
Definition in file cache_content_gc.c.
Function Documentation
cache_content_status_t cache_content_gc (cache_content_client_t * pclient, cache_content_status_t * pstatus)
cache_content_gc: Perform garbbage collection on the ressources managed by a client.
Perform garbbage collection on the ressources managed by a client.
Parameters:
pclient [INOUT] ressource allocated by the client for the nfs management.
pstatus [OUT] returned status.
Returns: CACHE_CONTENT_SUCCESS if operation is a success
CACHE_CONTENT_INVALID_ARGUMENT if a null argument is passed
CACHE_CONTENT_LRU_ERROR if allocation error occured when validating the entry
See also: LRU_invalidate_by_function
LRU_gc_invalid
Definition at line 308 of file cache_content_gc.c.
References cache_content_gc_function().
int cache_content_gc_function (LRU_entry_t * plru_entry, void * addparam)
cache_content_gc_function: Tests is an entry in the File Content cache is to be set invalid (has expired).
Tests is an entry in cache inode is to be set invalid (has expired). If entry is invalidated, does the cleaning stuff on it.
Parameters:
pentry [IN] pointer to the entry to test
Returns: 1 if entry must be set invalid, 0 if not.
See also: LRU_invalidate_by_function
LRU_gc_invalid
Definition at line 219 of file cache_content_gc.c.
References cache_content_gc_policy.
Referenced by cache_content_gc().
cache_content_gc_policy_t cache_content_get_gc_policy (void)
cache_content_get_gc_policy: Set the cache_content garbagge collecting policy.
Returns: the current policy.
Definition at line 134 of file cache_content_gc.c.
int cache_content_invalidate_flushed (LRU_entry_t * plru_entry, void * addparam)
Definition at line 385 of file cache_content_gc.c.
void cache_content_set_gc_policy (cache_content_gc_policy_t policy)
cache_content_set_gc_policy: Set the cache_content garbagge collecting policy.
Parameters:
policy [IN] policy to be set.
Returns: nothing (void function)
Definition at line 121 of file cache_content_gc.c.
References cache_content_gc_policy.
cache_content_status_t cache_content_sync (cache_content_client_t * pclient, cache_content_status_t * pstatus)
cache_content_sync: Sync the entry on the client
Perform garbbage collection on the ressources managed by a client.
Parameters:
pclient [INOUT] ressource allocated by the client for the nfs management.
pstatus [OUT] returned status.
Returns: CACHE_CONTENT_SUCCESS if operation is a success
CACHE_CONTENT_INVALID_ARGUMENT if a null argument is passed
CACHE_CONTENT_LRU_ERROR if allocation error occured when validating the entry
See also: LRU_invalidate_by_function
LRU_gc_invalid
Definition at line 359 of file cache_content_gc.c.
References cache_content_sync_function().
int cache_content_sync_function (LRU_entry_t * plru_entry, void * addparam)
cache_content_sync_function: Test if a entry is to be synced, and sync it.
Tests is an entry in cache inode is to be set invalid (has expired). If entry is invalidated, does the cleaning stuff on it.
Parameters:
pentry [IN] pointer to the entry to test
Returns: 1 if entry must be set invalid, 0 if not.
See also: LRU_invalidate_by_function
LRU_gc_invalid
Definition at line 263 of file cache_content_gc.c.
References cache_content_gc_policy.
Referenced by cache_content_sync().
Variable Documentation
cache_content_gc_policy_t cache_content_gc_policy
Definition at line 109 of file cache_content_gc.c.
Referenced by cache_content_gc_function(), cache_content_set_gc_policy(), and cache_content_sync_function().