cache_content_emergency_flush.c File Reference
Emergency flush for forcing flush of data cached files to FSAL.
#include `LRU_List.h`
#include `log_functions.h`
#include `HashData.h`
#include `HashTable.h`
#include `fsal.h`
#include `cache_inode.h`
#include `cache_content.h`
#include <unistd.h>
#include <sys/types.h>
#include <sys/param.h>
#include <time.h>
#include <pthread.h>
#include <errno.h>
#include <dirent.h>
#include <sys/stat.h>
#include <string.h>
Functions
cache_content_status_t cache_content_emergency_flush (char *cachedir, cache_content_flush_behaviour_t flushhow, time_t grace_period, unsigned int index, unsigned int mod, fsal_op_context_t *pcontext, cache_content_status_t *pstatus)
Variables
unsigned int cache_content_dir_errno
Detailed Description
Emergency flush for forcing flush of data cached files to FSAL.
Author: $Author$
Date: $Date$
Version: $Revision$
cache_content_emergency_flush.c(p.) : Emergency flush for forcing flush of data cached files to FSAL.
Definition in file cache_content_emergency_flush.c.
Function Documentation
cache_content_status_t cache_content_emergency_flush (char * cachedir, cache_content_flush_behaviour_t flushhow, time_t grace_period, unsigned int index, unsigned int mod, fsal_op_context_t * pcontext, cache_content_status_t * pstatus)
cache_content_emergency_flush: Flushes the content of a file in the local cache to the FSAL data.
Flushes the content of a file in the local cache to the FSAL data. This routine should be called only from the cache_inode layer.
No lock management is done in this layer: the related pentry in the cache inode layer is locked and will prevent from concurent accesses.
Parameters:
cachedir [IN] cachedir the filesystem where the cache resides
flushhow [IN] should we delete local files or not ?
grace_period [IN] grace_period The grace period for a file before being considered for deletion
pcontext [INOUT] pcontext the FSAL context for this operation
pstatys [OUT] the status of the operation.
Returns: CACHE_CONTENT_SUCCESS if successful, an error otherwise.
Definition at line 135 of file cache_content_emergency_flush.c.
References cache_content_dir_errno, cache_content_get_datapath(), cache_content_get_inum(), cache_content_local_cache_closedir(), cache_content_local_cache_dir_iter(), and cache_content_local_cache_opendir().
Variable Documentation
unsigned int cache_content_dir_errno
Definition at line 111 of file cache_content_misc.c.
Referenced by cache_content_emergency_flush(), cache_content_local_cache_dir_iter(), and cache_content_local_cache_opendir().