cache_content_crash_recover.c File Reference
#include `LRU_List.h`
#include `log_functions.h`
#include `HashData.h`
#include `HashTable.h`
#include `fsal.h`
#include `cache_inode.h`
#include `cache_content.h`
#include <unistd.h>
#include <sys/types.h>
#include <sys/param.h>
#include <time.h>
#include <pthread.h>
#include <errno.h>
#include <dirent.h>
#include <string.h>
Functions
cache_content_status_t cache_content_crash_recover (unsigned short exportid, unsigned int index, unsigned int mod, cache_content_client_t *pclient_data, cache_inode_client_t *pclient_inode, hash_table_t *ht, fsal_op_context_t *pcontext, cache_content_status_t *pstatus)
Function Documentation
cache_content_status_t cache_content_crash_recover (unsigned short exportid, unsigned int index, unsigned int mod, cache_content_client_t * pclient_data, cache_inode_client_t * pclient_inode, hash_table_t * ht, fsal_op_context_t * pcontext, cache_content_status_t * pstatus)
cache_content_crash_recover: recovers the data cache and the associated inode after a crash.
Parameters:
pclient [IN] ressource allocated by the client for the nfs management. [OUT] returned status.
Returns: CACHE_CONTENT_SUCCESS is successful.
Definition at line 118 of file cache_content_crash_recover.c.
References cache_content_get_export_id(), cache_content_get_inum(), cache_content_local_cache_closedir(), cache_content_local_cache_dir_iter(), cache_content_local_cache_opendir(), cache_content_new_entry(), cache_content_recover_size(), and cache_content_valid().