cache_content_add_entry.c File Reference
Management of the file content cache: adding a new entry.
#include `LRU_List.h`
#include `log_functions.h`
#include `HashData.h`
#include `HashTable.h`
#include `fsal.h`
#include `cache_inode.h`
#include `cache_content.h`
#include `stuff_alloc.h`
#include <unistd.h>
#include <sys/types.h>
#include <sys/param.h>
#include <time.h>
#include <pthread.h>
#include <errno.h>
#include <fcntl.h>
#include <string.h>
Functions
cache_content_entry_t * cache_content_new_entry (cache_entry_t *pentry_inode, cache_content_spec_data_t *pspecdata, cache_content_client_t *pclient, cache_content_add_behaviour_t how, fsal_op_context_t *pcontext, cache_content_status_t *pstatus)
Detailed Description
Management of the file content cache: adding a new entry.
Author:
Author deniel
Date:
Date 2005/11/28 17:02:32
Version:
Revision 1.12
cache_content_add_entry.c(p.) : Management of the file content cache: adding a new entry.
Definition in file cache_content_add_entry.c.
Function Documentation
cache_content_entry_t* cache_content_new_entry (cache_entry_t * pentry_inode, cache_content_spec_data_t * pspecdata, cache_content_client_t * pclient, cache_content_add_behaviour_t how, fsal_op_context_t * pcontext, cache_content_status_t * pstatus)
cache_content_new_entry: adds an entry to the file content cache.
Adds an entry to the file content cache. This routine should be called only from the cache_inode layer.
No lock management is done in this layer: the related pentry in the cache inode layer is locked and will prevent from concurent accesses.
Parameters:
pentry_inode [IN] entry in cache_inode layer for this file.
pspecdata [IN] pointer to the entry's specific data
pclient [IN] ressource allocated by the client for the nfs management. [OUT] returned status.
Returns: CACHE_CONTENT_SUCCESS is successful .
Definition at line 128 of file cache_content_add_entry.c.
References cache_content_create_name(), and cache_content_refresh().
Referenced by cache_content_crash_recover().