idmapper_cache.c File Reference
Id mapping functions.
#include `HashData.h`
#include `HashTable.h`
#include `log_functions.h`
#include `stuff_alloc.h`
#include `nfs_core.h`
#include `nfs_exports.h`
#include `config_parsing.h`
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <pwd.h>
#include <grp.h>
Functions
size_t strnlen (const char *s, size_t maxlen)
unsigned long idmapper_value_hash_func (hash_parameter_t *p_hparam, hash_buffer_t *buffclef)
unsigned long namemapper_value_hash_func (hash_parameter_t *p_hparam, hash_buffer_t *buffclef)
unsigned long idmapper_rbt_hash_func (hash_parameter_t *p_hparam, hash_buffer_t *buffclef)
unsigned long namemapper_rbt_hash_func (hash_parameter_t *p_hparam, hash_buffer_t *buffclef)
int compare_idmapper (hash_buffer_t *buff1, hash_buffer_t *buff2)
int compare_namemapper (hash_buffer_t *buff1, hash_buffer_t *buff2)
int display_idmapper_key (hash_buffer_t *pbuff, char *str)
int display_idmapper_val (hash_buffer_t *pbuff, char *str)
int idmap_uid_init (nfs_idmap_cache_parameter_t param)
int idmap_uname_init (nfs_idmap_cache_parameter_t param)
int idmap_gid_init (nfs_idmap_cache_parameter_t param)
int idmap_gname_init (nfs_idmap_cache_parameter_t param)
int idmap_compute_hash_value (char *name, uint32_t *phashval)
int idmap_add (hash_table_t *ht, char *key, unsigned int val)
int namemap_add (hash_table_t *ht, unsigned int key, char *val)
int uidmap_add (char *key, unsigned int val)
int unamemap_add (unsigned int key, char *val)
int gidmap_add (char *key, unsigned int val)
int gnamemap_add (unsigned int key, char *val)
int idmap_get (hash_table_t *ht, char *key, unsigned long *pval)
int namemap_get (hash_table_t *ht, unsigned int key, char *pval)
int uidmap_get (char *key, unsigned long *pval)
int unamemap_get (unsigned int key, char *val)
int gidmap_get (char *key, unsigned long *pval)
int gnamemap_get (unsigned int key, char *val)
int idmap_remove (hash_table_t *ht, char *key)
int namemap_remove (hash_table_t *ht, unsigned int key)
int uidmap_remove (char *key)
int unamemap_remove (unsigned int key)
int gidmap_remove (char *key)
int gnamemap_remove (unsigned int key)
int idmap_populate (char *path, idmap_type_t maptype)
void idmap_get_stats (idmap_type_t maptype, hash_stat_t *phstat, hash_stat_t *phstat_reverse)
Variables
hash_table_t * ht_pwnam
hash_table_t * ht_grnam
hash_table_t * ht_pwuid
hash_table_t * ht_grgid
nfs_parameter_t nfs_param
Detailed Description
Id mapping functions.
Author:
Author deniel
Date: $Date$
Version: $Revision$
idmapper_cache.c(p.) : Id mapping functions, passwd and groups cache management.
Definition in file idmapper_cache.c.
Function Documentation
int compare_idmapper (hash_buffer_t * buff1, hash_buffer_t * buff2)
compare_idmapper: compares the values stored in the key buffers.
Compares the values stored in the key buffers. This function is to be used as 'compare_key' field in the hashtable storing the nfs duplicated requests.
Parameters:
buff1 [IN] first key
buff2 [IN] second key
Returns: 0 if keys are identifical, 1 if they are different.
Definition at line 191 of file idmapper_cache.c.
int compare_namemapper (hash_buffer_t * buff1, hash_buffer_t * buff2)
Definition at line 196 of file idmapper_cache.c.
int display_idmapper_key (hash_buffer_t * pbuff, char * str)
display_idmapper_key: displays the entry key stored in the buffer.
Displays the entry key stored in the buffer. This function is to be used as 'key_to_str' field in the hashtable storing the id mapper stuff
Parameters:
buff1 [IN] buffer to display
buff2 [OUT] output string
Returns: number of character written.
Definition at line 218 of file idmapper_cache.c.
int display_idmapper_val (hash_buffer_t * pbuff, char * str)
display_idmapper_val: displays the entry key stored in the buffer.
Displays the entry key stored in the buffer. This function is to be used as 'val_to_str' field in the hashtable storing the id mapper stuff
Parameters:
buff1 [IN] buffer to display
buff2 [OUT] output string
Returns: number of character written.
Definition at line 237 of file idmapper_cache.c.
int gidmap_add (char * key, unsigned int val)
Definition at line 526 of file idmapper_cache.c.
References ht_grgid, ht_grnam, idmap_add(), and namemap_add().
Referenced by name2gid().
int gidmap_get (char * key, unsigned long * pval)
Definition at line 640 of file idmapper_cache.c.
References ht_grnam, and idmap_get().
Referenced by name2gid().
int gidmap_remove (char * key)
Definition at line 727 of file idmapper_cache.c.
References ht_grnam, and idmap_remove().
int gnamemap_add (unsigned int key, char * val)
Definition at line 542 of file idmapper_cache.c.
References ht_grgid, ht_grnam, idmap_add(), and namemap_add().
int gnamemap_get (unsigned int key, char * val)
Definition at line 646 of file idmapper_cache.c.
References ht_grgid, and namemap_get().
int gnamemap_remove (unsigned int key)
Definition at line 732 of file idmapper_cache.c.
References ht_grgid, and namemap_remove().
int idmap_add (hash_table_t * ht, char * key, unsigned int val)
idmap_add: Adds a value by key
Adss a value by key.
Parameters:
ht [INOUT] the hash table to be used
key [IN] the ip address requested
val [OUT] the value
Returns: ID_MAPPER_SUCCESS, ID_MAPPER_INSERT_MALLOC_ERROR, ID_MAPPER_INVALID_ARGUMENT
Definition at line 430 of file idmapper_cache.c.
Referenced by gidmap_add(), gnamemap_add(), idmap_populate(), uidmap_add(), and unamemap_add().
int idmap_compute_hash_value (char * name, uint32_t * phashval)
idmap_compute_hash_value: computes the hash value, based on the string.
Computes the computes the hash value, based on the string.
Definition at line 318 of file idmapper_cache.c.
References strnlen().
Referenced by idmapper_rbt_hash_func().
int idmap_get (hash_table_t * ht, char * key, unsigned long * pval)
idmap_get: gets a value by key
Gets a value by key.
Parameters:
ht [INOUT] the hash table to be used
key [IN] the ip address requested
hostname [OUT] the hostname
Returns: ID_MAPPER_SUCCESS or ID_MAPPER_NOT_FOUND
Definition at line 571 of file idmapper_cache.c.
Referenced by gidmap_get(), and uidmap_get().
void idmap_get_stats (idmap_type_t maptype, hash_stat_t * phstat, hash_stat_t * phstat_reverse)
idmap_get_stats: gets the hash table statistics for the idmap et the reverse id map
Gets the hash table statistics for the idmap et the reverse idmap.
Parameters:
maptype [IN] type of the mapping to be queried (should be UIDMAP_TYPE or GIDMAP_TYPE)
phstat [OUT] pointer to the resulting stats for direct map.
phstat [OUT] pointer to the resulting stats for reverse map.
Returns: nothing (void function)
See also: HashTable_GetStats
Definition at line 847 of file idmapper_cache.c.
int idmap_gid_init (nfs_idmap_cache_parameter_t param)
idmap_gid_init: Inits the hashtable for GID mapping.
Inits the hashtable for GID mapping.
Parameters:
param [IN] parameter used to init the gid map cache
Returns: 0 if successful, -1 otherwise
Definition at line 287 of file idmapper_cache.c.
References ht_grnam.
int idmap_gname_init (nfs_idmap_cache_parameter_t param)
Definition at line 298 of file idmapper_cache.c.
References ht_grgid.
int idmap_populate (char * path, idmap_type_t maptype)
idmap_populate_by_conf: Use the configuration file to populate the ID_MAPPER.
Use the configuration file to populate the ID_MAPPER.
Definition at line 745 of file idmapper_cache.c.
References idmap_add(), and namemap_add().
int idmap_remove (hash_table_t * ht, char * key)
idmap_remove: Tries to remove an entry for ID_MAPPER
Tries to remove an entry for ID_MAPPER
Parameters:
ht [INOUT] the hash table to be used
key [IN] the key uncached.
Returns: the delete status
Definition at line 664 of file idmapper_cache.c.
Referenced by gidmap_remove(), and uidmap_remove().
int idmap_uid_init (nfs_idmap_cache_parameter_t param)
idmap_uid_init: Inits the hashtable for UID mapping.
Inits the hashtable for UID mapping.
Parameters:
param [IN] parameter used to init the uid map cache
Returns: 0 if successful, -1 otherwise
Definition at line 254 of file idmapper_cache.c.
References ht_pwnam.
int idmap_uname_init (nfs_idmap_cache_parameter_t param)
Definition at line 265 of file idmapper_cache.c.
References ht_pwuid.
unsigned long idmapper_rbt_hash_func (hash_parameter_t * p_hparam, hash_buffer_t * buffclef)
idmapper_rbt_hash_func: computes the rbt value for the entry in the id mapper stuff.
Computes the rbt value for the entry in the id mapper stuff.
Parameters:
hparam [IN] hash table parameter.
buffcleff[in] pointer to the hash key buffer
Returns: the computed rbt value.
See also: HashTable_Init
Definition at line 163 of file idmapper_cache.c.
References idmap_compute_hash_value().
unsigned long idmapper_value_hash_func (hash_parameter_t * p_hparam, hash_buffer_t * buffclef)
idmapper_rbt_hash_func: computes the hash value for the entry in id mapper stuff
Computes the hash value for the entry in id mapper stuff. In fact, it just use addresse as value (identity function) modulo the size of the hash. This function is called internal in the HasTable_* function
Parameters:
hparam [IN] hash table parameter.
buffcleff[in] pointer to the hash key buffer
Returns: the computed hash value.
See also: HashTable_Init
Definition at line 132 of file idmapper_cache.c.
int namemap_add (hash_table_t * ht, unsigned int key, char * val)
Definition at line 461 of file idmapper_cache.c.
Referenced by gidmap_add(), gnamemap_add(), idmap_populate(), uidmap_add(), and unamemap_add().
int namemap_get (hash_table_t * ht, unsigned int key, char * pval)
Definition at line 599 of file idmapper_cache.c.
Referenced by gnamemap_get(), and unamemap_get().
int namemap_remove (hash_table_t * ht, unsigned int key)
Definition at line 689 of file idmapper_cache.c.
Referenced by gnamemap_remove(), and unamemap_remove().
unsigned long namemapper_rbt_hash_func (hash_parameter_t * p_hparam, hash_buffer_t * buffclef)
Definition at line 174 of file idmapper_cache.c.
unsigned long namemapper_value_hash_func (hash_parameter_t * p_hparam, hash_buffer_t * buffclef)
Definition at line 144 of file idmapper_cache.c.
size_t strnlen (const char * s, size_t maxlen)
Referenced by idmap_compute_hash_value(), and idmap_computer_hash_value().
int uidmap_add (char * key, unsigned int val)
Definition at line 494 of file idmapper_cache.c.
References ht_pwnam, ht_pwuid, idmap_add(), and namemap_add().
Referenced by name2uid().
int uidmap_get (char * key, unsigned long * pval)
Definition at line 628 of file idmapper_cache.c.
References ht_pwnam, and idmap_get().
Referenced by name2uid().
int uidmap_remove (char * key)
Definition at line 717 of file idmapper_cache.c.
References ht_pwnam, and idmap_remove().
int unamemap_add (unsigned int key, char * val)
Definition at line 510 of file idmapper_cache.c.
References ht_pwnam, ht_pwuid, idmap_add(), and namemap_add().
int unamemap_get (unsigned int key, char * val)
Definition at line 634 of file idmapper_cache.c.
References ht_pwuid, and namemap_get().
int unamemap_remove (unsigned int key)
Definition at line 722 of file idmapper_cache.c.
References ht_pwuid, and namemap_remove().
Variable Documentation
hash_table_t* ht_grgid
Definition at line 112 of file idmapper_cache.c.
Referenced by gidmap_add(), gnamemap_add(), gnamemap_get(), gnamemap_remove(), and idmap_gname_init().
hash_table_t* ht_grnam
Definition at line 110 of file idmapper_cache.c.
Referenced by gidmap_add(), gidmap_get(), gidmap_remove(), gnamemap_add(), and idmap_gid_init().
hash_table_t* ht_pwnam
Definition at line 109 of file idmapper_cache.c.
Referenced by idmap_uid_init(), uidmap_add(), uidmap_get(), uidmap_remove(), and unamemap_add().
hash_table_t* ht_pwuid
Definition at line 111 of file idmapper_cache.c.
Referenced by idmap_uname_init(), uidmap_add(), unamemap_add(), unamemap_get(), and unamemap_remove().
nfs_parameter_t nfs_param
Definition at line 47 of file test_idmapper.c.