idmapper.c File Reference
Id mapping functions.
#include <rpc/rpc.h>
#include <rpc/svc.h>
#include `nfs_core.h`
#include `nfs_tools.h`
#include <unistd.h>
#include <stdlib.h>
#include <strings.h>
#include <string.h>
#include <sys/types.h>
#include <pwd.h>
#include <grp.h>
Functions
int uid2name (char *name, uid_t uid)
int name2uid (char *name, uid_t *puid)
int gid2name (char *name, gid_t gid)
int name2gid (char *name, gid_t *pgid)
int uid2str (uid_t uid, char *str)
int gid2str (gid_t gid, char *str)
int uid2utf8 (uid_t uid, utf8string *utf8str)
int gid2utf8 (gid_t gid, utf8string *utf8str)
int utf82uid (utf8string *utf8str, uid_t *Uid)
int utf82gid (utf8string *utf8str, gid_t *Gid)
Detailed Description
Id mapping functions.
Author:
Author deniel
Date:
Date 2006/01/24 11:43:05
Version:
Revision 1.2
idmapper.c(p.) : Id mapping functions.
Definition in file idmapper.c.
Function Documentation
int gid2name (char * name, gid_t gid)
gid2name: convert a gid to a name.
convert a uid to a name.
Parameters:
name [OUT] the name of the user
gid [IN] the input gid
return 1 if successful, 0 otherwise
Definition at line 185 of file idmapper.c.
Referenced by gid2str().
int gid2str (gid_t gid, char * str)
gid2ustr: convert a gid to a string.
Convert a gidonvert a gid to a string. to a string.
Parameters:
gid [IN] the input gid
str [OUT] computed string
Returns: the length of the utf8 buffer if succesfull, -1 if failed
Definition at line 272 of file idmapper.c.
References gid2name().
Referenced by gid2utf8().
int gid2utf8 (gid_t gid, utf8string * utf8str)
gid2utf8: converts a gid to a utf8 string descriptor.
Converts a gid to a utf8 string descriptor.
Parameters:
gid [IN] the input gid
utf8str [OUT] computed UTF8 string descriptor
Returns: the length of the utf8 buffer if succesfull, -1 if failed
Definition at line 321 of file idmapper.c.
References gid2str().
int name2gid (char * name, gid_t * pgid)
name2gid: convert a name to a gid
convert a name to a gid
Parameters:
name [IN] the name of the user
pgid [OUT] the resulting gid
return 1 if successful, 0 otherwise
Definition at line 210 of file idmapper.c.
References gidmap_add(), and gidmap_get().
Referenced by utf82gid().
int name2uid (char * name, uid_t * puid)
name2uid: convert a name to a uid
convert a name to a uid
Parameters:
name [IN] the name of the user
puid [OUT] the resulting uid
return 1 if successful, 0 otherwise
Definition at line 143 of file idmapper.c.
References uidmap_add(), and uidmap_get().
Referenced by utf82uid().
int uid2name (char * name, uid_t uid)
uid2name: convert a uid to a name.
convert a uid to a name.
Parameters:
name [OUT] the name of the user
uid [IN] the input uid
return 1 if successful, 0 otherwise
Definition at line 120 of file idmapper.c.
Referenced by uid2str().
int uid2str (uid_t uid, char * str)
uid2ustr: convert a uid to a string.
Convert a gidonvert a uid to a string. to a string.
Parameters:
uid [IN] the input gid
str [OUT] computed string
Returns: the length of the utf8 buffer if succesfull, -1 if failed
Definition at line 250 of file idmapper.c.
References uid2name().
Referenced by uid2utf8().
int uid2utf8 (uid_t uid, utf8string * utf8str)
uid2utf8: converts a uid to a utf8 string descriptor.
Converts a uid to a utf8 string descriptor.
Parameters:
uid [IN] the input uid
utf8str [OUT] computed UTF8 string descriptor
Returns: the length of the utf8 buffer if succesfull, -1 if failed
Definition at line 296 of file idmapper.c.
References uid2str().
int utf82gid (utf8string * utf8str, gid_t * Gid)
utf82gid: converts a utf8 string descriptorto a gid .
Converts a utf8 string descriptor to a gid .
Parameters:
utf8str [IN] group's name as UTF8 string.
Gid [OUT] pointer to the computed gid.
Returns: 0 in all cases
Definition at line 380 of file idmapper.c.
References name2gid().
int utf82uid (utf8string * utf8str, uid_t * Uid)
utf82gid: converts a utf8 string descriptor to a uid .
Converts a utf8 string descriptor to a uid.
Parameters:
utf8str [IN] group's name as UTF8 string.
Uid [OUT] pointer to the computed uid.
Returns: 0 if successful, 0 otherwise.
Definition at line 345 of file idmapper.c.
References name2uid().