test_idmapper.c File Reference
#include <stdio.h>
#include <string.h>
#include <pthread.h>
#include <fcntl.h>
#include <sys/file.h>
#include <sys/resource.h>
#include <signal.h>
#include <gssapi/gssapi.h>
#include <rpc/rpc.h>
#include <rpc/svc.h>
#include <rpc/pmap_clnt.h>
#include `log_functions.h`
#include `stuff_alloc.h`
#include `fsal.h`
#include `nfs23.h`
#include `nfs4.h`
#include `mount.h`
#include `nfs_core.h`
#include `cache_inode.h`
#include `cache_content.h`
#include `nfs_file_handle.h`
#include `nfs_exports.h`
#include `nfs_tools.h`
#include `nfs_proto_functions.h`
#include `nfs_dupreq.h`
#include `config_parsing.h`
#include `SemN.h`
Functions
int idmap_computer_hash_value (char *name, uint32_t *phashval)
main (int argc, char *argv[])
Variables
nfs_parameter_t nfs_param
Function Documentation
int idmap_computer_hash_value (char * name, uint32_t * phashval)
Definition at line 49 of file test_idmapper.c.
References strnlen().
Referenced by main().
main (int argc, char * argv[])
Definition at line 151 of file test_idmapper.c.
References idmap_computer_hash_value().
Variable Documentation
nfs_parameter_t nfs_param
Definition at line 47 of file test_idmapper.c.