.TH "test_liblog_functions.c" 3 "31 Mar 2009" "Version 0.1" "Log Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_liblog_functions.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib.h>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include 'log_functions.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBERR_PIPO_1\fP   0"
.br
.ti -1c
.RI "#define \fBERR_PIPO_2\fP   1"
.br
.ti -1c
.RI "#define \fBNB_THREADS\fP   20"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBTest1\fP (void *arg)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define ERR_PIPO_1   0"
.PP
.SS "#define ERR_PIPO_2   1"
.PP
.SS "#define NB_THREADS   20"
.PP
Definition at line 174 of file test_liblog_functions.c.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"
.PP
Definition at line 176 of file test_liblog_functions.c.
.SS "void* Test1 (void * arg)"
.PP
Tests about Log streams and special printf functions. 
.PP
Definition at line 104 of file test_liblog_functions.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Log Library from the source code.
