.TH "test_lru.c" 3 "9 Apr 2008" "Version 0.1" "LRu List Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_lru.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <strings.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include 'BuddyMalloc.h'\fP
.br
\fC#include 'LRU_List.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBPREALLOC\fP   10000"
.br
.ti -1c
.RI "#define \fBMAXTEST\fP   10"
.br
.ti -1c
.RI "#define \fBKEPT_ENTRY\fP   5"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBprint_entry\fP (LRU_data_t data, char *str)"
.br
.ti -1c
.RI "int \fBclean_entry\fP (LRU_entry_t *pentry, void *addparam)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define KEPT_ENTRY   5"
.PP
Definition at line 123 of file test_lru.c.
.SS "#define MAXTEST   10"
.PP
Definition at line 122 of file test_lru.c.
.SS "#define PREALLOC   10000"
.PP
Definition at line 121 of file test_lru.c.
.SH "Function Documentation"
.PP 
.SS "int clean_entry (LRU_entry_t * pentry, void * addparam)"
.PP
Definition at line 130 of file test_lru.c.
.SS "int main (int argc, char * argv[])"
.PP
Definition at line 135 of file test_lru.c.
.PP
References LRU_gc_invalid(), LRU_Init(), LRU_invalidate(), LRU_new_entry(), and LRU_Print().
.SS "int print_entry (LRU_data_t data, char * str)"
.PP
Definition at line 125 of file test_lru.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for LRu List Library from the source code.
