.TH "test_configurable_lru.c" 3 "15 Sep 2010" "Version 0.1" "LRu List Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_configurable_lru.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <strings.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include 'BuddyMalloc.h'\fP
.br
\fC#include 'LRU_List.h'\fP
.br
\fC#include 'log_macros.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBLENBUF\fP   256"
.br
.ti -1c
.RI "#define \fBSTRSIZE\fP   10"
.br
.ti -1c
.RI "#define \fBPREALLOC\fP   1000000"
.br
.ti -1c
.RI "#define \fBMAXTEST\fP   1000000"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBdo_invalidate\fP (LRU_list_t *plru, int key)"
.br
.ti -1c
.RI "int \fBdo_new\fP (LRU_list_t *plru, int key)"
.br
.ti -1c
.RI "int \fBdo_gc\fP (LRU_list_t *plru)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "LRU_entry_t * \fBtabentry\fP [MAXTEST]"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define LENBUF   256"
.PP
Definition at line 63 of file test_configurable_lru.c.
.SS "#define MAXTEST   1000000"
.PP
Definition at line 66 of file test_configurable_lru.c.
.SS "#define PREALLOC   1000000"
.PP
Definition at line 65 of file test_configurable_lru.c.
.SS "#define STRSIZE   10"
.PP
Definition at line 64 of file test_configurable_lru.c.
.SH "Function Documentation"
.PP 
.SS "int do_gc (LRU_list_t * plru)"
.PP
Definition at line 116 of file test_configurable_lru.c.
.SS "int do_invalidate (LRU_list_t * plru, int key)"
.PP
Definition at line 81 of file test_configurable_lru.c.
.SS "int do_new (LRU_list_t * plru, int key)"
.PP
Definition at line 90 of file test_configurable_lru.c.
.SS "int main (int argc, char * argv[])"
.PP
Definition at line 121 of file test_configurable_lru.c.
.SH "Variable Documentation"
.PP 
.SS "LRU_entry_t* \fBtabentry\fP[MAXTEST]"
.PP
Definition at line 68 of file test_configurable_lru.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for LRu List Library from the source code.
