cache_inode_access.c File Reference
Check for object accessibility.
#include `LRU_List.h`
#include `log_functions.h`
#include `HashData.h`
#include `HashTable.h`
#include `fsal.h`
#include `cache_inode.h`
#include `stuff_alloc.h`
#include <unistd.h>
#include <sys/types.h>
#include <sys/param.h>
#include <time.h>
#include <pthread.h>
Functions
cache_inode_status_t cache_inode_access_sw (cache_entry_t *pentry, fsal_accessflags_t access_type, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus, int use_mutex)
cache_inode_status_t cache_inode_access_no_mutex (cache_entry_t *pentry, fsal_accessflags_t access_type, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus)
cache_inode_status_t cache_inode_access (cache_entry_t *pentry, fsal_accessflags_t access_type, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus)
Detailed Description
Check for object accessibility.
Author:
Author deniel
Date:
Date 2005/11/28 17:02:26
Version:
Revision 1.19
cache_inode_access.c(p.) : Check for object accessibility.
Definition in file cache_inode_access.c.
Function Documentation
cache_inode_status_t cache_inode_access (cache_entry_t * pentry, fsal_accessflags_t access_type, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus)
cache_inode_access: checks for an entry accessibility.
Checks for an entry accessibility.
Parameters:
pentry [IN] entry pointer for the fs object to be checked.
access_type [IN] flags used to describe the kind of access to be checked.
ht [INOUT] hash table used for the cache.
pclient [INOUT] ressource allocated by the client for the nfs management.
pcontext [IN] FSAL credentials
pstatus [OUT] returned status.
Returns: CACHE_INODE_SUCCESS if operation is a success
CACHE_INODE_LRU_ERROR if allocation error occured when validating the entry
Definition at line 277 of file cache_inode_access.c.
References cache_inode_access_sw().
cache_inode_status_t cache_inode_access_no_mutex (cache_entry_t * pentry, fsal_accessflags_t access_type, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus)
cache_inode_access_no_mutex: checks for an entry accessibility. No mutex management
Checks for an entry accessibility.
Parameters:
pentry [IN] entry pointer for the fs object to be checked.
access_type [IN] flags used to describe the kind of access to be checked.
ht [INOUT] hash table used for the cache.
pclient [INOUT] ressource allocated by the client for the nfs management.
pcontext [IN] FSAL credentials
pstatus [OUT] returned status.
Returns: CACHE_INODE_SUCCESS if operation is a success
CACHE_INODE_LRU_ERROR if allocation error occured when validating the entry
Definition at line 244 of file cache_inode_access.c.
References cache_inode_access_sw().
Referenced by cache_inode_lookup_sw(), and cache_inode_readdir().
cache_inode_status_t cache_inode_access_sw (cache_entry_t * pentry, fsal_accessflags_t access_type, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus, int use_mutex)
cache_inode_access: checks for an entry accessibility.
Checks for an entry accessibility.
Parameters:
pentry [IN] entry pointer for the fs object to be checked.
access_type [IN] flags used to describe the kind of access to be checked.
ht [INOUT] hash table used for the cache.
pclient [INOUT] ressource allocated by the client for the nfs management.
pcontext [IN] FSAL context
pstatus [OUT] returned status.
use_mutex [IN] a flag to tell if mutex are to be used or not.
Returns: CACHE_INODE_SUCCESS if operation is a success
CACHE_INODE_LRU_ERROR if allocation error occured when validating the entry
any other values show an unauthorized access.
Definition at line 123 of file cache_inode_access.c.
References cache_inode_error_convert(), cache_inode_get_attributes(), cache_inode_get_fsal_handle(), cache_inode_kill_entry(), and cache_inode_valid().
Referenced by cache_inode_access(), and cache_inode_access_no_mutex().