cache_inode_open_close.c File Reference
Removes an entry of any type.
#include `fsal.h`
#include `LRU_List.h`
#include `log_functions.h`
#include `HashData.h`
#include `HashTable.h`
#include `cache_inode.h`
#include `cache_content.h`
#include `stuff_alloc.h`
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/param.h>
#include <time.h>
#include <pthread.h>
#include <strings.h>
Functions
cache_inode_status_t cache_inode_open (cache_entry_t *pentry, cache_inode_client_t *pclient, fsal_openflags_t openflags, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus)
cache_inode_status_t cache_inode_open_by_name (cache_entry_t *pentry_dir, fsal_name_t *pname, cache_entry_t *pentry_file, cache_inode_client_t *pclient, fsal_openflags_t openflags, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus)
cache_inode_status_t cache_inode_close (cache_entry_t *pentry, cache_inode_client_t *pclient, cache_inode_status_t *pstatus)
Detailed Description
Removes an entry of any type.
vim:expandtab:shiftwidth=8:tabstop=8:
Copyright CEA/DAM/DIF (2008) contributeur : Philippe DENIEL philippe.deniel@cea.fr Thomas LEIBOVICI thomas.leibovici@cea.fr
Ce logiciel est un serveur implementant le protocole NFS.
Ce logiciel est regi par la licence CeCILL soumise au droit francais et respectant les principes de diffusion des logiciels libres. Vous pouvez utiliser, modifier et/ou redistribuer ce programme sous les conditions de la licence CeCILL telle que diffusee par le CEA, le CNRS et l'INRIA sur le site `http://www.cecill.info`.
En contrepartie de l'accessibilite au code source et des droits de copie, de modification et de redistribution accordes par cette licence, il n'est offert aux utilisateurs qu'une garantie limitee. Pour les memes raisons, seule une responsabilite restreinte pese sur l'auteur du programme, le titulaire des droits patrimoniaux et les concedants successifs.
A cet egard l'attention de l'utilisateur est attiree sur les risques associes au chargement, a l'utilisation, a la modification et/ou au developpement et a la reproduction du logiciel par l'utilisateur etant donne sa specificite de logiciel libre, qui peut le rendre complexe a manipuler et qui le reserve donc a des developpeurs et des professionnels avertis possedant des connaissances informatiques approfondies. Les utilisateurs sont donc invites a charger et tester l'adequation du logiciel a leurs besoins dans des conditions permettant d'assurer la securite de leurs systemes et ou de leurs donnees et, plus generalement, a l'utiliser et l'exploiter dans les memes conditions de securite.
Le fait que vous puissiez acceder a cet en-tete signifie que vous avez pris connaissance de la licence CeCILL, et que vous en avez accepte les termes.
---------------------
Copyright CEA/DAM/DIF (2005) Contributor: Philippe DENIEL philippe.deniel@cea.fr Thomas LEIBOVICI thomas.leibovici@cea.fr
This software is a server that implements the NFS protocol.
This software is governed by the CeCILL license under French law and abiding by the rules of distribution of free software. You can use, modify and/ or redistribute the software under the terms of the CeCILL license as circulated by CEA, CNRS and INRIA at the following URL `http://www.cecill.info`.
As a counterpart to the access to the source code and rights to copy, modify and redistribute granted by the license, users are provided only with a limited warranty and the software's author, the holder of the economic rights, and the successive licensors have only limited liability.
In this respect, the user's attention is drawn to the risks associated with loading, using, modifying and/or developing or reproducing the software by the user in light of its specific status of free software, that may mean that it is complicated to manipulate, and that also therefore means that it is reserved for developers and experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the software's suitability as regards their requirements in conditions enabling the security of their systems and/or data to be ensured and, more generally, to use and operate it in the same conditions as regards security.
The fact that you are presently reading this means that you have had knowledge of the CeCILL license and that you accept its terms. ---------------------------------------
Author:
Author deniel
Date:
Date 2005/11/28 17:02:27
Version:
Revision 1.20
cache_inode_rdwr.c(p.) : performs an IO on a REGULAR_FILE.
Definition in file cache_inode_open_close.c.
Function Documentation
cache_inode_status_t cache_inode_close (cache_entry_t * pentry, cache_inode_client_t * pclient, cache_inode_status_t * pstatus)
cache_inode_close: closes the local fd in the FSAL.
Closes the local fd in the FSAL.
No lock management is done in this layer: the related pentry in the cache inode layer is locked and will prevent from concurent accesses.
Parameters:
pentry [IN] entry in file content layer whose content is to be accessed.
pclient [IN] ressource allocated by the client for the nfs management. [OUT] returned status.
Returns: CACHE_CONTENT_SUCCESS is successful .
Definition at line 370 of file cache_inode_open_close.c.
References cache_inode_error_convert().
Referenced by cache_inode_rdwr(), and cache_inode_valid().
cache_inode_status_t cache_inode_open (cache_entry_t * pentry, cache_inode_client_t * pclient, fsal_openflags_t openflags, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus)
cache_content_open: opens the local fd on the cache.
Opens the fd on the FSAL
Parameters:
pentry [IN] entry in file content layer whose content is to be accessed.
pclient [IN] ressource allocated by the client for the nfs management.
openflags [IN] flags to be used to open the file
pcontent [IN] FSAL operation context [OUT] returned status.
Returns: CACHE_CONTENT_SUCCESS is successful .
Definition at line 126 of file cache_inode_open_close.c.
References cache_inode_error_convert().
Referenced by cache_inode_rdwr().
cache_inode_status_t cache_inode_open_by_name (cache_entry_t * pentry_dir, fsal_name_t * pname, cache_entry_t * pentry_file, cache_inode_client_t * pclient, fsal_openflags_t openflags, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus)
cache_content_open: opens the local fd on the cache.
Opens the fd on the FSAL
Parameters:
pentry_dir [IN] parent entry for the file
pname [IN] name of the file to be opened in the parent directory
pentry_file [IN] file entry to be opened
pclient [IN] ressource allocated by the client for the nfs management.
openflags [IN] flags to be used to open the file
pcontent [IN] FSAL operation context [OUT] returned status.
Returns: CACHE_CONTENT_SUCCESS is successful .
Definition at line 226 of file cache_inode_open_close.c.
References cache_inode_error_convert().