cache_inode_remove.c File Reference
Removes an entry of any type.
#include `LRU_List.h`
#include `log_functions.h`
#include `HashData.h`
#include `HashTable.h`
#include `fsal.h`
#include `cache_inode.h`
#include `cache_content.h`
#include `stuff_alloc.h`
#include <unistd.h>
#include <sys/types.h>
#include <sys/param.h>
#include <time.h>
#include <pthread.h>
Functions
cache_inode_status_t cache_inode_is_dir_empty (cache_entry_t *pentry)
cache_inode_status_t cache_inode_is_dir_empty_WithLock (cache_entry_t *pentry)
cache_inode_status_t cache_inode_remove_sw (cache_entry_t *pentry, fsal_name_t *pnode_name, fsal_attrib_list_t *pattr, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus, int use_mutex)
cache_inode_status_t cache_inode_remove_no_mutex (cache_entry_t *pentry, fsal_name_t *pnode_name, fsal_attrib_list_t *pattr, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus)
cache_inode_status_t cache_inode_remove (cache_entry_t *pentry, fsal_name_t *pnode_name, fsal_attrib_list_t *pattr, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus)
Detailed Description
Removes an entry of any type.
Author:
Author leibovic
Date:
Date 2006/01/31 10:18:58
Version:
Revision 1.32
Definition in file cache_inode_remove.c.
Function Documentation
cache_inode_status_t cache_inode_is_dir_empty (cache_entry_t * pentry)
cache_inode_is_dir_empty: checks if a directory is empty or not. No mutex management.
Checks if a directory is empty or not. No mutex management
Parameters:
pentry [IN] entry to be checked (should be of type DIR_BEGINNING)
Returns: CACHE_INODE_SUCCESS is directory is empty
CACHE_INODE_BAD_TYPE is pentry is not of type DIR_BEGINNING
CACHE_INODE_DIR_NOT_EMPTY if pentry is a non empty DIR_BEGINNING
Definition at line 46 of file cache_inode_remove.c.
Referenced by cache_inode_gc_suppress_directory(), cache_inode_is_dir_empty_WithLock(), cache_inode_remove_sw(), cache_inode_rename(), and cache_inode_type_are_rename_compatible().
cache_inode_status_t cache_inode_is_dir_empty_WithLock (cache_entry_t * pentry)
cache_inode_is_dir_empty_WithLock: checks if a directory is empty or not, BUT has lock management.
Checks if a directory is empty or not, BUT has lock management.
Parameters:
pentry [IN] entry to be checked (should be of type DIR_BEGINNING)
Returns: CACHE_INODE_SUCCESS is directory is empty
CACHE_INODE_BAD_TYPE is pentry is not of type DIR_BEGINNING
CACHE_INODE_DIR_NOT_EMPTY if pentry is a non empty DIR_BEGINNING
Definition at line 106 of file cache_inode_remove.c.
References cache_inode_is_dir_empty().
cache_inode_status_t cache_inode_remove (cache_entry_t * pentry, fsal_name_t * pnode_name, fsal_attrib_list_t * pattr, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus)
cache_inode_remove: removes a pentry addressed by its parent pentry and its FSAL name.
Removes a pentry addressed by its parent pentry and its FSAL name.
Parameters:
pentry [IN] entry for the parent directory to be managed.
name [IN] name of the entry that we are looking for in the cache.
pattr [OUT] attributes for the entry that we have found.
ht [IN] hash table used for the cache, unused in this call.
pclient [INOUT] ressource allocated by the client for the nfs management.
pcontext [IN] FSAL credentials
pstatus [OUT] returned status.
Returns: CACHE_INODE_SUCCESS if operation is a success
CACHE_INODE_LRU_ERROR if allocation error occured when validating the entry
Parameters:
pentry Parent entry
Definition at line 539 of file cache_inode_remove.c.
References cache_inode_remove_sw().
cache_inode_status_t cache_inode_remove_no_mutex (cache_entry_t * pentry, fsal_name_t * pnode_name, fsal_attrib_list_t * pattr, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus)
cache_inode_remove_no_mutex: removes a pentry addressed by its parent pentry and its FSAL name. No mutex management.
Removes a pentry addressed by its parent pentry and its FSAL name.
Parameters:
pentry [IN] entry for the parent directory to be managed.
name [IN] name of the entry that we are looking for in the cache.
pattr [OUT] attributes for the entry that we have found.
ht [IN] hash table used for the cache, unused in this call.
pclient [INOUT] ressource allocated by the client for the nfs management.
pcontext [IN] FSAL credentials
pstatus [OUT] returned status.
Returns: CACHE_INODE_SUCCESS if operation is a success
CACHE_INODE_LRU_ERROR if allocation error occured when validating the entry
Parameters:
pentry Parent entry
Definition at line 502 of file cache_inode_remove.c.
References cache_inode_remove_sw().
Referenced by cache_inode_rename().
cache_inode_status_t cache_inode_remove_sw (cache_entry_t * pentry, fsal_name_t * pnode_name, fsal_attrib_list_t * pattr, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus, int use_mutex)
cache_inode_remove_sw: removes a pentry addressed by its parent pentry and its FSAL name. Mutex management is switched.
Removes a pentry addressed by its parent pentry and its FSAL name. Mutex management is switched.
Parameters:
pentry [IN] entry for the parent directory to be managed.
name [IN] name of the entry that we are looking for in the cache.
pattr [OUT] attributes for the entry that we have found.
ht [IN] hash table used for the cache, unused in this call.
pclient [INOUT] ressource allocated by the client for the nfs management.
pcontext [IN] FSAL credentials
pstatus [OUT] returned status.
Returns: CACHE_INODE_SUCCESS if operation is a success
CACHE_INODE_LRU_ERROR if allocation error occured when validating the entry
Parameters:
pentry Parent entry
Definition at line 136 of file cache_inode_remove.c.
References cache_inode_error_convert(), cache_inode_fsaldata_2_key(), cache_inode_get_fsal_handle(), cache_inode_is_dir_empty(), cache_inode_kill_entry(), cache_inode_lookup_sw(), cache_inode_mutex_destroy(), cache_inode_release_fsaldata_key(), cache_inode_remove_cached_dirent(), and cache_inode_valid().
Referenced by cache_inode_remove(), and cache_inode_remove_no_mutex().