cache_inode_setattr.c File Reference
Sets the attributes for an entry.
#include `LRU_List.h`
#include `log_functions.h`
#include `HashData.h`
#include `HashTable.h`
#include `fsal.h`
#include `cache_inode.h`
#include `stuff_alloc.h`
#include <unistd.h>
#include <sys/types.h>
#include <sys/param.h>
#include <time.h>
#include <pthread.h>
Functions
cache_inode_status_t cache_inode_setattr (cache_entry_t *pentry, fsal_attrib_list_t *pattr, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus)
Detailed Description
Sets the attributes for an entry.
Author:
Author leibovic
Date:
Date 2006/02/14 11:47:40
Version:
Revision 1.19
cache_inode_setattr.c(p.) : Sets the attributes for an entry.
Definition in file cache_inode_setattr.c.
Function Documentation
cache_inode_status_t cache_inode_setattr (cache_entry_t * pentry, fsal_attrib_list_t * pattr, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus)
cache_inode_setattrs: set the attributes for an entry located in the cache by its address.
Sets the attributes for an entry located in the cache by its address. Attributes are provided with compliance to the underlying FSAL semantics. Attributes that are set are returned in `*pattr`.
Parameters:
pentry_parent [IN] entry for the parent directory to be managed.
pattr [INOUT] attributes for the entry that we have found. Out: attributes set.
ht [INOUT] hash table used for the cache, unused in this call.
pclient [INOUT] ressource allocated by the client for the nfs management.
pcontext [IN] FSAL credentials
pstatus [OUT] returned status.
Returns: CACHE_INODE_SUCCESS if operation is a success
CACHE_INODE_LRU_ERROR if allocation error occured when validating the entry
Definition at line 124 of file cache_inode_setattr.c.
References cache_inode_error_convert(), cache_inode_kill_entry(), and cache_inode_valid().