cache_inode_truncate.c File Reference
Truncates a regular file.
#include `fsal.h`
#include `LRU_List.h`
#include `log_functions.h`
#include `HashData.h`
#include `HashTable.h`
#include `cache_inode.h`
#include `cache_content.h`
#include <unistd.h>
#include <sys/types.h>
#include <sys/param.h>
#include <time.h>
#include <pthread.h>
Functions
cache_inode_status_t cache_inode_truncate_sw (cache_entry_t *pentry, fsal_size_t length, fsal_attrib_list_t *pattr, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus, int use_mutex)
cache_inode_status_t cache_inode_truncate_no_mutex (cache_entry_t *pentry, fsal_size_t length, fsal_attrib_list_t *pattr, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus)
cache_inode_status_t cache_inode_truncate (cache_entry_t *pentry, fsal_size_t length, fsal_attrib_list_t *pattr, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus)
Detailed Description
Truncates a regular file.
Author:
Author deniel
Date:
Date 2005/11/28 17:02:28
Version:
Revision 1.19
cache_inode_truncate.c(p.) : Truncates a regular file.
Definition in file cache_inode_truncate.c.
Function Documentation
cache_inode_status_t cache_inode_truncate (cache_entry_t * pentry, fsal_size_t length, fsal_attrib_list_t * pattr, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus)
cache_inode_truncate: truncates a regular file specified by its cache entry.
Truncates a regular file specified by its cache entry.
Parameters:
pentry [INOUT] entry pointer for the fs object to be truncated.
length [IN] wanted length for the file.
pattr [OUT] attrtibutes for the file after the operation.
ht [INOUT] hash table used for the cache. Unused in this call (kept for protototype's homogeneity).
pclient [INOUT] ressource allocated by the client for the nfs management.
pcontext [IN] FSAL credentials
pstatus [OUT] returned status.
Returns: CACHE_INODE_SUCCESS if operation is a success
CACHE_INODE_LRU_ERROR if allocation error occured when validating the entry
Definition at line 298 of file cache_inode_truncate.c.
References cache_inode_truncate_sw().
cache_inode_status_t cache_inode_truncate_no_mutex (cache_entry_t * pentry, fsal_size_t length, fsal_attrib_list_t * pattr, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus)
cache_inode_truncate_no_mutex: truncates a regular file specified by its cache entry (no mutex management).
Truncates a regular file specified by its cache entry.
Parameters:
pentry [INOUT] entry pointer for the fs object to be truncated.
length [IN] wanted length for the file.
pattr [OUT] attrtibutes for the file after the operation.
ht [INOUT] hash table used for the cache. Unused in this call (kept for protototype's homogeneity).
pclient [INOUT] ressource allocated by the client for the nfs management.
pcontext [IN] FSAL credentials
pstatus [OUT] returned status.
Returns: CACHE_INODE_SUCCESS if operation is a success
CACHE_INODE_LRU_ERROR if allocation error occured when validating the entry
Definition at line 262 of file cache_inode_truncate.c.
References cache_inode_truncate_sw().
cache_inode_status_t cache_inode_truncate_sw (cache_entry_t * pentry, fsal_size_t length, fsal_attrib_list_t * pattr, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus, int use_mutex)
cache_inode_truncate_sw: truncates a regular file specified by its cache entry.
Truncates a regular file specified by its cache entry.
Parameters:
pentry [INOUT] entry pointer for the fs object to be truncated.
length [IN] wanted length for the file.
pattr [OUT] attrtibutes for the file after the operation.
ht [INOUT] hash table used for the cache. Unused in this call (kept for protototype's homogeneity).
pclient [INOUT] ressource allocated by the client for the nfs management.
pcontext [IN] FSAL credentials
pstatus [OUT] returned status.
use_mutex [IN] if TRUE, mutex management is done, not if equal to FALSE.
Returns: CACHE_INODE_SUCCESS if operation is a success
CACHE_INODE_LRU_ERROR if allocation error occured when validating the entry
Definition at line 126 of file cache_inode_truncate.c.
References cache_inode_error_convert(), cache_inode_kill_entry(), and cache_inode_valid().
Referenced by cache_inode_truncate(), and cache_inode_truncate_no_mutex().