cache_inode_readlink.c File Reference
Reads a symlink.
#include `LRU_List.h`
#include `log_functions.h`
#include `HashData.h`
#include `HashTable.h`
#include `fsal.h`
#include `cache_inode.h`
#include <unistd.h>
#include <sys/types.h>
#include <sys/param.h>
#include <time.h>
#include <pthread.h>
Functions
cache_inode_status_t cache_inode_readlink (cache_entry_t *pentry, fsal_path_t *plink_content, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus)
Detailed Description
Reads a symlink.
Author:
Author deniel
Date:
Date 2005/12/05 09:02:36
Version:
Revision 1.16
cache_inode_readlink.c(p.) : Reads a symlink.
Definition in file cache_inode_readlink.c.
Function Documentation
cache_inode_status_t cache_inode_readlink (cache_entry_t * pentry, fsal_path_t * plink_content, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus)
Definition at line 104 of file cache_inode_readlink.c.
References cache_inode_error_convert(), cache_inode_kill_entry(), cache_inode_renew_entry(), and cache_inode_valid().