cache_inode_release.c File Reference
Release an entry.
#include `LRU_List.h`
#include `log_functions.h`
#include `HashData.h`
#include `HashTable.h`
#include `fsal.h`
#include `cache_inode.h`
#include `stuff_alloc.h`
#include <unistd.h>
#include <sys/types.h>
#include <sys/param.h>
#include <time.h>
#include <pthread.h>
Functions
cache_inode_status_t cache_inode_release (cache_entry_t *pentry, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus)
Detailed Description
Release an entry.
Author:
Author deniel
Date:
Date 2005/12/20 10:51:50
Version:
Revision 1.10
cache_inode_release.c(p.) : Release an entry.
Definition in file cache_inode_release.c.
Function Documentation
cache_inode_status_t cache_inode_release (cache_entry_t * pentry, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus)
Definition at line 107 of file cache_inode_release.c.
References cache_inode_fsaldata_2_key(), cache_inode_get_fsal_handle(), cache_inode_mutex_destroy(), and cache_inode_release_fsaldata_key().