cache_inode_getattr.c File Reference
Gets the attributes for an entry.
#include `LRU_List.h`
#include `log_functions.h`
#include `HashData.h`
#include `HashTable.h`
#include `fsal.h`
#include `cache_inode.h`
#include `stuff_alloc.h`
#include <unistd.h>
#include <sys/types.h>
#include <sys/param.h>
#include <time.h>
#include <pthread.h>
Functions
cache_inode_status_t cache_inode_getattr (cache_entry_t *pentry, fsal_attrib_list_t *pattr, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus)
Detailed Description
Gets the attributes for an entry.
Author:
Author deniel
Date:
Date 2005/11/28 17:02:26
Version:
Revision 1.17
cache_inode_getattr.c(p.) : Gets the attributes for an entry.
Definition in file cache_inode_getattr.c.
Function Documentation
cache_inode_status_t cache_inode_getattr (cache_entry_t * pentry, fsal_attrib_list_t * pattr, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus)
cache_inode_getattr: Gets the attributes for a cached entry.
Gets the attributes for a cached entry. The FSAL attributes are kept in a structure when the entry is added to the cache.
Parameters:
pentry [IN] entry to be managed.
pattr [OUT] pointer to the results
ht [IN] hash table used for the cache, unused in this call.
pclient [INOUT] ressource allocated by the client for the nfs management.
pcontext [IN] FSAL credentials
pstatus [OUT] returned status.
Returns: CACHE_INODE_SUCCESS if operation is a success
CACHE_INODE_LRU_ERROR if allocation error occured when validating the entry
Definition at line 123 of file cache_inode_getattr.c.
References cache_inode_error_convert(), cache_inode_get_attributes(), cache_inode_kill_entry(), cache_inode_renew_entry(), cache_inode_set_attributes(), and cache_inode_valid().