cache_inode_rename.c File Reference
Renames an entry.
#include `LRU_List.h`
#include `log_functions.h`
#include `HashData.h`
#include `HashTable.h`
#include `fsal.h`
#include `cache_inode.h`
#include <unistd.h>
#include <sys/types.h>
#include <sys/param.h>
#include <time.h>
#include <pthread.h>
Functions
cache_inode_status_t cache_inode_rename_cached_dirent (cache_entry_t *pentry_parent, fsal_name_t *oldname, fsal_name_t *newname, hash_table_t *ht, cache_inode_client_t *pclient, cache_inode_status_t *pstatus)
cache_inode_status_t cache_inode_rename (cache_entry_t *pentry_dirsrc, fsal_name_t *poldname, cache_entry_t *pentry_dirdest, fsal_name_t *pnewname, fsal_attrib_list_t *pattr_src, fsal_attrib_list_t *pattr_dst, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus)
Detailed Description
Renames an entry.
Author:
Author deniel
Date:
Date 2005/11/28 17:02:27
Version:
Revision 1.20
cache_inode_rename.c(p.) : Renames an entry.
Definition in file cache_inode_rename.c.
Function Documentation
cache_inode_status_t cache_inode_rename (cache_entry_t * pentry_dirsrc, fsal_name_t * poldname, cache_entry_t * pentry_dirdest, fsal_name_t * pnewname, fsal_attrib_list_t * pattr_src, fsal_attrib_list_t * pattr_dst, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus)
cache_inode_rename: renames an entry in the cache.
Renames an entry in the cache. This operation is used for moving an object into a different directory.
Parameters:
pentry_dirsrc [IN] entry pointer for the source directory
newname [IN] name of the object in the source directory
pentry_dirdest [INOUT] entry pointer for the destination directory in which the object will be moved.
newname [IN] name of the object in the destination directory
pattr_src [OUT] contains the source directory attributes if not NULL
pattr_dst [OUT] contains the destination directory attributes if not NULL
ht [INOUT] hash table used for the cache.
pclient [INOUT] ressource allocated by the client for the nfs management.
pcontext [IN] FSAL credentials
pstatus [OUT] returned status.
Returns: CACHE_INODE_SUCCESS operation is a success
CACHE_INODE_LRU_ERROR allocation error occured when validating the entry
CACHE_INODE_NOT_FOUND source object does not exist
Definition at line 179 of file cache_inode_rename.c.
References cache_inode_add_cached_dirent(), cache_inode_error_convert(), cache_inode_is_dir_empty(), cache_inode_kill_entry(), cache_inode_lookup_no_mutex(), cache_inode_remove_cached_dirent(), cache_inode_remove_no_mutex(), cache_inode_rename_cached_dirent(), and cache_inode_valid().
cache_inode_status_t cache_inode_rename_cached_dirent (cache_entry_t * pentry_parent, fsal_name_t * oldname, fsal_name_t * newname, hash_table_t * ht, cache_inode_client_t * pclient, cache_inode_status_t * pstatus)
cache_inode_rename_cached_dirent: renames an entry in the same directory.
Renames an entry in the same directory.
Parameters:
pentry_parent [INOUT] cache entry representing the directory to be managed.
oldname [IN] name of the entry to rename.
newname [IN] new name for the entry
ht [IN] hash table used for the cache, unused in this call.
pclient [INOUT] ressource allocated by the client for the nfs management.
pstatus [OUT] returned status.
Returns: the same as *pstatus
Definition at line 122 of file cache_inode_rename.c.
References cache_inode_operate_cached_dirent().
Referenced by cache_inode_rename().