cache_inode_create.c File Reference
Creation of a file through the cache layer.
#include `LRU_List.h`
#include `log_functions.h`
#include `HashData.h`
#include `HashTable.h`
#include `fsal.h`
#include `cache_inode.h`
#include `stuff_alloc.h`
#include <unistd.h>
#include <sys/types.h>
#include <sys/param.h>
#include <time.h>
#include <pthread.h>
Functions
cache_entry_t * cache_inode_create (cache_entry_t *pentry_parent, fsal_name_t *pname, cache_inode_file_type_t type, fsal_accessmode_t mode, cache_inode_create_arg_t *pcreate_arg, fsal_attrib_list_t *pattr, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus)
Detailed Description
Creation of a file through the cache layer.
Author:
Author deniel
Date:
Date 2005/11/28 17:02:26
Version:
Revision 1.29
cache_inode_mkdir.c : Creation of an entry through the cache layer
Definition in file cache_inode_create.c.
Function Documentation
cache_entry_t* cache_inode_create (cache_entry_t * pentry_parent, fsal_name_t * pname, cache_inode_file_type_t type, fsal_accessmode_t mode, cache_inode_create_arg_t * pcreate_arg, fsal_attrib_list_t * pattr, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus)
Definition at line 107 of file cache_inode_create.c.
References cache_inode_add_cached_dirent(), cache_inode_error_convert(), cache_inode_kill_entry(), cache_inode_lookup(), cache_inode_new_entry(), cache_inode_readdir_populate(), and cache_inode_valid().