cache_inode_rdwr.c File Reference
Removes an entry of any type.
#include `fsal.h`
#include `LRU_List.h`
#include `log_functions.h`
#include `HashData.h`
#include `HashTable.h`
#include `cache_inode.h`
#include `cache_content.h`
#include `stuff_alloc.h`
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/param.h>
#include <time.h>
#include <pthread.h>
Functions
cache_inode_status_t cache_inode_rdwr (cache_entry_t *pentry, cache_inode_io_direction_t read_or_write, fsal_seek_t *seek_descriptor, fsal_size_t buffer_size, fsal_size_t *pio_size, fsal_attrib_list_t *pfsal_attr, caddr_t buffer, fsal_boolean_t *p_fsal_eof, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus)
Detailed Description
Removes an entry of any type.
Author:
Author deniel
Date:
Date 2005/11/28 17:02:27
Version:
Revision 1.20
cache_inode_rdwr.c(p.) : performs an IO on a REGULAR_FILE.
Definition in file cache_inode_rdwr.c.
Function Documentation
cache_inode_status_t cache_inode_rdwr (cache_entry_t * pentry, cache_inode_io_direction_t read_or_write, fsal_seek_t * seek_descriptor, fsal_size_t buffer_size, fsal_size_t * pio_size, fsal_attrib_list_t * pfsal_attr, caddr_t buffer, fsal_boolean_t * p_fsal_eof, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus)
cache_inode_rdwr: Reads/Writes through the cache layer.
Reads/Writes through the cache layer.
Parameters:
pentry [IN] entry in cache inode layer whose content is to be accessed.
read_or_write [IN] a flag of type cache_content_io_direction_t to tell if a read or write is to be done.
seek_descriptor [IN] absolute position (in the FSAL file) where the IO will be done.
buffer_size [IN] size of the buffer pointed by parameter 'buffer'.
pio_size [OUT] the size of the io that was successfully made.
pfsal_attr [OUT] the FSAL attributes after the operation.
buffer write:[IN] read:[OUT] the buffer for the data.
ht [INOUT] the hashtable used for managing the cache.
pclient [IN] ressource allocated by the client for the nfs management.
pcontext [IN] fsal context for the operation. [OUT] returned status.
Returns: CACHE_CONTENT_SUCCESS is successful .
Todo : BUGAZEOMEU; gestion de la taille du fichier a prendre en compte.
Definition at line 133 of file cache_inode_rdwr.c.
References cache_inode_close(), cache_inode_error_convert(), cache_inode_open(), and cache_inode_valid().