cache_inode_renew_entry.c File Reference
Renews an entry in the cache inode.
#include `LRU_List.h`
#include `log_functions.h`
#include `HashData.h`
#include `HashTable.h`
#include `fsal.h`
#include `cache_inode.h`
#include `stuff_alloc.h`
#include <unistd.h>
#include <sys/types.h>
#include <sys/param.h>
#include <time.h>
#include <pthread.h>
Functions
cache_inode_status_t cache_inode_renew_entry (cache_entry_t *pentry, fsal_attrib_list_t *pattr, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus)
Detailed Description
Renews an entry in the cache inode.
Author:
Author leibovic
Date:
Date 2006/02/16 08:22:29
Version:
Revision 1.13
cache_inode_renew_entry.c(p.) : Renews an entry in the cache inode.
Definition in file cache_inode_renew_entry.c.
Function Documentation
cache_inode_status_t cache_inode_renew_entry (cache_entry_t * pentry, fsal_attrib_list_t * pattr, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus)
cache_inode_renew_entry: Renews the attributes for an entry.
Sets the attributes for an entry located in the cache by its address. Attributes are provided with compliance to the underlying FSAL semantics. Attributes that are set are returned in `*pattr`.
Parameters:
pentry_parent [IN] entry for the parent directory to be managed.
pattr [OUT] renewed attributes for the entry that we have found.
pclient [INOUT] ressource allocated by the client for the nfs management.
pcontext [IN] FSAL credentials
pstatus [OUT] returned status.
Returns: CACHE_INODE_SUCCESS if operation is a success
Other errors shows a FSAL error.
Definition at line 123 of file cache_inode_renew_entry.c.
References cache_inode_error_convert(), and cache_inode_kill_entry().
Referenced by cache_inode_getattr(), cache_inode_lookupp_sw(), cache_inode_readdir(), and cache_inode_readlink().