cache_inode_readdir.c File Reference
Reads the content of a directory.
#include `LRU_List.h`
#include `log_functions.h`
#include `HashData.h`
#include `HashTable.h`
#include `stuff_alloc.h`
#include `fsal.h`
#include `cache_inode.h`
#include <unistd.h>
#include <sys/types.h>
#include <sys/param.h>
#include <time.h>
#include <pthread.h>
Functions
cache_entry_t * cache_inode_operate_cached_dirent (cache_entry_t *pentry_parent, fsal_name_t *pname, fsal_name_t *newname, cache_inode_dirent_op_t dirent_op, cache_inode_status_t *pstatus)
cache_inode_status_t cache_inode_add_cached_dirent (cache_entry_t *pentry_parent, fsal_name_t *pname, cache_entry_t *pentry_added, cache_entry_t **ppentry_next, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus)
cache_inode_status_t cache_inode_invalidate_all_cached_dirent (cache_entry_t *pentry_dir, hash_table_t *ht, cache_inode_client_t *pclient, cache_inode_status_t *pstatus)
cache_inode_status_t cache_inode_remove_cached_dirent (cache_entry_t *pentry_parent, fsal_name_t *pname, hash_table_t *ht, cache_inode_client_t *pclient, cache_inode_status_t *pstatus)
cache_inode_status_t cache_inode_readdir_populate (cache_entry_t *pentry_dir, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus)
cache_inode_status_t cache_inode_readdir (cache_entry_t *dir_pentry, unsigned int cookie, unsigned int nbwanted, unsigned int *pnbfound, unsigned int *pend_cookie, cache_inode_endofdir_t *peod_met, cache_inode_dir_entry_t *dirent_array, unsigned int *cookie_array, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus)
Detailed Description
Reads the content of a directory.
Author:
Author deniel
Date:
Date 2006/01/24 11:43:05
Version:
Revision 1.50
cache_inode_readdir.c(p.) : Reads the content of a directory. Contains also the needed function for directory browsing.
Definition in file cache_inode_readdir.c.
Function Documentation
cache_inode_status_t cache_inode_add_cached_dirent (cache_entry_t * pentry_parent, fsal_name_t * pname, cache_entry_t * pentry_added, cache_entry_t ** ppentry_next, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus)
cache_inode_add_cached_dirent: Adds a directory entry to a cached directory.
Adds a directory entry to a cached directory. This is use when creating a new entry through nfs and keep it to the cache. It also allocates and caches the entry. This function can be call iteratively, within a loop (like what is done in cache_inode_readdir_populate). In this case, pentry_parent should be set to the value returned in *pentry_next. This function should never be used for managing a junction.
Parameters:
pentry_parent [INOUT] cache entry representing the directory to be managed.
name [IN] name of the entry to add.
pentry_added [IN] the pentry added to the dirent array
pentry_next [OUT] the next pentry to use for next call.
ht [IN] hash table used for the cache, unused in this call.
pclient [INOUT] ressource allocated by the client for the nfs management.
pstatus [OUT] returned status.
Returns: the DIR_CONTINUE or DIR_BEGINNING that contain this entry in its array_dirent
NULL if failed, see *pstatus for error's meaning.
Definition at line 343 of file cache_inode_readdir.c.
References cache_inode_new_entry().
Referenced by cache_inode_create(), cache_inode_link(), cache_inode_lookup_sw(), cache_inode_readdir_populate(), and cache_inode_rename().
cache_inode_status_t cache_inode_invalidate_all_cached_dirent (cache_entry_t * pentry_dir, hash_table_t * ht, cache_inode_client_t * pclient, cache_inode_status_t * pstatus)
Definition at line 608 of file cache_inode_readdir.c.
Referenced by cache_inode_readdir_populate().
cache_entry_t* cache_inode_operate_cached_dirent (cache_entry_t * pentry_parent, fsal_name_t * pname, fsal_name_t * newname, cache_inode_dirent_op_t dirent_op, cache_inode_status_t * pstatus)
cache_inode_operate_cached_dirent: locates a dirent in the cached dirent, and perform an operation on it.
Looks up for an dirent in the cached dirent. Thus function searches only in the entries listed in the dir_entries array. Some entries may be missing but existing and not be cached (it no readdir was never performed on the entry for example. This function provides a way to operate on the dirent.
Parameters:
pentry_parent [IN] directory entry to be looked.
name [IN] name for the searched entry.
newname [IN] newname if function is used to rename a dirent
dirent_op [IN] operation (ADD, LOOKUP or REMOVE) to do on the dirent if found. [OUT] returned status.
Returns: the found entry if its exists and NULL if it is not in the dirent arrays. REMOVE always returns NULL.
Definition at line 123 of file cache_inode_readdir.c.
References cache_inode_error_convert().
Referenced by cache_inode_remove_cached_dirent(), and cache_inode_rename_cached_dirent().
cache_inode_status_t cache_inode_readdir (cache_entry_t * dir_pentry, unsigned int cookie, unsigned int nbwanted, unsigned int * pnbfound, unsigned int * pend_cookie, cache_inode_endofdir_t * peod_met, cache_inode_dir_entry_t * dirent_array, unsigned int * cookie_array, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus)
cache_inode_readdir: Reads partially a directory.
Looks up for a name in a directory indicated by a cached entry. The directory should have been cached before. This is the only function in the cache_inode_readdir.c(p.) file that manages MT safety on a dir chain.
Parameters:
pentry [IN] entry for the parent directory to be read.
cookie [IN] cookie for the readdir operation (basically the offset).
nbwanted [IN] Maximum number of directory entries wanted.
peod_met [OUT] A flag to know if end of directory was met during this call.
dirent_array [OUT] the resulting array of found directory entries.
ht [IN] hash table used for the cache, unused in this call.
pclient [INOUT] ressource allocated by the client for the nfs management.
pcontext [IN] FSAL credentials
pstatus [OUT] returned status.
Returns: CACHE_INODE_SUCCESS if operation is a success
CACHE_INODE_BAD_TYPE if entry is not related to a directory
CACHE_INODE_LRU_ERROR if allocation error occured when validating the entry
Definition at line 976 of file cache_inode_readdir.c.
References cache_inode_access_no_mutex(), cache_inode_readdir_populate(), cache_inode_renew_entry(), and cache_inode_valid().
Referenced by main().
cache_inode_status_t cache_inode_readdir_populate (cache_entry_t * pentry_dir, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus)
cache_inode_readdir_populate: fully reads a directory in FSAL and caches the related entries.
fully reads a directory in FSAL and caches the related entries. No MT safety managed here !!
Parameters:
pentry [IN] entry for the parent directory to be read. This must be a DIR_BEGINNING
ht [IN] hash table used for the cache, unused in this call.
pclient [INOUT] ressource allocated by the client for the nfs management.
pcontext [IN] FSAL credentials
pstatus [OUT] returned status.
Definition at line 752 of file cache_inode_readdir.c.
References cache_inode_add_cached_dirent(), cache_inode_error_convert(), cache_inode_fsal_type_convert(), cache_inode_invalidate_all_cached_dirent(), cache_inode_kill_entry(), and cache_inode_new_entry().
Referenced by cache_inode_create(), and cache_inode_readdir().
cache_inode_status_t cache_inode_remove_cached_dirent (cache_entry_t * pentry_parent, fsal_name_t * pname, hash_table_t * ht, cache_inode_client_t * pclient, cache_inode_status_t * pstatus)
cache_inode_remove_cached_dirent: Removes a directory entry to a cached directory.
Removes a directory entry to a cached directory. No MT safety managed here !!
Parameters:
pentry_parent [INOUT] cache entry representing the directory to be managed.
name [IN] name of the entry to remove.
ht [IN] hash table used for the cache, unused in this call.
pclient [INOUT] ressource allocated by the client for the nfs management.
pstatus [OUT] returned status.
Returns: the same as *pstatus
Definition at line 669 of file cache_inode_readdir.c.
References cache_inode_operate_cached_dirent().
Referenced by cache_inode_remove_sw(), and cache_inode_rename().