cache_inode_lookup.c File Reference
Perform lookup through the cache.
#include `LRU_List.h`
#include `log_functions.h`
#include `HashData.h`
#include `HashTable.h`
#include `fsal.h`
#include `cache_inode.h`
#include `stuff_alloc.h`
#include <unistd.h>
#include <sys/types.h>
#include <sys/param.h>
#include <time.h>
#include <pthread.h>
Functions
cache_entry_t * cache_inode_lookup_sw (cache_entry_t *pentry_parent, fsal_name_t *pname, fsal_attrib_list_t *pattr, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus, int use_mutex)
cache_entry_t * cache_inode_lookup_no_mutex (cache_entry_t *pentry_parent, fsal_name_t *pname, fsal_attrib_list_t *pattr, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus)
cache_entry_t * cache_inode_lookup (cache_entry_t *pentry_parent, fsal_name_t *pname, fsal_attrib_list_t *pattr, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus)
Detailed Description
Perform lookup through the cache.
Author:
Author deniel
Date:
Date 2005/11/28 17:02:26
Version:
Revision 1.33
cache_inode_lookup.c(p.) : Perform lookup through the cache.
Definition in file cache_inode_lookup.c.
Function Documentation
cache_entry_t* cache_inode_lookup (cache_entry_t * pentry_parent, fsal_name_t * pname, fsal_attrib_list_t * pattr, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus)
cache_inode_lookup: looks up for a name in a directory indicated by a cached entry.
Looks up for a name in a directory indicated by a cached entry. The directory should have been cached before.
Parameters:
pentry_parent [IN] entry for the parent directory to be managed.
name [IN] name of the entry that we are looking for in the cache.
pattr [OUT] attributes for the entry that we have found.
ht [IN] hash table used for the cache, unused in this call.
pclient [INOUT] ressource allocated by the client for the nfs management.
pcontext [IN] FSAL credentials
pstatus [OUT] returned status.
Returns: CACHE_INODE_SUCCESS if operation is a success
CACHE_INODE_LRU_ERROR if allocation error occured when validating the entry
Definition at line 471 of file cache_inode_lookup.c.
References cache_inode_lookup_sw().
Referenced by cache_inode_create(), cache_inode_link(), and main().
cache_entry_t* cache_inode_lookup_no_mutex (cache_entry_t * pentry_parent, fsal_name_t * pname, fsal_attrib_list_t * pattr, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus)
cache_inode_lookup_no_mutex: looks up for a name in a directory indicated by a cached entry (no mutex management).
Looks up for a name in a directory indicated by a cached entry. The directory should have been cached before. This function has no mutex management and suppose that is it properly done in the clling function
Parameters:
pentry_parent [IN] entry for the parent directory to be managed.
name [IN] name of the entry that we are looking for in the cache.
pattr [OUT] attributes for the entry that we have found.
ht [IN] hash table used for the cache, unused in this call.
pclient [INOUT] ressource allocated by the client for the nfs management.
pcontext [IN] FSAL credentials
pstatus [OUT] returned status.
Returns: CACHE_INODE_SUCCESS if operation is a success
CACHE_INODE_LRU_ERROR if allocation error occured when validating the entry
Definition at line 434 of file cache_inode_lookup.c.
References cache_inode_lookup_sw().
Referenced by cache_inode_rename().
cache_entry_t* cache_inode_lookup_sw (cache_entry_t * pentry_parent, fsal_name_t * pname, fsal_attrib_list_t * pattr, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus, int use_mutex)
cache_inode_lookup_sw: looks up for a name in a directory indicated by a cached entry.
Looks up for a name in a directory indicated by a cached entry. The directory should have been cached before.
Parameters:
pentry_parent [IN] entry for the parent directory to be managed.
name [IN] name of the entry that we are looking for in the cache.
pattr [OUT] attributes for the entry that we have found.
ht [IN] hash table used for the cache, unused in this call.
pclient [INOUT] ressource allocated by the client for the nfs management.
pcontext [IN] FSAL credentials
pstatus [OUT] returned status.
use_mutex [IN] if TRUE, mutex management is done, not if equal to FALSE.
Returns: CACHE_INODE_SUCCESS if operation is a success
CACHE_INODE_LRU_ERROR if allocation error occured when validating the entry
Definition at line 124 of file cache_inode_lookup.c.
References cache_inode_access_no_mutex(), cache_inode_add_cached_dirent(), cache_inode_error_convert(), cache_inode_fsal_type_convert(), cache_inode_get_attributes(), cache_inode_kill_entry(), cache_inode_lookupp_no_mutex(), cache_inode_new_entry(), and cache_inode_valid().
Referenced by cache_inode_lookup(), cache_inode_lookup_no_mutex(), and cache_inode_remove_sw().