cache_inode_get.c File Reference
Get and eventually cache an entry.
#include `LRU_List.h`
#include `log_functions.h`
#include `HashData.h`
#include `HashTable.h`
#include `fsal.h`
#include `cache_inode.h`
#include `stuff_alloc.h`
#include <unistd.h>
#include <sys/types.h>
#include <sys/param.h>
#include <time.h>
#include <pthread.h>
Functions
cache_entry_t * cache_inode_get (cache_inode_fsal_data_t *pfsdata, fsal_attrib_list_t *pattr, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus)
Detailed Description
Get and eventually cache an entry.
Author:
Author deniel
Date:
Date 2005/11/28 17:02:26
Version:
Revision 1.26
cache_inode_get.c(p.) : Get and eventually cache an entry.
Definition in file cache_inode_get.c.
Function Documentation
cache_entry_t* cache_inode_get (cache_inode_fsal_data_t * pfsdata, fsal_attrib_list_t * pattr, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus)
cache_inode_get: Gets an entry by using its fsdata as a key and caches it if needed.
Gets an entry by using its fsdata as a key and caches it if needed. ASSUMPTION: DIR_CONT entries are always garbabbaged before their related DIR_BEGINNG
Parameters:
fsdata [IN] file system data
pattr [OUT] pointer to the attributes for the result.
ht [IN] hash table used for the cache, unused in this call.
pclient [INOUT] ressource allocated by the client for the nfs management.
pcontext [IN] FSAL credentials
pstatus [OUT] returned status.
Returns: the pointer to the entry is successfull, NULL otherwise.
Definition at line 123 of file cache_inode_get.c.
References cache_inode_error_convert(), cache_inode_fsal_type_convert(), cache_inode_fsaldata_2_key(), cache_inode_get_attributes(), cache_inode_kill_entry(), cache_inode_new_entry(), cache_inode_release_fsaldata_key(), and cache_inode_valid().
Referenced by cache_inode_lookupp_sw().