Cache Inode GC interface.
Functions
void cache_inode_set_gc_policy (cache_inode_gc_policy_t policy)
cache_inode_gc_policy_t cache_inode_get_gc_policy (void)
cache_inode_status_t cache_inode_gc (hash_table_t *ht, cache_inode_client_t *pclient, cache_inode_status_t *pstatus)
Detailed Description
These functions are used to run and configure the Cache inode GC
Function Documentation
cache_inode_status_t cache_inode_gc (hash_table_t * ht, cache_inode_client_t * pclient, cache_inode_status_t * pstatus)
cache_inode_gc: Perform garbbage collection on the ressources managed by a client.
Perform garbbage collection on the ressources managed by a client.
Parameters:
ht [INOUT] the hashtable used to stored the cache_inode entries.
pclient [INOUT] ressource allocated by the client for the nfs management.
pstatus [OUT] returned status.
Returns: CACHE_INODE_SUCCESS if operation is a success
CACHE_INODE_LRU_ERROR if allocation error occured when validating the entry
See also: HashTable_GetSize
LRU_invalidate_by_function
LRU_gc_invalid
Definition at line 603 of file cache_inode_gc.c.
References cache_inode_gc_function().
Referenced by main().
cache_inode_gc_policy_t cache_inode_get_gc_policy (void)
cache_inode_get_gc_policy: Set the cache_inode garbagge collecting policy.
Returns: the current policy.
Definition at line 580 of file cache_inode_gc.c.
void cache_inode_set_gc_policy (cache_inode_gc_policy_t policy)
cache_inode_set_gc_policy: Set the cache_inode garbagge collecting policy.
Parameters:
policy [IN] policy to be set.
Returns: nothing (void function)
Definition at line 567 of file cache_inode_gc.c.
Referenced by main().