Cache Inode GC internal functions.
Functions
int cache_inode_gc_suppress_file (cache_entry_t *pentry, cache_inode_param_gc_t *pgcparam)
int cache_inode_gc_suppress_directory (cache_entry_t *pentry, cache_inode_param_gc_t *pgcparam)
int cache_inode_gc_function (LRU_entry_t *plru_entry, void *addparam)
Detailed Description
These functions are used for Garbagge collector internal management.
Function Documentation
int cache_inode_gc_function (LRU_entry_t * plru_entry, void * addparam)
cache_inode_gc_function: Tests is an entry in cache inode is to be set invalid (has expired).
Tests is an entry in cache inode is to be set invalid (has expired). If entry is invalidated, does the cleaning stuff on it.
Parameters:
pentry [IN] pointer to the entry to test
Returns: 1 if entry must be set invalid, 0 if not.
See also: LRU_invalidate_by_function
LRU_gc_invalid
Definition at line 490 of file cache_inode_gc.c.
References cache_inode_gc_suppress_directory(), and cache_inode_gc_suppress_file().
Referenced by cache_inode_gc().
int cache_inode_gc_suppress_directory (cache_entry_t * pentry, cache_inode_param_gc_t * pgcparam)
cache_inode_gc_suppress_directory: suppress a directory entry from the cache inode.
Suppress a file entry from the cache inode.
Parameters:
pentry [IN] pointer to the entry to be suppressed.
Returns: 1 if entry is successfully suppressed, 0 otherwise
See also: LRU_invalidate_by_function
LRU_gc_invalid
Definition at line 397 of file cache_inode_gc.c.
References cache_inode_is_dir_empty().
Referenced by cache_inode_gc_function().
int cache_inode_gc_suppress_file (cache_entry_t * pentry, cache_inode_param_gc_t * pgcparam)
cache_inode_gc_suppress_file: suppress a file entry from the cache inode.
Suppress a file entry from the cache inode.
Parameters:
pentry [IN] pointer to the entry to be suppressed.
Returns: LRU_LIST_SET_INVALID if entry is successfully suppressed, LRU_LIST_DO_NOT_SET_INVALID otherwise
See also: LRU_invalidate_by_function
LRU_gc_invalid
Definition at line 352 of file cache_inode_gc.c.
Referenced by cache_inode_gc_function().