test_cache_inode_readdir.c File Reference
#include `BuddyMalloc.h`
#include `fsal.h`
#include `cache_inode.h`
#include `LRU_List.h`
#include `log_functions.h`
#include `err_fsal.h`
#include `err_cache_inode.h`
#include `stuff_alloc.h`
#include <unistd.h>
#include <stdlib.h>
#include <strings.h>
#include <sys/types.h>
Defines
#define HPSS_SSM `hpss_ssm`
#define HPSS_KEYTAB `/krb5/hpssserver.keytab`
Functions
int lru_entry_to_str (LRU_data_t data, char *str)
int lru_clean_entry (LRU_entry_t *entry, void *adddata)
main (int argc, char *argv[])
Define Documentation
#define HPSS_KEYTAB `/krb5/hpssserver.keytab`
Definition at line 105 of file test_cache_inode_readdir.c.
#define HPSS_SSM `hpss_ssm`
Definition at line 104 of file test_cache_inode_readdir.c.
Function Documentation
int lru_clean_entry (LRU_entry_t * entry, void * adddata)
Definition at line 116 of file test_cache_inode_readdir.c.
int lru_entry_to_str (LRU_data_t data, char * str)
Definition at line 107 of file test_cache_inode_readdir.c.
main (int argc, char * argv[])
main: test main function.
test main function.
Parameters:
argc [IN] number of command line arguments.
argv [IN] arguments set on the command line.
Returns: an integer sent back to the calling shell.
Definition at line 134 of file test_cache_inode_readdir.c.
References cache_inode_client_init(), cache_inode_init(), cache_inode_lookup(), cache_inode_make_root(), cache_inode_print_dir(), cache_inode_readdir(), HPSS_KEYTAB, and HPSS_SSM.