# A few CPack related variables
set(CPACK_PACKAGE_NAME "nfs-ganesha${PACKNAME}" )
set(CPACK_PACKAGE_VENDOR "NFS-Ganesha Project")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "NFS-Ganesha - A NFS Server runnning in user space")
set(CPACK_PACKAGE_VERSION_MAJOR ${${PROJECT_NAME}_MAJOR_VERSION})
set(CPACK_PACKAGE_VERSION_MINOR ${${PROJECT_NAME}_MINOR_VERSION})
set(CPACK_PACKAGE_VERSION_PATCH ${${PROJECT_NAME}_PATCH_LEVEL})

# CPack's debian stuff
SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "nfs-ganesha-devel@lists.sourceforge.net") 

set(CPACK_RPM_COMPONENT_INSTALL OFF)
set(CPACK_COMPONENTS_IGNORE_GROUPS "IGNORE")

# Tell CPack the kind of packages to be generated
set(CPACK_GENERATOR "STGZ;TGZ;TZ;DEB")
set(CPACK_SOURCE_GENERATOR "TGZ;TBZ2;TZ;DEB")

set(CPACK_SOURCE_IGNORE_FILES
  "/.git/;".gitignore";/build/;/.bzr/;~$;${CPACK_SOURCE_IGNORE_FILES}")


