{
 "title": "From_ankush",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "NFS INFO",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "ganesha_build_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "“NFS-Ganesha CPU Utilization (%)",
     "type": "gauge",
     "description": "Shows CPU utilization of the NFS-Ganesha process over time (percentage).\nThis panel helps correlate spikes in CPU usage with increased request rate, latency, thread saturation, or cache misses.\nUse it to detect CPU bottlenecks (e.g., sustained high CPU) that can drive higher tail latencies and lower throughput.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "nfs_cpu_utilization", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Thread Utilization (%)",
     "type": "gauge",
     "description": "Shows how much of the NFS-Ganesha thread pool is currently being used, expressed as a percentage.\nCalculated as: (threads_scheduled ÷ threads_schedulable) × 100.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "($A/$B)*100", "type": "math" }
     ]
    },
    {
     "title": "RPCs In Flight",
     "type": "gauge",
     "description": "Shows the current number of NFS RPC requests actively being processed (concurrency).\nHigher values indicate increased load or slower processing (requests taking longer to complete).\nUse this to detect saturation: if RPCs in flight stay elevated while throughput flattens or latency rises, the server is likely bottlenecked (CPU, threads, I/O, or contention).",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "rpcs_in_flight", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Metadata cache hit percentage",
     "type": "timeseries",
     "description": "Shows the percentage of metadata lookups served from the Ganesha metadata cache (MDCACHE) instead of requiring backend/FS work.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expression": "($A/$B)*100", "type": "math" }
     ]
    },
    {
     "title": "Total request rate",
     "type": "timeseries",
     "description": "nfs_requests_total is a counter that tracks the total number of NFS requests processed by NFS-Ganesha, split by operation (e.g., read, write, getattr, putfh, etc.).",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "\nsum(rate(nfs_requests_total[$__rate_interval]))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total throughput (Bytes/s)",
     "type": "timeseries",
     "description": "Shows the total network traffic handled by NFS-Ganesha on the wire, calculated as the per-second rate of bytes sent plus bytes received (Bytes/s).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      { "expression": "$A + $B", "type": "math" }
     ]
    }
   ]
  },
  {
   "title": "Latency distributions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Read latency distribution",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (le) (increase(nfs_latency_ms_bucket{operation=\"read\", le!=\"+Inf\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Write latency distribution",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (le) (increase(nfs_latency_ms_bucket{operation=\"write\", le!=\"+Inf\"}[$__range]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Getattr latency distribution",
     "type": "bargauge",
     "description": "Shows the distribution of NFS GETATTR operation latencies over the selected time range, using Prometheus histogram buckets (nfs_latency_ms_bucket). \nEach bar represents the number of GETATTR requests whose latency fell within a specific bucket range(previous le … current le), derived from cumulative bucket counters and converted into per-bucket counts for visualization.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (le) (increase(nfs_latency_ms_bucket{operation=\"getattr\", le!=\"+Inf\"}[$__range]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Lookup latency distribution",
     "type": "bargauge",
     "description": "Shows the distribution of NFS LOOKUP operation latencies over the selected time range using Prometheus histogram buckets (nfs_latency_ms_bucket). \nEach bar represents the number of LOOKUP requests whose latency fell within a specific bucket interval(previous le … current le), derived from cumulative histogram bucket counters and converted into per-bucket counts for visualization.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (le) (increase(nfs_latency_ms_bucket{operation=\"lookup\", le!=\"+Inf\"}[$__range]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Access latency distribution",
     "type": "bargauge",
     "description": "Shows the distribution of NFS ACCESS operation latencies over the selected time range using Prometheus histogram buckets (nfs_latency_ms_bucket). \nEach bar represents the number of ACCESS requests whose latency fell within a specific bucket interval(previous le … current le), derived from cumulative bucket counters and visualized as per-bucket counts (not cumulative).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (le) (increase(nfs_latency_ms_bucket{operation=\"access\", le!=\"+Inf\"}[$__range]))",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request / response sizes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    { "title": "Reads", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 3 }, "options": { "content": " " } },
    { "title": "Writes", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 3 }, "options": { "content": " " } },
    {
     "title": "NFS read response size heatmap (Bytes)",
     "type": "bargauge",
     "description": "Shows the distribution of NFS READ response sizes (Bytes) over the selected time range using Prometheus histogram buckets (nfs_response_size_bytes_bucket). \nEach bar represents the number of read responses whose size fell within a specific bucket interval(previous le … current le), derived from Prometheus cumulative buckets and visualized as per-bucket counts.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (le) (increase(nfs_response_size_bytes_bucket{operation=\"read\", le!=\"+Inf\"}[$__range]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "NFS write request size heatmap (Bytes)",
     "type": "bargauge",
     "description": "Shows the distribution of NFS WRITE request sizes (Bytes) over the selected time range using Prometheus histogram buckets (nfs_request_size_bytes_bucket). \nEach bar represents the number of write requests whose payload size fell within a specific bucket interval(previous le … current le), derived from Prometheus cumulative bucket counters and converted into per-bucket counts for visualization.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (le) (increase(nfs_request_size_bytes_bucket{operation=\"write\", le!=\"+Inf\"}[$__range]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "NFS read request size heatmap (Bytes)",
     "type": "bargauge",
     "description": "Shows the distribution of NFS READ request sizes (Bytes) over the selected time range using Prometheus histogram buckets (nfs_request_size_bytes_bucket). \nEach bar represents the number of READ requests whose payload size fell within a specific bucket interval(previous le … current le), derived from Prometheus cumulative histogram buckets and converted into per-bucket counts for visualization.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (le) (increase(nfs_request_size_bytes_bucket{operation=\"read\", le!=\"+Inf\"}[$__range]))",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Errors / second",
     "type": "timeseries",
     "description": "Shows the rate of failed NFS operations per second (errors/s), derived from the nfs_errors_total counter using rate() over a 1‑minute window. \nThe query excludes successful responses by filtering out status values NFS3_OK and NFS4_OK, so only non‑OK statuses contribute to the error rate.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(nfs_errors_total{status!~\"NFS3_OK|NFS4_OK\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error rate (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expression": "($A/$B)*100", "type": "math" }
     ]
    },
    {
     "title": "Total error count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "\nsum(\n  nfs_errors_total{status!~\"NFS3_OK|NFS4_OK\"}\n)\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Per export metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total request rate per export",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (export) (rate(nfs_requests_by_export_total[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cache hit ratio per export [ getattr ]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expression": "$A/$B", "type": "math" }
     ]
    },
    {
     "title": "Read throughput per export (Bytes/s)",
     "type": "timeseries",
     "description": "Shows the per-export read data throughput in Bytes/s, computed as the per-second rate of cumulative bytes associated with NFS READ activity and grouped by export.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (export) (rate(nfs_request_size_by_export_bytes_sum{operation=\"read\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cache hit ratio per export [ lookup ]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expression": "$A/$B", "type": "math" }
     ]
    },
    {
     "title": "Write throughput per export (Bytes/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (export) (rate(nfs_response_size_by_export_bytes_sum[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Per export latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Mean (50%) read latency per export",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.5,\n  sum by (le, export) (\n    rate(nfs_response_size_by_export_bytes_bucket{operation=\"read\"}[1m])\n  )\n)",
       "legendFormat": "{{export}}"
      }
     ]
    },
    {
     "title": "Mean (50%) latency per export (all operations)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.5,\n  sum by (le, export) (\n    rate(nfs_latency_ms_by_export_bucket[1m])\n  )\n)",
       "legendFormat": "{{ operation }} {{ export }}"
      }
     ]
    },
    {
     "title": "90% read latency per export",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by (le, export) (rate(nfs_response_size_by_export_bytes_bucket{operation=\"read\"}[1m])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Other metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Active NFS clients",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "clients__confirmed_count", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Rate of RPCs completed /received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expression": "($A/$B)*100", "type": "math" }
     ]
    }
   ]
  }
 ]
}