fsal_dirs.c File Reference
Directory browsing operations.
#include `stuff_alloc.h`
#include `fsal.h`
#include `fsal_internal.h`
#include `fsal_convert.h`
#include `HPSSclapiExt/hpssclapiext.h`
#include <string.h>
Functions
fsal_status_t HPSSFSAL_opendir (hpssfsal_handle_t *dir_handle, hpssfsal_op_context_t *p_context, hpssfsal_dir_t *dir_descriptor, fsal_attrib_list_t *dir_attributes)
fsal_status_t HPSSFSAL_readdir (hpssfsal_dir_t *dir_descriptor, hpssfsal_cookie_t start_position, fsal_attrib_mask_t get_attr_mask, fsal_mdsize_t buffersize, fsal_dirent_t *pdirent, hpssfsal_cookie_t *end_position, fsal_count_t *nb_entries, fsal_boolean_t *end_of_dir)
fsal_status_t HPSSFSAL_closedir (hpssfsal_dir_t *dir_descriptor)
Detailed Description
Directory browsing operations.
Author
Author
leibovic
Date
Date
2005/07/29 09:39:04
Version
Revision
1.10
Definition in file fsal_dirs.c.
Function Documentation
fsal_status_t HPSSFSAL_closedir (hpssfsal_dir_t * dir_descriptor)
FSAL_closedir : Free the resources allocated for reading directory entries.
Parameters
dir_descriptor (input): Pointer to a directory descriptor filled by FSAL_opendir.
Returns
Major error codes :
ERR_FSAL_NO_ERROR (no error)
ERR_FSAL_FAULT (a NULL pointer was passed as mandatory argument)
Other error codes can be returned : ERR_FSAL_IO, ...
Definition at line 307 of file fsal_dirs.c.
fsal_status_t HPSSFSAL_opendir (hpssfsal_handle_t * dir_handle, hpssfsal_op_context_t * p_context, hpssfsal_dir_t * dir_descriptor, fsal_attrib_list_t * dir_attributes)
FSAL_opendir : Opens a directory for reading its content.
Parameters
dir_handle (input) the handle of the directory to be opened.
p_context (input) Permission context for the operation (user, export context...).
dir_descriptor (output) pointer to an allocated structure that will receive directory stream informations, on successfull completion.
dir_attributes (optional output) On successfull completion,the structure pointed by dir_attributes receives the new directory attributes. Can be NULL.
Returns
Major error codes :
ERR_FSAL_NO_ERROR (no error)
ERR_FSAL_ACCESS (user does not have read permission on directory)
ERR_FSAL_STALE (dir_handle does not address an existing object)
ERR_FSAL_FAULT (a NULL pointer was passed as mandatory argument)
Other error codes can be returned : ERR_FSAL_IO, ...
Definition at line 48 of file fsal_dirs.c.
References HPSSFSAL_access().
fsal_status_t HPSSFSAL_readdir (hpssfsal_dir_t * dir_descriptor, hpssfsal_cookie_t start_position, fsal_attrib_mask_t get_attr_mask, fsal_mdsize_t buffersize, fsal_dirent_t * pdirent, hpssfsal_cookie_t * end_position, fsal_count_t * nb_entries, fsal_boolean_t * end_of_dir)
FSAL_readdir : Read the entries of an opened directory.
Parameters
dir_descriptor (input): Pointer to the directory descriptor filled by FSAL_opendir.
start_position (input): Cookie that indicates the first object to be read during this readdir operation. This should be :
FSAL_READDIR_FROM_BEGINNING for reading the content of the directory from the beginning.
The end_position parameter returned by the previous call to FSAL_readdir.
get_attr_mask (input) Specify the set of attributes to be retrieved for directory entries.
buffersize (input) The size (in bytes) of the buffer where the direntries are to be stored.
pdirent (output) Adresse of the buffer where the direntries are to be stored.
end_position (output) Cookie that indicates the current position in the directory.
nb_entries (output) Pointer to the number of entries read during the call.
end_of_dir (output) Pointer to a boolean that indicates if the end of dir has been reached during the call.
Returns
Major error codes :
ERR_FSAL_NO_ERROR (no error)
ERR_FSAL_FAULT (a NULL pointer was passed as mandatory argument)
Other error codes can be returned : ERR_FSAL_IO, ...
Todo : does handle provide mounted_on_fileid ?
Todo : test returned status
Definition at line 115 of file fsal_dirs.c.
References hpss2fsal_attributes(), hpss2fsal_error(), hpss2fsal_type(), hpssHandle2fsalAttributes(), and TakeTokenFSCall().