fsal_symlinks.c File Reference
symlinks operations.
#include `fsal.h`
#include `fsal_internal.h`
#include `fsal_convert.h`
#include `fsal_common.h`
#include <string.h>
#include `HPSSclapiExt/hpssclapiext.h`
#include <hpss_errno.h>
Functions
fsal_status_t HPSSFSAL_readlink (hpssfsal_handle_t *linkhandle, hpssfsal_op_context_t *p_context, fsal_path_t *p_link_content, fsal_attrib_list_t *link_attributes)
fsal_status_t HPSSFSAL_symlink (hpssfsal_handle_t *parent_directory_handle, fsal_name_t *p_linkname, fsal_path_t *p_linkcontent, hpssfsal_op_context_t *p_context, fsal_accessmode_t accessmode, hpssfsal_handle_t *link_handle, fsal_attrib_list_t *link_attributes)
Detailed Description
symlinks operations.
Author
Author
leibovic
Date
Date
2005/07/29 09:39:04
Version
Revision
1.15
Definition in file fsal_symlinks.c.
Function Documentation
fsal_status_t HPSSFSAL_readlink (hpssfsal_handle_t * linkhandle, hpssfsal_op_context_t * p_context, fsal_path_t * p_link_content, fsal_attrib_list_t * link_attributes)
FSAL_readlink: Read the content of a symbolic link.
Parameters
linkhandle (input): Handle of the link to be read.
cred (input): Authentication context for the operation (user,...).
p_link_content (output): Pointer to an fsal path structure where the link content is to be stored..
link_attributes (optionnal input/output): The post operation attributes of the symlink link. As input, it defines the attributes that the caller wants to retrieve (by positioning flags into this structure) and the output is built considering this input (it fills the structure according to the flags it contains). May be NULL.
Returns
Major error codes :
ERR_FSAL_NO_ERROR (no error)
ERR_FSAL_STALE (linkhandle does not address an existing object)
ERR_FSAL_INVAL (linkhandle does not address a symbolic link)
ERR_FSAL_FAULT (a NULL pointer was passed as mandatory argument)
Other error codes can be returned : ERR_FSAL_ACCESS, ERR_FSAL_IO, ...
Definition at line 54 of file fsal_symlinks.c.
References hpss2fsal_error(), HPSSFSAL_getattrs(), and TakeTokenFSCall().
fsal_status_t HPSSFSAL_symlink (hpssfsal_handle_t * parent_directory_handle, fsal_name_t * p_linkname, fsal_path_t * p_linkcontent, hpssfsal_op_context_t * p_context, fsal_accessmode_t accessmode, hpssfsal_handle_t * link_handle, fsal_attrib_list_t * link_attributes)
FSAL_symlink: Create a symbolic link.
Parameters
parent_directory_handle (input): Handle of the parent directory where the link is to be created.
p_linkname (input): Name of the link to be created.
p_linkcontent (input): Content of the link to be created.
cred (input): Authentication context for the operation (user,...).
accessmode (ignored input): Mode of the link to be created. It has no sense in HPSS nor UNIX filesystems.
link_handle (output): Pointer to the handle of the created symlink.
link_attributes (optionnal input/output): Attributes of the newly created symlink. As input, it defines the attributes that the caller wants to retrieve (by positioning flags into this structure) and the output is built considering this input (it fills the structure according to the flags it contains). May be NULL.
Returns
Major error codes :
ERR_FSAL_NO_ERROR (no error)
ERR_FSAL_STALE (parent_directory_handle does not address an existing object)
ERR_FSAL_NOTDIR (parent_directory_handle does not address a directory)
ERR_FSAL_FAULT (a NULL pointer was passed as mandatory argument)
Other error codes can be returned : ERR_FSAL_ACCESS, ERR_FSAL_IO, ...
Definition at line 155 of file fsal_symlinks.c.
References hpss2fsal_attributes(), hpss2fsal_error(), and TakeTokenFSCall().