fsal_truncate.c File Reference
Truncate function.
#include `fsal.h`
#include `fsal_internal.h`
#include `fsal_convert.h`
#include <hpss_errno.h>
Functions
fsal_status_t HPSSFSAL_truncate (hpssfsal_handle_t *filehandle, hpssfsal_op_context_t *p_context, fsal_size_t length, hpssfsal_file_t *file_descriptor, fsal_attrib_list_t *object_attributes)
Detailed Description
Truncate function.
Author
Author
leibovic
Date
Date
2005/07/29 09:39:05
Version
Revision
1.4
Definition in file fsal_truncate.c.
Function Documentation
fsal_status_t HPSSFSAL_truncate (hpssfsal_handle_t * filehandle, hpssfsal_op_context_t * p_context, fsal_size_t length, hpssfsal_file_t * file_descriptor, fsal_attrib_list_t * object_attributes)
FSAL_truncate: Modify the data length of a regular file.
Parameters
filehandle (input): Handle of the file is to be truncated.
cred (input): Authentication context for the operation (user,...).
length (input): The new data length for the file.
object_attributes (optionnal input/output): The post operation attributes of the file. As input, it defines the attributes that the caller wants to retrieve (by positioning flags into this structure) and the output is built considering this input (it fills the structure according to the flags it contains). May be NULL.
Returns
Major error codes :
ERR_FSAL_NO_ERROR (no error)
ERR_FSAL_STALE (filehandle does not address an existing object)
ERR_FSAL_INVAL (filehandle does not address a regular file)
ERR_FSAL_FAULT (a NULL pointer was passed as mandatory argument)
Other error codes can be returned : ERR_FSAL_ACCESS, ERR_FSAL_IO, ...
Definition at line 51 of file fsal_truncate.c.
References fsal2hpss_64(), hpss2fsal_error(), HPSSFSAL_getattrs(), and TakeTokenFSCall().