fsal_access.c File Reference
FSAL access permissions functions.
#include `fsal.h`
#include `fsal_internal.h`
#include `fsal_convert.h`
#include <hpss_errno.h>
Functions
fsal_status_t HPSSFSAL_access (hpssfsal_handle_t *object_handle, hpssfsal_op_context_t *p_context, fsal_accessflags_t access_type, fsal_attrib_list_t *object_attributes)
Detailed Description
FSAL access permissions functions.
Author
Author
leibovic
Date
Date
2006/01/17 14:20:07
Version
Revision
1.16
Definition in file fsal_access.c.
Function Documentation
fsal_status_t HPSSFSAL_access (hpssfsal_handle_t * object_handle, hpssfsal_op_context_t * p_context, fsal_accessflags_t access_type, fsal_attrib_list_t * object_attributes)
FSAL_access : Tests whether the user or entity identified by the p_context structure can access the object identified by object_handle, as indicated by the access_type parameter.
Parameters
object_handle (input): The handle of the object to test permissions on.
p_context (input): Authentication context for the operation (export entry, user,...).
access_type (input): Indicates the permissions to be tested. This is an inclusive OR of the permissions to be checked for the user specified by p_context. Permissions constants are :
FSAL_R_OK : test for read permission
FSAL_W_OK : test for write permission
FSAL_X_OK : test for exec permission
FSAL_F_OK : test for file existence
object_attributes (optional input/output): The post operation attributes for the object. As input, it defines the attributes that the caller wants to retrieve (by positioning flags into this structure) and the output is built considering this input (it fills the structure according to the flags it contains). Can be NULL.
Returns
Major error codes :
ERR_FSAL_NO_ERROR (no error, asked permission is granted)
ERR_FSAL_ACCESS (object permissions doesn't fit asked access type)
ERR_FSAL_STALE (object_handle does not address an existing object)
ERR_FSAL_FAULT (a NULL pointer was passed as mandatory argument)
Other error codes when something anormal occurs.
Definition at line 58 of file fsal_access.c.
References fsal2hpss_testperm(), hpss2fsal_error(), and TakeTokenFSCall().
Referenced by HPSSFSAL_opendir().