fsal_unlink.c File Reference
object removing function.
#include `fsal.h`
#include `fsal_internal.h`
#include `fsal_convert.h`
Functions
fsal_status_t HPSSFSAL_unlink (hpssfsal_handle_t *parentdir_handle, fsal_name_t *p_object_name, hpssfsal_op_context_t *p_context, fsal_attrib_list_t *parentdir_attributes)
Detailed Description
object removing function.
Author
Author
leibovic
Date
Date
2006/01/24 13:45:37
Version
Revision
1.9
Definition in file fsal_unlink.c.
Function Documentation
fsal_status_t HPSSFSAL_unlink (hpssfsal_handle_t * parentdir_handle, fsal_name_t * p_object_name, hpssfsal_op_context_t * p_context, fsal_attrib_list_t * parentdir_attributes)
FSAL_unlink: Remove a filesystem object .
Parameters
parentdir_handle (input): Handle of the parent directory of the object to be deleted.
p_object_name (input): Name of the object to be removed.
p_context (input): Authentication context for the operation (user,...).
parentdir_attributes (optionnal input/output): Post operation attributes of the parent directory. As input, it defines the attributes that the caller wants to retrieve (by positioning flags into this structure) and the output is built considering this input (it fills the structure according to the flags it contains). May be NULL.
Returns
Major error codes :
ERR_FSAL_NO_ERROR (no error)
ERR_FSAL_STALE (parentdir_handle does not address an existing object)
ERR_FSAL_NOTDIR (parentdir_handle does not address a directory)
ERR_FSAL_NOENT (the object designated by p_object_name does not exist)
ERR_FSAL_NOTEMPTY (tried to remove a non empty directory)
ERR_FSAL_FAULT (a NULL pointer was passed as mandatory argument)
Other error codes can be returned : ERR_FSAL_ACCESS, ERR_FSAL_IO, ...
Definition at line 51 of file fsal_unlink.c.
References hpss2fsal_error(), HPSSFSAL_getattrs(), HPSSFSAL_lookup(), and TakeTokenFSCall().