fsal_attrs.c File Reference
Attributes functions.
#include `fsal.h`
#include `fsal_internal.h`
#include `fsal_convert.h`
#include `HPSSclapiExt/hpssclapiext.h`
#include <hpss_errno.h>
Functions
fsal_status_t HPSSFSAL_getattrs (hpssfsal_handle_t *filehandle, hpssfsal_op_context_t *p_context, fsal_attrib_list_t *object_attributes)
fsal_status_t HPSSFSAL_setattrs (hpssfsal_handle_t *filehandle, hpssfsal_op_context_t *p_context, fsal_attrib_list_t *attrib_set, fsal_attrib_list_t *object_attributes)
fsal_status_t HPSSFSAL_getextattrs (hpssfsal_handle_t *p_filehandle, hpssfsal_op_context_t *p_context, fsal_extattrib_list_t *p_object_attributes)
Detailed Description
Attributes functions.
Author
Author
leibovic
Date
Date
2005/09/09 15:22:49
Version
Revision
1.19
Definition in file fsal_attrs.c.
Function Documentation
fsal_status_t HPSSFSAL_getattrs (hpssfsal_handle_t * filehandle, hpssfsal_op_context_t * p_context, fsal_attrib_list_t * object_attributes)
FSAL_getattrs: Get attributes for the object specified by its filehandle.
Parameters
filehandle (input): The handle of the object to get parameters.
p_context (input): Authentication context for the operation (user, export...).
object_attributes (mandatory input/output): The retrieved attributes for the object. As input, it defines the attributes that the caller wants to retrieve (by positioning flags into this structure) and the output is built considering this input (it fills the structure according to the flags it contains).
Returns
Major error codes :
ERR_FSAL_NO_ERROR (no error)
ERR_FSAL_STALE (object_handle does not address an existing object)
ERR_FSAL_FAULT (a NULL pointer was passed as mandatory argument)
Another error code if an error occured.
Definition at line 46 of file fsal_attrs.c.
References hpss2fsal_attributes(), hpss2fsal_error(), and TakeTokenFSCall().
Referenced by HPSSFSAL_GetXAttrAttrs(), HPSSFSAL_link(), HPSSFSAL_lookup(), HPSSFSAL_readlink(), HPSSFSAL_rename(), HPSSFSAL_setattrs(), HPSSFSAL_truncate(), and HPSSFSAL_unlink().
fsal_status_t HPSSFSAL_getextattrs (hpssfsal_handle_t * p_filehandle, hpssfsal_op_context_t * p_context, fsal_extattrib_list_t * p_object_attributes)
FSAL_getetxattrs: Get attributes for the object specified by its filehandle.
Parameters
filehandle (input): The handle of the object to get parameters.
cred (input): Authentication context for the operation (user,...).
object_attributes (mandatory input/output): The retrieved attributes for the object. As input, it defines the attributes that the caller wants to retrieve (by positioning flags into this structure) and the output is built considering this input (it fills the structure according to the flags it contains).
Returns
Major error codes :
ERR_FSAL_NO_ERROR (no error)
Another error code if an error occured.
Definition at line 271 of file fsal_attrs.c.
fsal_status_t HPSSFSAL_setattrs (hpssfsal_handle_t * filehandle, hpssfsal_op_context_t * p_context, fsal_attrib_list_t * attrib_set, fsal_attrib_list_t * object_attributes)
FSAL_setattrs: Set attributes for the object specified by its filehandle.
Parameters
filehandle (input): The handle of the object to get parameters.
p_context (input): Authentication context for the operation (user,...).
attrib_set (mandatory input): The attributes to be set for the object. It defines the attributes that the caller wants to set and their values.
object_attributes (optionnal input/output): The post operation attributes for the object. As input, it defines the attributes that the caller wants to retrieve (by positioning flags into this structure) and the output is built considering this input (it fills the structure according to the flags it contains). May be NULL.
Returns
Major error codes :
ERR_FSAL_NO_ERROR (no error)
ERR_FSAL_STALE (object_handle does not address an existing object)
ERR_FSAL_INVAL (tried to modify a read-only attribute)
ERR_FSAL_ATTRNOTSUPP (tried to modify a non-supported attribute)
ERR_FSAL_FAULT (a NULL pointer was passed as mandatory argument)
Another error code if an error occured. NB: if getting postop attributes failed, the function does not return an error but the FSAL_ATTR_RDATTR_ERR bit is set in the object_attributes->asked_attributes field.
Todo : chown restricted seems to be OK.
Todo voir pourquoi hpss_fattr_out ne contient pas ce qu'il devrait contenir
Definition at line 125 of file fsal_attrs.c.
References fsal2hpss_attribset(), hpss2fsal_attributes(), hpss2fsal_error(), HPSSFSAL_getattrs(), and TakeTokenFSCall().