.TH "_type_affect_" 3 "9 Apr 2008" "Version 0.1" "ConfigParsing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_type_affect_ \- 
.SH SYNOPSIS
.br
.PP
\fC#include <analyse.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBvarname\fP [MAXSTRLEN]"
.br
.ti -1c
.RI "char \fBvarvalue\fP [MAXSTRLEN]"
.br
.ti -1c
.RI "\fB_type_affect_\fP * \fBnext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fB_type_affect_\fP* \fB_type_affect_::next\fP"
.PP
Definition at line 38 of file analyse.h.
.PP
Referenced by config_adddef(), config_createaffect(), config_createblock(), config_GetKeyValue(), config_GetKeyValueByName(), config_GetNbKeys(), and config_print_list().
.SS "char \fB_type_affect_::varname\fP[MAXSTRLEN]"
.PP
Definition at line 36 of file analyse.h.
.PP
Referenced by config_GetKeyValue(), config_GetKeyValueByName(), and config_print_list().
.SS "char \fB_type_affect_::varvalue\fP[MAXSTRLEN]"
.PP
Definition at line 37 of file analyse.h.
.PP
Referenced by config_GetKeyValue(), config_GetKeyValueByName(), and config_print_list().

.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigParsing from the source code.
