.TH "_type_block_" 3 "9 Apr 2008" "Version 0.1" "ConfigParsing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_type_block_ \- 
.SH SYNOPSIS
.br
.PP
\fC#include <analyse.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBname\fP [MAXSTRLEN]"
.br
.ti -1c
.RI "\fBlist_affect\fP \fBlist_def\fP"
.br
.ti -1c
.RI "\fB_type_block_\fP * \fBnext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBlist_affect\fP \fB_type_block_::list_def\fP"
.PP
Definition at line 46 of file analyse.h.
.PP
Referenced by config_createblock(), config_GetKeyValue(), config_GetKeyValueByName(), config_GetNbKeys(), and config_print_list().
.SS "char \fB_type_block_::name\fP[MAXSTRLEN]"
.PP
Definition at line 45 of file analyse.h.
.PP
Referenced by config_GetBlockIndexByName(), config_GetBlockName(), and config_print_list().
.SS "struct \fB_type_block_\fP* \fB_type_block_::next\fP"
.PP
Definition at line 47 of file analyse.h.
.PP
Referenced by config_addblock(), config_free_list(), config_GetBlockIndexByName(), config_GetNbBlocks(), and config_print_list().

.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigParsing from the source code.
