.TH "_type_affect_" 3 "15 Sep 2010" "Version 0.1" "ConfigParsing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_type_affect_ \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <analyse.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBvarname\fP [MAXSTRLEN]"
.br
.ti -1c
.RI "char \fBvarvalue\fP [MAXSTRLEN]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 43 of file analyse.h.
.SH "Member Data Documentation"
.PP 
.SS "char \fB_type_affect_::varname\fP[MAXSTRLEN]"
.PP
Definition at line 46 of file analyse.h.
.SS "char \fB_type_affect_::varvalue\fP[MAXSTRLEN]"
.PP
Definition at line 47 of file analyse.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigParsing from the source code.
