.TH "_type_block_" 3 "31 Mar 2009" "Version 0.1" "ConfigParsing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_type_block_ \- 
.SH SYNOPSIS
.br
.PP
\fC#include <analyse.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBblock_name\fP [MAXSTRLEN]"
.br
.ti -1c
.RI "struct \fB_generic_item_\fP * \fBblock_content\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 96 of file analyse.h.
.SH "Member Data Documentation"
.PP 
.SS "struct \fB_generic_item_\fP* \fB_type_block_::block_content\fP\fC [read]\fP"
.PP
Definition at line 99 of file analyse.h.
.SS "char \fB_type_block_::block_name\fP[MAXSTRLEN]"
.PP
Definition at line 98 of file analyse.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigParsing from the source code.
