.TH "analyse.h" 3 "31 Mar 2009" "Version 0.1" "ConfigParsing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
analyse.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB_type_affect_\fP"
.br
.ti -1c
.RI "struct \fB_type_block_\fP"
.br
.ti -1c
.RI "struct \fB_generic_item_\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMAXSTRLEN\fP   1024"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB_type_affect_\fP \fBtype_affect\fP"
.br
.ti -1c
.RI "typedef struct \fB_type_block_\fP \fBtype_block\fP"
.br
.ti -1c
.RI "typedef struct \fB_generic_item_\fP \fBgeneric_item\fP"
.br
.ti -1c
.RI "typedef \fBgeneric_item\fP * \fBlist_items\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBtype_item\fP { \fBTYPE_BLOCK\fP, \fBTYPE_AFFECT\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlist_items\fP * \fBconfig_CreateItemsList\fP ()"
.br
.ti -1c
.RI "\fBgeneric_item\fP * \fBconfig_CreateBlock\fP (char *blockname, \fBlist_items\fP *list)"
.br
.ti -1c
.RI "\fBgeneric_item\fP * \fBconfig_CreateAffect\fP (char *varname, char *varval)"
.br
.ti -1c
.RI "void \fBconfig_AddItem\fP (\fBlist_items\fP *list, \fBgeneric_item\fP *item)"
.br
.ti -1c
.RI "void \fBconfig_print_list\fP (FILE *output, \fBlist_items\fP *list)"
.br
.ti -1c
.RI "void \fBconfig_free_list\fP (\fBlist_items\fP *list)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define MAXSTRLEN   1024"
.PP
Definition at line 71 of file analyse.h.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB_generic_item_\fP  \fBgeneric_item\fP"
.PP
.SS "typedef \fBgeneric_item\fP* \fBlist_items\fP"
.PP
Definition at line 119 of file analyse.h.
.SS "typedef struct \fB_type_affect_\fP  \fBtype_affect\fP"
.PP
.SS "typedef struct \fB_type_block_\fP  \fBtype_block\fP"
.PP
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBtype_item\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fITYPE_BLOCK \fP\fP
.TP
\fB\fITYPE_AFFECT \fP\fP

.PP
Definition at line 82 of file analyse.h.
.SH "Function Documentation"
.PP 
.SS "void config_AddItem (\fBlist_items\fP * list, \fBgeneric_item\fP * item)"
.PP
Add an item to a list
.PP
Add an item to a list as first element 
.PP
Definition at line 140 of file analyse.c.
.SS "\fBgeneric_item\fP* config_CreateAffect (char * varname, char * varval)"
.PP
Create a key=value peer (assignment) 
.PP
Definition at line 122 of file analyse.c.
.SS "\fBgeneric_item\fP* config_CreateBlock (char * blockname, \fBlist_items\fP * list)"
.PP
Create a block item with the given content 
.PP
Definition at line 99 of file analyse.c.
.SS "\fBlist_items\fP* config_CreateItemsList ()"
.PP
create a list of items 
.PP
Definition at line 87 of file analyse.c.
.SS "void config_free_list (\fBlist_items\fP * list)"
.PP
config_free_list: Free ressources for a list 
.PP
Definition at line 229 of file analyse.c.
.SS "void config_print_list (FILE * output, \fBlist_items\fP * list)"
.PP
Displays the content of a list of blocks. 
.PP
Definition at line 191 of file analyse.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigParsing from the source code.
