.TH "analyse.c" 3 "31 Mar 2009" "Version 0.1" "ConfigParsing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
analyse.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'config.h'\fP
.br
\fC#include 'analyse.h'\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <stdio.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlist_items\fP * \fBconfig_CreateItemsList\fP ()"
.br
.ti -1c
.RI "\fBgeneric_item\fP * \fBconfig_CreateBlock\fP (char *blockname, \fBlist_items\fP *list)"
.br
.ti -1c
.RI "\fBgeneric_item\fP * \fBconfig_CreateAffect\fP (char *varname, char *varval)"
.br
.ti -1c
.RI "void \fBconfig_AddItem\fP (\fBlist_items\fP *list, \fBgeneric_item\fP *item)"
.br
.ti -1c
.RI "void \fBconfig_print_list\fP (FILE *output, \fBlist_items\fP *list)"
.br
.ti -1c
.RI "void \fBconfig_free_list\fP (\fBlist_items\fP *list)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void config_AddItem (\fBlist_items\fP * list, \fBgeneric_item\fP * item)"
.PP
Add an item to a list as first element 
.PP
Definition at line 140 of file analyse.c.
.SS "\fBgeneric_item\fP* config_CreateAffect (char * varname, char * varval)"
.PP
Create a key=value peer (assignment) 
.PP
Definition at line 122 of file analyse.c.
.SS "\fBgeneric_item\fP* config_CreateBlock (char * blockname, \fBlist_items\fP * list)"
.PP
Create a block item with the given content 
.PP
Definition at line 99 of file analyse.c.
.SS "\fBlist_items\fP* config_CreateItemsList ()"
.PP
create a list of items 
.PP
Definition at line 87 of file analyse.c.
.SS "void config_free_list (\fBlist_items\fP * list)"
.PP
config_free_list: Free ressources for a list 
.PP
Definition at line 229 of file analyse.c.
.SS "void config_print_list (FILE * output, \fBlist_items\fP * list)"
.PP
Displays the content of a list of blocks. 
.PP
Definition at line 191 of file analyse.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigParsing from the source code.
