.TH "conf_yacc.h" 3 "31 Mar 2009" "Version 0.1" "ConfigParsing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
conf_yacc.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "union \fBYYSTYPE\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_ERROR_\fP   258"
.br
.ti -1c
.RI "#define \fBBEGIN_BLOCK\fP   259"
.br
.ti -1c
.RI "#define \fBEND_BLOCK\fP   260"
.br
.ti -1c
.RI "#define \fBBEGIN_SUB_BLOCK\fP   261"
.br
.ti -1c
.RI "#define \fBEND_SUB_BLOCK\fP   262"
.br
.ti -1c
.RI "#define \fBAFFECTATION\fP   263"
.br
.ti -1c
.RI "#define \fBEND_AFFECT\fP   264"
.br
.ti -1c
.RI "#define \fBIDENTIFIER\fP   265"
.br
.ti -1c
.RI "#define \fBKEYVALUE\fP   266"
.br
.ti -1c
.RI "#define \fByystype\fP   \fBYYSTYPE\fP"
.br
.ti -1c
.RI "#define \fBYYSTYPE_IS_DECLARED\fP   1"
.br
.ti -1c
.RI "#define \fBYYSTYPE_IS_TRIVIAL\fP   1"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fByytokentype\fP { \fB_ERROR_\fP =  258, \fBBEGIN_BLOCK\fP =  259, \fBEND_BLOCK\fP =  260, \fBBEGIN_SUB_BLOCK\fP =  261, \fBEND_SUB_BLOCK\fP =  262, \fBAFFECTATION\fP =  263, \fBEND_AFFECT\fP =  264, \fBIDENTIFIER\fP =  265, \fBKEYVALUE\fP =  266, \fB_ERROR_\fP =  258, \fBBEGIN_BLOCK\fP =  259, \fBEND_BLOCK\fP =  260, \fBBEGIN_SUB_BLOCK\fP =  261, \fBEND_SUB_BLOCK\fP =  262, \fBAFFECTATION\fP =  263, \fBEND_AFFECT\fP =  264, \fBIDENTIFIER\fP =  265, \fBKEYVALUE\fP =  266 }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBYYSTYPE\fP \fBganesha_yylval\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define _ERROR_   258"
.PP
Definition at line 54 of file conf_yacc.h.
.SS "#define AFFECTATION   263"
.PP
Definition at line 59 of file conf_yacc.h.
.SS "#define BEGIN_BLOCK   259"
.PP
Definition at line 55 of file conf_yacc.h.
.SS "#define BEGIN_SUB_BLOCK   261"
.PP
Definition at line 57 of file conf_yacc.h.
.SS "#define END_AFFECT   264"
.PP
Definition at line 60 of file conf_yacc.h.
.SS "#define END_BLOCK   260"
.PP
Definition at line 56 of file conf_yacc.h.
.SS "#define END_SUB_BLOCK   262"
.PP
Definition at line 58 of file conf_yacc.h.
.SS "#define IDENTIFIER   265"
.PP
Definition at line 61 of file conf_yacc.h.
.SS "#define KEYVALUE   266"
.PP
Definition at line 62 of file conf_yacc.h.
.SS "#define yystype   \fBYYSTYPE\fP"
.PP
Definition at line 78 of file conf_yacc.h.
.SS "#define YYSTYPE_IS_DECLARED   1"
.PP
Definition at line 79 of file conf_yacc.h.
.SS "#define YYSTYPE_IS_TRIVIAL   1"
.PP
Definition at line 80 of file conf_yacc.h.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fByytokentype\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fI_ERROR_ \fP\fP
.TP
\fB\fIBEGIN_BLOCK \fP\fP
.TP
\fB\fIEND_BLOCK \fP\fP
.TP
\fB\fIBEGIN_SUB_BLOCK \fP\fP
.TP
\fB\fIEND_SUB_BLOCK \fP\fP
.TP
\fB\fIAFFECTATION \fP\fP
.TP
\fB\fIEND_AFFECT \fP\fP
.TP
\fB\fIIDENTIFIER \fP\fP
.TP
\fB\fIKEYVALUE \fP\fP
.TP
\fB\fI_ERROR_ \fP\fP
.TP
\fB\fIBEGIN_BLOCK \fP\fP
.TP
\fB\fIEND_BLOCK \fP\fP
.TP
\fB\fIBEGIN_SUB_BLOCK \fP\fP
.TP
\fB\fIEND_SUB_BLOCK \fP\fP
.TP
\fB\fIAFFECTATION \fP\fP
.TP
\fB\fIEND_AFFECT \fP\fP
.TP
\fB\fIIDENTIFIER \fP\fP
.TP
\fB\fIKEYVALUE \fP\fP

.PP
Definition at line 41 of file conf_yacc.h.
.SH "Variable Documentation"
.PP 
.SS "\fBYYSTYPE\fP \fBganesha_yylval\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigParsing from the source code.
