.TH "conf_yacc.c" 3 "15 Sep 2010" "Version 0.1" "ConfigParsing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
conf_yacc.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'config.h'\fP
.br
\fC#include 'analyse.h'\fP
.br
\fC#include <stdio.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "union \fBYYSTYPE\fP"
.br
.ti -1c
.RI "union \fByyalloc\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBYYBISON\fP   1"
.br
.ti -1c
.RI "#define \fBYYBISON_VERSION\fP   '2.4.1'"
.br
.ti -1c
.RI "#define \fBYYSKELETON_NAME\fP   'yacc.c'"
.br
.ti -1c
.RI "#define \fBYYPURE\fP   0"
.br
.ti -1c
.RI "#define \fBYYPUSH\fP   0"
.br
.ti -1c
.RI "#define \fBYYPULL\fP   1"
.br
.ti -1c
.RI "#define \fBYYLSP_NEEDED\fP   0"
.br
.ti -1c
.RI "#define \fByyparse\fP   ganesha_yyparse"
.br
.ti -1c
.RI "#define \fByylex\fP   ganesha_yylex"
.br
.ti -1c
.RI "#define \fByyerror\fP   ganesha_yyerror"
.br
.ti -1c
.RI "#define \fByylval\fP   \fBganesha_yylval\fP"
.br
.ti -1c
.RI "#define \fByychar\fP   ganesha_yychar"
.br
.ti -1c
.RI "#define \fByydebug\fP   ganesha_yydebug"
.br
.ti -1c
.RI "#define \fByynerrs\fP   ganesha_yynerrs"
.br
.ti -1c
.RI "#define \fBDEBUG_YACK\fP"
.br
.ti -1c
.RI "#define \fBYYDEBUG\fP   0"
.br
.ti -1c
.RI "#define \fBYYERROR_VERBOSE\fP   0"
.br
.ti -1c
.RI "#define \fBYYTOKEN_TABLE\fP   0"
.br
.ti -1c
.RI "#define \fB_ERROR_\fP   258"
.br
.ti -1c
.RI "#define \fBBEGIN_BLOCK\fP   259"
.br
.ti -1c
.RI "#define \fBEND_BLOCK\fP   260"
.br
.ti -1c
.RI "#define \fBBEGIN_SUB_BLOCK\fP   261"
.br
.ti -1c
.RI "#define \fBEND_SUB_BLOCK\fP   262"
.br
.ti -1c
.RI "#define \fBAFFECTATION\fP   263"
.br
.ti -1c
.RI "#define \fBEND_AFFECT\fP   264"
.br
.ti -1c
.RI "#define \fBIDENTIFIER\fP   265"
.br
.ti -1c
.RI "#define \fBKEYVALUE\fP   266"
.br
.ti -1c
.RI "#define \fBYYSTYPE_IS_TRIVIAL\fP   1"
.br
.ti -1c
.RI "#define \fByystype\fP   \fBYYSTYPE\fP"
.br
.ti -1c
.RI "#define \fBYYSTYPE_IS_DECLARED\fP   1"
.br
.ti -1c
.RI "#define \fBYYSIZE_T\fP   unsigned int"
.br
.ti -1c
.RI "#define \fBYYSIZE_MAXIMUM\fP   ((YYSIZE_T) -1)"
.br
.ti -1c
.RI "#define \fBYY_\fP(msgid)   msgid"
.br
.ti -1c
.RI "#define \fBYYUSE\fP(e)   ((void) (e))"
.br
.ti -1c
.RI "#define \fBYYID\fP(n)   (n)"
.br
.ti -1c
.RI "#define \fBYYSTACK_ALLOC\fP   YYMALLOC"
.br
.ti -1c
.RI "#define \fBYYSTACK_FREE\fP   YYFREE"
.br
.ti -1c
.RI "#define \fBYYSTACK_ALLOC_MAXIMUM\fP   YYSIZE_MAXIMUM"
.br
.ti -1c
.RI "#define \fBYYMALLOC\fP   malloc"
.br
.ti -1c
.RI "#define \fBYYFREE\fP   free"
.br
.ti -1c
.RI "#define \fBYYSTACK_GAP_MAXIMUM\fP   (sizeof (union \fByyalloc\fP) - 1)"
.br
.ti -1c
.RI "#define \fBYYSTACK_BYTES\fP(N)"
.br
.ti -1c
.RI "#define \fBYYCOPY\fP(To, From, Count)"
.br
.ti -1c
.RI "#define \fBYYSTACK_RELOCATE\fP(Stack_alloc, Stack)"
.br
.ti -1c
.RI "#define \fBYYFINAL\fP   6"
.br
.ti -1c
.RI "#define \fBYYLAST\fP   14"
.br
.ti -1c
.RI "#define \fBYYNTOKENS\fP   12"
.br
.ti -1c
.RI "#define \fBYYNNTS\fP   8"
.br
.ti -1c
.RI "#define \fBYYNRULES\fP   11"
.br
.ti -1c
.RI "#define \fBYYNSTATES\fP   21"
.br
.ti -1c
.RI "#define \fBYYUNDEFTOK\fP   2"
.br
.ti -1c
.RI "#define \fBYYMAXUTOK\fP   266"
.br
.ti -1c
.RI "#define \fBYYTRANSLATE\fP(YYX)   ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)"
.br
.ti -1c
.RI "#define \fBYYPACT_NINF\fP   -11"
.br
.ti -1c
.RI "#define \fBYYTABLE_NINF\fP   -1"
.br
.ti -1c
.RI "#define \fByyerrok\fP   (yyerrstatus = 0)"
.br
.ti -1c
.RI "#define \fByyclearin\fP   (\fByychar\fP = YYEMPTY)"
.br
.ti -1c
.RI "#define \fBYYEMPTY\fP   (-2)"
.br
.ti -1c
.RI "#define \fBYYEOF\fP   0"
.br
.ti -1c
.RI "#define \fBYYACCEPT\fP   goto yyacceptlab"
.br
.ti -1c
.RI "#define \fBYYABORT\fP   goto yyabortlab"
.br
.ti -1c
.RI "#define \fBYYERROR\fP   goto yyerrorlab"
.br
.ti -1c
.RI "#define \fBYYFAIL\fP   goto yyerrlab"
.br
.ti -1c
.RI "#define \fBYYRECOVERING\fP()   (!!yyerrstatus)"
.br
.ti -1c
.RI "#define \fBYYBACKUP\fP(Token, Value)"
.br
.ti -1c
.RI "#define \fBYYTERROR\fP   1"
.br
.ti -1c
.RI "#define \fBYYERRCODE\fP   256"
.br
.ti -1c
.RI "#define \fBYYRHSLOC\fP(Rhs, K)   ((Rhs)[K])"
.br
.ti -1c
.RI "#define \fBYYLLOC_DEFAULT\fP(Current, Rhs, N)"
.br
.ti -1c
.RI "#define \fBYY_LOCATION_PRINT\fP(File, Loc)   ((void) 0)"
.br
.ti -1c
.RI "#define \fBYYLEX\fP   yylex ()"
.br
.ti -1c
.RI "#define \fBYYDPRINTF\fP(Args)"
.br
.ti -1c
.RI "#define \fBYY_SYMBOL_PRINT\fP(Title, Type, Value, Location)"
.br
.ti -1c
.RI "#define \fBYY_STACK_PRINT\fP(Bottom, Top)"
.br
.ti -1c
.RI "#define \fBYY_REDUCE_PRINT\fP(Rule)"
.br
.ti -1c
.RI "#define \fBYYINITDEPTH\fP   200"
.br
.ti -1c
.RI "#define \fBYYMAXDEPTH\fP   10000"
.br
.ti -1c
.RI "#define \fBYYPOPSTACK\fP(N)   (yyvsp -= (N), yyssp -= (N))"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned char \fByytype_uint8\fP"
.br
.ti -1c
.RI "typedef short int \fByytype_int8\fP"
.br
.ti -1c
.RI "typedef unsigned short int \fByytype_uint16\fP"
.br
.ti -1c
.RI "typedef short int \fByytype_int16\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fByytokentype\fP { \fB_ERROR_\fP =  258, \fBBEGIN_BLOCK\fP =  259, \fBEND_BLOCK\fP =  260, \fBBEGIN_SUB_BLOCK\fP =  261, \fBEND_SUB_BLOCK\fP =  262, \fBAFFECTATION\fP =  263, \fBEND_AFFECT\fP =  264, \fBIDENTIFIER\fP =  265, \fBKEYVALUE\fP =  266, \fB_ERROR_\fP =  258, \fBBEGIN_BLOCK\fP =  259, \fBEND_BLOCK\fP =  260, \fBBEGIN_SUB_BLOCK\fP =  261, \fBEND_SUB_BLOCK\fP =  262, \fBAFFECTATION\fP =  263, \fBEND_AFFECT\fP =  264, \fBIDENTIFIER\fP =  265, \fBKEYVALUE\fP =  266 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBganesha_yylex\fP (void)"
.br
.ti -1c
.RI "void \fBganesha_yyerror\fP (char *)"
.br
.ti -1c
.RI "int \fByyparse\fP ()"
.br
.ti -1c
.RI "void \fBset_error\fP (char *s)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBlist_items\fP * \fBprogram_result\fP = NULL"
.br
.ti -1c
.RI "char \fBlocal_errormsg\fP [1024] = ''"
.br
.ti -1c
.RI "char \fBextern_errormsg\fP [1024] = ''"
.br
.ti -1c
.RI "int \fByychar\fP"
.br
.ti -1c
.RI "\fBYYSTYPE\fP \fByylval\fP"
.br
.ti -1c
.RI "int \fByynerrs\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define _ERROR_   258"
.PP
Definition at line 152 of file conf_yacc.c.
.SS "#define AFFECTATION   263"
.PP
Definition at line 157 of file conf_yacc.c.
.SS "#define BEGIN_BLOCK   259"
.PP
Definition at line 153 of file conf_yacc.c.
.SS "#define BEGIN_SUB_BLOCK   261"
.PP
Definition at line 155 of file conf_yacc.c.
.SS "#define DEBUG_YACK"
.PP
Definition at line 106 of file conf_yacc.c.
.SS "#define END_AFFECT   264"
.PP
Definition at line 158 of file conf_yacc.c.
.SS "#define END_BLOCK   260"
.PP
Definition at line 154 of file conf_yacc.c.
.SS "#define END_SUB_BLOCK   262"
.PP
Definition at line 156 of file conf_yacc.c.
.SS "#define IDENTIFIER   265"
.PP
Definition at line 159 of file conf_yacc.c.
.SS "#define KEYVALUE   266"
.PP
Definition at line 160 of file conf_yacc.c.
.SS "#define YY_(msgid)   msgid"
.PP
Definition at line 248 of file conf_yacc.c.
.SS "#define YY_LOCATION_PRINT(File, Loc)   ((void) 0)"
.PP
Definition at line 653 of file conf_yacc.c.
.SS "#define YY_REDUCE_PRINT(Rule)"
.PP
Definition at line 826 of file conf_yacc.c.
.SS "#define YY_STACK_PRINT(Bottom, Top)"
.PP
Definition at line 825 of file conf_yacc.c.
.SS "#define YY_SYMBOL_PRINT(Title, Type, Value, Location)"
.PP
Definition at line 824 of file conf_yacc.c.
.SS "#define YYABORT   goto yyabortlab"
.PP
Definition at line 582 of file conf_yacc.c.
.SS "#define YYACCEPT   goto yyacceptlab"
.PP
Definition at line 581 of file conf_yacc.c.
.SS "#define YYBACKUP(Token, Value)"\fBValue:\fP
.PP
.nf
do                                                            \
  if (yychar == YYEMPTY && yylen == 1)                          \
    {                                                           \
      yychar = (Token);                                         \
      yylval = (Value);                                         \
      yytoken = YYTRANSLATE (yychar);                           \
      YYPOPSTACK (1);                                           \
      goto yybackup;                                            \
    }                                                           \
  else                                                          \
    {                                                           \
      yyerror (YY_('syntax error: cannot back up')); \
      YYERROR;                                                  \
    }                                                           \
while (YYID (0))
.fi
.PP
Definition at line 594 of file conf_yacc.c.
.SS "#define YYBISON   1"
.PP
Definition at line 46 of file conf_yacc.c.
.SS "#define YYBISON_VERSION   '2.4.1'"
.PP
Definition at line 49 of file conf_yacc.c.
.SS "#define \fByychar\fP   ganesha_yychar"
.PP
Definition at line 71 of file conf_yacc.c.
.SS "#define yyclearin   (\fByychar\fP = YYEMPTY)"
.PP
Definition at line 577 of file conf_yacc.c.
.SS "#define YYCOPY(To, From, Count)"\fBValue:\fP
.PP
.nf
do                                       \
        {                                       \
          YYSIZE_T yyi;                         \
          for (yyi = 0; yyi < (Count); yyi++)   \
            (To)[yyi] = (From)[yyi];            \
        }                                       \
      while (YYID (0))
.fi
.PP
Definition at line 374 of file conf_yacc.c.
.SS "#define YYDEBUG   0"
.PP
Definition at line 117 of file conf_yacc.c.
.SS "#define yydebug   ganesha_yydebug"
.PP
Definition at line 72 of file conf_yacc.c.
.SS "#define YYDPRINTF(Args)"
.PP
Definition at line 823 of file conf_yacc.c.
.SS "#define YYEMPTY   (-2)"
.PP
Definition at line 578 of file conf_yacc.c.
.SS "#define YYEOF   0"
.PP
Definition at line 579 of file conf_yacc.c.
.SS "#define YYERRCODE   256"
.PP
Definition at line 613 of file conf_yacc.c.
.SS "#define yyerrok   (yyerrstatus = 0)"
.PP
Definition at line 576 of file conf_yacc.c.
.SS "#define YYERROR   goto yyerrorlab"
.PP
Definition at line 583 of file conf_yacc.c.
.SS "#define yyerror   ganesha_yyerror"
.PP
Definition at line 69 of file conf_yacc.c.
.SS "#define YYERROR_VERBOSE   0"
.PP
Definition at line 125 of file conf_yacc.c.
.SS "#define YYFAIL   goto yyerrlab"
.PP
Definition at line 590 of file conf_yacc.c.
.SS "#define YYFINAL   6"
.PP
Definition at line 404 of file conf_yacc.c.
.SS "#define YYFREE   free"
.PP
Definition at line 337 of file conf_yacc.c.
.SS "#define YYID(n)   (n)"
.PP
Definition at line 261 of file conf_yacc.c.
.SS "#define YYINITDEPTH   200"
.PP
Definition at line 832 of file conf_yacc.c.
.SS "#define YYLAST   14"
.PP
Definition at line 406 of file conf_yacc.c.
.SS "#define YYLEX   yylex ()"
.PP
Definition at line 663 of file conf_yacc.c.
.SS "#define yylex   ganesha_yylex"
.PP
Definition at line 68 of file conf_yacc.c.
.SS "#define YYLLOC_DEFAULT(Current, Rhs, N)"\fBValue:\fP
.PP
.nf
do                                                                      \
      if (YYID (N))                                                    \
        {                                                               \
          (Current).first_line   = YYRHSLOC (Rhs, 1).first_line;        \
          (Current).first_column = YYRHSLOC (Rhs, 1).first_column;      \
          (Current).last_line    = YYRHSLOC (Rhs, N).last_line;         \
          (Current).last_column  = YYRHSLOC (Rhs, N).last_column;       \
        }                                                               \
      else                                                              \
        {                                                               \
          (Current).first_line   = (Current).last_line   =              \
            YYRHSLOC (Rhs, 0).last_line;                                \
          (Current).first_column = (Current).last_column =              \
            YYRHSLOC (Rhs, 0).last_column;                              \
        }                                                               \
    while (YYID (0))
.fi
.PP
Definition at line 622 of file conf_yacc.c.
.SS "#define YYLSP_NEEDED   0"
.PP
Definition at line 64 of file conf_yacc.c.
.SS "#define \fByylval\fP   \fBganesha_yylval\fP"
.PP
Definition at line 70 of file conf_yacc.c.
.SS "#define YYMALLOC   malloc"
.PP
Definition at line 330 of file conf_yacc.c.
.SS "#define YYMAXDEPTH   10000"
.PP
Definition at line 843 of file conf_yacc.c.
.SS "#define YYMAXUTOK   266"
.PP
Definition at line 419 of file conf_yacc.c.
.SS "#define \fByynerrs\fP   ganesha_yynerrs"
.PP
Definition at line 73 of file conf_yacc.c.
.SS "#define YYNNTS   8"
.PP
Definition at line 411 of file conf_yacc.c.
.SS "#define YYNRULES   11"
.PP
Definition at line 413 of file conf_yacc.c.
.SS "#define YYNSTATES   21"
.PP
Definition at line 415 of file conf_yacc.c.
.SS "#define YYNTOKENS   12"
.PP
Definition at line 409 of file conf_yacc.c.
.SS "#define YYPACT_NINF   -11"
.PP
Definition at line 536 of file conf_yacc.c.
.SS "int yyparse   ganesha_yyparse"
.PP
Definition at line 67 of file conf_yacc.c.
.SS "#define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N))"
.SS "#define YYPULL   1"
.PP
Definition at line 61 of file conf_yacc.c.
.SS "#define YYPURE   0"
.PP
Definition at line 55 of file conf_yacc.c.
.SS "#define YYPUSH   0"
.PP
Definition at line 58 of file conf_yacc.c.
.SS "#define YYRECOVERING()   (!!yyerrstatus)"
.PP
Definition at line 592 of file conf_yacc.c.
.SS "#define YYRHSLOC(Rhs, K)   ((Rhs)[K])"
.PP
Definition at line 620 of file conf_yacc.c.
.SS "#define YYSIZE_MAXIMUM   ((YYSIZE_T) -1)"
.PP
Definition at line 238 of file conf_yacc.c.
.SS "#define YYSIZE_T   unsigned int"
.PP
Definition at line 234 of file conf_yacc.c.
.SS "#define YYSKELETON_NAME   'yacc.c'"
.PP
Definition at line 52 of file conf_yacc.c.
.SS "#define YYSTACK_ALLOC   YYMALLOC"
.PP
Definition at line 316 of file conf_yacc.c.
.SS "#define YYSTACK_ALLOC_MAXIMUM   YYSIZE_MAXIMUM"
.PP
Definition at line 319 of file conf_yacc.c.
.SS "#define YYSTACK_BYTES(N)"\fBValue:\fP
.PP
.nf
((N) * (sizeof (yytype_int16) + sizeof (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)
.fi
.PP
Definition at line 363 of file conf_yacc.c.
.SS "#define YYSTACK_FREE   YYFREE"
.PP
Definition at line 317 of file conf_yacc.c.
.SS "#define YYSTACK_GAP_MAXIMUM   (sizeof (union \fByyalloc\fP) - 1)"
.PP
Definition at line 359 of file conf_yacc.c.
.SS "#define YYSTACK_RELOCATE(Stack_alloc, Stack)"\fBValue:\fP
.PP
.nf
do                                                                       \
      {                                                                 \
        YYSIZE_T yynewbytes;                                            \
        YYCOPY (&yyptr->Stack_alloc, Stack, yysize);                    \
        Stack = &yyptr->Stack_alloc;                                    \
        yynewbytes = yystacksize * sizeof (*Stack) + YYSTACK_GAP_MAXIMUM; \
        yyptr += yynewbytes / sizeof (*yyptr);                          \
      }                                                                 \
    while (YYID (0))
.fi
.PP
Definition at line 390 of file conf_yacc.c.
.SS "#define yystype   \fBYYSTYPE\fP"
.PP
Definition at line 182 of file conf_yacc.c.
.SS "#define YYSTYPE_IS_DECLARED   1"
.PP
Definition at line 183 of file conf_yacc.c.
.SS "#define YYSTYPE_IS_TRIVIAL   1"
.PP
Definition at line 181 of file conf_yacc.c.
.SS "#define YYTABLE_NINF   -1"
.PP
Definition at line 554 of file conf_yacc.c.
.SS "#define YYTERROR   1"
.PP
Definition at line 612 of file conf_yacc.c.
.SS "#define YYTOKEN_TABLE   0"
.PP
Definition at line 130 of file conf_yacc.c.
.SS "#define YYTRANSLATE(YYX)   ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)"
.PP
Definition at line 421 of file conf_yacc.c.
.SS "#define YYUNDEFTOK   2"
.PP
Definition at line 418 of file conf_yacc.c.
.SS "#define YYUSE(e)   ((void) (e))"
.PP
Definition at line 254 of file conf_yacc.c.
.SH "Typedef Documentation"
.PP 
.SS "typedef short int \fByytype_int16\fP"
.PP
Definition at line 221 of file conf_yacc.c.
.SS "typedef short int \fByytype_int8\fP"
.PP
Definition at line 209 of file conf_yacc.c.
.SS "typedef unsigned short int \fByytype_uint16\fP"
.PP
Definition at line 215 of file conf_yacc.c.
.SS "typedef unsigned char \fByytype_uint8\fP"
.PP
Definition at line 200 of file conf_yacc.c.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fByytokentype\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fI_ERROR_ \fP\fP
.TP
\fB\fIBEGIN_BLOCK \fP\fP
.TP
\fB\fIEND_BLOCK \fP\fP
.TP
\fB\fIBEGIN_SUB_BLOCK \fP\fP
.TP
\fB\fIEND_SUB_BLOCK \fP\fP
.TP
\fB\fIAFFECTATION \fP\fP
.TP
\fB\fIEND_AFFECT \fP\fP
.TP
\fB\fIIDENTIFIER \fP\fP
.TP
\fB\fIKEYVALUE \fP\fP
.TP
\fB\fI_ERROR_ \fP\fP
.TP
\fB\fIBEGIN_BLOCK \fP\fP
.TP
\fB\fIEND_BLOCK \fP\fP
.TP
\fB\fIBEGIN_SUB_BLOCK \fP\fP
.TP
\fB\fIEND_SUB_BLOCK \fP\fP
.TP
\fB\fIAFFECTATION \fP\fP
.TP
\fB\fIEND_AFFECT \fP\fP
.TP
\fB\fIIDENTIFIER \fP\fP
.TP
\fB\fIKEYVALUE \fP\fP

.PP
Definition at line 139 of file conf_yacc.c.
.SH "Function Documentation"
.PP 
.SS "void ganesha_yyerror (char * s)"
.PP
Definition at line 1658 of file conf_yacc.c.
.SS "int ganesha_yylex (void)"
.SS "void set_error (char * s)"
.PP
Definition at line 1665 of file conf_yacc.c.
.SS "int yyparse ()"
.PP
Definition at line 1138 of file conf_yacc.c.
.SH "Variable Documentation"
.PP 
.SS "char \fBextern_errormsg\fP[1024] = ''"
.PP
Definition at line 101 of file conf_yacc.c.
.SS "char \fBlocal_errormsg\fP[1024] = ''"
.PP
Definition at line 98 of file conf_yacc.c.
.SS "\fBlist_items\fP* \fBprogram_result\fP = NULL"
.PP
Definition at line 95 of file conf_yacc.c.
.SS "int \fByychar\fP"
.PP
Definition at line 1107 of file conf_yacc.c.
.SS "\fBYYSTYPE\fP \fByylval\fP"
.PP
Definition at line 1110 of file conf_yacc.c.
.SS "int \fByynerrs\fP"
.PP
Definition at line 1113 of file conf_yacc.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigParsing from the source code.
