.TH "test_parse.c" 3 "9 Apr 2008" "Version 0.1" "ConfigParsing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_parse.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'config_parsing.h'\fP
.br
\fC#include <errno.h>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <string.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"
.PP
Definition at line 83 of file test_parse.c.
.PP
References config_Free(), config_GetBlockName(), config_GetErrorMsg(), config_GetKeyValue(), config_GetNbBlocks(), config_GetNbKeys(), and config_ParseFile().
.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigParsing from the source code.
