.TH "verif_syntax.c" 3 "9 Apr 2008" "Version 0.1" "ConfigParsing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
verif_syntax.c \- Construction de l'arbre syntaxique. 
.SH SYNOPSIS
.br
.PP
\fC#include 'config_parsing.h'\fP
.br
\fC#include <errno.h>\fP
.br
\fC#include <stdio.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Construction de l'arbre syntaxique. 

\fBAuthor:\fP
.RS 4
\fBAuthor\fP.RS 4
deniel 
.RE
.PP
.RE
.PP
\fBDate:\fP
.RS 4
\fBDate\fP.RS 4
2005/11/28 17:02:31 
.RE
.PP
.RE
.PP
\fBVersion:\fP
.RS 4
\fBRevision\fP.RS 4
1.4 
.RE
.PP
.RE
.PP
Teste la syntaxe d'un fichier de configuration.
.PP
Definition in file \fBverif_syntax.c\fP.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"
.PP
Definition at line 95 of file verif_syntax.c.
.PP
References config_Free(), config_GetErrorMsg(), and config_ParseFile().
.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigParsing from the source code.
