.TH "yy_buffer_state" 3 "9 Apr 2008" "Version 0.1" "ConfigParsing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
yy_buffer_state \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FILE * \fByy_input_file\fP"
.br
.ti -1c
.RI "char * \fByy_ch_buf\fP"
.br
.ti -1c
.RI "char * \fByy_buf_pos\fP"
.br
.ti -1c
.RI "\fByy_size_t\fP \fByy_buf_size\fP"
.br
.ti -1c
.RI "int \fByy_n_chars\fP"
.br
.ti -1c
.RI "int \fByy_is_our_buffer\fP"
.br
.ti -1c
.RI "int \fByy_is_interactive\fP"
.br
.ti -1c
.RI "int \fByy_at_bol\fP"
.br
.ti -1c
.RI "int \fByy_fill_buffer\fP"
.br
.ti -1c
.RI "int \fByy_buffer_status\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int \fByy_buffer_state::yy_at_bol\fP"
.PP
Definition at line 178 of file conf_lex.c.
.SS "char* \fByy_buffer_state::yy_buf_pos\fP"
.PP
Definition at line 149 of file conf_lex.c.
.SS "\fByy_size_t\fP \fByy_buffer_state::yy_buf_size\fP"
.PP
Definition at line 154 of file conf_lex.c.
.SS "int \fByy_buffer_state::yy_buffer_status\fP"
.PP
Definition at line 185 of file conf_lex.c.
.SS "char* \fByy_buffer_state::yy_ch_buf\fP"
.PP
Definition at line 148 of file conf_lex.c.
.SS "int \fByy_buffer_state::yy_fill_buffer\fP"
.PP
Definition at line 183 of file conf_lex.c.
.SS "FILE* \fByy_buffer_state::yy_input_file\fP"
.PP
Definition at line 146 of file conf_lex.c.
.SS "int \fByy_buffer_state::yy_is_interactive\fP"
.PP
Definition at line 172 of file conf_lex.c.
.SS "int \fByy_buffer_state::yy_is_our_buffer\fP"
.PP
Definition at line 165 of file conf_lex.c.
.SS "int \fByy_buffer_state::yy_n_chars\fP"
.PP
Definition at line 159 of file conf_lex.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigParsing from the source code.
