.TH "yyalloc" 3 "9 Apr 2008" "Version 0.1" "ConfigParsing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
yyalloc \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fByyss\fP"
.br
.ti -1c
.RI "\fBYYSTYPE\fP \fByyvs\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "short \fByyalloc::yyss\fP"
.PP
Definition at line 188 of file conf_yacc.c.
.SS "\fBYYSTYPE\fP \fByyalloc::yyvs\fP"
.PP
Definition at line 189 of file conf_yacc.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigParsing from the source code.
