.TH "YYSTYPE" 3 "15 Sep 2010" "Version 0.1" "ConfigParsing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YYSTYPE \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBstr_val\fP [MAXSTRLEN]"
.br
.ti -1c
.RI "\fBlist_items\fP * \fBlist\fP"
.br
.ti -1c
.RI "\fBgeneric_item\fP * \fBitem\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 166 of file conf_yacc.c.
.SH "Member Data Documentation"
.PP 
.SS "\fBgeneric_item\fP* \fBYYSTYPE::item\fP"
.PP
Definition at line 174 of file conf_yacc.c.
.SS "\fBlist_items\fP* \fBYYSTYPE::list\fP"
.PP
Definition at line 173 of file conf_yacc.c.
.SS "char \fBYYSTYPE::str_val\fP[MAXSTRLEN]"
.PP
Definition at line 172 of file conf_yacc.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigParsing from the source code.
