.TH "YYSTYPE" 3 "31 Mar 2009" "Version 0.1" "ConfigParsing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YYSTYPE \- 
.SH SYNOPSIS
.br
.PP
\fC#include <conf_yacc.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBstr_val\fP [MAXSTRLEN]"
.br
.ti -1c
.RI "\fBlist_items\fP * \fBlist\fP"
.br
.ti -1c
.RI "\fBgeneric_item\fP * \fBitem\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 155 of file conf_yacc.c.
.SH "Member Data Documentation"
.PP 
.SS "\fBgeneric_item\fP * \fBYYSTYPE::item\fP"
.PP
Definition at line 160 of file conf_yacc.c.
.SS "\fBlist_items\fP * \fBYYSTYPE::list\fP"
.PP
Definition at line 159 of file conf_yacc.c.
.SS "char \fBYYSTYPE::str_val\fP"
.PP
Definition at line 158 of file conf_yacc.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigParsing from the source code.
