.TH "cache_inode_get.c" 3 "15 Sep 2010" "Version 0.1" "Cache inode layer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cache_inode_get.c \- 
.PP
Get and eventually cache an entry.  

.SH SYNOPSIS
.br
.PP
\fC#include 'LRU_List.h'\fP
.br
\fC#include 'log_macros.h'\fP
.br
\fC#include 'HashData.h'\fP
.br
\fC#include 'HashTable.h'\fP
.br
\fC#include 'fsal.h'\fP
.br
\fC#include 'cache_inode.h'\fP
.br
\fC#include 'stuff_alloc.h'\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <sys/types.h>\fP
.br
\fC#include <sys/param.h>\fP
.br
\fC#include <time.h>\fP
.br
\fC#include <pthread.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "cache_entry_t * \fBcache_inode_get\fP (cache_inode_fsal_data_t *pfsdata, fsal_attrib_list_t *pattr, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Get and eventually cache an entry. 

\fBAuthor:\fP
.RS 4
.RE
.PP
\fBAuthor\fP.RS 4
deniel 
.RE
.PP
\fBDate:\fP
.RS 4
.RE
.PP
\fBDate\fP.RS 4
2005/11/28 17:02:26 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision\fP.RS 4
1.26 
.RE
.PP
\fBcache_inode_get.c\fP : Get and eventually cache an entry. 
.PP
Definition in file \fBcache_inode_get.c\fP.
.SH "Function Documentation"
.PP 
.SS "cache_entry_t* cache_inode_get (cache_inode_fsal_data_t * pfsdata, fsal_attrib_list_t * pattr, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus)"cache_inode_get: Gets an entry by using its fsdata as a key and caches it if needed.
.PP
Gets an entry by using its fsdata as a key and caches it if needed. ASSUMPTION: DIR_CONT entries are always garbabbaged before their related DIR_BEGINNG
.PP
\fBParameters:\fP
.RS 4
\fIfsdata\fP [IN] file system data 
.br
\fIpattr\fP [OUT] pointer to the attributes for the result. 
.br
\fIht\fP [IN] hash table used for the cache, unused in this call. 
.br
\fIpclient\fP [INOUT] ressource allocated by the client for the nfs management. 
.br
\fIpcontext\fP [IN] FSAL credentials 
.br
\fIpstatus\fP [OUT] returned status.
.RE
.PP
\fBReturns:\fP
.RS 4
the pointer to the entry is successfull, NULL otherwise. 
.RE
.PP

.PP
Definition at line 76 of file cache_inode_get.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Cache inode layer from the source code.
