.TH "cache_inode_release.c" 3 "9 Apr 2008" "Version 0.1" "Cache inode layer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cache_inode_release.c \- Release an entry. 
.SH SYNOPSIS
.br
.PP
\fC#include 'LRU_List.h'\fP
.br
\fC#include 'log_functions.h'\fP
.br
\fC#include 'HashData.h'\fP
.br
\fC#include 'HashTable.h'\fP
.br
\fC#include 'fsal.h'\fP
.br
\fC#include 'cache_inode.h'\fP
.br
\fC#include 'stuff_alloc.h'\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <sys/types.h>\fP
.br
\fC#include <sys/param.h>\fP
.br
\fC#include <time.h>\fP
.br
\fC#include <pthread.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "cache_inode_status_t \fBcache_inode_release\fP (cache_entry_t *pentry, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Release an entry. 

\fBAuthor:\fP
.RS 4
\fBAuthor\fP.RS 4
deniel 
.RE
.PP
.RE
.PP
\fBDate:\fP
.RS 4
\fBDate\fP.RS 4
2005/12/20 10:51:50 
.RE
.PP
.RE
.PP
\fBVersion:\fP
.RS 4
\fBRevision\fP.RS 4
1.10 
.RE
.PP
.RE
.PP
\fBcache_inode_release.c\fP : Release an entry.
.PP
Definition in file \fBcache_inode_release.c\fP.
.SH "Function Documentation"
.PP 
.SS "cache_inode_status_t cache_inode_release (cache_entry_t * pentry, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus)"
.PP
Definition at line 107 of file cache_inode_release.c.
.PP
References cache_inode_fsaldata_2_key(), cache_inode_get_fsal_handle(), cache_inode_mutex_destroy(), and cache_inode_release_fsaldata_key().
.SH "Author"
.PP 
Generated automatically by Doxygen for Cache inode layer from the source code.
