.TH "cache_inode_release_data_cache.c" 3 "31 Mar 2009" "Version 0.1" "Cache inode layer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cache_inode_release_data_cache.c \- Associates a File Content cache entry to a pentry of type REGULAR FILE.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include 'LRU_List.h'\fP
.br
\fC#include 'log_functions.h'\fP
.br
\fC#include 'HashData.h'\fP
.br
\fC#include 'HashTable.h'\fP
.br
\fC#include 'fsal.h'\fP
.br
\fC#include 'cache_inode.h'\fP
.br
\fC#include 'cache_content.h'\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <sys/types.h>\fP
.br
\fC#include <sys/param.h>\fP
.br
\fC#include <time.h>\fP
.br
\fC#include <pthread.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "cache_inode_status_t \fBcache_inode_release_data_cache\fP (cache_entry_t *pentry, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Associates a File Content cache entry to a pentry of type REGULAR FILE. 

\fBAuthor:\fP
.RS 4
.RE
.PP
\fBAuthor\fP.RS 4
deniel 
.RE
.PP
\fBDate:\fP
.RS 4
.RE
.PP
\fBDate\fP.RS 4
2005/11/28 17:02:27 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision\fP.RS 4
1.4 
.RE
.PP
\fBcache_inode_release_data_cache.c\fP : Associates a File Content cache entry to a pentry of type REGULAR FILE. 
.PP
Definition in file \fBcache_inode_release_data_cache.c\fP.
.SH "Function Documentation"
.PP 
.SS "cache_inode_status_t cache_inode_release_data_cache (cache_entry_t * pentry, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus)"
.PP
Definition at line 111 of file cache_inode_release_data_cache.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Cache inode layer from the source code.
