.TH "Cache Inode GC internal functions." 3 "31 Mar 2009" "Version 0.1" "Cache inode layer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cache Inode GC internal functions. \- 
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcache_inode_gc_suppress_file\fP (cache_entry_t *pentry, cache_inode_param_gc_t *pgcparam)"
.br
.ti -1c
.RI "int \fBcache_inode_gc_suppress_directory\fP (cache_entry_t *pentry, cache_inode_param_gc_t *pgcparam)"
.br
.ti -1c
.RI "int \fBcache_inode_gc_function\fP (LRU_entry_t *plru_entry, void *addparam)"
.br
.in -1c
.SH "Detailed Description"
.PP 
These functions are used for Garbagge collector internal management. 
.SH "Function Documentation"
.PP 
.SS "int cache_inode_gc_function (LRU_entry_t * plru_entry, void * addparam)"
.PP
cache_inode_gc_function: Tests is an entry in cache inode is to be set invalid (has expired).
.PP
Tests is an entry in cache inode is to be set invalid (has expired). If entry is invalidated, does the cleaning stuff on it.
.PP
\fBParameters:\fP
.RS 4
\fIpentry\fP [IN] pointer to the entry to test
.RE
.PP
\fBReturns:\fP
.RS 4
1 if entry must be set invalid, 0 if not.
.RE
.PP
\fBSee also:\fP
.RS 4
LRU_invalidate_by_function 
.PP
LRU_gc_invalid 
.RE
.PP

.PP
Definition at line 492 of file cache_inode_gc.c.
.SS "int cache_inode_gc_suppress_directory (cache_entry_t * pentry, cache_inode_param_gc_t * pgcparam)"
.PP
cache_inode_gc_suppress_directory: suppress a directory entry from the cache inode.
.PP
Suppress a file entry from the cache inode.
.PP
\fBParameters:\fP
.RS 4
\fIpentry\fP [IN] pointer to the entry to be suppressed.
.RE
.PP
\fBReturns:\fP
.RS 4
1 if entry is successfully suppressed, 0 otherwise
.RE
.PP
\fBSee also:\fP
.RS 4
LRU_invalidate_by_function 
.PP
LRU_gc_invalid 
.RE
.PP

.PP
Definition at line 418 of file cache_inode_gc.c.
.SS "int cache_inode_gc_suppress_file (cache_entry_t * pentry, cache_inode_param_gc_t * pgcparam)"
.PP
cache_inode_gc_suppress_file: suppress a file entry from the cache inode.
.PP
Suppress a file entry from the cache inode.
.PP
\fBParameters:\fP
.RS 4
\fIpentry\fP [IN] pointer to the entry to be suppressed.
.RE
.PP
\fBReturns:\fP
.RS 4
LRU_LIST_SET_INVALID if entry is successfully suppressed, LRU_LIST_DO_NOT_SET_INVALID otherwise
.RE
.PP
\fBSee also:\fP
.RS 4
LRU_invalidate_by_function 
.PP
LRU_gc_invalid 
.RE
.PP

.PP
Definition at line 374 of file cache_inode_gc.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Cache inode layer from the source code.
