.TH "Cache Inode GC interface." 3 "9 Apr 2008" "Version 0.1" "Cache inode layer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cache Inode GC interface. \- 
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcache_inode_set_gc_policy\fP (cache_inode_gc_policy_t policy)"
.br
.ti -1c
.RI "cache_inode_gc_policy_t \fBcache_inode_get_gc_policy\fP (void)"
.br
.ti -1c
.RI "cache_inode_status_t \fBcache_inode_gc\fP (hash_table_t *ht, cache_inode_client_t *pclient, cache_inode_status_t *pstatus)"
.br
.in -1c
.SH "Detailed Description"
.PP 
These functions are used to run and configure the Cache inode GC 
.SH "Function Documentation"
.PP 
.SS "cache_inode_status_t cache_inode_gc (hash_table_t * ht, cache_inode_client_t * pclient, cache_inode_status_t * pstatus)"
.PP
cache_inode_gc: Perform garbbage collection on the ressources managed by a client.
.PP
Perform garbbage collection on the ressources managed by a client.
.PP
\fBParameters:\fP
.RS 4
\fIht\fP [INOUT] the hashtable used to stored the cache_inode entries. 
.br
\fIpclient\fP [INOUT] ressource allocated by the client for the nfs management. 
.br
\fIpstatus\fP [OUT] returned status.
.RE
.PP
\fBReturns:\fP
.RS 4
CACHE_INODE_SUCCESS if operation is a success 
.br
 
.PP
CACHE_INODE_LRU_ERROR if allocation error occured when validating the entry
.RE
.PP
\fBSee also:\fP
.RS 4
HashTable_GetSize 
.PP
LRU_invalidate_by_function 
.PP
LRU_gc_invalid 
.RE
.PP

.PP
Definition at line 603 of file cache_inode_gc.c.
.PP
References cache_inode_gc_function().
.PP
Referenced by main().
.SS "cache_inode_gc_policy_t cache_inode_get_gc_policy (void)"
.PP
cache_inode_get_gc_policy: Set the cache_inode garbagge collecting policy.
.PP
\fBReturns:\fP
.RS 4
the current policy. 
.RE
.PP

.PP
Definition at line 580 of file cache_inode_gc.c.
.SS "void cache_inode_set_gc_policy (cache_inode_gc_policy_t policy)"
.PP
cache_inode_set_gc_policy: Set the cache_inode garbagge collecting policy.
.PP
\fBParameters:\fP
.RS 4
\fIpolicy\fP [IN] policy to be set.
.RE
.PP
\fBReturns:\fP
.RS 4
nothing (void function) 
.RE
.PP

.PP
Definition at line 567 of file cache_inode_gc.c.
.PP
Referenced by main().
