.TH "cache_inode_read_conf.c" 3 "15 Sep 2010" "Version 0.1" "Cache inode layer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cache_inode_read_conf.c \- 
.PP
Read the configuration file for the Cache inode initialization.  

.SH SYNOPSIS
.br
.PP
\fC#include 'LRU_List.h'\fP
.br
\fC#include 'log_macros.h'\fP
.br
\fC#include 'HashData.h'\fP
.br
\fC#include 'HashTable.h'\fP
.br
\fC#include 'fsal.h'\fP
.br
\fC#include 'cache_inode.h'\fP
.br
\fC#include 'stuff_alloc.h'\fP
.br
\fC#include 'config_parsing.h'\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <sys/types.h>\fP
.br
\fC#include <sys/param.h>\fP
.br
\fC#include <time.h>\fP
.br
\fC#include <pthread.h>\fP
.br
\fC#include <string.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "cache_inode_status_t \fBcache_inode_read_conf_hash_parameter\fP (config_file_t in_config, cache_inode_parameter_t *pparam)"
.br
.ti -1c
.RI "cache_inode_status_t \fBcache_inode_read_conf_client_parameter\fP (config_file_t in_config, cache_inode_client_parameter_t *pparam)"
.br
.ti -1c
.RI "cache_inode_status_t \fBcache_inode_read_conf_gc_policy\fP (config_file_t in_config, cache_inode_gc_policy_t *ppolicy)"
.br
.ti -1c
.RI "void \fBcache_inode_print_conf_hash_parameter\fP (FILE *output, cache_inode_parameter_t param)"
.br
.ti -1c
.RI "void \fBcache_inode_print_conf_client_parameter\fP (FILE *output, cache_inode_client_parameter_t param)"
.br
.ti -1c
.RI "void \fBcache_inode_print_conf_gc_policy\fP (FILE *output, cache_inode_gc_policy_t gcpolicy)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Read the configuration file for the Cache inode initialization. 

\fBAuthor:\fP
.RS 4
.RE
.PP
\fBAuthor\fP.RS 4
leibovic 
.RE
.PP
\fBDate:\fP
.RS 4
.RE
.PP
\fBDate\fP.RS 4
2006/02/16 08:21:47 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision\fP.RS 4
1.11 
.RE
.PP
\fBcache_inode_read_conf.c\fP : Read the configuration file for the Cache inode initialization. 
.PP
Definition in file \fBcache_inode_read_conf.c\fP.
.SH "Function Documentation"
.PP 
.SS "void cache_inode_print_conf_client_parameter (FILE * output, cache_inode_client_parameter_t param)"cache_inode_print_conf_client_parameter: prints the client parameter.
.PP
Prints the client parameters.
.PP
\fBParameters:\fP
.RS 4
\fIoutput\fP [IN] a descriptor to the IO for printing the data. 
.br
\fIparam\fP [IN] structure to be printed.
.RE
.PP
\fBReturns:\fP
.RS 4
nothing (void function). 
.RE
.PP

.PP
Definition at line 419 of file cache_inode_read_conf.c.
.SS "void cache_inode_print_conf_gc_policy (FILE * output, cache_inode_gc_policy_t gcpolicy)"cache_inode_print_gc_pol: prints the garbage collection policy.
.PP
Prints the garbage collection policy.
.PP
\fBParameters:\fP
.RS 4
\fIoutput\fP [IN] a descriptor to the IO for printing the data. 
.br
\fIparam\fP [IN] structure to be printed.
.RE
.PP
\fBReturns:\fP
.RS 4
nothing (void function). 
.RE
.PP

.PP
Definition at line 454 of file cache_inode_read_conf.c.
.SS "void cache_inode_print_conf_hash_parameter (FILE * output, cache_inode_parameter_t param)"cache_inode_print_conf_gc_policy: prints the garbage collection policy.
.PP
Prints the garbage collection policy in configuration file.
.PP
\fBParameters:\fP
.RS 4
\fIoutput\fP [IN] a descriptor to the IO for printing the data. 
.br
\fIparam\fP [IN] structure to be printed.
.RE
.PP
\fBReturns:\fP
.RS 4
nothing (void function). 
.RE
.PP

.PP
Definition at line 397 of file cache_inode_read_conf.c.
.SS "cache_inode_status_t cache_inode_read_conf_client_parameter (config_file_t in_config, cache_inode_client_parameter_t * pparam)"cache_inode_read_conf_client_parameter: read the configuration for a client to Cache inode layer.
.PP
Reads the configuration for a client to Cache inode layer (typically a worker thread).
.PP
\fBParameters:\fP
.RS 4
\fIin_config\fP [IN] configuration file handle 
.br
\fIpparam\fP [OUT] read parameters
.RE
.PP
\fBReturns:\fP
.RS 4
CACHE_INODE_SUCCESS if ok, CACHE_INODE_NOT_FOUND is stanza is not there, CACHE_INODE_INVALID_ARGUMENT otherwise. 
.RE
.PP

.PP
Definition at line 153 of file cache_inode_read_conf.c.
.SS "cache_inode_status_t cache_inode_read_conf_gc_policy (config_file_t in_config, cache_inode_gc_policy_t * ppolicy)"cache_inode_read_conf_gc_policy: read the garbage collection policy in configuration file.
.PP
Reads the garbage collection policy in configuration file.
.PP
\fBParameters:\fP
.RS 4
\fIin_config\fP [IN] configuration file handle 
.br
\fIpparam\fP [OUT] read parameters
.RE
.PP
\fBReturns:\fP
.RS 4
CACHE_INODE_SUCCESS if ok, CACHE_INODE_NOT_FOUND is stanza is not there, CACHE_INODE_INVALID_ARGUMENT otherwise. 
.RE
.PP

.PP
Definition at line 305 of file cache_inode_read_conf.c.
.SS "cache_inode_status_t cache_inode_read_conf_hash_parameter (config_file_t in_config, cache_inode_parameter_t * pparam)"cache_inode_read_conf_hash_parameter: read the configuration for the hash in Cache_inode layer.
.PP
Reads the configuration for the hash in Cache_inode layer.
.PP
\fBParameters:\fP
.RS 4
\fIin_config\fP [IN] configuration file handle 
.br
\fIpparam\fP [OUT] read parameters
.RE
.PP
\fBReturns:\fP
.RS 4
CACHE_INODE_SUCCESS if ok, CACHE_INODE_NOT_FOUND is stanza is not there, CACHE_INODE_INVALID_ARGUMENT otherwise. 
.RE
.PP

.PP
Definition at line 73 of file cache_inode_read_conf.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Cache inode layer from the source code.
