.TH "cache_inode_create.c" 3 "15 Sep 2010" "Version 0.1" "Cache inode layer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cache_inode_create.c \- 
.PP
Creation of a file through the cache layer.  

.SH SYNOPSIS
.br
.PP
\fC#include 'LRU_List.h'\fP
.br
\fC#include 'log_macros.h'\fP
.br
\fC#include 'HashData.h'\fP
.br
\fC#include 'HashTable.h'\fP
.br
\fC#include 'fsal.h'\fP
.br
\fC#include 'cache_inode.h'\fP
.br
\fC#include 'stuff_alloc.h'\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <sys/types.h>\fP
.br
\fC#include <sys/param.h>\fP
.br
\fC#include <time.h>\fP
.br
\fC#include <pthread.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "cache_entry_t * \fBcache_inode_create\fP (cache_entry_t *pentry_parent, fsal_name_t *pname, cache_inode_file_type_t type, fsal_accessmode_t mode, cache_inode_create_arg_t *pcreate_arg, fsal_attrib_list_t *pattr, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus)"
.br
.ti -1c
.RI "cache_entry_t * \fBcache_inode_create_open\fP (cache_entry_t *pentry_parent, fsal_name_t *pname, cache_inode_file_type_t type, fsal_accessmode_t mode, cache_inode_create_arg_t *pcreate_arg, fsal_openflags_t openflags, fsal_attrib_list_t *pattr, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Creation of a file through the cache layer. 

\fBAuthor:\fP
.RS 4
.RE
.PP
\fBAuthor\fP.RS 4
deniel 
.RE
.PP
\fBDate:\fP
.RS 4
.RE
.PP
\fBDate\fP.RS 4
2005/11/28 17:02:26 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision\fP.RS 4
1.29 
.RE
.PP
cache_inode_mkdir.c : Creation of an entry through the cache layer 
.PP
Definition in file \fBcache_inode_create.c\fP.
.SH "Function Documentation"
.PP 
.SS "cache_entry_t* cache_inode_create (cache_entry_t * pentry_parent, fsal_name_t * pname, cache_inode_file_type_t type, fsal_accessmode_t mode, cache_inode_create_arg_t * pcreate_arg, fsal_attrib_list_t * pattr, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus)"cache_inode_create: creates an entry through the cache.
.PP
Creates an entry through the cache.
.PP
\fBParameters:\fP
.RS 4
\fIpentry_parent\fP [IN] pointer to the pentry parent 
.br
\fIpname\fP [IN] pointer to the name of the object in the destination directory. 
.br
\fItype\fP [IN] type of the object to be created. 
.br
\fImode\fP [IN] mode to be used at file creation 
.br
\fIpcreate_arg\fP [IN] additional argument for object creation 
.br
\fIpattr\fP [OUT] attributes for the new object. 
.br
\fIht\fP [INOUT] hash table used for the cache. 
.br
\fIpclient\fP [INOUT] ressource allocated by the client for the nfs management. 
.br
\fIpcontext\fP [IN] FSAL credentials 
.br
\fIpstatus\fP [OUT] returned status.
.RE
.PP
\fBReturns:\fP
.RS 4
CACHE_INODE_SUCCESS if operation is a success 
.br
 
.PP
CACHE_INODE_LRU_ERROR if allocation error occured when validating the entry
.br
 
.PP
CACHE_INODE_BAD_TYPE either source or destination have incorrect type
.br
 
.PP
CACHE_INODE_ENTRY_EXISTS entry of that name already exists in destination. 
.RE
.PP

.PP
Definition at line 86 of file cache_inode_create.c.
.SS "cache_entry_t* cache_inode_create_open (cache_entry_t * pentry_parent, fsal_name_t * pname, cache_inode_file_type_t type, fsal_accessmode_t mode, cache_inode_create_arg_t * pcreate_arg, fsal_openflags_t openflags, fsal_attrib_list_t * pattr, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus)"cache_inode_create_open: creates a file and opens it at the same time (for NFSv4 semantics)
.PP
Creates an entry through the cache.
.PP
\fBParameters:\fP
.RS 4
\fIpentry_parent\fP [IN] pointer to the pentry parent 
.br
\fIpname\fP [IN] pointer to the name of the object in the destination directory. 
.br
\fItype\fP [IN] type of the object to be created. 
.br
\fImode\fP [IN] mode to be used at file creation 
.br
\fIopenflags\fP [IN] flags to be used during file open 
.br
\fIpcreate_arg\fP [IN] additional argument for object creation 
.br
\fIpattr\fP [OUT] attributes for the new object. 
.br
\fIht\fP [INOUT] hash table used for the cache. 
.br
\fIpclient\fP [INOUT] ressource allocated by the client for the nfs management. 
.br
\fIpcontext\fP [IN] FSAL credentials 
.br
\fIpstatus\fP [OUT] returned status.
.RE
.PP
\fBReturns:\fP
.RS 4
CACHE_INODE_SUCCESS if operation is a success 
.br
 
.PP
CACHE_INODE_LRU_ERROR if allocation error occured when validating the entry
.br
 
.PP
CACHE_INODE_BAD_TYPE either source or destination have incorrect type
.br
 
.PP
CACHE_INODE_ENTRY_EXISTS entry of that name already exists in destination. 
.RE
.PP

.PP
Definition at line 469 of file cache_inode_create.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Cache inode layer from the source code.
