.TH "cache_inode_make_root.c" 3 "31 Mar 2009" "Version 0.1" "Cache inode layer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cache_inode_make_root.c \- Insert in the cache an entry that is the root of the FS cached.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include 'LRU_List.h'\fP
.br
\fC#include 'log_functions.h'\fP
.br
\fC#include 'HashData.h'\fP
.br
\fC#include 'HashTable.h'\fP
.br
\fC#include 'fsal.h'\fP
.br
\fC#include 'cache_inode.h'\fP
.br
\fC#include 'stuff_alloc.h'\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <sys/types.h>\fP
.br
\fC#include <sys/param.h>\fP
.br
\fC#include <time.h>\fP
.br
\fC#include <pthread.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "cache_entry_t * \fBcache_inode_make_root\fP (cache_inode_fsal_data_t *pfsdata, hash_table_t *ht, cache_inode_client_t *pclient, fsal_op_context_t *pcontext, cache_inode_status_t *pstatus)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Insert in the cache an entry that is the root of the FS cached. 

\fBAuthor:\fP
.RS 4
.RE
.PP
\fBAuthor\fP.RS 4
deniel 
.RE
.PP
\fBDate:\fP
.RS 4
.RE
.PP
\fBDate\fP.RS 4
2005/11/28 17:02:26 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision\fP.RS 4
1.12 
.RE
.PP
\fBcache_inode_make_root.c\fP : Inserts in the cache an entry that is the root of the FS cached. 
.PP
Definition in file \fBcache_inode_make_root.c\fP.
.SH "Function Documentation"
.PP 
.SS "cache_entry_t* cache_inode_make_root (cache_inode_fsal_data_t * pfsdata, hash_table_t * ht, cache_inode_client_t * pclient, fsal_op_context_t * pcontext, cache_inode_status_t * pstatus)"
.PP
cache_inode_make_root: Inserts the root of a FS in the cache.
.PP
Inserts the root of a FS in the cache. This function will be called at junction traversal.
.PP
\fBParameters:\fP
.RS 4
\fIpfsdata\fP [IN] FSAL data for the root. 
.br
\fIht\fP [IN] hash table used for the cache, unused in this call. 
.br
\fIpclient\fP [INOUT] ressource allocated by the client for the nfs management. 
.br
\fIpcontext\fP [IN] FSAL credentials. Unused here. 
.br
\fIpstatus\fP [OUT] returned status. 
.RE
.PP

.PP
Definition at line 121 of file cache_inode_make_root.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Cache inode layer from the source code.
