.TH "test_cache_inode_readdir.c" 3 "9 Apr 2008" "Version 0.1" "Cache inode layer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_cache_inode_readdir.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'BuddyMalloc.h'\fP
.br
\fC#include 'fsal.h'\fP
.br
\fC#include 'cache_inode.h'\fP
.br
\fC#include 'LRU_List.h'\fP
.br
\fC#include 'log_functions.h'\fP
.br
\fC#include 'err_fsal.h'\fP
.br
\fC#include 'err_cache_inode.h'\fP
.br
\fC#include 'stuff_alloc.h'\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <strings.h>\fP
.br
\fC#include <sys/types.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBHPSS_SSM\fP   'hpss_ssm'"
.br
.ti -1c
.RI "#define \fBHPSS_KEYTAB\fP   '/krb5/hpssserver.keytab'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBlru_entry_to_str\fP (LRU_data_t data, char *str)"
.br
.ti -1c
.RI "int \fBlru_clean_entry\fP (LRU_entry_t *entry, void *adddata)"
.br
.ti -1c
.RI "\fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define HPSS_KEYTAB   '/krb5/hpssserver.keytab'"
.PP
Definition at line 105 of file test_cache_inode_readdir.c.
.SS "#define HPSS_SSM   'hpss_ssm'"
.PP
Definition at line 104 of file test_cache_inode_readdir.c.
.SH "Function Documentation"
.PP 
.SS "int lru_clean_entry (LRU_entry_t * entry, void * adddata)"
.PP
Definition at line 116 of file test_cache_inode_readdir.c.
.SS "int lru_entry_to_str (LRU_data_t data, char * str)"
.PP
Definition at line 107 of file test_cache_inode_readdir.c.
.SS "main (int argc, char * argv[])"
.PP
main: test main function.
.PP
test main function.
.PP
\fBParameters:\fP
.RS 4
\fIargc\fP [IN] number of command line arguments. 
.br
\fIargv\fP [IN] arguments set on the command line.
.RE
.PP
\fBReturns:\fP
.RS 4
an integer sent back to the calling shell. 
.RE
.PP

.PP
Definition at line 134 of file test_cache_inode_readdir.c.
.PP
References cache_inode_client_init(), cache_inode_init(), cache_inode_lookup(), cache_inode_make_root(), cache_inode_print_dir(), cache_inode_readdir(), HPSS_KEYTAB, and HPSS_SSM.
.SH "Author"
.PP 
Generated automatically by Doxygen for Cache inode layer from the source code.
