.TH "todo" 3 "15 Sep 2010" "Version 0.1" "Cache inode layer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
 
.IP "\fBMember \fBcache_inode_commit\fP \fP" 1c
: BUGAZEOMEU; gestion de la taille du fichier a prendre en compte.
.PP
.PP
.PP
 
.IP "\fBMember \fBcache_inode_rdwr\fP \fP" 1c
: BUGAZEOMEU; gestion de la taille du fichier a prendre en compte.
.PP
.PP
.PP
 
.IP "\fBMember \fBcache_inode_state_conflict\fP \fP" 1c
No conflict management on layout for now 
.PP
.PP
 
.IP "\fBMember \fBcache_inode_truncate_sw\fP \fP" 1c
&pentry->object.file.open_fd.fd, 
.PP

