.TH "todo" 3 "31 Mar 2009" "Version 0.1" "Cache inode layer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
 
.IP "\fBMember \fBcache_inode_rdwr\fP \fP" 1c
: BUGAZEOMEU; gestion de la taille du fichier a prendre en compte.
.PP
.PP
.PP
 
.IP "\fBMember \fBcache_inode_truncate_sw\fP \fP" 1c
&pentry->object.file.open_fd.fd, 
.PP

