.TH "cmd_nfstools.c" 3 "15 Sep 2010" "Version 0.1" "ganeshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmd_nfstools.c \- 
.PP
nfs conversion tools.  

.SH SYNOPSIS
.br
.PP
\fC#include <limits.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <sys/stat.h>\fP
.br
\fC#include 'cmd_nfstools.h'\fP
.br
\fC#include 'stuff_alloc.h'\fP
.br
\fC#include 'nfs23.h'\fP
.br
\fC#include 'nfs4.h'\fP
.br
\fC#include 'mount.h'\fP
.br
\fC#include 'nfs_proto_functions.h'\fP
.br
\fC#include 'nfs_tools.h'\fP
.br
\fC#include 'nfs_proto_tools.h'\fP
.br
\fC#include 'nfs_file_handle.h'\fP
.br
\fC#include 'cmd_tools.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBSIZE_STR_NFSHANDLE2\fP   (2 * NFS2_FHSIZE + 1)"
.br
.ti -1c
.RI "#define \fBSIZE_STR_NFSHANDLE3\fP   (2 * NFS3_FHSIZE + 1)"
.br
.ti -1c
.RI "#define \fBMNT_HANDLE\fP(p_mount_res3)   ( (p_mount_res3)->mountres3_u.mountinfo.fhandle )"
.br
.ti -1c
.RI "#define \fBAUTH_FLAVORS\fP(p_mount_res3)   ( (p_mount_res3)->mountres3_u.mountinfo.auth_flavors )"
.br
.ti -1c
.RI "#define \fBATTR2_ATTRIBUTES\fP(_p_attr2res)   ( (_p_attr2res)->ATTR2res_u.attributes )"
.br
.ti -1c
.RI "#define \fBDIROP2_HANDLE\fP(_p_dirop)   ( (_p_dirop)->DIROP2res_u.diropok.file )"
.br
.ti -1c
.RI "#define \fBDIROP2_ATTRIBUTES\fP(_p_dirop)   ( (_p_dirop)->DIROP2res_u.diropok.attributes )"
.br
.ti -1c
.RI "#define \fBREADLINKRES_PATH\fP(_p_rl2res)   ( (_p_rl2res)->READLINK2res_u.data )"
.br
.ti -1c
.RI "#define \fBGETATTR3_ATTRIBUTES\fP(_p_GETATTR3res)   ( (_p_GETATTR3res)->GETATTR3res_u.resok.obj_attributes )"
.br
.ti -1c
.RI "#define \fBLOOKUP3_OK_HANDLE\fP(_p_LOOKUP3res)   ( (_p_LOOKUP3res)->LOOKUP3res_u.resok.object )"
.br
.ti -1c
.RI "#define \fBLOOKUP3_OK_OBJATTR\fP(_p_LOOKUP3res)   ( (_p_LOOKUP3res)->LOOKUP3res_u.resok.obj_attributes )"
.br
.ti -1c
.RI "#define \fBLOOKUP3_OK_DIRATTR\fP(_p_LOOKUP3res)   ( (_p_LOOKUP3res)->LOOKUP3res_u.resok.dir_attributes )"
.br
.ti -1c
.RI "#define \fBLOOKUP3_FAIL_DIRATTR\fP(_p_LOOKUP3res)   ( (_p_LOOKUP3res)->LOOKUP3res_u.resfail.dir_attributes )"
.br
.ti -1c
.RI "#define \fBREADDIR3_OK\fP(_p_READDIR3res)   ( (_p_READDIR3res)->READDIR3res_u.resok )"
.br
.ti -1c
.RI "#define \fBREADDIR3_FAIL\fP(_p_READDIR3res)   ( (_p_READDIR3res)->READDIR3res_u.resfail )"
.br
.ti -1c
.RI "#define \fBREADDIRPLUS3_OK\fP(_p_READDIRPLUS3res)   ( (_p_READDIRPLUS3res)->READDIRPLUS3res_u.resok )"
.br
.ti -1c
.RI "#define \fBREADDIRPLUS3_FAIL\fP(_p_READDIRPLUS3res)   ( (_p_READDIRPLUS3res)->READDIRPLUS3res_u.resfail )"
.br
.ti -1c
.RI "#define \fBREADLINK3_OK_ATTRS\fP(_p_READLINK3res)   ( (_p_READLINK3res)->READLINK3res_u.resok.symlink_attributes )"
.br
.ti -1c
.RI "#define \fBREADLINK3_OK_DATA\fP(_p_READLINK3res)   ( (_p_READLINK3res)->READLINK3res_u.resok.data )"
.br
.ti -1c
.RI "#define \fBREADLINK3_FAIL_ATTRS\fP(_p_READLINK3res)   ( (_p_READLINK3res)->READLINK3res_u.resfail.symlink_attributes )"
.br
.ti -1c
.RI "#define \fBFSSTAT3_OK\fP(_p_FSSTAT3res)   ( (_p_FSSTAT3res)->FSSTAT3res_u.resok )"
.br
.ti -1c
.RI "#define \fBFSSTAT3_FAIL_ATTRS\fP(_p_FSSTAT3res)   ( (_p_FSSTAT3res)->FSSTAT3res_u.resfail.obj_attributes )"
.br
.ti -1c
.RI "#define \fBACCESS3_OK_ATTRS\fP(_p_ACCESS3res)   ( (_p_ACCESS3res)->ACCESS3res_u.resok.obj_attributes )"
.br
.ti -1c
.RI "#define \fBACCESS3_OK_ACCESS\fP(_p_ACCESS3res)   ( (_p_ACCESS3res)->ACCESS3res_u.resok.access )"
.br
.ti -1c
.RI "#define \fBACCESS3_FAIL_ATTRS\fP(_p_ACCESS3res)   ( (_p_ACCESS3res)->ACCESS3res_u.resfail.obj_attributes )"
.br
.ti -1c
.RI "#define \fBCREATE3_OK_FH\fP(_p_CREATE3res)   ( (_p_CREATE3res)->CREATE3res_u.resok.obj )"
.br
.ti -1c
.RI "#define \fBCREATE3_OK_ATTRS\fP(_p_CREATE3res)   ( (_p_CREATE3res)->CREATE3res_u.resok.obj_attributes )"
.br
.ti -1c
.RI "#define \fBCREATE3_OK_WCC\fP(_p_CREATE3res)   ( (_p_CREATE3res)->CREATE3res_u.resok.dir_wcc )"
.br
.ti -1c
.RI "#define \fBCREATE3_FAIL_WCC\fP(_p_CREATE3res)   ( (_p_CREATE3res)->CREATE3res_u.resfail.dir_wcc )"
.br
.ti -1c
.RI "#define \fBMKDIR3_OK_FH\fP(_p_MKDIR3res)   ( (_p_MKDIR3res)->MKDIR3res_u.resok.obj )"
.br
.ti -1c
.RI "#define \fBMKDIR3_OK_ATTRS\fP(_p_MKDIR3res)   ( (_p_MKDIR3res)->MKDIR3res_u.resok.obj_attributes )"
.br
.ti -1c
.RI "#define \fBMKDIR3_OK_WCC\fP(_p_MKDIR3res)   ( (_p_MKDIR3res)->MKDIR3res_u.resok.dir_wcc )"
.br
.ti -1c
.RI "#define \fBMKDIR3_FAIL_WCC\fP(_p_MKDIR3res)   ( (_p_MKDIR3res)->MKDIR3res_u.resfail.dir_wcc )"
.br
.ti -1c
.RI "#define \fBREMOVE3_OK_WCC\fP(_p_REMOVE3res)   ( (_p_REMOVE3res)->REMOVE3res_u.resok.dir_wcc )"
.br
.ti -1c
.RI "#define \fBREMOVE3_FAIL_WCC\fP(_p_REMOVE3res)   ( (_p_REMOVE3res)->REMOVE3res_u.resfail.dir_wcc )"
.br
.ti -1c
.RI "#define \fBRMDIR3_OK_WCC\fP(_p_RMDIR3res)   ( (_p_RMDIR3res)->RMDIR3res_u.resok.dir_wcc )"
.br
.ti -1c
.RI "#define \fBRMDIR3_FAIL_WCC\fP(_p_RMDIR3res)   ( (_p_RMDIR3res)->RMDIR3res_u.resfail.dir_wcc )"
.br
.ti -1c
.RI "#define \fBSETATTR3_OK_WCC\fP(_p_SETATTR3res)   ( (_p_SETATTR3res)->SETATTR3res_u.resok.obj_wcc )"
.br
.ti -1c
.RI "#define \fBSETATTR3_FAIL_WCC\fP(_p_SETATTR3res)   ( (_p_SETATTR3res)->SETATTR3res_u.resfail.obj_wcc )"
.br
.ti -1c
.RI "#define \fBRENAME3_OK_FROMWCC\fP(_p_RENAME3res)   ( (_p_RENAME3res)->RENAME3res_u.resok.fromdir_wcc )"
.br
.ti -1c
.RI "#define \fBRENAME3_OK_TOWCC\fP(_p_RENAME3res)   ( (_p_RENAME3res)->RENAME3res_u.resok.todir_wcc )"
.br
.ti -1c
.RI "#define \fBRENAME3_FAIL_FROMWCC\fP(_p_RENAME3res)   ( (_p_RENAME3res)->RENAME3res_u.resfail.fromdir_wcc )"
.br
.ti -1c
.RI "#define \fBRENAME3_FAIL_TOWCC\fP(_p_RENAME3res)   ( (_p_RENAME3res)->RENAME3res_u.resfail.todir_wcc )"
.br
.ti -1c
.RI "#define \fBLINK3_OK_ATTRS\fP(_p_LINK3res)   ( (_p_LINK3res)->LINK3res_u.resok.file_attributes )"
.br
.ti -1c
.RI "#define \fBLINK3_OK_WCC\fP(_p_LINK3res)   ( (_p_LINK3res)->LINK3res_u.resok.linkdir_wcc )"
.br
.ti -1c
.RI "#define \fBLINK3_FAIL_ATTRS\fP(_p_LINK3res)   ( (_p_LINK3res)->LINK3res_u.resfail.file_attributes )"
.br
.ti -1c
.RI "#define \fBLINK3_FAIL_WCC\fP(_p_LINK3res)   ( (_p_LINK3res)->LINK3res_u.resfail.linkdir_wcc )"
.br
.ti -1c
.RI "#define \fBSYMLINK3_OK_FH\fP(_p_SYMLINK3res)   ( (_p_SYMLINK3res)->SYMLINK3res_u.resok.obj )"
.br
.ti -1c
.RI "#define \fBSYMLINK3_OK_ATTRS\fP(_p_SYMLINK3res)   ( (_p_SYMLINK3res)->SYMLINK3res_u.resok.obj_attributes )"
.br
.ti -1c
.RI "#define \fBSYMLINK3_OK_WCC\fP(_p_SYMLINK3res)   ( (_p_SYMLINK3res)->SYMLINK3res_u.resok.dir_wcc )"
.br
.ti -1c
.RI "#define \fBSYMLINK3_FAIL_WCC\fP(_p_SYMLINK3res)   ( (_p_SYMLINK3res)->SYMLINK3res_u.resfail.dir_wcc )"
.br
.ti -1c
.RI "#define \fBFSINFO3_OK_ATTRS\fP(_p_FSINFO3res)   ( (_p_FSINFO3res)->FSINFO3res_u.resok.obj_attributes )"
.br
.ti -1c
.RI "#define \fBFSINFO3_OK_INFO\fP(_p_FSINFO3res)   ( (_p_FSINFO3res)->FSINFO3res_u.resok )"
.br
.ti -1c
.RI "#define \fBFSINFO3_FAIL_ATTRS\fP(_p_FSINFO3res)   ( (_p_FSINFO3res)->FSINFO3res_u.resfail.obj_attributes )"
.br
.ti -1c
.RI "#define \fBPATHCONF3_OK_ATTRS\fP(_p_PATHCONF3res)   ( (_p_PATHCONF3res)->PATHCONF3res_u.resok.obj_attributes )"
.br
.ti -1c
.RI "#define \fBPATHCONF3_OK_INFO\fP(_p_PATHCONF3res)   ( (_p_PATHCONF3res)->PATHCONF3res_u.resok )"
.br
.ti -1c
.RI "#define \fBPATHCONF3_FAIL_ATTRS\fP(_p_PATHCONF3res)   ( (_p_PATHCONF3res)->PATHCONF3res_u.resfail.obj_attributes )"
.br
.ti -1c
.RI "#define \fBprint_mask\fP(_out, _mode, _mask, _lettre)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBget_rpc_xid\fP ()"
.br
.ti -1c
.RI "int \fBcmdnfs_void\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_dirpath\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_fhandle2\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_fhstatus2\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_STATFS2res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_mountlist\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_exports\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_fhandle3\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_mountres3\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_nfsstat2\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_fattr2\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_ATTR2res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_DIROP2res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_diropargs2\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_READLINK2res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_sattr2\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_CREATE2args\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_SETATTR2args\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_READDIR2args\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_READDIR2res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_RENAME2args\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_nfsstat3\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_fattr3\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_sattr3\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_GETATTR3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_diropargs3\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_postopattr\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_postopfh3\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_LOOKUP3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_READDIR3args\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_READDIR3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_READDIRPLUS3args\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_READDIRPLUS3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_READLINK3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_FSSTAT3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_ACCESS3args\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_ACCESS3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_CREATE3args\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_preopattr\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_wccdata\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_CREATE3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_MKDIR3args\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_MKDIR3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_REMOVE3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_RMDIR3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_sattrguard3\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_SETATTR3args\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_SETATTR3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_RENAME3args\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_RENAME3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_LINK3args\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_LINK3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_SYMLINK3args\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_SYMLINK3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_FSINFO3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_PATHCONF3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "void \fBprint_nfsitem_line\fP (FILE *out, fattr3 *attrib, char *name, char *target)"
.br
.ti -1c
.RI "void \fBprint_nfs_attributes\fP (fattr3 *attrs, FILE *output)"
.br
.in -1c
.SH "Detailed Description"
.PP 
nfs conversion tools. 

\fBAuthor:\fP
.RS 4
.RE
.PP
\fBAuthor\fP.RS 4
leibovic 
.RE
.PP
\fBDate:\fP
.RS 4
.RE
.PP
\fBDate\fP.RS 4
2006/02/17 13:37:44 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision\fP.RS 4
1.24 
.RE
.PP
\fBLog\fP.RS 4
\fBcmd_nfstools.c\fP,v 
.RE
.PP
Revision 1.24 2006/02/17 13:37:44 leibovic Ghost FS is back !
.PP
Revision 1.23 2006/01/31 12:25:42 leibovic Fixing a minor display bug.
.PP
Revision 1.22 2006/01/18 08:02:04 deniel Order in includes and libraries
.PP
Revision 1.21 2006/01/18 07:29:11 leibovic Fixing bugs about exportlists.
.PP
Revision 1.19 2005/10/12 11:30:10 leibovic NFSv2.
.PP
Revision 1.18 2005/10/07 08:30:43 leibovic nfs2_rename + New FSAL init functions.
.PP
Revision 1.17 2005/09/30 14:30:43 leibovic Adding nfs2_readdir commqnd.
.PP
Revision 1.16 2005/09/30 06:56:55 leibovic Adding nfs2_setattr command.
.PP
Revision 1.15 2005/09/30 06:46:00 leibovic New create2 and mkdir2 args format.
.PP
Revision 1.14 2005/09/28 09:08:00 leibovic thread-safe version of localtime.
.PP
Revision 1.13 2005/08/30 13:22:26 leibovic Addind nfs3_fsinfo et nfs3_pathconf functions.
.PP
Revision 1.12 2005/08/10 14:55:05 leibovic NFS support of setattr, rename, link, symlink.
.PP
Revision 1.11 2005/08/10 10:57:17 leibovic Adding removal functions.
.PP
Revision 1.10 2005/08/09 14:52:57 leibovic Addinf create and mkdir commands.
.PP
Revision 1.9 2005/08/08 11:42:49 leibovic Adding some stardard unix calls through NFS (ls, cd, pwd).
.PP
Revision 1.8 2005/08/05 15:17:56 leibovic Adding mount and pwd commands for browsing.
.PP
Revision 1.7 2005/08/05 10:42:38 leibovic Adding readdirplus.
.PP
Revision 1.6 2005/08/05 08:59:32 leibovic Adding explicit strings for type and NFS status.
.PP
Revision 1.5 2005/08/05 07:59:07 leibovic some nfs3 commands added.
.PP
Revision 1.4 2005/08/04 06:57:41 leibovic some NFSv2 commands are completed.
.PP
Revision 1.3 2005/08/03 12:51:16 leibovic MNT3 protocol OK.
.PP
Revision 1.2 2005/08/03 11:51:09 leibovic MNT1 protocol OK.
.PP
Revision 1.1 2005/08/03 08:16:23 leibovic Adding nfs layer structures. 
.PP
Definition in file \fBcmd_nfstools.c\fP.
.SH "Define Documentation"
.PP 
.SS "#define ACCESS3_FAIL_ATTRS(_p_ACCESS3res)   ( (_p_ACCESS3res)->ACCESS3res_u.resfail.obj_attributes )"
.PP
Definition at line 2782 of file cmd_nfstools.c.
.SS "#define ACCESS3_OK_ACCESS(_p_ACCESS3res)   ( (_p_ACCESS3res)->ACCESS3res_u.resok.access )"
.PP
Definition at line 2781 of file cmd_nfstools.c.
.SS "#define ACCESS3_OK_ATTRS(_p_ACCESS3res)   ( (_p_ACCESS3res)->ACCESS3res_u.resok.obj_attributes )"
.PP
Definition at line 2780 of file cmd_nfstools.c.
.SS "#define ATTR2_ATTRIBUTES(_p_attr2res)   ( (_p_attr2res)->ATTR2res_u.attributes )"
.PP
Definition at line 755 of file cmd_nfstools.c.
.SS "#define AUTH_FLAVORS(p_mount_res3)   ( (p_mount_res3)->mountres3_u.mountinfo.auth_flavors )"
.PP
Definition at line 588 of file cmd_nfstools.c.
.SS "#define CREATE3_FAIL_WCC(_p_CREATE3res)   ( (_p_CREATE3res)->CREATE3res_u.resfail.dir_wcc )"
.PP
Definition at line 3052 of file cmd_nfstools.c.
.SS "#define CREATE3_OK_ATTRS(_p_CREATE3res)   ( (_p_CREATE3res)->CREATE3res_u.resok.obj_attributes )"
.PP
Definition at line 3050 of file cmd_nfstools.c.
.SS "#define CREATE3_OK_FH(_p_CREATE3res)   ( (_p_CREATE3res)->CREATE3res_u.resok.obj )"
.PP
Definition at line 3049 of file cmd_nfstools.c.
.SS "#define CREATE3_OK_WCC(_p_CREATE3res)   ( (_p_CREATE3res)->CREATE3res_u.resok.dir_wcc )"
.PP
Definition at line 3051 of file cmd_nfstools.c.
.SS "#define DIROP2_ATTRIBUTES(_p_dirop)   ( (_p_dirop)->DIROP2res_u.diropok.attributes )"
.PP
Definition at line 809 of file cmd_nfstools.c.
.SS "#define DIROP2_HANDLE(_p_dirop)   ( (_p_dirop)->DIROP2res_u.diropok.file )"
.PP
Definition at line 808 of file cmd_nfstools.c.
.SS "#define FSINFO3_FAIL_ATTRS(_p_FSINFO3res)   ( (_p_FSINFO3res)->FSINFO3res_u.resfail.obj_attributes )"
.PP
Definition at line 4032 of file cmd_nfstools.c.
.SS "#define FSINFO3_OK_ATTRS(_p_FSINFO3res)   ( (_p_FSINFO3res)->FSINFO3res_u.resok.obj_attributes )"
.PP
Definition at line 4030 of file cmd_nfstools.c.
.SS "#define FSINFO3_OK_INFO(_p_FSINFO3res)   ( (_p_FSINFO3res)->FSINFO3res_u.resok )"
.PP
Definition at line 4031 of file cmd_nfstools.c.
.SS "#define FSSTAT3_FAIL_ATTRS(_p_FSSTAT3res)   ( (_p_FSSTAT3res)->FSSTAT3res_u.resfail.obj_attributes )"
.PP
Definition at line 2632 of file cmd_nfstools.c.
.SS "#define FSSTAT3_OK(_p_FSSTAT3res)   ( (_p_FSSTAT3res)->FSSTAT3res_u.resok )"
.PP
Definition at line 2631 of file cmd_nfstools.c.
.SS "#define GETATTR3_ATTRIBUTES(_p_GETATTR3res)   ( (_p_GETATTR3res)->GETATTR3res_u.resok.obj_attributes )"
.PP
Definition at line 1781 of file cmd_nfstools.c.
.SS "#define LINK3_FAIL_ATTRS(_p_LINK3res)   ( (_p_LINK3res)->LINK3res_u.resfail.file_attributes )"
.PP
Definition at line 3787 of file cmd_nfstools.c.
.SS "#define LINK3_FAIL_WCC(_p_LINK3res)   ( (_p_LINK3res)->LINK3res_u.resfail.linkdir_wcc )"
.PP
Definition at line 3788 of file cmd_nfstools.c.
.SS "#define LINK3_OK_ATTRS(_p_LINK3res)   ( (_p_LINK3res)->LINK3res_u.resok.file_attributes )"
.PP
Definition at line 3785 of file cmd_nfstools.c.
.SS "#define LINK3_OK_WCC(_p_LINK3res)   ( (_p_LINK3res)->LINK3res_u.resok.linkdir_wcc )"
.PP
Definition at line 3786 of file cmd_nfstools.c.
.SS "#define LOOKUP3_FAIL_DIRATTR(_p_LOOKUP3res)   ( (_p_LOOKUP3res)->LOOKUP3res_u.resfail.dir_attributes )"
.PP
Definition at line 1950 of file cmd_nfstools.c.
.SS "#define LOOKUP3_OK_DIRATTR(_p_LOOKUP3res)   ( (_p_LOOKUP3res)->LOOKUP3res_u.resok.dir_attributes )"
.PP
Definition at line 1949 of file cmd_nfstools.c.
.SS "#define LOOKUP3_OK_HANDLE(_p_LOOKUP3res)   ( (_p_LOOKUP3res)->LOOKUP3res_u.resok.object )"
.PP
Definition at line 1947 of file cmd_nfstools.c.
.SS "#define LOOKUP3_OK_OBJATTR(_p_LOOKUP3res)   ( (_p_LOOKUP3res)->LOOKUP3res_u.resok.obj_attributes )"
.PP
Definition at line 1948 of file cmd_nfstools.c.
.SS "#define MKDIR3_FAIL_WCC(_p_MKDIR3res)   ( (_p_MKDIR3res)->MKDIR3res_u.resfail.dir_wcc )"
.PP
Definition at line 3197 of file cmd_nfstools.c.
.SS "#define MKDIR3_OK_ATTRS(_p_MKDIR3res)   ( (_p_MKDIR3res)->MKDIR3res_u.resok.obj_attributes )"
.PP
Definition at line 3195 of file cmd_nfstools.c.
.SS "#define MKDIR3_OK_FH(_p_MKDIR3res)   ( (_p_MKDIR3res)->MKDIR3res_u.resok.obj )"
.PP
Definition at line 3194 of file cmd_nfstools.c.
.SS "#define MKDIR3_OK_WCC(_p_MKDIR3res)   ( (_p_MKDIR3res)->MKDIR3res_u.resok.dir_wcc )"
.PP
Definition at line 3196 of file cmd_nfstools.c.
.SS "#define MNT_HANDLE(p_mount_res3)   ( (p_mount_res3)->mountres3_u.mountinfo.fhandle )"
.PP
Definition at line 587 of file cmd_nfstools.c.
.SS "#define PATHCONF3_FAIL_ATTRS(_p_PATHCONF3res)   ( (_p_PATHCONF3res)->PATHCONF3res_u.resfail.obj_attributes )"
.PP
Definition at line 4135 of file cmd_nfstools.c.
.SS "#define PATHCONF3_OK_ATTRS(_p_PATHCONF3res)   ( (_p_PATHCONF3res)->PATHCONF3res_u.resok.obj_attributes )"
.PP
Definition at line 4133 of file cmd_nfstools.c.
.SS "#define PATHCONF3_OK_INFO(_p_PATHCONF3res)   ( (_p_PATHCONF3res)->PATHCONF3res_u.resok )"
.PP
Definition at line 4134 of file cmd_nfstools.c.
.SS "#define print_mask(_out, _mode, _mask, _lettre)"\fBValue:\fP
.PP
.nf
do {    \
        if (_mode & _mask) fprintf(_out,_lettre);    \
        else fprintf(_out,'-');                      \
      } while(0)
.fi
print_nfsitem_line: Prints a nfs element on one line, like the Unix ls command.
.PP
\fBParameters:\fP
.RS 4
\fIout\fP (in FILE*) The file where the item is to be printed. 
.br
\fIattrib\fP (fattr3 *) the NFS attributes for the item. 
.br
\fIname\fP (in char *) The name of the item to be printed. 
.br
\fItarget\fP (in char *) It the item is a symbolic link, this contains the link target. 
.RE
.PP
\fBReturns:\fP
.RS 4
Nothing. 
.RE
.PP

.PP
Definition at line 4228 of file cmd_nfstools.c.
.SS "#define READDIR3_FAIL(_p_READDIR3res)   ( (_p_READDIR3res)->READDIR3res_u.resfail )"
.PP
Definition at line 2234 of file cmd_nfstools.c.
.SS "#define READDIR3_OK(_p_READDIR3res)   ( (_p_READDIR3res)->READDIR3res_u.resok )"
.PP
Definition at line 2233 of file cmd_nfstools.c.
.SS "#define READDIRPLUS3_FAIL(_p_READDIRPLUS3res)   ( (_p_READDIRPLUS3res)->READDIRPLUS3res_u.resfail )"
.PP
Definition at line 2485 of file cmd_nfstools.c.
.SS "#define READDIRPLUS3_OK(_p_READDIRPLUS3res)   ( (_p_READDIRPLUS3res)->READDIRPLUS3res_u.resok )"
.PP
Definition at line 2484 of file cmd_nfstools.c.
.SS "#define READLINK3_FAIL_ATTRS(_p_READLINK3res)   ( (_p_READLINK3res)->READLINK3res_u.resfail.symlink_attributes )"
.PP
Definition at line 2564 of file cmd_nfstools.c.
.SS "#define READLINK3_OK_ATTRS(_p_READLINK3res)   ( (_p_READLINK3res)->READLINK3res_u.resok.symlink_attributes )"
.PP
Definition at line 2562 of file cmd_nfstools.c.
.SS "#define READLINK3_OK_DATA(_p_READLINK3res)   ( (_p_READLINK3res)->READLINK3res_u.resok.data )"
.PP
Definition at line 2563 of file cmd_nfstools.c.
.SS "#define READLINKRES_PATH(_p_rl2res)   ( (_p_rl2res)->READLINK2res_u.data )"
.PP
Definition at line 912 of file cmd_nfstools.c.
.SS "#define REMOVE3_FAIL_WCC(_p_REMOVE3res)   ( (_p_REMOVE3res)->REMOVE3res_u.resfail.dir_wcc )"
.PP
Definition at line 3279 of file cmd_nfstools.c.
.SS "#define REMOVE3_OK_WCC(_p_REMOVE3res)   ( (_p_REMOVE3res)->REMOVE3res_u.resok.dir_wcc )"
.PP
Definition at line 3278 of file cmd_nfstools.c.
.SS "#define RENAME3_FAIL_FROMWCC(_p_RENAME3res)   ( (_p_RENAME3res)->RENAME3res_u.resfail.fromdir_wcc )"
.PP
Definition at line 3658 of file cmd_nfstools.c.
.SS "#define RENAME3_FAIL_TOWCC(_p_RENAME3res)   ( (_p_RENAME3res)->RENAME3res_u.resfail.todir_wcc )"
.PP
Definition at line 3659 of file cmd_nfstools.c.
.SS "#define RENAME3_OK_FROMWCC(_p_RENAME3res)   ( (_p_RENAME3res)->RENAME3res_u.resok.fromdir_wcc )"
.PP
Definition at line 3656 of file cmd_nfstools.c.
.SS "#define RENAME3_OK_TOWCC(_p_RENAME3res)   ( (_p_RENAME3res)->RENAME3res_u.resok.todir_wcc )"
.PP
Definition at line 3657 of file cmd_nfstools.c.
.SS "#define RMDIR3_FAIL_WCC(_p_RMDIR3res)   ( (_p_RMDIR3res)->RMDIR3res_u.resfail.dir_wcc )"
.PP
Definition at line 3346 of file cmd_nfstools.c.
.SS "#define RMDIR3_OK_WCC(_p_RMDIR3res)   ( (_p_RMDIR3res)->RMDIR3res_u.resok.dir_wcc )"
.PP
Definition at line 3345 of file cmd_nfstools.c.
.SS "#define SETATTR3_FAIL_WCC(_p_SETATTR3res)   ( (_p_SETATTR3res)->SETATTR3res_u.resfail.obj_wcc )"
.PP
Definition at line 3544 of file cmd_nfstools.c.
.SS "#define SETATTR3_OK_WCC(_p_SETATTR3res)   ( (_p_SETATTR3res)->SETATTR3res_u.resok.obj_wcc )"
.PP
Definition at line 3543 of file cmd_nfstools.c.
.SS "#define SIZE_STR_NFSHANDLE2   (2 * NFS2_FHSIZE + 1)"
.PP
Definition at line 132 of file cmd_nfstools.c.
.SS "#define SIZE_STR_NFSHANDLE3   (2 * NFS3_FHSIZE + 1)"
.PP
Definition at line 133 of file cmd_nfstools.c.
.SS "#define SYMLINK3_FAIL_WCC(_p_SYMLINK3res)   ( (_p_SYMLINK3res)->SYMLINK3res_u.resfail.dir_wcc )"
.PP
Definition at line 3949 of file cmd_nfstools.c.
.SS "#define SYMLINK3_OK_ATTRS(_p_SYMLINK3res)   ( (_p_SYMLINK3res)->SYMLINK3res_u.resok.obj_attributes )"
.PP
Definition at line 3947 of file cmd_nfstools.c.
.SS "#define SYMLINK3_OK_FH(_p_SYMLINK3res)   ( (_p_SYMLINK3res)->SYMLINK3res_u.resok.obj )"
.PP
Definition at line 3946 of file cmd_nfstools.c.
.SS "#define SYMLINK3_OK_WCC(_p_SYMLINK3res)   ( (_p_SYMLINK3res)->SYMLINK3res_u.resok.dir_wcc )"
.PP
Definition at line 3948 of file cmd_nfstools.c.
.SH "Function Documentation"
.PP 
.SS "int cmdnfs_ACCESS3args (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 2711 of file cmd_nfstools.c.
.SS "int cmdnfs_ACCESS3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 2784 of file cmd_nfstools.c.
.SS "int cmdnfs_ATTR2res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 757 of file cmd_nfstools.c.
.SS "int cmdnfs_CREATE2args (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 1171 of file cmd_nfstools.c.
.SS "int cmdnfs_CREATE3args (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 2863 of file cmd_nfstools.c.
.SS "int cmdnfs_CREATE3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 3054 of file cmd_nfstools.c.
.SS "int cmdnfs_DIROP2res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 811 of file cmd_nfstools.c.
.SS "int cmdnfs_diropargs2 (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 868 of file cmd_nfstools.c.
.SS "int cmdnfs_diropargs3 (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 1834 of file cmd_nfstools.c.
.SS "int cmdnfs_dirpath (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 153 of file cmd_nfstools.c.
.SS "int cmdnfs_exports (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 447 of file cmd_nfstools.c.
.SS "int cmdnfs_fattr2 (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
\fBTodo\fP
.RS 4
.RE
.PP
.PP
\fBTodo\fP
.RS 4
.RE
.PP

.PP
Definition at line 681 of file cmd_nfstools.c.
.SS "int cmdnfs_fattr3 (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
\fBTodo\fP
.RS 4
.RE
.PP
.PP
\fBTodo\fP
.RS 4
.RE
.PP

.PP
Definition at line 1497 of file cmd_nfstools.c.
.SS "int cmdnfs_fhandle2 (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 203 of file cmd_nfstools.c.
.SS "int cmdnfs_fhandle3 (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 509 of file cmd_nfstools.c.
.SS "int cmdnfs_fhstatus2 (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 269 of file cmd_nfstools.c.
.SS "int cmdnfs_FSINFO3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 4034 of file cmd_nfstools.c.
.SS "int cmdnfs_FSSTAT3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 2634 of file cmd_nfstools.c.
.SS "int cmdnfs_GETATTR3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 1783 of file cmd_nfstools.c.
.SS "int cmdnfs_LINK3args (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 3739 of file cmd_nfstools.c.
.SS "int cmdnfs_LINK3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 3790 of file cmd_nfstools.c.
.SS "int cmdnfs_LOOKUP3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 1952 of file cmd_nfstools.c.
.SS "int cmdnfs_MKDIR3args (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 3133 of file cmd_nfstools.c.
.SS "int cmdnfs_MKDIR3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 3199 of file cmd_nfstools.c.
.SS "int cmdnfs_mountlist (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 393 of file cmd_nfstools.c.
.SS "int cmdnfs_mountres3 (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
\fBTodo\fP
.RS 4
Convert status to error code 
.RE
.PP

.PP
Definition at line 590 of file cmd_nfstools.c.
.SS "int cmdnfs_nfsstat2 (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 652 of file cmd_nfstools.c.
.SS "int cmdnfs_nfsstat3 (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 1468 of file cmd_nfstools.c.
.SS "int cmdnfs_PATHCONF3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 4137 of file cmd_nfstools.c.
.SS "int cmdnfs_postopattr (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 1875 of file cmd_nfstools.c.
.SS "int cmdnfs_postopfh3 (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 1911 of file cmd_nfstools.c.
.SS "int cmdnfs_preopattr (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 2960 of file cmd_nfstools.c.
.SS "int cmdnfs_READDIR2args (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 1261 of file cmd_nfstools.c.
.SS "int cmdnfs_READDIR2res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 1365 of file cmd_nfstools.c.
.SS "int cmdnfs_READDIR3args (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 2146 of file cmd_nfstools.c.
.SS "int cmdnfs_READDIR3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 2236 of file cmd_nfstools.c.
.SS "int cmdnfs_READDIRPLUS3args (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 2311 of file cmd_nfstools.c.
.SS "int cmdnfs_READDIRPLUS3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 2487 of file cmd_nfstools.c.
.SS "int cmdnfs_READLINK2res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 914 of file cmd_nfstools.c.
.SS "int cmdnfs_READLINK3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 2566 of file cmd_nfstools.c.
.SS "int cmdnfs_REMOVE3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 3281 of file cmd_nfstools.c.
.SS "int cmdnfs_RENAME2args (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 1422 of file cmd_nfstools.c.
.SS "int cmdnfs_RENAME3args (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 3610 of file cmd_nfstools.c.
.SS "int cmdnfs_RENAME3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 3661 of file cmd_nfstools.c.
.SS "int cmdnfs_RMDIR3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 3348 of file cmd_nfstools.c.
.SS "int cmdnfs_sattr2 (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 962 of file cmd_nfstools.c.
.SS "int cmdnfs_sattr3 (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 1572 of file cmd_nfstools.c.
.SS "int cmdnfs_sattrguard3 (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 3412 of file cmd_nfstools.c.
.SS "int cmdnfs_SETATTR2args (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 1215 of file cmd_nfstools.c.
.SS "int cmdnfs_SETATTR3args (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 3486 of file cmd_nfstools.c.
.SS "int cmdnfs_SETATTR3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 3546 of file cmd_nfstools.c.
.SS "int cmdnfs_STATFS2res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 325 of file cmd_nfstools.c.
.SS "int cmdnfs_SYMLINK3args (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 3870 of file cmd_nfstools.c.
.SS "int cmdnfs_SYMLINK3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 3951 of file cmd_nfstools.c.
.SS "int cmdnfs_void (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 143 of file cmd_nfstools.c.
.SS "int cmdnfs_wccdata (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 3013 of file cmd_nfstools.c.
.SS "int get_rpc_xid ()"
.PP
Definition at line 136 of file cmd_nfstools.c.
.SS "void print_nfs_attributes (fattr3 * attrs, FILE * output)"print_nfs_attributes: print an fattr3 to a given output file.
.PP
\fBParameters:\fP
.RS 4
\fIattrs\fP (in fattr3) The attributes to be printed. 
.br
\fIoutput\fP (in FILE *) The file where the attributes are to be printed. 
.RE
.PP
\fBReturns:\fP
.RS 4
Nothing. 
.RE
.PP

.PP
Definition at line 4336 of file cmd_nfstools.c.
.SS "void print_nfsitem_line (FILE * out, fattr3 * attrib, char * name, char * target)"print_nfsitem_line: Prints a nfs element on one line, like the Unix ls command.
.PP
\fBParameters:\fP
.RS 4
\fIout\fP (in FILE*) The file where the item is to be printed. 
.br
\fIattrib\fP (fattr3 *) the NFS attributes for the item. 
.br
\fIname\fP (in char *) The name of the item to be printed. 
.br
\fItarget\fP (in char *) It the item is a symbolic link, this contains the link target. 
.RE
.PP
\fBReturns:\fP
.RS 4
Nothing. 
.RE
.PP

.PP
Definition at line 4233 of file cmd_nfstools.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for ganeshell from the source code.
