.TH "cmd_nfstools.h" 3 "15 Sep 2010" "Version 0.1" "ganeshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmd_nfstools.h \- 
.PP
nfs tools for ganeshell.  

.SH SYNOPSIS
.br
.PP
\fC#include <rpc/rpc.h>\fP
.br
\fC#include <rpc/auth.h>\fP
.br
\fC#include 'nfs_proto_functions.h'\fP
.br
\fC#include 'nfs_remote_functions.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBcmdnfs_funcdesc__\fP"
.br
.ti -1c
.RI "struct \fBcmdnfsremote_funcdesc__\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fBcmdnfs_encodetype__\fP \fBcmdnfs_encodetype_t\fP"
.br
.ti -1c
.RI "typedef int(* \fBcmdnfs_encoding_func_t\fP )(\fBcmdnfs_encodetype_t\fP, int, char **, int, FILE *, caddr_t)"
.br
.ti -1c
.RI "typedef struct \fBcmdnfs_funcdesc__\fP \fBcmdnfs_funcdesc_t\fP"
.br
.ti -1c
.RI "typedef struct \fBcmdnfsremote_funcdesc__\fP \fBcmdnfsremote_funcdesc_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBcmdnfs_encodetype__\fP { \fBCMDNFS_ENCODE\fP =  1, \fBCMDNFS_DECODE\fP =  2, \fBCMDNFS_FREE\fP =  3 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcmdnfs_void\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_dirpath\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_fhstatus2\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_fhandle2\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_mountlist\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_exports\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_mountres3\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_fhandle3\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_fattr2\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_ATTR2res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_DIROP2res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_diropargs2\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_nfsstat2\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_READLINK2res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_sattr2\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_CREATE2args\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_SETATTR2args\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_READDIR2args\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_READDIR2res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_nfsstat3\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_fattr3\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_sattr3\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_GETATTR3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_postopattr\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_postopfh3\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_diropargs3\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_LOOKUP3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_READDIR3args\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_READDIR3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_READDIRPLUS3args\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_READDIRPLUS3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_READLINK3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_FSSTAT3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_ACCESS3args\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_ACCESS3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_CREATE3args\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_CREATE3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_MKDIR3args\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_MKDIR3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_REMOVE3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_RMDIR3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_SETATTR3args\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_SETATTR3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_RENAME3args\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_RENAME3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_LINK3args\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_LINK3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_SYMLINK3args\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_SYMLINK3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_FSINFO3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_PATHCONF3res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_RENAME2args\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "int \fBcmdnfs_STATFS2res\fP (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)"
.br
.ti -1c
.RI "void \fBprint_nfsitem_line\fP (FILE *out, fattr3 *attrib, char *name, char *target)"
.br
.ti -1c
.RI "void \fBprint_nfs_attributes\fP (fattr3 *attrs, FILE *output)"
.br
.in -1c
.SH "Detailed Description"
.PP 
nfs tools for ganeshell. 

\fBAuthor:\fP
.RS 4
.RE
.PP
\fBAuthor\fP.RS 4
leibovic 
.RE
.PP
\fBDate:\fP
.RS 4
.RE
.PP
\fBDate\fP.RS 4
2006/01/18 17:03:35 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision\fP.RS 4
1.22 
.RE
.PP
\fBLog\fP.RS 4
\fBcmd_nfstools.h\fP,v 
.RE
.PP
Revision 1.22 2006/01/18 17:03:35 leibovic Removing some warnings.
.PP
Revision 1.21 2006/01/18 08:02:04 deniel Order in includes and libraries
.PP
Revision 1.20 2006/01/18 07:29:11 leibovic Fixing bugs about exportlists.
.PP
Revision 1.19 2005/10/12 11:30:10 leibovic NFSv2.
.PP
Revision 1.18 2005/10/10 12:39:08 leibovic Using mnt/nfs free functions.
.PP
Revision 1.17 2005/10/07 08:30:43 leibovic nfs2_rename + New FSAL init functions.
.PP
Revision 1.16 2005/09/30 14:30:43 leibovic Adding nfs2_readdir commqnd.
.PP
Revision 1.15 2005/09/30 06:56:55 leibovic Adding nfs2_setattr command.
.PP
Revision 1.14 2005/09/30 06:46:00 leibovic New create2 and mkdir2 args format.
.PP
Revision 1.13 2005/09/07 14:08:22 leibovic Adding NFS3_pathconf command.
.PP
Revision 1.12 2005/08/30 13:22:26 leibovic Addind nfs3_fsinfo et nfs3_pathconf functions.
.PP
Revision 1.11 2005/08/10 14:55:05 leibovic NFS support of setattr, rename, link, symlink.
.PP
Revision 1.10 2005/08/10 10:57:17 leibovic Adding removal functions.
.PP
Revision 1.9 2005/08/09 14:52:57 leibovic Addinf create and mkdir commands.
.PP
Revision 1.8 2005/08/08 11:42:49 leibovic Adding some stardard unix calls through NFS (ls, cd, pwd).
.PP
Revision 1.7 2005/08/05 15:17:56 leibovic Adding mount and pwd commands for browsing.
.PP
Revision 1.6 2005/08/05 10:42:38 leibovic Adding readdirplus.
.PP
Revision 1.5 2005/08/05 07:59:07 leibovic some nfs3 commands added.
.PP
Revision 1.4 2005/08/04 06:57:41 leibovic some NFSv2 commands are completed.
.PP
Revision 1.3 2005/08/03 12:51:16 leibovic MNT3 protocol OK.
.PP
Revision 1.2 2005/08/03 11:51:10 leibovic MNT1 protocol OK.
.PP
Revision 1.1 2005/08/03 08:16:23 leibovic Adding nfs layer structures. 
.PP
Definition in file \fBcmd_nfstools.h\fP.
.SH "Typedef Documentation"
.PP 
.SS "typedef enum \fBcmdnfs_encodetype__\fP  \fBcmdnfs_encodetype_t\fP"
.SS "typedef int(* \fBcmdnfs_encoding_func_t\fP)(\fBcmdnfs_encodetype_t\fP,int, char **,int, FILE *,caddr_t)"
.PP
Definition at line 102 of file cmd_nfstools.h.
.SS "typedef struct \fBcmdnfs_funcdesc__\fP  \fBcmdnfs_funcdesc_t\fP"
.SS "typedef struct \fBcmdnfsremote_funcdesc__\fP  \fBcmdnfsremote_funcdesc_t\fP"
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBcmdnfs_encodetype__\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fICMDNFS_ENCODE \fP\fP
.TP
\fB\fICMDNFS_DECODE \fP\fP
.TP
\fB\fICMDNFS_FREE \fP\fP

.PP
Definition at line 93 of file cmd_nfstools.h.
.SH "Function Documentation"
.PP 
.SS "int cmdnfs_ACCESS3args (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 2711 of file cmd_nfstools.c.
.SS "int cmdnfs_ACCESS3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 2784 of file cmd_nfstools.c.
.SS "int cmdnfs_ATTR2res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 757 of file cmd_nfstools.c.
.SS "int cmdnfs_CREATE2args (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 1171 of file cmd_nfstools.c.
.SS "int cmdnfs_CREATE3args (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 2863 of file cmd_nfstools.c.
.SS "int cmdnfs_CREATE3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 3054 of file cmd_nfstools.c.
.SS "int cmdnfs_DIROP2res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 811 of file cmd_nfstools.c.
.SS "int cmdnfs_diropargs2 (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 868 of file cmd_nfstools.c.
.SS "int cmdnfs_diropargs3 (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 1834 of file cmd_nfstools.c.
.SS "int cmdnfs_dirpath (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 153 of file cmd_nfstools.c.
.SS "int cmdnfs_exports (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 447 of file cmd_nfstools.c.
.SS "int cmdnfs_fattr2 (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
\fBTodo\fP
.RS 4
.RE
.PP
.PP
\fBTodo\fP
.RS 4
.RE
.PP

.PP
Definition at line 681 of file cmd_nfstools.c.
.SS "int cmdnfs_fattr3 (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
\fBTodo\fP
.RS 4
.RE
.PP
.PP
\fBTodo\fP
.RS 4
.RE
.PP

.PP
Definition at line 1497 of file cmd_nfstools.c.
.SS "int cmdnfs_fhandle2 (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 203 of file cmd_nfstools.c.
.SS "int cmdnfs_fhandle3 (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 509 of file cmd_nfstools.c.
.SS "int cmdnfs_fhstatus2 (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 269 of file cmd_nfstools.c.
.SS "int cmdnfs_FSINFO3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 4034 of file cmd_nfstools.c.
.SS "int cmdnfs_FSSTAT3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 2634 of file cmd_nfstools.c.
.SS "int cmdnfs_GETATTR3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 1783 of file cmd_nfstools.c.
.SS "int cmdnfs_LINK3args (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 3739 of file cmd_nfstools.c.
.SS "int cmdnfs_LINK3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 3790 of file cmd_nfstools.c.
.SS "int cmdnfs_LOOKUP3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 1952 of file cmd_nfstools.c.
.SS "int cmdnfs_MKDIR3args (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 3133 of file cmd_nfstools.c.
.SS "int cmdnfs_MKDIR3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 3199 of file cmd_nfstools.c.
.SS "int cmdnfs_mountlist (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 393 of file cmd_nfstools.c.
.SS "int cmdnfs_mountres3 (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
\fBTodo\fP
.RS 4
Convert status to error code 
.RE
.PP

.PP
Definition at line 590 of file cmd_nfstools.c.
.SS "int cmdnfs_nfsstat2 (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 652 of file cmd_nfstools.c.
.SS "int cmdnfs_nfsstat3 (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 1468 of file cmd_nfstools.c.
.SS "int cmdnfs_PATHCONF3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 4137 of file cmd_nfstools.c.
.SS "int cmdnfs_postopattr (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 1875 of file cmd_nfstools.c.
.SS "int cmdnfs_postopfh3 (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 1911 of file cmd_nfstools.c.
.SS "int cmdnfs_READDIR2args (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 1261 of file cmd_nfstools.c.
.SS "int cmdnfs_READDIR2res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 1365 of file cmd_nfstools.c.
.SS "int cmdnfs_READDIR3args (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 2146 of file cmd_nfstools.c.
.SS "int cmdnfs_READDIR3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 2236 of file cmd_nfstools.c.
.SS "int cmdnfs_READDIRPLUS3args (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 2311 of file cmd_nfstools.c.
.SS "int cmdnfs_READDIRPLUS3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 2487 of file cmd_nfstools.c.
.SS "int cmdnfs_READLINK2res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 914 of file cmd_nfstools.c.
.SS "int cmdnfs_READLINK3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 2566 of file cmd_nfstools.c.
.SS "int cmdnfs_REMOVE3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 3281 of file cmd_nfstools.c.
.SS "int cmdnfs_RENAME2args (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 1422 of file cmd_nfstools.c.
.SS "int cmdnfs_RENAME3args (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 3610 of file cmd_nfstools.c.
.SS "int cmdnfs_RENAME3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 3661 of file cmd_nfstools.c.
.SS "int cmdnfs_RMDIR3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 3348 of file cmd_nfstools.c.
.SS "int cmdnfs_sattr2 (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 962 of file cmd_nfstools.c.
.SS "int cmdnfs_sattr3 (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 1572 of file cmd_nfstools.c.
.SS "int cmdnfs_SETATTR2args (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 1215 of file cmd_nfstools.c.
.SS "int cmdnfs_SETATTR3args (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 3486 of file cmd_nfstools.c.
.SS "int cmdnfs_SETATTR3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 3546 of file cmd_nfstools.c.
.SS "int cmdnfs_STATFS2res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 325 of file cmd_nfstools.c.
.SS "int cmdnfs_SYMLINK3args (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 3870 of file cmd_nfstools.c.
.SS "int cmdnfs_SYMLINK3res (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 3951 of file cmd_nfstools.c.
.SS "int cmdnfs_void (\fBcmdnfs_encodetype_t\fP encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)"
.PP
Definition at line 143 of file cmd_nfstools.c.
.SS "void print_nfs_attributes (fattr3 * attrs, FILE * output)"print_nfs_attributes: print an fattr3 to a given output file.
.PP
\fBParameters:\fP
.RS 4
\fIattrs\fP (in fattr3) The attributes to be printed. 
.br
\fIoutput\fP (in FILE *) The file where the attributes are to be printed. 
.RE
.PP
\fBReturns:\fP
.RS 4
Nothing. 
.RE
.PP

.PP
Definition at line 4336 of file cmd_nfstools.c.
.SS "void print_nfsitem_line (FILE * out, fattr3 * attrib, char * name, char * target)"print_nfsitem_line: Prints a nfs element on one line, like the Unix ls command.
.PP
\fBParameters:\fP
.RS 4
\fIout\fP (in FILE*) The file where the item is to be printed. 
.br
\fIattrib\fP (fattr3 *) the NFS attributes for the item. 
.br
\fIname\fP (in char *) The name of the item to be printed. 
.br
\fItarget\fP (in char *) It the item is a symbolic link, this contains the link target. 
.RE
.PP
\fBReturns:\fP
.RS 4
Nothing. 
.RE
.PP

.PP
Definition at line 4233 of file cmd_nfstools.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for ganeshell from the source code.
