.TH "cmdCacheInode_thr_info__" 3 "15 Sep 2010" "Version 0.1" "ganeshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmdCacheInode_thr_info__ \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBis_thread_init\fP"
.br
.ti -1c
.RI "fsal_export_context_t \fBexp_context\fP"
.br
.ti -1c
.RI "fsal_op_context_t \fBcontext\fP"
.br
.ti -1c
.RI "cache_inode_status_t \fBcache_status\fP"
.br
.ti -1c
.RI "int \fBis_client_init\fP"
.br
.ti -1c
.RI "cache_entry_t * \fBpentry\fP"
.br
.ti -1c
.RI "char \fBcurrent_path\fP [FSAL_MAX_PATH_LEN]"
.br
.ti -1c
.RI "cache_inode_client_t \fBclient\fP"
.br
.ti -1c
.RI "cache_content_client_t \fBdc_client\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 91 of file commands_Cache_inode.c.
.SH "Member Data Documentation"
.PP 
.SS "cache_inode_status_t \fBcmdCacheInode_thr_info__::cache_status\fP"Thread specific variable: Last status from cache_inode layer 
.PP
Definition at line 106 of file commands_Cache_inode.c.
.SS "cache_inode_client_t \fBcmdCacheInode_thr_info__::client\fP"Thread specific variable : the client for the cache 
.PP
Definition at line 117 of file commands_Cache_inode.c.
.SS "fsal_op_context_t \fBcmdCacheInode_thr_info__::context\fP"context for accessing the filesystem 
.PP
Definition at line 103 of file commands_Cache_inode.c.
.SS "char \fBcmdCacheInode_thr_info__::current_path\fP[FSAL_MAX_PATH_LEN]"Thread specific variable : Current path 
.PP
Definition at line 114 of file commands_Cache_inode.c.
.SS "cache_content_client_t \fBcmdCacheInode_thr_info__::dc_client\fP"
.PP
Definition at line 118 of file commands_Cache_inode.c.
.SS "fsal_export_context_t \fBcmdCacheInode_thr_info__::exp_context\fP"
.PP
Definition at line 100 of file commands_Cache_inode.c.
.SS "int \fBcmdCacheInode_thr_info__::is_client_init\fP"
.PP
Definition at line 108 of file commands_Cache_inode.c.
.SS "int \fBcmdCacheInode_thr_info__::is_thread_init\fP"
.PP
Definition at line 94 of file commands_Cache_inode.c.
.SS "cache_entry_t* \fBcmdCacheInode_thr_info__::pentry\fP"Thread specific variable: current pentry 
.PP
Definition at line 111 of file commands_Cache_inode.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for ganeshell from the source code.
