.TH "cmdfsal_thr_info__" 3 "31 Mar 2009" "Version 0.1" "ganeshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmdfsal_thr_info__ \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBis_thread_ok\fP"
.br
.ti -1c
.RI "fsal_handle_t \fBcurrent_dir\fP"
.br
.ti -1c
.RI "char \fBcurrent_path\fP [FSAL_MAX_PATH_LEN]"
.br
.ti -1c
.RI "fsal_op_context_t \fBcontext\fP"
.br
.ti -1c
.RI "fsal_export_context_t \fBexp_context\fP"
.br
.ti -1c
.RI "int \fBopened\fP"
.br
.ti -1c
.RI "fsal_file_t \fBcurrent_fd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 314 of file commands_FSAL.c.
.SH "Member Data Documentation"
.PP 
.SS "fsal_op_context_t \fBcmdfsal_thr_info__::context\fP"
.PP
Definition at line 321 of file commands_FSAL.c.
.SS "fsal_handle_t \fBcmdfsal_thr_info__::current_dir\fP"
.PP
Definition at line 317 of file commands_FSAL.c.
.SS "fsal_file_t \fBcmdfsal_thr_info__::current_fd\fP"
.PP
Definition at line 329 of file commands_FSAL.c.
.SS "char \fBcmdfsal_thr_info__::current_path\fP[FSAL_MAX_PATH_LEN]"
.PP
Definition at line 318 of file commands_FSAL.c.
.SS "fsal_export_context_t \fBcmdfsal_thr_info__::exp_context\fP"
.PP
Definition at line 327 of file commands_FSAL.c.
.SS "int \fBcmdfsal_thr_info__::is_thread_ok\fP"
.PP
Definition at line 316 of file commands_FSAL.c.
.SS "int \fBcmdfsal_thr_info__::opened\fP"
.PP
Definition at line 328 of file commands_FSAL.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for ganeshell from the source code.
