.TH "cmdnfs_thr_info__" 3 "15 Sep 2010" "Version 0.1" "ganeshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmdnfs_thr_info__ \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBis_thread_init\fP"
.br
.ti -1c
.RI "fsal_export_context_t \fBexp_context\fP"
.br
.ti -1c
.RI "fsal_op_context_t \fBcontext\fP"
.br
.ti -1c
.RI "struct authunix_parms \fBauthunix_struct\fP"
.br
.ti -1c
.RI "cache_inode_client_t \fBclient\fP"
.br
.ti -1c
.RI "cache_content_client_t \fBdc_client\fP"
.br
.ti -1c
.RI "int \fBis_mounted_path\fP"
.br
.ti -1c
.RI "\fBshell_fh3_t\fP \fBmounted_path_hdl\fP"
.br
.ti -1c
.RI "char \fBmounted_path\fP [NFS2_MAXPATHLEN]"
.br
.ti -1c
.RI "\fBshell_fh3_t\fP \fBcurrent_path_hdl\fP"
.br
.ti -1c
.RI "char \fBcurrent_path\fP [NFS2_MAXPATHLEN]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 232 of file commands_NFS.c.
.SH "Member Data Documentation"
.PP 
.SS "struct authunix_parms \fBcmdnfs_thr_info__::authunix_struct\fP\fC [read]\fP"
.PP
Definition at line 247 of file commands_NFS.c.
.SS "cache_inode_client_t \fBcmdnfs_thr_info__::client\fP"Thread specific variable : the client for the cache 
.PP
Definition at line 250 of file commands_NFS.c.
.SS "fsal_op_context_t \fBcmdnfs_thr_info__::context\fP"context for accessing the filesystem 
.PP
Definition at line 244 of file commands_NFS.c.
.SS "char \fBcmdnfs_thr_info__::current_path\fP[NFS2_MAXPATHLEN]"
.PP
Definition at line 260 of file commands_NFS.c.
.SS "\fBshell_fh3_t\fP \fBcmdnfs_thr_info__::current_path_hdl\fP"
.PP
Definition at line 259 of file commands_NFS.c.
.SS "cache_content_client_t \fBcmdnfs_thr_info__::dc_client\fP"
.PP
Definition at line 251 of file commands_NFS.c.
.SS "fsal_export_context_t \fBcmdnfs_thr_info__::exp_context\fP"
.PP
Definition at line 241 of file commands_NFS.c.
.SS "int \fBcmdnfs_thr_info__::is_mounted_path\fP"
.PP
Definition at line 254 of file commands_NFS.c.
.SS "int \fBcmdnfs_thr_info__::is_thread_init\fP"
.PP
Definition at line 235 of file commands_NFS.c.
.SS "char \fBcmdnfs_thr_info__::mounted_path\fP[NFS2_MAXPATHLEN]"
.PP
Definition at line 257 of file commands_NFS.c.
.SS "\fBshell_fh3_t\fP \fBcmdnfs_thr_info__::mounted_path_hdl\fP"
.PP
Definition at line 256 of file commands_NFS.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for ganeshell from the source code.
