.TH "cmdnfsremote_funcdesc__" 3 "31 Mar 2009" "Version 0.1" "ganeshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmdnfsremote_funcdesc__ \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cmd_nfstools.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBfunc_name\fP"
.br
.ti -1c
.RI "nfsremote_protocol_function_t \fBfunc_call\fP"
.br
.ti -1c
.RI "nfs_protocol_free_t \fBfunc_free\fP"
.br
.ti -1c
.RI "\fBcmdnfs_encoding_func_t\fP \fBfunc_encode\fP"
.br
.ti -1c
.RI "\fBcmdnfs_encoding_func_t\fP \fBfunc_decode\fP"
.br
.ti -1c
.RI "char * \fBfunc_help\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 136 of file cmd_nfstools.h.
.SH "Member Data Documentation"
.PP 
.SS "nfsremote_protocol_function_t \fBcmdnfsremote_funcdesc__::func_call\fP"
.PP
Definition at line 142 of file cmd_nfstools.h.
.SS "\fBcmdnfs_encoding_func_t\fP \fBcmdnfsremote_funcdesc__::func_decode\fP"
.PP
Definition at line 151 of file cmd_nfstools.h.
.SS "\fBcmdnfs_encoding_func_t\fP \fBcmdnfsremote_funcdesc__::func_encode\fP"
.PP
Definition at line 148 of file cmd_nfstools.h.
.SS "nfs_protocol_free_t \fBcmdnfsremote_funcdesc__::func_free\fP"
.PP
Definition at line 145 of file cmd_nfstools.h.
.SS "char* \fBcmdnfsremote_funcdesc__::func_help\fP"
.PP
Definition at line 154 of file cmd_nfstools.h.
.SS "char* \fBcmdnfsremote_funcdesc__::func_name\fP"
.PP
Definition at line 139 of file cmd_nfstools.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ganeshell from the source code.
