.TH "cmdnfs_funcdesc__" 3 "31 Mar 2009" "Version 0.1" "ganeshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmdnfs_funcdesc__ \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cmd_nfstools.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBfunc_name\fP"
.br
.ti -1c
.RI "nfs_protocol_function_t \fBfunc_call\fP"
.br
.ti -1c
.RI "nfs_protocol_free_t \fBfunc_free\fP"
.br
.ti -1c
.RI "\fBcmdnfs_encoding_func_t\fP \fBfunc_encode\fP"
.br
.ti -1c
.RI "\fBcmdnfs_encoding_func_t\fP \fBfunc_decode\fP"
.br
.ti -1c
.RI "char * \fBfunc_help\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 114 of file cmd_nfstools.h.
.SH "Member Data Documentation"
.PP 
.SS "nfs_protocol_function_t \fBcmdnfs_funcdesc__::func_call\fP"
.PP
Definition at line 120 of file cmd_nfstools.h.
.SS "\fBcmdnfs_encoding_func_t\fP \fBcmdnfs_funcdesc__::func_decode\fP"
.PP
Definition at line 129 of file cmd_nfstools.h.
.SS "\fBcmdnfs_encoding_func_t\fP \fBcmdnfs_funcdesc__::func_encode\fP"
.PP
Definition at line 126 of file cmd_nfstools.h.
.SS "nfs_protocol_free_t \fBcmdnfs_funcdesc__::func_free\fP"
.PP
Definition at line 123 of file cmd_nfstools.h.
.SS "char* \fBcmdnfs_funcdesc__::func_help\fP"
.PP
Definition at line 132 of file cmd_nfstools.h.
.SS "char* \fBcmdnfs_funcdesc__::func_name\fP"
.PP
Definition at line 117 of file cmd_nfstools.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ganeshell from the source code.
