.TH "command_def__" 3 "15 Sep 2010" "Version 0.1" "ganeshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
command_def__ \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shell_types.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBcommand_name\fP"
.br
.ti -1c
.RI "int(* \fBcommand_func\fP )(int, char **, FILE *)"
.br
.ti -1c
.RI "char * \fBcommand_help\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
command definition 
.PP
Definition at line 27 of file shell_types.h.
.SH "Member Data Documentation"
.PP 
.SS "int(* \fBcommand_def__::command_func\fP)(int, char **, FILE *)"
.SS "char* \fBcommand_def__::command_help\fP"
.PP
Definition at line 37 of file shell_types.h.
.SS "char* \fBcommand_def__::command_name\fP"
.PP
Definition at line 31 of file shell_types.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ganeshell from the source code.
