.TH "commands.h" 3 "15 Sep 2010" "Version 0.1" "ganeshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
commands.h \- 
.PP
Header file for processing user's command line.  

.SH SYNOPSIS
.br
.PP
\fC#include 'shell_types.h'\fP
.br
\fC#include <stdio.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfsal_layer_SetLogLevel\fP (int log_lvl)"
.br
.ti -1c
.RI "int \fBfn_fsal_init_fs\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_fsal_pwd\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_fsal_cd\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_fsal_stat\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_fsal_ls\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_fsal_callstat\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_fsal_su\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_fsal_unlink\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_fsal_mkdir\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_fsal_rename\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_fsal_ln\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_fsal_hardlink\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_fsal_create\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_fsal_setattr\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_fsal_access\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_fsal_truncate\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_fsal_open\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_fsal_open_byname\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_fsal_open_byfileid\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_fsal_read\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_fsal_write\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_fsal_close\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_fsal_close_byfileid\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_fsal_cat\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_fsal_rcp\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_fsal_cross\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_fsal_handlecmp\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_fsal_lsxattrs\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_fsal_getxattr\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "void \fBCache_inode_layer_SetLogLevel\fP (int log_lvl)"
.br
.ti -1c
.RI "int \fBfn_Cache_inode_cache_init\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_Cache_inode_pwd\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_Cache_inode_cd\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_Cache_inode_stat\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_Cache_inode_gc\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_Cache_inode_ls\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_Cache_inode_link\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_Cache_inode_mkdir\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_Cache_inode_rename\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_Cache_inode_create\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_Cache_inode_ln\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_Cache_inode_open_by_name\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_Cache_inode_close\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_Cache_inode_setattr\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_Cache_inode_unlink\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_Cache_inode_callstat\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_Cache_inode_data_cache\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_Cache_inode_recover_cache\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_Cache_inode_refresh_cache\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_Cache_inode_flush_cache\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_Cache_inode_release_cache\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_Cache_inode_read\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_Cache_inode_write\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_Cache_inode_su\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_Cache_inode_access\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "void \fBnfs_layer_SetLogLevel\fP (int log_lvl)"
.br
.ti -1c
.RI "int \fBfn_nfs_init\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_MNT1_command\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_MNT3_command\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_NFS2_command\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_NFS3_command\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_cd\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_ls\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_mount\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_umount\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_pwd\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_create\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_mkdir\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_unlink\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_setattr\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_rename\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_hardlink\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_ln\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_stat\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_su\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_id\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "void \fBnfs_remote_layer_SetLogLevel\fP (int log_lvl)"
.br
.ti -1c
.RI "int \fBfn_rpc_init\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_MNT1_remote_command\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_MNT3_remote_command\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_NFS2_remote_command\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_NFS3_remote_command\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_remote_cd\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_remote_ls\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_remote_mount\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_remote_umount\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_remote_pwd\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_remote_create\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_remote_mkdir\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_remote_unlink\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_remote_setattr\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_remote_rename\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_remote_hardlink\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_remote_ln\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_remote_stat\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_remote_su\fP (int argc, char **argv, FILE *output)"
.br
.ti -1c
.RI "int \fBfn_nfs_remote_id\fP (int argc, char **argv, FILE *output)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBlayer_def_t\fP \fBlayer_list\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header file for processing user's command line. 

\fBAuthor:\fP
.RS 4
.RE
.PP
\fBAuthor\fP.RS 4
leibovic 
.RE
.PP
\fBDate:\fP
.RS 4
.RE
.PP
\fBDate\fP.RS 4
2006/01/24 15:04:22 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision\fP.RS 4
1.52 
.RE
.PP

.PP
Definition in file \fBcommands.h\fP.
.SH "Function Documentation"
.PP 
.SS "void Cache_inode_layer_SetLogLevel (int log_lvl)"
.PP
Definition at line 287 of file commands_Cache_inode.c.
.SS "int fn_Cache_inode_access (int argc, char ** argv, FILE * output)"perform an access command. syntax: access [F][R][W][X] <file> example: access toto FRX 
.PP
Definition at line 2761 of file commands_Cache_inode.c.
.SS "int fn_Cache_inode_cache_init (int argc, char ** argv, FILE * output)"inits the filesystem.
.PP
proceed an init_fs command. 
.PP
Definition at line 753 of file commands_Cache_inode.c.
.SS "int fn_Cache_inode_callstat (int argc, char ** argv, FILE * output)"display statistics about FSAL calls. 
.PP
Definition at line 1526 of file commands_Cache_inode.c.
.SS "int fn_Cache_inode_cd (int argc, char ** argv, FILE * output)"proceed a cd command.
.PP
change current path 
.PP
Definition at line 864 of file commands_Cache_inode.c.
.SS "int fn_Cache_inode_close (int argc, char ** argv, FILE * output)"Close a previously opened file
.PP
Close an opened entry 
.PP
Definition at line 4559 of file commands_Cache_inode.c.
.SS "int fn_Cache_inode_create (int argc, char ** argv, FILE * output)"proceed an create command. 
.PP
Definition at line 2082 of file commands_Cache_inode.c.
.SS "int fn_Cache_inode_data_cache (int argc, char ** argv, FILE * output)"cache en entry (REGULAR_FILE) in the data cache 
.PP
Definition at line 2934 of file commands_Cache_inode.c.
.SS "int fn_Cache_inode_flush_cache (int argc, char ** argv, FILE * output)"flush en entry (REGULAR_FILE) in the data cache 
.PP
Definition at line 3409 of file commands_Cache_inode.c.
.SS "int fn_Cache_inode_gc (int argc, char ** argv, FILE * output)"proceed to a call to the garbagge collector. 
.PP
Definition at line 1030 of file commands_Cache_inode.c.
.SS "int fn_Cache_inode_link (int argc, char ** argv, FILE * output)"proceed a hard link (hard link) command.
.PP
proceed an create command. 
.PP
Definition at line 1783 of file commands_Cache_inode.c.
.SS "int fn_Cache_inode_ln (int argc, char ** argv, FILE * output)"proceed an ln (symlink) command. 
.PP
Definition at line 1928 of file commands_Cache_inode.c.
.SS "int fn_Cache_inode_ls (int argc, char ** argv, FILE * output)"proceed an ls command. 
.PP
Definition at line 1112 of file commands_Cache_inode.c.
.SS "int fn_Cache_inode_mkdir (int argc, char ** argv, FILE * output)"proceed a mkdir command.
.PP
proceed an mkdir command. 
.PP
Definition at line 1594 of file commands_Cache_inode.c.
.SS "int fn_Cache_inode_open_by_name (int argc, char ** argv, FILE * output)"proceed an open by name (open_by_name) command.
.PP
change current path 
.PP
Definition at line 4485 of file commands_Cache_inode.c.
.SS "int fn_Cache_inode_pwd (int argc, char ** argv, FILE * output)"proceed an pwd command.
.PP
prints current path 
.PP
Definition at line 833 of file commands_Cache_inode.c.
.SS "int fn_Cache_inode_read (int argc, char ** argv, FILE * output)"Reads the content of a cached regular file 
.PP
Definition at line 3529 of file commands_Cache_inode.c.
.SS "int fn_Cache_inode_recover_cache (int argc, char ** argv, FILE * output)"recover the data cache 
.PP
Definition at line 3189 of file commands_Cache_inode.c.
.SS "int fn_Cache_inode_refresh_cache (int argc, char ** argv, FILE * output)"refresh en entry (REGULAR_FILE) in the data cache 
.PP
Definition at line 3288 of file commands_Cache_inode.c.
.SS "int fn_Cache_inode_release_cache (int argc, char ** argv, FILE * output)"cache en entry (REGULAR_FILE) in the data cache 
.PP
Definition at line 3077 of file commands_Cache_inode.c.
.SS "int fn_Cache_inode_rename (int argc, char ** argv, FILE * output)"proceed a rename command. 
.PP
Definition at line 2270 of file commands_Cache_inode.c.
.SS "int fn_Cache_inode_setattr (int argc, char ** argv, FILE * output)"setattr
.PP
syntax of command line: setattr file_path attribute_name attribute_value 
.PP
Definition at line 2575 of file commands_Cache_inode.c.
.SS "int fn_Cache_inode_stat (int argc, char ** argv, FILE * output)"proceed a stat command. 
.PP
Definition at line 928 of file commands_Cache_inode.c.
.SS "int fn_Cache_inode_su (int argc, char ** argv, FILE * output)"Change current user
.PP
change thread contexte. 
.PP
Definition at line 4390 of file commands_Cache_inode.c.
.SS "int fn_Cache_inode_unlink (int argc, char ** argv, FILE * output)"proceed an unlink command. 
.PP
Definition at line 2434 of file commands_Cache_inode.c.
.SS "int fn_Cache_inode_write (int argc, char ** argv, FILE * output)"Reads the content of a cached regular file 
.PP
Definition at line 3953 of file commands_Cache_inode.c.
.SS "int fn_fsal_access (int argc, char ** argv, FILE * output)"test access rights.
.PP
perform an access command. syntax: access [-A] [F][R][W][X] <file> example: access toto FRX 
.PP
Definition at line 3222 of file commands_FSAL.c.
.SS "int fn_fsal_callstat (int argc, char ** argv, FILE * output)"display statistics about FSAL calls. 
.PP
Definition at line 1857 of file commands_FSAL.c.
.SS "int fn_fsal_cat (int argc, char ** argv, FILE * output)"display a file.
.PP
Command that prints a file to screen. cat [-f] <path> 
.PP
Definition at line 5265 of file commands_FSAL.c.
.SS "int fn_fsal_cd (int argc, char ** argv, FILE * output)"proceed a cd command.
.PP
change current path 
.PP
Definition at line 911 of file commands_FSAL.c.
.SS "int fn_fsal_close (int argc, char ** argv, FILE * output)"close a file.
.PP
Command that closes a file. close 
.PP
Definition at line 5135 of file commands_FSAL.c.
.SS "int fn_fsal_close_byfileid (int argc, char ** argv, FILE * output)"close a file.
.PP
Command that closes a file. close 
.PP
Definition at line 5200 of file commands_FSAL.c.
.SS "int fn_fsal_create (int argc, char ** argv, FILE * output)"create a regular file.
.PP
proceed an create command. 
.PP
Definition at line 2829 of file commands_FSAL.c.
.SS "int fn_fsal_cross (int argc, char ** argv, FILE * output)"cross a junction.
.PP
change current path 
.PP
Definition at line 5643 of file commands_FSAL.c.
.SS "int fn_fsal_getxattr (int argc, char ** argv, FILE * output)"display an extended attribute. 
.PP
Definition at line 1289 of file commands_FSAL.c.
.SS "int fn_fsal_handlecmp (int argc, char ** argv, FILE * output)"compare 2 handles. 
.PP
Definition at line 5728 of file commands_FSAL.c.
.SS "int fn_fsal_hardlink (int argc, char ** argv, FILE * output)"create a hardlink.
.PP
proceed a hardlink command. 
.PP
Definition at line 2668 of file commands_FSAL.c.
.SS "int fn_fsal_init_fs (int argc, char ** argv, FILE * output)"inits the filesystem.
.PP
proceed an init_fs command. 
.PP
Definition at line 625 of file commands_FSAL.c.
.SS "int fn_fsal_ln (int argc, char ** argv, FILE * output)"create a symlink.
.PP
proceed an ln command. 
.PP
Definition at line 2500 of file commands_FSAL.c.
.SS "int fn_fsal_ls (int argc, char ** argv, FILE * output)"proceed an ls command. 
.PP
Definition at line 1539 of file commands_FSAL.c.
.SS "int fn_fsal_lsxattrs (int argc, char ** argv, FILE * output)"list extended attributes. 
.PP
Definition at line 1145 of file commands_FSAL.c.
.SS "int fn_fsal_mkdir (int argc, char ** argv, FILE * output)"create a directory.
.PP
proceed an mkdir command. 
.PP
Definition at line 2138 of file commands_FSAL.c.
.SS "int fn_fsal_open (int argc, char ** argv, FILE * output)"open a file.
.PP
Command that opens a file using specific flags. open <path> [ rwat ] 
.PP
Definition at line 3826 of file commands_FSAL.c.
.SS "int fn_fsal_open_byfileid (int argc, char ** argv, FILE * output)"open a file (using FSAL_open_by_name).
.PP
Command that opens a file using specific flags. open <path> [ rwat ] 
.PP
Definition at line 4031 of file commands_FSAL.c.
.SS "int fn_fsal_open_byname (int argc, char ** argv, FILE * output)"open a file (using FSAL_open_by_name).
.PP
Command that opens a file using specific flags, but using FSAL_open_by_name. open <path> [ rwat ] 
.PP
Definition at line 3620 of file commands_FSAL.c.
.SS "int fn_fsal_pwd (int argc, char ** argv, FILE * output)"proceed an pwd command.
.PP
prints current path 
.PP
Definition at line 701 of file commands_FSAL.c.
.SS "int fn_fsal_rcp (int argc, char ** argv, FILE * output)"copy a file to/from local path.
.PP
Command that copy a file from/to the local filesystem. rcp [-h] -r|-w <fsal_path> <local_path> 
.PP
Definition at line 5438 of file commands_FSAL.c.
.SS "int fn_fsal_read (int argc, char ** argv, FILE * output)"read from file.
.PP
Command that reads data from an opened file. 
.PP
Definition at line 4240 of file commands_FSAL.c.
.SS "int fn_fsal_rename (int argc, char ** argv, FILE * output)"create a directory.
.PP
proceed a rename command. 
.PP
Definition at line 2322 of file commands_FSAL.c.
.SS "int fn_fsal_setattr (int argc, char ** argv, FILE * output)"change file attributes. 
.PP
Definition at line 3027 of file commands_FSAL.c.
.SS "int fn_fsal_stat (int argc, char ** argv, FILE * output)"proceed a stat command. 
.PP
Definition at line 1007 of file commands_FSAL.c.
.SS "int fn_fsal_su (int argc, char ** argv, FILE * output)"change current user.
.PP
change thread contexte. 
.PP
Definition at line 1902 of file commands_FSAL.c.
.SS "int fn_fsal_truncate (int argc, char ** argv, FILE * output)"truncate file.
.PP
proceed a truncate command. 
.PP
Definition at line 3483 of file commands_FSAL.c.
.SS "int fn_fsal_unlink (int argc, char ** argv, FILE * output)"unlink an fs object.
.PP
proceed an unlink command. 
.PP
Definition at line 2008 of file commands_FSAL.c.
.SS "int fn_fsal_write (int argc, char ** argv, FILE * output)"write to file.
.PP
Command that writes data to an opened file.
.PP
Usage: write [-h][-v] [ -s <seek_type>,<offset> ] [-N <nb_times>] -A <ascii_string> write [-h][-v] [ -s <seek_type>,<offset> ] [-N <nb_times>] -X <hexa_data> Where: <seek_type> can be: SET, CUR, END <offset> is a signed number of bytes. <nb_times> is the number of times we write the expression into the file.
.PP
<ascii_string> is a string to be written to file. Note that the null terminating character of is also written to file. or <hexa_data> is a data represented in hexadecimal format, that is to be written to file.
.PP
Examples:
.PP
For writing 10 times the null terminated string 'hello world' at the end of the file: write -s END,0 -N 10 -A 'hello world'
.PP
For overwriting the beginning of the file with the pattern 0xA1267AEF31254ADE repeated twice: write -s SET,0 -N 2 -X 'A1267AEF31254ADE' 
.PP
Definition at line 4688 of file commands_FSAL.c.
.SS "int fn_MNT1_command (int argc, char ** argv, FILE * output)"process MNT1 protocol's command. 
.PP
Definition at line 571 of file commands_NFS.c.
.SS "int fn_MNT1_remote_command (int argc, char ** argv, FILE * output)"process MNT1 protocol's command. 
.PP
Definition at line 658 of file commands_NFS_remote.c.
.SS "int fn_MNT3_command (int argc, char ** argv, FILE * output)"process MNT3 protocol's command. 
.PP
Definition at line 661 of file commands_NFS.c.
.SS "int fn_MNT3_remote_command (int argc, char ** argv, FILE * output)"process MNT3 protocol's command. 
.PP
Definition at line 735 of file commands_NFS_remote.c.
.SS "int fn_NFS2_command (int argc, char ** argv, FILE * output)"process NFS2 protocol's command. 
.PP
Definition at line 750 of file commands_NFS.c.
.SS "int fn_NFS2_remote_command (int argc, char ** argv, FILE * output)"process NFS2 protocol's command. 
.PP
Definition at line 812 of file commands_NFS_remote.c.
.SS "int fn_NFS3_command (int argc, char ** argv, FILE * output)"process NFS3 protocol's command. 
.PP
Definition at line 857 of file commands_NFS.c.
.SS "int fn_NFS3_remote_command (int argc, char ** argv, FILE * output)"process NFS3 protocol's command. 
.PP
Definition at line 890 of file commands_NFS_remote.c.
.SS "int fn_nfs_cd (int argc, char ** argv, FILE * output)"process a cd command using NFS protocol.
.PP
change current path 
.PP
Definition at line 2407 of file commands_NFS.c.
.SS "int fn_nfs_create (int argc, char ** argv, FILE * output)"process an create command using NFS protocol.
.PP
create a file 
.PP
Definition at line 2493 of file commands_NFS.c.
.SS "int fn_nfs_hardlink (int argc, char ** argv, FILE * output)"process an create command using NFS protocol.
.PP
proceed a hardlink command. 
.PP
Definition at line 3152 of file commands_NFS.c.
.SS "int fn_nfs_id (int argc, char ** argv, FILE * output)"
.PP
Definition at line 3686 of file commands_NFS.c.
.SS "int fn_nfs_init (int argc, char ** argv, FILE * output)"process NFS layer initialization.
.PP
Init nfs layer 
.PP
Definition at line 489 of file commands_NFS.c.
.SS "int fn_nfs_ln (int argc, char ** argv, FILE * output)"process an create command using NFS protocol.
.PP
proceed an ln command. 
.PP
Definition at line 3288 of file commands_NFS.c.
.SS "int fn_nfs_ls (int argc, char ** argv, FILE * output)"process an ls command using NFS protocol.
.PP
proceed an ls command using NFS protocol NFS 
.PP
Definition at line 2084 of file commands_NFS.c.
.SS "int fn_nfs_mkdir (int argc, char ** argv, FILE * output)"process an create command using NFS protocol.
.PP
create a directory 
.PP
Definition at line 2620 of file commands_NFS.c.
.SS "int fn_nfs_mount (int argc, char ** argv, FILE * output)"process a mount command using MOUNT protocol.
.PP
mount a path to browse it. 
.PP
Definition at line 1871 of file commands_NFS.c.
.SS "int fn_nfs_pwd (int argc, char ** argv, FILE * output)"process an ls command using NFS protocol.
.PP
prints current path 
.PP
Definition at line 2051 of file commands_NFS.c.
.SS "int fn_nfs_remote_cd (int argc, char ** argv, FILE * output)"process a cd command using NFS protocol.
.PP
change current path 
.PP
Definition at line 2389 of file commands_NFS_remote.c.
.SS "int fn_nfs_remote_create (int argc, char ** argv, FILE * output)"process an create command using NFS protocol.
.PP
create a file 
.PP
Definition at line 2464 of file commands_NFS_remote.c.
.SS "int fn_nfs_remote_hardlink (int argc, char ** argv, FILE * output)"process an create command using NFS protocol.
.PP
proceed a hardlink command. 
.PP
Definition at line 3068 of file commands_NFS_remote.c.
.SS "int fn_nfs_remote_id (int argc, char ** argv, FILE * output)"
.PP
Definition at line 3559 of file commands_NFS_remote.c.
.SS "int fn_nfs_remote_ln (int argc, char ** argv, FILE * output)"process an create command using NFS protocol.
.PP
proceed an ln command. 
.PP
Definition at line 3194 of file commands_NFS_remote.c.
.SS "int fn_nfs_remote_ls (int argc, char ** argv, FILE * output)"process an ls command using NFS protocol.
.PP
proceed an ls command using NFS protocol NFS 
.PP
Definition at line 2076 of file commands_NFS_remote.c.
.SS "int fn_nfs_remote_mkdir (int argc, char ** argv, FILE * output)"process an create command using NFS protocol.
.PP
create a directory 
.PP
Definition at line 2580 of file commands_NFS_remote.c.
.SS "int fn_nfs_remote_mount (int argc, char ** argv, FILE * output)"process an mount command using MOUNT protocol.
.PP
mount a path to browse it. 
.PP
Definition at line 1939 of file commands_NFS_remote.c.
.SS "int fn_nfs_remote_pwd (int argc, char ** argv, FILE * output)"process an ls command using NFS protocol.
.PP
prints current path 
.PP
Definition at line 2056 of file commands_NFS_remote.c.
.SS "int fn_nfs_remote_rename (int argc, char ** argv, FILE * output)"process an create command using NFS protocol.
.PP
proceed a rename command. 
.PP
Definition at line 2941 of file commands_NFS_remote.c.
.SS "int fn_nfs_remote_setattr (int argc, char ** argv, FILE * output)"process an create command using NFS protocol.
.PP
setattr 
.PP
Definition at line 2825 of file commands_NFS_remote.c.
.SS "int fn_nfs_remote_stat (int argc, char ** argv, FILE * output)"process a stat command using NFS protocol.
.PP
proceed an ls command using NFS protocol NFS 
.PP
Definition at line 3326 of file commands_NFS_remote.c.
.SS "int fn_nfs_remote_su (int argc, char ** argv, FILE * output)"change thread credentials. 
.PP
Definition at line 3469 of file commands_NFS_remote.c.
.SS "int fn_nfs_remote_umount (int argc, char ** argv, FILE * output)"process a umount command using MOUNT protocol.
.PP
umount a mounted path 
.PP
Definition at line 1985 of file commands_NFS_remote.c.
.SS "int fn_nfs_remote_unlink (int argc, char ** argv, FILE * output)"process an create command using NFS protocol.
.PP
unlink a file 
.PP
Definition at line 2697 of file commands_NFS_remote.c.
.SS "int fn_nfs_rename (int argc, char ** argv, FILE * output)"process an create command using NFS protocol.
.PP
proceed a rename command. 
.PP
Definition at line 3015 of file commands_NFS.c.
.SS "int fn_nfs_setattr (int argc, char ** argv, FILE * output)"process an create command using NFS protocol.
.PP
setattr 
.PP
Definition at line 2885 of file commands_NFS.c.
.SS "int fn_nfs_stat (int argc, char ** argv, FILE * output)"process a stat command using NFS protocol.
.PP
proceed an ls command using NFS protocol NFS 
.PP
Definition at line 3430 of file commands_NFS.c.
.SS "int fn_nfs_su (int argc, char ** argv, FILE * output)"change thread credentials. 
.PP
Definition at line 3585 of file commands_NFS.c.
.SS "int fn_nfs_umount (int argc, char ** argv, FILE * output)"process an umount command using MOUNT protocol.
.PP
umount a mounted path. 
.PP
Definition at line 1970 of file commands_NFS.c.
.SS "int fn_nfs_unlink (int argc, char ** argv, FILE * output)"process an create command using NFS protocol.
.PP
unlink a file 
.PP
Definition at line 2747 of file commands_NFS.c.
.SS "int fn_rpc_init (int argc, char ** argv, FILE * output)"process RPC clients initialization.
.PP
fn_rpc_init 
.PP
Definition at line 565 of file commands_NFS_remote.c.
.SS "void fsal_layer_SetLogLevel (int log_lvl)"
.PP
Definition at line 434 of file commands_FSAL.c.
.SS "void nfs_layer_SetLogLevel (int log_lvl)"
.PP
Definition at line 404 of file commands_NFS.c.
.SS "void nfs_remote_layer_SetLogLevel (int log_lvl)"
.PP
Definition at line 649 of file commands_NFS_remote.c.
.SH "Variable Documentation"
.PP 
.SS "\fBlayer_def_t\fP \fBlayer_list\fP[]"Layer list. 
.PP
Definition at line 133 of file shell.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for ganeshell from the source code.
