.TH "Getopt.h" 3 "31 Mar 2009" "Version 0.1" "ganeshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Getopt.h \- Prototype for GANESHA's version of getopt, to avoid portability issues.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBGetopt\fP (int argc, char *argv[], char *opts)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBOpterr\fP"
.br
.ti -1c
.RI "int \fBOptind\fP"
.br
.ti -1c
.RI "int \fBOptopt\fP"
.br
.ti -1c
.RI "char * \fBOptarg\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Prototype for GANESHA's version of getopt, to avoid portability issues. 

\fBAuthor:\fP
.RS 4
.RE
.PP
\fBAuthor\fP.RS 4
leibovic 
.RE
.PP
\fBDate:\fP
.RS 4
.RE
.PP
\fBDate\fP.RS 4
2005/02/02 09:05:30 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision\fP.RS 4
1.1 
.RE
.PP
\fBLog\fP.RS 4
\fBGetopt.h\fP,v 
.RE
.PP
Revision 1.1 2005/02/02 09:05:30 leibovic Adding our own version of getopt, to avoid portability issues. 
.PP
Definition in file \fBGetopt.h\fP.
.SH "Function Documentation"
.PP 
.SS "int Getopt (int argc, char * argv[], char * opts)"
.PP
Definition at line 128 of file Getopt.c.
.SH "Variable Documentation"
.PP 
.SS "char* \fBOptarg\fP"
.PP
Definition at line 126 of file Getopt.c.
.SS "int \fBOpterr\fP"
.PP
Definition at line 123 of file Getopt.c.
.SS "int \fBOptind\fP"
.PP
Definition at line 124 of file Getopt.c.
.SS "int \fBOptopt\fP"
.PP
Definition at line 125 of file Getopt.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for ganeshell from the source code.
