.TH "Getopt.c" 3 "15 Sep 2010" "Version 0.1" "ganeshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Getopt.c \- 
.PP
GANESHA's version of getopt, to avoid portability issues.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Getopt.h'\fP
.br
\fC#include <string.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBNULL\fP   0"
.br
.ti -1c
.RI "#define \fBEOF\fP   (-1)"
.br
.ti -1c
.RI "#define \fBERR\fP(s, c)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBGetopt\fP (int argc, char *argv[], char *opts)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBOpterr\fP = 1"
.br
.ti -1c
.RI "int \fBOptind\fP = 1"
.br
.ti -1c
.RI "int \fBOptopt\fP"
.br
.ti -1c
.RI "char * \fBOptarg\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
GANESHA's version of getopt, to avoid portability issues. 

\fBAuthor:\fP
.RS 4
.RE
.PP
\fBAuthor\fP.RS 4
leibovic 
.RE
.PP
\fBDate:\fP
.RS 4
.RE
.PP
\fBDate\fP.RS 4
2006/01/18 17:03:35 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision\fP.RS 4
1.4 
.RE
.PP
This source code is an adaptation of the AT&T public domain source for getopt(3).
.PP
\fBLog\fP.RS 4
\fBGetopt.c\fP,v 
.RE
.PP
Revision 1.4 2006/01/18 17:03:35 leibovic Removing some warnings.
.PP
Revision 1.2 2005/03/09 15:43:25 leibovic Multi-OS compiling.
.PP
Revision 1.1 2005/02/02 09:05:30 leibovic Adding our own version of getopt, to avoid portability issues. 
.PP
Definition in file \fBGetopt.c\fP.
.SH "Define Documentation"
.PP 
.SS "#define EOF   (-1)"
.PP
Definition at line 61 of file Getopt.c.
.SS "#define ERR(s, c)"\fBValue:\fP
.PP
.nf
if(Opterr){\
    extern int write(int, void *, unsigned);\
    char errbuf[2];\
    errbuf[0] = (char)c; errbuf[1] = '\n';\
    (void) write(2, argv[0], (unsigned)strlen(argv[0]));\
    (void) write(2, s, (unsigned)strlen(s));\
    (void) write(2, errbuf, 2);}
.fi
.PP
Definition at line 62 of file Getopt.c.
.SS "#define NULL   0"
.PP
Definition at line 58 of file Getopt.c.
.SH "Function Documentation"
.PP 
.SS "int Getopt (int argc, char * argv[], char * opts)"
.PP
Definition at line 75 of file Getopt.c.
.SH "Variable Documentation"
.PP 
.SS "char* \fBOptarg\fP"
.PP
Definition at line 73 of file Getopt.c.
.SS "int \fBOpterr\fP = 1"
.PP
Definition at line 70 of file Getopt.c.
.SS "int \fBOptind\fP = 1"
.PP
Definition at line 71 of file Getopt.c.
.SS "int \fBOptopt\fP"
.PP
Definition at line 72 of file Getopt.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for ganeshell from the source code.
