.TH "layer_def__" 3 "15 Sep 2010" "Version 0.1" "ganeshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
layer_def__ \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shell_types.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBlayer_name\fP"
.br
.ti -1c
.RI "\fBcommand_def_t\fP * \fBcommand_list\fP"
.br
.ti -1c
.RI "char * \fBlayer_description\fP"
.br
.ti -1c
.RI "void(* \fBsetlog_func\fP )(int)"
.br
.in -1c
.SH "Detailed Description"
.PP 
layer definition 
.PP
Definition at line 43 of file shell_types.h.
.SH "Member Data Documentation"
.PP 
.SS "\fBcommand_def_t\fP* \fBlayer_def__::command_list\fP"
.PP
Definition at line 47 of file shell_types.h.
.SS "char* \fBlayer_def__::layer_description\fP"
.PP
Definition at line 48 of file shell_types.h.
.SS "char* \fBlayer_def__::layer_name\fP"
.PP
Definition at line 46 of file shell_types.h.
.SS "void(* \fBlayer_def__::setlog_func\fP)(int)"

.SH "Author"
.PP 
Generated automatically by Doxygen for ganeshell from the source code.
