.TH "main.c" 3 "15 Sep 2010" "Version 0.1" "ganeshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c \- 
.PP
main shell routine.  

.SH SYNOPSIS
.br
.PP
\fC#include 'shell.h'\fP
.br
\fC#include 'Getopt.h'\fP
.br
\fC#include <libgen.h>\fP
.br
\fC#include <pthread.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <stdio.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBshell_info__\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBNBTHRMAX\fP   64"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBshell_info__\fP \fBshell_info_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBLaunchShell\fP (void *arg)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "time_t \fBServerBootTime\fP = 0"
.br
.ti -1c
.RI "\fBshell_info_t\fP \fBthrlist\fP [NBTHRMAX]"
.br
.ti -1c
.RI "int \fBverbose\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
main shell routine. 

\fBAuthor:\fP
.RS 4
.RE
.PP
\fBAuthor\fP.RS 4
leibovic 
.RE
.PP
\fBDate:\fP
.RS 4
.RE
.PP
\fBDate\fP.RS 4
2006/02/23 07:42:53 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision\fP.RS 4
1.28 
.RE
.PP
\fBLog\fP.RS 4
\fBmain.c\fP,v 
.RE
.PP
Revision 1.28 2006/02/23 07:42:53 leibovic Adding -n option to shell.
.PP
Revision 1.26 2005/08/12 11:56:59 leibovic coquille.
.PP
Revision 1.25 2005/07/26 12:54:47 leibovic Multi-thread shell with synchronisation routines.
.PP
Revision 1.24 2005/05/09 12:23:55 leibovic Version 2 of ganeshell. 
.PP
Definition in file \fBmain.c\fP.
.SH "Define Documentation"
.PP 
.SS "#define NBTHRMAX   64"
.PP
Definition at line 66 of file main.c.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBshell_info__\fP  \fBshell_info_t\fP"
.SH "Function Documentation"
.PP 
.SS "void* LaunchShell (void * arg)"
.PP
Definition at line 89 of file main.c.
.SS "int main (int argc, char ** argv)"
.PP
Definition at line 120 of file main.c.
.SH "Variable Documentation"
.PP 
.SS "time_t \fBServerBootTime\fP = 0"
.PP
Definition at line 68 of file main.c.
.SS "\fBshell_info_t\fP \fBthrlist\fP[NBTHRMAX]"
.PP
Definition at line 85 of file main.c.
.SS "int \fBverbose\fP = 0"
.PP
Definition at line 87 of file main.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for ganeshell from the source code.
