.TH "Mount protocol functions." 3 "15 Sep 2010" "Version 0.1" "ganeshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mount protocol functions. \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBNFS protocols functions.\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmnt1_remote_Null\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBmnt1_remote_Mnt\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBmnt1_remote_Dump\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBmnt1_remote_Umnt\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBmnt1_remote_UmntAll\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBmnt1_remote_Export\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBmnt3_remote_Null\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBmnt3_remote_Mnt\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBmnt3_remote_Dump\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBmnt3_remote_Umnt\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBmnt3_remote_UmntAll\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBmnt3_remote_Export\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int mnt1_remote_Dump (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"mnt1_remote_Dump: The Mount proc dump function, v1.
.PP
The MOUNT proc dump function, v1
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 129 of file nfs_remote_functions.c.
.SS "int mnt1_remote_Export (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"mnt1_remote_Export: The Mount proc export function, v1.
.PP
The MOUNT proc export function, v1
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 205 of file nfs_remote_functions.c.
.SS "int mnt1_remote_Mnt (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"mnt1_remote_Mnt: The Mount proc mount function, v1.
.PP
The MOUNT proc mount function, v1.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 103 of file nfs_remote_functions.c.
.SS "int mnt1_remote_Null (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"mnt1_remote_Null: The Mount proc null function, v1.
.PP
The MOUNT proc null function, v1.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 78 of file nfs_remote_functions.c.
.SS "int mnt1_remote_Umnt (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"mnt1_remote_Umnt: The Mount proc umount function, v1.
.PP
The MOUNT proc umount function, v1
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 155 of file nfs_remote_functions.c.
.SS "int mnt1_remote_UmntAll (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"mnt1_remote_UmntAll: The Mount proc umount_all function, v1.
.PP
The MOUNT proc umount_all function, v1
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 180 of file nfs_remote_functions.c.
.SS "int mnt3_remote_Dump (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"mnt3_remote_Dump: The Mount proc dump function, v3.
.PP
The MOUNT proc dump function, v3
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 282 of file nfs_remote_functions.c.
.SS "int mnt3_remote_Export (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"mnt3_remote_Export: The Mount proc export function, v3.
.PP
The MOUNT proc export function, v3
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 358 of file nfs_remote_functions.c.
.SS "int mnt3_remote_Mnt (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"mnt3_remote_Mnt: The Mount proc mount function, v3.
.PP
The MOUNT proc mount function, v3.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 256 of file nfs_remote_functions.c.
.SS "int mnt3_remote_Null (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"mnt3_remote_Null: The Mount proc null function, v3.
.PP
The MOUNT proc null function, v3.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 231 of file nfs_remote_functions.c.
.SS "int mnt3_remote_Umnt (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"mnt3_remote_Umnt: The Mount proc umount function, v3.
.PP
The MOUNT proc umount function, v3
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 308 of file nfs_remote_functions.c.
.SS "int mnt3_remote_UmntAll (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"mnt3_remote_UmntAll: The Mount proc umount_all function, v3.
.PP
The MOUNT proc umount_all function, v3
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 333 of file nfs_remote_functions.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for ganeshell from the source code.
