.TH "nfs_remote_functions.h" 3 "9 Apr 2008" "Version 0.1" "ganeshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfs_remote_functions.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'nfs_proto_functions.h'\fP
.br
\fC#include <rpc/clnt.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmnt1_remote_Null\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBmnt1_remote_Mnt\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBmnt1_remote_Dump\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBmnt1_remote_Umnt\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBmnt1_remote_UmntAll\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBmnt1_remote_Export\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBmnt3_remote_Null\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBmnt3_remote_Mnt\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBmnt3_remote_Dump\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBmnt3_remote_Umnt\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBmnt3_remote_UmntAll\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBmnt3_remote_Export\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Null\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Getattr\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Setattr\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Root\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Lookup\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Readlink\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Read\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Writecache\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Write\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Create\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Remove\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Rename\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Link\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Symlink\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Mkdir\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Rmdir\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Readdir\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Fsstat\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Null\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Getattr\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Setattr\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Lookup\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Readlink\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Read\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Write\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Create\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Remove\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Rename\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Link\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Symlink\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Mkdir\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Rmdir\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Readdir\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Fsstat\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Access\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Readdirplus\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Fsinfo\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Pathconf\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Commit\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Mknod\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs4_remote_COMPOUND\fP (CLIENT *clnt, COMPOUND4args *parg, COMPOUND4res *pres)"
.br
.ti -1c
.RI "int \fBnfs4_remote_Null\fP (CLIENT *clnt)"
.br
.ti -1c
.RI "void \fBmnt1_remote_Mnt_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBmnt1_remote_Dump_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBmnt1_remote_Export_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBmnt1_remote_Null_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBmnt1_remote_Umnt_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBmnt1_remote_UmntAll_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBmnt3_remote_Mnt_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBmnt3_remote_Dump_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBmnt3_remote_Export_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBmnt3_remote_Null_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBmnt3_remote_Umnt_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBmnt3_remote_UmntAll_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Null_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Getattr_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Setattr_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Lookup_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Read_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Write_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Create_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Mkdir_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Symlink_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Remove_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Rmdir_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Rename_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Link_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Fsstat_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Root_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Writecache_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Readdir_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Readlink_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Null_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Getattr_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Setattr_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Lookup_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Access_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Readlink_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Write_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Create_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Mkdir_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Symlink_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Mknod_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Remove_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Rmdir_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Rename_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Link_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Readdir_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Readdirplus_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Fsstat_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Fsinfo_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Pathconf_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Commit_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Read_Free\fP (nfs_res_t *resp)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ganeshell from the source code.
