.TH "NFS protocols functions." 3 "15 Sep 2010" "Version 0.1" "ganeshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NFS protocols functions. \- 
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBnfs2_remote_Null\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Getattr\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Setattr\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Root\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Lookup\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Readlink\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Read\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Writecache\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Write\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Create\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Remove\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Rename\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Link\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Symlink\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Mkdir\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Rmdir\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Readdir\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs2_remote_Fsstat\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Null\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Getattr\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Setattr\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Lookup\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Readlink\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Read\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Write\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Create\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Remove\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Rename\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Link\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Symlink\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Mkdir\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Rmdir\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Readdir\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Fsstat\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Access\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Readdirplus\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Fsinfo\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Pathconf\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Commit\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs3_remote_Mknod\fP (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)"
.br
.ti -1c
.RI "int \fBnfs4_remote_COMPOUND\fP (CLIENT *clnt, COMPOUND4args *parg, COMPOUND4res *pres)"
.br
.ti -1c
.RI "int \fBnfs4_remote_Null\fP (CLIENT *clnt)"
.br
.ti -1c
.RI "void \fBmnt1_remote_Mnt_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBmnt1_remote_Dump_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBmnt1_remote_Export_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBmnt1_remote_Null_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBmnt1_remote_Umnt_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBmnt1_remote_UmntAll_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBmnt3_remote_Mnt_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBmnt3_remote_Dump_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBmnt3_remote_Export_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBmnt3_remote_Null_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBmnt3_remote_Umnt_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBmnt3_remote_UmntAll_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Null_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Getattr_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Setattr_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Lookup_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Read_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Write_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Create_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Mkdir_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Symlink_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Remove_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Rmdir_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Rename_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Link_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Fsstat_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Root_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Writecache_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Readdir_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs2_remote_Readlink_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Null_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Getattr_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Setattr_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Lookup_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Access_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Readlink_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Write_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Create_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Mkdir_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Symlink_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Mknod_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Remove_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Rmdir_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Rename_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Link_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Readdir_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Readdirplus_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Fsstat_Free\fP (nfs_res_t *resp)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Fsinfo_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Pathconf_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Commit_Free\fP (nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBnfs3_remote_Read_Free\fP (nfs_res_t *resp)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void mnt1_remote_Dump_Free (nfs_res_t * pres)"mnt1_remote_Dump_Free: Frees the result structure allocated for mnt1_remote_Dump.
.PP
Frees the result structure allocated for mnt1_remote_Dump.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1495 of file nfs_remote_functions.c.
.SS "void mnt1_remote_Export_Free (nfs_res_t * pres)"mnt1_remote_Export_Free: Frees the result structure allocated for mnt1_remote_Export.
.PP
Frees the result structure allocated for mnt1_remote_Export.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1508 of file nfs_remote_functions.c.
.SS "void mnt1_remote_Mnt_Free (nfs_res_t * pres)"mnt1_remote_Mnt_Free: Frees the result structure allocated for mnt1_remote_Mnt.
.PP
Frees the result structure allocated for mnt1_remote_Mnt.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1482 of file nfs_remote_functions.c.
.SS "void mnt1_remote_Null_Free (nfs_res_t * pres)"mnt1_remote_Null_Free: Frees the result structure allocated for mnt1_remote_Null
.PP
Frees the result structure allocated for mnt1_remote_Null. Does Nothing in fact.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1469 of file nfs_remote_functions.c.
.SS "void mnt1_remote_Umnt_Free (nfs_res_t * pres)"mnt1_remote_Umnt_Free: Frees the result structure allocated for mnt1_remote_Umnt.
.PP
Frees the result structure allocated for mnt1_remote_Umnt.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1521 of file nfs_remote_functions.c.
.SS "void mnt1_remote_UmntAll_Free (nfs_res_t * pres)"mnt1_remote_UmntAll_Free: Frees the result structure allocated for mnt1_remote_UmntAll.
.PP
Frees the result structure allocated for mnt1_remote_UmntAll.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1534 of file nfs_remote_functions.c.
.SS "void mnt3_remote_Dump_Free (nfs_res_t * pres)"mnt3_remote_Dump_Free: Frees the result structure allocated for mnt3_remote_Dump.
.PP
Frees the result structure allocated for mnt3_remote_Dump.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1573 of file nfs_remote_functions.c.
.SS "void mnt3_remote_Export_Free (nfs_res_t * pres)"mnt3_remote_Export_Free: Frees the result structure allocated for mnt3_remote_Export.
.PP
Frees the result structure allocated for mnt3_remote_Export.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1586 of file nfs_remote_functions.c.
.SS "void mnt3_remote_Mnt_Free (nfs_res_t * pres)"mnt3_remote_Mnt_Free: Frees the result structure allocated for mnt3_remote_Mnt.
.PP
Frees the result structure allocated for mnt3_remote_Mnt.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1560 of file nfs_remote_functions.c.
.SS "void mnt3_remote_Null_Free (nfs_res_t * pres)"mnt3_remote_Null_Free: Frees the result structure allocated for mnt3_remote_Null
.PP
Frees the result structure allocated for mnt3_remote_Null. Does Nothing in fact.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1547 of file nfs_remote_functions.c.
.SS "void mnt3_remote_Umnt_Free (nfs_res_t * pres)"mnt3_remote_Umnt_Free: Frees the result structure allocated for mnt3_remote_Umnt.
.PP
Frees the result structure allocated for mnt3_remote_Umnt.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1599 of file nfs_remote_functions.c.
.SS "void mnt3_remote_UmntAll_Free (nfs_res_t * pres)"mnt3_remote_UmntAll_Free: Frees the result structure allocated for mnt3_remote_UmntAll.
.PP
Frees the result structure allocated for mnt3_remote_UmntAll.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1612 of file nfs_remote_functions.c.
.SS "int nfs2_remote_Create (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs2_remote_Create: The NFS proc create function, v2.
.PP
The NFS proc create function, v2.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 615 of file nfs_remote_functions.c.
.SS "void nfs2_remote_Create_Free (nfs_res_t * resp)"nfs2_remote_Create_Free: Frees the result structure allocated for nfs2_remote_Create.
.PP
Frees the result structure allocated for nfs2_remote_Create.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1703 of file nfs_remote_functions.c.
.SS "int nfs2_remote_Fsstat (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs2_remote_Fsstat: The NFS proc statfs function, v2.
.PP
The NFS proc statfs function, v2.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 823 of file nfs_remote_functions.c.
.SS "void nfs2_remote_Fsstat_Free (nfs_res_t * resp)"nfs2_remote_Fsstat_Free: Frees the result structure allocated for nfs2_remote_Fsstat.
.PP
Frees the result structure allocated for nfs2_remote_Fsstat.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1794 of file nfs_remote_functions.c.
.SS "int nfs2_remote_Getattr (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs2_remote_Getattr: The NFS proc getattr function, v2.
.PP
The NFS proc getattr function, v2.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 409 of file nfs_remote_functions.c.
.SS "void nfs2_remote_Getattr_Free (nfs_res_t * resp)"nfs2_remote_Getattr_Free: Frees the result structure allocated for nfs2_remote_Getattr.
.PP
Frees the result structure allocated for nfs2_remote_Getattr.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1638 of file nfs_remote_functions.c.
.SS "int nfs2_remote_Link (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs2_remote_Link: The NFS proc link function, v2.
.PP
The NFS proc link function, v2.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 693 of file nfs_remote_functions.c.
.SS "void nfs2_remote_Link_Free (nfs_res_t * resp)"nfs2_remote_Link_Free: Frees the result structure allocated for nfs2_remote_Link.
.PP
Frees the result structure allocated for nfs2_remote_Link.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1781 of file nfs_remote_functions.c.
.SS "int nfs2_remote_Lookup (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs2_remote_Lookup: The NFS proc lookup function, v2.
.PP
The NFS proc lookup function, v2.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 486 of file nfs_remote_functions.c.
.SS "void nfs2_remote_Lookup_Free (nfs_res_t * resp)"nfs2_remote_Lookup_Free: Frees the result structure allocated for nfs2_remote_Lookup.
.PP
Frees the result structure allocated for nfs2_remote_Lookup.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1664 of file nfs_remote_functions.c.
.SS "int nfs2_remote_Mkdir (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs2_remote_Mkdir: The NFS proc mkdir function, v2.
.PP
The NFS proc mkdir function, v2.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 745 of file nfs_remote_functions.c.
.SS "void nfs2_remote_Mkdir_Free (nfs_res_t * resp)"nfs2_remote_Mkdir_Free: Frees the result structure allocated for nfs2_remote_Mkdir.
.PP
Frees the result structure allocated for nfs2_remote_Mkdir.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1716 of file nfs_remote_functions.c.
.SS "int nfs2_remote_Null (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs2_remote_Null: The NFS proc null function, v2.
.PP
The NFS proc null function, v2.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 384 of file nfs_remote_functions.c.
.SS "void nfs2_remote_Null_Free (nfs_res_t * resp)"nfs2_remote_Null_Free: Frees the result structure allocated for nfs2_remote_Null.
.PP
Frees the result structure allocated for nfs2_remote_Null.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1625 of file nfs_remote_functions.c.
.SS "int nfs2_remote_Read (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs2_remote_Read: The NFS proc read function, v2.
.PP
The NFS proc read function, v2.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 538 of file nfs_remote_functions.c.
.SS "void nfs2_remote_Read_Free (nfs_res_t * resp)"nfs2_remote_Read_Free: Frees the result structure allocated for nfs2_remote_Read.
.PP
Frees the result structure allocated for nfs2_remote_Read.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1677 of file nfs_remote_functions.c.
.SS "int nfs2_remote_Readdir (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs2_remote_Readdir: The NFS proc readdir function, v2.
.PP
The NFS proc readdir function, v2.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 797 of file nfs_remote_functions.c.
.SS "void nfs2_remote_Readdir_Free (nfs_res_t * resp)"nfs2_remote_Readdir_Free: Frees the result structure allocated for nfs2_remote_Readdir.
.PP
Frees the result structure allocated for nfs2_remote_Readdir.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1833 of file nfs_remote_functions.c.
.SS "int nfs2_remote_Readlink (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs2_remote_Readlink: The NFS proc readlink function, v2.
.PP
The NFS proc readlink function, v2.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 512 of file nfs_remote_functions.c.
.SS "void nfs2_remote_Readlink_Free (nfs_res_t * resp)"nfs2_remote_Readlink_Free: Frees the result structure allocated for nfs2_remote_Readlink.
.PP
Frees the result structure allocated for nfs2_remote_Readlink.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1846 of file nfs_remote_functions.c.
.SS "int nfs2_remote_Remove (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs2_remote_Remove: The NFS proc remove function, v2.
.PP
The NFS proc remove function, v2.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 641 of file nfs_remote_functions.c.
.SS "void nfs2_remote_Remove_Free (nfs_res_t * resp)"nfs2_remote_Remove_Free: Frees the result structure allocated for nfs2_remote_Remove.
.PP
Frees the result structure allocated for nfs2_remote_Remove.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1742 of file nfs_remote_functions.c.
.SS "int nfs2_remote_Rename (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs2_remote_Rename: The NFS proc rename function, v2.
.PP
The NFS proc rename function, v2.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 667 of file nfs_remote_functions.c.
.SS "void nfs2_remote_Rename_Free (nfs_res_t * resp)"nfs2_remote_Rename_Free: Frees the result structure allocated for nfs2_remote_Rename.
.PP
Frees the result structure allocated for nfs2_remote_Rename.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1768 of file nfs_remote_functions.c.
.SS "int nfs2_remote_Rmdir (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs2_remote_Rmdir: The NFS proc rmdir function, v2.
.PP
The NFS proc rmdir function, v2.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 771 of file nfs_remote_functions.c.
.SS "void nfs2_remote_Rmdir_Free (nfs_res_t * resp)"nfs2_remote_Rmdir_Free: Frees the result structure allocated for nfs2_remote_Rmdir.
.PP
Frees the result structure allocated for nfs2_remote_Rmdir.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1755 of file nfs_remote_functions.c.
.SS "int nfs2_remote_Root (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs2_remote_Root: The NFS proc root function, v2.
.PP
The NFS proc root function, v2.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 461 of file nfs_remote_functions.c.
.SS "void nfs2_remote_Root_Free (nfs_res_t * pres)"nfs2_remote_Root_Free: Frees the result structure allocated for nfs2_remote_Root.
.PP
Frees the result structure allocated for nfs2_remote_Root.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1807 of file nfs_remote_functions.c.
.SS "int nfs2_remote_Setattr (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs2_remote_Setattr: The NFS proc setattr function, v2.
.PP
The NFS proc setattr function, v2.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 435 of file nfs_remote_functions.c.
.SS "void nfs2_remote_Setattr_Free (nfs_res_t * resp)"nfs2_remote_Setattr_Free: Frees the result structure allocated for nfs2_remote_Setattr.
.PP
Frees the result structure allocated for nfs2_remote_Setattr.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1651 of file nfs_remote_functions.c.
.SS "int nfs2_remote_Symlink (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs2_remote_Symlink: The NFS proc symlink function, v2.
.PP
The NFS proc symlink function, v2.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 719 of file nfs_remote_functions.c.
.SS "void nfs2_remote_Symlink_Free (nfs_res_t * resp)"nfs2_remote_Symlink_Free: Frees the result structure allocated for nfs2_remote_Symlink.
.PP
Frees the result structure allocated for nfs2_remote_Symlink.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1729 of file nfs_remote_functions.c.
.SS "int nfs2_remote_Write (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs2_remote_Write: The NFS proc write function, v2.
.PP
The NFS proc write function, v2.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 589 of file nfs_remote_functions.c.
.SS "void nfs2_remote_Write_Free (nfs_res_t * resp)"nfs2_remote_Write_Free: Frees the result structure allocated for nfs2_remote_Write.
.PP
Frees the result structure allocated for nfs2_remote_Write.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1690 of file nfs_remote_functions.c.
.SS "int nfs2_remote_Writecache (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs2_remote_Writecache: The NFS proc writecache function, v2.
.PP
The NFS proc writecache function, v2.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 564 of file nfs_remote_functions.c.
.SS "void nfs2_remote_Writecache_Free (nfs_res_t * pres)"nfs2_remote_Writecache_Free: Frees the result structure allocated for nfs2_remote_Writecache.
.PP
Frees the result structure allocated for nfs2_remote_Writecache.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1820 of file nfs_remote_functions.c.
.SS "int nfs3_remote_Access (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs3_remote_Access: The NFS proc access function, v3.
.PP
The NFS proc access function, v3.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 1264 of file nfs_remote_functions.c.
.SS "void nfs3_remote_Access_Free (nfs_res_t * pres)"nfs3_remote_Access_Free: Frees the result structure allocated for nfs3_remote_Access.
.PP
Frees the result structure allocated for nfs3_remote_Access.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1911 of file nfs_remote_functions.c.
.SS "int nfs3_remote_Commit (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs3_remote_Commit: The NFS proc commit function, v3.
.PP
The NFS proc commit function, v3.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 1368 of file nfs_remote_functions.c.
.SS "void nfs3_remote_Commit_Free (nfs_res_t * pres)"nfs3_remote_Commit_Free: Frees the result structure allocated for nfs3_remote_Commit.
.PP
Frees the result structure allocated for nfs3_remote_Commit.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 2119 of file nfs_remote_functions.c.
.SS "int nfs3_remote_Create (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs3_remote_Create: The NFS proc create function, v3.
.PP
The NFS proc create function, v3.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 1030 of file nfs_remote_functions.c.
.SS "void nfs3_remote_Create_Free (nfs_res_t * resp)"nfs3_remote_Create_Free: Frees the result structure allocated for nfs3_remote_Create.
.PP
Frees the result structure allocated for nfs3_remote_Create.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1950 of file nfs_remote_functions.c.
.SS "int nfs3_remote_Fsinfo (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs3_remote_Fsinfo: The NFS proc fsinfo function, v3.
.PP
The NFS proc fsinfo function, v3.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 1316 of file nfs_remote_functions.c.
.SS "void nfs3_remote_Fsinfo_Free (nfs_res_t * pres)"nfs3_remote_Fsinfo_Free: Frees the result structure allocated for nfs3_remote_Fsinfo.
.PP
Frees the result structure allocated for nfs3_remote_Fsinfo.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 2093 of file nfs_remote_functions.c.
.SS "int nfs3_remote_Fsstat (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs3_remote_Fsstat: The NFS proc statfs function, v3.
.PP
The NFS proc statfs function, v3.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 1238 of file nfs_remote_functions.c.
.SS "void nfs3_remote_Fsstat_Free (nfs_res_t * resp)"nfs3_remote_Fsstat_Free: Frees the result structure allocated for nfs3_remote_Fsstat.
.PP
Frees the result structure allocated for nfs3_remote_Fsstat.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 2080 of file nfs_remote_functions.c.
.SS "int nfs3_remote_Getattr (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs3_remote_Getattr: The NFS proc getattr function, v3.
.PP
The NFS proc getattr function, v3.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 874 of file nfs_remote_functions.c.
.SS "void nfs3_remote_Getattr_Free (nfs_res_t * resp)"nfs3_remote_Getattr_Free: Frees the result structure allocated for nfs3_remote_Getattr.
.PP
Frees the result structure allocated for nfs3_remote_Getattr.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1872 of file nfs_remote_functions.c.
.SS "int nfs3_remote_Link (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs3_remote_Link: The NFS proc link function, v3.
.PP
The NFS proc link function, v3.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 1108 of file nfs_remote_functions.c.
.SS "void nfs3_remote_Link_Free (nfs_res_t * resp)"nfs3_remote_Link_Free: Frees the result structure allocated for nfs3_remote_Link.
.PP
Frees the result structure allocated for nfs3_remote_Link.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 2041 of file nfs_remote_functions.c.
.SS "int nfs3_remote_Lookup (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs3_remote_Lookup: The NFS proc lookup function, v3.
.PP
The NFS proc lookup function, v3.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 926 of file nfs_remote_functions.c.
.SS "void nfs3_remote_Lookup_Free (nfs_res_t * resp)"nfs3_remote_Lookup_Free: Frees the result structure allocated for nfs3_remote_Lookup.
.PP
Frees the result structure allocated for nfs3_remote_Lookup.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1898 of file nfs_remote_functions.c.
.SS "int nfs3_remote_Mkdir (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs3_remote_Mkdir: The NFS proc mkdir function, v3.
.PP
The NFS proc mkdir function, v3.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 1160 of file nfs_remote_functions.c.
.SS "void nfs3_remote_Mkdir_Free (nfs_res_t * resp)"nfs3_remote_Mkdir_Free: Frees the result structure allocated for nfs3_remote_Mkdir.
.PP
Frees the result structure allocated for nfs3_remote_Mkdir.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1963 of file nfs_remote_functions.c.
.SS "int nfs3_remote_Mknod (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs3_remote_Mknod: The NFS proc mknod function, v3.
.PP
The NFS proc mknod function, v3.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 1394 of file nfs_remote_functions.c.
.SS "void nfs3_remote_Mknod_Free (nfs_res_t * pres)"nfs3_remote_Mknod_Free: Frees the result structure allocated for nfs3_remote_Mknod.
.PP
Frees the result structure allocated for nfs3_remote_Mknod.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1989 of file nfs_remote_functions.c.
.SS "int nfs3_remote_Null (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs3_remote_Null: The NFS proc null function, v3.
.PP
The NFS proc null function, v3.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 849 of file nfs_remote_functions.c.
.SS "void nfs3_remote_Null_Free (nfs_res_t * resp)"nfs3_remote_Null_Free: Frees the result structure allocated for nfs3_remote_Null.
.PP
Frees the result structure allocated for nfs3_remote_Null.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1859 of file nfs_remote_functions.c.
.SS "int nfs3_remote_Pathconf (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs3_remote_Pathconf: The NFS proc pathconf function, v3.
.PP
The NFS proc pathconf function, v3.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 1342 of file nfs_remote_functions.c.
.SS "void nfs3_remote_Pathconf_Free (nfs_res_t * pres)"nfs3_remote_Pathconf_Free: Frees the result structure allocated for nfs3_remote_Pathconf.
.PP
Frees the result structure allocated for nfs3_remote_Pathconf.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 2106 of file nfs_remote_functions.c.
.SS "int nfs3_remote_Read (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs3_remote_Read: The NFS proc read function, v3.
.PP
The NFS proc read function, v3.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 978 of file nfs_remote_functions.c.
.SS "void nfs3_remote_Read_Free (nfs_res_t * resp)"nfs3_remote_Read_Free: Frees the result structure allocated for nfs3_remote_Read.
.PP
Frees the result structure allocated for nfs3_remote_Read.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 2132 of file nfs_remote_functions.c.
.SS "int nfs3_remote_Readdir (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs3_remote_Readdir: The NFS proc readdir function, v3.
.PP
The NFS proc readdir function, v3.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 1212 of file nfs_remote_functions.c.
.SS "void nfs3_remote_Readdir_Free (nfs_res_t * resp)"nfs3_remote_Readdir_Free: Frees the result structure allocated for nfs3_remote_Readdir.
.PP
Frees the result structure allocated for nfs3_remote_Readdir.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 2054 of file nfs_remote_functions.c.
.SS "int nfs3_remote_Readdirplus (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs3_remote_Readdirplus: The NFS proc readdirplus function, v3.
.PP
The NFS proc readdirplus function, v3.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 1290 of file nfs_remote_functions.c.
.SS "void nfs3_remote_Readdirplus_Free (nfs_res_t * resp)"nfs3_remote_Readdirplus_Free: Frees the result structure allocated for nfs3_remote_Readdirplus.
.PP
Frees the result structure allocated for nfs3_remote_Readdirplus.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 2067 of file nfs_remote_functions.c.
.SS "int nfs3_remote_Readlink (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs3_remote_Readlink: The NFS proc readlink function, v3.
.PP
The NFS proc readlink function, v3.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 952 of file nfs_remote_functions.c.
.SS "void nfs3_remote_Readlink_Free (nfs_res_t * resp)"nfs3_remote_Readlink_Free: Frees the result structure allocated for nfs3_remote_Readlink.
.PP
Frees the result structure allocated for nfs3_remote_Readlink.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1924 of file nfs_remote_functions.c.
.SS "int nfs3_remote_Remove (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs3_remote_Remove: The NFS proc remove function, v3.
.PP
The NFS proc remove function, v3.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 1056 of file nfs_remote_functions.c.
.SS "void nfs3_remote_Remove_Free (nfs_res_t * resp)"nfs3_remote_Remove_Free: Frees the result structure allocated for nfs3_remote_Remove.
.PP
Frees the result structure allocated for nfs3_remote_Remove.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 2002 of file nfs_remote_functions.c.
.SS "int nfs3_remote_Rename (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs3_remote_Rename: The NFS proc rename function, v3.
.PP
The NFS proc rename function, v3.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 1082 of file nfs_remote_functions.c.
.SS "void nfs3_remote_Rename_Free (nfs_res_t * resp)"nfs3_remote_Rename_Free: Frees the result structure allocated for nfs3_remote_Rename.
.PP
Frees the result structure allocated for nfs3_remote_Rename.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 2028 of file nfs_remote_functions.c.
.SS "int nfs3_remote_Rmdir (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs3_remote_Rmdir: The NFS proc rmdir function, v3.
.PP
The NFS proc rmdir function, v3.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 1186 of file nfs_remote_functions.c.
.SS "void nfs3_remote_Rmdir_Free (nfs_res_t * resp)"nfs3_remote_Rmdir_Free: Frees the result structure allocated for nfs3_remote_Rmdir.
.PP
Frees the result structure allocated for nfs3_remote_Rmdir.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 2015 of file nfs_remote_functions.c.
.SS "int nfs3_remote_Setattr (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs3_remote_Setattr: The NFS proc setattr function, v3.
.PP
The NFS proc setattr function, v3.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 900 of file nfs_remote_functions.c.
.SS "void nfs3_remote_Setattr_Free (nfs_res_t * resp)"nfs3_remote_Setattr_Free: Frees the result structure allocated for nfs3_remote_Setattr.
.PP
Frees the result structure allocated for nfs3_remote_Setattr.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1885 of file nfs_remote_functions.c.
.SS "int nfs3_remote_Symlink (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs3_remote_Symlink: The NFS proc symlink function, v3.
.PP
The NFS proc symlink function, v3.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 1134 of file nfs_remote_functions.c.
.SS "void nfs3_remote_Symlink_Free (nfs_res_t * resp)"nfs3_remote_Symlink_Free: Frees the result structure allocated for nfs3_remote_Symlink.
.PP
Frees the result structure allocated for nfs3_remote_Symlink.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1976 of file nfs_remote_functions.c.
.SS "int nfs3_remote_Write (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)"nfs3_remote_Write: The NFS proc write function, v3.
.PP
The NFS proc write function, v3.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 1004 of file nfs_remote_functions.c.
.SS "void nfs3_remote_Write_Free (nfs_res_t * resp)"nfs3_remote_Write_Free: Frees the result structure allocated for nfs3_remote_Write.
.PP
Frees the result structure allocated for nfs3_remote_Write.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 1937 of file nfs_remote_functions.c.
.SS "int nfs4_remote_COMPOUND (CLIENT * clnt, COMPOUND4args * parg, COMPOUND4res * pres)"nfs4_remote_COMPOUND: The NFS proc compound function, v4.
.PP
The NFS proc compound function, v4.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.br
\fIparg\fP [IN] 
.br
\fIpres\fP [OUT] 
.RE
.PP

.PP
Definition at line 1443 of file nfs_remote_functions.c.
.SS "int nfs4_remote_Null (CLIENT * clnt)"nfs4_remote_Null: The NFS proc null function, v4.
.PP
The NFS proc null function, v4.
.PP
\fBParameters:\fP
.RS 4
\fIclnt\fP [IN] 
.RE
.PP

.PP
Definition at line 1418 of file nfs_remote_functions.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for ganeshell from the source code.
