.TH "prog_vers_client_def__" 3 "15 Sep 2010" "Version 0.1" "ganeshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
prog_vers_client_def__ \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "CLIENT * \fBclnt\fP"
.br
.ti -1c
.RI "char * \fBhostname\fP"
.br
.ti -1c
.RI "char * \fBproto\fP"
.br
.ti -1c
.RI "int \fBport\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 147 of file commands_NFS_remote.c.
.SH "Member Data Documentation"
.PP 
.SS "CLIENT* \fBprog_vers_client_def__::clnt\fP"
.PP
Definition at line 150 of file commands_NFS_remote.c.
.SS "char* \fBprog_vers_client_def__::hostname\fP"
.PP
Definition at line 151 of file commands_NFS_remote.c.
.SS "char* \fBprog_vers_client_def__::name\fP"
.PP
Definition at line 149 of file commands_NFS_remote.c.
.SS "int \fBprog_vers_client_def__::port\fP"
.PP
Definition at line 153 of file commands_NFS_remote.c.
.SS "char* \fBprog_vers_client_def__::proto\fP"
.PP
Definition at line 152 of file commands_NFS_remote.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for ganeshell from the source code.
