.TH "prog_vers_def__" 3 "31 Mar 2009" "Version 0.1" "ganeshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
prog_vers_def__ \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "u_long \fBprog\fP"
.br
.ti -1c
.RI "u_long \fBvers\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 182 of file commands_NFS_remote.c.
.SH "Member Data Documentation"
.PP 
.SS "char* \fBprog_vers_def__::name\fP"
.PP
Definition at line 183 of file commands_NFS_remote.c.
.SS "u_long \fBprog_vers_def__::prog\fP"
.PP
Definition at line 184 of file commands_NFS_remote.c.
.SS "u_long \fBprog_vers_def__::vers\fP"
.PP
Definition at line 185 of file commands_NFS_remote.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for ganeshell from the source code.
