.TH "shell_vars.h" 3 "15 Sep 2010" "Version 0.1" "ganeshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shell_vars.h \- 
.PP
variables management for the shell.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMAX_VAR_LEN\fP   32"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBis_authorized_varname\fP (char *str)"
.br
.ti -1c
.RI "char * \fBget_var_value\fP (char *varname)"
.br
.ti -1c
.RI "int \fBset_var_value\fP (char *varname, char *var_value)"
.br
.ti -1c
.RI "int \fBfree_var\fP (char *varname)"
.br
.ti -1c
.RI "void \fBprint_varlist\fP (FILE *output, int is_dlen)"
.br
.in -1c
.SH "Detailed Description"
.PP 
variables management for the shell. 

\fBAuthor:\fP
.RS 4
.RE
.PP
\fBAuthor\fP.RS 4
leibovic 
.RE
.PP
\fBDate:\fP
.RS 4
.RE
.PP
\fBDate\fP.RS 4
2005/05/09 12:23:55 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision\fP.RS 4
1.2 
.RE
.PP
\fBLog\fP.RS 4
\fBshell_vars.h\fP,v 
.RE
.PP
Revision 1.2 2005/05/09 12:23:55 leibovic Version 2 of ganeshell.
.PP
Revision 1.1 2004/12/14 09:56:00 leibovic Variables management. 
.PP
Definition in file \fBshell_vars.h\fP.
.SH "Define Documentation"
.PP 
.SS "#define MAX_VAR_LEN   32"
.PP
Definition at line 24 of file shell_vars.h.
.SH "Function Documentation"
.PP 
.SS "int free_var (char * varname)"free the resources used by a variable. 
.PP
Definition at line 288 of file shell_vars.c.
.SS "char* get_var_value (char * varname)"returns the value for a variable, NULL if the variable doesn't exist. 
.PP
Definition at line 254 of file shell_vars.c.
.SS "int is_authorized_varname (char * str)"indicates whether a name is authorized for a variable. A variable name must be in [a-zA-Z0-9._:]* 
.PP
Definition at line 224 of file shell_vars.c.
.SS "void print_varlist (FILE * output, int is_dlen)"print var list. 
.PP
\fBParameters:\fP
.RS 4
\fIis_dlen,:\fP indicates if it prints the length of the data they contain.
.RE
.PP
print var list. 
.PP
Definition at line 121 of file shell_vars.c.
.SS "int set_var_value (char * varname, char * var_value)"set the value for a variable, and create it if necessary. 
.PP
Definition at line 270 of file shell_vars.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for ganeshell from the source code.
