.TH "shell_types.h" 3 "31 Mar 2009" "Version 0.1" "ganeshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shell_types.h \- Internal routines for the shell.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBcommand_def__\fP"
.br
.ti -1c
.RI "struct \fBlayer_def__\fP"
.br
.ti -1c
.RI "struct \fBshell_state__\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBcommand_def__\fP \fBcommand_def_t\fP"
.br
.ti -1c
.RI "typedef struct \fBlayer_def__\fP \fBlayer_def_t\fP"
.br
.ti -1c
.RI "typedef struct \fBshell_state__\fP \fBshell_state_t\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Internal routines for the shell. 

\fBAuthor:\fP
.RS 4
.RE
.PP
\fBAuthor\fP.RS 4
leibovic 
.RE
.PP
\fBDate:\fP
.RS 4
.RE
.PP
\fBDate\fP.RS 4
2005/07/26 12:54:47 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision\fP.RS 4
1.2 
.RE
.PP
\fBLog\fP.RS 4
\fBshell_types.h\fP,v 
.RE
.PP
Revision 1.2 2005/07/26 12:54:47 leibovic Multi-thread shell with synchronisation routines.
.PP
Revision 1.1 2005/05/09 12:23:55 leibovic Version 2 of ganeshell. 
.PP
Definition in file \fBshell_types.h\fP.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBcommand_def__\fP  \fBcommand_def_t\fP"
.PP
command definition 
.SS "typedef struct \fBlayer_def__\fP  \fBlayer_def_t\fP"
.PP
layer definition 
.SS "typedef struct \fBshell_state__\fP  \fBshell_state_t\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for ganeshell from the source code.
