.TH "shell_variable__" 3 "15 Sep 2010" "Version 0.1" "ganeshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shell_variable__ \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBvar_name\fP [MAX_VAR_LEN]"
.br
.ti -1c
.RI "char * \fBvar_value\fP"
.br
.ti -1c
.RI "int \fBdatalen\fP"
.br
.ti -1c
.RI "struct \fBshell_variable__\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBshell_variable__\fP * \fBprev\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 69 of file shell_vars.c.
.SH "Member Data Documentation"
.PP 
.SS "int \fBshell_variable__::datalen\fP"
.PP
Definition at line 73 of file shell_vars.c.
.SS "struct \fBshell_variable__\fP* \fBshell_variable__::next\fP\fC [read]\fP"
.PP
Definition at line 74 of file shell_vars.c.
.SS "struct \fBshell_variable__\fP* \fBshell_variable__::prev\fP\fC [read]\fP"
.PP
Definition at line 75 of file shell_vars.c.
.SS "char \fBshell_variable__::var_name\fP[MAX_VAR_LEN]"
.PP
Definition at line 71 of file shell_vars.c.
.SS "char* \fBshell_variable__::var_value\fP"
.PP
Definition at line 72 of file shell_vars.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for ganeshell from the source code.
