.TH "shell_info__" 3 "15 Sep 2010" "Version 0.1" "ganeshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shell_info__ \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBshell_id\fP"
.br
.ti -1c
.RI "char \fBprompt\fP [32]"
.br
.ti -1c
.RI "char \fBscript_file\fP [128]"
.br
.ti -1c
.RI "pthread_t \fBthread\fP"
.br
.ti -1c
.RI "pthread_attr_t \fBattrs\fP"
.br
.ti -1c
.RI "int \fBstatus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 70 of file main.c.
.SH "Member Data Documentation"
.PP 
.SS "pthread_attr_t \fBshell_info__::attrs\fP"
.PP
Definition at line 79 of file main.c.
.SS "char \fBshell_info__::prompt\fP[32]"
.PP
Definition at line 75 of file main.c.
.SS "char \fBshell_info__::script_file\fP[128]"
.PP
Definition at line 76 of file main.c.
.SS "int \fBshell_info__::shell_id\fP"
.PP
Definition at line 73 of file main.c.
.SS "int \fBshell_info__::status\fP"
.PP
Definition at line 81 of file main.c.
.SS "pthread_t \fBshell_info__::thread\fP"
.PP
Definition at line 78 of file main.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for ganeshell from the source code.
