.TH "shell_attribute__" 3 "31 Mar 2009" "Version 0.1" "ganeshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shell_attribute__ \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cmd_tools.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBattr_name\fP"
.br
.ti -1c
.RI "\fBshell_attr_type_t\fP \fBattr_type\fP"
.br
.ti -1c
.RI "fsal_attrib_mask_t \fBattr_mask\fP"
.br
.ti -1c
.RI "unsigned long int \fBattr_offset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Attribute definition structure. 
.PP
Definition at line 234 of file cmd_tools.h.
.SH "Member Data Documentation"
.PP 
.SS "fsal_attrib_mask_t \fBshell_attribute__::attr_mask\fP"
.PP
Definition at line 238 of file cmd_tools.h.
.SS "char* \fBshell_attribute__::attr_name\fP"
.PP
Definition at line 236 of file cmd_tools.h.
.SS "unsigned long int \fBshell_attribute__::attr_offset\fP"
.PP
Definition at line 239 of file cmd_tools.h.
.SS "\fBshell_attr_type_t\fP \fBshell_attribute__::attr_type\fP"
.PP
Definition at line 237 of file cmd_tools.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ganeshell from the source code.
