.TH "shell_state__" 3 "31 Mar 2009" "Version 0.1" "ganeshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shell_state__ \- 
.SH SYNOPSIS
.br
.PP
\fC#include <shell_types.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FILE * \fBinput_stream\fP"
.br
.ti -1c
.RI "int \fBinteractive\fP"
.br
.ti -1c
.RI "\fBlayer_def_t\fP * \fBlayer\fP"
.br
.ti -1c
.RI "int \fBstatus\fP"
.br
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "int \fBdebug_level\fP"
.br
.ti -1c
.RI "int \fBline\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 60 of file shell_types.h.
.SH "Member Data Documentation"
.PP 
.SS "int \fBshell_state__::debug_level\fP"
.PP
Definition at line 67 of file shell_types.h.
.SS "FILE* \fBshell_state__::input_stream\fP"
.PP
Definition at line 62 of file shell_types.h.
.SS "int \fBshell_state__::interactive\fP"
.PP
Definition at line 63 of file shell_types.h.
.SS "\fBlayer_def_t\fP* \fBshell_state__::layer\fP"
.PP
Definition at line 64 of file shell_types.h.
.SS "int \fBshell_state__::line\fP"
.PP
Definition at line 68 of file shell_types.h.
.SS "int \fBshell_state__::status\fP"
.PP
Definition at line 65 of file shell_types.h.
.SS "int \fBshell_state__::verbose\fP"
.PP
Definition at line 66 of file shell_types.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ganeshell from the source code.
