.TH "todo" 3 "9 Apr 2008" "Version 0.1" "ganeshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List
 
.IP "\fBMember \fBcmdnfs_fattr2\fP(cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct) \fP" 1c
.PP
.PP
.PP
 
.IP "\fBMember \fBcmdnfs_fattr3\fP(cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct) \fP" 1c
.PP
.PP
.PP
 
.IP "\fBMember \fBcmdnfs_mountres3\fP(cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct) \fP" 1c
Convert status to error code
.PP
.PP
 
.IP "\fBMember \fBInitNFSClient\fP(cmdnfs_thr_info_t *p_thr_info) \fP" 1c
No secondary groups support.
.PP
.PP
 
.IP "\fBMember \fBnfs_init\fP(char *filename, int flag_v, FILE *output) \fP" 1c
Are there other things to initialize ?
.PP

