.TH "todo" 3 "31 Mar 2009" "Version 0.1" "ganeshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
 
.IP "\fBMember \fBcmdnfs_fattr2\fP \fP" 1c
.PP
.PP
 
.IP "\fBMember \fBcmdnfs_fattr3\fP \fP" 1c
.PP
.PP
 
.IP "\fBMember \fBcmdnfs_mountres3\fP \fP" 1c
Convert status to error code 
.PP
.PP
 
.IP "\fBMember \fBInitNFSClient\fP \fP" 1c
No secondary groups support. 
.PP
.PP
 
.IP "\fBMember \fBnfs_init\fP \fP" 1c
Are there other things to initialize ? 
.PP

