analyse.c File Reference
Building the syntax tree.
#include `analyse.h`
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
Functions
list_block * config_createlistblock ()
type_block * config_createblock (char *blockname, list_affect *list)
void config_addblock (list_block *list, type_block *block)
list_affect * config_createlistaffect ()
type_affect * config_createaffect (char *varname, char *varval)
void config_adddef (list_affect *list, type_affect *affect)
void config_print_list (FILE *output, list_block *list)
void config_free_list (list_block *list)
Detailed Description
Building the syntax tree.
Author:
Author deniel
Date:
Date 2005/11/28 17:02:31
Version:
Revision 1.5
Build the structure that represents a config file.
Definition in file analyse.c.
Function Documentation
void config_addblock (list_block * list, type_block * block)
Ajout d'un block a une list de blocks
Definition at line 123 of file analyse.c.
References list_block, _type_block_::next, and type_block.
Referenced by yyparse().
void config_adddef (list_affect * list, type_affect * affect)
Ajout d'une definition a une list d'affectations
Definition at line 164 of file analyse.c.
References list_affect, _type_affect_::next, and type_affect.
Referenced by yyparse().
type_affect* config_createaffect (char * varname, char * varval)
Creation d'une definition variable=valeur
Definition at line 149 of file analyse.c.
References MAXSTRLEN, _type_affect_::next, and type_affect.
Referenced by yyparse().
type_block* config_createblock (char * blockname, list_affect * list)
Creation d'un block
Definition at line 109 of file analyse.c.
References list_affect, _type_block_::list_def, MAXSTRLEN, _type_affect_::next, and type_block.
Referenced by yyparse().
list_affect* config_createlistaffect ()
Creation d'une list d'affectations
Definition at line 138 of file analyse.c.
References list_affect.
Referenced by yyparse().
list_block* config_createlistblock ()
Creation d'une list de blocks
Definition at line 98 of file analyse.c.
References list_block.
Referenced by yyparse().
void config_free_list (list_block * list)
config_free_list: libere les ressources utilisees par une liste de blocks.
Definition at line 238 of file analyse.c.
References list_block, _type_block_::next, and type_block.
Referenced by config_Free().
void config_print_list (FILE * output, list_block * list)
Affichage idente du contenu d'une list de blocks.
Definition at line 178 of file analyse.c.
References list_block, _type_block_::list_def, _type_block_::name, _type_affect_::next, _type_block_::next, type_affect, type_block, _type_affect_::varname, and _type_affect_::varvalue.
Referenced by config_Print().