config_parsing.c File Reference
#include `config_parsing.h`
#include `analyse.h`
#include <stdio.h>
#include <errno.h>
#include <string.h>
Classes
struct config_struct_t
Defines
#define STRNCMP strncasecmp
Typedefs
typedef config_struct_t config_struct_t
Functions
int yyparse ()
config_file_t config_ParseFile (char *file_path)
char * config_GetErrorMsg ()
void config_Print (FILE *output, config_file_t config)
void config_Free (config_file_t config)
int config_GetNbBlocks (config_file_t config)
int config_GetBlockIndexByName (config_file_t config, char *block_name)
char * config_GetBlockName (config_file_t config, int block_no)
int config_GetNbKeys (config_file_t config, int block_no)
int config_GetKeyValue (config_file_t config, int block_no, int key_no, char **var_name, char **var_value)
char * config_GetKeyValueByName (config_file_t config, int block_no, char *key_name)
Variables
FILE * yyin
list_block * program_result
char extern_errormsg [1024]
Define Documentation
#define STRNCMP strncasecmp
Definition at line 95 of file config_parsing.c.
Referenced by config_GetBlockIndexByName(), and config_GetKeyValueByName().
Typedef Documentation
typedef struct config_struct_t config_struct_t
Function Documentation
void config_Free (config_file_t config)
config_Free: Free the memory structure that store the configuration.
Definition at line 237 of file config_parsing.c.
References config_free_list(), and config_struct_t::syntax_tree.
Referenced by main().
int config_GetBlockIndexByName (config_file_t config, char * block_name)
config_GetBlockIndexByName: Returns the index of the block with the specified name.
Definition at line 351 of file config_parsing.c.
References config_struct_t::last_item_index, config_struct_t::last_item_ptr, MAXSTRLEN, _type_block_::name, _type_block_::next, STRNCMP, config_struct_t::syntax_tree, and type_block.
char* config_GetBlockName (config_file_t config, int block_no)
config_GetBlockName: Indicates the name of a block (specified with its index).
Definition at line 397 of file config_parsing.c.
References config_struct_t::last_item_ptr, and _type_block_::name.
Referenced by main().
char* config_GetErrorMsg ()
Definition at line 203 of file config_parsing.c.
Referenced by main().
int config_GetKeyValue (config_file_t config, int block_no, int key_no, char ** var_name, char ** var_value)
config_GetKeyValue: Retrieves a key-value peer from the block index and the key index.
Definition at line 453 of file config_parsing.c.
References config_struct_t::last_item_ptr, _type_block_::list_def, _type_affect_::next, type_affect, _type_affect_::varname, and _type_affect_::varvalue.
Referenced by main().
char* config_GetKeyValueByName (config_file_t config, int block_no, char * key_name)
config_GetKeyValueByName: Returns the value of the key with the specified name.
Definition at line 504 of file config_parsing.c.
References config_struct_t::last_item_ptr, _type_block_::list_def, MAXSTRLEN, _type_affect_::next, STRNCMP, type_affect, _type_affect_::varname, and _type_affect_::varvalue.
int config_GetNbBlocks (config_file_t config)
config_GetNbBlocks: Indicates how many blocks are defined into the config file.
Definition at line 258 of file config_parsing.c.
References config_struct_t::cache_nb_items, config_struct_t::last_item_index, config_struct_t::last_item_ptr, _type_block_::next, config_struct_t::syntax_tree, and type_block.
Referenced by main().
int config_GetNbKeys (config_file_t config, int block_no)
config_GetNbKeys: Indicates how many peers (key-value) are defined in a block (specified with its index).
Definition at line 421 of file config_parsing.c.
References config_struct_t::last_item_ptr, _type_block_::list_def, _type_affect_::next, and type_affect.
Referenced by main().
config_file_t config_ParseFile (char * file_path)
Todo : yyparse fait exit en cas d'erreur. Remedier au probleme.
Definition at line 136 of file config_parsing.c.
References config_struct_t::cache_nb_items, extern_errormsg, config_struct_t::last_item_index, config_struct_t::last_item_ptr, config_struct_t::syntax_tree, yyin, and yyparse().
Referenced by main().
void config_Print (FILE * output, config_file_t config)
config_Print: Print the content of the syntax tree to a file.
Definition at line 217 of file config_parsing.c.
References config_print_list().
int yyparse ()
Variable Documentation
char extern_errormsg[1024]
Definition at line 94 of file conf_yacc.c.
Referenced by config_ParseFile(), and yyerror().
list_block* program_result
Definition at line 88 of file conf_yacc.c.
Referenced by yyparse().
FILE* yyin