test_parse.c File Reference
#include `config_parsing.h`
#include <errno.h>
#include <stdio.h>
#include <string.h>
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 83 of file test_parse.c.
References config_Free(), config_GetBlockName(), config_GetErrorMsg(), config_GetKeyValue(), config_GetNbBlocks(), config_GetNbKeys(), and config_ParseFile().