verif_syntax.c File Reference
Construction de l'arbre syntaxique.
#include `config_parsing.h`
#include <errno.h>
#include <stdio.h>
Functions
int main (int argc, char **argv)
Detailed Description
Construction de l'arbre syntaxique.
Author:
Author deniel
Date:
Date 2005/11/28 17:02:31
Version:
Revision 1.4
Teste la syntaxe d'un fichier de configuration.
Definition in file verif_syntax.c.
Function Documentation
int main (int argc, char ** argv)
Definition at line 95 of file verif_syntax.c.
References config_Free(), config_GetErrorMsg(), and config_ParseFile().