.TH "nfs_admin_thread.c" 3 "31 Mar 2009" "Version 0.1" "Daemon Main" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfs_admin_thread.c \- The file that contain the 'admin_thread' routine for the nfsd.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <pthread.h>\fP
.br
\fC#include 'nfs_core.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBadmin_thread\fP (void *IndexArg)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The file that contain the 'admin_thread' routine for the nfsd. 

\fBAuthor:\fP
.RS 4
.RE
.PP
\fBAuthor\fP.RS 4
deniel 
.RE
.PP
\fBDate:\fP
.RS 4
.RE
.PP
\fBDate\fP.RS 4
2006/01/31 10:08:04 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision\fP.RS 4
1.6 
.RE
.PP
\fBnfs_admin_thread.c\fP : The file that contain the 'admin_thread' routine for the nfsd. 
.PP
Definition in file \fBnfs_admin_thread.c\fP.
.SH "Function Documentation"
.PP 
.SS "void* admin_thread (void * IndexArg)"
.PP
Definition at line 102 of file nfs_admin_thread.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Daemon Main from the source code.
