.TH "nfs_main.c" 3 "31 Mar 2009" "Version 0.1" "Daemon Main" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfs_main.c \- The file that contain the 'main' routine for the nfsd.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include 'nfs_init.h'\fP
.br
\fC#include 'fsal.h'\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <pthread.h>\fP
.br
\fC#include <signal.h>\fP
.br
\fC#include <errno.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBnfs_start_info_t\fP \fBmy_nfs_start_info\fP"
.br
.ti -1c
.RI "char \fBmy_config_path\fP [MAXPATHLEN] = '/etc/ganesha/ganesha.conf'"
.br
.ti -1c
.RI "char \fBlog_path\fP [MAXPATHLEN] = '/tmp/nfs-ganesha.log'"
.br
.ti -1c
.RI "char \fBexec_name\fP [MAXPATHLEN] = 'nfs-ganesha'"
.br
.ti -1c
.RI "char \fBhost_name\fP [MAXHOSTNAMELEN] = 'localhost'"
.br
.ti -1c
.RI "int \fBdebug_level\fP = NIV_EVENT"
.br
.ti -1c
.RI "int \fBdetach_flag\fP = FALSE"
.br
.ti -1c
.RI "char \fBganesha_exec_path\fP [MAXPATHLEN]"
.br
.ti -1c
.RI "char \fBoptions\fP [] = 'h@RdS:F:S:P:f:L:N:'"
.br
.ti -1c
.RI "char \fBusage\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
The file that contain the 'main' routine for the nfsd. 

\fBAuthor:\fP
.RS 4
.RE
.PP
\fBAuthor\fP.RS 4
deniel 
.RE
.PP
\fBnfs_main.c\fP : The file that contain the 'main' routine for the nfsd. 
.PP
Definition in file \fBnfs_main.c\fP.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"
.PP
main: simply the main function.
.PP
The 'main' function as in every C program.
.PP
\fBParameters:\fP
.RS 4
\fIargc\fP number of arguments 
.br
\fIargv\fP array of arguments
.RE
.PP
\fBReturns:\fP
.RS 4
status to calling program by calling the exit(3C) function. 
.RE
.PP

.PP
Definition at line 196 of file nfs_main.c.
.SH "Variable Documentation"
.PP 
.SS "int \fBdebug_level\fP = NIV_EVENT"
.PP
Definition at line 116 of file nfs_main.c.
.SS "int \fBdetach_flag\fP = FALSE"
.PP
Definition at line 117 of file nfs_main.c.
.SS "char \fBexec_name\fP[MAXPATHLEN] = 'nfs-ganesha'"
.PP
Definition at line 114 of file nfs_main.c.
.SS "char \fBganesha_exec_path\fP[MAXPATHLEN]"
.PP
Definition at line 118 of file nfs_main.c.
.SS "char \fBhost_name\fP[MAXHOSTNAMELEN] = 'localhost'"
.PP
Definition at line 115 of file nfs_main.c.
.SS "char \fBlog_path\fP[MAXPATHLEN] = '/tmp/nfs-ganesha.log'"
.PP
Definition at line 113 of file nfs_main.c.
.SS "char \fBmy_config_path\fP[MAXPATHLEN] = '/etc/ganesha/ganesha.conf'"
.PP
Definition at line 112 of file nfs_main.c.
.SS "\fBnfs_start_info_t\fP \fBmy_nfs_start_info\fP"
.PP
\fBInitial value:\fP
.PP
.nf

{
   .flush_datacache_mode = FALSE,
   .nb_flush_threads     = 1,
   .flush_behaviour      = CACHE_CONTENT_FLUSH_AND_DELETE,
   .lw_mark_trigger      = FALSE
}
.fi
.PP
Definition at line 104 of file nfs_main.c.
.SS "char \fBoptions\fP[] = 'h@RdS:F:S:P:f:L:N:'"
.PP
Definition at line 124 of file nfs_main.c.
.SS "char \fBusage\fP[]"
.PP
\fBInitial value:\fP
.PP
.nf
 
    'Usage: %s [-hd][-L <logfile>][-N <dbg_lvl>][-f <config_file>]\n'
    '\t[-h]                display this help\n'
    '\t[-L <logfile>]      set the default logfile for the daemon\n'
    '\t[-N <dbg_lvl>]      set the verbosity level\n'
    '\t[-f <config_file>]  set the config file to be used\n'
    '\t[-d]                the daemon starts in background, in a new process group\n'
    '\t[-R]                daemon will manage RPCSEC_GSS (default is no RPCSEC_GSS)\n'
    '\t[-F] <nb_flushers>  flushes the data cache with purge, but do not answer to requests\n'
    '\t[-S] <nb_flushers>  flushes the data cache without purge, but do not answer to requests\n'
    '\t[-P] <nb_flushers>  flushes the data cache with purge until lw mark is reached, then just sync. Do not answer to requests\n'
    '----------------- Signals ----------------\n'
    'SIGUSR1    : Enable/Disable File Content Cache forced flush\n' 
    'SIGTERM    : Cleanly terminate the program\n' 
    '------------- Default Values -------------\n'
    'LogFile    : /tmp/nfs-ganesha.log\n'
    'DebugLevel : NIV_EVENT\n'
    'ConfigFile : /etc/ganesha/ganesha.conf\n'
.fi
.PP
Definition at line 125 of file nfs_main.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Daemon Main from the source code.
