.TH "nfs_stats_thread.c" 3 "9 Apr 2008" "Version 0.1" "Daemon Main" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfs_stats_thread.c \- The file that contain the 'stats_thread' routine for the nfsd. 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <pthread.h>\fP
.br
\fC#include <sys/stat.h>\fP
.br
\fC#include <time.h>\fP
.br
\fC#include 'nfs_core.h'\fP
.br
\fC#include 'nfs_stat.h'\fP
.br
\fC#include 'nfs_exports.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBstats_thread\fP (void *addr)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "nfs_parameter_t \fBnfs_param\fP"
.br
.ti -1c
.RI "time_t \fBServerBootTime\fP"
.br
.ti -1c
.RI "hash_table_t * \fBht_ip_stats\fP [NB_MAX_WORKER_THREAD]"
.br
.in -1c
.SH "Detailed Description"
.PP 
The file that contain the 'stats_thread' routine for the nfsd. 

\fBAuthor:\fP
.RS 4
\fBAuthor\fP.RS 4
deniel 
.RE
.PP
.RE
.PP
\fBDate:\fP
.RS 4
\fBDate\fP.RS 4
2006/02/22 12:01:58 
.RE
.PP
.RE
.PP
\fBVersion:\fP
.RS 4
\fBRevision\fP.RS 4
1.6 
.RE
.PP
.RE
.PP
\fBnfs_stats_thread.c\fP : The file that contain the 'stats_thread' routine for the nfsd.
.PP
Definition in file \fBnfs_stats_thread.c\fP.
.SH "Function Documentation"
.PP 
.SS "void* stats_thread (void * addr)"
.PP
Definition at line 104 of file nfs_stats_thread.c.
.PP
References global_buddy_stat, ht_ip_stats, nfs_dupreq_get_stats(), nfs_param, ServerBootTime, stats_snmp(), and workers_data.
.SH "Variable Documentation"
.PP 
.SS "hash_table_t* \fBht_ip_stats\fP[NB_MAX_WORKER_THREAD]"
.PP
Definition at line 136 of file nfs_init.c.
.PP
Referenced by stats_thread().
.SS "nfs_parameter_t \fBnfs_param\fP"
.PP
Definition at line 130 of file nfs_init.c.
.SS "time_t \fBServerBootTime\fP"
.PP
Definition at line 131 of file nfs_init.c.
.PP
Referenced by nfs_start(), and stats_thread().
.SH "Author"
.PP 
Generated automatically by Doxygen for Daemon Main from the source code.
