/* Copyright (C) 2025, IBM
 * Contributor : Avani Rateria <arateria@redhat.com>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA
 *
 * -------------
 */

syntax = "proto3";

import "nfsProtoUtil.proto";

package nfsService;

// Get the connected client ids
service GetClientId
{
	rpc GetClientIds(nfsProtoUtil.EmptyRequest)
		returns (GetClientIdsResponse);
}

message GetClientIdsResponse
{
	repeated uint64 client_ids = 1; // List of client IDs
}

// Grace related requests

// Get if nfs in grace
service GetNfsGrace
{
	rpc GetGracePeriod(nfsProtoUtil.EmptyRequest)
		returns (GetNfsGraceResponse);
}

message GetNfsGraceResponse
{
	optional bool ingrace = 1; // Whether the system is in grace period
}

// Invoke grace period on the NFS Ganesha
service StartNfsGrace
{
	rpc StartGraceWithEvent(GraceWithEvent) returns (GraceStatus);
}

message GraceWithEvent
{
	int32 Event = 1;
	int32 NodeId = 2;
	string IpAddr = 3;
}

message GraceStatus
{
	bool graceStarted = 1;
	string response_msg = 2;
}

// Get session ids
service GetSessionId
{
	rpc GetSessionIds(nfsProtoUtil.EmptyRequest)
		returns (GetSessionIdsResponse);
}

message GetSessionIdsResponse
{
	repeated string session_ids = 1;
}

/* NFS Admin Services */
service nfsAdmin
{
	/* Shutdown Ganesha */
	rpc ShutdownGanesha(nfsProtoUtil.EmptyRequest)
		returns (nfsProtoUtil.ActionResponse);
	/* Purge Group Ids */
	rpc PurgeGids(nfsProtoUtil.EmptyRequest)
		returns (nfsProtoUtil.ActionResponse);
	/* Purge Netgroups */
	rpc PurgeNetGroups(nfsProtoUtil.EmptyRequest)
		returns (nfsProtoUtil.ActionResponse);
	/* Update open fd limit */
	rpc InitFdLimit(nfsProtoUtil.EmptyRequest)
		returns (nfsProtoUtil.ActionResponse);
	/* Flush idmapper cache */
	rpc PurgeIdmapperCache(nfsProtoUtil.EmptyRequest)
		returns (nfsProtoUtil.ActionResponse);
	/* Flush idmapper negative cache */
	rpc PurgeIdmapperNegativeCache(nfsProtoUtil.EmptyRequest)
		returns (nfsProtoUtil.ActionResponse);
	/* Enable Malloc Trace */
	rpc MallocTrace(MallocTraceRequest)
		returns (nfsProtoUtil.MessageResponse);
	/* Disable Malloc Trace */
	rpc MallocUntrace(nfsProtoUtil.EmptyRequest)
		returns (nfsProtoUtil.MessageResponse);
	/* Enable or Disable Malloc Trim */
	rpc TrimEnableDisable(TrimEnableDisableRequest)
		returns (nfsProtoUtil.ActionResponse);
	/* Call malloc_trim() */
	rpc TrimCall(nfsProtoUtil.EmptyRequest)
		returns (nfsProtoUtil.ActionResponse);
	/* Get Trim Status */
	rpc TrimStatus(nfsProtoUtil.EmptyRequest) returns (TrimStatusResponse);
	/* Re-Read Config */
	rpc ReReadConfig(nfsProtoUtil.EmptyRequest)
		returns (nfsProtoUtil.ActionResponse);
}

message MallocTraceRequest
{
	string filename = 1;
}

message TrimEnableDisableRequest
{
	optional bool enable = 1;
}

message TrimStatusResponse
{
	optional bool enable = 1;
	optional bool success = 2;
}
message IdMapperEntry
{
	string name = 1;
	uint32 uid = 2;
	bool gid_set = 3;
	uint32 gid = 4;
}

message ShowIdMapperResponse
{
	uint64 timestamp_sec = 1;
	uint64 timestamp_nsec = 2;
	repeated IdMapperEntry entries = 3;
}

service ShowIdMapperService
{
	rpc ShowIdMapper(nfsProtoUtil.EmptyRequest)
		returns (ShowIdMapperResponse);
}
