/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "nfs_prot.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

void *
nfsproc_null_2(void *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NFSPROC_NULL,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

attrstat *
nfsproc_getattr_2(nfs_fh *argp, CLIENT *clnt)
{
	static attrstat clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NFSPROC_GETATTR,
		(xdrproc_t) xdr_nfs_fh, (caddr_t) argp,
		(xdrproc_t) xdr_attrstat, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

attrstat *
nfsproc_setattr_2(sattrargs *argp, CLIENT *clnt)
{
	static attrstat clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NFSPROC_SETATTR,
		(xdrproc_t) xdr_sattrargs, (caddr_t) argp,
		(xdrproc_t) xdr_attrstat, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

void *
nfsproc_root_2(void *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NFSPROC_ROOT,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

diropres *
nfsproc_lookup_2(diropargs *argp, CLIENT *clnt)
{
	static diropres clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NFSPROC_LOOKUP,
		(xdrproc_t) xdr_diropargs, (caddr_t) argp,
		(xdrproc_t) xdr_diropres, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

readlinkres *
nfsproc_readlink_2(nfs_fh *argp, CLIENT *clnt)
{
	static readlinkres clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NFSPROC_READLINK,
		(xdrproc_t) xdr_nfs_fh, (caddr_t) argp,
		(xdrproc_t) xdr_readlinkres, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

readres *
nfsproc_read_2(readargs *argp, CLIENT *clnt)
{
	static readres clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NFSPROC_READ,
		(xdrproc_t) xdr_readargs, (caddr_t) argp,
		(xdrproc_t) xdr_readres, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

void *
nfsproc_writecache_2(void *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NFSPROC_WRITECACHE,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

attrstat *
nfsproc_write_2(writeargs *argp, CLIENT *clnt)
{
	static attrstat clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NFSPROC_WRITE,
		(xdrproc_t) xdr_writeargs, (caddr_t) argp,
		(xdrproc_t) xdr_attrstat, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

diropres *
nfsproc_create_2(createargs *argp, CLIENT *clnt)
{
	static diropres clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NFSPROC_CREATE,
		(xdrproc_t) xdr_createargs, (caddr_t) argp,
		(xdrproc_t) xdr_diropres, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

nfsstat *
nfsproc_remove_2(diropargs *argp, CLIENT *clnt)
{
	static nfsstat clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NFSPROC_REMOVE,
		(xdrproc_t) xdr_diropargs, (caddr_t) argp,
		(xdrproc_t) xdr_nfsstat, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

nfsstat *
nfsproc_rename_2(renameargs *argp, CLIENT *clnt)
{
	static nfsstat clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NFSPROC_RENAME,
		(xdrproc_t) xdr_renameargs, (caddr_t) argp,
		(xdrproc_t) xdr_nfsstat, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

nfsstat *
nfsproc_link_2(linkargs *argp, CLIENT *clnt)
{
	static nfsstat clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NFSPROC_LINK,
		(xdrproc_t) xdr_linkargs, (caddr_t) argp,
		(xdrproc_t) xdr_nfsstat, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

nfsstat *
nfsproc_symlink_2(symlinkargs *argp, CLIENT *clnt)
{
	static nfsstat clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NFSPROC_SYMLINK,
		(xdrproc_t) xdr_symlinkargs, (caddr_t) argp,
		(xdrproc_t) xdr_nfsstat, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

diropres *
nfsproc_mkdir_2(createargs *argp, CLIENT *clnt)
{
	static diropres clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NFSPROC_MKDIR,
		(xdrproc_t) xdr_createargs, (caddr_t) argp,
		(xdrproc_t) xdr_diropres, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

nfsstat *
nfsproc_rmdir_2(diropargs *argp, CLIENT *clnt)
{
	static nfsstat clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NFSPROC_RMDIR,
		(xdrproc_t) xdr_diropargs, (caddr_t) argp,
		(xdrproc_t) xdr_nfsstat, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

readdirres *
nfsproc_readdir_2(readdirargs *argp, CLIENT *clnt)
{
	static readdirres clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NFSPROC_READDIR,
		(xdrproc_t) xdr_readdirargs, (caddr_t) argp,
		(xdrproc_t) xdr_readdirres, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

statfsres *
nfsproc_statfs_2(nfs_fh *argp, CLIENT *clnt)
{
	static statfsres clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NFSPROC_STATFS,
		(xdrproc_t) xdr_nfs_fh, (caddr_t) argp,
		(xdrproc_t) xdr_statfsres, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
