.TH "fsal_objectres.c" 3 "9 Apr 2008" "Version 0.2" "File System Abstraction Layer (HPSS) library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fsal_objectres.c \- FSAL remanent resources management routines. 
.SH SYNOPSIS
.br
.PP
\fC#include 'fsal.h'\fP
.br
\fC#include 'fsal_internal.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "fsal_status_t \fBFSAL_CleanObjectResources\fP (fsal_handle_t *in_fsal_handle)"
.br
.in -1c
.SH "Detailed Description"
.PP 
FSAL remanent resources management routines. 

\fBAuthor:\fP
.RS 4
$Author$ 
.RE
.PP
\fBDate:\fP
.RS 4
$Date$ 
.RE
.PP
\fBVersion:\fP
.RS 4
$Revision$ 
.RE
.PP

.PP
Definition in file \fBfsal_objectres.c\fP.
.SH "Function Documentation"
.PP 
.SS "fsal_status_t FSAL_CleanObjectResources (fsal_handle_t * in_fsal_handle)"
.PP
FSAL_CleanObjectResources: This function cleans remanent internal resources that are kept for a given FSAL handle.
.PP
\fBParameters:\fP
.RS 4
\fIin_fsal_handle\fP (input): The handle whose the resources are to be cleaned. 
.RE
.PP

.PP
Definition at line 28 of file fsal_objectres.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for File System Abstraction Layer (HPSS) library from the source code.
