.TH "fsal_rcp.c" 3 "9 Apr 2008" "Version 0.2" "File System Abstraction Layer (HPSS) library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fsal_rcp.c \- Transfer operations. 
.SH SYNOPSIS
.br
.PP
\fC#include 'fsal.h'\fP
.br
\fC#include 'fsal_internal.h'\fP
.br
\fC#include 'fsal_convert.h'\fP
.br
\fC#include 'stuff_alloc.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBRCP_BUFFER_SIZE\fP   1048576"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "fsal_status_t \fBFSAL_rcp\fP (fsal_handle_t *filehandle, fsal_op_context_t *p_context, fsal_path_t *p_local_path, fsal_rcpflag_t transfer_opt)"
.br
.ti -1c
.RI "fsal_status_t \fBFSAL_rcp_by_fileid\fP (fsal_handle_t *filehandle, fsal_u64_t fileid, fsal_op_context_t *p_context, fsal_path_t *p_local_path, fsal_rcpflag_t transfer_opt)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Transfer operations. 

\fBAuthor:\fP
.RS 4
\fBAuthor\fP.RS 4
leibovic 
.RE
.PP
.RE
.PP
\fBDate:\fP
.RS 4
\fBDate\fP.RS 4
2006/01/24 13:45:37 
.RE
.PP
.RE
.PP
\fBVersion:\fP
.RS 4
\fBRevision\fP.RS 4
1.7 
.RE
.PP
.RE
.PP

.PP
Definition in file \fBfsal_rcp.c\fP.
.SH "Function Documentation"
.PP 
.SS "fsal_status_t FSAL_rcp (fsal_handle_t * filehandle, fsal_op_context_t * p_context, fsal_path_t * p_local_path, fsal_rcpflag_t transfer_opt)"
.PP
FSAL_rcp: Copy an HPSS file to/from a local filesystem.
.PP
\fBParameters:\fP
.RS 4
\fIfilehandle\fP (input): Handle of the HPSS file to be copied. 
.br
\fIp_context\fP (input): Authentication context for the operation (user,...). 
.br
\fIp_local_path\fP (input): Path of the file in the local filesystem. 
.br
\fItransfer_opt\fP (input): Flags that indicate transfer direction and options. This consists of an inclusive OR between the following values :
.IP "\(bu" 2
FSAL_RCP_FS_TO_LOCAL: Copy the file from the filesystem to a local path.
.IP "\(bu" 2
FSAL_RCP_LOCAL_TO_FS: Copy the file from local path to the filesystem.
.IP "\(bu" 2
FSAL_RCP_LOCAL_CREAT: Create the target local file if it doesn't exist.
.IP "\(bu" 2
FSAL_RCP_LOCAL_EXCL: Produce an error if the target local file already exists.
.PP
.RE
.PP
\fBReturns:\fP
.RS 4
Major error codes :
.IP "\(bu" 2
ERR_FSAL_NO_ERROR (no error)
.IP "\(bu" 2
ERR_FSAL_ACCESS (user doesn't have the permissions for opening the file)
.IP "\(bu" 2
ERR_FSAL_STALE (filehandle does not address an existing object)
.IP "\(bu" 2
ERR_FSAL_INVAL (filehandle does not address a regular file, or tranfert options are conflicting)
.IP "\(bu" 2
ERR_FSAL_FAULT (a NULL pointer was passed as mandatory argument)
.IP "\(bu" 2
Other error codes can be returned : ERR_FSAL_IO, ERR_FSAL_NOSPC, ERR_FSAL_DQUOT... 
.PP
.RE
.PP

.PP
Definition at line 58 of file fsal_rcp.c.
.PP
References FSAL_close(), FSAL_open(), FSAL_read(), FSAL_write(), and hpss2fsal_error().
.SH "Author"
.PP 
Generated automatically by Doxygen for File System Abstraction Layer (HPSS) library from the source code.
