.TH "fsal_stats.c" 3 "9 Apr 2008" "Version 0.2" "File System Abstraction Layer (HPSS) library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fsal_stats.c \- Statistics functions. 
.SH SYNOPSIS
.br
.PP
\fC#include 'fsal.h'\fP
.br
\fC#include 'fsal_internal.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBFSAL_get_stats\fP (fsal_statistics_t *stats, fsal_boolean_t reset)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Statistics functions. 

\fBAuthor:\fP
.RS 4
\fBAuthor\fP.RS 4
leibovic 
.RE
.PP
.RE
.PP
\fBDate:\fP
.RS 4
\fBDate\fP.RS 4
2005/07/27 13:30:26 
.RE
.PP
.RE
.PP
\fBVersion:\fP
.RS 4
\fBRevision\fP.RS 4
1.2 
.RE
.PP
.RE
.PP

.PP
Definition in file \fBfsal_stats.c\fP.
.SH "Function Documentation"
.PP 
.SS "void FSAL_get_stats (fsal_statistics_t * stats, fsal_boolean_t reset)"
.PP
FSAL_get_stats: Retrieve call statistics for current thread.
.PP
\fBParameters:\fP
.RS 4
\fIstats\fP (output): Pointer to the call statistics structure. 
.br
\fIreset\fP (input): Boolean that indicates if the stats must be reset.
.RE
.PP
\fBReturns:\fP
.RS 4
Nothing. 
.RE
.PP

.PP
Definition at line 34 of file fsal_stats.c.
.PP
References fsal_internal_getstats().
.SH "Author"
.PP 
Generated automatically by Doxygen for File System Abstraction Layer (HPSS) library from the source code.
