.TH "fsal_lock.c" 3 "31 Mar 2009" "Version 0.2" "File System Abstraction Layer (HPSS) library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fsal_lock.c \- Locking operations.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include 'fsal.h'\fP
.br
\fC#include 'fsal_internal.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "fsal_status_t \fBFSAL_lock\fP (fsal_handle_t *objecthandle, fsal_op_context_t *p_context, fsal_lockparam_t *lock_info, fsal_lockdesc_t *lock_descriptor)"
.br
.ti -1c
.RI "fsal_status_t \fBFSAL_changelock\fP (fsal_lockdesc_t *lock_descriptor, fsal_lockparam_t *lock_info)"
.br
.ti -1c
.RI "fsal_status_t \fBFSAL_unlock\fP (fsal_lockdesc_t *lock_descriptor)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Locking operations. 

\fBAuthor:\fP
.RS 4
.RE
.PP
\fBAuthor\fP.RS 4
leibovic 
.RE
.PP
\fBDate:\fP
.RS 4
.RE
.PP
\fBDate\fP.RS 4
2005/07/27 13:30:26 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision\fP.RS 4
1.2 
.RE
.PP

.PP
Definition in file \fBfsal_lock.c\fP.
.SH "Function Documentation"
.PP 
.SS "fsal_status_t FSAL_changelock (fsal_lockdesc_t * lock_descriptor, fsal_lockparam_t * lock_info)"
.PP
FSAL_changelock: Not implemented. 
.PP
Definition at line 56 of file fsal_lock.c.
.SS "fsal_status_t FSAL_lock (fsal_handle_t * objecthandle, fsal_op_context_t * p_context, fsal_lockparam_t * lock_info, fsal_lockdesc_t * lock_descriptor)"
.PP
FSAL_lock: Lock an entry in the filesystem.
.PP
\fBParameters:\fP
.RS 4
\fIobjecthandle\fP (input): Handle of the object to be locked. 
.br
\fIp_context\fP (input): Authentication context for the operation (user, export...). 
.br
\fItypelock\fP (input): Type of lock to be taken 
.br
\fIlock_descriptor\fP (output): The returned lock descriptor 
.RE
.PP

.PP
Definition at line 36 of file fsal_lock.c.
.SS "fsal_status_t FSAL_unlock (fsal_lockdesc_t * lock_descriptor)"
.PP
FSAL_unlock: Not implemented. 
.PP
Definition at line 74 of file fsal_lock.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for File System Abstraction Layer (HPSS) library from the source code.
