.TH "todo" 3 "15 Sep 2010" "Version 0.2" "File System Abstraction Layer (HPSS) library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
 
.IP "\fBMember \fBfsal2hpss_attribset\fP \fP" 1c
: Define some constants for settable and supported attributes. 
.PP
ACL management 
.PP
.PP
 
.IP "\fBMember \fBfsal_is_retryable\fP \fP" 1c
: ERR_FSAL_DELAY : The only retryable error ? 
.PP
.PP
 
.IP "\fBMember \fBhpss2fsal_attributes\fP \fP" 1c
: This doesn't convert ACLs for the moment. 
.PP
.PP
 
.IP "\fBMember \fBhpss2fsal_error\fP \fP" 1c
: The EBADF error also happens when file is opened for reading, and we try writting in it. In this case, we return ERR_FSAL_NOT_OPENED, but it doesn't seems to be a correct error translation. 
.PP
.PP
 
.IP "\fBMember \fBHPSSFSAL_lookupPath\fP \fP" 1c
: Be carefull about junction crossing, symlinks, hardlinks,... 
.PP
.PP
 
.IP "\fBMember \fBHPSSFSAL_read\fP \fP" 1c
: manage fsal_size_t to size_t convertion 
.PP
: manage ssize_t to fsal_size_t convertion 
.PP
.PP
 
.IP "\fBMember \fBHPSSFSAL_readdir\fP \fP" 1c
: does handle provide mounted_on_fileid ? 
.PP
: test returned status 
.PP
.PP
 
.IP "\fBMember \fBHPSSFSAL_setattrs\fP \fP" 1c
: chown restricted seems to be OK. 
.PP
voir pourquoi hpss_fattr_out ne contient pas ce qu'il devrait contenir 
.PP
.PP
 
.IP "\fBMember \fBHPSSFSAL_test_access\fP \fP" 1c
: test that needed attributes are in the structure 
.PP
: ACLs. 
.PP
.PP
 
.IP "\fBMember \fBHPSSFSAL_write\fP \fP" 1c
: manage fsal_size_t to size_t convertion 
.PP
: manage ssize_t to fsal_size_t convertion 
.PP

