fsal_fsinfo.c File Reference
functions for retrieving filesystem info.
#include `fsal.h`
#include `fsal_internal.h`
#include `fsal_convert.h`
#include <sys/statvfs.h>
Functions
fsal_status_t POSIXFSAL_static_fsinfo (posixfsal_handle_t *p_filehandle, posixfsal_op_context_t *p_context, fsal_staticfsinfo_t *p_staticinfo)
fsal_status_t POSIXFSAL_dynamic_fsinfo (posixfsal_handle_t *p_filehandle, posixfsal_op_context_t *p_context, fsal_dynamicfsinfo_t *p_dynamicinfo)
Detailed Description
functions for retrieving filesystem info.
Author
Author
leibovic
Date
Date
2006/01/17 14:20:07
Version
Revision
1.7
Definition in file fsal_fsinfo.c.
Function Documentation
fsal_status_t POSIXFSAL_dynamic_fsinfo (posixfsal_handle_t * p_filehandle, posixfsal_op_context_t * p_context, fsal_dynamicfsinfo_t * p_dynamicinfo)
FSAL_dynamic_fsinfo: Return dynamic filesystem info such as used size, free size, number of objects...
Parameters
filehandle (input): Handle of an object in the filesystem whom info is to be retrieved.
cred (input): Authentication context for the operation (user,...).
dynamicinfo (output): Pointer to the static info of the filesystem.
Returns
Major error codes:
ERR_FSAL_NO_ERROR: no error.
ERR_FSAL_FAULT: NULL pointer passed as input parameter.
ERR_FSAL_SERVERFAULT: Unexpected error.
Definition at line 75 of file fsal_fsinfo.c.
References fsal_internal_getPathFromHandle(), posix2fsal_error(), and TakeTokenFSCall().
fsal_status_t POSIXFSAL_static_fsinfo (posixfsal_handle_t * p_filehandle, posixfsal_op_context_t * p_context, fsal_staticfsinfo_t * p_staticinfo)
FSAL_static_fsinfo: Return static filesystem info such as behavior, configuration, supported operations...
Parameters
filehandle (input): Handle of an object in the filesystem whom info is to be retrieved.
cred (input): Authentication context for the operation (user,...).
staticinfo (output): Pointer to the static info of the filesystem.
Returns
Major error codes:
ERR_FSAL_NO_ERROR: no error.
ERR_FSAL_FAULT: NULL pointer passed as input parameter.
ERR_FSAL_SERVERFAULT: Unexpected error.
Definition at line 41 of file fsal_fsinfo.c.