fsal_internal.c File Reference
Defines the datas that are to be accessed as extern by the fsal modules.
#include `fsal.h`
#include `fsal_internal.h`
#include `posixdb_consistency.h`
#include `stuff_alloc.h`
#include `SemN.h`
#include `fsal_convert.h`
#include <libgen.h>
#include <pthread.h>
#include <string.h>
Defines
#define FSAL_INTERNAL_C
#define SET_INTEGER_PARAM(cfg, p_init_info, _field)
#define SET_BITMAP_PARAM(cfg, p_init_info, _field)
#define SET_BOOLEAN_PARAM(cfg, p_init_info, _field)
Functions
void fsal_increment_nbcall (int function_index, fsal_status_t status)
void fsal_internal_getstats (fsal_statistics_t *output_stats)
void fsal_internal_SetCredentialLifetime (fsal_uint_t lifetime_in)
void TakeTokenFSCall ()
void ReleaseTokenFSCall ()
fsal_status_t fsal_internal_init_global (fsal_init_info_t *fsal_info, fs_common_initinfo_t *fs_common_info, fs_specific_initinfo_t *fs_specific_info)
fsal_status_t fsal_internal_posix2posixdb_fileinfo (struct stat *buffstat, fsal_posixdb_fileinfo_t *info)
convert 'struct stat' to 'fsal_posixdb_fileinfo_t'
fsal_status_t fsal_internal_posixdb_add_entry (fsal_posixdb_conn *p_conn, fsal_name_t *p_filename, fsal_posixdb_fileinfo_t *p_info, fsal_handle_t *p_dir_handle, fsal_handle_t *p_new_handle)
fsal_status_t fsal_internal_appendFSALNameToFSALPath (fsal_path_t *p_path, fsal_name_t *p_name)
p_path <- p_path + '/' + p_name
fsal_status_t fsal_internal_getPathFromHandle (fsal_op_context_t *p_context, fsal_handle_t *p_handle, int is_dir, fsal_path_t *p_fsalpath, struct stat *p_buffstat)
fsal_status_t fsal_internal_getInfoFromName (fsal_op_context_t *p_context, fsal_handle_t *p_parent_dir_handle, fsal_name_t *p_fsalname, fsal_posixdb_fileinfo_t *p_infofs, fsal_handle_t *p_object_handle)
Get the handle of a file, knowing its name and its parent dir.
fsal_status_t fsal_internal_getInfoFromChildrenList (fsal_op_context_t *p_context, fsal_handle_t *p_parent_dir_handle, fsal_name_t *p_fsalname, fsal_posixdb_fileinfo_t *p_infofs, fsal_posixdb_child *p_children, unsigned int children_count, fsal_handle_t *p_object_handle)
Get the handle of a file from a fsal_posixdb_child array, knowing its name.
fsal_status_t fsal_internal_testAccess (fsal_op_context_t *p_context, fsal_accessflags_t access_type, struct stat *p_buffstat, fsal_attrib_list_t *p_object_attributes)
Variables
fsal_uint_t CredentialLifetime = 3600
fsal_staticfsinfo_t global_fs_info
fsal_posixdb_conn_params_t global_posixdb_params
log_t fsal_log
semaphore_t sem_fs_calls
Detailed Description
Defines the datas that are to be accessed as extern by the fsal modules.
Author:
Author leibovic
Date:
Date 2006/01/17 14:20:07
Version:
Revision 1.24
Definition in file fsal_internal.c.
Define Documentation
#define SET_BITMAP_PARAM(cfg, p_init_info, _field)
Value:
switch( (p_init_info)->behaviors._field ){                    \
    case FSAL_INIT_FORCE_VALUE :                                  \
        /* force the value in any case */                         \
        cfg._field = (p_init_info)->values._field;                \
        break;                                                    \
    case FSAL_INIT_MAX_LIMIT :                                    \
      /* proceed a bit AND */                                     \
      cfg._field &= (p_init_info)->values._field ;                \
      break;                                                      \
    case FSAL_INIT_MIN_LIMIT :                                    \
      /* proceed a bit OR */                                      \
      cfg._field |= (p_init_info)->values._field ;                \
      break;                                                      \
    /* In the other cases, we keep the default value. */          \
    }
Definition at line 293 of file fsal_internal.c.
#define SET_BOOLEAN_PARAM(cfg, p_init_info, _field)
Value:
switch( (p_init_info)->behaviors._field ){                    \
    case FSAL_INIT_FORCE_VALUE :                                  \
        /* force the value in any case */                         \
        cfg._field = (p_init_info)->values._field;                \
        break;                                                    \
    case FSAL_INIT_MAX_LIMIT :                                    \
      /* proceed a boolean AND */                                 \
      cfg._field = cfg._field && (p_init_info)->values._field ;   \
      break;                                                      \
    case FSAL_INIT_MIN_LIMIT :                                    \
      /* proceed a boolean OR */                                  \
      cfg._field = cfg._field && (p_init_info)->values._field ;   \
      break;                                                      \
    /* In the other cases, we keep the default value. */          \
    }
Definition at line 311 of file fsal_internal.c.
#define SET_INTEGER_PARAM(cfg, p_init_info, _field)
Value:
switch( (p_init_info)->behaviors._field ){                    \
    case FSAL_INIT_FORCE_VALUE :                                  \
      /* force the value in any case */                           \
      cfg._field = (p_init_info)->values._field;                  \
      break;                                                      \
    case FSAL_INIT_MAX_LIMIT :                                    \
      /* check the higher limit */                                \
      if ( cfg._field > (p_init_info)->values._field )            \
        cfg._field = (p_init_info)->values._field ;               \
      break;                                                      \
    case FSAL_INIT_MIN_LIMIT :                                    \
      /* check the lower limit */                                 \
      if ( cfg._field < (p_init_info)->values._field )            \
        cfg._field = (p_init_info)->values._field ;               \
      break;                                                      \
    /* In the other cases, we keep the default value. */          \
    }
Definition at line 273 of file fsal_internal.c.
Function Documentation
void fsal_increment_nbcall (int function_index, fsal_status_t status)
fsal_increment_nbcall: Updates fonction call statistics.
Parameters:
function_index (input): Index of the function whom number of call is to be incremented.
status (input): Status the function returned.
Returns: Nothing.
Definition at line 107 of file fsal_internal.c.
References fsal_is_retryable().
fsal_status_t fsal_internal_appendFSALNameToFSALPath (fsal_path_t * p_path, fsal_name_t * p_name)
p_path <- p_path + '/' + p_name
Parameters:
p_path
p_name
Returns:
Definition at line 515 of file fsal_internal.c.
Referenced by FSAL_create(), FSAL_link(), FSAL_lookup(), FSAL_mkdir(), FSAL_mknode(), FSAL_readdir(), FSAL_rename(), FSAL_symlink(), and FSAL_unlink().
fsal_status_t fsal_internal_getInfoFromChildrenList (fsal_op_context_t * p_context, fsal_handle_t * p_parent_dir_handle, fsal_name_t * p_fsalname, fsal_posixdb_fileinfo_t * p_infofs, fsal_posixdb_child * p_children, unsigned int children_count, fsal_handle_t * p_object_handle)
Get the handle of a file from a fsal_posixdb_child array, knowing its name.
Parameters:
p_context
p_parent_dir_handle Handle of the parent directory
p_fsalname Name of the object
p_infofs Information about the file (taken from the filesystem) to be compared to information stored in database
p_children fsal_posixdb_child array (that contains the entries of the directory stored in the db)
p_object_handle Handle of the file.
Returns: ERR_FSAL_NOERR, if no error Anothere error code else.
Definition at line 714 of file fsal_internal.c.
References FSAL_namecmp(), and posixdb2fsal_error().
Referenced by FSAL_readdir().
fsal_status_t fsal_internal_getInfoFromName (fsal_op_context_t * p_context, fsal_handle_t * p_parent_dir_handle, fsal_name_t * p_fsalname, fsal_posixdb_fileinfo_t * p_infofs, fsal_handle_t * p_object_handle)
Get the handle of a file, knowing its name and its parent dir.
Parameters:
p_context
p_parent_dir_handle Handle of the parent directory
p_fsalname Name of the object
p_infofs Information about the file (taken from the filesystem) to be compared to information stored in database
p_object_handle Handle of the file.
Returns: ERR_FSAL_NOERR, if no error Anothere error code else.
Definition at line 649 of file fsal_internal.c.
References posixdb2fsal_error().
Referenced by FSAL_lookup(), and FSAL_readdir().
fsal_status_t fsal_internal_getPathFromHandle (fsal_op_context_t * p_context, fsal_handle_t * p_handle, int is_dir, fsal_path_t * p_fsalpath, struct stat * p_buffstat)
Get a valid path associated to an handle. The function selects many paths from the DB and return the first valid one. If is_dir is set, then only 1 path will be constructed from the database.
Definition at line 545 of file fsal_internal.c.
References fsal_internal_posix2posixdb_fileinfo(), FSAL_lookupPath(), FSAL_pathcpy(), FSAL_str2name(), FSAL_str2path(), posixdb2fsal_error(), and TakeTokenFSCall().
Referenced by FSAL_create(), FSAL_dynamic_fsinfo(), FSAL_getattrs(), FSAL_link(), FSAL_lookup(), FSAL_mkdir(), FSAL_mknode(), FSAL_open(), FSAL_opendir(), FSAL_readlink(), FSAL_rename(), FSAL_setattrs(), FSAL_symlink(), FSAL_truncate(), and FSAL_unlink().
void fsal_internal_getstats (fsal_statistics_t * output_stats)
fsal_internal_getstats: (For internal use in the FSAL). Retrieve call statistics for current thread.
Parameters:
output_stats (output): Pointer to the call statistics structure.
Returns: Nothing.
Definition at line 186 of file fsal_internal.c.
Referenced by FSAL_get_stats().
fsal_status_t fsal_internal_posix2posixdb_fileinfo (struct stat * buffstat, fsal_posixdb_fileinfo_t * info)
convert 'struct stat' to 'fsal_posixdb_fileinfo_t'
Parameters:
buffstat
info
Returns:
Definition at line 464 of file fsal_internal.c.
References posix2fsal_type().
Referenced by FSAL_create(), fsal_internal_getPathFromHandle(), FSAL_link(), FSAL_lookup(), FSAL_mkdir(), FSAL_mknode(), FSAL_readdir(), FSAL_rename(), FSAL_symlink(), and FSAL_unlink().
void fsal_internal_SetCredentialLifetime (fsal_uint_t lifetime_in)
Set credential lifetime. (For internal use in the FSAL). Set the period for thread's credential renewal.
Parameters:
lifetime_in (input): The period for thread's credential renewal.
Returns: Nothing.
Definition at line 241 of file fsal_internal.c.
void TakeTokenFSCall ()
Used to limit the number of simultaneous calls to Filesystem.
Definition at line 250 of file fsal_internal.c.
Referenced by FSAL_close(), FSAL_create(), FSAL_dynamic_fsinfo(), fsal_internal_getPathFromHandle(), FSAL_link(), FSAL_lookup(), FSAL_mkdir(), FSAL_mknode(), FSAL_open(), FSAL_opendir(), FSAL_read(), FSAL_readdir(), FSAL_readlink(), FSAL_rename(), FSAL_setattrs(), FSAL_symlink(), FSAL_truncate(), FSAL_unlink(), and FSAL_write().