cmd_nfstools.h File Reference
nfs tools for ganeshell.
#include <rpc/rpc.h>
#include <rpc/auth.h>
#include `nfs_proto_functions.h`
#include `nfs_remote_functions.h`
Classes
struct cmdnfs_funcdesc__
struct cmdnfsremote_funcdesc__
Typedefs
typedef enum cmdnfs_encodetype__ cmdnfs_encodetype_t
typedef int(* cmdnfs_encoding_func_t)(cmdnfs_encodetype_t, int, char **, int, FILE *, caddr_t)
typedef cmdnfs_funcdesc__ cmdnfs_funcdesc_t
typedef cmdnfsremote_funcdesc__ cmdnfsremote_funcdesc_t
Enumerations
enum cmdnfs_encodetype__ { CMDNFS_ENCODE = 1,
CMDNFS_DECODE = 2,
CMDNFS_FREE = 3
 }
Functions
int cmdnfs_void (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_dirpath (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_fhstatus2 (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_fhandle2 (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_mountlist (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_exports (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_mountres3 (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_fhandle3 (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_fattr2 (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_ATTR2res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_DIROP2res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_diropargs2 (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_nfsstat2 (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_READLINK2res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_sattr2 (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_CREATE2args (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_SETATTR2args (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_READDIR2args (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_READDIR2res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_nfsstat3 (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_fattr3 (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_sattr3 (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_GETATTR3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_postopattr (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_postopfh3 (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_diropargs3 (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_LOOKUP3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_READDIR3args (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_READDIR3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_READDIRPLUS3args (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_READDIRPLUS3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_READLINK3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_FSSTAT3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_ACCESS3args (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_ACCESS3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_CREATE3args (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_CREATE3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_MKDIR3args (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_MKDIR3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_REMOVE3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_RMDIR3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_SETATTR3args (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_SETATTR3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_RENAME3args (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_RENAME3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_LINK3args (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_LINK3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_SYMLINK3args (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_SYMLINK3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_FSINFO3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_PATHCONF3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_RENAME2args (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_STATFS2res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
void print_nfsitem_line (FILE *out, fattr3 *attrib, char *name, char *target)
void print_nfs_attributes (fattr3 *attrs, FILE *output)
Detailed Description
nfs tools for ganeshell.
Author:
Author leibovic
Date:
Date 2006/01/18 17:03:35
Version:
Revision 1.22
Log cmd_nfstools.h(p.),v
Revision 1.22 2006/01/18 17:03:35 leibovic Removing some warnings.
Revision 1.21 2006/01/18 08:02:04 deniel Order in includes and libraries
Revision 1.20 2006/01/18 07:29:11 leibovic Fixing bugs about exportlists.
Revision 1.19 2005/10/12 11:30:10 leibovic NFSv2.
Revision 1.18 2005/10/10 12:39:08 leibovic Using mnt/nfs free functions.
Revision 1.17 2005/10/07 08:30:43 leibovic nfs2_rename + New FSAL init functions.
Revision 1.16 2005/09/30 14:30:43 leibovic Adding nfs2_readdir commqnd.
Revision 1.15 2005/09/30 06:56:55 leibovic Adding nfs2_setattr command.
Revision 1.14 2005/09/30 06:46:00 leibovic New create2 and mkdir2 args format.
Revision 1.13 2005/09/07 14:08:22 leibovic Adding NFS3_pathconf command.
Revision 1.12 2005/08/30 13:22:26 leibovic Addind nfs3_fsinfo et nfs3_pathconf functions.
Revision 1.11 2005/08/10 14:55:05 leibovic NFS support of setattr, rename, link, symlink.
Revision 1.10 2005/08/10 10:57:17 leibovic Adding removal functions.
Revision 1.9 2005/08/09 14:52:57 leibovic Addinf create and mkdir commands.
Revision 1.8 2005/08/08 11:42:49 leibovic Adding some stardard unix calls through NFS (ls, cd, pwd).
Revision 1.7 2005/08/05 15:17:56 leibovic Adding mount and pwd commands for browsing.
Revision 1.6 2005/08/05 10:42:38 leibovic Adding readdirplus.
Revision 1.5 2005/08/05 07:59:07 leibovic some nfs3 commands added.
Revision 1.4 2005/08/04 06:57:41 leibovic some NFSv2 commands are completed.
Revision 1.3 2005/08/03 12:51:16 leibovic MNT3 protocol OK.
Revision 1.2 2005/08/03 11:51:10 leibovic MNT1 protocol OK.
Revision 1.1 2005/08/03 08:16:23 leibovic Adding nfs layer structures.
Definition in file cmd_nfstools.h.
Typedef Documentation
typedef enum cmdnfs_encodetype__ cmdnfs_encodetype_t
typedef int(* cmdnfs_encoding_func_t)(cmdnfs_encodetype_t,int, char **,int, FILE *,caddr_t)
Definition at line 104 of file cmd_nfstools.h.
typedef struct cmdnfs_funcdesc__ cmdnfs_funcdesc_t
Referenced by fn_MNT1_command(), fn_MNT3_command(), fn_NFS2_command(), and fn_NFS3_command().
typedef struct cmdnfsremote_funcdesc__ cmdnfsremote_funcdesc_t
Referenced by fn_MNT1_remote_command(), fn_MNT3_remote_command(), fn_NFS2_remote_command(), and fn_NFS3_remote_command().
Enumeration Type Documentation
enum cmdnfs_encodetype__
Enumeration values:
CMDNFS_ENCODE
CMDNFS_DECODE
CMDNFS_FREE
Definition at line 94 of file cmd_nfstools.h.
Function Documentation
int cmdnfs_ACCESS3args (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 2833 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, cmdnfs_fhandle3(), CMDNFS_FREE, and NULL.
int cmdnfs_ACCESS3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 2909 of file cmd_nfstools.c.
References ACCESS3_FAIL_ATTRS, ACCESS3_OK_ACCESS, ACCESS3_OK_ATTRS, CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_postopattr(), and NULL.
int cmdnfs_ATTR2res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 821 of file cmd_nfstools.c.
References ATTR2_ATTRIBUTES, CMDNFS_DECODE, CMDNFS_ENCODE, cmdnfs_fattr2(), CMDNFS_FREE, cmdnfs_nfsstat2(), and NULL.
int cmdnfs_CREATE2args (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 1237 of file cmd_nfstools.c.
References CMDNFS_DECODE, cmdnfs_diropargs2(), CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_sattr2(), and NULL.
int cmdnfs_CREATE3args (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 2993 of file cmd_nfstools.c.
References CMDNFS_DECODE, cmdnfs_diropargs3(), CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_sattr3(), and NULL.
int cmdnfs_CREATE3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 3190 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_postopattr(), cmdnfs_postopfh3(), cmdnfs_wccdata(), CREATE3_FAIL_WCC, CREATE3_OK_ATTRS, CREATE3_OK_FH, CREATE3_OK_WCC, and NULL.
int cmdnfs_DIROP2res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 879 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, cmdnfs_fattr2(), cmdnfs_fhandle2(), CMDNFS_FREE, cmdnfs_nfsstat2(), DIROP2_ATTRIBUTES, DIROP2_HANDLE, and NULL.
int cmdnfs_diropargs2 (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 938 of file cmd_nfstools.c.
References CMDNFS_DECODE, cmdnfs_dirpath(), CMDNFS_ENCODE, cmdnfs_fhandle2(), CMDNFS_FREE, and NULL.
Referenced by cmdnfs_CREATE2args(), and cmdnfs_RENAME2args().
int cmdnfs_diropargs3 (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 1926 of file cmd_nfstools.c.
References CMDNFS_DECODE, cmdnfs_dirpath(), CMDNFS_ENCODE, cmdnfs_fhandle3(), CMDNFS_FREE, and NULL.
Referenced by cmdnfs_CREATE3args(), cmdnfs_LINK3args(), cmdnfs_MKDIR3args(), cmdnfs_RENAME3args(), and cmdnfs_SYMLINK3args().
int cmdnfs_dirpath (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 203 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, and CMDNFS_FREE.
Referenced by cmdnfs_diropargs2(), cmdnfs_diropargs3(), cmdnfs_SYMLINK3args(), fn_nfs_mount(), fn_nfs_remote_umount(), fn_nfs_umount(), and nfs_remote_mount().
int cmdnfs_exports (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 503 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, and NULL.
int cmdnfs_fattr2 (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Todo
Definition at line 746 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, and Localtime_r().
Referenced by cmdnfs_ATTR2res(), and cmdnfs_DIROP2res().
int cmdnfs_fattr3 (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Todo
Definition at line 1591 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, and Localtime_r().
Referenced by cmdnfs_GETATTR3res(), and cmdnfs_postopattr().
int cmdnfs_fhandle2 (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 255 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, and SIZE_STR_NFSHANDLE2.
Referenced by cmdnfs_DIROP2res(), cmdnfs_diropargs2(), cmdnfs_fhstatus2(), cmdnfs_READDIR2args(), and cmdnfs_SETATTR2args().
int cmdnfs_fhandle3 (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 567 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, and SIZE_STR_NFSHANDLE3.
Referenced by cmdnfs_ACCESS3args(), cmdnfs_diropargs3(), cmdnfs_LINK3args(), cmdnfs_LOOKUP3res(), cmdnfs_mountres3(), cmdnfs_postopfh3(), cmdnfs_READDIR3args(), cmdnfs_READDIRPLUS3args(), cmdnfs_SETATTR3args(), and nfs_remote_solvepath().
int cmdnfs_fhstatus2 (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 323 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, cmdnfs_fhandle2(), CMDNFS_FREE, cmdnfs_nfsstat2(), and NULL.
int cmdnfs_FSINFO3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 4224 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_postopattr(), FSINFO3_FAIL_ATTRS, FSINFO3_OK_ATTRS, FSINFO3_OK_INFO, and NULL.
int cmdnfs_FSSTAT3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 2760 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_postopattr(), FSSTAT3_FAIL_ATTRS, FSSTAT3_OK, and NULL.
int cmdnfs_GETATTR3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 1872 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, cmdnfs_fattr3(), CMDNFS_FREE, cmdnfs_nfsstat3(), GETATTR3_ATTRIBUTES, and NULL.
int cmdnfs_LINK3args (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 3914 of file cmd_nfstools.c.
References CMDNFS_DECODE, cmdnfs_diropargs3(), CMDNFS_ENCODE, cmdnfs_fhandle3(), CMDNFS_FREE, and NULL.
int cmdnfs_LINK3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 3971 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_postopattr(), cmdnfs_wccdata(), LINK3_FAIL_ATTRS, LINK3_FAIL_WCC, LINK3_OK_ATTRS, LINK3_OK_WCC, and NULL.
int cmdnfs_LOOKUP3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 2056 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, cmdnfs_fhandle3(), CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_postopattr(), LOOKUP3_FAIL_DIRATTR, LOOKUP3_OK_DIRATTR, LOOKUP3_OK_HANDLE, LOOKUP3_OK_OBJATTR, and NULL.
int cmdnfs_MKDIR3args (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 3272 of file cmd_nfstools.c.
References CMDNFS_DECODE, cmdnfs_diropargs3(), CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_sattr3(), and NULL.
int cmdnfs_MKDIR3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 3344 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_postopattr(), cmdnfs_postopfh3(), cmdnfs_wccdata(), MKDIR3_FAIL_WCC, MKDIR3_OK_ATTRS, MKDIR3_OK_FH, MKDIR3_OK_WCC, and NULL.
int cmdnfs_mountlist (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 449 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, and NULL.
int cmdnfs_mountres3 (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Todo Convert status to error code
Definition at line 646 of file cmd_nfstools.c.
References AUTH_FLAVORS, CMDNFS_DECODE, CMDNFS_ENCODE, cmdnfs_fhandle3(), CMDNFS_FREE, MNT_HANDLE, and NULL.
int cmdnfs_nfsstat2 (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 711 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, and CMDNFS_FREE.
Referenced by cmdnfs_ATTR2res(), cmdnfs_DIROP2res(), cmdnfs_fhstatus2(), cmdnfs_READDIR2res(), cmdnfs_READLINK2res(), and cmdnfs_STATFS2res().
int cmdnfs_nfsstat3 (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 1557 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, and CMDNFS_FREE.
Referenced by cmdnfs_ACCESS3res(), cmdnfs_CREATE3res(), cmdnfs_FSINFO3res(), cmdnfs_FSSTAT3res(), cmdnfs_GETATTR3res(), cmdnfs_LINK3res(), cmdnfs_LOOKUP3res(), cmdnfs_MKDIR3res(), cmdnfs_PATHCONF3res(), cmdnfs_READDIR3res(), cmdnfs_READDIRPLUS3res(), cmdnfs_READLINK3res(), cmdnfs_REMOVE3res(), cmdnfs_RENAME3res(), cmdnfs_RMDIR3res(), cmdnfs_SETATTR3res(), and cmdnfs_SYMLINK3res().
int cmdnfs_PATHCONF3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 4321 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_postopattr(), NULL, PATHCONF3_FAIL_ATTRS, PATHCONF3_OK_ATTRS, and PATHCONF3_OK_INFO.
int cmdnfs_postopattr (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 1973 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, cmdnfs_fattr3(), CMDNFS_FREE, and NULL.
Referenced by cmdnfs_ACCESS3res(), cmdnfs_CREATE3res(), cmdnfs_FSINFO3res(), cmdnfs_FSSTAT3res(), cmdnfs_LINK3res(), cmdnfs_LOOKUP3res(), cmdnfs_MKDIR3res(), cmdnfs_PATHCONF3res(), cmdnfs_READDIR3res(), cmdnfs_READDIRPLUS3res(), cmdnfs_READLINK3res(), cmdnfs_SYMLINK3res(), and cmdnfs_wccdata().
int cmdnfs_postopfh3 (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 2012 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, cmdnfs_fhandle3(), CMDNFS_FREE, and NULL.
Referenced by cmdnfs_CREATE3res(), cmdnfs_MKDIR3res(), and cmdnfs_SYMLINK3res().
int cmdnfs_READDIR2args (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 1336 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, cmdnfs_fhandle2(), CMDNFS_FREE, my_atoi(), and NULL.
int cmdnfs_READDIR2res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 1447 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat2(), and NULL.
int cmdnfs_READDIR3args (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 2262 of file cmd_nfstools.c.
References ato64(), CMDNFS_DECODE, CMDNFS_ENCODE, cmdnfs_fhandle3(), CMDNFS_FREE, and NULL.
int cmdnfs_READDIR3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 2353 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_postopattr(), NULL, READDIR3_FAIL, and READDIR3_OK.
int cmdnfs_READDIRPLUS3args (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 2429 of file cmd_nfstools.c.
References ato64(), CMDNFS_DECODE, CMDNFS_ENCODE, cmdnfs_fhandle3(), CMDNFS_FREE, and NULL.
int cmdnfs_READDIRPLUS3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 2610 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_postopattr(), NULL, READDIRPLUS3_FAIL, and READDIRPLUS3_OK.
int cmdnfs_READLINK2res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 988 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat2(), NULL, and READLINKRES_PATH.
int cmdnfs_READLINK3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 2690 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_postopattr(), NULL, READLINK3_FAIL_ATTRS, READLINK3_OK_ATTRS, and READLINK3_OK_DATA.
int cmdnfs_REMOVE3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 3429 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_wccdata(), NULL, REMOVE3_FAIL_WCC, and REMOVE3_OK_WCC.
int cmdnfs_RENAME2args (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 1506 of file cmd_nfstools.c.
References CMDNFS_DECODE, cmdnfs_diropargs2(), CMDNFS_ENCODE, CMDNFS_FREE, and NULL.
int cmdnfs_RENAME3args (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 3775 of file cmd_nfstools.c.
References CMDNFS_DECODE, cmdnfs_diropargs3(), CMDNFS_ENCODE, CMDNFS_FREE, and NULL.
int cmdnfs_RENAME3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 3832 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_wccdata(), NULL, RENAME3_FAIL_FROMWCC, RENAME3_FAIL_TOWCC, RENAME3_OK_FROMWCC, and RENAME3_OK_TOWCC.
int cmdnfs_RMDIR3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 3498 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_wccdata(), NULL, RMDIR3_FAIL_WCC, and RMDIR3_OK_WCC.
int cmdnfs_sattr2 (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 1037 of file cmd_nfstools.c.
References ato64(), atomode(), atotime(), CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, and my_atoi().
Referenced by cmdnfs_CREATE2args(), and cmdnfs_SETATTR2args().
int cmdnfs_sattr3 (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 1666 of file cmd_nfstools.c.
References ato64(), atomode(), atotime(), CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, and my_atoi().
Referenced by cmdnfs_CREATE3args(), cmdnfs_MKDIR3args(), cmdnfs_SETATTR3args(), cmdnfs_SYMLINK3args(), fn_nfs_ln(), fn_nfs_remote_ln(), fn_nfs_remote_setattr(), fn_nfs_setattr(), nfs_remote_create(), and nfs_remote_mkdir().
int cmdnfs_SETATTR2args (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 1285 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, cmdnfs_fhandle2(), CMDNFS_FREE, cmdnfs_sattr2(), and NULL.
int cmdnfs_SETATTR3args (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 3640 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, cmdnfs_fhandle3(), CMDNFS_FREE, cmdnfs_sattr3(), cmdnfs_sattrguard3(), and NULL.
int cmdnfs_SETATTR3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 3707 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_wccdata(), NULL, SETATTR3_FAIL_WCC, and SETATTR3_OK_WCC.
int cmdnfs_STATFS2res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 382 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat2(), and NULL.
int cmdnfs_SYMLINK3args (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 4056 of file cmd_nfstools.c.
References CMDNFS_DECODE, cmdnfs_diropargs3(), cmdnfs_dirpath(), CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_sattr3(), and NULL.
int cmdnfs_SYMLINK3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 4138 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_postopattr(), cmdnfs_postopfh3(), cmdnfs_wccdata(), NULL, SYMLINK3_FAIL_WCC, SYMLINK3_OK_ATTRS, SYMLINK3_OK_FH, and SYMLINK3_OK_WCC.
int cmdnfs_void (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 190 of file cmd_nfstools.c.
void print_nfs_attributes (fattr3 * attrs, FILE * output)
print_nfs_attributes: print an fattr3 to a given output file.
Parameters:
attrs (in fattr3) The attributes to be printed.
output (in FILE *) The file where the attributes are to be printed.
Returns: Nothing.
Definition at line 4500 of file cmd_nfstools.c.
Referenced by fn_nfs_ls(), fn_nfs_remote_ls(), fn_nfs_remote_stat(), and fn_nfs_stat().
void print_nfsitem_line (FILE * out, fattr3 * attrib, char * name, char * target)
print_nfsitem_line: Prints a nfs element on one line, like the Unix ls command.
Parameters:
out (in FILE*) The file where the item is to be printed.
attrib (fattr3 *) the NFS attributes for the item.
name (in char *) The name of the item to be printed.
target (in char *) It the item is a symbolic link, this contains the link target.
Returns: Nothing.
Definition at line 4416 of file cmd_nfstools.c.
References print_mask, and time2str().
Referenced by fn_nfs_ls(), and fn_nfs_remote_ls().