cmd_nfstools.c File Reference
nfs conversion tools.
#include <limits.h>
#include <string.h>
#include <sys/stat.h>
#include `cmd_nfstools.h`
#include `stuff_alloc.h`
#include `nfs23.h`
#include `nfs4.h`
#include `mount.h`
#include `nfs_proto_functions.h`
#include `nfs_tools.h`
#include `nfs_proto_tools.h`
#include `nfs_file_handle.h`
#include `cmd_tools.h`
Defines
#define SIZE_STR_NFSHANDLE2 (2 * NFS2_FHSIZE + 1)
#define SIZE_STR_NFSHANDLE3 (2 * NFS3_FHSIZE + 1)
#define MNT_HANDLE(p_mount_res3) ((p_mount_res3) $\rightarrow$ mountres3_u.mountinfo.fhandle)
#define AUTH_FLAVORS(p_mount_res3) ((p_mount_res3) $\rightarrow$ mountres3_u.mountinfo.auth_flavors)
#define ATTR2_ATTRIBUTES(_p_attr2res) ((_p_attr2res) $\rightarrow$ ATTR2res_u.attributes)
#define DIROP2_HANDLE(_p_dirop) ((_p_dirop) $\rightarrow$ DIROP2res_u.diropok.file)
#define DIROP2_ATTRIBUTES(_p_dirop) ((_p_dirop) $\rightarrow$ DIROP2res_u.diropok.attributes)
#define READLINKRES_PATH(_p_rl2res) ((_p_rl2res) $\rightarrow$ READLINK2res_u.data)
#define GETATTR3_ATTRIBUTES(_p_GETATTR3res) ((_p_GETATTR3res) $\rightarrow$ GETATTR3res_u.resok.obj_attributes)
#define LOOKUP3_OK_HANDLE(_p_LOOKUP3res) ((_p_LOOKUP3res) $\rightarrow$ LOOKUP3res_u.resok.object)
#define LOOKUP3_OK_OBJATTR(_p_LOOKUP3res) ((_p_LOOKUP3res) $\rightarrow$ LOOKUP3res_u.resok.obj_attributes)
#define LOOKUP3_OK_DIRATTR(_p_LOOKUP3res) ((_p_LOOKUP3res) $\rightarrow$ LOOKUP3res_u.resok.dir_attributes)
#define LOOKUP3_FAIL_DIRATTR(_p_LOOKUP3res) ((_p_LOOKUP3res) $\rightarrow$ LOOKUP3res_u.resfail.dir_attributes)
#define READDIR3_OK(_p_READDIR3res) ((_p_READDIR3res) $\rightarrow$ READDIR3res_u.resok)
#define READDIR3_FAIL(_p_READDIR3res) ((_p_READDIR3res) $\rightarrow$ READDIR3res_u.resfail)
#define READDIRPLUS3_OK(_p_READDIRPLUS3res) ((_p_READDIRPLUS3res) $\rightarrow$ READDIRPLUS3res_u.resok)
#define READDIRPLUS3_FAIL(_p_READDIRPLUS3res) ((_p_READDIRPLUS3res) $\rightarrow$ READDIRPLUS3res_u.resfail)
#define READLINK3_OK_ATTRS(_p_READLINK3res) ((_p_READLINK3res) $\rightarrow$ READLINK3res_u.resok.symlink_attributes)
#define READLINK3_OK_DATA(_p_READLINK3res) ((_p_READLINK3res) $\rightarrow$ READLINK3res_u.resok.data)
#define READLINK3_FAIL_ATTRS(_p_READLINK3res) ((_p_READLINK3res) $\rightarrow$ READLINK3res_u.resfail.symlink_attributes)
#define FSSTAT3_OK(_p_FSSTAT3res) ((_p_FSSTAT3res) $\rightarrow$ FSSTAT3res_u.resok)
#define FSSTAT3_FAIL_ATTRS(_p_FSSTAT3res) ((_p_FSSTAT3res) $\rightarrow$ FSSTAT3res_u.resfail.obj_attributes)
#define ACCESS3_OK_ATTRS(_p_ACCESS3res) ((_p_ACCESS3res) $\rightarrow$ ACCESS3res_u.resok.obj_attributes)
#define ACCESS3_OK_ACCESS(_p_ACCESS3res) ((_p_ACCESS3res) $\rightarrow$ ACCESS3res_u.resok.access)
#define ACCESS3_FAIL_ATTRS(_p_ACCESS3res) ((_p_ACCESS3res) $\rightarrow$ ACCESS3res_u.resfail.obj_attributes)
#define CREATE3_OK_FH(_p_CREATE3res) ((_p_CREATE3res) $\rightarrow$ CREATE3res_u.resok.obj)
#define CREATE3_OK_ATTRS(_p_CREATE3res) ((_p_CREATE3res) $\rightarrow$ CREATE3res_u.resok.obj_attributes)
#define CREATE3_OK_WCC(_p_CREATE3res) ((_p_CREATE3res) $\rightarrow$ CREATE3res_u.resok.dir_wcc)
#define CREATE3_FAIL_WCC(_p_CREATE3res) ((_p_CREATE3res) $\rightarrow$ CREATE3res_u.resfail.dir_wcc)
#define MKDIR3_OK_FH(_p_MKDIR3res) ((_p_MKDIR3res) $\rightarrow$ MKDIR3res_u.resok.obj)
#define MKDIR3_OK_ATTRS(_p_MKDIR3res) ((_p_MKDIR3res) $\rightarrow$ MKDIR3res_u.resok.obj_attributes)
#define MKDIR3_OK_WCC(_p_MKDIR3res) ((_p_MKDIR3res) $\rightarrow$ MKDIR3res_u.resok.dir_wcc)
#define MKDIR3_FAIL_WCC(_p_MKDIR3res) ((_p_MKDIR3res) $\rightarrow$ MKDIR3res_u.resfail.dir_wcc)
#define REMOVE3_OK_WCC(_p_REMOVE3res) ((_p_REMOVE3res) $\rightarrow$ REMOVE3res_u.resok.dir_wcc)
#define REMOVE3_FAIL_WCC(_p_REMOVE3res) ((_p_REMOVE3res) $\rightarrow$ REMOVE3res_u.resfail.dir_wcc)
#define RMDIR3_OK_WCC(_p_RMDIR3res) ((_p_RMDIR3res) $\rightarrow$ RMDIR3res_u.resok.dir_wcc)
#define RMDIR3_FAIL_WCC(_p_RMDIR3res) ((_p_RMDIR3res) $\rightarrow$ RMDIR3res_u.resfail.dir_wcc)
#define SETATTR3_OK_WCC(_p_SETATTR3res) ((_p_SETATTR3res) $\rightarrow$ SETATTR3res_u.resok.obj_wcc)
#define SETATTR3_FAIL_WCC(_p_SETATTR3res) ((_p_SETATTR3res) $\rightarrow$ SETATTR3res_u.resfail.obj_wcc)
#define RENAME3_OK_FROMWCC(_p_RENAME3res) ((_p_RENAME3res) $\rightarrow$ RENAME3res_u.resok.fromdir_wcc)
#define RENAME3_OK_TOWCC(_p_RENAME3res) ((_p_RENAME3res) $\rightarrow$ RENAME3res_u.resok.todir_wcc)
#define RENAME3_FAIL_FROMWCC(_p_RENAME3res) ((_p_RENAME3res) $\rightarrow$ RENAME3res_u.resfail.fromdir_wcc)
#define RENAME3_FAIL_TOWCC(_p_RENAME3res) ((_p_RENAME3res) $\rightarrow$ RENAME3res_u.resfail.todir_wcc)
#define LINK3_OK_ATTRS(_p_LINK3res) ((_p_LINK3res) $\rightarrow$ LINK3res_u.resok.file_attributes)
#define LINK3_OK_WCC(_p_LINK3res) ((_p_LINK3res) $\rightarrow$ LINK3res_u.resok.linkdir_wcc)
#define LINK3_FAIL_ATTRS(_p_LINK3res) ((_p_LINK3res) $\rightarrow$ LINK3res_u.resfail.file_attributes)
#define LINK3_FAIL_WCC(_p_LINK3res) ((_p_LINK3res) $\rightarrow$ LINK3res_u.resfail.linkdir_wcc)
#define SYMLINK3_OK_FH(_p_SYMLINK3res) ((_p_SYMLINK3res) $\rightarrow$ SYMLINK3res_u.resok.obj)
#define SYMLINK3_OK_ATTRS(_p_SYMLINK3res) ((_p_SYMLINK3res) $\rightarrow$ SYMLINK3res_u.resok.obj_attributes)
#define SYMLINK3_OK_WCC(_p_SYMLINK3res) ((_p_SYMLINK3res) $\rightarrow$ SYMLINK3res_u.resok.dir_wcc)
#define SYMLINK3_FAIL_WCC(_p_SYMLINK3res) ((_p_SYMLINK3res) $\rightarrow$ SYMLINK3res_u.resfail.dir_wcc)
#define FSINFO3_OK_ATTRS(_p_FSINFO3res) ((_p_FSINFO3res) $\rightarrow$ FSINFO3res_u.resok.obj_attributes)
#define FSINFO3_OK_INFO(_p_FSINFO3res) ((_p_FSINFO3res) $\rightarrow$ FSINFO3res_u.resok)
#define FSINFO3_FAIL_ATTRS(_p_FSINFO3res) ((_p_FSINFO3res) $\rightarrow$ FSINFO3res_u.resfail.obj_attributes)
#define PATHCONF3_OK_ATTRS(_p_PATHCONF3res) ((_p_PATHCONF3res) $\rightarrow$ PATHCONF3res_u.resok.obj_attributes)
#define PATHCONF3_OK_INFO(_p_PATHCONF3res) ((_p_PATHCONF3res) $\rightarrow$ PATHCONF3res_u.resok)
#define PATHCONF3_FAIL_ATTRS(_p_PATHCONF3res) ((_p_PATHCONF3res) $\rightarrow$ PATHCONF3res_u.resfail.obj_attributes)
#define print_mask(_out, _mode, _mask, _lettre)
Functions
int get_rpc_xid ()
int cmdnfs_void (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_dirpath (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_fhandle2 (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_fhstatus2 (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_STATFS2res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_mountlist (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_exports (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_fhandle3 (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_mountres3 (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_nfsstat2 (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_fattr2 (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_ATTR2res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_DIROP2res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_diropargs2 (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_READLINK2res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_sattr2 (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_CREATE2args (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_SETATTR2args (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_READDIR2args (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_READDIR2res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_RENAME2args (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_nfsstat3 (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_fattr3 (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_sattr3 (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_GETATTR3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_diropargs3 (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_postopattr (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_postopfh3 (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_LOOKUP3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_READDIR3args (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_READDIR3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_READDIRPLUS3args (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_READDIRPLUS3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_READLINK3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_FSSTAT3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_ACCESS3args (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_ACCESS3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_CREATE3args (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_preopattr (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_wccdata (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_CREATE3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_MKDIR3args (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_MKDIR3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_REMOVE3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_RMDIR3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_sattrguard3 (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_SETATTR3args (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_SETATTR3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_RENAME3args (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_RENAME3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_LINK3args (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_LINK3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_SYMLINK3args (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_SYMLINK3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_FSINFO3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
int cmdnfs_PATHCONF3res (cmdnfs_encodetype_t encodeflag, int argc, char **argv, int indent, FILE *out_stream, caddr_t p_nfs_struct)
void print_nfsitem_line (FILE *out, fattr3 *attrib, char *name, char *target)
void print_nfs_attributes (fattr3 *attrs, FILE *output)
Detailed Description
nfs conversion tools.
Author:
Author leibovic
Date:
Date 2006/02/17 13:37:44
Version:
Revision 1.24
Log cmd_nfstools.c(p.),v
Revision 1.24 2006/02/17 13:37:44 leibovic Ghost FS is back !
Revision 1.23 2006/01/31 12:25:42 leibovic Fixing a minor display bug.
Revision 1.22 2006/01/18 08:02:04 deniel Order in includes and libraries
Revision 1.21 2006/01/18 07:29:11 leibovic Fixing bugs about exportlists.
Revision 1.20 2005/11/28 17:02:59 deniel Added CeCILL headers
Revision 1.19 2005/10/12 11:30:10 leibovic NFSv2.
Revision 1.18 2005/10/07 08:30:43 leibovic nfs2_rename + New FSAL init functions.
Revision 1.17 2005/09/30 14:30:43 leibovic Adding nfs2_readdir commqnd.
Revision 1.16 2005/09/30 06:56:55 leibovic Adding nfs2_setattr command.
Revision 1.15 2005/09/30 06:46:00 leibovic New create2 and mkdir2 args format.
Revision 1.14 2005/09/28 09:08:00 leibovic thread-safe version of localtime.
Revision 1.13 2005/08/30 13:22:26 leibovic Addind nfs3_fsinfo et nfs3_pathconf functions.
Revision 1.12 2005/08/10 14:55:05 leibovic NFS support of setattr, rename, link, symlink.
Revision 1.11 2005/08/10 10:57:17 leibovic Adding removal functions.
Revision 1.10 2005/08/09 14:52:57 leibovic Addinf create and mkdir commands.
Revision 1.9 2005/08/08 11:42:49 leibovic Adding some stardard unix calls through NFS (ls, cd, pwd).
Revision 1.8 2005/08/05 15:17:56 leibovic Adding mount and pwd commands for browsing.
Revision 1.7 2005/08/05 10:42:38 leibovic Adding readdirplus.
Revision 1.6 2005/08/05 08:59:32 leibovic Adding explicit strings for type and NFS status.
Revision 1.5 2005/08/05 07:59:07 leibovic some nfs3 commands added.
Revision 1.4 2005/08/04 06:57:41 leibovic some NFSv2 commands are completed.
Revision 1.3 2005/08/03 12:51:16 leibovic MNT3 protocol OK.
Revision 1.2 2005/08/03 11:51:09 leibovic MNT1 protocol OK.
Revision 1.1 2005/08/03 08:16:23 leibovic Adding nfs layer structures.
Definition in file cmd_nfstools.c.
Define Documentation
#define ACCESS3_FAIL_ATTRS(_p_ACCESS3res) ((_p_ACCESS3res) $\rightarrow$ ACCESS3res_u.resfail.obj_attributes)
Definition at line 2907 of file cmd_nfstools.c.
Referenced by cmdnfs_ACCESS3res().
#define ACCESS3_OK_ACCESS(_p_ACCESS3res) ((_p_ACCESS3res) $\rightarrow$ ACCESS3res_u.resok.access)
Definition at line 2906 of file cmd_nfstools.c.
Referenced by cmdnfs_ACCESS3res().
#define ACCESS3_OK_ATTRS(_p_ACCESS3res) ((_p_ACCESS3res) $\rightarrow$ ACCESS3res_u.resok.obj_attributes)
Definition at line 2905 of file cmd_nfstools.c.
Referenced by cmdnfs_ACCESS3res().
#define ATTR2_ATTRIBUTES(_p_attr2res) ((_p_attr2res) $\rightarrow$ ATTR2res_u.attributes)
Definition at line 819 of file cmd_nfstools.c.
Referenced by cmdnfs_ATTR2res().
#define AUTH_FLAVORS(p_mount_res3) ((p_mount_res3) $\rightarrow$ mountres3_u.mountinfo.auth_flavors)
Definition at line 644 of file cmd_nfstools.c.
Referenced by cmdnfs_mountres3().
#define CREATE3_FAIL_WCC(_p_CREATE3res) ((_p_CREATE3res) $\rightarrow$ CREATE3res_u.resfail.dir_wcc)
Definition at line 3188 of file cmd_nfstools.c.
Referenced by cmdnfs_CREATE3res().
#define CREATE3_OK_ATTRS(_p_CREATE3res) ((_p_CREATE3res) $\rightarrow$ CREATE3res_u.resok.obj_attributes)
Definition at line 3186 of file cmd_nfstools.c.
Referenced by cmdnfs_CREATE3res().
#define CREATE3_OK_FH(_p_CREATE3res) ((_p_CREATE3res) $\rightarrow$ CREATE3res_u.resok.obj)
Definition at line 3185 of file cmd_nfstools.c.
Referenced by cmdnfs_CREATE3res().
#define CREATE3_OK_WCC(_p_CREATE3res) ((_p_CREATE3res) $\rightarrow$ CREATE3res_u.resok.dir_wcc)
Definition at line 3187 of file cmd_nfstools.c.
Referenced by cmdnfs_CREATE3res().
#define DIROP2_ATTRIBUTES(_p_dirop) ((_p_dirop) $\rightarrow$ DIROP2res_u.diropok.attributes)
Definition at line 876 of file cmd_nfstools.c.
Referenced by cmdnfs_DIROP2res().
#define DIROP2_HANDLE(_p_dirop) ((_p_dirop) $\rightarrow$ DIROP2res_u.diropok.file)
Definition at line 875 of file cmd_nfstools.c.
Referenced by cmdnfs_DIROP2res().
#define FSINFO3_FAIL_ATTRS(_p_FSINFO3res) ((_p_FSINFO3res) $\rightarrow$ FSINFO3res_u.resfail.obj_attributes)
Definition at line 4222 of file cmd_nfstools.c.
Referenced by cmdnfs_FSINFO3res().
#define FSINFO3_OK_ATTRS(_p_FSINFO3res) ((_p_FSINFO3res) $\rightarrow$ FSINFO3res_u.resok.obj_attributes)
Definition at line 4220 of file cmd_nfstools.c.
Referenced by cmdnfs_FSINFO3res().
#define FSINFO3_OK_INFO(_p_FSINFO3res) ((_p_FSINFO3res) $\rightarrow$ FSINFO3res_u.resok)
Definition at line 4221 of file cmd_nfstools.c.
Referenced by cmdnfs_FSINFO3res().
#define FSSTAT3_FAIL_ATTRS(_p_FSSTAT3res) ((_p_FSSTAT3res) $\rightarrow$ FSSTAT3res_u.resfail.obj_attributes)
Definition at line 2758 of file cmd_nfstools.c.
Referenced by cmdnfs_FSSTAT3res().
#define FSSTAT3_OK(_p_FSSTAT3res) ((_p_FSSTAT3res) $\rightarrow$ FSSTAT3res_u.resok)
Definition at line 2757 of file cmd_nfstools.c.
Referenced by cmdnfs_FSSTAT3res().
#define GETATTR3_ATTRIBUTES(_p_GETATTR3res) ((_p_GETATTR3res) $\rightarrow$ GETATTR3res_u.resok.obj_attributes)
Definition at line 1870 of file cmd_nfstools.c.
Referenced by cmdnfs_GETATTR3res().
#define LINK3_FAIL_ATTRS(_p_LINK3res) ((_p_LINK3res) $\rightarrow$ LINK3res_u.resfail.file_attributes)
Definition at line 3968 of file cmd_nfstools.c.
Referenced by cmdnfs_LINK3res().
#define LINK3_FAIL_WCC(_p_LINK3res) ((_p_LINK3res) $\rightarrow$ LINK3res_u.resfail.linkdir_wcc)
Definition at line 3969 of file cmd_nfstools.c.
Referenced by cmdnfs_LINK3res().
#define LINK3_OK_ATTRS(_p_LINK3res) ((_p_LINK3res) $\rightarrow$ LINK3res_u.resok.file_attributes)
Definition at line 3966 of file cmd_nfstools.c.
Referenced by cmdnfs_LINK3res().
#define LINK3_OK_WCC(_p_LINK3res) ((_p_LINK3res) $\rightarrow$ LINK3res_u.resok.linkdir_wcc)
Definition at line 3967 of file cmd_nfstools.c.
Referenced by cmdnfs_LINK3res().
#define LOOKUP3_FAIL_DIRATTR(_p_LOOKUP3res) ((_p_LOOKUP3res) $\rightarrow$ LOOKUP3res_u.resfail.dir_attributes)
Definition at line 2054 of file cmd_nfstools.c.
Referenced by cmdnfs_LOOKUP3res().
#define LOOKUP3_OK_DIRATTR(_p_LOOKUP3res) ((_p_LOOKUP3res) $\rightarrow$ LOOKUP3res_u.resok.dir_attributes)
Definition at line 2053 of file cmd_nfstools.c.
Referenced by cmdnfs_LOOKUP3res().
#define LOOKUP3_OK_HANDLE(_p_LOOKUP3res) ((_p_LOOKUP3res) $\rightarrow$ LOOKUP3res_u.resok.object)
Definition at line 2051 of file cmd_nfstools.c.
Referenced by cmdnfs_LOOKUP3res().
#define LOOKUP3_OK_OBJATTR(_p_LOOKUP3res) ((_p_LOOKUP3res) $\rightarrow$ LOOKUP3res_u.resok.obj_attributes)
Definition at line 2052 of file cmd_nfstools.c.
Referenced by cmdnfs_LOOKUP3res().
#define MKDIR3_FAIL_WCC(_p_MKDIR3res) ((_p_MKDIR3res) $\rightarrow$ MKDIR3res_u.resfail.dir_wcc)
Definition at line 3342 of file cmd_nfstools.c.
Referenced by cmdnfs_MKDIR3res().
#define MKDIR3_OK_ATTRS(_p_MKDIR3res) ((_p_MKDIR3res) $\rightarrow$ MKDIR3res_u.resok.obj_attributes)
Definition at line 3340 of file cmd_nfstools.c.
Referenced by cmdnfs_MKDIR3res().
#define MKDIR3_OK_FH(_p_MKDIR3res) ((_p_MKDIR3res) $\rightarrow$ MKDIR3res_u.resok.obj)
Definition at line 3339 of file cmd_nfstools.c.
Referenced by cmdnfs_MKDIR3res().
#define MKDIR3_OK_WCC(_p_MKDIR3res) ((_p_MKDIR3res) $\rightarrow$ MKDIR3res_u.resok.dir_wcc)
Definition at line 3341 of file cmd_nfstools.c.
Referenced by cmdnfs_MKDIR3res().
#define MNT_HANDLE(p_mount_res3) ((p_mount_res3) $\rightarrow$ mountres3_u.mountinfo.fhandle)
Definition at line 643 of file cmd_nfstools.c.
Referenced by cmdnfs_mountres3().
#define PATHCONF3_FAIL_ATTRS(_p_PATHCONF3res) ((_p_PATHCONF3res) $\rightarrow$ PATHCONF3res_u.resfail.obj_attributes)
Definition at line 4319 of file cmd_nfstools.c.
Referenced by cmdnfs_PATHCONF3res().
#define PATHCONF3_OK_ATTRS(_p_PATHCONF3res) ((_p_PATHCONF3res) $\rightarrow$ PATHCONF3res_u.resok.obj_attributes)
Definition at line 4317 of file cmd_nfstools.c.
Referenced by cmdnfs_PATHCONF3res().
#define PATHCONF3_OK_INFO(_p_PATHCONF3res) ((_p_PATHCONF3res) $\rightarrow$ PATHCONF3res_u.resok)
Definition at line 4318 of file cmd_nfstools.c.
Referenced by cmdnfs_PATHCONF3res().
#define print_mask(_out, _mode, _mask, _lettre)
Value:
do {    \
        if (_mode & _mask) fprintf(_out,_lettre);    \
        else fprintf(_out,"-");                      \
      } while(0)
print_nfsitem_line: Prints a nfs element on one line, like the Unix ls command.
Parameters:
out (in FILE*) The file where the item is to be printed.
attrib (fattr3 *) the NFS attributes for the item.
name (in char *) The name of the item to be printed.
target (in char *) It the item is a symbolic link, this contains the link target.
Returns: Nothing.
Definition at line 4411 of file cmd_nfstools.c.
Referenced by print_item_line(), and print_nfsitem_line().
#define READDIR3_FAIL(_p_READDIR3res) ((_p_READDIR3res) $\rightarrow$ READDIR3res_u.resfail)
Definition at line 2351 of file cmd_nfstools.c.
Referenced by cmdnfs_READDIR3res().
#define READDIR3_OK(_p_READDIR3res) ((_p_READDIR3res) $\rightarrow$ READDIR3res_u.resok)
Definition at line 2350 of file cmd_nfstools.c.
Referenced by cmdnfs_READDIR3res().
#define READDIRPLUS3_FAIL(_p_READDIRPLUS3res) ((_p_READDIRPLUS3res) $\rightarrow$ READDIRPLUS3res_u.resfail)
Definition at line 2608 of file cmd_nfstools.c.
Referenced by cmdnfs_READDIRPLUS3res().
#define READDIRPLUS3_OK(_p_READDIRPLUS3res) ((_p_READDIRPLUS3res) $\rightarrow$ READDIRPLUS3res_u.resok)
Definition at line 2607 of file cmd_nfstools.c.
Referenced by cmdnfs_READDIRPLUS3res().
#define READLINK3_FAIL_ATTRS(_p_READLINK3res) ((_p_READLINK3res) $\rightarrow$ READLINK3res_u.resfail.symlink_attributes)
Definition at line 2688 of file cmd_nfstools.c.
Referenced by cmdnfs_READLINK3res().
#define READLINK3_OK_ATTRS(_p_READLINK3res) ((_p_READLINK3res) $\rightarrow$ READLINK3res_u.resok.symlink_attributes)
Definition at line 2686 of file cmd_nfstools.c.
Referenced by cmdnfs_READLINK3res().
#define READLINK3_OK_DATA(_p_READLINK3res) ((_p_READLINK3res) $\rightarrow$ READLINK3res_u.resok.data)
Definition at line 2687 of file cmd_nfstools.c.
Referenced by cmdnfs_READLINK3res().
#define READLINKRES_PATH(_p_rl2res) ((_p_rl2res) $\rightarrow$ READLINK2res_u.data)
Definition at line 986 of file cmd_nfstools.c.
Referenced by cmdnfs_READLINK2res().
#define REMOVE3_FAIL_WCC(_p_REMOVE3res) ((_p_REMOVE3res) $\rightarrow$ REMOVE3res_u.resfail.dir_wcc)
Definition at line 3427 of file cmd_nfstools.c.
Referenced by cmdnfs_REMOVE3res().
#define REMOVE3_OK_WCC(_p_REMOVE3res) ((_p_REMOVE3res) $\rightarrow$ REMOVE3res_u.resok.dir_wcc)
Definition at line 3426 of file cmd_nfstools.c.
Referenced by cmdnfs_REMOVE3res().
#define RENAME3_FAIL_FROMWCC(_p_RENAME3res) ((_p_RENAME3res) $\rightarrow$ RENAME3res_u.resfail.fromdir_wcc)
Definition at line 3829 of file cmd_nfstools.c.
Referenced by cmdnfs_RENAME3res().
#define RENAME3_FAIL_TOWCC(_p_RENAME3res) ((_p_RENAME3res) $\rightarrow$ RENAME3res_u.resfail.todir_wcc)
Definition at line 3830 of file cmd_nfstools.c.
Referenced by cmdnfs_RENAME3res().
#define RENAME3_OK_FROMWCC(_p_RENAME3res) ((_p_RENAME3res) $\rightarrow$ RENAME3res_u.resok.fromdir_wcc)
Definition at line 3827 of file cmd_nfstools.c.
Referenced by cmdnfs_RENAME3res().
#define RENAME3_OK_TOWCC(_p_RENAME3res) ((_p_RENAME3res) $\rightarrow$ RENAME3res_u.resok.todir_wcc)
Definition at line 3828 of file cmd_nfstools.c.
Referenced by cmdnfs_RENAME3res().
#define RMDIR3_FAIL_WCC(_p_RMDIR3res) ((_p_RMDIR3res) $\rightarrow$ RMDIR3res_u.resfail.dir_wcc)
Definition at line 3496 of file cmd_nfstools.c.
Referenced by cmdnfs_RMDIR3res().
#define RMDIR3_OK_WCC(_p_RMDIR3res) ((_p_RMDIR3res) $\rightarrow$ RMDIR3res_u.resok.dir_wcc)
Definition at line 3495 of file cmd_nfstools.c.
Referenced by cmdnfs_RMDIR3res().
#define SETATTR3_FAIL_WCC(_p_SETATTR3res) ((_p_SETATTR3res) $\rightarrow$ SETATTR3res_u.resfail.obj_wcc)
Definition at line 3705 of file cmd_nfstools.c.
Referenced by cmdnfs_SETATTR3res().
#define SETATTR3_OK_WCC(_p_SETATTR3res) ((_p_SETATTR3res) $\rightarrow$ SETATTR3res_u.resok.obj_wcc)
Definition at line 3704 of file cmd_nfstools.c.
Referenced by cmdnfs_SETATTR3res().
#define SIZE_STR_NFSHANDLE2 (2 * NFS2_FHSIZE + 1)
Definition at line 179 of file cmd_nfstools.c.
Referenced by cmdnfs_fhandle2().
#define SIZE_STR_NFSHANDLE3 (2 * NFS3_FHSIZE + 1)
Definition at line 180 of file cmd_nfstools.c.
Referenced by cmdnfs_fhandle3().
#define SYMLINK3_FAIL_WCC(_p_SYMLINK3res) ((_p_SYMLINK3res) $\rightarrow$ SYMLINK3res_u.resfail.dir_wcc)
Definition at line 4136 of file cmd_nfstools.c.
Referenced by cmdnfs_SYMLINK3res().
#define SYMLINK3_OK_ATTRS(_p_SYMLINK3res) ((_p_SYMLINK3res) $\rightarrow$ SYMLINK3res_u.resok.obj_attributes)
Definition at line 4134 of file cmd_nfstools.c.
Referenced by cmdnfs_SYMLINK3res().
#define SYMLINK3_OK_FH(_p_SYMLINK3res) ((_p_SYMLINK3res) $\rightarrow$ SYMLINK3res_u.resok.obj)
Definition at line 4133 of file cmd_nfstools.c.
Referenced by cmdnfs_SYMLINK3res().
#define SYMLINK3_OK_WCC(_p_SYMLINK3res) ((_p_SYMLINK3res) $\rightarrow$ SYMLINK3res_u.resok.dir_wcc)
Definition at line 4135 of file cmd_nfstools.c.
Referenced by cmdnfs_SYMLINK3res().
Function Documentation
int cmdnfs_ACCESS3args (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 2833 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, cmdnfs_fhandle3(), CMDNFS_FREE, and NULL.
int cmdnfs_ACCESS3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 2909 of file cmd_nfstools.c.
References ACCESS3_FAIL_ATTRS, ACCESS3_OK_ACCESS, ACCESS3_OK_ATTRS, CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_postopattr(), and NULL.
int cmdnfs_ATTR2res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 821 of file cmd_nfstools.c.
References ATTR2_ATTRIBUTES, CMDNFS_DECODE, CMDNFS_ENCODE, cmdnfs_fattr2(), CMDNFS_FREE, cmdnfs_nfsstat2(), and NULL.
int cmdnfs_CREATE2args (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 1237 of file cmd_nfstools.c.
References CMDNFS_DECODE, cmdnfs_diropargs2(), CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_sattr2(), and NULL.
int cmdnfs_CREATE3args (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 2993 of file cmd_nfstools.c.
References CMDNFS_DECODE, cmdnfs_diropargs3(), CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_sattr3(), and NULL.
int cmdnfs_CREATE3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 3190 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_postopattr(), cmdnfs_postopfh3(), cmdnfs_wccdata(), CREATE3_FAIL_WCC, CREATE3_OK_ATTRS, CREATE3_OK_FH, CREATE3_OK_WCC, and NULL.
int cmdnfs_DIROP2res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 879 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, cmdnfs_fattr2(), cmdnfs_fhandle2(), CMDNFS_FREE, cmdnfs_nfsstat2(), DIROP2_ATTRIBUTES, DIROP2_HANDLE, and NULL.
int cmdnfs_diropargs2 (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 938 of file cmd_nfstools.c.
References CMDNFS_DECODE, cmdnfs_dirpath(), CMDNFS_ENCODE, cmdnfs_fhandle2(), CMDNFS_FREE, and NULL.
Referenced by cmdnfs_CREATE2args(), and cmdnfs_RENAME2args().
int cmdnfs_diropargs3 (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 1926 of file cmd_nfstools.c.
References CMDNFS_DECODE, cmdnfs_dirpath(), CMDNFS_ENCODE, cmdnfs_fhandle3(), CMDNFS_FREE, and NULL.
Referenced by cmdnfs_CREATE3args(), cmdnfs_LINK3args(), cmdnfs_MKDIR3args(), cmdnfs_RENAME3args(), and cmdnfs_SYMLINK3args().
int cmdnfs_dirpath (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 203 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, and CMDNFS_FREE.
Referenced by cmdnfs_diropargs2(), cmdnfs_diropargs3(), cmdnfs_SYMLINK3args(), fn_nfs_mount(), fn_nfs_remote_umount(), fn_nfs_umount(), and nfs_remote_mount().
int cmdnfs_exports (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 503 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, and NULL.
int cmdnfs_fattr2 (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Todo
Definition at line 746 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, and Localtime_r().
Referenced by cmdnfs_ATTR2res(), and cmdnfs_DIROP2res().
int cmdnfs_fattr3 (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Todo
Definition at line 1591 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, and Localtime_r().
Referenced by cmdnfs_GETATTR3res(), and cmdnfs_postopattr().
int cmdnfs_fhandle2 (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 255 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, and SIZE_STR_NFSHANDLE2.
Referenced by cmdnfs_DIROP2res(), cmdnfs_diropargs2(), cmdnfs_fhstatus2(), cmdnfs_READDIR2args(), and cmdnfs_SETATTR2args().
int cmdnfs_fhandle3 (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 567 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, and SIZE_STR_NFSHANDLE3.
Referenced by cmdnfs_ACCESS3args(), cmdnfs_diropargs3(), cmdnfs_LINK3args(), cmdnfs_LOOKUP3res(), cmdnfs_mountres3(), cmdnfs_postopfh3(), cmdnfs_READDIR3args(), cmdnfs_READDIRPLUS3args(), cmdnfs_SETATTR3args(), and nfs_remote_solvepath().
int cmdnfs_fhstatus2 (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 323 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, cmdnfs_fhandle2(), CMDNFS_FREE, cmdnfs_nfsstat2(), and NULL.
int cmdnfs_FSINFO3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 4224 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_postopattr(), FSINFO3_FAIL_ATTRS, FSINFO3_OK_ATTRS, FSINFO3_OK_INFO, and NULL.
int cmdnfs_FSSTAT3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 2760 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_postopattr(), FSSTAT3_FAIL_ATTRS, FSSTAT3_OK, and NULL.
int cmdnfs_GETATTR3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 1872 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, cmdnfs_fattr3(), CMDNFS_FREE, cmdnfs_nfsstat3(), GETATTR3_ATTRIBUTES, and NULL.
int cmdnfs_LINK3args (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 3914 of file cmd_nfstools.c.
References CMDNFS_DECODE, cmdnfs_diropargs3(), CMDNFS_ENCODE, cmdnfs_fhandle3(), CMDNFS_FREE, and NULL.
int cmdnfs_LINK3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 3971 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_postopattr(), cmdnfs_wccdata(), LINK3_FAIL_ATTRS, LINK3_FAIL_WCC, LINK3_OK_ATTRS, LINK3_OK_WCC, and NULL.
int cmdnfs_LOOKUP3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 2056 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, cmdnfs_fhandle3(), CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_postopattr(), LOOKUP3_FAIL_DIRATTR, LOOKUP3_OK_DIRATTR, LOOKUP3_OK_HANDLE, LOOKUP3_OK_OBJATTR, and NULL.
int cmdnfs_MKDIR3args (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 3272 of file cmd_nfstools.c.
References CMDNFS_DECODE, cmdnfs_diropargs3(), CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_sattr3(), and NULL.
int cmdnfs_MKDIR3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 3344 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_postopattr(), cmdnfs_postopfh3(), cmdnfs_wccdata(), MKDIR3_FAIL_WCC, MKDIR3_OK_ATTRS, MKDIR3_OK_FH, MKDIR3_OK_WCC, and NULL.
int cmdnfs_mountlist (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 449 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, and NULL.
int cmdnfs_mountres3 (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Todo Convert status to error code
Definition at line 646 of file cmd_nfstools.c.
References AUTH_FLAVORS, CMDNFS_DECODE, CMDNFS_ENCODE, cmdnfs_fhandle3(), CMDNFS_FREE, MNT_HANDLE, and NULL.
int cmdnfs_nfsstat2 (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 711 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, and CMDNFS_FREE.
Referenced by cmdnfs_ATTR2res(), cmdnfs_DIROP2res(), cmdnfs_fhstatus2(), cmdnfs_READDIR2res(), cmdnfs_READLINK2res(), and cmdnfs_STATFS2res().
int cmdnfs_nfsstat3 (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 1557 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, and CMDNFS_FREE.
Referenced by cmdnfs_ACCESS3res(), cmdnfs_CREATE3res(), cmdnfs_FSINFO3res(), cmdnfs_FSSTAT3res(), cmdnfs_GETATTR3res(), cmdnfs_LINK3res(), cmdnfs_LOOKUP3res(), cmdnfs_MKDIR3res(), cmdnfs_PATHCONF3res(), cmdnfs_READDIR3res(), cmdnfs_READDIRPLUS3res(), cmdnfs_READLINK3res(), cmdnfs_REMOVE3res(), cmdnfs_RENAME3res(), cmdnfs_RMDIR3res(), cmdnfs_SETATTR3res(), and cmdnfs_SYMLINK3res().
int cmdnfs_PATHCONF3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 4321 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_postopattr(), NULL, PATHCONF3_FAIL_ATTRS, PATHCONF3_OK_ATTRS, and PATHCONF3_OK_INFO.
int cmdnfs_postopattr (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 1973 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, cmdnfs_fattr3(), CMDNFS_FREE, and NULL.
Referenced by cmdnfs_ACCESS3res(), cmdnfs_CREATE3res(), cmdnfs_FSINFO3res(), cmdnfs_FSSTAT3res(), cmdnfs_LINK3res(), cmdnfs_LOOKUP3res(), cmdnfs_MKDIR3res(), cmdnfs_PATHCONF3res(), cmdnfs_READDIR3res(), cmdnfs_READDIRPLUS3res(), cmdnfs_READLINK3res(), cmdnfs_SYMLINK3res(), and cmdnfs_wccdata().
int cmdnfs_postopfh3 (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 2012 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, cmdnfs_fhandle3(), CMDNFS_FREE, and NULL.
Referenced by cmdnfs_CREATE3res(), cmdnfs_MKDIR3res(), and cmdnfs_SYMLINK3res().
int cmdnfs_preopattr (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 3092 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, and Localtime_r().
Referenced by cmdnfs_wccdata().
int cmdnfs_READDIR2args (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 1336 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, cmdnfs_fhandle2(), CMDNFS_FREE, my_atoi(), and NULL.
int cmdnfs_READDIR2res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 1447 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat2(), and NULL.
int cmdnfs_READDIR3args (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 2262 of file cmd_nfstools.c.
References ato64(), CMDNFS_DECODE, CMDNFS_ENCODE, cmdnfs_fhandle3(), CMDNFS_FREE, and NULL.
int cmdnfs_READDIR3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 2353 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_postopattr(), NULL, READDIR3_FAIL, and READDIR3_OK.
int cmdnfs_READDIRPLUS3args (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 2429 of file cmd_nfstools.c.
References ato64(), CMDNFS_DECODE, CMDNFS_ENCODE, cmdnfs_fhandle3(), CMDNFS_FREE, and NULL.
int cmdnfs_READDIRPLUS3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 2610 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_postopattr(), NULL, READDIRPLUS3_FAIL, and READDIRPLUS3_OK.
int cmdnfs_READLINK2res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 988 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat2(), NULL, and READLINKRES_PATH.
int cmdnfs_READLINK3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 2690 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_postopattr(), NULL, READLINK3_FAIL_ATTRS, READLINK3_OK_ATTRS, and READLINK3_OK_DATA.
int cmdnfs_REMOVE3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 3429 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_wccdata(), NULL, REMOVE3_FAIL_WCC, and REMOVE3_OK_WCC.
int cmdnfs_RENAME2args (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 1506 of file cmd_nfstools.c.
References CMDNFS_DECODE, cmdnfs_diropargs2(), CMDNFS_ENCODE, CMDNFS_FREE, and NULL.
int cmdnfs_RENAME3args (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 3775 of file cmd_nfstools.c.
References CMDNFS_DECODE, cmdnfs_diropargs3(), CMDNFS_ENCODE, CMDNFS_FREE, and NULL.
int cmdnfs_RENAME3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 3832 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_wccdata(), NULL, RENAME3_FAIL_FROMWCC, RENAME3_FAIL_TOWCC, RENAME3_OK_FROMWCC, and RENAME3_OK_TOWCC.
int cmdnfs_RMDIR3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 3498 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_wccdata(), NULL, RMDIR3_FAIL_WCC, and RMDIR3_OK_WCC.
int cmdnfs_sattr2 (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 1037 of file cmd_nfstools.c.
References ato64(), atomode(), atotime(), CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, and my_atoi().
Referenced by cmdnfs_CREATE2args(), and cmdnfs_SETATTR2args().
int cmdnfs_sattr3 (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 1666 of file cmd_nfstools.c.
References ato64(), atomode(), atotime(), CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, and my_atoi().
Referenced by cmdnfs_CREATE3args(), cmdnfs_MKDIR3args(), cmdnfs_SETATTR3args(), cmdnfs_SYMLINK3args(), fn_nfs_ln(), fn_nfs_remote_ln(), fn_nfs_remote_setattr(), fn_nfs_setattr(), nfs_remote_create(), and nfs_remote_mkdir().
int cmdnfs_sattrguard3 (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 3564 of file cmd_nfstools.c.
References atotime(), CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, and my_atoi().
Referenced by cmdnfs_SETATTR3args().
int cmdnfs_SETATTR2args (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 1285 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, cmdnfs_fhandle2(), CMDNFS_FREE, cmdnfs_sattr2(), and NULL.
int cmdnfs_SETATTR3args (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 3640 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, cmdnfs_fhandle3(), CMDNFS_FREE, cmdnfs_sattr3(), cmdnfs_sattrguard3(), and NULL.
int cmdnfs_SETATTR3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 3707 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_wccdata(), NULL, SETATTR3_FAIL_WCC, and SETATTR3_OK_WCC.
int cmdnfs_STATFS2res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 382 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat2(), and NULL.
int cmdnfs_SYMLINK3args (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 4056 of file cmd_nfstools.c.
References CMDNFS_DECODE, cmdnfs_diropargs3(), cmdnfs_dirpath(), CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_sattr3(), and NULL.
int cmdnfs_SYMLINK3res (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 4138 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_nfsstat3(), cmdnfs_postopattr(), cmdnfs_postopfh3(), cmdnfs_wccdata(), NULL, SYMLINK3_FAIL_WCC, SYMLINK3_OK_ATTRS, SYMLINK3_OK_FH, and SYMLINK3_OK_WCC.
int cmdnfs_void (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 190 of file cmd_nfstools.c.
int cmdnfs_wccdata (cmdnfs_encodetype_t encodeflag, int argc, char ** argv, int indent, FILE * out_stream, caddr_t p_nfs_struct)
Definition at line 3146 of file cmd_nfstools.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_postopattr(), cmdnfs_preopattr(), and NULL.
Referenced by cmdnfs_CREATE3res(), cmdnfs_LINK3res(), cmdnfs_MKDIR3res(), cmdnfs_REMOVE3res(), cmdnfs_RENAME3res(), cmdnfs_RMDIR3res(), cmdnfs_SETATTR3res(), and cmdnfs_SYMLINK3res().
int get_rpc_xid ()
Definition at line 183 of file cmd_nfstools.c.
void print_nfs_attributes (fattr3 * attrs, FILE * output)
print_nfs_attributes: print an fattr3 to a given output file.
Parameters:
attrs (in fattr3) The attributes to be printed.
output (in FILE *) The file where the attributes are to be printed.
Returns: Nothing.
Definition at line 4500 of file cmd_nfstools.c.
Referenced by fn_nfs_ls(), fn_nfs_remote_ls(), fn_nfs_remote_stat(), and fn_nfs_stat().
void print_nfsitem_line (FILE * out, fattr3 * attrib, char * name, char * target)
print_nfsitem_line: Prints a nfs element on one line, like the Unix ls command.
Parameters:
out (in FILE*) The file where the item is to be printed.
attrib (fattr3 *) the NFS attributes for the item.
name (in char *) The name of the item to be printed.
target (in char *) It the item is a symbolic link, this contains the link target.
Returns: Nothing.
Definition at line 4416 of file cmd_nfstools.c.
References print_mask, and time2str().
Referenced by fn_nfs_ls(), and fn_nfs_remote_ls().