commands_FSAL.c File Reference
#include <strings.h>
#include <errno.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <unistd.h>
#include <time.h>
#include <ctype.h>
#include <string.h>
#include <pwd.h>
#include `fsal.h`
#include `log_functions.h`
#include `err_ghost_fs.h`
#include `config_parsing.h`
#include `cmd_tools.h`
#include `commands.h`
#include `Getopt.h`
#include `stuff_alloc.h`
Classes
struct cmdfsal_thr_info__
Defines
#define READDIR_SIZE FSAL_READDIR_SIZE
#define MAX_GRPS 128
#define MAX_CAT_SIZE (1024*1024)
Typedefs
typedef cmdfsal_thr_info__ cmdfsal_thr_info_t
Functions
cmdfsal_thr_info_t * GetFSALCmdContext ()
int Init_Thread_Context (FILE *output, cmdfsal_thr_info_t *context, int flag_v)
void fsal_layer_SetLogLevel (int log_lvl)
int fsal_init (char *filename, int flag_v, FILE *output)
int fn_fsal_init_fs (int argc, char **argv, FILE *output)
int fn_fsal_pwd (int argc, char **argv, FILE *output)
int solvepath (char *io_global_path, int size_global_path, char *i_spec_path, fsal_handle_t i_current_handle, fsal_handle_t *new_handle, FILE *output)
int fn_fsal_cd (int argc, char **argv, FILE *output)
int fn_fsal_stat (int argc, char **argv, FILE *output)
int fn_fsal_lsxattrs (int argc, char **argv, FILE *output)
int fn_fsal_getxattr (int argc, char **argv, FILE *output)
int fn_fsal_ls (int argc, char **argv, FILE *output)
int fn_fsal_callstat (int argc, char **argv, FILE *output)
int fn_fsal_su (int argc, char **argv, FILE *output)
int fn_fsal_unlink (int argc, char **argv, FILE *output)
int fn_fsal_mkdir (int argc, char **argv, FILE *output)
int fn_fsal_rename (int argc, char **argv, FILE *output)
int fn_fsal_ln (int argc, char **argv, FILE *output)
int fn_fsal_hardlink (int argc, char **argv, FILE *output)
int fn_fsal_create (int argc, char **argv, FILE *output)
int fn_fsal_setattr (int argc, char **argv, FILE *output)
int fn_fsal_access (int argc, char **argv, FILE *output)
int fn_fsal_truncate (int argc, char **argv, FILE *output)
int fn_fsal_open_byname (int argc, char **argv, FILE *output)
int fn_fsal_open (int argc, char **argv, FILE *output)
int fn_fsal_open_byfileid (int argc, char **argv, FILE *output)
int fn_fsal_read (int argc, char **argv, FILE *output)
int fn_fsal_write (int argc, char **argv, FILE *output)
int fn_fsal_close (int argc, char **argv, FILE *output)
int fn_fsal_close_byfileid (int argc, char **argv, FILE *output)
int fn_fsal_cat (int argc, char **argv, FILE *output)
int fn_fsal_rcp (int argc, char **argv, FILE *output)
int fn_fsal_cross (int argc, char **argv, FILE *output)
int fn_fsal_handlecmp (int argc, char **argv, FILE *output)
Define Documentation
#define MAX_CAT_SIZE (1024*1024)
#define MAX_GRPS 128
#define READDIR_SIZE FSAL_READDIR_SIZE
Referenced by fn_fsal_ls().
Typedef Documentation
typedef struct cmdfsal_thr_info__ cmdfsal_thr_info_t
Referenced by fn_fsal_access(), fn_fsal_cat(), fn_fsal_cd(), fn_fsal_close(), fn_fsal_close_byfileid(), fn_fsal_create(), fn_fsal_cross(), fn_fsal_getxattr(), fn_fsal_handlecmp(), fn_fsal_hardlink(), fn_fsal_ln(), fn_fsal_ls(), fn_fsal_lsxattrs(), fn_fsal_mkdir(), fn_fsal_open(), fn_fsal_open_byfileid(), fn_fsal_open_byname(), fn_fsal_pwd(), fn_fsal_rcp(), fn_fsal_read(), fn_fsal_rename(), fn_fsal_setattr(), fn_fsal_stat(), fn_fsal_su(), fn_fsal_truncate(), fn_fsal_unlink(), fn_fsal_write(), fsal_init(), GetFSALCmdContext(), Init_Thread_Context(), and solvepath().
Function Documentation
int fn_fsal_access (int argc, char ** argv, FILE * output)
perform an access command. syntax: access [-A] [F][R][W][X] <file> example: access toto FRX
Definition at line 3125 of file commands_FSAL.c.
References cmdfsal_thr_info_t, cmdfsal_thr_info__::context, cmdfsal_thr_info__::current_dir, cmdfsal_thr_info__::current_path, GetFSALCmdContext(), Getopt(), Init_Thread_Context(), cmdfsal_thr_info__::is_thread_ok, NULL, Optind, Optopt, print_fsal_attributes(), print_fsal_status(), and solvepath().
int fn_fsal_callstat (int argc, char ** argv, FILE * output)
display statistics about FSAL calls.
Definition at line 1810 of file commands_FSAL.c.
int fn_fsal_cat (int argc, char ** argv, FILE * output)
Command that prints a file to screen. cat [-f] <path>
Definition at line 5103 of file commands_FSAL.c.
References cmdfsal_thr_info_t, cmdfsal_thr_info__::context, cmdfsal_thr_info__::current_dir, cmdfsal_thr_info__::current_path, GetFSALCmdContext(), Getopt(), Init_Thread_Context(), cmdfsal_thr_info__::is_thread_ok, NULL, Optind, Optopt, print_fsal_status(), and solvepath().
int fn_fsal_cd (int argc, char ** argv, FILE * output)
change current path
Definition at line 919 of file commands_FSAL.c.
References cmdfsal_thr_info_t, cmdfsal_thr_info__::context, cmdfsal_thr_info__::current_dir, cmdfsal_thr_info__::current_path, GetFSALCmdContext(), Init_Thread_Context(), cmdfsal_thr_info__::is_thread_ok, print_fsal_status(), and solvepath().
int fn_fsal_close (int argc, char ** argv, FILE * output)
Command that closes a file. close
Definition at line 4974 of file commands_FSAL.c.
References cmdfsal_thr_info_t, cmdfsal_thr_info__::current_fd, GetFSALCmdContext(), Init_Thread_Context(), cmdfsal_thr_info__::is_thread_ok, cmdfsal_thr_info__::opened, and print_fsal_status().
int fn_fsal_close_byfileid (int argc, char ** argv, FILE * output)
Command that closes a file. close
Definition at line 5038 of file commands_FSAL.c.
References cmdfsal_thr_info_t, cmdfsal_thr_info__::current_fd, GetFSALCmdContext(), Init_Thread_Context(), cmdfsal_thr_info__::is_thread_ok, cmdfsal_thr_info__::opened, and print_fsal_status().
int fn_fsal_create (int argc, char ** argv, FILE * output)
proceed an create command.
Definition at line 2758 of file commands_FSAL.c.
References atomode(), cmdfsal_thr_info_t, cmdfsal_thr_info__::context, cmdfsal_thr_info__::current_dir, cmdfsal_thr_info__::current_path, GetFSALCmdContext(), Getopt(), Init_Thread_Context(), cmdfsal_thr_info__::is_thread_ok, NULL, Optind, Optopt, print_fsal_status(), solvepath(), and split_path().
int fn_fsal_cross (int argc, char ** argv, FILE * output)
change current path
Definition at line 5472 of file commands_FSAL.c.
References cmdfsal_thr_info_t, cmdfsal_thr_info__::context, cmdfsal_thr_info__::current_dir, cmdfsal_thr_info__::current_path, GetFSALCmdContext(), Init_Thread_Context(), cmdfsal_thr_info__::is_thread_ok, NULL, print_fsal_status(), and solvepath().
int fn_fsal_getxattr (int argc, char ** argv, FILE * output)
display an extended attribute.
Definition at line 1280 of file commands_FSAL.c.
References cmdfsal_thr_info_t, cmdfsal_thr_info__::context, cmdfsal_thr_info__::current_dir, cmdfsal_thr_info__::current_path, GetFSALCmdContext(), Getopt(), Init_Thread_Context(), cmdfsal_thr_info__::is_thread_ok, Optind, Optopt, print_fsal_status(), and solvepath().
int fn_fsal_handlecmp (int argc, char ** argv, FILE * output)
compare 2 handles.
Definition at line 5564 of file commands_FSAL.c.
References cmdfsal_thr_info_t, cmdfsal_thr_info__::current_dir, cmdfsal_thr_info__::current_path, GetFSALCmdContext(), Init_Thread_Context(), cmdfsal_thr_info__::is_thread_ok, print_fsal_status(), and solvepath().
int fn_fsal_hardlink (int argc, char ** argv, FILE * output)
proceed a hardlink command.
Definition at line 2598 of file commands_FSAL.c.
References cmdfsal_thr_info_t, cmdfsal_thr_info__::context, cmdfsal_thr_info__::current_dir, cmdfsal_thr_info__::current_path, GetFSALCmdContext(), Getopt(), Init_Thread_Context(), cmdfsal_thr_info__::is_thread_ok, NULL, Optind, Optopt, print_fsal_status(), solvepath(), and split_path().
int fn_fsal_init_fs (int argc, char ** argv, FILE * output)
proceed an init_fs command.
Definition at line 639 of file commands_FSAL.c.
References fsal_init(), Getopt(), Optind, and Optopt.
int fn_fsal_ln (int argc, char ** argv, FILE * output)
proceed an ln command.
Definition at line 2430 of file commands_FSAL.c.
References cmdfsal_thr_info_t, cmdfsal_thr_info__::context, cmdfsal_thr_info__::current_dir, cmdfsal_thr_info__::current_path, GetFSALCmdContext(), Getopt(), Init_Thread_Context(), cmdfsal_thr_info__::is_thread_ok, NULL, Optind, Optopt, print_fsal_status(), solvepath(), and split_path().
int fn_fsal_ls (int argc, char ** argv, FILE * output)
proceed an ls command.
Definition at line 1522 of file commands_FSAL.c.
References cmdfsal_thr_info_t, cmdfsal_thr_info__::context, cmdfsal_thr_info__::current_dir, cmdfsal_thr_info__::current_path, GetFSALCmdContext(), Getopt(), Init_Thread_Context(), cmdfsal_thr_info__::is_thread_ok, NULL, Optind, Optopt, print_fsal_attributes(), print_fsal_status(), print_item_line(), READDIR_SIZE, and solvepath().
int fn_fsal_lsxattrs (int argc, char ** argv, FILE * output)
list extended attributes.
Definition at line 1146 of file commands_FSAL.c.
References cmdfsal_thr_info_t, cmdfsal_thr_info__::context, cmdfsal_thr_info__::current_dir, cmdfsal_thr_info__::current_path, GetFSALCmdContext(), Getopt(), Init_Thread_Context(), cmdfsal_thr_info__::is_thread_ok, Optind, Optopt, print_fsal_status(), and solvepath().
int fn_fsal_mkdir (int argc, char ** argv, FILE * output)
proceed an mkdir command.
Definition at line 2086 of file commands_FSAL.c.
References atomode(), cmdfsal_thr_info_t, cmdfsal_thr_info__::context, cmdfsal_thr_info__::current_dir, cmdfsal_thr_info__::current_path, GetFSALCmdContext(), Getopt(), Init_Thread_Context(), cmdfsal_thr_info__::is_thread_ok, NULL, Optind, Optopt, print_fsal_status(), solvepath(), and split_path().
int fn_fsal_open (int argc, char ** argv, FILE * output)
Command that opens a file using specific flags. open <path> [ rwat ]
Definition at line 3693 of file commands_FSAL.c.
References cmdfsal_thr_info_t, cmdfsal_thr_info__::context, cmdfsal_thr_info__::current_dir, cmdfsal_thr_info__::current_fd, cmdfsal_thr_info__::current_path, GetFSALCmdContext(), Getopt(), Init_Thread_Context(), cmdfsal_thr_info__::is_thread_ok, NULL, cmdfsal_thr_info__::opened, Optind, Optopt, print_fsal_status(), and solvepath().
int fn_fsal_open_byfileid (int argc, char ** argv, FILE * output)
Command that opens a file using specific flags. open <path> [ rwat ]
Definition at line 3884 of file commands_FSAL.c.
References cmdfsal_thr_info_t, cmdfsal_thr_info__::context, cmdfsal_thr_info__::current_dir, cmdfsal_thr_info__::current_fd, cmdfsal_thr_info__::current_path, GetFSALCmdContext(), Getopt(), Init_Thread_Context(), cmdfsal_thr_info__::is_thread_ok, NULL, cmdfsal_thr_info__::opened, Optind, Optopt, print_fsal_status(), and solvepath().
int fn_fsal_open_byname (int argc, char ** argv, FILE * output)
Command that opens a file using specific flags, but using FSAL_open_by_name. open <path> [ rwat ]
Definition at line 3498 of file commands_FSAL.c.
References cmdfsal_thr_info_t, cmdfsal_thr_info__::context, cmdfsal_thr_info__::current_dir, cmdfsal_thr_info__::current_fd, GetFSALCmdContext(), Getopt(), Init_Thread_Context(), cmdfsal_thr_info__::is_thread_ok, NULL, cmdfsal_thr_info__::opened, Optind, Optopt, and print_fsal_status().
int fn_fsal_pwd (int argc, char ** argv, FILE * output)
prints current path
Definition at line 713 of file commands_FSAL.c.
References cmdfsal_thr_info_t, cmdfsal_thr_info__::current_dir, cmdfsal_thr_info__::current_path, GetFSALCmdContext(), Init_Thread_Context(), and cmdfsal_thr_info__::is_thread_ok.
int fn_fsal_rcp (int argc, char ** argv, FILE * output)
Command that copy a file from/to the local filesystem. rcp [-h] -r|-w <fsal_path> <local_path>
Definition at line 5269 of file commands_FSAL.c.
References cmdfsal_thr_info_t, cmdfsal_thr_info__::context, cmdfsal_thr_info__::current_dir, cmdfsal_thr_info__::current_path, GetFSALCmdContext(), Getopt(), Init_Thread_Context(), cmdfsal_thr_info__::is_thread_ok, Optind, Optopt, print_fsal_status(), and solvepath().
int fn_fsal_read (int argc, char ** argv, FILE * output)
Command that reads data from an opened file.
Definition at line 4081 of file commands_FSAL.c.
References ato64(), cmdfsal_thr_info_t, GetFSALCmdContext(), Getopt(), Init_Thread_Context(), NULL, Optarg, Optind, Optopt, print_fsal_status(), print_timeval, and time_diff().
int fn_fsal_rename (int argc, char ** argv, FILE * output)
proceed a rename command.
Definition at line 2255 of file commands_FSAL.c.
References cmdfsal_thr_info_t, cmdfsal_thr_info__::context, cmdfsal_thr_info__::current_dir, cmdfsal_thr_info__::current_path, GetFSALCmdContext(), Getopt(), Init_Thread_Context(), cmdfsal_thr_info__::is_thread_ok, NULL, Optind, Optopt, print_fsal_status(), solvepath(), and split_path().
int fn_fsal_setattr (int argc, char ** argv, FILE * output)
change file attributes.
Definition at line 2939 of file commands_FSAL.c.
References ATTR_32, ATTR_64, shell_attribute__::attr_name, ATTR_OCTAL, ATTR_TIME, shell_attribute__::attr_type, cmdfsal_thr_info_t, cmdfsal_thr_info__::context, cmdfsal_thr_info__::current_dir, cmdfsal_thr_info__::current_path, GetFSALCmdContext(), Getopt(), Init_Thread_Context(), cmdfsal_thr_info__::is_thread_ok, MkFSALSetAttrStruct(), NULL, Optind, Optopt, print_fsal_attributes(), print_fsal_status(), shell_attribute_t, and solvepath().
int fn_fsal_stat (int argc, char ** argv, FILE * output)
proceed a stat command.
Definition at line 1019 of file commands_FSAL.c.
References cmdfsal_thr_info_t, cmdfsal_thr_info__::context, cmdfsal_thr_info__::current_dir, cmdfsal_thr_info__::current_path, GetFSALCmdContext(), Getopt(), Init_Thread_Context(), cmdfsal_thr_info__::is_thread_ok, Optind, Optopt, print_fsal_attrib_mask(), print_fsal_attributes(), print_fsal_status(), and solvepath().
int fn_fsal_su (int argc, char ** argv, FILE * output)
change thread contexte.
Definition at line 1854 of file commands_FSAL.c.
References cmdfsal_thr_info_t, cmdfsal_thr_info__::context, cmdfsal_thr_info__::exp_context, GetFSALCmdContext(), getugroups(), Init_Thread_Context(), cmdfsal_thr_info__::is_thread_ok, MAX_GRPS, my_atoi(), and print_fsal_status().
int fn_fsal_truncate (int argc, char ** argv, FILE * output)
proceed a truncate command.
Definition at line 3370 of file commands_FSAL.c.
References ato64(), cmdfsal_thr_info_t, cmdfsal_thr_info__::context, cmdfsal_thr_info__::current_dir, cmdfsal_thr_info__::current_path, GetFSALCmdContext(), Getopt(), Init_Thread_Context(), cmdfsal_thr_info__::is_thread_ok, NULL, Optind, Optopt, print_fsal_status(), and solvepath().
int fn_fsal_unlink (int argc, char ** argv, FILE * output)
proceed an unlink command.
Definition at line 1960 of file commands_FSAL.c.
References cmdfsal_thr_info_t, cmdfsal_thr_info__::context, cmdfsal_thr_info__::current_dir, cmdfsal_thr_info__::current_path, GetFSALCmdContext(), Getopt(), Init_Thread_Context(), cmdfsal_thr_info__::is_thread_ok, NULL, Optind, Optopt, print_fsal_status(), solvepath(), and split_path().
int fn_fsal_write (int argc, char ** argv, FILE * output)
Command that writes data to an opened file.
Usage: write [-h][-v] [ -s <seek_type>,<offset> ] [-N <nb_times>] -A <ascii_string> write [-h][-v] [ -s <seek_type>,<offset> ] [-N <nb_times>] -X <hexa_data> Where: <seek_type> can be: SET, CUR, END <offset> is a signed number of bytes. <nb_times> is the number of times we write the expression into the file.
<ascii_string> is a string to be written to file. Note that the null terminating character of is also written to file. or <hexa_data> is a data represented in hexadecimal format, that is to be written to file.
Examples:
For writing 10 times the null terminated string `hello world` at the end of the file: write -s END,0 -N 10 -A `hello world`
For overwriting the beginning of the file with the pattern 0xA1267AEF31254ADE repeated twice: write -s SET,0 -N 2 -X `A1267AEF31254ADE`
Definition at line 4525 of file commands_FSAL.c.
References ato64(), cmdfsal_thr_info_t, GetFSALCmdContext(), Getopt(), Init_Thread_Context(), NULL, Optarg, Optind, Optopt, print_fsal_status(), print_timeval, and time_diff().
int fsal_init (char * filename, int flag_v, FILE * output)
Definition at line 507 of file commands_FSAL.c.
References cmdfsal_thr_info_t, GetFSALCmdContext(), Init_Thread_Context(), cmdfsal_thr_info__::is_thread_ok, and print_fsal_status().
Referenced by fn_fsal_init_fs().
void fsal_layer_SetLogLevel (int log_lvl)
Definition at line 473 of file commands_FSAL.c.
cmdfsal_thr_info_t* GetFSALCmdContext ()
GetFSALCmdContext : manages pthread_keys.
Definition at line 347 of file commands_FSAL.c.
References cmdfsal_thr_info_t, cmdfsal_thr_info__::current_path, cmdfsal_thr_info__::is_thread_ok, and cmdfsal_thr_info__::opened.
Referenced by fn_fsal_access(), fn_fsal_cat(), fn_fsal_cd(), fn_fsal_close(), fn_fsal_close_byfileid(), fn_fsal_create(), fn_fsal_cross(), fn_fsal_getxattr(), fn_fsal_handlecmp(), fn_fsal_hardlink(), fn_fsal_ln(), fn_fsal_ls(), fn_fsal_lsxattrs(), fn_fsal_mkdir(), fn_fsal_open(), fn_fsal_open_byfileid(), fn_fsal_open_byname(), fn_fsal_pwd(), fn_fsal_rcp(), fn_fsal_read(), fn_fsal_rename(), fn_fsal_setattr(), fn_fsal_stat(), fn_fsal_su(), fn_fsal_truncate(), fn_fsal_unlink(), fn_fsal_write(), fsal_init(), and solvepath().
int Init_Thread_Context (FILE * output, cmdfsal_thr_info_t * context, int flag_v)
Initialize thread specific FSAL environment.
Definition at line 395 of file commands_FSAL.c.
References cmdfsal_thr_info_t, cmdfsal_thr_info__::context, cmdfsal_thr_info__::current_dir, cmdfsal_thr_info__::current_path, cmdfsal_thr_info__::exp_context, cmdfsal_thr_info__::is_thread_ok, NULL, and print_fsal_status().
Referenced by fn_fsal_access(), fn_fsal_cat(), fn_fsal_cd(), fn_fsal_close(), fn_fsal_close_byfileid(), fn_fsal_create(), fn_fsal_cross(), fn_fsal_getxattr(), fn_fsal_handlecmp(), fn_fsal_hardlink(), fn_fsal_ln(), fn_fsal_ls(), fn_fsal_lsxattrs(), fn_fsal_mkdir(), fn_fsal_open(), fn_fsal_open_byfileid(), fn_fsal_open_byname(), fn_fsal_pwd(), fn_fsal_rcp(), fn_fsal_read(), fn_fsal_rename(), fn_fsal_setattr(), fn_fsal_stat(), fn_fsal_su(), fn_fsal_truncate(), fn_fsal_unlink(), fn_fsal_write(), fsal_init(), and solvepath().
int solvepath (char * io_global_path, int size_global_path, char * i_spec_path, fsal_handle_t i_current_handle, fsal_handle_t * new_handle, FILE * output)
Definition at line 757 of file commands_FSAL.c.
References clean_path(), cmdfsal_thr_info_t, cmdfsal_thr_info__::context, GetFSALCmdContext(), Init_Thread_Context(), cmdfsal_thr_info__::is_thread_ok, NULL, and print_fsal_status().
Referenced by fn_fsal_access(), fn_fsal_cat(), fn_fsal_cd(), fn_fsal_create(), fn_fsal_cross(), fn_fsal_getxattr(), fn_fsal_handlecmp(), fn_fsal_hardlink(), fn_fsal_ln(), fn_fsal_ls(), fn_fsal_lsxattrs(), fn_fsal_mkdir(), fn_fsal_open(), fn_fsal_open_byfileid(), fn_fsal_rcp(), fn_fsal_rename(), fn_fsal_setattr(), fn_fsal_stat(), fn_fsal_truncate(), and fn_fsal_unlink().