commands_NFS.c File Reference
calls to NFSv2, NFSv3, MNTv1, MNTv3 commands.
#include <rpc/types.h>
#include <rpc/rpc.h>
#include <rpc/svc.h>
#include <rpc/auth.h>
#include `fsal.h`
#include `cache_inode.h`
#include `cache_content.h`
#include `commands.h`
#include `stuff_alloc.h`
#include `Getopt.h`
#include `cmd_nfstools.h`
#include `cmd_tools.h`
#include `nfs_file_handle.h`
#include `nfs_core.h`
#include <ctype.h>
#include <unistd.h>
#include <pwd.h>
#include <string.h>
Classes
struct shell_fh3__
struct cmdnfs_thr_info__
Defines
#define NFS_READDIR_SIZE 10
#define MAX_GRPS 128
Typedefs
typedef shell_fh3__ shell_fh3_t
typedef cmdnfs_thr_info__ cmdnfs_thr_info_t
Functions
cmdnfs_thr_info_t * GetNFSClient ()
int InitNFSClient (cmdnfs_thr_info_t *p_thr_info)
void nfs_layer_SetLogLevel (int log_lvl)
int nfs_init (char *filename, int flag_v, FILE *output)
int fn_nfs_init (int argc, char **argv, FILE *output)
int fn_MNT1_command (int argc, char **argv, FILE *output)
int fn_MNT3_command (int argc, char **argv, FILE *output)
int fn_NFS2_command (int argc, char **argv, FILE *output)
int fn_NFS3_command (int argc, char **argv, FILE *output)
void nfs_readdirplus_free (nfs_res_t *to_free)
int fn_nfs_mount (int argc, char **argv, FILE *output)
int fn_nfs_umount (int argc, char **argv, FILE *output)
int fn_nfs_pwd (int argc, char **argv, FILE *output)
int fn_nfs_ls (int argc, char **argv, FILE *output)
int fn_nfs_cd (int argc, char **argv, FILE *output)
int fn_nfs_create (int argc, char **argv, FILE *output)
int fn_nfs_mkdir (int argc, char **argv, FILE *output)
int fn_nfs_unlink (int argc, char **argv, FILE *output)
int fn_nfs_setattr (int argc, char **argv, FILE *output)
int fn_nfs_rename (int argc, char **argv, FILE *output)
int fn_nfs_hardlink (int argc, char **argv, FILE *output)
int fn_nfs_ln (int argc, char **argv, FILE *output)
int fn_nfs_stat (int argc, char **argv, FILE *output)
int fn_nfs_su (int argc, char **argv, FILE *output)
int fn_nfs_id (int argc, char **argv, FILE *output)
Variables
nfs_parameter_t nfs_param
hash_table_t * ht
cache_inode_client_parameter_t cache_client_param
cache_content_client_parameter_t datacache_client_param
exportlist_t exportlist [128]
exportlist_t * pexportlist = exportlist
Detailed Description
calls to NFSv2, NFSv3, MNTv1, MNTv3 commands.
Author:
Author leibovic
Date:
Date 2006/02/23 07:42:53
Version:
Revision 1.34
Log commands_NFS.c(p.),v
Revision 1.34 2006/02/23 07:42:53 leibovic Adding -n option to shell.
Revision 1.33 2006/02/22 09:07:45 leibovic Correcting bug for returned value.
Revision 1.32 2006/02/17 13:37:44 leibovic Ghost FS is back !
Revision 1.31 2006/01/27 10:28:37 deniel Now support rpm
Revision 1.30 2006/01/26 07:54:44 leibovic Compil AIX_5 et Linux OK.
Revision 1.29 2006/01/25 09:39:44 deniel pb include DCE
Revision 1.28 2006/01/24 13:49:33 leibovic Adding missing includes.
Revision 1.27 2006/01/24 11:43:05 deniel Code cleaning in progress
Revision 1.26 2006/01/20 14:44:14 leibovic altgroups support.
Revision 1.25 2006/01/18 08:02:04 deniel Order in includes and libraries
Revision 1.24 2006/01/17 16:40:54 leibovic New interface for readexport.
Revision 1.23 2005/11/28 17:03:00 deniel Added CeCILL headers
Revision 1.22 2005/11/21 09:55:18 leibovic Once for all thread's credential initialization.
Revision 1.21 2005/11/08 15:22:24 deniel WildCard and Netgroup entry for exportlist are now supported
Revision 1.20 2005/11/04 15:12:58 deniel Added basic authentication support
Revision 1.19 2005/10/12 11:30:10 leibovic NFSv2.
Revision 1.18 2005/10/10 12:39:08 leibovic Using mnt/nfs free functions.
Revision 1.17 2005/09/28 11:02:29 leibovic Adding su command to NFS layer.
Revision 1.16 2005/09/27 08:15:13 leibovic Adding traces and changhing readexport prototype.
Revision 1.15 2005/09/07 14:08:32 leibovic Adding stat command for NFS.
Revision 1.14 2005/08/12 07:07:23 leibovic Adding ln command for nfs.
Revision 1.13 2005/08/10 14:55:05 leibovic NFS support of setattr, rename, link, symlink.
Revision 1.12 2005/08/10 10:57:18 leibovic Adding removal functions.
Revision 1.11 2005/08/09 14:52:58 leibovic Addinf create and mkdir commands.
Revision 1.10 2005/08/08 11:42:50 leibovic Adding some stardard unix calls through NFS (ls, cd, pwd).
Revision 1.9 2005/08/05 15:17:57 leibovic Adding mount and pwd commands for browsing.
Revision 1.8 2005/08/05 07:59:07 leibovic some nfs3 commands added.
Revision 1.7 2005/08/04 06:57:41 leibovic some NFSv2 commands are completed.
Revision 1.6 2005/08/03 12:51:16 leibovic MNT3 protocol OK.
Revision 1.5 2005/08/03 11:51:10 leibovic MNT1 protocol OK.
Revision 1.4 2005/08/03 08:16:23 leibovic Adding nfs layer structures.
Revision 1.3 2005/05/09 12:23:55 leibovic Version 2 of ganeshell.
Revision 1.2 2005/03/04 10:12:15 leibovic New debug functions.
Revision 1.1 2005/01/21 09:40:31 leibovic Integrating NFS and MNT protocol commands.
Definition in file commands_NFS.c.
Define Documentation
#define MAX_GRPS 128
#define NFS_READDIR_SIZE 10
Typedef Documentation
typedef struct cmdnfs_thr_info__ cmdnfs_thr_info_t
Referenced by fn_MNT1_command(), fn_MNT3_command(), fn_NFS2_command(), fn_NFS3_command(), fn_nfs_cd(), fn_nfs_create(), fn_nfs_hardlink(), fn_nfs_id(), fn_nfs_ln(), fn_nfs_ls(), fn_nfs_mkdir(), fn_nfs_mount(), fn_nfs_pwd(), fn_nfs_rename(), fn_nfs_setattr(), fn_nfs_stat(), fn_nfs_su(), fn_nfs_umount(), fn_nfs_unlink(), GetNFSClient(), and InitNFSClient().
typedef struct shell_fh3__ shell_fh3_t
Referenced by fn_nfs_cd(), fn_nfs_create(), fn_nfs_hardlink(), fn_nfs_ln(), fn_nfs_ls(), fn_nfs_mkdir(), fn_nfs_remote_cd(), fn_nfs_remote_create(), fn_nfs_remote_hardlink(), fn_nfs_remote_ln(), fn_nfs_remote_ls(), fn_nfs_remote_mkdir(), fn_nfs_remote_mount(), fn_nfs_remote_rename(), fn_nfs_remote_setattr(), fn_nfs_remote_stat(), fn_nfs_remote_umount(), fn_nfs_remote_unlink(), fn_nfs_rename(), fn_nfs_setattr(), fn_nfs_stat(), fn_nfs_unlink(), nfs_remote_access(), nfs_remote_create(), nfs_remote_getattr(), nfs_remote_link(), nfs_remote_mkdir(), nfs_remote_mount(), nfs_remote_readdir(), nfs_remote_readdirplus(), nfs_remote_readlink(), nfs_remote_remove(), nfs_remote_rename(), nfs_remote_rmdir(), nfs_remote_setattr(), nfs_remote_solvepath(), and nfs_remote_symlink().
Function Documentation
int fn_MNT1_command (int argc, char ** argv, FILE * output)
process MNT1 protocol's command.
Definition at line 623 of file commands_NFS.c.
References cmdnfs_thr_info__::authunix_struct, cmdnfs_thr_info__::client, CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_funcdesc_t, cmdnfs_thr_info_t, cmdnfs_thr_info__::context, cmdnfs_funcdesc__::func_call, cmdnfs_funcdesc__::func_decode, cmdnfs_funcdesc__::func_encode, cmdnfs_funcdesc__::func_free, cmdnfs_funcdesc__::func_help, cmdnfs_funcdesc__::func_name, GetNFSClient(), ht, InitNFSClient(), cmdnfs_thr_info__::is_thread_init, NULL, and pexportlist.
int fn_MNT3_command (int argc, char ** argv, FILE * output)
process MNT3 protocol's command.
Definition at line 727 of file commands_NFS.c.
References cmdnfs_thr_info__::authunix_struct, cmdnfs_thr_info__::client, CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_funcdesc_t, cmdnfs_thr_info_t, cmdnfs_thr_info__::context, cmdnfs_funcdesc__::func_call, cmdnfs_funcdesc__::func_decode, cmdnfs_funcdesc__::func_encode, cmdnfs_funcdesc__::func_free, cmdnfs_funcdesc__::func_help, cmdnfs_funcdesc__::func_name, GetNFSClient(), ht, InitNFSClient(), cmdnfs_thr_info__::is_thread_init, NULL, and pexportlist.
int fn_NFS2_command (int argc, char ** argv, FILE * output)
process NFS2 protocol's command.
Definition at line 828 of file commands_NFS.c.
References cmdnfs_thr_info__::authunix_struct, cmdnfs_thr_info__::client, CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_funcdesc_t, cmdnfs_thr_info_t, cmdnfs_thr_info__::context, cmdnfs_funcdesc__::func_call, cmdnfs_funcdesc__::func_decode, cmdnfs_funcdesc__::func_encode, cmdnfs_funcdesc__::func_free, cmdnfs_funcdesc__::func_help, cmdnfs_funcdesc__::func_name, GetNFSClient(), ht, InitNFSClient(), cmdnfs_thr_info__::is_thread_init, NULL, and pexportlist.
int fn_NFS3_command (int argc, char ** argv, FILE * output)
process NFS3 protocol's command.
Definition at line 947 of file commands_NFS.c.
References cmdnfs_thr_info__::authunix_struct, cmdnfs_thr_info__::client, CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_funcdesc_t, cmdnfs_thr_info_t, cmdnfs_thr_info__::context, cmdnfs_funcdesc__::func_call, cmdnfs_funcdesc__::func_decode, cmdnfs_funcdesc__::func_encode, cmdnfs_funcdesc__::func_free, cmdnfs_funcdesc__::func_help, cmdnfs_funcdesc__::func_name, GetNFSClient(), ht, InitNFSClient(), cmdnfs_thr_info__::is_thread_init, NULL, and pexportlist.
int fn_nfs_cd (int argc, char ** argv, FILE * output)
change current path
Definition at line 2682 of file commands_NFS.c.
References cmdnfs_thr_info_t, cmdnfs_thr_info__::current_path, cmdnfs_thr_info__::current_path_hdl, shell_fh3__::data_len, shell_fh3__::data_val, GetNFSClient(), cmdnfs_thr_info__::is_mounted_path, and shell_fh3_t.
int fn_nfs_create (int argc, char ** argv, FILE * output)
create a file
Definition at line 2768 of file commands_NFS.c.
References atomode(), cmdnfs_thr_info_t, cmdnfs_thr_info__::current_path, cmdnfs_thr_info__::current_path_hdl, shell_fh3__::data_len, shell_fh3__::data_val, GetNFSClient(), Getopt(), cmdnfs_thr_info__::is_mounted_path, Optind, Optopt, shell_fh3_t, and split_path().
int fn_nfs_hardlink (int argc, char ** argv, FILE * output)
proceed a hardlink command.
Definition at line 3415 of file commands_NFS.c.
References cmdnfs_thr_info_t, cmdnfs_thr_info__::current_path, cmdnfs_thr_info__::current_path_hdl, GetNFSClient(), Getopt(), cmdnfs_thr_info__::is_mounted_path, Optind, Optopt, shell_fh3_t, and split_path().
int fn_nfs_id (int argc, char ** argv, FILE * output)
Definition at line 3965 of file commands_NFS.c.
References cmdnfs_thr_info_t, cmdnfs_thr_info__::context, GetNFSClient(), InitNFSClient(), and cmdnfs_thr_info__::is_thread_init.
int fn_nfs_init (int argc, char ** argv, FILE * output)
Init nfs layer
Definition at line 536 of file commands_NFS.c.
References Getopt(), nfs_init(), Optind, and Optopt.
int fn_nfs_ln (int argc, char ** argv, FILE * output)
proceed an ln command.
Definition at line 3548 of file commands_NFS.c.
References CMDNFS_ENCODE, cmdnfs_sattr3(), cmdnfs_thr_info_t, cmdnfs_thr_info__::current_path, cmdnfs_thr_info__::current_path_hdl, shell_fh3__::data_len, shell_fh3__::data_val, GetNFSClient(), Getopt(), cmdnfs_thr_info__::is_mounted_path, NULL, Optind, Optopt, shell_fh3_t, and split_path().
int fn_nfs_ls (int argc, char ** argv, FILE * output)
proceed an ls command using NFS protocol NFS
Definition at line 2341 of file commands_NFS.c.
References cmdnfs_thr_info_t, cmdnfs_thr_info__::current_path, cmdnfs_thr_info__::current_path_hdl, shell_fh3__::data_len, shell_fh3__::data_val, GetNFSClient(), Getopt(), cmdnfs_thr_info__::is_mounted_path, nfs_readdirplus_free(), Optind, Optopt, print_nfs_attributes(), print_nfsitem_line(), and shell_fh3_t.
int fn_nfs_mkdir (int argc, char ** argv, FILE * output)
create a directory
Definition at line 2895 of file commands_NFS.c.
References atomode(), cmdnfs_thr_info_t, cmdnfs_thr_info__::current_path, cmdnfs_thr_info__::current_path_hdl, shell_fh3__::data_len, shell_fh3__::data_val, GetNFSClient(), Getopt(), cmdnfs_thr_info__::is_mounted_path, Optind, Optopt, shell_fh3_t, and split_path().
int fn_nfs_mount (int argc, char ** argv, FILE * output)
mount a path to browse it.
Definition at line 2100 of file commands_NFS.c.
References cmdnfs_thr_info__::authunix_struct, cmdnfs_thr_info__::client, cmdnfs_dirpath(), CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_thr_info_t, cmdnfs_thr_info__::context, cmdnfs_thr_info__::current_path, cmdnfs_thr_info__::current_path_hdl, shell_fh3__::data_len, shell_fh3__::data_val, GetNFSClient(), ht, InitNFSClient(), cmdnfs_thr_info__::is_mounted_path, cmdnfs_thr_info__::is_thread_init, cmdnfs_thr_info__::mounted_path, cmdnfs_thr_info__::mounted_path_hdl, NULL, and pexportlist.
int fn_nfs_pwd (int argc, char ** argv, FILE * output)
prints current path
Definition at line 2306 of file commands_NFS.c.
References cmdnfs_thr_info_t, cmdnfs_thr_info__::current_path, cmdnfs_thr_info__::current_path_hdl, shell_fh3__::data_len, shell_fh3__::data_val, GetNFSClient(), and cmdnfs_thr_info__::is_mounted_path.
int fn_nfs_rename (int argc, char ** argv, FILE * output)
proceed a rename command.
Definition at line 3278 of file commands_NFS.c.
References cmdnfs_thr_info_t, cmdnfs_thr_info__::current_path, cmdnfs_thr_info__::current_path_hdl, GetNFSClient(), Getopt(), cmdnfs_thr_info__::is_mounted_path, Optind, Optopt, shell_fh3_t, and split_path().
int fn_nfs_setattr (int argc, char ** argv, FILE * output)
setattr
Definition at line 3153 of file commands_NFS.c.
References CMDNFS_ENCODE, cmdnfs_sattr3(), cmdnfs_thr_info_t, cmdnfs_thr_info__::current_path, cmdnfs_thr_info__::current_path_hdl, GetNFSClient(), Getopt(), cmdnfs_thr_info__::is_mounted_path, NULL, Optind, Optopt, and shell_fh3_t.
int fn_nfs_stat (int argc, char ** argv, FILE * output)
proceed an ls command using NFS protocol NFS
Definition at line 3689 of file commands_NFS.c.
References cmdnfs_thr_info_t, cmdnfs_thr_info__::current_path, cmdnfs_thr_info__::current_path_hdl, shell_fh3__::data_len, shell_fh3__::data_val, GetNFSClient(), Getopt(), cmdnfs_thr_info__::is_mounted_path, Optind, Optopt, print_nfs_attributes(), and shell_fh3_t.
int fn_nfs_su (int argc, char ** argv, FILE * output)
change thread credentials.
Definition at line 3861 of file commands_NFS.c.
References cmdnfs_thr_info_t, cmdnfs_thr_info__::context, cmdnfs_thr_info__::exp_context, GetNFSClient(), getugroups(), InitNFSClient(), cmdnfs_thr_info__::is_thread_init, MAX_GRPS, my_atoi(), and print_fsal_status().
int fn_nfs_umount (int argc, char ** argv, FILE * output)
umount a mounted path.
Definition at line 2211 of file commands_NFS.c.
References cmdnfs_thr_info__::authunix_struct, cmdnfs_thr_info__::client, cmdnfs_dirpath(), CMDNFS_ENCODE, CMDNFS_FREE, cmdnfs_thr_info_t, cmdnfs_thr_info__::context, GetNFSClient(), ht, InitNFSClient(), cmdnfs_thr_info__::is_mounted_path, cmdnfs_thr_info__::is_thread_init, cmdnfs_thr_info__::mounted_path, NULL, and pexportlist.
int fn_nfs_unlink (int argc, char ** argv, FILE * output)
unlink a file
Definition at line 3021 of file commands_NFS.c.
References cmdnfs_thr_info_t, cmdnfs_thr_info__::current_path, cmdnfs_thr_info__::current_path_hdl, GetNFSClient(), Getopt(), cmdnfs_thr_info__::is_mounted_path, Optind, Optopt, shell_fh3_t, and split_path().
cmdnfs_thr_info_t* GetNFSClient ()
Definition at line 337 of file commands_NFS.c.
References cmdnfs_thr_info_t, cmdnfs_thr_info__::is_mounted_path, and cmdnfs_thr_info__::is_thread_init.
Referenced by fn_MNT1_command(), fn_MNT3_command(), fn_NFS2_command(), fn_NFS3_command(), fn_nfs_cd(), fn_nfs_create(), fn_nfs_hardlink(), fn_nfs_id(), fn_nfs_ln(), fn_nfs_ls(), fn_nfs_mkdir(), fn_nfs_mount(), fn_nfs_pwd(), fn_nfs_rename(), fn_nfs_setattr(), fn_nfs_stat(), fn_nfs_su(), fn_nfs_umount(), and fn_nfs_unlink().
int InitNFSClient (cmdnfs_thr_info_t * p_thr_info)
Todo No secondary groups support.
Definition at line 383 of file commands_NFS.c.
References cmdnfs_thr_info__::authunix_struct, cache_client_param, cmdnfs_thr_info__::client, cmdnfs_thr_info_t, cmdnfs_thr_info__::context, datacache_client_param, cmdnfs_thr_info__::dc_client, cmdnfs_thr_info__::exp_context, cmdnfs_thr_info__::is_thread_init, and NULL.
Referenced by fn_MNT1_command(), fn_MNT3_command(), fn_NFS2_command(), fn_NFS3_command(), fn_nfs_id(), fn_nfs_mount(), fn_nfs_su(), and fn_nfs_umount().
int nfs_init (char * filename, int flag_v, FILE * output)
Todo Are there other things to initialize ?
Definition at line 466 of file commands_NFS.c.
References ht, nfs_param, and pexportlist.
Referenced by fn_nfs_init().
void nfs_layer_SetLogLevel (int log_lvl)
Definition at line 450 of file commands_NFS.c.
void nfs_readdirplus_free (nfs_res_t * to_free)
Definition at line 1510 of file commands_NFS.c.
Referenced by fn_nfs_ls().
Variable Documentation
cache_inode_client_parameter_t cache_client_param
Global (exported) variable : init parameters for clients.
Definition at line 346 of file commands_Cache_inode.c.
Referenced by cacheinode_init(), and InitNFSClient().
cache_content_client_parameter_t datacache_client_param
Definition at line 347 of file commands_Cache_inode.c.
Referenced by cacheinode_init(), and InitNFSClient().
exportlist_t exportlist[128]
Definition at line 273 of file commands_NFS.c.
hash_table_t* ht
Global (exported) variable : The cache hash table
Definition at line 340 of file commands_Cache_inode.c.
Referenced by cache_solvepath(), cacheinode_init(), fn_Cache_inode_access(), fn_Cache_inode_cache_init(), fn_Cache_inode_callstat(), fn_Cache_inode_cd(), fn_Cache_inode_create(), fn_Cache_inode_data_cache(), fn_Cache_inode_flush_cache(), fn_Cache_inode_gc(), fn_Cache_inode_link(), fn_Cache_inode_ln(), fn_Cache_inode_ls(), fn_Cache_inode_mkdir(), fn_Cache_inode_pwd(), fn_Cache_inode_read(), fn_Cache_inode_recover_cache(), fn_Cache_inode_refresh_cache(), fn_Cache_inode_release_cache(), fn_Cache_inode_rename(), fn_Cache_inode_setattr(), fn_Cache_inode_stat(), fn_Cache_inode_su(), fn_Cache_inode_unlink(), fn_Cache_inode_write(), fn_MNT1_command(), fn_MNT3_command(), fn_NFS2_command(), fn_NFS3_command(), fn_nfs_mount(), fn_nfs_umount(), and nfs_init().
nfs_parameter_t nfs_param
Definition at line 220 of file commands_NFS.c.
Referenced by nfs_init().
exportlist_t* pexportlist = exportlist
Definition at line 274 of file commands_NFS.c.
Referenced by fn_MNT1_command(), fn_MNT3_command(), fn_NFS2_command(), fn_NFS3_command(), fn_nfs_mount(), fn_nfs_umount(), and nfs_init().