commands_NFS_remote.c File Reference
#include <rpc/types.h>
#include <rpc/rpc.h>
#include <rpc/auth.h>
#include <rpc/clnt.h>
#include <string.h>
#include `fsal.h`
#include `cache_inode.h`
#include `cache_content.h`
#include `commands.h`
#include `stuff_alloc.h`
#include `Getopt.h`
#include `cmd_nfstools.h`
#include `cmd_tools.h`
#include `nfs_file_handle.h`
#include `nfs_core.h`
#include `nfs23.h`
#include `mount.h`
#include <unistd.h>
#include <sys/types.h>
#include <pwd.h>
#include <ctype.h>
Classes
struct shell_fh3__
struct prog_vers_def__
struct prog_vers_client_def__
Defines
#define MAXIT 10
#define MAXRETRY 3
#define MAX_GRPS 128
#define NFS_READDIR_SIZE 10
#define MAX_GRPS 128
Typedefs
typedef shell_fh3__ shell_fh3_t
typedef prog_vers_def__ prog_vers_def_t
typedef prog_vers_client_def__ prog_vers_client_def_t
Functions
CLIENT * getCLIENT (char *name)
int setCLIENT (char *name, CLIENT *clnt)
char * getHostname (char *name)
int setHostname (char *name, char *hostname)
char * getProto (char *name)
int setProto (char *name, char *proto)
int getPort (char *name)
int setPort (char *name, int port)
int rpc_init (char *hostname, char *name, char *proto, int port, FILE *output)
int rpc_reinit (char *name, FILE *output)
int try_rpc_reinit (char *name, int error, FILE *output)
int switch_result (int result, int i, char *name, char *func_name, char *func_called_name, FILE *output)
int fn_rpc_init (int argc, char **argv, FILE *output)
void nfs_remote_layer_SetLogLevel (int log_lvl)
int fn_MNT1_remote_command (int argc, char **argv, FILE *output)
int fn_MNT3_remote_command (int argc, char **argv, FILE *output)
int fn_NFS2_remote_command (int argc, char **argv, FILE *output)
int fn_NFS3_remote_command (int argc, char **argv, FILE *output)
int nfs_remote_solvepath (shell_fh3_t *p_mounted_path_hdl, char *io_global_path, int size_global_path, char *i_spec_path, shell_fh3_t *p_current_hdl, shell_fh3_t *pnew_hdl, FILE *output)
int nfs_remote_getattr (shell_fh3_t *p_hdl, fattr3 *attrs, FILE *output)
int nfs_remote_access (shell_fh3_t *p_hdl, nfs3_uint32 *access_mask, FILE *output)
int nfs_remote_readlink (shell_fh3_t *p_hdl, char *linkcontent, FILE *output)
int nfs_remote_readdirplus (shell_fh3_t *p_dir_hdl, cookie3 cookie, cookieverf3 *p_cookieverf, dirlistplus3 *dirlist, nfs_res_t **to_be_freed, FILE *output)
void nfs_remote_readdirplus_free (nfs_res_t *to_free)
int nfs_remote_readdir (shell_fh3_t *p_dir_hdl, cookie3 cookie, cookieverf3 *p_cookieverf, dirlist3 *dirlist, nfs_res_t **to_be_freed, FILE *output)
void nfs_remote_readdir_free (nfs_res_t *to_free)
int nfs_remote_create (shell_fh3_t *p_dir_hdl, char *obj_name, mode_t posix_mode, shell_fh3_t *p_obj_hdl, FILE *output)
int nfs_remote_mkdir (shell_fh3_t *p_dir_hdl, char *obj_name, mode_t posix_mode, shell_fh3_t *p_obj_hdl, FILE *output)
int nfs_remote_rmdir (shell_fh3_t *p_dir_hdl, char *obj_name, FILE *output)
int nfs_remote_remove (shell_fh3_t *p_dir_hdl, char *obj_name, FILE *output)
int nfs_remote_setattr (shell_fh3_t *p_obj_hdl, sattr3 *p_attributes, FILE *output)
int nfs_remote_rename (shell_fh3_t *p_src_dir_hdl, char *src_name, shell_fh3_t *p_tgt_dir_hdl, char *tgt_name, FILE *output)
int nfs_remote_link (shell_fh3_t *p_file_hdl, shell_fh3_t *p_tgt_dir_hdl, char *tgt_name, FILE *output)
int nfs_remote_symlink (shell_fh3_t path_hdl, char *link_name, char *link_content, sattr3 *p_setattr, shell_fh3_t *p_link_hdl, FILE *output)
int nfs_remote_mount (char *str_path, shell_fh3_t *p_mnt_hdl, FILE *output)
int fn_nfs_remote_mount (int argc, char **argv, FILE *output)
int fn_nfs_remote_umount (int argc, char **argv, FILE *output)
int fn_nfs_remote_pwd (int argc, char **argv, FILE *output)
int fn_nfs_remote_ls (int argc, char **argv, FILE *output)
int fn_nfs_remote_cd (int argc, char **argv, FILE *output)
int fn_nfs_remote_create (int argc, char **argv, FILE *output)
int fn_nfs_remote_mkdir (int argc, char **argv, FILE *output)
int fn_nfs_remote_unlink (int argc, char **argv, FILE *output)
int fn_nfs_remote_setattr (int argc, char **argv, FILE *output)
int fn_nfs_remote_rename (int argc, char **argv, FILE *output)
int fn_nfs_remote_hardlink (int argc, char **argv, FILE *output)
int fn_nfs_remote_ln (int argc, char **argv, FILE *output)
int fn_nfs_remote_stat (int argc, char **argv, FILE *output)
int fn_nfs_remote_su (int argc, char **argv, FILE *output)
int fn_nfs_remote_id (int argc, char **argv, FILE *output)
Variables
nfs_parameter_t nfs_param
passwd * current_pw
Define Documentation
#define MAX_GRPS 128
#define MAX_GRPS 128
#define MAXIT 10
Definition at line 113 of file commands_NFS_remote.c.
#define MAXRETRY 3
Definition at line 114 of file commands_NFS_remote.c.
#define NFS_READDIR_SIZE 10
Typedef Documentation
typedef struct prog_vers_client_def__ prog_vers_client_def_t
Referenced by fn_nfs_remote_su(), getCLIENT(), getHostname(), getPort(), getProto(), setCLIENT(), setHostname(), setPort(), and setProto().
typedef struct prog_vers_def__ prog_vers_def_t
Referenced by rpc_init().
typedef struct shell_fh3__ shell_fh3_t
Function Documentation
int fn_MNT1_remote_command (int argc, char ** argv, FILE * output)
process MNT1 protocol's command.
Definition at line 666 of file commands_NFS_remote.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfsremote_funcdesc_t, cmdnfsremote_funcdesc__::func_call, cmdnfsremote_funcdesc__::func_decode, cmdnfsremote_funcdesc__::func_encode, cmdnfsremote_funcdesc__::func_free, cmdnfsremote_funcdesc__::func_help, cmdnfsremote_funcdesc__::func_name, getCLIENT(), NULL, and switch_result().
int fn_MNT3_remote_command (int argc, char ** argv, FILE * output)
process MNT3 protocol's command.
Definition at line 748 of file commands_NFS_remote.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfsremote_funcdesc_t, cmdnfsremote_funcdesc__::func_call, cmdnfsremote_funcdesc__::func_decode, cmdnfsremote_funcdesc__::func_encode, cmdnfsremote_funcdesc__::func_free, cmdnfsremote_funcdesc__::func_help, cmdnfsremote_funcdesc__::func_name, getCLIENT(), NULL, and switch_result().
int fn_NFS2_remote_command (int argc, char ** argv, FILE * output)
process NFS2 protocol's command.
Definition at line 830 of file commands_NFS_remote.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfsremote_funcdesc_t, cmdnfsremote_funcdesc__::func_call, cmdnfsremote_funcdesc__::func_decode, cmdnfsremote_funcdesc__::func_encode, cmdnfsremote_funcdesc__::func_free, cmdnfsremote_funcdesc__::func_help, cmdnfsremote_funcdesc__::func_name, getCLIENT(), NULL, and switch_result().
int fn_NFS3_remote_command (int argc, char ** argv, FILE * output)
process NFS3 protocol's command.
Definition at line 913 of file commands_NFS_remote.c.
References CMDNFS_DECODE, CMDNFS_ENCODE, CMDNFS_FREE, cmdnfsremote_funcdesc_t, cmdnfsremote_funcdesc__::func_call, cmdnfsremote_funcdesc__::func_decode, cmdnfsremote_funcdesc__::func_encode, cmdnfsremote_funcdesc__::func_free, cmdnfsremote_funcdesc__::func_help, cmdnfsremote_funcdesc__::func_name, getCLIENT(), NULL, and switch_result().
int fn_nfs_remote_cd (int argc, char ** argv, FILE * output)
change current path
Definition at line 2462 of file commands_NFS_remote.c.
References shell_fh3__::data_len, shell_fh3__::data_val, nfs_remote_access(), nfs_remote_getattr(), nfs_remote_solvepath(), and shell_fh3_t.
int fn_nfs_remote_create (int argc, char ** argv, FILE * output)
create a file
Definition at line 2538 of file commands_NFS_remote.c.
References atomode(), shell_fh3__::data_len, shell_fh3__::data_val, Getopt(), nfs_remote_create(), nfs_remote_solvepath(), Optind, Optopt, shell_fh3_t, and split_path().
int fn_nfs_remote_hardlink (int argc, char ** argv, FILE * output)
proceed a hardlink command.
Definition at line 3122 of file commands_NFS_remote.c.
References Getopt(), nfs_remote_link(), nfs_remote_solvepath(), Optind, Optopt, shell_fh3_t, and split_path().
int fn_nfs_remote_id (int argc, char ** argv, FILE * output)
Definition at line 3623 of file commands_NFS_remote.c.
References current_pw.
int fn_nfs_remote_ln (int argc, char ** argv, FILE * output)
proceed an ln command.
Definition at line 3244 of file commands_NFS_remote.c.
References CMDNFS_ENCODE, cmdnfs_sattr3(), shell_fh3__::data_len, shell_fh3__::data_val, Getopt(), nfs_remote_solvepath(), nfs_remote_symlink(), NULL, Optind, Optopt, shell_fh3_t, and split_path().
int fn_nfs_remote_ls (int argc, char ** argv, FILE * output)
proceed an ls command using NFS protocol NFS
Definition at line 2132 of file commands_NFS_remote.c.
References shell_fh3__::data_len, shell_fh3__::data_val, Getopt(), nfs_remote_getattr(), nfs_remote_readdirplus(), nfs_remote_readdirplus_free(), nfs_remote_readlink(), nfs_remote_solvepath(), Optind, Optopt, print_nfs_attributes(), print_nfsitem_line(), and shell_fh3_t.
int fn_nfs_remote_mkdir (int argc, char ** argv, FILE * output)
create a directory
Definition at line 2647 of file commands_NFS_remote.c.
References atomode(), shell_fh3__::data_len, shell_fh3__::data_val, Getopt(), nfs_remote_mkdir(), nfs_remote_solvepath(), Optind, Optopt, shell_fh3_t, and split_path().
int fn_nfs_remote_mount (int argc, char ** argv, FILE * output)
mount a path to browse it.
Definition at line 1985 of file commands_NFS_remote.c.
References shell_fh3__::data_len, shell_fh3__::data_val, nfs_remote_mount(), and shell_fh3_t.
int fn_nfs_remote_pwd (int argc, char ** argv, FILE * output)
prints current path
Definition at line 2109 of file commands_NFS_remote.c.
References shell_fh3__::data_len, and shell_fh3__::data_val.
int fn_nfs_remote_rename (int argc, char ** argv, FILE * output)
proceed a rename command.
Definition at line 2996 of file commands_NFS_remote.c.
References Getopt(), nfs_remote_rename(), nfs_remote_solvepath(), Optind, Optopt, shell_fh3_t, and split_path().
int fn_nfs_remote_setattr (int argc, char ** argv, FILE * output)
setattr
Definition at line 2881 of file commands_NFS_remote.c.
References CMDNFS_ENCODE, cmdnfs_sattr3(), Getopt(), nfs_remote_setattr(), nfs_remote_solvepath(), NULL, Optind, Optopt, and shell_fh3_t.
int fn_nfs_remote_stat (int argc, char ** argv, FILE * output)
proceed an ls command using NFS protocol NFS
Definition at line 3374 of file commands_NFS_remote.c.
References shell_fh3__::data_len, shell_fh3__::data_val, Getopt(), nfs_remote_getattr(), nfs_remote_solvepath(), Optind, Optopt, print_nfs_attributes(), and shell_fh3_t.
int fn_nfs_remote_su (int argc, char ** argv, FILE * output)
change thread credentials.
Definition at line 3535 of file commands_NFS_remote.c.
References prog_vers_client_def__::clnt, current_pw, getugroups(), MAX_GRPS, my_atoi(), prog_vers_client_def__::name, and prog_vers_client_def_t.
int fn_nfs_remote_umount (int argc, char ** argv, FILE * output)
umount a mounted path
Definition at line 2031 of file commands_NFS_remote.c.
References cmdnfs_dirpath(), CMDNFS_ENCODE, CMDNFS_FREE, getCLIENT(), mnt3_remote_Mnt(), mnt3_remote_Umnt_Free(), NULL, shell_fh3_t, and switch_result().
int fn_nfs_remote_unlink (int argc, char ** argv, FILE * output)
unlink a file
Definition at line 2759 of file commands_NFS_remote.c.
References Getopt(), nfs_remote_getattr(), nfs_remote_remove(), nfs_remote_rmdir(), nfs_remote_solvepath(), Optind, Optopt, shell_fh3_t, and split_path().
int fn_rpc_init (int argc, char ** argv, FILE * output)
fn_rpc_init
Definition at line 579 of file commands_NFS_remote.c.
References Getopt(), Optind, Optopt, and rpc_init().
CLIENT* getCLIENT (char * name)
getCLIENT
Definition at line 204 of file commands_NFS_remote.c.
References prog_vers_client_def__::clnt, prog_vers_client_def__::name, and prog_vers_client_def_t.
Referenced by fn_MNT1_remote_command(), fn_MNT3_remote_command(), fn_NFS2_remote_command(), fn_NFS3_remote_command(), fn_nfs_remote_umount(), nfs_remote_access(), nfs_remote_create(), nfs_remote_getattr(), nfs_remote_link(), nfs_remote_mkdir(), nfs_remote_mount(), nfs_remote_readdir(), nfs_remote_readdirplus(), nfs_remote_readlink(), nfs_remote_remove(), nfs_remote_rename(), nfs_remote_rmdir(), nfs_remote_setattr(), nfs_remote_solvepath(), and nfs_remote_symlink().
char* getHostname (char * name)
getHostname
Definition at line 238 of file commands_NFS_remote.c.
References prog_vers_client_def__::hostname, prog_vers_client_def__::name, and prog_vers_client_def_t.
Referenced by rpc_reinit().
int getPort (char * name)
getPort
Definition at line 306 of file commands_NFS_remote.c.
References prog_vers_client_def__::name, prog_vers_client_def__::port, and prog_vers_client_def_t.
Referenced by rpc_reinit().
char* getProto (char * name)
getProto
Definition at line 272 of file commands_NFS_remote.c.
References prog_vers_client_def__::name, prog_vers_client_def_t, and prog_vers_client_def__::proto.
Referenced by rpc_reinit().
int nfs_remote_access (shell_fh3_t * p_hdl, nfs3_uint32 * access_mask, FILE * output)
nfs_remote_access
Definition at line 1209 of file commands_NFS_remote.c.
References getCLIENT(), nfs3_remote_Access(), nfs3_remote_Access_Free(), shell_fh3_t, and switch_result().
Referenced by fn_nfs_remote_cd().
int nfs_remote_create (shell_fh3_t * p_dir_hdl, char * obj_name, mode_t posix_mode, shell_fh3_t * p_obj_hdl, FILE * output)
nfs_remote_create
Definition at line 1457 of file commands_NFS_remote.c.
References CMDNFS_ENCODE, cmdnfs_sattr3(), getCLIENT(), nfs3_remote_Create(), nfs3_remote_Create_Free(), NULL, shell_fh3_t, and switch_result().
Referenced by fn_nfs_remote_create().
int nfs_remote_getattr (shell_fh3_t * p_hdl, fattr3 * attrs, FILE * output)
nfs_remote_getattr
Definition at line 1159 of file commands_NFS_remote.c.
References getCLIENT(), nfs3_remote_Getattr(), nfs3_remote_Getattr_Free(), shell_fh3_t, and switch_result().
Referenced by fn_nfs_remote_cd(), fn_nfs_remote_ls(), fn_nfs_remote_stat(), and fn_nfs_remote_unlink().
void nfs_remote_layer_SetLogLevel (int log_lvl)
Definition at line 657 of file commands_NFS_remote.c.
int nfs_remote_link (shell_fh3_t * p_file_hdl, shell_fh3_t * p_tgt_dir_hdl, char * tgt_name, FILE * output)
nfs_remote_link
Definition at line 1805 of file commands_NFS_remote.c.
References getCLIENT(), nfs3_remote_Link(), nfs3_remote_Link_Free(), shell_fh3_t, and switch_result().
Referenced by fn_nfs_remote_hardlink().
int nfs_remote_mkdir (shell_fh3_t * p_dir_hdl, char * obj_name, mode_t posix_mode, shell_fh3_t * p_obj_hdl, FILE * output)
nfs_remote_mkdir
Definition at line 1531 of file commands_NFS_remote.c.
References CMDNFS_ENCODE, cmdnfs_sattr3(), getCLIENT(), nfs3_remote_Mkdir(), nfs3_remote_Mkdir_Free(), NULL, shell_fh3_t, and switch_result().
Referenced by fn_nfs_remote_mkdir().
int nfs_remote_mount (char * str_path, shell_fh3_t * p_mnt_hdl, FILE * output)
nfs_remote_mount
Definition at line 1922 of file commands_NFS_remote.c.
References cmdnfs_dirpath(), CMDNFS_ENCODE, CMDNFS_FREE, getCLIENT(), mnt3_remote_Mnt(), mnt3_remote_Mnt_Free(), NULL, shell_fh3_t, and switch_result().
Referenced by fn_nfs_remote_mount().
int nfs_remote_readdir (shell_fh3_t * p_dir_hdl, cookie3 cookie, cookieverf3 * p_cookieverf, dirlist3 * dirlist, nfs_res_t ** to_be_freed, FILE * output)
nfs_remote_readdir
Definition at line 1385 of file commands_NFS_remote.c.
References getCLIENT(), nfs3_remote_Readdir(), nfs3_remote_Readdir_Free(), shell_fh3_t, and switch_result().
void nfs_remote_readdir_free (nfs_res_t * to_free)
nfs_remote_readdir_free
Definition at line 1447 of file commands_NFS_remote.c.
References nfs3_remote_Readdir_Free().
int nfs_remote_readdirplus (shell_fh3_t * p_dir_hdl, cookie3 cookie, cookieverf3 * p_cookieverf, dirlistplus3 * dirlist, nfs_res_t ** to_be_freed, FILE * output)
nfs_remote_readdirplus
Definition at line 1312 of file commands_NFS_remote.c.
References getCLIENT(), nfs3_remote_Readdirplus(), nfs3_remote_Readdirplus_Free(), shell_fh3_t, and switch_result().
Referenced by fn_nfs_remote_ls().
void nfs_remote_readdirplus_free (nfs_res_t * to_free)
nfs_remote_readdirplus_free
Definition at line 1375 of file commands_NFS_remote.c.
References nfs3_remote_Readdirplus_Free().
Referenced by fn_nfs_remote_ls().
int nfs_remote_readlink (shell_fh3_t * p_hdl, char * linkcontent, FILE * output)
nfs_remote_readlink
Definition at line 1261 of file commands_NFS_remote.c.
References getCLIENT(), nfs3_remote_Readlink(), nfs3_remote_Readlink_Free(), shell_fh3_t, and switch_result().
Referenced by fn_nfs_remote_ls().
int nfs_remote_remove (shell_fh3_t * p_dir_hdl, char * obj_name, FILE * output)
nfs_remote_remove
Definition at line 1653 of file commands_NFS_remote.c.
References getCLIENT(), nfs3_remote_Remove(), nfs3_remote_Remove_Free(), shell_fh3_t, and switch_result().
Referenced by fn_nfs_remote_unlink().
int nfs_remote_rename (shell_fh3_t * p_src_dir_hdl, char * src_name, shell_fh3_t * p_tgt_dir_hdl, char * tgt_name, FILE * output)
nfs_remote_rename
Definition at line 1752 of file commands_NFS_remote.c.
References getCLIENT(), nfs3_remote_Rename(), nfs3_remote_Rename_Free(), shell_fh3_t, and switch_result().
Referenced by fn_nfs_remote_rename().
int nfs_remote_rmdir (shell_fh3_t * p_dir_hdl, char * obj_name, FILE * output)
nfs_remote_rmdir
Definition at line 1604 of file commands_NFS_remote.c.
References getCLIENT(), nfs3_remote_Rmdir(), nfs3_remote_Rmdir_Free(), shell_fh3_t, and switch_result().
Referenced by fn_nfs_remote_unlink().
int nfs_remote_setattr (shell_fh3_t * p_obj_hdl, sattr3 * p_attributes, FILE * output)
nfs_remote_setattr
Definition at line 1702 of file commands_NFS_remote.c.
References getCLIENT(), nfs3_remote_Setattr(), nfs3_remote_Setattr_Free(), shell_fh3_t, and switch_result().
Referenced by fn_nfs_remote_setattr().
int nfs_remote_solvepath (shell_fh3_t * p_mounted_path_hdl, char * io_global_path, int size_global_path, char * i_spec_path, shell_fh3_t * p_current_hdl, shell_fh3_t * pnew_hdl, FILE * output)
Definition at line 1001 of file commands_NFS_remote.c.
References clean_path(), CMDNFS_ENCODE, cmdnfs_fhandle3(), CMDNFS_FREE, getCLIENT(), nfs3_remote_Lookup(), nfs3_remote_Lookup_Free(), NULL, shell_fh3_t, and switch_result().
Referenced by fn_nfs_remote_cd(), fn_nfs_remote_create(), fn_nfs_remote_hardlink(), fn_nfs_remote_ln(), fn_nfs_remote_ls(), fn_nfs_remote_mkdir(), fn_nfs_remote_rename(), fn_nfs_remote_setattr(), fn_nfs_remote_stat(), and fn_nfs_remote_unlink().
int nfs_remote_symlink (shell_fh3_t path_hdl, char * link_name, char * link_content, sattr3 * p_setattr, shell_fh3_t * p_link_hdl, FILE * output)
nfs_remote_symlink
Definition at line 1856 of file commands_NFS_remote.c.
References getCLIENT(), nfs3_remote_Symlink(), nfs3_remote_Symlink_Free(), shell_fh3_t, and switch_result().
Referenced by fn_nfs_remote_ln().
int rpc_init (char * hostname, char * name, char * proto, int port, FILE * output)
rpc_init
Definition at line 357 of file commands_NFS_remote.c.
References current_pw, getugroups(), MAX_GRPS, prog_vers_def__::name, prog_vers_def__::prog, prog_vers_def_t, setCLIENT(), setHostname(), setPort(), setProto(), and prog_vers_def__::vers.
Referenced by fn_rpc_init(), and rpc_reinit().
int rpc_reinit (char * name, FILE * output)
rpc_reinit
Definition at line 487 of file commands_NFS_remote.c.
References getHostname(), getPort(), getProto(), and rpc_init().
Referenced by try_rpc_reinit().
int setCLIENT (char * name, CLIENT * clnt)
setCLIENT
Definition at line 220 of file commands_NFS_remote.c.
References prog_vers_client_def__::clnt, prog_vers_client_def__::name, and prog_vers_client_def_t.
Referenced by rpc_init(), and switch_result().
int setHostname (char * name, char * hostname)
setHostname
Definition at line 254 of file commands_NFS_remote.c.
References prog_vers_client_def__::hostname, prog_vers_client_def__::name, and prog_vers_client_def_t.
Referenced by rpc_init().
int setPort (char * name, int port)
setPort
Definition at line 322 of file commands_NFS_remote.c.
References prog_vers_client_def__::name, prog_vers_client_def__::port, and prog_vers_client_def_t.
Referenced by rpc_init().
int setProto (char * name, char * proto)
setProto
Definition at line 288 of file commands_NFS_remote.c.
References prog_vers_client_def__::name, prog_vers_client_def_t, and prog_vers_client_def__::proto.
Referenced by rpc_init().
int switch_result (int result, int i, char * name, char * func_name, char * func_called_name, FILE * output)
Definition at line 539 of file commands_NFS_remote.c.
References NULL, setCLIENT(), and try_rpc_reinit().
Referenced by fn_MNT1_remote_command(), fn_MNT3_remote_command(), fn_NFS2_remote_command(), fn_NFS3_remote_command(), fn_nfs_remote_umount(), nfs_remote_access(), nfs_remote_create(), nfs_remote_getattr(), nfs_remote_link(), nfs_remote_mkdir(), nfs_remote_mount(), nfs_remote_readdir(), nfs_remote_readdirplus(), nfs_remote_readlink(), nfs_remote_remove(), nfs_remote_rename(), nfs_remote_rmdir(), nfs_remote_setattr(), nfs_remote_solvepath(), and nfs_remote_symlink().
int try_rpc_reinit (char * name, int error, FILE * output)
try_rpc_reinit
Definition at line 520 of file commands_NFS_remote.c.
References rpc_reinit().
Referenced by switch_result().
Variable Documentation
struct passwd* current_pw
Definition at line 339 of file commands_NFS_remote.c.
Referenced by fn_nfs_remote_id(), fn_nfs_remote_su(), and rpc_init().
nfs_parameter_t nfs_param
Definition at line 118 of file commands_NFS_remote.c.