commands_Cache_inode.c File Reference
#include `fsal.h`
#include `cache_inode.h`
#include `cache_content.h`
#include `LRU_List.h`
#include `err_fsal.h`
#include `err_cache_inode.h`
#include `err_cache_content.h`
#include `stuff_alloc.h`
#include `cmd_tools.h`
#include `commands.h`
#include `Getopt.h`
#include <unistd.h>
#include <stdio.h>
#include <strings.h>
#include <errno.h>
#include <sys/types.h>
#include <sys/time.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>
#include <pwd.h>
#include <ctype.h>
Classes
struct cmdCacheInode_thr_info__
Defines
#define EXPORT_ID 1
#define ATTR_LEN 100
#define CACHE_INODE_SHELL_READDIR_SIZE 10
#define MAX_GRPS 128
Typedefs
typedef cmdCacheInode_thr_info__ cmdCacheInode_thr_info_t
Functions
cmdCacheInode_thr_info_t * RetrieveInitializedContext ()
void Cache_inode_layer_SetLogLevel (int log_lvl)
int lru_entry_to_str (LRU_data_t data, char *str)
int lru_clean_entry (LRU_entry_t *entry, void *adddata)
int cache_solvepath (char *io_global_path, int size_global_path, char *i_spec_path, cache_entry_t *current_pentry, cache_entry_t **pnew_pentry, FILE *output)
int cacheinode_init (char *filename, int flag_v, FILE *output)
int fn_Cache_inode_cache_init (int argc, char **argv, FILE *output)
int fn_Cache_inode_pwd (int argc, char **argv, FILE *output)
int fn_Cache_inode_cd (int argc, char **argv, FILE *output)
int fn_Cache_inode_stat (int argc, char **argv, FILE *output)
int fn_Cache_inode_gc (int argc, char **argv, FILE *output)
int fn_Cache_inode_ls (int argc, char **argv, FILE *output)
int fn_Cache_inode_callstat (int argc, char **argv, FILE *output)
int fn_Cache_inode_mkdir (int argc, char **argv, FILE *output)
int fn_Cache_inode_link (int argc, char **argv, FILE *output)
int fn_Cache_inode_ln (int argc, char **argv, FILE *output)
int fn_Cache_inode_create (int argc, char **argv, FILE *output)
int fn_Cache_inode_rename (int argc, char **argv, FILE *output)
int fn_Cache_inode_unlink (int argc, char **argv, FILE *output)
int fn_Cache_inode_setattr (int argc, char **argv, FILE *output)
int fn_Cache_inode_access (int argc, char **argv, FILE *output)
int fn_Cache_inode_data_cache (int argc, char **argv, FILE *output)
int fn_Cache_inode_release_cache (int argc, char **argv, FILE *output)
int fn_Cache_inode_recover_cache (int argc, char **argv, FILE *output)
int fn_Cache_inode_refresh_cache (int argc, char **argv, FILE *output)
int fn_Cache_inode_flush_cache (int argc, char **argv, FILE *output)
int fn_Cache_inode_read (int argc, char **argv, FILE *output)
int fn_Cache_inode_write (int argc, char **argv, FILE *output)
int fn_Cache_inode_su (int argc, char **argv, FILE *output)
Variables
hash_table_t * ht
cache_inode_client_parameter_t cache_client_param
cache_content_client_parameter_t datacache_client_param
Define Documentation
#define ATTR_LEN 100
Definition at line 325 of file commands_Cache_inode.c.
#define CACHE_INODE_SHELL_READDIR_SIZE 10
Referenced by fn_Cache_inode_ls().
#define EXPORT_ID 1
Definition at line 324 of file commands_Cache_inode.c.
Referenced by cacheinode_init(), and fn_Cache_inode_recover_cache().
#define MAX_GRPS 128
Referenced by fn_Cache_inode_su(), fn_fsal_su(), fn_nfs_remote_su(), fn_nfs_su(), and rpc_init().
Typedef Documentation
typedef struct cmdCacheInode_thr_info__ cmdCacheInode_thr_info_t
Referenced by cache_solvepath(), cacheinode_init(), fn_Cache_inode_access(), fn_Cache_inode_callstat(), fn_Cache_inode_cd(), fn_Cache_inode_create(), fn_Cache_inode_data_cache(), fn_Cache_inode_flush_cache(), fn_Cache_inode_gc(), fn_Cache_inode_link(), fn_Cache_inode_ln(), fn_Cache_inode_ls(), fn_Cache_inode_mkdir(), fn_Cache_inode_pwd(), fn_Cache_inode_read(), fn_Cache_inode_recover_cache(), fn_Cache_inode_refresh_cache(), fn_Cache_inode_release_cache(), fn_Cache_inode_rename(), fn_Cache_inode_setattr(), fn_Cache_inode_stat(), fn_Cache_inode_su(), fn_Cache_inode_unlink(), fn_Cache_inode_write(), and RetrieveInitializedContext().
Function Documentation
void Cache_inode_layer_SetLogLevel (int log_lvl)
Definition at line 547 of file commands_Cache_inode.c.
int cache_solvepath (char * io_global_path, int size_global_path, char * i_spec_path, cache_entry_t * current_pentry, cache_entry_t ** pnew_pentry, FILE * output)
Definition at line 599 of file commands_Cache_inode.c.
References cmdCacheInode_thr_info__::cache_status, clean_path(), cmdCacheInode_thr_info__::client, cmdCacheInode_thr_info_t, cmdCacheInode_thr_info__::context, ht, print_fsal_status(), and RetrieveInitializedContext().
Referenced by fn_Cache_inode_access(), fn_Cache_inode_cd(), fn_Cache_inode_create(), fn_Cache_inode_data_cache(), fn_Cache_inode_flush_cache(), fn_Cache_inode_link(), fn_Cache_inode_ln(), fn_Cache_inode_ls(), fn_Cache_inode_mkdir(), fn_Cache_inode_read(), fn_Cache_inode_refresh_cache(), fn_Cache_inode_release_cache(), fn_Cache_inode_rename(), fn_Cache_inode_setattr(), fn_Cache_inode_stat(), fn_Cache_inode_unlink(), and fn_Cache_inode_write().
int cacheinode_init (char * filename, int flag_v, FILE * output)
Definition at line 763 of file commands_Cache_inode.c.
References cache_client_param, cmdCacheInode_thr_info__::cache_status, cmdCacheInode_thr_info__::client, cmdCacheInode_thr_info_t, cmdCacheInode_thr_info__::context, cmdCacheInode_thr_info__::current_path, datacache_client_param, cmdCacheInode_thr_info__::dc_client, cmdCacheInode_thr_info__::exp_context, EXPORT_ID, ht, cmdCacheInode_thr_info__::is_client_init, cmdCacheInode_thr_info__::is_thread_init, NULL, cmdCacheInode_thr_info__::pentry, and print_fsal_status().
Referenced by fn_Cache_inode_cache_init().
int fn_Cache_inode_access (int argc, char ** argv, FILE * output)
perform an access command. syntax: access [F][R][W][X] <file> example: access toto FRX
Definition at line 3012 of file commands_Cache_inode.c.
References cache_solvepath(), cmdCacheInode_thr_info__::cache_status, cmdCacheInode_thr_info__::client, cmdCacheInode_thr_info_t, cmdCacheInode_thr_info__::context, cmdCacheInode_thr_info__::current_path, Getopt(), ht, Optind, Optopt, cmdCacheInode_thr_info__::pentry, and RetrieveInitializedContext().
int fn_Cache_inode_cache_init (int argc, char ** argv, FILE * output)
proceed an init_fs command.
Definition at line 1019 of file commands_Cache_inode.c.
References cacheinode_init(), Getopt(), ht, Optind, and Optopt.
int fn_Cache_inode_callstat (int argc, char ** argv, FILE * output)
display statistics about FSAL calls.
Definition at line 1807 of file commands_Cache_inode.c.
References cmdCacheInode_thr_info__::client, cmdCacheInode_thr_info_t, ht, and RetrieveInitializedContext().
int fn_Cache_inode_cd (int argc, char ** argv, FILE * output)
change current path
Definition at line 1134 of file commands_Cache_inode.c.
References cache_solvepath(), cmdCacheInode_thr_info__::cache_status, cmdCacheInode_thr_info__::client, cmdCacheInode_thr_info_t, cmdCacheInode_thr_info__::context, cmdCacheInode_thr_info__::current_path, ht, cmdCacheInode_thr_info__::pentry, and RetrieveInitializedContext().
int fn_Cache_inode_create (int argc, char ** argv, FILE * output)
proceed an create command.
Definition at line 2339 of file commands_Cache_inode.c.
References atomode(), cache_solvepath(), cmdCacheInode_thr_info__::cache_status, cmdCacheInode_thr_info__::client, cmdCacheInode_thr_info_t, cmdCacheInode_thr_info__::context, cmdCacheInode_thr_info__::current_path, Getopt(), ht, NULL, Optind, Optopt, cmdCacheInode_thr_info__::pentry, print_fsal_status(), RetrieveInitializedContext(), and split_path().
int fn_Cache_inode_data_cache (int argc, char ** argv, FILE * output)
cache en entry (REGULAR_FILE) in the data cache
Definition at line 3185 of file commands_Cache_inode.c.
References cache_solvepath(), cmdCacheInode_thr_info__::cache_status, cmdCacheInode_thr_info__::client, cmdCacheInode_thr_info_t, cmdCacheInode_thr_info__::context, cmdCacheInode_thr_info__::current_path, Getopt(), ht, Optind, Optopt, cmdCacheInode_thr_info__::pentry, and RetrieveInitializedContext().
int fn_Cache_inode_flush_cache (int argc, char ** argv, FILE * output)
flush en entry (REGULAR_FILE) in the data cache
Definition at line 3671 of file commands_Cache_inode.c.
References cache_solvepath(), cmdCacheInode_thr_info__::client, cmdCacheInode_thr_info_t, cmdCacheInode_thr_info__::context, cmdCacheInode_thr_info__::current_path, Getopt(), ht, Optind, Optopt, cmdCacheInode_thr_info__::pentry, and RetrieveInitializedContext().
int fn_Cache_inode_gc (int argc, char ** argv, FILE * output)
proceed to a call to the garbagge collector.
Definition at line 1298 of file commands_Cache_inode.c.
References cmdCacheInode_thr_info__::cache_status, cmdCacheInode_thr_info__::client, cmdCacheInode_thr_info_t, Getopt(), ht, Optopt, and RetrieveInitializedContext().
int fn_Cache_inode_link (int argc, char ** argv, FILE * output)
proceed an create command.
Definition at line 2040 of file commands_Cache_inode.c.
References cache_solvepath(), cmdCacheInode_thr_info__::cache_status, cmdCacheInode_thr_info__::client, cmdCacheInode_thr_info_t, cmdCacheInode_thr_info__::context, cmdCacheInode_thr_info__::current_path, Getopt(), ht, Optind, Optopt, cmdCacheInode_thr_info__::pentry, print_fsal_status(), RetrieveInitializedContext(), and split_path().
int fn_Cache_inode_ln (int argc, char ** argv, FILE * output)
proceed an ln (symlink) command.
Definition at line 2186 of file commands_Cache_inode.c.
References cache_solvepath(), cmdCacheInode_thr_info__::cache_status, cmdCacheInode_thr_info__::client, cmdCacheInode_thr_info_t, cmdCacheInode_thr_info__::context, cmdCacheInode_thr_info__::current_path, Getopt(), ht, Optind, Optopt, cmdCacheInode_thr_info__::pentry, print_fsal_status(), RetrieveInitializedContext(), and split_path().
int fn_Cache_inode_ls (int argc, char ** argv, FILE * output)
proceed an ls command.
Definition at line 1382 of file commands_Cache_inode.c.
References CACHE_INODE_SHELL_READDIR_SIZE, cache_solvepath(), cmdCacheInode_thr_info__::cache_status, cmdCacheInode_thr_info__::client, cmdCacheInode_thr_info_t, cmdCacheInode_thr_info__::context, cmdCacheInode_thr_info__::current_path, Getopt(), ht, Optind, Optopt, cmdCacheInode_thr_info__::pentry, print_fsal_attributes(), print_item_line(), and RetrieveInitializedContext().
int fn_Cache_inode_mkdir (int argc, char ** argv, FILE * output)
proceed an mkdir command.
Definition at line 1866 of file commands_Cache_inode.c.
References atomode(), cache_solvepath(), cmdCacheInode_thr_info__::cache_status, cmdCacheInode_thr_info__::client, cmdCacheInode_thr_info_t, cmdCacheInode_thr_info__::context, cmdCacheInode_thr_info__::current_path, Getopt(), ht, NULL, Optind, Optopt, cmdCacheInode_thr_info__::pentry, print_fsal_status(), RetrieveInitializedContext(), and split_path().
int fn_Cache_inode_pwd (int argc, char ** argv, FILE * output)
prints current path
Definition at line 1103 of file commands_Cache_inode.c.
References cmdCacheInode_thr_info__::cache_status, cmdCacheInode_thr_info_t, cmdCacheInode_thr_info__::current_path, ht, cmdCacheInode_thr_info__::pentry, and RetrieveInitializedContext().
int fn_Cache_inode_read (int argc, char ** argv, FILE * output)
Reads the content of a cached regular file
Definition at line 3792 of file commands_Cache_inode.c.
References ato64(), cache_solvepath(), cmdCacheInode_thr_info__::cache_status, cmdCacheInode_thr_info__::client, cmdCacheInode_thr_info_t, cmdCacheInode_thr_info__::context, cmdCacheInode_thr_info__::current_path, Getopt(), ht, NULL, Optarg, Optind, Optopt, cmdCacheInode_thr_info__::pentry, print_timeval, RetrieveInitializedContext(), and time_diff().
int fn_Cache_inode_recover_cache (int argc, char ** argv, FILE * output)
recover the data cache
Definition at line 3443 of file commands_Cache_inode.c.
References cmdCacheInode_thr_info__::client, cmdCacheInode_thr_info_t, cmdCacheInode_thr_info__::context, EXPORT_ID, Getopt(), ht, Optind, Optopt, and RetrieveInitializedContext().
int fn_Cache_inode_refresh_cache (int argc, char ** argv, FILE * output)
refresh en entry (REGULAR_FILE) in the data cache
Definition at line 3549 of file commands_Cache_inode.c.
References cache_solvepath(), cmdCacheInode_thr_info__::client, cmdCacheInode_thr_info_t, cmdCacheInode_thr_info__::context, cmdCacheInode_thr_info__::current_path, Getopt(), ht, Optind, Optopt, cmdCacheInode_thr_info__::pentry, and RetrieveInitializedContext().
int fn_Cache_inode_release_cache (int argc, char ** argv, FILE * output)
cache en entry (REGULAR_FILE) in the data cache
Definition at line 3331 of file commands_Cache_inode.c.
References cache_solvepath(), cmdCacheInode_thr_info__::cache_status, cmdCacheInode_thr_info__::client, cmdCacheInode_thr_info_t, cmdCacheInode_thr_info__::context, cmdCacheInode_thr_info__::current_path, Getopt(), ht, Optind, Optopt, cmdCacheInode_thr_info__::pentry, and RetrieveInitializedContext().
int fn_Cache_inode_rename (int argc, char ** argv, FILE * output)
proceed a rename command.
Definition at line 2511 of file commands_Cache_inode.c.
References cache_solvepath(), cmdCacheInode_thr_info__::cache_status, cmdCacheInode_thr_info__::client, cmdCacheInode_thr_info_t, cmdCacheInode_thr_info__::context, cmdCacheInode_thr_info__::current_path, Getopt(), ht, Optind, Optopt, cmdCacheInode_thr_info__::pentry, print_fsal_status(), RetrieveInitializedContext(), and split_path().
int fn_Cache_inode_setattr (int argc, char ** argv, FILE * output)
setattr
syntax of command line: setattr file_path attribute_name attribute_value
Definition at line 2828 of file commands_Cache_inode.c.
References ATTR_32, ATTR_64, shell_attribute__::attr_name, ATTR_OCTAL, ATTR_TIME, shell_attribute__::attr_type, cache_solvepath(), cmdCacheInode_thr_info__::cache_status, cmdCacheInode_thr_info__::client, cmdCacheInode_thr_info_t, cmdCacheInode_thr_info__::context, cmdCacheInode_thr_info__::current_path, Getopt(), ht, MkFSALSetAttrStruct(), Optind, Optopt, cmdCacheInode_thr_info__::pentry, print_fsal_attributes(), RetrieveInitializedContext(), and shell_attribute_t.
int fn_Cache_inode_stat (int argc, char ** argv, FILE * output)
proceed a stat command.
Definition at line 1199 of file commands_Cache_inode.c.
References cache_solvepath(), cmdCacheInode_thr_info__::cache_status, cmdCacheInode_thr_info__::client, cmdCacheInode_thr_info_t, cmdCacheInode_thr_info__::context, cmdCacheInode_thr_info__::current_path, Getopt(), ht, Optind, Optopt, cmdCacheInode_thr_info__::pentry, print_fsal_attributes(), and RetrieveInitializedContext().
int fn_Cache_inode_su (int argc, char ** argv, FILE * output)
change thread contexte.
Definition at line 4664 of file commands_Cache_inode.c.
References cmdCacheInode_thr_info_t, cmdCacheInode_thr_info__::context, cmdCacheInode_thr_info__::exp_context, getugroups(), ht, MAX_GRPS, my_atoi(), print_fsal_status(), and RetrieveInitializedContext().
int fn_Cache_inode_unlink (int argc, char ** argv, FILE * output)
proceed an unlink command.
Definition at line 2685 of file commands_Cache_inode.c.
References cache_solvepath(), cmdCacheInode_thr_info__::cache_status, cmdCacheInode_thr_info__::client, cmdCacheInode_thr_info_t, cmdCacheInode_thr_info__::context, cmdCacheInode_thr_info__::current_path, Getopt(), ht, Optind, Optopt, cmdCacheInode_thr_info__::pentry, print_fsal_status(), RetrieveInitializedContext(), and split_path().
int fn_Cache_inode_write (int argc, char ** argv, FILE * output)
Reads the content of a cached regular file
Definition at line 4219 of file commands_Cache_inode.c.
References ato64(), cache_solvepath(), cmdCacheInode_thr_info__::cache_status, cmdCacheInode_thr_info__::client, cmdCacheInode_thr_info_t, cmdCacheInode_thr_info__::context, cmdCacheInode_thr_info__::current_path, Getopt(), ht, NULL, Optarg, Optind, Optopt, cmdCacheInode_thr_info__::pentry, print_timeval, RetrieveInitializedContext(), and time_diff().
int lru_clean_entry (LRU_entry_t * entry, void * adddata)
Definition at line 583 of file commands_Cache_inode.c.
int lru_entry_to_str (LRU_data_t data, char * str)
Definition at line 578 of file commands_Cache_inode.c.
cmdCacheInode_thr_info_t* RetrieveInitializedContext ()
Definition at line 521 of file commands_Cache_inode.c.
References cmdCacheInode_thr_info_t, cmdCacheInode_thr_info__::is_client_init, and cmdCacheInode_thr_info__::is_thread_init.
Referenced by cache_solvepath(), fn_Cache_inode_access(), fn_Cache_inode_callstat(), fn_Cache_inode_cd(), fn_Cache_inode_create(), fn_Cache_inode_data_cache(), fn_Cache_inode_flush_cache(), fn_Cache_inode_gc(), fn_Cache_inode_link(), fn_Cache_inode_ln(), fn_Cache_inode_ls(), fn_Cache_inode_mkdir(), fn_Cache_inode_pwd(), fn_Cache_inode_read(), fn_Cache_inode_recover_cache(), fn_Cache_inode_refresh_cache(), fn_Cache_inode_release_cache(), fn_Cache_inode_rename(), fn_Cache_inode_setattr(), fn_Cache_inode_stat(), fn_Cache_inode_su(), fn_Cache_inode_unlink(), and fn_Cache_inode_write().
Variable Documentation
cache_inode_client_parameter_t cache_client_param
Global (exported) variable : init parameters for clients.
Definition at line 346 of file commands_Cache_inode.c.
Referenced by cacheinode_init(), and InitNFSClient().
cache_content_client_parameter_t datacache_client_param
Definition at line 347 of file commands_Cache_inode.c.
Referenced by cacheinode_init(), and InitNFSClient().
hash_table_t* ht
Global (exported) variable : The cache hash table
Definition at line 340 of file commands_Cache_inode.c.
Referenced by cache_solvepath(), cacheinode_init(), fn_Cache_inode_access(), fn_Cache_inode_cache_init(), fn_Cache_inode_callstat(), fn_Cache_inode_cd(), fn_Cache_inode_create(), fn_Cache_inode_data_cache(), fn_Cache_inode_flush_cache(), fn_Cache_inode_gc(), fn_Cache_inode_link(), fn_Cache_inode_ln(), fn_Cache_inode_ls(), fn_Cache_inode_mkdir(), fn_Cache_inode_pwd(), fn_Cache_inode_read(), fn_Cache_inode_recover_cache(), fn_Cache_inode_refresh_cache(), fn_Cache_inode_release_cache(), fn_Cache_inode_rename(), fn_Cache_inode_setattr(), fn_Cache_inode_stat(), fn_Cache_inode_su(), fn_Cache_inode_unlink(), fn_Cache_inode_write(), fn_MNT1_command(), fn_MNT3_command(), fn_NFS2_command(), fn_NFS3_command(), fn_nfs_mount(), fn_nfs_umount(), and nfs_init().