NFS protocols functions.
Functions
int nfs2_remote_Null (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs2_remote_Getattr (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs2_remote_Setattr (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs2_remote_Root (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs2_remote_Lookup (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs2_remote_Readlink (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs2_remote_Read (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs2_remote_Writecache (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs2_remote_Write (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs2_remote_Create (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs2_remote_Remove (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs2_remote_Rename (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs2_remote_Link (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs2_remote_Symlink (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs2_remote_Mkdir (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs2_remote_Rmdir (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs2_remote_Readdir (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs2_remote_Fsstat (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs3_remote_Null (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs3_remote_Getattr (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs3_remote_Setattr (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs3_remote_Lookup (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs3_remote_Readlink (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs3_remote_Read (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs3_remote_Write (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs3_remote_Create (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs3_remote_Remove (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs3_remote_Rename (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs3_remote_Link (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs3_remote_Symlink (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs3_remote_Mkdir (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs3_remote_Rmdir (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs3_remote_Readdir (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs3_remote_Fsstat (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs3_remote_Access (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs3_remote_Readdirplus (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs3_remote_Fsinfo (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs3_remote_Pathconf (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs3_remote_Commit (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs3_remote_Mknod (CLIENT *clnt, nfs_arg_t *parg, nfs_res_t *pres)
int nfs4_remote_COMPOUND (CLIENT *clnt, COMPOUND4args *parg, COMPOUND4res *pres)
int nfs4_remote_Null (CLIENT *clnt)
void mnt1_remote_Mnt_Free (nfs_res_t *pres)
void mnt1_remote_Dump_Free (nfs_res_t *pres)
void mnt1_remote_Export_Free (nfs_res_t *pres)
void mnt1_remote_Null_Free (nfs_res_t *pres)
void mnt1_remote_Umnt_Free (nfs_res_t *pres)
void mnt1_remote_UmntAll_Free (nfs_res_t *pres)
void mnt3_remote_Mnt_Free (nfs_res_t *pres)
void mnt3_remote_Dump_Free (nfs_res_t *pres)
void mnt3_remote_Export_Free (nfs_res_t *pres)
void mnt3_remote_Null_Free (nfs_res_t *pres)
void mnt3_remote_Umnt_Free (nfs_res_t *pres)
void mnt3_remote_UmntAll_Free (nfs_res_t *pres)
void nfs2_remote_Null_Free (nfs_res_t *resp)
void nfs2_remote_Getattr_Free (nfs_res_t *resp)
void nfs2_remote_Setattr_Free (nfs_res_t *resp)
void nfs2_remote_Lookup_Free (nfs_res_t *resp)
void nfs2_remote_Read_Free (nfs_res_t *resp)
void nfs2_remote_Write_Free (nfs_res_t *resp)
void nfs2_remote_Create_Free (nfs_res_t *resp)
void nfs2_remote_Mkdir_Free (nfs_res_t *resp)
void nfs2_remote_Symlink_Free (nfs_res_t *resp)
void nfs2_remote_Remove_Free (nfs_res_t *resp)
void nfs2_remote_Rmdir_Free (nfs_res_t *resp)
void nfs2_remote_Rename_Free (nfs_res_t *resp)
void nfs2_remote_Link_Free (nfs_res_t *resp)
void nfs2_remote_Fsstat_Free (nfs_res_t *resp)
void nfs2_remote_Root_Free (nfs_res_t *pres)
void nfs2_remote_Writecache_Free (nfs_res_t *pres)
void nfs2_remote_Readdir_Free (nfs_res_t *resp)
void nfs2_remote_Readlink_Free (nfs_res_t *resp)
void nfs3_remote_Null_Free (nfs_res_t *resp)
void nfs3_remote_Getattr_Free (nfs_res_t *resp)
void nfs3_remote_Setattr_Free (nfs_res_t *resp)
void nfs3_remote_Lookup_Free (nfs_res_t *resp)
void nfs3_remote_Access_Free (nfs_res_t *pres)
void nfs3_remote_Readlink_Free (nfs_res_t *resp)
void nfs3_remote_Write_Free (nfs_res_t *resp)
void nfs3_remote_Create_Free (nfs_res_t *resp)
void nfs3_remote_Mkdir_Free (nfs_res_t *resp)
void nfs3_remote_Symlink_Free (nfs_res_t *resp)
void nfs3_remote_Mknod_Free (nfs_res_t *pres)
void nfs3_remote_Remove_Free (nfs_res_t *resp)
void nfs3_remote_Rmdir_Free (nfs_res_t *resp)
void nfs3_remote_Rename_Free (nfs_res_t *resp)
void nfs3_remote_Link_Free (nfs_res_t *resp)
void nfs3_remote_Readdir_Free (nfs_res_t *resp)
void nfs3_remote_Readdirplus_Free (nfs_res_t *resp)
void nfs3_remote_Fsstat_Free (nfs_res_t *resp)
void nfs3_remote_Fsinfo_Free (nfs_res_t *pres)
void nfs3_remote_Pathconf_Free (nfs_res_t *pres)
void nfs3_remote_Commit_Free (nfs_res_t *pres)
void nfs3_remote_Read_Free (nfs_res_t *resp)
Function Documentation
void mnt1_remote_Dump_Free (nfs_res_t * pres)
mnt1_remote_Dump_Free: Frees the result structure allocated for mnt1_remote_Dump.
Frees the result structure allocated for mnt1_remote_Dump.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1542 of file nfs_remote_functions.c.
void mnt1_remote_Export_Free (nfs_res_t * pres)
mnt1_remote_Export_Free: Frees the result structure allocated for mnt1_remote_Export.
Frees the result structure allocated for mnt1_remote_Export.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1555 of file nfs_remote_functions.c.
void mnt1_remote_Mnt_Free (nfs_res_t * pres)
mnt1_remote_Mnt_Free: Frees the result structure allocated for mnt1_remote_Mnt.
Frees the result structure allocated for mnt1_remote_Mnt.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1529 of file nfs_remote_functions.c.
void mnt1_remote_Null_Free (nfs_res_t * pres)
mnt1_remote_Null_Free: Frees the result structure allocated for mnt1_remote_Null
Frees the result structure allocated for mnt1_remote_Null. Does Nothing in fact.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1516 of file nfs_remote_functions.c.
void mnt1_remote_Umnt_Free (nfs_res_t * pres)
mnt1_remote_Umnt_Free: Frees the result structure allocated for mnt1_remote_Umnt.
Frees the result structure allocated for mnt1_remote_Umnt.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1568 of file nfs_remote_functions.c.
void mnt1_remote_UmntAll_Free (nfs_res_t * pres)
mnt1_remote_UmntAll_Free: Frees the result structure allocated for mnt1_remote_UmntAll.
Frees the result structure allocated for mnt1_remote_UmntAll.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1581 of file nfs_remote_functions.c.
void mnt3_remote_Dump_Free (nfs_res_t * pres)
mnt3_remote_Dump_Free: Frees the result structure allocated for mnt3_remote_Dump.
Frees the result structure allocated for mnt3_remote_Dump.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1620 of file nfs_remote_functions.c.
void mnt3_remote_Export_Free (nfs_res_t * pres)
mnt3_remote_Export_Free: Frees the result structure allocated for mnt3_remote_Export.
Frees the result structure allocated for mnt3_remote_Export.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1633 of file nfs_remote_functions.c.
void mnt3_remote_Mnt_Free (nfs_res_t * pres)
mnt3_remote_Mnt_Free: Frees the result structure allocated for mnt3_remote_Mnt.
Frees the result structure allocated for mnt3_remote_Mnt.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1607 of file nfs_remote_functions.c.
Referenced by nfs_remote_mount().
void mnt3_remote_Null_Free (nfs_res_t * pres)
mnt3_remote_Null_Free: Frees the result structure allocated for mnt3_remote_Null
Frees the result structure allocated for mnt3_remote_Null. Does Nothing in fact.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1594 of file nfs_remote_functions.c.
void mnt3_remote_Umnt_Free (nfs_res_t * pres)
mnt3_remote_Umnt_Free: Frees the result structure allocated for mnt3_remote_Umnt.
Frees the result structure allocated for mnt3_remote_Umnt.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1646 of file nfs_remote_functions.c.
Referenced by fn_nfs_remote_umount().
void mnt3_remote_UmntAll_Free (nfs_res_t * pres)
mnt3_remote_UmntAll_Free: Frees the result structure allocated for mnt3_remote_UmntAll.
Frees the result structure allocated for mnt3_remote_UmntAll.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1659 of file nfs_remote_functions.c.
int nfs2_remote_Create (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs2_remote_Create: The NFS proc create function, v2.
The NFS proc create function, v2.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 662 of file nfs_remote_functions.c.
void nfs2_remote_Create_Free (nfs_res_t * resp)
nfs2_remote_Create_Free: Frees the result structure allocated for nfs2_remote_Create.
Frees the result structure allocated for nfs2_remote_Create.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1750 of file nfs_remote_functions.c.
int nfs2_remote_Fsstat (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs2_remote_Fsstat: The NFS proc statfs function, v2.
The NFS proc statfs function, v2.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 870 of file nfs_remote_functions.c.
void nfs2_remote_Fsstat_Free (nfs_res_t * resp)
nfs2_remote_Fsstat_Free: Frees the result structure allocated for nfs2_remote_Fsstat.
Frees the result structure allocated for nfs2_remote_Fsstat.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1841 of file nfs_remote_functions.c.
int nfs2_remote_Getattr (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs2_remote_Getattr: The NFS proc getattr function, v2.
The NFS proc getattr function, v2.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 456 of file nfs_remote_functions.c.
void nfs2_remote_Getattr_Free (nfs_res_t * resp)
nfs2_remote_Getattr_Free: Frees the result structure allocated for nfs2_remote_Getattr.
Frees the result structure allocated for nfs2_remote_Getattr.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1685 of file nfs_remote_functions.c.
int nfs2_remote_Link (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs2_remote_Link: The NFS proc link function, v2.
The NFS proc link function, v2.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 740 of file nfs_remote_functions.c.
void nfs2_remote_Link_Free (nfs_res_t * resp)
nfs2_remote_Link_Free: Frees the result structure allocated for nfs2_remote_Link.
Frees the result structure allocated for nfs2_remote_Link.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1828 of file nfs_remote_functions.c.
int nfs2_remote_Lookup (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs2_remote_Lookup: The NFS proc lookup function, v2.
The NFS proc lookup function, v2.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 533 of file nfs_remote_functions.c.
void nfs2_remote_Lookup_Free (nfs_res_t * resp)
nfs2_remote_Lookup_Free: Frees the result structure allocated for nfs2_remote_Lookup.
Frees the result structure allocated for nfs2_remote_Lookup.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1711 of file nfs_remote_functions.c.
int nfs2_remote_Mkdir (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs2_remote_Mkdir: The NFS proc mkdir function, v2.
The NFS proc mkdir function, v2.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 792 of file nfs_remote_functions.c.
void nfs2_remote_Mkdir_Free (nfs_res_t * resp)
nfs2_remote_Mkdir_Free: Frees the result structure allocated for nfs2_remote_Mkdir.
Frees the result structure allocated for nfs2_remote_Mkdir.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1763 of file nfs_remote_functions.c.
int nfs2_remote_Null (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs2_remote_Null: The NFS proc null function, v2.
The NFS proc null function, v2.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 431 of file nfs_remote_functions.c.
void nfs2_remote_Null_Free (nfs_res_t * resp)
nfs2_remote_Null_Free: Frees the result structure allocated for nfs2_remote_Null.
Frees the result structure allocated for nfs2_remote_Null.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1672 of file nfs_remote_functions.c.
int nfs2_remote_Read (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs2_remote_Read: The NFS proc read function, v2.
The NFS proc read function, v2.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 585 of file nfs_remote_functions.c.
void nfs2_remote_Read_Free (nfs_res_t * resp)
nfs2_remote_Read_Free: Frees the result structure allocated for nfs2_remote_Read.
Frees the result structure allocated for nfs2_remote_Read.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1724 of file nfs_remote_functions.c.
int nfs2_remote_Readdir (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs2_remote_Readdir: The NFS proc readdir function, v2.
The NFS proc readdir function, v2.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 844 of file nfs_remote_functions.c.
void nfs2_remote_Readdir_Free (nfs_res_t * resp)
nfs2_remote_Readdir_Free: Frees the result structure allocated for nfs2_remote_Readdir.
Frees the result structure allocated for nfs2_remote_Readdir.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1880 of file nfs_remote_functions.c.
int nfs2_remote_Readlink (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs2_remote_Readlink: The NFS proc readlink function, v2.
The NFS proc readlink function, v2.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 559 of file nfs_remote_functions.c.
void nfs2_remote_Readlink_Free (nfs_res_t * resp)
nfs2_remote_Readlink_Free: Frees the result structure allocated for nfs2_remote_Readlink.
Frees the result structure allocated for nfs2_remote_Readlink.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1893 of file nfs_remote_functions.c.
int nfs2_remote_Remove (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs2_remote_Remove: The NFS proc remove function, v2.
The NFS proc remove function, v2.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 688 of file nfs_remote_functions.c.
void nfs2_remote_Remove_Free (nfs_res_t * resp)
nfs2_remote_Remove_Free: Frees the result structure allocated for nfs2_remote_Remove.
Frees the result structure allocated for nfs2_remote_Remove.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1789 of file nfs_remote_functions.c.
int nfs2_remote_Rename (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs2_remote_Rename: The NFS proc rename function, v2.
The NFS proc rename function, v2.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 714 of file nfs_remote_functions.c.
void nfs2_remote_Rename_Free (nfs_res_t * resp)
nfs2_remote_Rename_Free: Frees the result structure allocated for nfs2_remote_Rename.
Frees the result structure allocated for nfs2_remote_Rename.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1815 of file nfs_remote_functions.c.
int nfs2_remote_Rmdir (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs2_remote_Rmdir: The NFS proc rmdir function, v2.
The NFS proc rmdir function, v2.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 818 of file nfs_remote_functions.c.
void nfs2_remote_Rmdir_Free (nfs_res_t * resp)
nfs2_remote_Rmdir_Free: Frees the result structure allocated for nfs2_remote_Rmdir.
Frees the result structure allocated for nfs2_remote_Rmdir.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1802 of file nfs_remote_functions.c.
int nfs2_remote_Root (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs2_remote_Root: The NFS proc root function, v2.
The NFS proc root function, v2.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 508 of file nfs_remote_functions.c.
void nfs2_remote_Root_Free (nfs_res_t * pres)
nfs2_remote_Root_Free: Frees the result structure allocated for nfs2_remote_Root.
Frees the result structure allocated for nfs2_remote_Root.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1854 of file nfs_remote_functions.c.
int nfs2_remote_Setattr (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs2_remote_Setattr: The NFS proc setattr function, v2.
The NFS proc setattr function, v2.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 482 of file nfs_remote_functions.c.
void nfs2_remote_Setattr_Free (nfs_res_t * resp)
nfs2_remote_Setattr_Free: Frees the result structure allocated for nfs2_remote_Setattr.
Frees the result structure allocated for nfs2_remote_Setattr.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1698 of file nfs_remote_functions.c.
int nfs2_remote_Symlink (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs2_remote_Symlink: The NFS proc symlink function, v2.
The NFS proc symlink function, v2.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 766 of file nfs_remote_functions.c.
void nfs2_remote_Symlink_Free (nfs_res_t * resp)
nfs2_remote_Symlink_Free: Frees the result structure allocated for nfs2_remote_Symlink.
Frees the result structure allocated for nfs2_remote_Symlink.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1776 of file nfs_remote_functions.c.
int nfs2_remote_Write (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs2_remote_Write: The NFS proc write function, v2.
The NFS proc write function, v2.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 636 of file nfs_remote_functions.c.
void nfs2_remote_Write_Free (nfs_res_t * resp)
nfs2_remote_Write_Free: Frees the result structure allocated for nfs2_remote_Write.
Frees the result structure allocated for nfs2_remote_Write.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1737 of file nfs_remote_functions.c.
int nfs2_remote_Writecache (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs2_remote_Writecache: The NFS proc writecache function, v2.
The NFS proc writecache function, v2.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 611 of file nfs_remote_functions.c.
void nfs2_remote_Writecache_Free (nfs_res_t * pres)
nfs2_remote_Writecache_Free: Frees the result structure allocated for nfs2_remote_Writecache.
Frees the result structure allocated for nfs2_remote_Writecache.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1867 of file nfs_remote_functions.c.
int nfs3_remote_Access (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs3_remote_Access: The NFS proc access function, v3.
The NFS proc access function, v3.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 1311 of file nfs_remote_functions.c.
Referenced by nfs_remote_access().
void nfs3_remote_Access_Free (nfs_res_t * pres)
nfs3_remote_Access_Free: Frees the result structure allocated for nfs3_remote_Access.
Frees the result structure allocated for nfs3_remote_Access.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1958 of file nfs_remote_functions.c.
Referenced by nfs_remote_access().
int nfs3_remote_Commit (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs3_remote_Commit: The NFS proc commit function, v3.
The NFS proc commit function, v3.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 1415 of file nfs_remote_functions.c.
void nfs3_remote_Commit_Free (nfs_res_t * pres)
nfs3_remote_Commit_Free: Frees the result structure allocated for nfs3_remote_Commit.
Frees the result structure allocated for nfs3_remote_Commit.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 2166 of file nfs_remote_functions.c.
int nfs3_remote_Create (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs3_remote_Create: The NFS proc create function, v3.
The NFS proc create function, v3.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 1077 of file nfs_remote_functions.c.
Referenced by nfs_remote_create().
void nfs3_remote_Create_Free (nfs_res_t * resp)
nfs3_remote_Create_Free: Frees the result structure allocated for nfs3_remote_Create.
Frees the result structure allocated for nfs3_remote_Create.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1997 of file nfs_remote_functions.c.
Referenced by nfs_remote_create().
int nfs3_remote_Fsinfo (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs3_remote_Fsinfo: The NFS proc fsinfo function, v3.
The NFS proc fsinfo function, v3.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 1363 of file nfs_remote_functions.c.
void nfs3_remote_Fsinfo_Free (nfs_res_t * pres)
nfs3_remote_Fsinfo_Free: Frees the result structure allocated for nfs3_remote_Fsinfo.
Frees the result structure allocated for nfs3_remote_Fsinfo.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 2140 of file nfs_remote_functions.c.
int nfs3_remote_Fsstat (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs3_remote_Fsstat: The NFS proc statfs function, v3.
The NFS proc statfs function, v3.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 1285 of file nfs_remote_functions.c.
void nfs3_remote_Fsstat_Free (nfs_res_t * resp)
nfs3_remote_Fsstat_Free: Frees the result structure allocated for nfs3_remote_Fsstat.
Frees the result structure allocated for nfs3_remote_Fsstat.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 2127 of file nfs_remote_functions.c.
int nfs3_remote_Getattr (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs3_remote_Getattr: The NFS proc getattr function, v3.
The NFS proc getattr function, v3.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 921 of file nfs_remote_functions.c.
Referenced by nfs_remote_getattr().
void nfs3_remote_Getattr_Free (nfs_res_t * resp)
nfs3_remote_Getattr_Free: Frees the result structure allocated for nfs3_remote_Getattr.
Frees the result structure allocated for nfs3_remote_Getattr.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1919 of file nfs_remote_functions.c.
Referenced by nfs_remote_getattr().
int nfs3_remote_Link (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs3_remote_Link: The NFS proc link function, v3.
The NFS proc link function, v3.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 1155 of file nfs_remote_functions.c.
Referenced by nfs_remote_link().
void nfs3_remote_Link_Free (nfs_res_t * resp)
nfs3_remote_Link_Free: Frees the result structure allocated for nfs3_remote_Link.
Frees the result structure allocated for nfs3_remote_Link.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 2088 of file nfs_remote_functions.c.
Referenced by nfs_remote_link().
int nfs3_remote_Lookup (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs3_remote_Lookup: The NFS proc lookup function, v3.
The NFS proc lookup function, v3.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 973 of file nfs_remote_functions.c.
Referenced by nfs_remote_solvepath().
void nfs3_remote_Lookup_Free (nfs_res_t * resp)
nfs3_remote_Lookup_Free: Frees the result structure allocated for nfs3_remote_Lookup.
Frees the result structure allocated for nfs3_remote_Lookup.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1945 of file nfs_remote_functions.c.
Referenced by nfs_remote_solvepath().
int nfs3_remote_Mkdir (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs3_remote_Mkdir: The NFS proc mkdir function, v3.
The NFS proc mkdir function, v3.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 1207 of file nfs_remote_functions.c.
Referenced by nfs_remote_mkdir().
void nfs3_remote_Mkdir_Free (nfs_res_t * resp)
nfs3_remote_Mkdir_Free: Frees the result structure allocated for nfs3_remote_Mkdir.
Frees the result structure allocated for nfs3_remote_Mkdir.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 2010 of file nfs_remote_functions.c.
Referenced by nfs_remote_mkdir().
int nfs3_remote_Mknod (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs3_remote_Mknod: The NFS proc mknod function, v3.
The NFS proc mknod function, v3.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 1441 of file nfs_remote_functions.c.
void nfs3_remote_Mknod_Free (nfs_res_t * pres)
nfs3_remote_Mknod_Free: Frees the result structure allocated for nfs3_remote_Mknod.
Frees the result structure allocated for nfs3_remote_Mknod.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 2036 of file nfs_remote_functions.c.
int nfs3_remote_Null (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs3_remote_Null: The NFS proc null function, v3.
The NFS proc null function, v3.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 896 of file nfs_remote_functions.c.
void nfs3_remote_Null_Free (nfs_res_t * resp)
nfs3_remote_Null_Free: Frees the result structure allocated for nfs3_remote_Null.
Frees the result structure allocated for nfs3_remote_Null.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1906 of file nfs_remote_functions.c.
int nfs3_remote_Pathconf (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs3_remote_Pathconf: The NFS proc pathconf function, v3.
The NFS proc pathconf function, v3.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 1389 of file nfs_remote_functions.c.
void nfs3_remote_Pathconf_Free (nfs_res_t * pres)
nfs3_remote_Pathconf_Free: Frees the result structure allocated for nfs3_remote_Pathconf.
Frees the result structure allocated for nfs3_remote_Pathconf.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 2153 of file nfs_remote_functions.c.
int nfs3_remote_Read (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs3_remote_Read: The NFS proc read function, v3.
The NFS proc read function, v3.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 1025 of file nfs_remote_functions.c.
void nfs3_remote_Read_Free (nfs_res_t * resp)
nfs3_remote_Read_Free: Frees the result structure allocated for nfs3_remote_Read.
Frees the result structure allocated for nfs3_remote_Read.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 2179 of file nfs_remote_functions.c.
int nfs3_remote_Readdir (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs3_remote_Readdir: The NFS proc readdir function, v3.
The NFS proc readdir function, v3.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 1259 of file nfs_remote_functions.c.
Referenced by nfs_remote_readdir().
void nfs3_remote_Readdir_Free (nfs_res_t * resp)
nfs3_remote_Readdir_Free: Frees the result structure allocated for nfs3_remote_Readdir.
Frees the result structure allocated for nfs3_remote_Readdir.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 2101 of file nfs_remote_functions.c.
Referenced by nfs_remote_readdir(), and nfs_remote_readdir_free().
int nfs3_remote_Readdirplus (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs3_remote_Readdirplus: The NFS proc readdirplus function, v3.
The NFS proc readdirplus function, v3.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 1337 of file nfs_remote_functions.c.
Referenced by nfs_remote_readdirplus().
void nfs3_remote_Readdirplus_Free (nfs_res_t * resp)
nfs3_remote_Readdirplus_Free: Frees the result structure allocated for nfs3_remote_Readdirplus.
Frees the result structure allocated for nfs3_remote_Readdirplus.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 2114 of file nfs_remote_functions.c.
Referenced by nfs_remote_readdirplus(), and nfs_remote_readdirplus_free().
int nfs3_remote_Readlink (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs3_remote_Readlink: The NFS proc readlink function, v3.
The NFS proc readlink function, v3.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 999 of file nfs_remote_functions.c.
Referenced by nfs_remote_readlink().
void nfs3_remote_Readlink_Free (nfs_res_t * resp)
nfs3_remote_Readlink_Free: Frees the result structure allocated for nfs3_remote_Readlink.
Frees the result structure allocated for nfs3_remote_Readlink.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1971 of file nfs_remote_functions.c.
Referenced by nfs_remote_readlink().
int nfs3_remote_Remove (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs3_remote_Remove: The NFS proc remove function, v3.
The NFS proc remove function, v3.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 1103 of file nfs_remote_functions.c.
Referenced by nfs_remote_remove().
void nfs3_remote_Remove_Free (nfs_res_t * resp)
nfs3_remote_Remove_Free: Frees the result structure allocated for nfs3_remote_Remove.
Frees the result structure allocated for nfs3_remote_Remove.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 2049 of file nfs_remote_functions.c.
Referenced by nfs_remote_remove().
int nfs3_remote_Rename (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs3_remote_Rename: The NFS proc rename function, v3.
The NFS proc rename function, v3.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 1129 of file nfs_remote_functions.c.
Referenced by nfs_remote_rename().
void nfs3_remote_Rename_Free (nfs_res_t * resp)
nfs3_remote_Rename_Free: Frees the result structure allocated for nfs3_remote_Rename.
Frees the result structure allocated for nfs3_remote_Rename.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 2075 of file nfs_remote_functions.c.
Referenced by nfs_remote_rename().
int nfs3_remote_Rmdir (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs3_remote_Rmdir: The NFS proc rmdir function, v3.
The NFS proc rmdir function, v3.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 1233 of file nfs_remote_functions.c.
Referenced by nfs_remote_rmdir().
void nfs3_remote_Rmdir_Free (nfs_res_t * resp)
nfs3_remote_Rmdir_Free: Frees the result structure allocated for nfs3_remote_Rmdir.
Frees the result structure allocated for nfs3_remote_Rmdir.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 2062 of file nfs_remote_functions.c.
Referenced by nfs_remote_rmdir().
int nfs3_remote_Setattr (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs3_remote_Setattr: The NFS proc setattr function, v3.
The NFS proc setattr function, v3.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 947 of file nfs_remote_functions.c.
Referenced by nfs_remote_setattr().
void nfs3_remote_Setattr_Free (nfs_res_t * resp)
nfs3_remote_Setattr_Free: Frees the result structure allocated for nfs3_remote_Setattr.
Frees the result structure allocated for nfs3_remote_Setattr.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1932 of file nfs_remote_functions.c.
Referenced by nfs_remote_setattr().
int nfs3_remote_Symlink (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs3_remote_Symlink: The NFS proc symlink function, v3.
The NFS proc symlink function, v3.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 1181 of file nfs_remote_functions.c.
Referenced by nfs_remote_symlink().
void nfs3_remote_Symlink_Free (nfs_res_t * resp)
nfs3_remote_Symlink_Free: Frees the result structure allocated for nfs3_remote_Symlink.
Frees the result structure allocated for nfs3_remote_Symlink.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 2023 of file nfs_remote_functions.c.
Referenced by nfs_remote_symlink().
int nfs3_remote_Write (CLIENT * clnt, nfs_arg_t * parg, nfs_res_t * pres)
nfs3_remote_Write: The NFS proc write function, v3.
The NFS proc write function, v3.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 1051 of file nfs_remote_functions.c.
void nfs3_remote_Write_Free (nfs_res_t * resp)
nfs3_remote_Write_Free: Frees the result structure allocated for nfs3_remote_Write.
Frees the result structure allocated for nfs3_remote_Write.
Parameters:
pres [INOUT] Pointer to the result structure.
Definition at line 1984 of file nfs_remote_functions.c.
int nfs4_remote_COMPOUND (CLIENT * clnt, COMPOUND4args * parg, COMPOUND4res * pres)
nfs4_remote_COMPOUND: The NFS proc compound function, v4.
The NFS proc compound function, v4.
Parameters:
clnt [IN]
parg [IN]
pres [OUT]
Definition at line 1490 of file nfs_remote_functions.c.
int nfs4_remote_Null (CLIENT * clnt)
nfs4_remote_Null: The NFS proc null function, v4.
The NFS proc null function, v4.
Parameters:
clnt [IN]
Definition at line 1465 of file nfs_remote_functions.c.