main.c File Reference
main shell routine.
#include `shell.h`
#include `Getopt.h`
#include <libgen.h>
#include <pthread.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <readline/readline.h>
#include <readline/history.h>
Classes
struct shell_info__
Defines
#define NBTHRMAX 64
Typedefs
typedef shell_info__ shell_info_t
Functions
void * LaunchShell (void *arg)
int main (int argc, char **argv)
Variables
time_t ServerBootTime = 0
shell_info_t thrlist [NBTHRMAX]
int verbose = 0
Detailed Description
main shell routine.
Author:
Author leibovic
Date:
Date 2006/02/23 07:42:53
Version:
Revision 1.28
Log main.c(p.),v
Revision 1.28 2006/02/23 07:42:53 leibovic Adding -n option to shell.
Revision 1.27 2005/11/28 17:03:00 deniel Added CeCILL headers
Revision 1.26 2005/08/12 11:56:59 leibovic coquille.
Revision 1.25 2005/07/26 12:54:47 leibovic Multi-thread shell with synchronisation routines.
Revision 1.24 2005/05/09 12:23:55 leibovic Version 2 of ganeshell.
Definition in file main.c.
Define Documentation
#define NBTHRMAX 64
Definition at line 117 of file main.c.
Referenced by main().
Typedef Documentation
typedef struct shell_info__ shell_info_t
Referenced by LaunchShell().
Function Documentation
void* LaunchShell (void * arg)
Definition at line 142 of file main.c.
References shell_info__::prompt, shell_info__::script_file, shell_info__::shell_id, shell_info_t, shell_Init(), shell_Launch(), shell_info__::status, and verbose.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 174 of file main.c.
References Getopt(), LaunchShell(), NBTHRMAX, NULL, Optarg, Opterr, Optind, Optopt, ServerBootTime, shell_BarrierInit(), shell_info__::shell_id, shell_Init(), shell_Launch(), thrlist, and verbose.
Variable Documentation
time_t ServerBootTime = 0
Definition at line 119 of file main.c.
Referenced by main().
shell_info_t thrlist[NBTHRMAX]
Definition at line 136 of file main.c.
Referenced by main().
int verbose = 0
Definition at line 138 of file main.c.
Referenced by LaunchShell(), main(), and shell_Init().