shell_utils.h File Reference
Miscellaneous build-in commands for shell.
#include `shell_types.h`
#include <stdio.h>
Functions
int util_timer (int argc, char **argv, FILE *output)
int util_sleep (int argc, char **argv, FILE *output)
int util_shell (int argc, char **argv, FILE *output)
int util_meminfo (int argc, char **argv, FILE *output)
int util_cmp (int argc, char **argv, FILE *output)
int util_diff (int argc, char **argv, FILE *output)
int util_wc (int argc, char **argv, FILE *output)
int util_chomp (int argc, char **argv, FILE *output)
Detailed Description
Miscellaneous build-in commands for shell.
Author:
Author leibovic
Date:
Date 2005/05/11 07:25:45
Version:
Revision 1.3
Log shell_utils.h(p.),v
Revision 1.3 2005/05/11 07:25:45 leibovic adding chomp util.
Revision 1.2 2005/05/09 14:54:43 leibovic Adding eq and ne.
Revision 1.1 2005/05/09 12:23:55 leibovic Version 2 of ganeshell.
Definition in file shell_utils.h.
Function Documentation
int util_chomp (int argc, char ** argv, FILE * output)
Definition at line 736 of file shell_utils.c.
int util_cmp (int argc, char ** argv, FILE * output)
String utils
Definition at line 419 of file shell_utils.c.
References Getopt(), my_atoi(), Opterr, Optind, and Optopt.
int util_diff (int argc, char ** argv, FILE * output)
Definition at line 674 of file shell_utils.c.
int util_meminfo (int argc, char ** argv, FILE * output)
Definition at line 344 of file shell_utils.c.
int util_shell (int argc, char ** argv, FILE * output)
Definition at line 291 of file shell_utils.c.
int util_sleep (int argc, char ** argv, FILE * output)
System utils.
Definition at line 251 of file shell_utils.c.
References my_atoi().
int util_timer (int argc, char ** argv, FILE * output)
Timer management.
Definition at line 146 of file shell_utils.c.
References NULL, print_timeval, and time_diff().
int util_wc (int argc, char ** argv, FILE * output)
Definition at line 716 of file shell_utils.c.