shell.c File Reference
Internal routines for the shell.
#include `shell.h`
#include `shell_utils.h`
#include `shell_vars.h`
#include `log_functions.h`
#include `commands.h`
#include `cmd_tools.h`
#include `BuddyMalloc.h`
#include `stuff_alloc.h`
#include <unistd.h>
#include <string.h>
#include <stdio.h>
#include <readline/readline.h>
#include <readline/history.h>
#include <sys/time.h>
Defines
#define MAX_OUTPUT_LEN (1024*1024)
#define TRACEBUFFSIZE 1024
#define PROMPTSIZE 64
#define P(_mutex_) pthread_mutex_lock(&_mutex_)
#define V(_mutex_) pthread_mutex_unlock(&_mutex_)
Functions
int shell_BarrierInit (int nb_threads)
int shell_Init (int verbose, char *input_file, char *prompt, int shell_index)
int shell_Launch ()
int shell_ParseLine (char *in_out_line, char **out_arglist, int *p_argcount)
int shell_SolveArgs (int argc, char **in_out_argv, int *out_allocated)
void shell_CleanArgs (int argc, char **in_out_argv, int *in_allocated)
int shell_Execute (int argc, char **argv, FILE *output)
void shell_PrintError (shell_state_t *context, char *error_msg)
void shell_PrintTrace (shell_state_t *context, char *msg)
int shell_SetLayer (shell_state_t *context, char *layer_name)
layer_def_t * shell_GetLayer (shell_state_t *context)
int shell_SetStatus (shell_state_t *context, int returned_status)
int shell_GetStatus (shell_state_t *context)
int shell_SetVerbose (shell_state_t *context, char *str_verbose)
int shell_GetVerbose (shell_state_t *context)
int shell_SetDbgLvl (shell_state_t *context, char *str_debug_level)
int shell_GetDbgLvl (shell_state_t *context)
int shell_SetInput (shell_state_t *context, char *file_name)
FILE * shell_GetInputStream (shell_state_t *context)
int shell_SetPrompt (shell_state_t *context, char *str_prompt)
char * shell_GetPrompt (shell_state_t *context)
int shell_SetShellId (shell_state_t *context, int shell_index)
int shell_SetLine (shell_state_t *context, int lineno)
int shell_GetLine (shell_state_t *context)
int shellcmd_help (int argc, char **argv, FILE *output)
int shellcmd_if (int argc, char **argv, FILE *output)
int shellcmd_interactive (int argc, char **argv, FILE *output)
int shellcmd_set (int argc, char **argv, FILE *output)
int shellcmd_unset (int argc, char **argv, FILE *output)
int shellcmd_print (int argc, char **argv, FILE *output)
int shellcmd_varlist (int argc, char **argv, FILE *output)
int shellcmd_time (int argc, char **argv, FILE *output)
int shellcmd_quit (int argc, char **argv, FILE *output)
int shellcmd_barrier (int argc, char **argv, FILE *output)
Detailed Description
Internal routines for the shell.
Author:
Author leibovic
Date:
Date 2006/02/24 08:33:44
Version:
Revision 1.20
Log shell.c(p.),v
Revision 1.20 2006/02/24 08:33:44 leibovic shellid is read only.
Revision 1.19 2006/02/23 07:42:53 leibovic Adding -n option to shell.
Revision 1.18 2006/02/08 12:50:00 leibovic changing NIV_EVNMT to NIV_EVENT.
Revision 1.17 2006/01/17 14:56:22 leibovic Adaptation de HPSS 6.2.
Revision 1.16 2005/11/28 17:03:00 deniel Added CeCILL headers
Revision 1.15 2005/09/27 09:30:16 leibovic Removing non-thread safe trace buffer.
Revision 1.14 2005/09/27 08:15:13 leibovic Adding traces and changhing readexport prototype.
Revision 1.13 2005/08/12 12:15:33 leibovic Erreur d'init.
Revision 1.12 2005/08/12 11:21:27 leibovic Now, set cat concatenate strings.
Revision 1.11 2005/08/05 07:59:21 leibovic Better help printing.
Revision 1.10 2005/07/29 13:34:28 leibovic Changing _FULL_DEBUG to _DEBUG_SHELL
Revision 1.9 2005/07/26 12:54:47 leibovic Multi-thread shell with synchronisation routines.
Revision 1.8 2005/07/25 12:50:45 leibovic Adding thr_create and thr_join commands.
Revision 1.7 2005/05/11 15:53:37 leibovic Adding time function.
Revision 1.6 2005/05/11 07:25:58 leibovic Escaped char support.
Revision 1.5 2005/05/10 14:02:27 leibovic Fixed bug in log management.
Revision 1.4 2005/05/10 11:38:07 leibovic Adding log initialization.
Revision 1.3 2005/05/10 11:07:21 leibovic Adapting to ganeshell v2.
Revision 1.2 2005/05/09 14:54:59 leibovic Adding if.
Revision 1.1 2005/05/09 12:23:55 leibovic Version 2 of ganeshell.
Definition in file shell.c.
Define Documentation
#define MAX_OUTPUT_LEN (1024*1024)
Definition at line 173 of file shell.c.
Referenced by shell_SolveArgs(), and shellcmd_set().
#define P(_mutex_) pthread_mutex_lock(&_mutex_)
Definition at line 187 of file shell.c.
Referenced by shell_BarrierInit().
#define PROMPTSIZE 64
Definition at line 177 of file shell.c.
#define TRACEBUFFSIZE 1024
Definition at line 175 of file shell.c.
Referenced by shell_Execute(), shell_SetDbgLvl(), shell_SetInput(), shell_SetLayer(), shell_SetLine(), shell_SetPrompt(), shell_SetShellId(), shell_SetStatus(), shell_SetVerbose(), shell_SolveArgs(), shellcmd_barrier(), shellcmd_help(), shellcmd_interactive(), shellcmd_quit(), shellcmd_set(), shellcmd_unset(), and shellcmd_varlist().
#define V(_mutex_) pthread_mutex_unlock(&_mutex_)
Definition at line 188 of file shell.c.
Referenced by shell_BarrierInit().
Function Documentation
int shell_BarrierInit (int nb_threads)
Initialize the barrier for shell synchronization routines. The number of threads to wait for is given as parameter.
Definition at line 209 of file shell.c.
References P, and V.
Referenced by main().
void shell_CleanArgs (int argc, char ** in_out_argv, int * in_allocated)
shell_CleanArgs: Free allocated arguments.
Parameters:
argc The number of command line tokens.
in_out_argv The list of command line tokens (modified).
in_allocated Indicates which tokens must be freed.
Definition at line 1090 of file shell.c.
Referenced by shell_Launch(), and shell_SolveArgs().
int shell_Execute (int argc, char ** argv, FILE * output)
shell_Execute: Commands dispatcher.
Parameters:
argc The number of arguments of this command.
argv The arguments for this command.
output The output stream of this command.
Returns: The returned status of this command.
Definition at line 1123 of file shell.c.
References command_def__::command_func, layer_def__::command_list, command_def__::command_name, layer_def_t, layer_def__::setlog_func, shell_GetDbgLvl(), shell_GetLayer(), shell_GetVerbose(), shell_PrintError(), shell_PrintTrace(), shell_state_t, and TRACEBUFFSIZE.
Referenced by shell_Launch(), shell_SolveArgs(), shellcmd_if(), and shellcmd_time().
int shell_GetDbgLvl (shell_state_t * context)
shell_GetDbgLvl Get the special variable $DEBUG_LEVEL and $DBG_LVL (internal use).
Definition at line 1558 of file shell.c.
References shell_state__::debug_level, and shell_state_t.
FILE* shell_GetInputStream (shell_state_t * context)
shell_GetInputStream Get the input stream for reading commands (internal use).
Definition at line 1688 of file shell.c.
References shell_state__::input_stream, and shell_state_t.
layer_def_t* shell_GetLayer (shell_state_t * context)
shell_GetLayer: Retrieves the current active layer (internal use).
Definition at line 1366 of file shell.c.
References shell_state__::layer, layer_def_t, and shell_state_t.
Referenced by shell_Execute(), and shellcmd_help().
int shell_GetLine (shell_state_t * context)
shell_GetLine Get the special variable $LINE
Definition at line 1790 of file shell.c.
References shell_state__::line, and shell_state_t.
Referenced by shell_Launch(), shell_PrintError(), and shell_PrintTrace().
char* shell_GetPrompt (shell_state_t * context)
shell_GetPrompt Get the special variable $PROMPT
Definition at line 1724 of file shell.c.
References get_var_value(), and shell_state_t.
int shell_GetStatus (shell_state_t * context)
shell_GetStatus Get the special variables $? or $STATUS (internal use).
Definition at line 1416 of file shell.c.
References shell_state_t, and shell_state__::status.
int shell_GetVerbose (shell_state_t * context)
shell_GetVerbose Get the special variable $VERBOSE (internal use).
Definition at line 1490 of file shell.c.
References shell_state_t, and shell_state__::verbose.
Referenced by shell_Execute(), shell_PrintTrace(), and shellcmd_varlist().
int shell_Init (int verbose, char * input_file, char * prompt, int shell_index)
Initialize the shell. The command line for the shell is given as parameter.
Parameters:
input_file the file to read from (NULL if stdin).
Definition at line 358 of file shell.c.
References NULL, shell_SetDbgLvl(), shell_SetInput(), shell_SetPrompt(), shell_SetShellId(), shell_SetVerbose(), shell_state_t, and verbose.
Referenced by LaunchShell(), and main().
int shell_Launch ()
Run the interpreter.
Definition at line 473 of file shell.c.
References shell_state__::input_stream, shell_state__::interactive, MAX_LINE_LEN, shell_CleanArgs(), shell_Execute(), shell_GetLine(), shell_ParseLine(), shell_SetLine(), shell_SetStatus(), shell_SolveArgs(), and shell_state_t.
Referenced by LaunchShell(), and main().
int shell_ParseLine (char * in_out_line, char ** out_arglist, int * p_argcount)
shell_ParseLine: Extract an arglist from a command line.
Parameters:
in_out_line The command line (modified).
out_arglist The list of command line tokens.
p_argcount The number of command line tokens.
Returns: 0 if no errors.
Definition at line 695 of file shell.c.
Referenced by shell_Launch(), and shell_SolveArgs().
void shell_PrintError (shell_state_t * context, char * error_msg)
shell_PrintError: Prints an error.
Definition at line 1257 of file shell.c.
References get_var_value(), shell_GetLine(), and shell_state_t.
Referenced by shell_Execute(), shell_SetDbgLvl(), shell_SetInput(), shell_SetLayer(), shell_SetLine(), shell_SetPrompt(), shell_SetShellId(), shell_SetStatus(), shell_SetVerbose(), shell_SolveArgs(), shellcmd_barrier(), shellcmd_help(), shellcmd_interactive(), shellcmd_quit(), shellcmd_set(), shellcmd_unset(), and shellcmd_varlist().
void shell_PrintTrace (shell_state_t * context, char * msg)
shell_PrintTrace: Prints a verbose trace.
Definition at line 1275 of file shell.c.
References get_var_value(), shell_GetLine(), shell_GetVerbose(), and shell_state_t.
Referenced by shell_Execute(), shell_SetInput(), and shell_SetLayer().
int shell_SetDbgLvl (shell_state_t * context, char * str_debug_level)
shell_SetDbgLvl Set the special variables $DEBUG_LEVEL and $DBG_LVL
Definition at line 1500 of file shell.c.
References shell_state__::debug_level, set_var_value(), shell_PrintError(), shell_state_t, and TRACEBUFFSIZE.
Referenced by shell_Init(), and shellcmd_set().
int shell_SetInput (shell_state_t * context, char * file_name)
shell_SetInput Set the input for reading commands and set the value of $INPUT and $INTERACTIVE.
Parameters:
file_name: a script file or NULL for reading from stdin.
Definition at line 1573 of file shell.c.
References shell_state__::input_stream, shell_state__::interactive, set_var_value(), shell_PrintError(), shell_PrintTrace(), shell_SetLine(), shell_state_t, and TRACEBUFFSIZE.
Referenced by shell_Init(), shellcmd_interactive(), and shellcmd_set().
int shell_SetLayer (shell_state_t * context, char * layer_name)
shell_SetLayer: Set the current active layer.
Returns: 0 if OK. else, an error code.
Definition at line 1306 of file shell.c.
References shell_state__::layer, layer_def_t, layer_def__::layer_name, set_var_value(), shell_PrintError(), shell_PrintTrace(), shell_state_t, and TRACEBUFFSIZE.
Referenced by shellcmd_set().
int shell_SetLine (shell_state_t * context, int lineno)
shell_SetLine Set the special variable $LINE
Definition at line 1761 of file shell.c.
References shell_state__::line, set_var_value(), shell_PrintError(), shell_state_t, and TRACEBUFFSIZE.
Referenced by shell_Launch(), and shell_SetInput().
int shell_SetPrompt (shell_state_t * context, char * str_prompt)
shell_SetPrompt Set the special variable $PROMPT
Definition at line 1703 of file shell.c.
References set_var_value(), shell_PrintError(), shell_state_t, and TRACEBUFFSIZE.
Referenced by shell_Init(), and shellcmd_set().
int shell_SetShellId (shell_state_t * context, int shell_index)
shell_SetShellId Set the special variable $SHELLID
Definition at line 1735 of file shell.c.
References set_var_value(), shell_PrintError(), shell_state_t, and TRACEBUFFSIZE.
Referenced by shell_Init().
int shell_SetStatus (shell_state_t * context, int returned_status)
shell_SetStatus Set the special variables $? and $STATUS.
Definition at line 1378 of file shell.c.
References set_var_value(), shell_PrintError(), shell_state_t, shell_state__::status, and TRACEBUFFSIZE.
Referenced by shell_Launch(), shell_SolveArgs(), and shellcmd_set().
int shell_SetVerbose (shell_state_t * context, char * str_verbose)
shell_SetVerbose Set the special variable $VERBOSE.
Definition at line 1426 of file shell.c.
References set_var_value(), shell_PrintError(), shell_state_t, TRACEBUFFSIZE, and shell_state__::verbose.
Referenced by shell_Init(), and shellcmd_set().
int shell_SolveArgs (int argc, char ** in_out_argv, int * out_allocated)
shell_SolveArgs: Interprets arguments if they are vars or commands.
Parameters:
argc The number of command line tokens.
in_out_argv The list of command line tokens (modified).
out_allocated Indicates which tokens must be freed.
Returns: 0 if no errors.
Definition at line 804 of file shell.c.
References get_var_value(), MAX_OUTPUT_LEN, shell_CleanArgs(), shell_Execute(), shell_ParseLine(), shell_PrintError(), shell_SetStatus(), shell_state_t, and TRACEBUFFSIZE.
Referenced by shell_Launch().
int shellcmd_barrier (int argc, char ** argv, FILE * output)
Definition at line 2306 of file shell.c.
References shell_PrintError(), and TRACEBUFFSIZE.
int shellcmd_help (int argc, char ** argv, FILE * output)
Definition at line 1802 of file shell.c.
References command_def__::command_help, layer_def__::command_list, command_def__::command_name, layer_def_t, layer_def__::layer_name, shell_GetLayer(), shell_PrintError(), and TRACEBUFFSIZE.
int shellcmd_if (int argc, char ** argv, FILE * output)
Definition at line 1879 of file shell.c.
References shell_Execute().
int shellcmd_interactive (int argc, char ** argv, FILE * output)
Definition at line 1973 of file shell.c.
References NULL, shell_PrintError(), shell_SetInput(), and TRACEBUFFSIZE.
int shellcmd_print (int argc, char ** argv, FILE * output)
Definition at line 2179 of file shell.c.
int shellcmd_quit (int argc, char ** argv, FILE * output)
Definition at line 2278 of file shell.c.
References shell_PrintError(), and TRACEBUFFSIZE.
int shellcmd_set (int argc, char ** argv, FILE * output)
Definition at line 2003 of file shell.c.
References concat(), is_authorized_varname(), MAX_OUTPUT_LEN, my_atoi(), set_var_value(), shell_PrintError(), shell_SetDbgLvl(), shell_SetInput(), shell_SetLayer(), shell_SetPrompt(), shell_SetStatus(), shell_SetVerbose(), and TRACEBUFFSIZE.
int shellcmd_time (int argc, char ** argv, FILE * output)
Definition at line 2231 of file shell.c.
References NULL, print_timeval, shell_Execute(), and time_diff().
int shellcmd_unset (int argc, char ** argv, FILE * output)
Definition at line 2115 of file shell.c.
References free_var(), shell_PrintError(), and TRACEBUFFSIZE.
int shellcmd_varlist (int argc, char ** argv, FILE * output)
Definition at line 2201 of file shell.c.
References print_varlist(), shell_GetVerbose(), shell_PrintError(), and TRACEBUFFSIZE.