shell_utils.c File Reference
Miscellaneous build-in commands for shell.
#include `cmd_tools.h`
#include <errno.h>
#include `shell_utils.h`
#include `Getopt.h`
#include <string.h>
#include `stuff_alloc.h`
#include <malloc.h>
#include <sys/time.h>
Functions
int util_timer (int argc, char **argv, FILE *output)
int util_sleep (int argc, char **argv, FILE *output)
int util_shell (int argc, char **argv, FILE *output)
int util_meminfo (int argc, char **argv, FILE *output)
int util_cmp (int argc, char **argv, FILE *output)
int util_diff (int argc, char **argv, FILE *output)
int util_wc (int argc, char **argv, FILE *output)
int util_chomp (int argc, char **argv, FILE *output)
Detailed Description
Miscellaneous build-in commands for shell.
Author:
Author leibovic
Date:
Date 2006/01/17 14:56:22
Version:
Revision 1.8
Log shell_utils.c(p.),v
Revision 1.8 2006/01/17 14:56:22 leibovic Adaptation de HPSS 6.2.
Revision 1.7 2005/11/28 17:03:00 deniel Added CeCILL headers
Revision 1.6 2005/10/10 12:39:08 leibovic Using mnt/nfs free functions.
Revision 1.5 2005/08/02 09:40:28 leibovic stream error in diff.
Revision 1.4 2005/05/11 15:53:37 leibovic Adding time function.
Revision 1.3 2005/05/11 07:25:45 leibovic adding chomp util.
Revision 1.2 2005/05/09 14:54:43 leibovic Adding eq and ne.
Revision 1.1 2005/05/09 12:23:55 leibovic Version 2 of ganeshell.
Definition in file shell_utils.c.
Function Documentation
int util_chomp (int argc, char ** argv, FILE * output)
Definition at line 736 of file shell_utils.c.
int util_cmp (int argc, char ** argv, FILE * output)
String utils
Definition at line 419 of file shell_utils.c.
References Getopt(), my_atoi(), Opterr, Optind, and Optopt.
int util_diff (int argc, char ** argv, FILE * output)
Definition at line 674 of file shell_utils.c.
int util_meminfo (int argc, char ** argv, FILE * output)
Definition at line 344 of file shell_utils.c.
int util_shell (int argc, char ** argv, FILE * output)
Definition at line 291 of file shell_utils.c.
int util_sleep (int argc, char ** argv, FILE * output)
System utils.
Definition at line 251 of file shell_utils.c.
References my_atoi().
int util_timer (int argc, char ** argv, FILE * output)
Timer management.
Definition at line 146 of file shell_utils.c.
References NULL, print_timeval, and time_diff().
int util_wc (int argc, char ** argv, FILE * output)
Definition at line 716 of file shell_utils.c.