shell_vars.c File Reference
variables management for the shell.
#include <HashTable.h>
#include <strings.h>
#include <stdlib.h>
#include <string.h>
#include `shell_vars.h`
#include `stuff_alloc.h`
Classes
struct shell_variable__
Defines
#define IS_LETTER(_c_) (((_c_) >= 'a') && ((_c_) <= 'z'))
#define IS_LETTER_CAP(_c_) (((_c_) >= 'A') && ((_c_) <= 'Z'))
#define IS_NUMERIC(_c_) (((_c_) >= '0') && ((_c_) <= '9'))
Typedefs
typedef shell_variable__ shell_variable_t
Functions
void SetVarTable (shell_variable_t *var_table)
void print_varlist (FILE *output, int is_dlen)
int is_authorized_varname (char *str)
char * get_var_value (char *varname)
int set_var_value (char *varname, char *var_value)
int free_var (char *varname)
Detailed Description
variables management for the shell.
Author:
Author leibovic
Date:
Date 2006/01/24 13:49:33
Version:
Revision 1.8
Log shell_vars.c(p.),v
Revision 1.8 2006/01/24 13:49:33 leibovic Adding missing includes.
Revision 1.7 2005/11/28 17:03:01 deniel Added CeCILL headers
Revision 1.6 2005/07/26 12:54:47 leibovic Multi-thread shell with synchronisation routines.
Revision 1.5 2005/05/10 14:02:45 leibovic Removing adherence to BuddyMalloc.
Revision 1.4 2005/05/09 12:23:55 leibovic Version 2 of ganeshell.
Revision 1.3 2005/05/03 08:06:23 leibovic Adding meminfo command.
Revision 1.2 2005/05/03 07:37:58 leibovic Using Mem_Alloc and Mem_Free.
Revision 1.1 2004/12/14 09:56:00 leibovic Variables management.
Definition in file shell_vars.c.
Define Documentation
#define IS_LETTER(_c_) (((_c_) >= 'a') && ((_c_) <= 'z'))
Definition at line 269 of file shell_vars.c.
Referenced by is_authorized_varname().
#define IS_LETTER_CAP(_c_) (((_c_) >= 'A') && ((_c_) <= 'Z'))
Definition at line 270 of file shell_vars.c.
Referenced by is_authorized_varname().
#define IS_NUMERIC(_c_) (((_c_) >= '0') && ((_c_) <= '9'))
Definition at line 271 of file shell_vars.c.
Referenced by is_authorized_varname().
Typedef Documentation
typedef struct shell_variable__ shell_variable_t
Referenced by free_var(), get_var_value(), print_varlist(), set_var_value(), and SetVarTable().
Function Documentation
int free_var (char * varname)
free the resources used by a variable.
Definition at line 337 of file shell_vars.c.
References shell_variable_t.
Referenced by shellcmd_unset().
char* get_var_value (char * varname)
returns the value for a variable, NULL if the variable doesn't exist.
Definition at line 308 of file shell_vars.c.
References shell_variable_t, and shell_variable__::var_value.
Referenced by shell_GetPrompt(), shell_PrintError(), shell_PrintTrace(), and shell_SolveArgs().
int is_authorized_varname (char * str)
indicates whether a name is authorized for a variable. A variable name must be in [a-zA-Z0-9._:]*
Definition at line 276 of file shell_vars.c.
References IS_LETTER, IS_LETTER_CAP, and IS_NUMERIC.
Referenced by shellcmd_set().
void print_varlist (FILE * output, int is_dlen)
print var list.
Definition at line 182 of file shell_vars.c.
References shell_variable__::datalen, shell_variable_t, and shell_variable__::var_name.
Referenced by shellcmd_varlist().
int set_var_value (char * varname, char * var_value)
set the value for a variable, and create it if necessary.
Definition at line 321 of file shell_vars.c.
References shell_variable_t.
Referenced by shell_SetDbgLvl(), shell_SetInput(), shell_SetLayer(), shell_SetLine(), shell_SetPrompt(), shell_SetShellId(), shell_SetStatus(), shell_SetVerbose(), and shellcmd_set().
void SetVarTable (shell_variable_t * var_table)
Definition at line 170 of file shell_vars.c.
References shell_variable_t.