shell_vars.h File Reference
variables management for the shell.
#include <stdio.h>
Defines
#define MAX_VAR_LEN 32
Functions
int is_authorized_varname (char *str)
char * get_var_value (char *varname)
int set_var_value (char *varname, char *var_value)
int free_var (char *varname)
void print_varlist (FILE *output, int is_dlen)
Detailed Description
variables management for the shell.
Author:
Author leibovic
Date:
Date 2005/05/09 12:23:55
Version:
Revision 1.2
Log shell_vars.h(p.),v
Revision 1.2 2005/05/09 12:23:55 leibovic Version 2 of ganeshell.
Revision 1.1 2004/12/14 09:56:00 leibovic Variables management.
Definition in file shell_vars.h.
Define Documentation
#define MAX_VAR_LEN 32
Definition at line 24 of file shell_vars.h.
Function Documentation
int free_var (char * varname)
free the resources used by a variable.
Definition at line 337 of file shell_vars.c.
References shell_variable_t.
Referenced by shellcmd_unset().
char* get_var_value (char * varname)
returns the value for a variable, NULL if the variable doesn't exist.
Definition at line 308 of file shell_vars.c.
References shell_variable_t, and shell_variable__::var_value.
Referenced by shell_GetPrompt(), shell_PrintError(), shell_PrintTrace(), and shell_SolveArgs().
int is_authorized_varname (char * str)
indicates whether a name is authorized for a variable. A variable name must be in [a-zA-Z0-9._:]*
Definition at line 276 of file shell_vars.c.
References IS_LETTER, IS_LETTER_CAP, and IS_NUMERIC.
Referenced by shellcmd_set().
void print_varlist (FILE * output, int is_dlen)
print var list.
Definition at line 182 of file shell_vars.c.
References shell_variable__::datalen, shell_variable_t, and shell_variable__::var_name.
Referenced by shellcmd_varlist().
int set_var_value (char * varname, char * var_value)
set the value for a variable, and create it if necessary.
Definition at line 321 of file shell_vars.c.
References shell_variable_t.
Referenced by shell_SetDbgLvl(), shell_SetInput(), shell_SetLayer(), shell_SetLine(), shell_SetPrompt(), shell_SetShellId(), shell_SetStatus(), shell_SetVerbose(), and shellcmd_set().