.TH "cache_inode_fsal_glue.c" 3 "22 Dec 2006" "Version 0.1" "glue layer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cache_inode_fsal_glue.c \- Glue functions between the FSAL and the Cache inode layers. 
.SH SYNOPSIS
.br
.PP
\fC#include 'log_functions.h'\fP
.br
\fC#include 'err_fsal.h'\fP
.br
\fC#include 'err_cache_inode.h'\fP
.br
\fC#include 'stuff_alloc.h'\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <strings.h>\fP
.br
\fC#include <sys/types.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBHPSS_SSM\fP   'hpss_ssm'"
.br
.ti -1c
.RI "#define \fBHPSS_KEYTAB\fP   '/krb5/hpssserver.keytab'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBdisplay_key\fP (hash_buffer_t *pbuff, char *str)"
.br
.ti -1c
.RI "int \fBdisplay_not_implemented\fP (hash_buffer_t *pbuff, char *str)"
.br
.ti -1c
.RI "int \fBdisplay_value\fP (hash_buffer_t *pbuff, char *str)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Glue functions between the FSAL and the Cache inode layers. 

\fBAuthor:\fP
.RS 4
\fBAuthor\fP.RS 4
leibovic 
.RE
.PP
.RE
.PP
\fBDate:\fP
.RS 4
\fBDate\fP.RS 4
2006/01/20 07:39:23 
.RE
.PP
.RE
.PP
\fBVersion:\fP
.RS 4
\fBRevision\fP.RS 4
1.9 
.RE
.PP
.RE
.PP
\fBcache_inode_fsal_glue.c\fP : Glue functions between the FSAL and the Cache inode layers.
.PP
\fBHeader\fP.RS 4
/cea/home/cvs/cvs/SHERPA/BaseCvs/GANESHA/src/glue/cache_inode_fsal_glue.c,v 1.9 2006/01/20 07:39:23 leibovic Exp 
.RE
.PP
.PP
\fBLog\fP.RS 4
\fBcache_inode_fsal_glue.c\fP,v 
.RE
.PP
Revision 1.9 2006/01/20 07:39:23 leibovic Back to the previous version.
.PP
Revision 1.7 2006/01/17 14:52:59 leibovic changin _USE_HPSS to _USE_HPSS_51 and _USE_HPSS_62
.PP
Revision 1.6 2005/11/28 17:02:58 deniel Added CeCILL headers
.PP
Revision 1.5 2005/10/05 14:03:31 deniel DEBUG ifdef are now much cleaner
.PP
Revision 1.4 2005/07/28 12:26:58 deniel NFSv3 PROTOCOL Ok
.PP
Revision 1.3 2005/04/15 12:25:15 deniel Added doxygen comments for code readability.
.PP
Revision 1.1 2005/04/15 07:56:14 deniel Populating the repository with glue layer
.PP
Definition in file \fBcache_inode_fsal_glue.c\fP.
.SH "Define Documentation"
.PP 
.SS "#define HPSS_KEYTAB   '/krb5/hpssserver.keytab'"
.PP
Definition at line 121 of file cache_inode_fsal_glue.c.
.SS "#define HPSS_SSM   'hpss_ssm'"
.PP
Definition at line 120 of file cache_inode_fsal_glue.c.
.SH "Function Documentation"
.PP 
.SS "int display_key (hash_buffer_t * pbuff, char * str)"
.PP
Definition at line 303 of file cache_inode_fsal_glue.c.
.SS "int display_not_implemented (hash_buffer_t * pbuff, char * str)"
.PP
Definition at line 315 of file cache_inode_fsal_glue.c.
.SS "int display_value (hash_buffer_t * pbuff, char * str)"
.PP
Definition at line 321 of file cache_inode_fsal_glue.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for glue layer from the source code.
