/*
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 3 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA
 *
 * ---------------------------------------
 */

/**
 * @file   fsal_up_utils.c
 * @author Adam C. Emerson <aemerson@linuxbox.com>
 * @date   Mon Sep 24 17:04:22 2012
 *
 * @brief Utilities for use by FSAL UP-call handlers and callers
 *
 */

#include "fsal_up.h"
#include "cache_inode_lru.h"

/**
 * @brief Look up a cache entry by a key
 *
 * This function retrieves a cache entry from a key generated by the
 * FSAL.  It does no attribute refresh, since this is for upcalls.  It
 * does, however, get a reference on the cache_entry that must be
 * returned with up_put.
 *
 * @param[in]  key   The key identifying the inode
 * @param[out] entry The entry looked up.
 *
 * @retval CACHE_INODE_SUCCESS on success.
 * @retval CACHE_INODE_NOT_FOUND if the inode could not be found or
 *         referenced.
 * @retval CACHE_INODE_HASH_TABLE_ERROR on some inexplicable failure.
 */
int
up_get(const struct gsh_buffdesc *key,
       cache_entry_t **entry)
{
        struct gsh_buffdesc hashkey = {
                .addr = key->addr,
                .len = key->len
        };
        struct gsh_buffdesc hashval;
        hash_error_t hrc = 0;
        struct hash_latch latch;
        cache_entry_t *entry_found = NULL;

        *entry = NULL;

        hrc = HashTable_GetLatch(fh_to_cache_entry_ht, &hashkey, &hashval,
                                 false,
                                 &latch);

        if (hrc == HASHTABLE_SUCCESS) {
                /* Entry exists in the cache and was found */
                entry_found = hashval.addr;
                if (cache_inode_lru_ref(entry_found, LRU_REQ_INITIAL) !=
                    CACHE_INODE_SUCCESS) {
                        HashTable_ReleaseLatched(fh_to_cache_entry_ht, &latch);
                        return CACHE_INODE_NOT_FOUND;
                } else {
                        *entry = entry_found;
                }
        } else if (hrc == HASHTABLE_ERROR_NO_SUCH_KEY) {
                HashTable_ReleaseLatched(fh_to_cache_entry_ht, &latch);
                return ENOENT;
        } else {
                /* This should not happen */
                LogCrit(COMPONENT_FSAL_UP,
                        "Hash access failed with code %d"
                        " - this should not have happened",
                        hrc);
                return EFAULT;
        }
        return CACHE_INODE_SUCCESS;
}
