nfs_client_id.c File Reference
#include `HashData.h`
#include `HashTable.h`
#include `log_functions.h`
#include `stuff_alloc.h`
#include `nfs_core.h`
#include `nfs_exports.h`
#include `config_parsing.h`
#include <stdlib.h>
#include <string.h>
#include `nfs4.h`
#include `SHA1.h`
Functions
size_t strnlen (const char *s, size_t maxlen)
unsigned long client_id_value_hash_func (hash_parameter_t *p_hparam, hash_buffer_t *buffclef)
unsigned long client_id_value_hash_func_reverse (hash_parameter_t *p_hparam, hash_buffer_t *buffclef)
unsigned long client_id_rbt_hash_func (hash_parameter_t *p_hparam, hash_buffer_t *buffclef)
unsigned long client_id_rbt_hash_func_reverse (hash_parameter_t *p_hparam, hash_buffer_t *buffclef)
int compare_client_id (hash_buffer_t *buff1, hash_buffer_t *buff2)
int compare_client_id_reverse (hash_buffer_t *buff1, hash_buffer_t *buff2)
int display_client_id (hash_buffer_t *pbuff, char *str)
int display_client_id_reverse (hash_buffer_t *pbuff, char *str)
int display_client_id_val (hash_buffer_t *pbuff, char *str)
int nfs_client_id_add (clientid4 clientid, nfs_client_id_t client_record, nfs_client_id_t *nfs_client_id_pool)
int nfs_client_id_set (clientid4 clientid, nfs_client_id_t client_record, nfs_client_id_t *nfs_client_id_pool)
int nfs_client_id_get (clientid4 clientid, nfs_client_id_t *client_id_res)
int nfs_client_id_get_reverse (char *key, nfs_client_id_t *client_id_res)
int nfs_client_id_remove (clientid4 clientid, nfs_client_id_t *nfs_client_id_pool)
int nfs_Init_client_id (nfs_client_id_parameter_t param)
int nfs_Init_client_id_reverse (nfs_client_id_parameter_t param)
int nfs_client_id_compute (char *name, clientid4 *pclientid)
int nfs_client_id_sha1_compute (char *name, clientid4 *pclientid)
Variables
hash_table_t * ht_client_id
hash_table_t * ht_client_id_reverse
nfs_parameter_t nfs_param
Function Documentation
unsigned long client_id_rbt_hash_func (hash_parameter_t * p_hparam, hash_buffer_t * buffclef)
client_id_rbt_hash_func: computes the rbt value for the entry in Client Id cache.
Computes the rbt value for the entry in Client Id cache. In fact, it just use the address value itself (which is an unsigned integer) as the rbt value. This function is called internal in the HasTable_* function
Parameters:
hparam [IN] hash table parameter.
buffcleff[in] pointer to the hash key buffer
Returns: the computed rbt value.
See also: HashTable_Init
Definition at line 181 of file nfs_client_id.c.
unsigned long client_id_rbt_hash_func_reverse (hash_parameter_t * p_hparam, hash_buffer_t * buffclef)
Definition at line 195 of file nfs_client_id.c.
References nfs_client_id_compute().
unsigned long client_id_value_hash_func (hash_parameter_t * p_hparam, hash_buffer_t * buffclef)
client_id_rbt_hash_func: computes the hash value for the entry in Client Id cache.
Computes the hash value for the entry in Client Id cache. In fact, it just use addresse as value (identity function) modulo the size of the hash. This function is called internal in the HasTable_* function
Parameters:
hparam [IN] hash table parameter.
buffcleff [IN] pointer to the hash key buffer
Returns: the computed hash value.
See also: HashTable_Init
Definition at line 123 of file nfs_client_id.c.
unsigned long client_id_value_hash_func_reverse (hash_parameter_t * p_hparam, hash_buffer_t * buffclef)
client_id_reverse_hash_func: computes the hash value for the entry in Client Id cache.
Computes the hash value for the entry in Client Id cache. In fact, it just use addresse as value (identity function) modulo the size of the hash. This function is called internal in the HasTable_* function
Parameters:
hparam [IN] hash table parameter.
buffcleff [IN] pointer to the hash key buffer
Returns: the computed hash value.
See also: HashTable_Init
Definition at line 153 of file nfs_client_id.c.
int compare_client_id (hash_buffer_t * buff1, hash_buffer_t * buff2)
compare_client_id: compares the ip address stored in the key buffers.
compare the ip address stored in the key buffers. This function is to be used as 'compare_key' field in the hashtable storing the nfs duplicated requests.
Parameters:
buff1 [IN] first key
buff2 [IN] second key
Returns: 0 if keys are identifical, 1 if they are different.
Definition at line 219 of file nfs_client_id.c.
int compare_client_id_reverse (hash_buffer_t * buff1, hash_buffer_t * buff2)
Definition at line 226 of file nfs_client_id.c.
int display_client_id (hash_buffer_t * pbuff, char * str)
display_client_id: displays the client_id stored in the buffer.
displays the client_id stored in the buffer. This function is to be used as 'key_to_str' field in the hashtable storing the nfs duplicated requests.
Parameters:
buff1 [IN] buffer to display
buff2 [OUT] output string
Returns: number of character written.
Definition at line 247 of file nfs_client_id.c.
int display_client_id_reverse (hash_buffer_t * pbuff, char * str)
Definition at line 256 of file nfs_client_id.c.
int display_client_id_val (hash_buffer_t * pbuff, char * str)
Definition at line 262 of file nfs_client_id.c.
int nfs_client_id_add (clientid4 clientid, nfs_client_id_t client_record, nfs_client_id_t * nfs_client_id_pool)
nfs_client_id_add: adds an entry in the duplicate requests cache.
Adds an entry in the duplicate requests cache.
Parameters:
clientid [IN] the client id used as key
client_record [IN] the candidate record for the client
nfs_client_id_pool [INOUT] values pool for hash table
Returns: CLIENT_ID_SUCCESS if successfull
.
CLIENT_ID_INSERT_MALLOC_ERROR if an error occured during the insertion process
CLIENT_ID_NETDB_ERROR if an error occured during the netdb query (via gethostbyaddr).
Definition at line 292 of file nfs_client_id.c.
References ht_client_id, ht_client_id_reverse, and nfs_param.
int nfs_client_id_compute (char * name, clientid4 * pclientid)
nfs_client_id_compute: computes the client id, based on the string.
Computes the client id, based on the string.
Definition at line 644 of file nfs_client_id.c.
References strnlen().
int nfs_client_id_get (clientid4 clientid, nfs_client_id_t * client_id_res)
nfs_client_id_get: Tries to get an entry for client_id cache.
Tries to get an entry for client_id cache.
Parameters:
clientid [IN] the client id
resclientid [OUT] the found client id
Returns: the result previously set if *pstatus == CLIENT_ID_SUCCESS
Definition at line 454 of file nfs_client_id.c.
References ht_client_id, and ht_client_id_reverse.
Referenced by nfs4_Check_Stateid(), and nfs4_is_lease_expired().
int nfs_client_id_get_reverse (char * key, nfs_client_id_t * client_id_res)
Definition at line 499 of file nfs_client_id.c.
References ht_client_id_reverse.
int nfs_client_id_remove (clientid4 clientid, nfs_client_id_t * nfs_client_id_pool)
nfs_client_id_remove: Tries to remove an entry for client_id cache
Tries to remove an entry for client_id cache.
Parameters:
clientid [IN] the clientid to be used as key
nfs_client_id_pool [INOUT] values pool for hash table
Returns: the result previously set if *pstatus == CLIENT_ID_SUCCESS
Definition at line 541 of file nfs_client_id.c.
References ht_client_id, and ht_client_id_reverse.
int nfs_client_id_set (clientid4 clientid, nfs_client_id_t client_record, nfs_client_id_t * nfs_client_id_pool)
nfs_client_id_sets: sets an entry that already exists.
Sets an entry that already exists
Parameters:
clientid [IN] the client id used as key
client_record [IN] the candidate record for the client
nfs_client_id_pool [INOUT] values pool for hash table
Returns: CLIENT_ID_SUCCESS if successfull
.
CLIENT_ID_INSERT_MALLOC_ERROR if an error occured during the insertion process
CLIENT_ID_NETDB_ERROR if an error occured during the netdb query (via gethostbyaddr).
Definition at line 378 of file nfs_client_id.c.
References ht_client_id, ht_client_id_reverse, and nfs_param.
int nfs_client_id_sha1_compute (char * name, clientid4 * pclientid)
nfs_client_id_sha1_compute: computes the client id, based on the string, with SHA1 algorithm
Computes the client id, based on the string, with SHA1 algorithm.
Definition at line 752 of file nfs_client_id.c.
References SHA1Final(), SHA1Init(), and SHA1Update().
Referenced by main().
int nfs_Init_client_id (nfs_client_id_parameter_t param)
nfs_Init_client_id: Init the hashtable for Client Id cache.
Perform all the required initialization for hashtable Client Id cache
Parameters:
param [IN] parameter used to init the duplicate request cache
Returns: 0 if successful, -1 otherwise
Definition at line 600 of file nfs_client_id.c.
References ht_client_id.
int nfs_Init_client_id_reverse (nfs_client_id_parameter_t param)
nfs_Init_client_id_reverse: Init the reverse hashtable for Client Id cache.
Perform all the required initialization for hashtable Client Id cache
Parameters:
param [IN] parameter used to init the duplicate request cache
Returns: 0 if successful, -1 otherwise
Definition at line 622 of file nfs_client_id.c.
References ht_client_id_reverse.
size_t strnlen (const char * s, size_t maxlen)
vim:expandtab:shiftwidth=8:tabstop=8:
Copyright CEA/DAM/DIF (2008) contributeur : Philippe DENIEL philippe.deniel@cea.fr Thomas LEIBOVICI thomas.leibovici@cea.fr
Ce logiciel est un serveur implementant le protocole NFS.
Ce logiciel est regi par la licence CeCILL soumise au droit francais et respectant les principes de diffusion des logiciels libres. Vous pouvez utiliser, modifier et/ou redistribuer ce programme sous les conditions de la licence CeCILL telle que diffusee par le CEA, le CNRS et l'INRIA sur le site `http://www.cecill.info`.
En contrepartie de l'accessibilite au code source et des droits de copie, de modification et de redistribution accordes par cette licence, il n'est offert aux utilisateurs qu'une garantie limitee. Pour les memes raisons, seule une responsabilite restreinte pese sur l'auteur du programme, le titulaire des droits patrimoniaux et les concedants successifs.
A cet egard l'attention de l'utilisateur est attiree sur les risques associes au chargement, a l'utilisation, a la modification et/ou au developpement et a la reproduction du logiciel par l'utilisateur etant donne sa specificite de logiciel libre, qui peut le rendre complexe a manipuler et qui le reserve donc a des developpeurs et des professionnels avertis possedant des connaissances informatiques approfondies. Les utilisateurs sont donc invites a charger et tester l'adequation du logiciel a leurs besoins dans des conditions permettant d'assurer la securite de leurs systemes et ou de leurs donnees et, plus generalement, a l'utiliser et l'exploiter dans les memes conditions de securite.
Le fait que vous puissiez acceder a cet en-tete signifie que vous avez pris connaissance de la licence CeCILL, et que vous en avez accepte les termes.
---------------------
Copyright CEA/DAM/DIF (2005) Contributor: Philippe DENIEL philippe.deniel@cea.fr Thomas LEIBOVICI thomas.leibovici@cea.fr
This software is a server that implements the NFS protocol.
This software is governed by the CeCILL license under French law and abiding by the rules of distribution of free software. You can use, modify and/ or redistribute the software under the terms of the CeCILL license as circulated by CEA, CNRS and INRIA at the following URL `http://www.cecill.info`.
As a counterpart to the access to the source code and rights to copy, modify and redistribute granted by the license, users are provided only with a limited warranty and the software's author, the holder of the economic rights, and the successive licensors have only limited liability.
In this respect, the user's attention is drawn to the risks associated with loading, using, modifying and/or developing or reproducing the software by the user in light of its specific status of free software, that may mean that it is complicated to manipulate, and that also therefore means that it is reserved for developers and experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the software's suitability as regards their requirements in conditions enabling the security of their systems and/or data to be ensured and, more generally, to use and operate it in the same conditions as regards security.
The fact that you are presently reading this means that you have had knowledge of the CeCILL license and that you accept its terms. ---------------------------------------
nfs_client_id.c(p.) : The management of the client id cache.
$Header$
$Log$
Variable Documentation
hash_table_t* ht_client_id
Definition at line 102 of file nfs_client_id.c.
Referenced by nfs_client_id_add(), nfs_client_id_get(), nfs_client_id_remove(), nfs_client_id_set(), and nfs_Init_client_id().
hash_table_t* ht_client_id_reverse
Definition at line 103 of file nfs_client_id.c.
Referenced by nfs_client_id_add(), nfs_client_id_get(), nfs_client_id_get_reverse(), nfs_client_id_remove(), nfs_client_id_set(), and nfs_Init_client_id_reverse().
nfs_parameter_t nfs_param
Definition at line 146 of file test_clientid.c.