nfs_filehandle_mgmt.c File Reference
Some tools for managing the file handles.
#include <stdio.h>
#include <sys/types.h>
#include <ctype.h>
#include <stdlib.h>
#include <dirent.h>
#include <netdb.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <string.h>
#include <pthread.h>
#include <fcntl.h>
#include <sys/file.h>
#include <pwd.h>
#include <grp.h>
#include <rpc/types.h>
#include <rpc/rpc.h>
#include <rpc/auth.h>
#include <rpc/pmap_clnt.h>
#include `log_functions.h`
#include `stuff_alloc.h`
#include `nfs_core.h`
#include `nfs23.h`
#include `nfs4.h`
#include `fsal.h`
#include `nfs_tools.h`
#include `nfs_exports.h`
#include `nfs_file_handle.h`
Functions
int nfs4_FhandleToFSAL (nfs_fh4 *pfh4, fsal_handle_t *pfsalhandle, fsal_op_context_t *pcontext)
int nfs3_FhandleToFSAL (nfs_fh3 *pfh3, fsal_handle_t *pfsalhandle, fsal_op_context_t *pcontext)
int nfs2_FhandleToFSAL (fhandle2 *pfh2, fsal_handle_t *pfsalhandle, fsal_op_context_t *pcontext)
int nfs4_FSALToFhandle (nfs_fh4 *pfh4, fsal_handle_t *pfsalhandle, compound_data_t *data)
int nfs3_FSALToFhandle (nfs_fh3 *pfh3, fsal_handle_t *pfsalhandle, exportlist_t *pexport)
int nfs2_FSALToFhandle (fhandle2 *pfh2, fsal_handle_t *pfsalhandle, exportlist_t *pexport)
short nfs4_FhandleToExportId (nfs_fh4 *pfh4)
short nfs3_FhandleToExportId (nfs_fh3 *pfh3)
short nfs2_FhandleToExportId (fhandle2 *pfh2)
int nfs4_Is_Fh_Empty (nfs_fh4 *pfh)
int nfs4_Is_Fh_Pseudo (nfs_fh4 *pfh)
int nfs4_Is_Fh_Expired (nfs_fh4 *pfh)
int nfs4_Is_Fh_Invalid (nfs_fh4 *pfh)
unsigned long nfs2_FhandleCheckSum (file_handle_v2_t *pfh)
unsigned long nfs3_FhandleCheckSum (file_handle_v3_t *pfh)
unsigned long nfs4_FhandleCheckSum (file_handle_v4_t *pfh)
void print_fhandle2 (fhandle2 fh)
void sprint_fhandle2 (char *str, fhandle2 fh)
void print_fhandle3 (nfs_fh3 fh)
void sprint_fhandle3 (char *str, nfs_fh3 fh)
void print_fhandle4 (nfs_fh4 fh)
void sprint_fhandle4 (char *str, nfs_fh4 fh)
void print_buff (char *buff, int len)
void sprint_buff (char *str, char *buff, int len)
void print_compound_fh (compound_data_t *data)
void nfs4_sprint_fhandle (nfs_fh4 *fh4p, char *outstr)
Variables
time_t ServerBootTime
nfs_parameter_t nfs_param
Detailed Description
Some tools for managing the file handles.
Author:
Author deniel
Date:
Date 2006/01/24 11:43:05
Version:
Revision 1.12
nfs_filehandle_mgmt.c(p.) : Some tools for managing the file handles.
Header /cea/S/home/cvs/cvs/SHERPA/BaseCvs/GANESHA/src/support/nfs_filehandle_mgmt.c,v 1.12 2006/01/24 11:43:05 deniel Exp
Log nfs_filehandle_mgmt.c(p.),v
Revision 1.12 2006/01/24 11:43:05 deniel Code cleaning in progress
Revision 1.11 2006/01/11 08:12:18 deniel Added bug track and warning for badly formed handles
Revision 1.10 2005/11/28 17:03:03 deniel Added CeCILL headers
Revision 1.9 2005/09/07 08:58:30 deniel NFSv2 FH was only 31 byte long instead of 32
Revision 1.8 2005/09/07 08:16:07 deniel The checksum is filled with zeros before being computed to avoid 'dead beef' values
Revision 1.7 2005/08/11 12:37:28 deniel Added statistics management
Revision 1.6 2005/08/09 12:35:37 leibovic setting file_handle to 0 in nfs3_FSALToFhandle, before writting into it.
Revision 1.5 2005/08/08 14:09:25 leibovic setting checksum to 0 before writting in it.
Revision 1.4 2005/08/04 08:34:32 deniel memset management was badly made
Revision 1.3 2005/08/03 13:23:43 deniel Possible incoherency in CVS or in Emacs
Revision 1.2 2005/08/03 13:13:59 deniel memset to zero before building the filehandles
Revision 1.1 2005/08/03 06:57:54 deniel Added a libsupport for miscellaneous service functions
Revision 1.4 2005/07/28 12:26:57 deniel NFSv3 PROTOCOL Ok
Revision 1.3 2005/07/26 07:39:15 deniel Integration of NFSv2/NFSv3 In progress
Revision 1.2 2005/07/21 09:18:42 deniel Structure of the file handles was redefined
Revision 1.1 2005/07/20 12:56:54 deniel Reorganisation of the source files
Definition in file nfs_filehandle_mgmt.c.
Function Documentation
unsigned long nfs2_FhandleCheckSum (file_handle_v2_t * pfh)
nfs2_FhandleCheckSum
Computes the checksum associated with a nfsv2 file handle.
Parameters:
pfh [IN] pointer to the file handle whose checksum is to be computed.
Returns: the computed checksum.
Definition at line 672 of file nfs_filehandle_mgmt.c.
Referenced by nfs2_FhandleToFSAL(), and nfs2_FSALToFhandle().
short nfs2_FhandleToExportId (fhandle2 * pfh2)
nfs2_FhandleToExportId
This routine extracts the export id from the file handle NFSv2
Parameters:
pfh2 [IN] file handle to manage.
Returns: the export id.
Definition at line 542 of file nfs_filehandle_mgmt.c.
int nfs2_FhandleToFSAL (fhandle2 * pfh2, fsal_handle_t * pfsalhandle, fsal_op_context_t * pcontext)
nfs2_FhandleToFSAL: converts a nfs2 file handle to a FSAL file handle.
Converts a nfs2 file handle to a FSAL file handle.
Parameters:
pfh2 [IN] pointer to the file handle to be converted
pfsalhandle [OUT] pointer to the extracted FSAL handle
Returns: 1 if successful, 0 otherwise
Definition at line 289 of file nfs_filehandle_mgmt.c.
References nfs2_FhandleCheckSum(), print_buff(), and print_fhandle2().
int nfs2_FSALToFhandle (fhandle2 * pfh2, fsal_handle_t * pfsalhandle, exportlist_t * pexport)
nfs2_FSALToFhandle: converts a FSAL file handle to a nfs2 file handle.
Converts a nfs2 file handle to a FSAL file handle.
Parameters:
pfh2 [OUT] pointer to the extracted file handle
pfsalhandle [IN] pointer to the FSAL handle to be converted
pfsalhandle [IN] pointer to the FSAL handle to be converted
Returns: 1 if successful, 0 otherwise
Definition at line 443 of file nfs_filehandle_mgmt.c.
References nfs2_FhandleCheckSum(), print_buff(), and print_fhandle2().
unsigned long nfs3_FhandleCheckSum (file_handle_v3_t * pfh)
nfs3_FhandleCheckSum
Computes the checksum associated with a nfsv3 file handle.
Parameters:
pfh [IN] pointer to the file handle whose checksum is to be computed.
Returns: the computed checksum.
Definition at line 692 of file nfs_filehandle_mgmt.c.
Referenced by nfs3_FhandleToFSAL(), and nfs3_FSALToFhandle().
short nfs3_FhandleToExportId (nfs_fh3 * pfh3)
nfs3_FhandleToExportId
This routine extracts the export id from the file handle NFSv3
Parameters:
pfh3 [IN] file handle to manage.
Returns: the export id.
Definition at line 515 of file nfs_filehandle_mgmt.c.
References print_buff().
int nfs3_FhandleToFSAL (nfs_fh3 * pfh3, fsal_handle_t * pfsalhandle, fsal_op_context_t * pcontext)
nfs3_FhandleToFSAL: converts a nfs3 file handle to a FSAL file handle.
Converts a nfs3 file handle to a FSAL file handle.
Parameters:
pfh3 [IN] pointer to the file handle to be converted
pfsalhandle [OUT] pointer to the extracted FSAL handle
Returns: 1 if successful, 0 otherwise
Definition at line 244 of file nfs_filehandle_mgmt.c.
References nfs3_FhandleCheckSum(), print_buff(), and print_fhandle3().
int nfs3_FSALToFhandle (nfs_fh3 * pfh3, fsal_handle_t * pfsalhandle, exportlist_t * pexport)
nfs3_FSALToFhandle: converts a FSAL file handle to a nfs3 file handle.
Converts a nfs3 file handle to a FSAL file handle.
Parameters:
pfh3 [OUT] pointer to the extracted file handle
pfsalhandle [IN] pointer to the FSAL handle to be converted
pexport [IN] pointer to the export list entry the FH belongs to
Returns: 1 if successful, 0 otherwise
Definition at line 389 of file nfs_filehandle_mgmt.c.
References nfs3_FhandleCheckSum(), print_buff(), and print_fhandle3().
unsigned long nfs4_FhandleCheckSum (file_handle_v4_t * pfh)
nfs4_FhandleCheckSum
Computes the checksum associated with a nfsv4 file handle.
Parameters:
pfh [IN] pointer to the file handle whose checksum is to be computed.
Returns: the computed checksum.
Definition at line 712 of file nfs_filehandle_mgmt.c.
Referenced by nfs4_FhandleToFSAL(), and nfs4_FSALToFhandle().
short nfs4_FhandleToExportId (nfs_fh4 * pfh4)
nfs4_FhandleToExportId
This routine extracts the export id from the file handle NFSv4
Parameters:
pfh4 [IN] file handle to manage.
Returns: the export id.
Definition at line 491 of file nfs_filehandle_mgmt.c.
int nfs4_FhandleToFSAL (nfs_fh4 * pfh4, fsal_handle_t * pfsalhandle, fsal_op_context_t * pcontext)
nfs4_FhandleToFSAL: converts a nfs4 file handle to a FSAL file handle.
Converts a nfs4 file handle to a FSAL file handle.
Parameters:
pfh4 [IN] pointer to the file handle to be converted
pfsalhandle [OUT] pointer to the extracted FSAL handle
Returns: 1 if successful, 0 otherwise
Definition at line 194 of file nfs_filehandle_mgmt.c.
References nfs4_FhandleCheckSum(), print_buff(), and print_fhandle4().
int nfs4_FSALToFhandle (nfs_fh4 * pfh4, fsal_handle_t * pfsalhandle, compound_data_t * data)
nfs4_FSALToFhandle: converts a FSAL file handle to a nfs4 file handle.
Converts a nfs4 file handle to a FSAL file handle.
Parameters:
pfh4 [OUT] pointer to the extracted file handle
pfsalhandle [IN] pointer to the FSAL handle to be converted
data [IN] pointer to NFSv4 compound data structure.
Returns: 1 if successful, 0 otherwise
Definition at line 327 of file nfs_filehandle_mgmt.c.
References nfs4_FhandleCheckSum(), and nfs_param.
int nfs4_Is_Fh_Empty (nfs_fh4 * pfh)
nfs4_Is_Fh_Empty
This routine is used to test if a fh is empty (contains no data).
Parameters:
pfh [IN] file handle to test.
Returns: NFS4_OK if successfull, NFS4ERR_NOFILEHANDLE is fh is empty.
Definition at line 566 of file nfs_filehandle_mgmt.c.
int nfs4_Is_Fh_Expired (nfs_fh4 * pfh)
nfs4_Is_Fh_Expired
This routine is used to test if a fh is expired
Parameters:
pfh [IN] file handle to test.
Returns: NFS4_OK if successfull. All the FH are persistent for now.
Definition at line 613 of file nfs_filehandle_mgmt.c.
References nfs_param.
int nfs4_Is_Fh_Invalid (nfs_fh4 * pfh)
nfs4_Is_Fh_Invalid
This routine is used to test if a fh is invalid.
Parameters:
pfh [IN] file handle to test.
Returns: NFS4_OK if successfull.
Definition at line 646 of file nfs_filehandle_mgmt.c.
int nfs4_Is_Fh_Pseudo (nfs_fh4 * pfh)
nfs4_Is_Fh_Pseudo
This routine is used to test if a fh refers to pseudo fs
Parameters:
pfh [IN] file handle to test.
Returns: TRUE if in pseudo fh, FALSE otherwise
Definition at line 589 of file nfs_filehandle_mgmt.c.
void nfs4_sprint_fhandle (nfs_fh4 * fh4p, char * outstr)
nfs4_sprint_fhandle : converts a file handle v4 to a string.
Converts a file handle v4 to a string. This will be used mostly for debugging purpose.
Parameters:
fh4p [OUT] pointer to the file handle to be converted to a string.
data [INOUT] pointer to the char * resulting from the operation.
Returns: nothing (void function).
Definition at line 885 of file nfs_filehandle_mgmt.c.
void print_buff (char * buff, int len)
print_buff
This routine prints the content of a buffer.
Parameters:
buff [IN] buffer to print.
len [IN] length of the buffer.
Returns: nothing (void function).
Definition at line 826 of file nfs_filehandle_mgmt.c.
Referenced by nfs2_FhandleToFSAL(), nfs2_FSALToFhandle(), nfs3_FhandleToExportId(), nfs3_FhandleToFSAL(), nfs3_FSALToFhandle(), and nfs4_FhandleToFSAL().
void print_compound_fh (compound_data_t * data)
print_compound_fh
This routine prints all the file handle within a compoud request's data structure.
Parameters:
data [IN] compound's data to manage.
Returns: nothing (void function).
Definition at line 856 of file nfs_filehandle_mgmt.c.
References print_fhandle4().
void print_fhandle2 (fhandle2 fh)
print_fhandle2
This routine prints a NFSv2 file handle (for debugging purpose)
Parameters:
fh [IN] file handle to print.
Returns: nothing (void function).
Definition at line 733 of file nfs_filehandle_mgmt.c.
Referenced by nfs2_FhandleToFSAL(), and nfs2_FSALToFhandle().
void print_fhandle3 (nfs_fh3 fh)
print_fhandle3
This routine prints a NFSv3 file handle (for debugging purpose)
Parameters:
fh [IN] file handle to print.
Returns: nothing (void function).
Definition at line 763 of file nfs_filehandle_mgmt.c.
Referenced by nfs3_FhandleToFSAL(), and nfs3_FSALToFhandle().
void print_fhandle4 (nfs_fh4 fh)
print_fhandle4
This routine prints a NFSv4 file handle (for debugging purpose)
Parameters:
fh [IN] file handle to print.
Returns: nothing (void function).
Definition at line 794 of file nfs_filehandle_mgmt.c.
Referenced by nfs4_FhandleToFSAL(), and print_compound_fh().
void sprint_buff (char * str, char * buff, int len)
Definition at line 836 of file nfs_filehandle_mgmt.c.
void sprint_fhandle2 (char * str, fhandle2 fh)
Definition at line 743 of file nfs_filehandle_mgmt.c.
void sprint_fhandle3 (char * str, nfs_fh3 fh)
Definition at line 773 of file nfs_filehandle_mgmt.c.
void sprint_fhandle4 (char * str, nfs_fh4 fh)
Definition at line 804 of file nfs_filehandle_mgmt.c.
Variable Documentation
nfs_parameter_t nfs_param
Definition at line 146 of file test_clientid.c.
time_t ServerBootTime