nfs_mnt_list.c File Reference
routines for managing the mount list.
#include <stdio.h>
#include <sys/types.h>
#include <ctype.h>
#include <stdlib.h>
#include <dirent.h>
#include <netdb.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <string.h>
#include <pthread.h>
#include <fcntl.h>
#include <sys/file.h>
#include <pwd.h>
#include <grp.h>
#include <rpc/types.h>
#include <rpc/rpc.h>
#include <rpc/auth.h>
#include <rpc/pmap_clnt.h>
#include `log_functions.h`
#include `stuff_alloc.h`
#include `nfs_core.h`
#include `nfs23.h`
#include `nfs4.h`
#include `fsal.h`
#include `nfs_tools.h`
#include `nfs_exports.h`
#include `nfs_file_handle.h`
Functions
int nfs_Add_MountList_Entry (char *hostname, char *dirpath)
int nfs_Remove_MountList_Entry (char *hostname, char *dirpath)
int nfs_Purge_MountList (void)
int nfs_Init_MountList (void)
mountlist nfs_Get_MountList (void)
void nfs_Print_MountList (void)
Variables
mountlist MNT_List_head = NULL
mountlist MNT_List_tail = NULL
Detailed Description
routines for managing the mount list.
Author:
Author deniel
Date:
Date 2005/11/28 17:03:03
Version:
Revision 1.7
nfs_mnt_list.c(p.) : routines for managing the mount list.
Header /cea/home/cvs/cvs/SHERPA/BaseCvs/GANESHA/src/support/nfs_mnt_list.c,v 1.7 2005/11/28 17:03:03 deniel Exp
Log nfs_mnt_list.c(p.),v
Revision 1.7 2005/11/28 17:03:03 deniel Added CeCILL headers
Revision 1.6 2005/11/24 13:44:29 deniel ajout du remove dans ipname track list in nfs_mnt_listc.
Revision 1.5 2005/10/07 09:33:22 leibovic Correcting bug in nfs_Add_MountList_Entry function (pnew_mnt_list_entry->ml_next not initialized).
Revision 1.4 2005/10/05 14:03:31 deniel DEBUG ifdef are now much cleaner
Revision 1.3 2005/08/11 12:37:28 deniel Added statistics management
Revision 1.2 2005/08/03 13:13:59 deniel memset to zero before building the filehandles
Revision 1.1 2005/08/03 06:57:54 deniel Added a libsupport for miscellaneous service functions
Revision 1.1 2005/07/20 11:49:47 deniel Mount protocol V1/V3 support almost complete
Definition in file nfs_mnt_list.c.
Function Documentation
int nfs_Add_MountList_Entry (char * hostname, char * dirpath)
nfs_Add_MountList_Entry: Adds a client to the mount list.
Adds a client to the mount list.
Parameters:
hostname [IN] the hostname for the client
dirpath [IN] the mounted path
Returns: 1 if successful, 0 otherwise
Definition at line 173 of file nfs_mnt_list.c.
References MNT_List_head, MNT_List_tail, and nfs_Print_MountList().
mountlist nfs_Get_MountList (void)
nfs_Get_MountList: Returns the mount list.
Returns the mount list.
Parameters:
none (take no argument)
Returns: the mount list (NULL if mount list is empty)
Definition at line 433 of file nfs_mnt_list.c.
References nfs_Print_MountList().
int nfs_Init_MountList (void)
nfs_Init_MountList: Initializes the mount list.
Initializes the mount list.
Parameters:
none (take no argument)
Returns: 1 if successful, 0 otherwise
Definition at line 409 of file nfs_mnt_list.c.
References MNT_List_head, MNT_List_tail, and nfs_Print_MountList().
void nfs_Print_MountList (void)
nfs_Print_MountList: Prints the mount list (for debugging purpose).
Prints the mount list (for debugging purpose).
Parameters:
none (take no argument)
Returns: nothing (void function)
Definition at line 453 of file nfs_mnt_list.c.
References MNT_List_head.
Referenced by nfs_Add_MountList_Entry(), nfs_Get_MountList(), nfs_Init_MountList(), nfs_Purge_MountList(), and nfs_Remove_MountList_Entry().
int nfs_Purge_MountList (void)
nfs_Purge_MountList: Purges the whole mount list.
Purges the whole mount list.
Parameters:
none (take no argument)
Returns: 1 if successful, 0 otherwise
Definition at line 367 of file nfs_mnt_list.c.
References MNT_List_head, MNT_List_tail, and nfs_Print_MountList().
int nfs_Remove_MountList_Entry (char * hostname, char * dirpath)
nfs_Remove_MountList_Entry: Removes a client to the mount list.
Removes a client to the mount list.
Parameters:
hostname [IN] the hostname for the client
path [IN] the mounted path
Returns: 1 if successful, 0 otherwise
Definition at line 286 of file nfs_mnt_list.c.
References MNT_List_head, MNT_List_tail, and nfs_Print_MountList().
Variable Documentation
mountlist MNT_List_head = NULL
Definition at line 158 of file nfs_mnt_list.c.
Referenced by nfs_Add_MountList_Entry(), nfs_Init_MountList(), nfs_Print_MountList(), nfs_Purge_MountList(), and nfs_Remove_MountList_Entry().
mountlist MNT_List_tail = NULL
Definition at line 159 of file nfs_mnt_list.c.
Referenced by nfs_Add_MountList_Entry(), nfs_Init_MountList(), nfs_Purge_MountList(), and nfs_Remove_MountList_Entry().