test_clientid_full.c File Reference
#include <stdio.h>
#include <string.h>
#include <pthread.h>
#include <fcntl.h>
#include <sys/file.h>
#include <sys/resource.h>
#include <signal.h>
#include <gssapi/gssapi.h>
#include <rpc/types.h>
#include <rpc/rpc.h>
#include <rpc/auth.h>
#include <rpc/pmap_clnt.h>
#include `log_functions.h`
#include `stuff_alloc.h`
#include `fsal.h`
#include `nfs23.h`
#include `nfs4.h`
#include `mount.h`
#include `nfs_core.h`
#include `cache_inode.h`
#include `cache_content.h`
#include `nfs_file_handle.h`
#include `nfs_exports.h`
#include `nfs_tools.h`
#include `nfs_proto_functions.h`
#include `nfs_dupreq.h`
#include `config_parsing.h`
#include `SemN.h`
Functions
int nfs_client_id_compute (char *name, clientid4 *pclientid)
main (int argc, char *argv[])
Function Documentation
main (int argc, char * argv[])
Definition at line 144 of file test_clientid_full.c.
References nfs_client_id_compute().
int nfs_client_id_compute (char * name, clientid4 * pclientid)
Definition at line 46 of file test_clientid_full.c.
References strnlen().
Referenced by client_id_rbt_hash_func_reverse(), and main().