/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef _SOLARIS
#include "solaris_port.h"
#endif

#include "ganesha_rpc.h"
#include "nfs23.h"

bool xdr_nfspath2(xdrs, objp)
register XDR *xdrs;
nfspath2 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_string(xdrs, objp, NFS2_MAXPATHLEN))
    return (false);
  return (true);
}

bool xdr_filename2(xdrs, objp)
register XDR *xdrs;
filename2 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_string(xdrs, objp, NFS2_MAXNAMLEN))
    return (false);
  return (true);
}

bool xdr_fhandle2(xdrs, objp)
register XDR *xdrs;
fhandle2 objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_opaque(xdrs, objp, NFS2_FHSIZE))
    return (false);
  return (true);
}

bool xdr_nfsdata2(xdrs, objp)
register XDR *xdrs;
nfsdata2 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_bytes
     (xdrs, (char **)&objp->nfsdata2_val, (u_int *) & objp->nfsdata2_len, NFS2_MAXDATA))
    return (false);
  return (true);
}

bool xdr_nfscookie2(xdrs, objp)
register XDR *xdrs;
nfscookie2 objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_opaque(xdrs, objp, NFS2_COOKIESIZE))
    return (false);
  return (true);
}

bool xdr_nfsstat2(xdrs, objp)
register XDR *xdrs;
nfsstat2 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_enum(xdrs, (enum_t *) objp))
    return (false);
  return (true);
}

bool xdr_ftype2(xdrs, objp)
register XDR *xdrs;
ftype2 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_enum(xdrs, (enum_t *) objp))
    return (false);
  return (true);
}

bool xdr_nfstime2(xdrs, objp)
register XDR *xdrs;
nfstime2 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_u_int(xdrs, &objp->seconds))
    return (false);
  if(!xdr_u_int(xdrs, &objp->useconds))
    return (false);
  return (true);
}

bool xdr_fattr2(xdrs, objp)
XDR *xdrs;
fattr2 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(xdrs->x_op == XDR_ENCODE)
    {
      if(!xdr_ftype2(xdrs, &objp->type))
        return (false);
#if defined(_LP64) || defined(_KERNEL)
      buf = (int *)XDR_INLINE(xdrs, (10 * BYTES_PER_XDR_UNIT));
#else
      buf = (long *)XDR_INLINE(xdrs, (10 * BYTES_PER_XDR_UNIT));
#endif
      if(buf == NULL)
        {
          if(!xdr_u_int(xdrs, &objp->mode))
            return (false);
          if(!xdr_u_int(xdrs, &objp->nlink))
            return (false);
          if(!xdr_u_int(xdrs, &objp->uid))
            return (false);
          if(!xdr_u_int(xdrs, &objp->gid))
            return (false);
          if(!xdr_u_int(xdrs, &objp->size))
            return (false);
          if(!xdr_u_int(xdrs, &objp->blocksize))
            return (false);
          if(!xdr_u_int(xdrs, &objp->rdev))
            return (false);
          if(!xdr_u_int(xdrs, &objp->blocks))
            return (false);
          if(!xdr_u_int(xdrs, &objp->fsid))
            return (false);
          if(!xdr_u_int(xdrs, &objp->fileid))
            return (false);

        }
      else
        {
#if defined(_LP64) || defined(_KERNEL)
          IXDR_PUT_U_INT32(buf, objp->mode);
          IXDR_PUT_U_INT32(buf, objp->nlink);
          IXDR_PUT_U_INT32(buf, objp->uid);
          IXDR_PUT_U_INT32(buf, objp->gid);
          IXDR_PUT_U_INT32(buf, objp->size);
          IXDR_PUT_U_INT32(buf, objp->blocksize);
          IXDR_PUT_U_INT32(buf, objp->rdev);
          IXDR_PUT_U_INT32(buf, objp->blocks);
          IXDR_PUT_U_INT32(buf, objp->fsid);
          IXDR_PUT_U_INT32(buf, objp->fileid);
#else
          IXDR_PUT_U_LONG(buf, objp->mode);
          IXDR_PUT_U_LONG(buf, objp->nlink);
          IXDR_PUT_U_LONG(buf, objp->uid);
          IXDR_PUT_U_LONG(buf, objp->gid);
          IXDR_PUT_U_LONG(buf, objp->size);
          IXDR_PUT_U_LONG(buf, objp->blocksize);
          IXDR_PUT_U_LONG(buf, objp->rdev);
          IXDR_PUT_U_LONG(buf, objp->blocks);
          IXDR_PUT_U_LONG(buf, objp->fsid);
          IXDR_PUT_U_LONG(buf, objp->fileid);
#endif
        }
      if(!xdr_nfstime2(xdrs, &objp->atime))
        return (false);
      if(!xdr_nfstime2(xdrs, &objp->mtime))
        return (false);
      if(!xdr_nfstime2(xdrs, &objp->ctime))
        return (false);
      return (true);
    }
  else if(xdrs->x_op == XDR_DECODE)
    {
      if(!xdr_ftype2(xdrs, &objp->type))
        return (false);
#if defined(_LP64) || defined(_KERNEL)
      buf = (int *)XDR_INLINE(xdrs, 10 * BYTES_PER_XDR_UNIT);
#else
      buf = (long *)XDR_INLINE(xdrs, 10 * BYTES_PER_XDR_UNIT);
#endif

      if(buf == NULL)
        {
          if(!xdr_u_int(xdrs, &objp->mode))
            return (false);
          if(!xdr_u_int(xdrs, &objp->nlink))
            return (false);
          if(!xdr_u_int(xdrs, &objp->uid))
            return (false);
          if(!xdr_u_int(xdrs, &objp->gid))
            return (false);
          if(!xdr_u_int(xdrs, &objp->size))
            return (false);
          if(!xdr_u_int(xdrs, &objp->blocksize))
            return (false);
          if(!xdr_u_int(xdrs, &objp->rdev))
            return (false);
          if(!xdr_u_int(xdrs, &objp->blocks))
            return (false);
          if(!xdr_u_int(xdrs, &objp->fsid))
            return (false);
          if(!xdr_u_int(xdrs, &objp->fileid))
            return (false);

        }
      else
        {
#if defined(_LP64) || defined(_KERNEL)
          objp->mode = IXDR_GET_U_INT32(buf);
          objp->nlink = IXDR_GET_U_INT32(buf);
          objp->uid = IXDR_GET_U_INT32(buf);
          objp->gid = IXDR_GET_U_INT32(buf);
          objp->size = IXDR_GET_U_INT32(buf);
          objp->blocksize = IXDR_GET_U_INT32(buf);
          objp->rdev = IXDR_GET_U_INT32(buf);
          objp->blocks = IXDR_GET_U_INT32(buf);
          objp->fsid = IXDR_GET_U_INT32(buf);
          objp->fileid = IXDR_GET_U_INT32(buf);
#else
          objp->mode = IXDR_GET_U_LONG(buf);
          objp->nlink = IXDR_GET_U_LONG(buf);
          objp->uid = IXDR_GET_U_LONG(buf);
          objp->gid = IXDR_GET_U_LONG(buf);
          objp->size = IXDR_GET_U_LONG(buf);
          objp->blocksize = IXDR_GET_U_LONG(buf);
          objp->rdev = IXDR_GET_U_LONG(buf);
          objp->blocks = IXDR_GET_U_LONG(buf);
          objp->fsid = IXDR_GET_U_LONG(buf);
          objp->fileid = IXDR_GET_U_LONG(buf);
#endif
        }
      if(!xdr_nfstime2(xdrs, &objp->atime))
        return (false);
      if(!xdr_nfstime2(xdrs, &objp->mtime))
        return (false);
      if(!xdr_nfstime2(xdrs, &objp->ctime))
        return (false);
      return (true);
    }

  if(!xdr_ftype2(xdrs, &objp->type))
    return (false);
  if(!xdr_u_int(xdrs, &objp->mode))
    return (false);
  if(!xdr_u_int(xdrs, &objp->nlink))
    return (false);
  if(!xdr_u_int(xdrs, &objp->uid))
    return (false);
  if(!xdr_u_int(xdrs, &objp->gid))
    return (false);
  if(!xdr_u_int(xdrs, &objp->size))
    return (false);
  if(!xdr_u_int(xdrs, &objp->blocksize))
    return (false);
  if(!xdr_u_int(xdrs, &objp->rdev))
    return (false);
  if(!xdr_u_int(xdrs, &objp->blocks))
    return (false);
  if(!xdr_u_int(xdrs, &objp->fsid))
    return (false);
  if(!xdr_u_int(xdrs, &objp->fileid))
    return (false);
  if(!xdr_nfstime2(xdrs, &objp->atime))
    return (false);
  if(!xdr_nfstime2(xdrs, &objp->mtime))
    return (false);
  if(!xdr_nfstime2(xdrs, &objp->ctime))
    return (false);
  return (true);
}

bool xdr_fhstatus2(xdrs, objp)
register XDR *xdrs;
fhstatus2 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_u_int(xdrs, &objp->status))
    return (false);
  switch (objp->status)
    {
    case 0:
      if(!xdr_fhandle2(xdrs, objp->fhstatus2_u.directory))
        return (false);
      break;
    }
  return (true);
}

bool xdr_diropargs2(xdrs, objp)
register XDR *xdrs;
diropargs2 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_fhandle2(xdrs, objp->dir))
    return (false);
  if(!xdr_filename2(xdrs, &objp->name))
    return (false);
  return (true);
}

bool xdr_DIROP2resok(xdrs, objp)
register XDR *xdrs;
DIROP2resok *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_fhandle2(xdrs, objp->file))
    return (false);
  if(!xdr_fattr2(xdrs, &objp->attributes))
    return (false);
  return (true);
}

bool xdr_DIROP2res(xdrs, objp)
register XDR *xdrs;
DIROP2res *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfsstat2(xdrs, &objp->status))
    return (false);
  switch (objp->status)
    {
    case NFS_OK:
      if(!xdr_DIROP2resok(xdrs, &objp->DIROP2res_u.diropok))
        return (false);
      break;
    default:
      return (true);
      break;
    }
  return (true);
}

bool xdr_ATTR2res(xdrs, objp)
register XDR *xdrs;
ATTR2res *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfsstat2(xdrs, &objp->status))
    return (false);
  switch (objp->status)
    {
    case NFS_OK:
      if(!xdr_fattr2(xdrs, &objp->ATTR2res_u.attributes))
        return (false);
      break;
    default:
      return (true);
      break;
    }
  return (true);
}

bool xdr_sattr2(xdrs, objp)
register XDR *xdrs;
sattr2 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_u_int(xdrs, &objp->mode))
    return (false);
  if(!xdr_u_int(xdrs, &objp->uid))
    return (false);
  if(!xdr_u_int(xdrs, &objp->gid))
    return (false);
  if(!xdr_u_int(xdrs, &objp->size))
    return (false);
  if(!xdr_nfstime2(xdrs, &objp->atime))
    return (false);
  if(!xdr_nfstime2(xdrs, &objp->mtime))
    return (false);
  return (true);
}

bool xdr_statinfo2(xdrs, objp)
register XDR *xdrs;
statinfo2 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(xdrs->x_op == XDR_ENCODE)
    {
#if defined(_LP64) || defined(_KERNEL)
      buf = (int *)XDR_INLINE(xdrs, 5 * BYTES_PER_XDR_UNIT);
#else
      buf = (long *)XDR_INLINE(xdrs, 5 * BYTES_PER_XDR_UNIT);
#endif
      if(buf == NULL)
        {
          if(!xdr_u_int(xdrs, &objp->tsize))
            return (false);
          if(!xdr_u_int(xdrs, &objp->bsize))
            return (false);
          if(!xdr_u_int(xdrs, &objp->blocks))
            return (false);
          if(!xdr_u_int(xdrs, &objp->bfree))
            return (false);
          if(!xdr_u_int(xdrs, &objp->bavail))
            return (false);
        }
      else
        {
#if defined(_LP64) || defined(_KERNEL)
          IXDR_PUT_U_INT32(buf, objp->tsize);
          IXDR_PUT_U_INT32(buf, objp->bsize);
          IXDR_PUT_U_INT32(buf, objp->blocks);
          IXDR_PUT_U_INT32(buf, objp->bfree);
          IXDR_PUT_U_INT32(buf, objp->bavail);
#else
          IXDR_PUT_U_LONG(buf, objp->tsize);
          IXDR_PUT_U_LONG(buf, objp->bsize);
          IXDR_PUT_U_LONG(buf, objp->blocks);
          IXDR_PUT_U_LONG(buf, objp->bfree);
          IXDR_PUT_U_LONG(buf, objp->bavail);
#endif
        }
      return (true);
    }
  else if(xdrs->x_op == XDR_DECODE)
    {
#if defined(_LP64) || defined(_KERNEL)
      buf = (int *)XDR_INLINE(xdrs, 5 * BYTES_PER_XDR_UNIT);
#else
      buf = (long *)XDR_INLINE(xdrs, 5 * BYTES_PER_XDR_UNIT);
#endif
      if(buf == NULL)
        {
          if(!xdr_u_int(xdrs, &objp->tsize))
            return (false);
          if(!xdr_u_int(xdrs, &objp->bsize))
            return (false);
          if(!xdr_u_int(xdrs, &objp->blocks))
            return (false);
          if(!xdr_u_int(xdrs, &objp->bfree))
            return (false);
          if(!xdr_u_int(xdrs, &objp->bavail))
            return (false);
        }
      else
        {
#if defined(_LP64) || defined(_KERNEL)
          objp->tsize = IXDR_GET_U_INT32(buf);
          objp->bsize = IXDR_GET_U_INT32(buf);
          objp->blocks = IXDR_GET_U_INT32(buf);
          objp->bfree = IXDR_GET_U_INT32(buf);
          objp->bavail = IXDR_GET_U_INT32(buf);
#else
          objp->tsize = IXDR_GET_U_LONG(buf);
          objp->bsize = IXDR_GET_U_LONG(buf);
          objp->blocks = IXDR_GET_U_LONG(buf);
          objp->bfree = IXDR_GET_U_LONG(buf);
          objp->bavail = IXDR_GET_U_LONG(buf);
#endif
        }
      return (true);
    }

  if(!xdr_u_int(xdrs, &objp->tsize))
    return (false);
  if(!xdr_u_int(xdrs, &objp->bsize))
    return (false);
  if(!xdr_u_int(xdrs, &objp->blocks))
    return (false);
  if(!xdr_u_int(xdrs, &objp->bfree))
    return (false);
  if(!xdr_u_int(xdrs, &objp->bavail))
    return (false);
  return (true);
}

bool xdr_STATFS2res(xdrs, objp)
register XDR *xdrs;
STATFS2res *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfsstat2(xdrs, &objp->status))
    return (false);
  switch (objp->status)
    {
    case NFS_OK:
      if(!xdr_statinfo2(xdrs, &objp->STATFS2res_u.info))
        return (false);
      break;
    default:
      return (true);
      break;
    }
  return (true);
}

bool xdr_READDIR2args(xdrs, objp)
register XDR *xdrs;
READDIR2args *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_fhandle2(xdrs, objp->dir))
    return (false);
  if(!xdr_nfscookie2(xdrs, objp->cookie))
    return (false);
  if(!xdr_u_int(xdrs, &objp->count))
    return (false);
  return (true);
}

bool xdr_entry2(xdrs, objp)
register XDR *xdrs;
entry2 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_u_int(xdrs, &objp->fileid))
    return (false);
  if(!xdr_filename2(xdrs, &objp->name))
    return (false);
  if(!xdr_nfscookie2(xdrs, objp->cookie))
    return (false);
  if(!xdr_pointer
     (xdrs, (char **)&objp->nextentry, sizeof(entry2), (xdrproc_t) xdr_entry2))
    return (false);
  return (true);
}

bool xdr_READDIR2resok(xdrs, objp)
register XDR *xdrs;
READDIR2resok *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_pointer(xdrs, (char **)&objp->entries, sizeof(entry2), (xdrproc_t) xdr_entry2))
    return (false);
  if(!xdr_bool(xdrs, &objp->eof))
    return (false);
  return (true);
}

bool xdr_READDIR2res(xdrs, objp)
register XDR *xdrs;
READDIR2res *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfsstat2(xdrs, &objp->status))
    return (false);
  switch (objp->status)
    {
    case NFS_OK:
      if(!xdr_READDIR2resok(xdrs, &objp->READDIR2res_u.readdirok))
        return (false);
      break;
    default:
      return (true);
      break;
    }
  return (true);
}

bool xdr_SYMLINK2args(xdrs, objp)
register XDR *xdrs;
SYMLINK2args *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_diropargs2(xdrs, &objp->from))
    return (false);
  if(!xdr_nfspath2(xdrs, &objp->to))
    return (false);
  if(!xdr_sattr2(xdrs, &objp->attributes))
    return (false);
  return (true);
}

bool xdr_LINK2args(xdrs, objp)
register XDR *xdrs;
LINK2args *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_fhandle2(xdrs, objp->from))
    return (false);
  if(!xdr_diropargs2(xdrs, &objp->to))
    return (false);
  return (true);
}

bool xdr_RENAME2args(xdrs, objp)
register XDR *xdrs;
RENAME2args *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_diropargs2(xdrs, &objp->from))
    return (false);
  if(!xdr_diropargs2(xdrs, &objp->to))
    return (false);
  return (true);
}

bool xdr_CREATE2args(xdrs, objp)
register XDR *xdrs;
CREATE2args *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_diropargs2(xdrs, &objp->where))
    return (false);
  if(!xdr_sattr2(xdrs, &objp->attributes))
    return (false);
  return (true);
}

bool xdr_WRITE2args(xdrs, objp)
register XDR *xdrs;
WRITE2args *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_fhandle2(xdrs, objp->file))
    return (false);
  if(!xdr_u_int(xdrs, &objp->beginoffset))
    return (false);
  if(!xdr_u_int(xdrs, &objp->offset))
    return (false);
  if(!xdr_u_int(xdrs, &objp->totalcount))
    return (false);
  if(!xdr_nfsdata2(xdrs, &objp->data))
    return (false);
  return (true);
}

bool xdr_READ2resok(xdrs, objp)
register XDR *xdrs;
READ2resok *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_fattr2(xdrs, &objp->attributes))
    return (false);
  if(!xdr_nfsdata2(xdrs, &objp->data))
    return (false);
  return (true);
}

bool xdr_READ2res(xdrs, objp)
register XDR *xdrs;
READ2res *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfsstat2(xdrs, &objp->status))
    return (false);
  switch (objp->status)
    {
    case NFS_OK:
      if(!xdr_READ2resok(xdrs, &objp->READ2res_u.readok))
        return (false);
      break;
    default:
      return (true);
      break;
    }
  return (true);
}

bool xdr_READ2args(xdrs, objp)
register XDR *xdrs;
READ2args *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_fhandle2(xdrs, objp->file))
    return (false);
  if(!xdr_u_int(xdrs, &objp->offset))
    return (false);
  if(!xdr_u_int(xdrs, &objp->count))
    return (false);
  if(!xdr_u_int(xdrs, &objp->totalcount))
    return (false);
  return (true);
}

bool xdr_READLINK2res(xdrs, objp)
register XDR *xdrs;
READLINK2res *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfsstat2(xdrs, &objp->status))
    return (false);
  switch (objp->status)
    {
    case NFS_OK:
      if(!xdr_nfspath2(xdrs, &objp->READLINK2res_u.data))
        return (false);
      break;
    default:
      return (true);
      break;
    }
  return (true);
}

bool xdr_SETATTR2args(xdrs, objp)
register XDR *xdrs;
SETATTR2args *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_fhandle2(xdrs, objp->file))
    return (false);
  if(!xdr_sattr2(xdrs, &objp->attributes))
    return (false);
  return (true);
}

bool xdr_nfs3_uint64(xdrs, objp)
register XDR *xdrs;
nfs3_uint64 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_u_longlong_t(xdrs, (quad_t *) objp))
    return (false);
  return (true);
}

bool xdr_nfs3_int64(xdrs, objp)
register XDR *xdrs;
nfs3_int64 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_longlong_t(xdrs, (quad_t *) objp))
    return (false);
  return (true);
}

bool xdr_nfs3_uint32(xdrs, objp)
register XDR *xdrs;
nfs3_uint32 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_u_int(xdrs, objp))
    return (false);
  return (true);
}

bool xdr_nfs3_int32(xdrs, objp)
register XDR *xdrs;
nfs3_int32 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_int(xdrs, objp))
    return (false);
  return (true);
}

bool xdr_filename3(xdrs, objp)
register XDR *xdrs;
filename3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_string(xdrs, objp, ~0))
    return (false);
  return (true);
}

bool xdr_nfspath3(xdrs, objp)
register XDR *xdrs;
nfspath3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_string(xdrs, objp, ~0))
    return (false);
  return (true);
}

bool xdr_fileid3(xdrs, objp)
register XDR *xdrs;
fileid3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfs3_uint64(xdrs, objp))
    return (false);
  return (true);
}

bool xdr_cookie3(xdrs, objp)
register XDR *xdrs;
cookie3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfs3_uint64(xdrs, objp))
    return (false);
  return (true);
}

bool xdr_cookieverf3(xdrs, objp)
register XDR *xdrs;
cookieverf3 objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_opaque(xdrs, objp, 8))
    return (false);
  return (true);
}

bool xdr_createverf3(xdrs, objp)
register XDR *xdrs;
createverf3 objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_opaque(xdrs, objp, 8))
    return (false);
  return (true);
}

bool xdr_writeverf3(xdrs, objp)
register XDR *xdrs;
writeverf3 objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_opaque(xdrs, objp, 8))
    return (false);
  return (true);
}

bool xdr_uid3(xdrs, objp)
register XDR *xdrs;
uid3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfs3_uint32(xdrs, objp))
    return (false);
  return (true);
}

bool xdr_gid3(xdrs, objp)
register XDR *xdrs;
gid3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfs3_uint32(xdrs, objp))
    return (false);
  return (true);
}

bool xdr_size3(xdrs, objp)
register XDR *xdrs;
size3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfs3_uint64(xdrs, objp))
    return (false);
  return (true);
}

bool xdr_offset3(xdrs, objp)
register XDR *xdrs;
offset3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfs3_uint64(xdrs, objp))
    return (false);
  return (true);
}

bool xdr_mode3(xdrs, objp)
register XDR *xdrs;
mode3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfs3_uint32(xdrs, objp))
    return (false);
  return (true);
}

bool xdr_count3(xdrs, objp)
register XDR *xdrs;
count3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfs3_uint32(xdrs, objp))
    return (false);
  return (true);
}

bool xdr_nfsstat3(xdrs, objp)
register XDR *xdrs;
nfsstat3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_enum(xdrs, (enum_t *) objp))
    return (false);
  return (true);
}

bool xdr_ftype3(xdrs, objp)
register XDR *xdrs;
ftype3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_enum(xdrs, (enum_t *) objp))
    return (false);
  return (true);
}

bool xdr_specdata3(xdrs, objp)
register XDR *xdrs;
specdata3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfs3_uint32(xdrs, &objp->specdata1))
    return (false);
  if(!xdr_nfs3_uint32(xdrs, &objp->specdata2))
    return (false);
  return (true);
}

bool xdr_nfs_fh3(xdrs, objp)
register XDR *xdrs;
nfs_fh3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_bytes(xdrs, (char **)&objp->data.data_val, (u_int *) & objp->data.data_len, 64))
    return (false);
  return (true);
}

bool xdr_nfstime3(xdrs, objp)
register XDR *xdrs;
nfstime3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfs3_uint32(xdrs, &objp->seconds))
    return (false);
  if(!xdr_nfs3_uint32(xdrs, &objp->nseconds))
    return (false);
  return (true);
}

bool xdr_fattr3(xdrs, objp)
register XDR *xdrs;
fattr3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_ftype3(xdrs, &objp->type))
    return (false);
  if(!xdr_mode3(xdrs, &objp->mode))
    return (false);
  if(!xdr_nfs3_uint32(xdrs, &objp->nlink))
    return (false);
  if(!xdr_uid3(xdrs, &objp->uid))
    return (false);
  if(!xdr_gid3(xdrs, &objp->gid))
    return (false);
  if(!xdr_size3(xdrs, &objp->size))
    return (false);
  if(!xdr_size3(xdrs, &objp->used))
    return (false);
  if(!xdr_specdata3(xdrs, &objp->rdev))
    return (false);
  if(!xdr_nfs3_uint64(xdrs, &objp->fsid))
    return (false);
  if(!xdr_fileid3(xdrs, &objp->fileid))
    return (false);
  if(!xdr_nfstime3(xdrs, &objp->atime))
    return (false);
  if(!xdr_nfstime3(xdrs, &objp->mtime))
    return (false);
  if(!xdr_nfstime3(xdrs, &objp->ctime))
    return (false);
  return (true);
}

bool xdr_post_op_attr(xdrs, objp)
register XDR *xdrs;
post_op_attr *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_bool(xdrs, &objp->attributes_follow))
    return (false);
  switch (objp->attributes_follow)
    {
    case TRUE:
      if(!xdr_fattr3(xdrs, &objp->post_op_attr_u.attributes))
        return (false);
      break;
    case FALSE:
      break;
    default:
      return (false);
    }
  return (true);
}

bool xdr_wcc_attr(xdrs, objp)
register XDR *xdrs;
wcc_attr *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_size3(xdrs, &objp->size))
    return (false);
  if(!xdr_nfstime3(xdrs, &objp->mtime))
    return (false);
  if(!xdr_nfstime3(xdrs, &objp->ctime))
    return (false);
  return (true);
}

bool xdr_pre_op_attr(xdrs, objp)
register XDR *xdrs;
pre_op_attr *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_bool(xdrs, &objp->attributes_follow))
    return (false);
  switch (objp->attributes_follow)
    {
    case TRUE:
      if(!xdr_wcc_attr(xdrs, &objp->pre_op_attr_u.attributes))
        return (false);
      break;
    case FALSE:
      break;
    default:
      return (false);
    }
  return (true);
}

bool xdr_wcc_data(xdrs, objp)
register XDR *xdrs;
wcc_data *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_pre_op_attr(xdrs, &objp->before))
    return (false);
  if(!xdr_post_op_attr(xdrs, &objp->after))
    return (false);
  return (true);
}

bool xdr_post_op_fh3(xdrs, objp)
register XDR *xdrs;
post_op_fh3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_bool(xdrs, &objp->handle_follows))
    return (false);
  switch (objp->handle_follows)
    {
    case TRUE:
      if(!xdr_nfs_fh3(xdrs, &objp->post_op_fh3_u.handle))
        return (false);
      break;
    case FALSE:
      break;
    default:
      return (false);
    }
  return (true);
}

bool xdr_time_how(xdrs, objp)
register XDR *xdrs;
time_how *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_enum(xdrs, (enum_t *) objp))
    return (false);
  return (true);
}

bool xdr_set_mode3(xdrs, objp)
register XDR *xdrs;
set_mode3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_bool(xdrs, &objp->set_it))
    return (false);
  switch (objp->set_it)
    {
    case TRUE:
      if(!xdr_mode3(xdrs, &objp->set_mode3_u.mode))
        return (false);
      break;
    }
  return (true);
}

bool xdr_set_uid3(xdrs, objp)
register XDR *xdrs;
set_uid3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_bool(xdrs, &objp->set_it))
    return (false);
  switch (objp->set_it)
    {
    case TRUE:
      if(!xdr_uid3(xdrs, &objp->set_uid3_u.uid))
        return (false);
      break;
    }
  return (true);
}

bool xdr_set_gid3(xdrs, objp)
register XDR *xdrs;
set_gid3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_bool(xdrs, &objp->set_it))
    return (false);
  switch (objp->set_it)
    {
    case TRUE:
      if(!xdr_gid3(xdrs, &objp->set_gid3_u.gid))
        return (false);
      break;
    }
  return (true);
}

bool xdr_set_size3(xdrs, objp)
register XDR *xdrs;
set_size3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_bool(xdrs, &objp->set_it))
    return (false);
  switch (objp->set_it)
    {
    case TRUE:
      if(!xdr_size3(xdrs, &objp->set_size3_u.size))
        return (false);
      break;
    }
  return (true);
}

bool xdr_set_atime(xdrs, objp)
register XDR *xdrs;
set_atime *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_time_how(xdrs, &objp->set_it))
    return (false);
  switch (objp->set_it)
    {
    case SET_TO_CLIENT_TIME:
      if(!xdr_nfstime3(xdrs, &objp->set_atime_u.atime))
        return (false);
      break;
    default:
      return (true);
      break;
    }
  return (true);
}

bool xdr_set_mtime(xdrs, objp)
register XDR *xdrs;
set_mtime *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_time_how(xdrs, &objp->set_it))
    return (false);
  switch (objp->set_it)
    {
    case SET_TO_CLIENT_TIME:
      if(!xdr_nfstime3(xdrs, &objp->set_mtime_u.mtime))
        return (false);
      break;
    default:
      return (true);
      break;
    }
  return (true);
}

bool xdr_sattr3(xdrs, objp)
register XDR *xdrs;
sattr3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_set_mode3(xdrs, &objp->mode))
    return (false);
  if(!xdr_set_uid3(xdrs, &objp->uid))
    return (false);
  if(!xdr_set_gid3(xdrs, &objp->gid))
    return (false);
  if(!xdr_set_size3(xdrs, &objp->size))
    return (false);
  if(!xdr_set_atime(xdrs, &objp->atime))
    return (false);
  if(!xdr_set_mtime(xdrs, &objp->mtime))
    return (false);
  return (true);
}

bool xdr_diropargs3(xdrs, objp)
register XDR *xdrs;
diropargs3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfs_fh3(xdrs, &objp->dir))
    return (false);
  if(!xdr_filename3(xdrs, &objp->name))
    return (false);
  return (true);
}

bool xdr_GETATTR3args(xdrs, objp)
register XDR *xdrs;
GETATTR3args *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfs_fh3(xdrs, &objp->object))
    return (false);
  return (true);
}

bool xdr_GETATTR3resok(xdrs, objp)
register XDR *xdrs;
GETATTR3resok *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_fattr3(xdrs, &objp->obj_attributes))
    return (false);
  return (true);
}

bool xdr_GETATTR3res(xdrs, objp)
register XDR *xdrs;
GETATTR3res *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfsstat3(xdrs, &objp->status))
    return (false);
  switch (objp->status)
    {
    case NFS3_OK:
      if(!xdr_GETATTR3resok(xdrs, &objp->GETATTR3res_u.resok))
        return (false);
      break;
    default:
      return (true);
      break;
    }
  return (true);
}

bool xdr_sattrguard3(xdrs, objp)
register XDR *xdrs;
sattrguard3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_bool(xdrs, &objp->check))
    return (false);
  switch (objp->check)
    {
    case TRUE:
      if(!xdr_nfstime3(xdrs, &objp->sattrguard3_u.obj_ctime))
        return (false);
      break;
    case FALSE:
      break;
    default:
      return (false);
    }
  return (true);
}

bool xdr_SETATTR3args(xdrs, objp)
register XDR *xdrs;
SETATTR3args *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfs_fh3(xdrs, &objp->object))
    return (false);
  if(!xdr_sattr3(xdrs, &objp->new_attributes))
    return (false);
  if(!xdr_sattrguard3(xdrs, &objp->guard))
    return (false);
  return (true);
}

bool xdr_SETATTR3resok(xdrs, objp)
register XDR *xdrs;
SETATTR3resok *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_wcc_data(xdrs, &objp->obj_wcc))
    return (false);
  return (true);
}

bool xdr_SETATTR3resfail(xdrs, objp)
register XDR *xdrs;
SETATTR3resfail *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_wcc_data(xdrs, &objp->obj_wcc))
    return (false);
  return (true);
}

bool xdr_SETATTR3res(xdrs, objp)
register XDR *xdrs;
SETATTR3res *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfsstat3(xdrs, &objp->status))
    return (false);
  switch (objp->status)
    {
    case NFS3_OK:
      if(!xdr_SETATTR3resok(xdrs, &objp->SETATTR3res_u.resok))
        return (false);
      break;
    default:
      if(!xdr_SETATTR3resfail(xdrs, &objp->SETATTR3res_u.resfail))
        return (false);
      break;
    }
  return (true);
}

bool xdr_LOOKUP3args(xdrs, objp)
register XDR *xdrs;
LOOKUP3args *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_diropargs3(xdrs, &objp->what))
    return (false);
  return (true);
}

bool xdr_LOOKUP3resok(xdrs, objp)
register XDR *xdrs;
LOOKUP3resok *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfs_fh3(xdrs, &objp->object))
    return (false);
  if(!xdr_post_op_attr(xdrs, &objp->obj_attributes))
    return (false);
  if(!xdr_post_op_attr(xdrs, &objp->dir_attributes))
    return (false);
  return (true);
}

bool xdr_LOOKUP3resfail(xdrs, objp)
register XDR *xdrs;
LOOKUP3resfail *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_post_op_attr(xdrs, &objp->dir_attributes))
    return (false);
  return (true);
}

bool xdr_LOOKUP3res(xdrs, objp)
register XDR *xdrs;
LOOKUP3res *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfsstat3(xdrs, &objp->status))
    return (false);
  switch (objp->status)
    {
    case NFS3_OK:
      if(!xdr_LOOKUP3resok(xdrs, &objp->LOOKUP3res_u.resok))
        return (false);
      break;
    default:
      if(!xdr_LOOKUP3resfail(xdrs, &objp->LOOKUP3res_u.resfail))
        return (false);
      break;
    }
  return (true);
}

bool xdr_ACCESS3args(xdrs, objp)
register XDR *xdrs;
ACCESS3args *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfs_fh3(xdrs, &objp->object))
    return (false);
  if(!xdr_nfs3_uint32(xdrs, &objp->access))
    return (false);
  return (true);
}

bool xdr_ACCESS3resok(xdrs, objp)
register XDR *xdrs;
ACCESS3resok *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_post_op_attr(xdrs, &objp->obj_attributes))
    return (false);
  if(!xdr_nfs3_uint32(xdrs, &objp->access))
    return (false);
  return (true);
}

bool xdr_ACCESS3resfail(xdrs, objp)
register XDR *xdrs;
ACCESS3resfail *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_post_op_attr(xdrs, &objp->obj_attributes))
    return (false);
  return (true);
}

bool xdr_ACCESS3res(xdrs, objp)
register XDR *xdrs;
ACCESS3res *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfsstat3(xdrs, &objp->status))
    return (false);
  switch (objp->status)
    {
    case NFS3_OK:
      if(!xdr_ACCESS3resok(xdrs, &objp->ACCESS3res_u.resok))
        return (false);
      break;
    default:
      if(!xdr_ACCESS3resfail(xdrs, &objp->ACCESS3res_u.resfail))
        return (false);
      break;
    }
  return (true);
}

bool xdr_READLINK3args(xdrs, objp)
register XDR *xdrs;
READLINK3args *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfs_fh3(xdrs, &objp->symlink))
    return (false);
  return (true);
}

bool xdr_READLINK3resok(xdrs, objp)
register XDR *xdrs;
READLINK3resok *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_post_op_attr(xdrs, &objp->symlink_attributes))
    return (false);
  if(!xdr_nfspath3(xdrs, &objp->data))
    return (false);
  return (true);
}

bool xdr_READLINK3resfail(xdrs, objp)
register XDR *xdrs;
READLINK3resfail *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_post_op_attr(xdrs, &objp->symlink_attributes))
    return (false);
  return (true);
}

bool xdr_READLINK3res(xdrs, objp)
register XDR *xdrs;
READLINK3res *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfsstat3(xdrs, &objp->status))
    return (false);
  switch (objp->status)
    {
    case NFS3_OK:
      if(!xdr_READLINK3resok(xdrs, &objp->READLINK3res_u.resok))
        return (false);
      break;
    default:
      if(!xdr_READLINK3resfail(xdrs, &objp->READLINK3res_u.resfail))
        return (false);
      break;
    }
  return (true);
}

bool xdr_READ3args(xdrs, objp)
register XDR *xdrs;
READ3args *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfs_fh3(xdrs, &objp->file))
    return (false);
  if(!xdr_offset3(xdrs, &objp->offset))
    return (false);
  if(!xdr_count3(xdrs, &objp->count))
    return (false);
  return (true);
}

bool xdr_READ3resok(xdrs, objp)
register XDR *xdrs;
READ3resok *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_post_op_attr(xdrs, &objp->file_attributes))
    return (false);
  if(!xdr_count3(xdrs, &objp->count))
    return (false);
  if(!xdr_bool(xdrs, &objp->eof))
    return (false);
  if(!xdr_bytes(xdrs, (char **)&objp->data.data_val, (u_int *) & objp->data.data_len, ~0))
    return (false);
  return (true);
}

bool xdr_READ3resfail(xdrs, objp)
register XDR *xdrs;
READ3resfail *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_post_op_attr(xdrs, &objp->file_attributes))
    return (false);
  return (true);
}

bool xdr_READ3res(xdrs, objp)
register XDR *xdrs;
READ3res *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfsstat3(xdrs, &objp->status))
    return (false);
  switch (objp->status)
    {
    case NFS3_OK:
      if(!xdr_READ3resok(xdrs, &objp->READ3res_u.resok))
        return (false);
      break;
    default:
      if(!xdr_READ3resfail(xdrs, &objp->READ3res_u.resfail))
        return (false);
      break;
    }
  return (true);
}

bool xdr_stable_how(xdrs, objp)
register XDR *xdrs;
stable_how *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_enum(xdrs, (enum_t *) objp))
    return (false);
  return (true);
}

bool xdr_WRITE3args(xdrs, objp)
register XDR *xdrs;
WRITE3args *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfs_fh3(xdrs, &objp->file))
    return (false);
  if(!xdr_offset3(xdrs, &objp->offset))
    return (false);
  if(!xdr_count3(xdrs, &objp->count))
    return (false);
  if(!xdr_stable_how(xdrs, &objp->stable))
    return (false);
  if(!xdr_bytes(xdrs, (char **)&objp->data.data_val, (u_int *) & objp->data.data_len, ~0))
    return (false);
  return (true);
}

bool xdr_WRITE3resok(xdrs, objp)
register XDR *xdrs;
WRITE3resok *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_wcc_data(xdrs, &objp->file_wcc))
    return (false);
  if(!xdr_count3(xdrs, &objp->count))
    return (false);
  if(!xdr_stable_how(xdrs, &objp->committed))
    return (false);
  if(!xdr_writeverf3(xdrs, objp->verf))
    return (false);
  return (true);
}

bool xdr_WRITE3resfail(xdrs, objp)
register XDR *xdrs;
WRITE3resfail *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_wcc_data(xdrs, &objp->file_wcc))
    return (false);
  return (true);
}

bool xdr_WRITE3res(xdrs, objp)
register XDR *xdrs;
WRITE3res *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfsstat3(xdrs, &objp->status))
    return (false);
  switch (objp->status)
    {
    case NFS3_OK:
      if(!xdr_WRITE3resok(xdrs, &objp->WRITE3res_u.resok))
        return (false);
      break;
    default:
      if(!xdr_WRITE3resfail(xdrs, &objp->WRITE3res_u.resfail))
        return (false);
      break;
    }
  return (true);
}

bool xdr_createmode3(xdrs, objp)
register XDR *xdrs;
createmode3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_enum(xdrs, (enum_t *) objp))
    return (false);
  return (true);
}

bool xdr_createhow3(xdrs, objp)
register XDR *xdrs;
createhow3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_createmode3(xdrs, &objp->mode))
    return (false);
  switch (objp->mode)
    {
    case UNCHECKED:
    case GUARDED:
      if(!xdr_sattr3(xdrs, &objp->createhow3_u.obj_attributes))
        return (false);
      break;
    case EXCLUSIVE:
      if(!xdr_createverf3(xdrs, objp->createhow3_u.verf))
        return (false);
      break;
    default:
      return (false);
    }
  return (true);
}

bool xdr_CREATE3args(xdrs, objp)
register XDR *xdrs;
CREATE3args *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_diropargs3(xdrs, &objp->where))
    return (false);
  if(!xdr_createhow3(xdrs, &objp->how))
    return (false);
  return (true);
}

bool xdr_CREATE3resok(xdrs, objp)
register XDR *xdrs;
CREATE3resok *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_post_op_fh3(xdrs, &objp->obj))
    return (false);
  if(!xdr_post_op_attr(xdrs, &objp->obj_attributes))
    return (false);
  if(!xdr_wcc_data(xdrs, &objp->dir_wcc))
    return (false);
  return (true);
}

bool xdr_CREATE3resfail(xdrs, objp)
register XDR *xdrs;
CREATE3resfail *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_wcc_data(xdrs, &objp->dir_wcc))
    return (false);
  return (true);
}

bool xdr_CREATE3res(xdrs, objp)
register XDR *xdrs;
CREATE3res *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfsstat3(xdrs, &objp->status))
    return (false);
  switch (objp->status)
    {
    case NFS3_OK:
      if(!xdr_CREATE3resok(xdrs, &objp->CREATE3res_u.resok))
        return (false);
      break;
    default:
      if(!xdr_CREATE3resfail(xdrs, &objp->CREATE3res_u.resfail))
        return (false);
      break;
    }
  return (true);
}

bool xdr_MKDIR3args(xdrs, objp)
register XDR *xdrs;
MKDIR3args *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_diropargs3(xdrs, &objp->where))
    return (false);
  if(!xdr_sattr3(xdrs, &objp->attributes))
    return (false);
  return (true);
}

bool xdr_MKDIR3resok(xdrs, objp)
register XDR *xdrs;
MKDIR3resok *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_post_op_fh3(xdrs, &objp->obj))
    return (false);
  if(!xdr_post_op_attr(xdrs, &objp->obj_attributes))
    return (false);
  if(!xdr_wcc_data(xdrs, &objp->dir_wcc))
    return (false);
  return (true);
}

bool xdr_MKDIR3resfail(xdrs, objp)
register XDR *xdrs;
MKDIR3resfail *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_wcc_data(xdrs, &objp->dir_wcc))
    return (false);
  return (true);
}

bool xdr_MKDIR3res(xdrs, objp)
register XDR *xdrs;
MKDIR3res *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfsstat3(xdrs, &objp->status))
    return (false);
  switch (objp->status)
    {
    case NFS3_OK:
      if(!xdr_MKDIR3resok(xdrs, &objp->MKDIR3res_u.resok))
        return (false);
      break;
    default:
      if(!xdr_MKDIR3resfail(xdrs, &objp->MKDIR3res_u.resfail))
        return (false);
      break;
    }
  return (true);
}

bool xdr_symlinkdata3(xdrs, objp)
register XDR *xdrs;
symlinkdata3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_sattr3(xdrs, &objp->symlink_attributes))
    return (false);
  if(!xdr_nfspath3(xdrs, &objp->symlink_data))
    return (false);
  return (true);
}

bool xdr_SYMLINK3args(xdrs, objp)
register XDR *xdrs;
SYMLINK3args *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_diropargs3(xdrs, &objp->where))
    return (false);
  if(!xdr_symlinkdata3(xdrs, &objp->symlink))
    return (false);
  return (true);
}

bool xdr_SYMLINK3resok(xdrs, objp)
register XDR *xdrs;
SYMLINK3resok *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_post_op_fh3(xdrs, &objp->obj))
    return (false);
  if(!xdr_post_op_attr(xdrs, &objp->obj_attributes))
    return (false);
  if(!xdr_wcc_data(xdrs, &objp->dir_wcc))
    return (false);
  return (true);
}

bool xdr_SYMLINK3resfail(xdrs, objp)
register XDR *xdrs;
SYMLINK3resfail *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_wcc_data(xdrs, &objp->dir_wcc))
    return (false);
  return (true);
}

bool xdr_SYMLINK3res(xdrs, objp)
register XDR *xdrs;
SYMLINK3res *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfsstat3(xdrs, &objp->status))
    return (false);
  switch (objp->status)
    {
    case NFS3_OK:
      if(!xdr_SYMLINK3resok(xdrs, &objp->SYMLINK3res_u.resok))
        return (false);
      break;
    default:
      if(!xdr_SYMLINK3resfail(xdrs, &objp->SYMLINK3res_u.resfail))
        return (false);
      break;
    }
  return (true);
}

bool xdr_devicedata3(xdrs, objp)
register XDR *xdrs;
devicedata3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_sattr3(xdrs, &objp->dev_attributes))
    return (false);
  if(!xdr_specdata3(xdrs, &objp->spec))
    return (false);
  return (true);
}

bool xdr_mknoddata3(xdrs, objp)
register XDR *xdrs;
mknoddata3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_ftype3(xdrs, &objp->type))
    return (false);
  switch (objp->type)
    {
    case NF3CHR:
    case NF3BLK:
      if(!xdr_devicedata3(xdrs, &objp->mknoddata3_u.device))
        return (false);
      break;
    case NF3SOCK:
    case NF3FIFO:
      if(!xdr_sattr3(xdrs, &objp->mknoddata3_u.pipe_attributes))
        return (false);
      break;
    default:
      return (true);
      break;
    }
  return (true);
}

bool xdr_MKNOD3args(xdrs, objp)
register XDR *xdrs;
MKNOD3args *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_diropargs3(xdrs, &objp->where))
    return (false);
  if(!xdr_mknoddata3(xdrs, &objp->what))
    return (false);
  return (true);
}

bool xdr_MKNOD3resok(xdrs, objp)
register XDR *xdrs;
MKNOD3resok *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_post_op_fh3(xdrs, &objp->obj))
    return (false);
  if(!xdr_post_op_attr(xdrs, &objp->obj_attributes))
    return (false);
  if(!xdr_wcc_data(xdrs, &objp->dir_wcc))
    return (false);
  return (true);
}

bool xdr_MKNOD3resfail(xdrs, objp)
register XDR *xdrs;
MKNOD3resfail *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_wcc_data(xdrs, &objp->dir_wcc))
    return (false);
  return (true);
}

bool xdr_MKNOD3res(xdrs, objp)
register XDR *xdrs;
MKNOD3res *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfsstat3(xdrs, &objp->status))
    return (false);
  switch (objp->status)
    {
    case NFS3_OK:
      if(!xdr_MKNOD3resok(xdrs, &objp->MKNOD3res_u.resok))
        return (false);
      break;
    default:
      if(!xdr_MKNOD3resfail(xdrs, &objp->MKNOD3res_u.resfail))
        return (false);
      break;
    }
  return (true);
}

bool xdr_REMOVE3args(xdrs, objp)
register XDR *xdrs;
REMOVE3args *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_diropargs3(xdrs, &objp->object))
    return (false);
  return (true);
}

bool xdr_REMOVE3resok(xdrs, objp)
register XDR *xdrs;
REMOVE3resok *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_wcc_data(xdrs, &objp->dir_wcc))
    return (false);
  return (true);
}

bool xdr_REMOVE3resfail(xdrs, objp)
register XDR *xdrs;
REMOVE3resfail *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_wcc_data(xdrs, &objp->dir_wcc))
    return (false);
  return (true);
}

bool xdr_REMOVE3res(xdrs, objp)
register XDR *xdrs;
REMOVE3res *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfsstat3(xdrs, &objp->status))
    return (false);
  switch (objp->status)
    {
    case NFS3_OK:
      if(!xdr_REMOVE3resok(xdrs, &objp->REMOVE3res_u.resok))
        return (false);
      break;
    default:
      if(!xdr_REMOVE3resfail(xdrs, &objp->REMOVE3res_u.resfail))
        return (false);
      break;
    }
  return (true);
}

bool xdr_RMDIR3args(xdrs, objp)
register XDR *xdrs;
RMDIR3args *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_diropargs3(xdrs, &objp->object))
    return (false);
  return (true);
}

bool xdr_RMDIR3resok(xdrs, objp)
register XDR *xdrs;
RMDIR3resok *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_wcc_data(xdrs, &objp->dir_wcc))
    return (false);
  return (true);
}

bool xdr_RMDIR3resfail(xdrs, objp)
register XDR *xdrs;
RMDIR3resfail *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_wcc_data(xdrs, &objp->dir_wcc))
    return (false);
  return (true);
}

bool xdr_RMDIR3res(xdrs, objp)
register XDR *xdrs;
RMDIR3res *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfsstat3(xdrs, &objp->status))
    return (false);
  switch (objp->status)
    {
    case NFS3_OK:
      if(!xdr_RMDIR3resok(xdrs, &objp->RMDIR3res_u.resok))
        return (false);
      break;
    default:
      if(!xdr_RMDIR3resfail(xdrs, &objp->RMDIR3res_u.resfail))
        return (false);
      break;
    }
  return (true);
}

bool xdr_RENAME3args(xdrs, objp)
register XDR *xdrs;
RENAME3args *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_diropargs3(xdrs, &objp->from))
    return (false);
  if(!xdr_diropargs3(xdrs, &objp->to))
    return (false);
  return (true);
}

bool xdr_RENAME3resok(xdrs, objp)
register XDR *xdrs;
RENAME3resok *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_wcc_data(xdrs, &objp->fromdir_wcc))
    return (false);
  if(!xdr_wcc_data(xdrs, &objp->todir_wcc))
    return (false);
  return (true);
}

bool xdr_RENAME3resfail(xdrs, objp)
register XDR *xdrs;
RENAME3resfail *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_wcc_data(xdrs, &objp->fromdir_wcc))
    return (false);
  if(!xdr_wcc_data(xdrs, &objp->todir_wcc))
    return (false);
  return (true);
}

bool xdr_RENAME3res(xdrs, objp)
register XDR *xdrs;
RENAME3res *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfsstat3(xdrs, &objp->status))
    return (false);
  switch (objp->status)
    {
    case NFS3_OK:
      if(!xdr_RENAME3resok(xdrs, &objp->RENAME3res_u.resok))
        return (false);
      break;
    default:
      if(!xdr_RENAME3resfail(xdrs, &objp->RENAME3res_u.resfail))
        return (false);
      break;
    }
  return (true);
}

bool xdr_LINK3args(xdrs, objp)
register XDR *xdrs;
LINK3args *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfs_fh3(xdrs, &objp->file))
    return (false);
  if(!xdr_diropargs3(xdrs, &objp->link))
    return (false);
  return (true);
}

bool xdr_LINK3resok(xdrs, objp)
register XDR *xdrs;
LINK3resok *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_post_op_attr(xdrs, &objp->file_attributes))
    return (false);
  if(!xdr_wcc_data(xdrs, &objp->linkdir_wcc))
    return (false);
  return (true);
}

bool xdr_LINK3resfail(xdrs, objp)
register XDR *xdrs;
LINK3resfail *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_post_op_attr(xdrs, &objp->file_attributes))
    return (false);
  if(!xdr_wcc_data(xdrs, &objp->linkdir_wcc))
    return (false);
  return (true);
}

bool xdr_LINK3res(xdrs, objp)
register XDR *xdrs;
LINK3res *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfsstat3(xdrs, &objp->status))
    return (false);
  switch (objp->status)
    {
    case NFS3_OK:
      if(!xdr_LINK3resok(xdrs, &objp->LINK3res_u.resok))
        return (false);
      break;
    default:
      if(!xdr_LINK3resfail(xdrs, &objp->LINK3res_u.resfail))
        return (false);
      break;
    }
  return (true);
}

bool xdr_READDIR3args(xdrs, objp)
register XDR *xdrs;
READDIR3args *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfs_fh3(xdrs, &objp->dir))
    return (false);
  if(!xdr_cookie3(xdrs, &objp->cookie))
    return (false);
  if(!xdr_cookieverf3(xdrs, objp->cookieverf))
    return (false);
  if(!xdr_count3(xdrs, &objp->count))
    return (false);
  return (true);
}

bool xdr_entry3(xdrs, objp)
register XDR *xdrs;
entry3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_fileid3(xdrs, &objp->fileid))
    return (false);
  if(!xdr_filename3(xdrs, &objp->name))
    return (false);
  if(!xdr_cookie3(xdrs, &objp->cookie))
    return (false);
  if(!xdr_pointer
     (xdrs, (char **)&objp->nextentry, sizeof(entry3), (xdrproc_t) xdr_entry3))
    return (false);
  return (true);
}

bool xdr_dirlist3(xdrs, objp)
register XDR *xdrs;
dirlist3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_pointer(xdrs, (char **)&objp->entries, sizeof(entry3), (xdrproc_t) xdr_entry3))
    return (false);
  if(!xdr_bool(xdrs, &objp->eof))
    return (false);
  return (true);
}

bool xdr_READDIR3resok(xdrs, objp)
register XDR *xdrs;
READDIR3resok *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_post_op_attr(xdrs, &objp->dir_attributes))
    return (false);
  if(!xdr_cookieverf3(xdrs, objp->cookieverf))
    return (false);
  if(!xdr_dirlist3(xdrs, &objp->reply))
    return (false);
  return (true);
}

bool xdr_READDIR3resfail(xdrs, objp)
register XDR *xdrs;
READDIR3resfail *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_post_op_attr(xdrs, &objp->dir_attributes))
    return (false);
  return (true);
}

bool xdr_READDIR3res(xdrs, objp)
register XDR *xdrs;
READDIR3res *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfsstat3(xdrs, &objp->status))
    return (false);
  switch (objp->status)
    {
    case NFS3_OK:
      if(!xdr_READDIR3resok(xdrs, &objp->READDIR3res_u.resok))
        return (false);
      break;
    default:
      if(!xdr_READDIR3resfail(xdrs, &objp->READDIR3res_u.resfail))
        return (false);
      break;
    }
  return (true);
}

bool xdr_READDIRPLUS3args(xdrs, objp)
register XDR *xdrs;
READDIRPLUS3args *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfs_fh3(xdrs, &objp->dir))
    return (false);
  if(!xdr_cookie3(xdrs, &objp->cookie))
    return (false);
  if(!xdr_cookieverf3(xdrs, objp->cookieverf))
    return (false);
  if(!xdr_count3(xdrs, &objp->dircount))
    return (false);
  if(!xdr_count3(xdrs, &objp->maxcount))
    return (false);
  return (true);
}

bool xdr_entryplus3(xdrs, objp)
register XDR *xdrs;
entryplus3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_fileid3(xdrs, &objp->fileid))
    return (false);
  if(!xdr_filename3(xdrs, &objp->name))
    return (false);
  if(!xdr_cookie3(xdrs, &objp->cookie))
    return (false);
  if(!xdr_post_op_attr(xdrs, &objp->name_attributes))
    return (false);
  if(!xdr_post_op_fh3(xdrs, &objp->name_handle))
    return (false);
  if(!xdr_pointer
     (xdrs, (char **)&objp->nextentry, sizeof(entryplus3), (xdrproc_t) xdr_entryplus3))
    return (false);
  return (true);
}

bool xdr_dirlistplus3(xdrs, objp)
register XDR *xdrs;
dirlistplus3 *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_pointer
     (xdrs, (char **)&objp->entries, sizeof(entryplus3), (xdrproc_t) xdr_entryplus3))
    return (false);
  if(!xdr_bool(xdrs, &objp->eof))
    return (false);
  return (true);
}

bool xdr_READDIRPLUS3resok(xdrs, objp)
register XDR *xdrs;
READDIRPLUS3resok *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_post_op_attr(xdrs, &objp->dir_attributes))
    return (false);
  if(!xdr_cookieverf3(xdrs, objp->cookieverf))
    return (false);
  if(!xdr_dirlistplus3(xdrs, &objp->reply))
    return (false);
  return (true);
}

bool xdr_READDIRPLUS3resfail(xdrs, objp)
register XDR *xdrs;
READDIRPLUS3resfail *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_post_op_attr(xdrs, &objp->dir_attributes))
    return (false);
  return (true);
}

bool xdr_READDIRPLUS3res(xdrs, objp)
register XDR *xdrs;
READDIRPLUS3res *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfsstat3(xdrs, &objp->status))
    return (false);
  switch (objp->status)
    {
    case NFS3_OK:
      if(!xdr_READDIRPLUS3resok(xdrs, &objp->READDIRPLUS3res_u.resok))
        return (false);
      break;
    default:
      if(!xdr_READDIRPLUS3resfail(xdrs, &objp->READDIRPLUS3res_u.resfail))
        return (false);
      break;
    }
  return (true);
}

bool xdr_FSSTAT3args(xdrs, objp)
register XDR *xdrs;
FSSTAT3args *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfs_fh3(xdrs, &objp->fsroot))
    return (false);
  return (true);
}

bool xdr_FSSTAT3resok(xdrs, objp)
register XDR *xdrs;
FSSTAT3resok *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_post_op_attr(xdrs, &objp->obj_attributes))
    return (false);
  if(!xdr_size3(xdrs, &objp->tbytes))
    return (false);
  if(!xdr_size3(xdrs, &objp->fbytes))
    return (false);
  if(!xdr_size3(xdrs, &objp->abytes))
    return (false);
  if(!xdr_size3(xdrs, &objp->tfiles))
    return (false);
  if(!xdr_size3(xdrs, &objp->ffiles))
    return (false);
  if(!xdr_size3(xdrs, &objp->afiles))
    return (false);
  if(!xdr_nfs3_uint32(xdrs, &objp->invarsec))
    return (false);
  return (true);
}

bool xdr_FSSTAT3resfail(xdrs, objp)
register XDR *xdrs;
FSSTAT3resfail *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_post_op_attr(xdrs, &objp->obj_attributes))
    return (false);
  return (true);
}

bool xdr_FSSTAT3res(xdrs, objp)
register XDR *xdrs;
FSSTAT3res *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfsstat3(xdrs, &objp->status))
    return (false);
  switch (objp->status)
    {
    case NFS3_OK:
      if(!xdr_FSSTAT3resok(xdrs, &objp->FSSTAT3res_u.resok))
        return (false);
      break;
    default:
      if(!xdr_FSSTAT3resfail(xdrs, &objp->FSSTAT3res_u.resfail))
        return (false);
      break;
    }
  return (true);
}

bool xdr_FSINFO3args(xdrs, objp)
register XDR *xdrs;
FSINFO3args *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfs_fh3(xdrs, &objp->fsroot))
    return (false);
  return (true);
}

bool xdr_FSINFO3resok(xdrs, objp)
register XDR *xdrs;
FSINFO3resok *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_post_op_attr(xdrs, &objp->obj_attributes))
    return (false);
  if(!xdr_nfs3_uint32(xdrs, &objp->rtmax))
    return (false);
  if(!xdr_nfs3_uint32(xdrs, &objp->rtpref))
    return (false);
  if(!xdr_nfs3_uint32(xdrs, &objp->rtmult))
    return (false);
  if(!xdr_nfs3_uint32(xdrs, &objp->wtmax))
    return (false);
  if(!xdr_nfs3_uint32(xdrs, &objp->wtpref))
    return (false);
  if(!xdr_nfs3_uint32(xdrs, &objp->wtmult))
    return (false);
  if(!xdr_nfs3_uint32(xdrs, &objp->dtpref))
    return (false);
  if(!xdr_size3(xdrs, &objp->maxfilesize))
    return (false);
  if(!xdr_nfstime3(xdrs, &objp->time_delta))
    return (false);
  if(!xdr_nfs3_uint32(xdrs, &objp->properties))
    return (false);
  return (true);
}

bool xdr_FSINFO3resfail(xdrs, objp)
register XDR *xdrs;
FSINFO3resfail *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_post_op_attr(xdrs, &objp->obj_attributes))
    return (false);
  return (true);
}

bool xdr_FSINFO3res(xdrs, objp)
register XDR *xdrs;
FSINFO3res *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfsstat3(xdrs, &objp->status))
    return (false);
  switch (objp->status)
    {
    case NFS3_OK:
      if(!xdr_FSINFO3resok(xdrs, &objp->FSINFO3res_u.resok))
        return (false);
      break;
    default:
      if(!xdr_FSINFO3resfail(xdrs, &objp->FSINFO3res_u.resfail))
        return (false);
      break;
    }
  return (true);
}

bool xdr_PATHCONF3args(xdrs, objp)
register XDR *xdrs;
PATHCONF3args *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfs_fh3(xdrs, &objp->object))
    return (false);
  return (true);
}

bool xdr_PATHCONF3resok(xdrs, objp)
register XDR *xdrs;
PATHCONF3resok *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_post_op_attr(xdrs, &objp->obj_attributes))
    return (false);
  if(!xdr_nfs3_uint32(xdrs, &objp->linkmax))
    return (false);
  if(!xdr_nfs3_uint32(xdrs, &objp->name_max))
    return (false);
  if(!xdr_bool(xdrs, &objp->no_trunc))
    return (false);
  if(!xdr_bool(xdrs, &objp->chown_restricted))
    return (false);
  if(!xdr_bool(xdrs, &objp->case_insensitive))
    return (false);
  if(!xdr_bool(xdrs, &objp->case_preserving))
    return (false);
  return (true);
}

bool xdr_PATHCONF3resfail(xdrs, objp)
register XDR *xdrs;
PATHCONF3resfail *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_post_op_attr(xdrs, &objp->obj_attributes))
    return (false);
  return (true);
}

bool xdr_PATHCONF3res(xdrs, objp)
register XDR *xdrs;
PATHCONF3res *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfsstat3(xdrs, &objp->status))
    return (false);
  switch (objp->status)
    {
    case NFS3_OK:
      if(!xdr_PATHCONF3resok(xdrs, &objp->PATHCONF3res_u.resok))
        return (false);
      break;
    default:
      if(!xdr_PATHCONF3resfail(xdrs, &objp->PATHCONF3res_u.resfail))
        return (false);
      break;
    }
  return (true);
}

bool xdr_COMMIT3args(xdrs, objp)
register XDR *xdrs;
COMMIT3args *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfs_fh3(xdrs, &objp->file))
    return (false);
  if(!xdr_offset3(xdrs, &objp->offset))
    return (false);
  if(!xdr_count3(xdrs, &objp->count))
    return (false);
  return (true);
}

bool xdr_COMMIT3resok(xdrs, objp)
register XDR *xdrs;
COMMIT3resok *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_wcc_data(xdrs, &objp->file_wcc))
    return (false);
  if(!xdr_writeverf3(xdrs, objp->verf))
    return (false);
  return (true);
}

bool xdr_COMMIT3resfail(xdrs, objp)
register XDR *xdrs;
COMMIT3resfail *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_wcc_data(xdrs, &objp->file_wcc))
    return (false);
  return (true);
}

bool xdr_COMMIT3res(xdrs, objp)
register XDR *xdrs;
COMMIT3res *objp;
{

#if defined(_LP64) || defined(_KERNEL)
  register int __attribute__ ((__unused__)) * buf;
#else
  register long __attribute__ ((__unused__)) * buf;
#endif

  if(!xdr_nfsstat3(xdrs, &objp->status))
    return (false);
  switch (objp->status)
    {
    case NFS3_OK:
      if(!xdr_COMMIT3resok(xdrs, &objp->COMMIT3res_u.resok))
        return (false);
      break;
    default:
      if(!xdr_COMMIT3resfail(xdrs, &objp->COMMIT3res_u.resfail))
        return (false);
      break;
    }
  return (true);
}
