Auth_none.c File Reference
#include `Types.h`
#include `Xdr.h`
#include `Rpc.h`
#include `Auth.h`
Classes
struct Authnone_private
Defines
#define MAX_MARSHEL_SIZE 20
Functions
AUTH * Authnone_create (void)
Define Documentation
#define MAX_MARSHEL_SIZE 20
Definition at line 73 of file Auth_none.c.
Referenced by Authnone_create().
Function Documentation
AUTH* Authnone_create (void)
Definition at line 102 of file Auth_none.c.
References MAX_MARSHEL_SIZE, Xdr_opaque_auth(), and Xdrmem_create().
Referenced by Clnttcp_create(), and Clntudp_bufcreate().