Auth_unix.c File Reference
#include <stdio.h>
#include `Auth.h`
#include `Auth_unix.h`
Classes
struct Audata
Defines
#define AUTH_PRIVATE(auth) ((struct Audata *)auth $\rightarrow$ ah_private)
Functions
AUTH * Authunix_create (char *machname, uid_t uid, gid_t gid, int len, gid_t *aup_gids)
AUTH * Authunix_create_default ()
Define Documentation
#define AUTH_PRIVATE(auth) ((struct Audata *)auth $\rightarrow$ ah_private)
Definition at line 108 of file Auth_unix.c.
Function Documentation
AUTH* Authunix_create (char * machname, uid_t uid, gid_t gid, int len, gid_t * aup_gids)
Definition at line 117 of file Auth_unix.c.
References Audata::au_origcred, Audata::au_shcred, Audata::au_shfaults, Xdr_Authunix_parms(), and Xdrmem_create().
Referenced by Authunix_create_default().
AUTH* Authunix_create_default ()
Definition at line 201 of file Auth_unix.c.
References Authunix_create().
Referenced by Clnt_broadcast().