Authuxprot.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include `Types.h`
#include `Xdr.h`
#include `Rpc.h`
#include `Auth.h`
#include `Auth_unix.h`
#include `Clnt.h`
#include <netinet/in.h>
Functions
bool_t Xdr_Authunix_parms (register XDR *xdrs, register struct Authunix_parms *p)
Function Documentation
bool_t Xdr_Authunix_parms (register XDR * xdrs, register struct Authunix_parms * p)
Definition at line 83 of file Authuxprot.c.
References Xdr_array(), Xdr_string(), Xdr_u_int(), Xdr_u_long(), and Xdr_u_short().
Referenced by Authunix_create(), and Svcauth_unix().