Clnt_tcp.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include `Rpc.h`
#include <sys/param.h>
#include <sys/socket.h>
#include <netdb.h>
#include <errno.h>
#include `Types.h`
#include `stuff_alloc.h`
#include `Auth.h`
#include `Auth_none.h`
Classes
struct Ct_data
Defines
#define NFDBITS (sizeof(long) * 8)
#define MCALL_MSG_SIZE 24
Functions
Client * Clnttcp_create (struct sockaddr_in *raddr, u_long prog, u_long vers, register int *sockp, u_int sendsz, u_int recvsz)
Define Documentation
#define MCALL_MSG_SIZE 24
Definition at line 69 of file Clnt_tcp.c.
#define NFDBITS (sizeof(long) * 8)
Definition at line 66 of file Clnt_tcp.c.
Function Documentation
Client* Clnttcp_create (struct sockaddr_in * raddr, u_long prog, u_long vers, register int * sockp, u_int sendsz, u_int recvsz)
Definition at line 116 of file Clnt_tcp.c.
References Authnone_create(), Ct_data::ct_addr, Ct_data::ct_closeit, Ct_data::ct_mpos, Ct_data::ct_sock, Ct_data::ct_wait, Ct_data::ct_waitset, MCALL_MSG_SIZE, Xdr_callhdr(), Xdrmem_create(), and Xdrrec_create().
Referenced by Clnt_create(), Creer_RPCClient(), and Pmap_getport().