Clnt_udp.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/param.h>
#include <sys/socket.h>
#include <sys/ioctl.h>
#include <netdb.h>
#include <errno.h>
#include `Rpc.h`
#include `Clnt.h`
#include `Types.h`
#include `stuff_alloc.h`
#include `Auth.h`
#include `Auth_none.h`
Classes
struct Cu_data
Defines
#define NFDBITS (sizeof(long) * 8)
Functions
Client * Clntudp_bufcreate (struct sockaddr_in *raddr, u_long program, u_long version, struct timeval wait, register int *sockp, u_int sendsz, u_int recvsz)
Client * Clntudp_create (struct sockaddr_in *raddr, u_long program, u_long version, struct timeval wait, register int *sockp)
Define Documentation
#define NFDBITS (sizeof(long) * 8)
Definition at line 55 of file Clnt_udp.c.
Function Documentation
Client* Clntudp_bufcreate (struct sockaddr_in * raddr, u_long program, u_long version, struct timeval wait, register int * sockp, u_int sendsz, u_int recvsz)
Definition at line 112 of file Clnt_udp.c.
References Authnone_create(), Cu_data::cu_closeit, Cu_data::cu_inbuf, Cu_data::cu_outbuf, Cu_data::cu_raddr, Cu_data::cu_recvsz, Cu_data::cu_rlen, Cu_data::cu_sendsz, Cu_data::cu_sock, Cu_data::cu_total, Cu_data::cu_wait, Cu_data::cu_xdrpos, Xdr_callhdr(), and Xdrmem_create().
Referenced by Clntudp_create(), Pmap_getport(), Pmap_set(), and Pmap_unset().
Client* Clntudp_create (struct sockaddr_in * raddr, u_long program, u_long version, struct timeval wait, register int * sockp)
Definition at line 211 of file Clnt_udp.c.
References Clntudp_bufcreate(), and UDPMSGSIZE.
Referenced by Clnt_create(), and Pmap_rmtcall().