onc_rpc_server.c File Reference
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <sys/errno.h>
#include <sys/param.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include `Rpc.h`
#include `Pmap_clnt.h`
#include `gssapi/gssapi.h`
Defines
#define LOGFILE_DEFAUT `./toto-server.log`
#define TraduireAdresse(adresse, dest)
#define TIMEOUT_SEC 25
#define DEFAULT_RPC_SERVICE 300400
#define RECV_SIZE 2048
#define SEND_SIZE 2048
#define V1 1
#define PROC_NULL 0
#define PROC_PLUS1 1
Functions
void dispatch (struct Svc_req *ptr_req, SVCXPRT *ptr_svc)
main (int argc, char *argv[])
Variables
char options [] = `hL:N:s:`
char utilisation []
unsigned int rpc_service_num = DEFAULT_RPC_SERVICE
Define Documentation
#define DEFAULT_RPC_SERVICE 300400
Definition at line 39 of file onc_rpc_server.c.
#define LOGFILE_DEFAUT `./toto-server.log`
Definition at line 31 of file onc_rpc_server.c.
Referenced by main().
#define PROC_NULL 0
Definition at line 43 of file onc_rpc_server.c.
#define PROC_PLUS1 1
Definition at line 44 of file onc_rpc_server.c.
#define RECV_SIZE 2048
Definition at line 40 of file onc_rpc_server.c.
#define SEND_SIZE 2048
Definition at line 41 of file onc_rpc_server.c.
#define TIMEOUT_SEC 25
Definition at line 38 of file onc_rpc_server.c.
#define TraduireAdresse(adresse, dest)
Value:
sprintf( dest, "%d.%d.%d.%d",                   \
                  ( ntohl( adresse ) & 0xFF000000 ) >> 24, \
                  ( ntohl( adresse ) & 0x00FF0000 ) >> 16, \
                  ( ntohl( adresse ) & 0x0000FF00 ) >> 8,  \
                  ( ntohl( adresse ) & 0x000000FF ) )
Definition at line 32 of file onc_rpc_server.c.
#define V1 1
Definition at line 42 of file onc_rpc_server.c.
Function Documentation
void dispatch (struct Svc_req * ptr_req, SVCXPRT * ptr_svc)
Definition at line 63 of file onc_rpc_server.c.
References PROC_NULL, PROC_PLUS1, Svc_sendreply(), Svcerr_decode(), Xdr_int(), and Xdr_void().
Referenced by main().
main (int argc, char * argv[])
Definition at line 105 of file onc_rpc_server.c.
References dispatch(), LOGFILE_DEFAUT, options, Pmap_unset(), RECV_SIZE, rpc_service_num, SEND_SIZE, Svc_register(), Svc_run(), Svcauth_gss_tab_creds_alloc(), Svctcp_create(), utilisation, and V1.
Variable Documentation
char options[] = `hL:N:s:`
Definition at line 48 of file onc_rpc_server.c.
unsigned int rpc_service_num = DEFAULT_RPC_SERVICE
Definition at line 60 of file onc_rpc_server.c.
Referenced by main().
char utilisation[]
Initial value:
 
"Utilisation: %s [-hLs] \n"
"\t[-h]                   affiche cet aide en ligne\n"
"\t[-L <logfile>]         indique le fichier de log\n"
"\t[-N <NivDebug>]        indique le niveau de debug pour les journaux\n" 
"\t[-s <service RPC>]     indique le port ou le service a utiliser\n"
Definition at line 51 of file onc_rpc_server.c.