Pm_getport.c File Reference
#include <stdbool.h>
#include <unistd.h>
#include `Rpc.h`
#include `Pmap_prot.h`
#include `Pmap_clnt.h`
#include <sys/socket.h>
Functions
u_short Pmap_getport (struct sockaddr_in *address, u_long program, u_long version, u_int protocol)
Function Documentation
u_short Pmap_getport (struct sockaddr_in * address, u_long program, u_long version, u_int protocol)
Definition at line 53 of file Pm_getport.c.
References Clnt_perror(), Clnttcp_create(), Clntudp_bufcreate(), Xdr_Pmap(), and Xdr_u_short().