Pmap_prot.c File Reference
#include `Rpc.h`
#include `Clnt.h`
#include `Pmap_prot.h`
#include `Xdr.h`
Functions
bool_t Xdr_Pmap (XDR *xdrs, struct Pmap *regs)
Function Documentation
bool_t Xdr_Pmap (XDR * xdrs, struct Pmap * regs)
Definition at line 73 of file Pmap_prot.c.
References Xdr_u_long().
Referenced by Pmap_getport(), Pmap_set(), and Pmap_unset().