Pmap_clnt.c File Reference
#include <unistd.h>
#include `Rpc.h`
#include `Pmap_prot.h`
#include `Pmap_clnt.h`
Functions
void Clnt_perror ()
bool_t Pmap_set (u_long program, u_long version, u_int protocol, u_short port)
bool_t Pmap_unset (u_long program, u_long version)
Function Documentation
void Clnt_perror ()
Referenced by main(), Pmap_getport(), and Pmap_set().
bool_t Pmap_set (u_long program, u_long version, u_int protocol, u_short port)
Definition at line 51 of file Pmap_clnt.c.
References Clnt_perror(), Clntudp_bufcreate(), Xdr_bool(), and Xdr_Pmap().
Referenced by Svc_register().
bool_t Pmap_unset (u_long program, u_long version)
Definition at line 86 of file Pmap_clnt.c.
References Clntudp_bufcreate(), Xdr_bool(), and Xdr_Pmap().
Referenced by main(), and Svc_unregister().