Pmap_rmt.c File Reference
#include <unistd.h>
#include `Rpc.h`
#include `Auth_unix.h`
#include `Pmap_prot.h`
#include `Pmap_clnt.h`
#include `Pmap_rmt.h`
#include <sys/socket.h>
#include <stdio.h>
#include <errno.h>
#include <sys/param.h>
#include <net/if.h>
#include <sys/ioctl.h>
#include <arpa/inet.h>
Defines
#define MAX_BROADCAST_SIZE 1400
Functions
enum Clnt_stat Pmap_rmtcall (struct sockaddr_in *addr, u_long prog, u_long vers, u_long proc, Xdrproc_t xdrargs, caddr_t argsp, Xdrproc_t xdrres, caddr_t resp, struct timeval tout, u_long *port_ptr)
bool_t Xdr_Rmtcall_args (XDR *xdrs, struct Rmtcallargs *cap)
bool_t Xdr_Rmtcallres (XDR *xdrs, struct Rmtcallres *crp)
enum Clnt_stat Clnt_broadcast (u_long prog, u_long vers, u_long proc, Xdrproc_t xargs, caddr_t argsp, Xdrproc_t xresults, caddr_t resultsp, resultproc_t eachresult)
Define Documentation
#define MAX_BROADCAST_SIZE 1400
Definition at line 83 of file Pmap_rmt.c.
Referenced by Clnt_broadcast().
Function Documentation
enum Clnt_stat Clnt_broadcast (u_long prog, u_long vers, u_long proc, Xdrproc_t xargs, caddr_t argsp, Xdrproc_t xresults, caddr_t resultsp, resultproc_t eachresult)
Definition at line 208 of file Pmap_rmt.c.
References Authunix_create_default(), MAX_BROADCAST_SIZE, UDPMSGSIZE, Xdr_callmsg(), Xdr_replymsg(), Xdr_Rmtcall_args(), and Xdrmem_create().
enum Clnt_stat Pmap_rmtcall (struct sockaddr_in * addr, u_long prog, u_long vers, u_long proc, Xdrproc_t xdrargs, caddr_t argsp, Xdrproc_t xdrres, caddr_t resp, struct timeval tout, u_long * port_ptr)
Definition at line 97 of file Pmap_rmt.c.
References Clntudp_create(), Xdr_Rmtcall_args(), and Xdr_Rmtcallres().
bool_t Xdr_Rmtcall_args (XDR * xdrs, struct Rmtcallargs * cap)
Definition at line 141 of file Pmap_rmt.c.
References Xdr_u_long().
Referenced by Clnt_broadcast(), and Pmap_rmtcall().
bool_t Xdr_Rmtcallres (XDR * xdrs, struct Rmtcallres * crp)
Definition at line 169 of file Pmap_rmt.c.
References Xdr_reference(), and Xdr_u_long().
Referenced by Pmap_rmtcall().