Rpc_cmsg.c File Reference
#include <sys/param.h>
#include `Rpc.h`
Functions
bool_t Xdr_callmsg (XDR *xdrs, struct Rpc_msg *cmsg)
Function Documentation
bool_t Xdr_callmsg (XDR * xdrs, struct Rpc_msg * cmsg)
Definition at line 79 of file Rpc_cmsg.c.
References Xdr_enum(), Xdr_opaque(), Xdr_opaque_auth(), Xdr_u_int(), and Xdr_u_long().
Referenced by Clnt_broadcast().