Rpc_prot.c File Reference
#include <sys/param.h>
#include `Rpc.h`
Defines
#define Xdr_u_int32_t(x, a) Xdr_u_int(x, (u_int *)a)
Functions
bool_t Xdr_opaque_auth (XDR *xdrs, struct opaque_auth *ap)
bool_t Xdr_des_block (XDR *xdrs, des_block *blkp)
bool_t Xdr_accepted_reply (XDR *xdrs, struct accepted_reply *ar)
bool_t Xdr_rejected_reply (XDR *xdrs, struct rejected_reply *rr)
bool_t Xdr_replymsg (XDR *xdrs, struct Rpc_msg *rmsg)
bool_t Xdr_callhdr (XDR *xdrs, struct Rpc_msg *cmsg)
void _seterr_reply (struct Rpc_msg *msg, struct Rpc_err *error)
Define Documentation
#define Xdr_u_int32_t(x, a) Xdr_u_int(x, (u_int *)a)
Definition at line 47 of file Rpc_prot.c.
Referenced by Xdr_accepted_reply(), Xdr_callhdr(), Xdr_rejected_reply(), and Xdr_replymsg().
Function Documentation
void _seterr_reply (struct Rpc_msg * msg, struct Rpc_err * error)
Definition at line 216 of file Rpc_prot.c.
bool_t Xdr_accepted_reply (XDR * xdrs, struct accepted_reply * ar)
Definition at line 77 of file Rpc_prot.c.
References Xdr_enum(), Xdr_opaque_auth(), and Xdr_u_int32_t.
bool_t Xdr_callhdr (XDR * xdrs, struct Rpc_msg * cmsg)
Definition at line 143 of file Rpc_prot.c.
References Xdr_enum(), and Xdr_u_int32_t.
Referenced by Clntraw_create(), Clnttcp_create(), and Clntudp_bufcreate().
bool_t Xdr_des_block (XDR * xdrs, des_block * blkp)
Definition at line 67 of file Rpc_prot.c.
References Xdr_opaque().
bool_t Xdr_opaque_auth (XDR * xdrs, struct opaque_auth * ap)
Definition at line 55 of file Rpc_prot.c.
References Xdr_bytes(), and Xdr_enum().
Referenced by Authnone_create(), Xdr_accepted_reply(), and Xdr_callmsg().
bool_t Xdr_rejected_reply (XDR * xdrs, struct rejected_reply * rr)
Definition at line 101 of file Rpc_prot.c.
References Xdr_enum(), and Xdr_u_int32_t.
bool_t Xdr_replymsg (XDR * xdrs, struct Rpc_msg * rmsg)
Definition at line 127 of file Rpc_prot.c.
References Xdr_enum(), Xdr_u_int32_t, and Xdr_union().
Referenced by Clnt_broadcast().