rpcsec_gss_client.c File Reference
#include <stdio.h>
#include <unistd.h>
#include <sys/types.h>
#include <pwd.h>
#include <sys/param.h>
#include <netdb.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <sys/socket.h>
#include <errno.h>
#include `Rpc.h`
#include `Pmap_clnt.h`
Defines
#define TraduireAdresse(adresse, dest)
#define TIMEOUT_SEC 25
#define DEFAULT_RPC_SERVICE 300400
#define RECV_SIZE 2048
#define SEND_SIZE 2048
#define V1 1
#define PROC_NULL 0
#define PROC_PLUS1 1
#define DEFAULT_MECHANISM `kerberos_v5`
#define DEFAULT_PRINCIPAL `toto/trekking.bruyeres.s`
Functions
CLIENT * Creer_RPCClient (unsigned int adresse, unsigned int programme, unsigned int version, unsigned short port, int sockfd)
main (int argc, char *argv[])
Variables
gss_OID_desc krb5oid
char options [] = `hd:s:S:`
char utilisation []
char princ [1024]
char server [] = `server`
Define Documentation
#define DEFAULT_MECHANISM `kerberos_v5`
Definition at line 42 of file rpcsec_gss_client.c.
Referenced by main().
#define DEFAULT_PRINCIPAL `toto/trekking.bruyeres.s`
Definition at line 43 of file rpcsec_gss_client.c.
Referenced by main().
#define DEFAULT_RPC_SERVICE 300400
Definition at line 35 of file rpcsec_gss_client.c.
#define PROC_NULL 0
Definition at line 39 of file rpcsec_gss_client.c.
#define PROC_PLUS1 1
Definition at line 40 of file rpcsec_gss_client.c.
#define RECV_SIZE 2048
Definition at line 36 of file rpcsec_gss_client.c.
#define SEND_SIZE 2048
Definition at line 37 of file rpcsec_gss_client.c.
#define TIMEOUT_SEC 25
Definition at line 34 of file rpcsec_gss_client.c.
#define TraduireAdresse(adresse, dest)
Value:
sprintf( dest, "%d.%d.%d.%d",                   \
                  ( ntohl( adresse ) & 0xFF000000 ) >> 24, \
                  ( ntohl( adresse ) & 0x00FF0000 ) >> 16, \
                  ( ntohl( adresse ) & 0x0000FF00 ) >> 8,  \
                  ( ntohl( adresse ) & 0x000000FF ) )
Definition at line 28 of file rpcsec_gss_client.c.
#define V1 1
Definition at line 38 of file rpcsec_gss_client.c.
Function Documentation
CLIENT* Creer_RPCClient (unsigned int adresse, unsigned int programme, unsigned int version, unsigned short port, int sockfd)
Definition at line 62 of file rpcsec_gss_client.c.
References Clnttcp_create(), princ, RECV_SIZE, and SEND_SIZE.
main (int argc, char * argv[])
Definition at line 132 of file rpcsec_gss_client.c.
References Clnt_perror(), Creer_RPCClient(), DEFAULT_PRINCIPAL, options, princ, PROC_PLUS1, rpc_service_num, utilisation, V1, and Xdr_int().
Variable Documentation
gss_OID_desc krb5oid
Definition at line 50 of file client-gss.c.
char options[] = `hd:s:S:`
Definition at line 48 of file rpcsec_gss_client.c.
char princ[1024]
Definition at line 59 of file rpcsec_gss_client.c.
Referenced by Creer_RPCClient(), and main().
char server[] = `server`
Definition at line 60 of file rpcsec_gss_client.c.
char utilisation[]
Initial value:
"Utilisation: %s [-hds] message\n"
"\t[-h]                   affiche cet aide en ligbe\n"
"\t[-d <machine>]         indique la machine serveur\n"
"\t[-s <service RPC>]     indique le port ou le service a utiliser\n" 
"\t[-S <service auth>]    indique le principal a utiliser\n"
Definition at line 49 of file rpcsec_gss_client.c.