rpcsec_gss_server.c File Reference
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <sys/errno.h>
#include <sys/param.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include `Rpc.h`
#include `Pmap_clnt.h`
#include `gssapi/gssapi.h`
Classes
struct Svc_rpc_gss_data
Defines
#define LOGFILE_DEFAUT `./toto-server.log`
#define TraduireAdresse(adresse, dest)
#define TIMEOUT_SEC 25
#define DEFAULT_RPC_SERVICE 300400
#define RECV_SIZE 2048
#define SEND_SIZE 2048
#define V1 1
#define PROC_NULL 0
#define PROC_PLUS1 1
#define DEFAULT_MECHANISM `kerberos_v5`
#define DEFAULT_PRINCIPAL `toto@trekking.bruyeres.s`
#define SVCAUTH_PRIVATE(auth) ((struct Svc_rpc_gss_data *)(auth) $\rightarrow$ svc_ah_private)
Functions
void rpc_log_status (char *m, OM_uint32 maj_stat, OM_uint32 min_stat)
void dispatch (struct Svc_req *ptr_req, SVCXPRT *ptr_svc)
main (int argc, char *argv[])
Variables
char options [] = `hL:N:s:S:M:`
char utilisation []
unsigned int rpc_service_num = DEFAULT_RPC_SERVICE
Define Documentation
#define DEFAULT_MECHANISM `kerberos_v5`
Definition at line 46 of file rpcsec_gss_server.c.
#define DEFAULT_PRINCIPAL `toto@trekking.bruyeres.s`
Definition at line 47 of file rpcsec_gss_server.c.
#define DEFAULT_RPC_SERVICE 300400
Definition at line 39 of file rpcsec_gss_server.c.
#define LOGFILE_DEFAUT `./toto-server.log`
Definition at line 31 of file rpcsec_gss_server.c.
#define PROC_NULL 0
Definition at line 43 of file rpcsec_gss_server.c.
#define PROC_PLUS1 1
Definition at line 44 of file rpcsec_gss_server.c.
#define RECV_SIZE 2048
Definition at line 40 of file rpcsec_gss_server.c.
#define SEND_SIZE 2048
Definition at line 41 of file rpcsec_gss_server.c.
#define SVCAUTH_PRIVATE(auth) ((struct Svc_rpc_gss_data *)(auth) $\rightarrow$ svc_ah_private)
Definition at line 78 of file rpcsec_gss_server.c.
Referenced by dispatch().
#define TIMEOUT_SEC 25
Definition at line 38 of file rpcsec_gss_server.c.
#define TraduireAdresse(adresse, dest)
Value:
sprintf( dest, "%d.%d.%d.%d",                   \
                  ( ntohl( adresse ) & 0xFF000000 ) >> 24, \
                  ( ntohl( adresse ) & 0x00FF0000 ) >> 16, \
                  ( ntohl( adresse ) & 0x0000FF00 ) >> 8,  \
                  ( ntohl( adresse ) & 0x000000FF ) )
Definition at line 32 of file rpcsec_gss_server.c.
#define V1 1
Definition at line 42 of file rpcsec_gss_server.c.
Function Documentation
void dispatch (struct Svc_req * ptr_req, SVCXPRT * ptr_svc)
Definition at line 100 of file rpcsec_gss_server.c.
References Svc_rpc_gss_data::client_name, PROC_NULL, PROC_PLUS1, rpc_log_status(), Svc_rpc_gss_data::sec, Svc_sendreply(), SVCAUTH_PRIVATE, Svcerr_decode(), Svcerr_weakauth(), Xdr_int(), and Xdr_void().
main (int argc, char * argv[])
Definition at line 172 of file rpcsec_gss_server.c.
References DEFAULT_MECHANISM, DEFAULT_PRINCIPAL, dispatch(), LOGFILE_DEFAUT, options, Pmap_unset(), RECV_SIZE, rpc_service_num, SEND_SIZE, Svc_register(), Svc_run(), Svcauth_gss_tab_creds_alloc(), Svctcp_create(), utilisation, and V1.
void rpc_log_status (char * m, OM_uint32 maj_stat, OM_uint32 min_stat)
Definition at line 81 of file rpcsec_gss_server.c.
Variable Documentation
char options[] = `hL:N:s:S:M:`
Definition at line 50 of file rpcsec_gss_server.c.
unsigned int rpc_service_num = DEFAULT_RPC_SERVICE
Definition at line 64 of file rpcsec_gss_server.c.
char utilisation[]
Initial value:
 
"Utilisation: %s [-hLs] \n"
"\t[-h]                   affiche cet aide en ligne\n"
"\t[-L <logfile>]         indique le fichier de log\n"
"\t[-N <NivDebug>]        indique le niveau de debug pour les journaux\n" 
"\t[-s <service RPC>]     indique le port ou le service a utiliser\n" 
"\t[-S <service auth>]    indique le principal a utiliser\n"
"\t[-M <mechanism>]       indique le mecanisme a utiliser\n"
Definition at line 53 of file rpcsec_gss_server.c.