server-gss.c File Reference
#include <sys/param.h>
#include <sys/time.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <signal.h>
#include <sys/socket.h>
#include <netdb.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <gssapi/gssapi.h>
#include <gssapi/gssapi_generic.h>
Defines
#define TraduireAdresse(adresse, dest)
#define LOGFILE_DEFAUT `./toto-server.log`
#define MAX_CONN 32
#define LENMSG 256
#define STRLEN 256
#define GSS_SERVICE_DEFAUT `toto`
#define TOKEN_NOOP (1<<0)
#define TOKEN_CONTEXT (1<<1)
#define TOKEN_DATA (1<<2)
#define TOKEN_MIC (1<<3)
#define TOKEN_CONTEXT_NEXT (1<<4)
#define TOKEN_WRAPPED (1<<5)
#define TOKEN_ENCRYPTED (1<<6)
#define TOKEN_SEND_MIC (1<<7)
#define TOKEN_NOOP (1<<0)
#define TOKEN_CONTEXT (1<<1)
#define TOKEN_DATA (1<<2)
#define TOKEN_MIC (1<<3)
#define TOKEN_CONTEXT_NEXT (1<<4)
#define TOKEN_WRAPPED (1<<5)
#define TOKEN_ENCRYPTED (1<<6)
#define TOKEN_SEND_MIC (1<<7)
#define KEYTAB `/var/hpss/etc/hpss.keytab`
Functions
int recv_token (int s, int *flags, gss_buffer_t tok)
int send_token (int s, int flags, gss_buffer_t tok)
void sperror_gss (char *str, OM_uint32 major, OM_uint32 minor)
int obtention_creds (char *service_name, gss_cred_id_t *pcreds)
int negociation_server (int sockfd)
int main (int argc, char *argv[])
Variables
char rcsid [] = `$Id: server-gss.c,v 1.1 2005/04/13 13:45:49 deniel Exp $`
char options [] = `hL:N:P:S:`
char utilisation []
unsigned short binding_port = 0
char gss_service [STRLEN]
gss_cred_id_t creds
Define Documentation
#define GSS_SERVICE_DEFAUT `toto`
Definition at line 39 of file server-gss.c.
Referenced by main().
#define KEYTAB `/var/hpss/etc/hpss.keytab`
Definition at line 58 of file server-gss.c.
Referenced by obtention_creds().
#define LENMSG 256
Definition at line 37 of file server-gss.c.
#define LOGFILE_DEFAUT `./toto-server.log`
Definition at line 35 of file server-gss.c.
#define MAX_CONN 32
Definition at line 36 of file server-gss.c.
Referenced by main(), and Svctcp_create().
#define STRLEN 256
Definition at line 38 of file server-gss.c.
#define TOKEN_CONTEXT (1<<1)
Definition at line 50 of file server-gss.c.
#define TOKEN_CONTEXT (1<<1)
Definition at line 50 of file server-gss.c.
#define TOKEN_CONTEXT_NEXT (1<<4)
Definition at line 53 of file server-gss.c.
#define TOKEN_CONTEXT_NEXT (1<<4)
Definition at line 53 of file server-gss.c.
#define TOKEN_DATA (1<<2)
Definition at line 51 of file server-gss.c.
#define TOKEN_DATA (1<<2)
Definition at line 51 of file server-gss.c.
#define TOKEN_ENCRYPTED (1<<6)
Definition at line 55 of file server-gss.c.
#define TOKEN_ENCRYPTED (1<<6)
Definition at line 55 of file server-gss.c.
#define TOKEN_MIC (1<<3)
Definition at line 52 of file server-gss.c.
#define TOKEN_MIC (1<<3)
Definition at line 52 of file server-gss.c.
#define TOKEN_NOOP (1<<0)
Definition at line 49 of file server-gss.c.
#define TOKEN_NOOP (1<<0)
Definition at line 49 of file server-gss.c.
#define TOKEN_SEND_MIC (1<<7)
Definition at line 56 of file server-gss.c.
#define TOKEN_SEND_MIC (1<<7)
Definition at line 56 of file server-gss.c.
#define TOKEN_WRAPPED (1<<5)
Definition at line 54 of file server-gss.c.
#define TOKEN_WRAPPED (1<<5)
Definition at line 54 of file server-gss.c.
#define TraduireAdresse(adresse, dest)
Value:
sprintf( dest, "%d.%d.%d.%d",                   \
                  ( ntohl( adresse ) & 0xFF000000 ) >> 24, \
                  ( ntohl( adresse ) & 0x00FF0000 ) >> 16, \
                  ( ntohl( adresse ) & 0x0000FF00 ) >> 8,  \
                  ( ntohl( adresse ) & 0x000000FF ) )
Definition at line 28 of file server-gss.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 271 of file server-gss.c.
References binding_port, creds, gss_service, GSS_SERVICE_DEFAUT, LENMSG, LOGFILE_DEFAUT, MAX_CONN, negociation_server(), obtention_creds(), options, TraduireAdresse, and utilisation.
int negociation_server (int sockfd)
Definition at line 149 of file server-gss.c.
References creds, recv_token(), send_token(), sperror_gss(), and TOKEN_CONTEXT.
Referenced by main().
int obtention_creds (char * service_name, gss_cred_id_t * pcreds)
Definition at line 87 of file server-gss.c.
References KEYTAB, and sperror_gss().
Referenced by main().
int recv_token (int s, int * flags, gss_buffer_t tok)
Definition at line 218 of file tools-gss.c.
int send_token (int s, int flags, gss_buffer_t tok)
Definition at line 149 of file tools-gss.c.
Referenced by negociation_client(), negociation_server(), recv_msg(), and send_msg().
void sperror_gss (char * str, OM_uint32 major, OM_uint32 minor)
Definition at line 80 of file tools-gss.c.
Variable Documentation
unsigned short binding_port = 0
Definition at line 79 of file server-gss.c.
Referenced by main().
gss_cred_id_t creds
Definition at line 81 of file server-gss.c.
Referenced by main(), and negociation_server().
char gss_service[STRLEN]
Definition at line 80 of file server-gss.c.
Referenced by main().
char options[] = `hL:N:P:S:`
Definition at line 66 of file server-gss.c.
char rcsid[] = `$Id: server-gss.c,v 1.1 2005/04/13 13:45:49 deniel Exp $`
Definition at line 6 of file server-gss.c.
char utilisation[]
Initial value:
 
"Utilisation: %s [-hLPM] \n"
"\t[-h]                   affiche cet aide en ligne\n"
"\t[-L <logfile>]         indique le fichier de log\n"
"\t[-N <NivDebug>]        indique le niveau de debug pour les journaux\n" 
"\t[-P <port ou service>] indique le port ou le service a utiliser\n"
"\t[-S <service Auth>]    le service utilise par ls GSS-API\n"
Definition at line 69 of file server-gss.c.