Svc_udp.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include `Rpc.h`
#include `Clnt.h`
#include `Svc.h`
#include <sys/socket.h>
#include <errno.h>
Classes
struct Svcudp_data
Defines
#define UDPMSGSIZE 8800
#define rpc_buffer(xprt) ((xprt) $\rightarrow$ xp_p1)
#define Su_data(xprt) ((struct Svcudp_data *)(xprt $\rightarrow$ xp_p2))
Functions
SVCXPRT * Svcudp_bufcreate (register int sock, u_int sendsz, u_int recvsz)
SVCXPRT * Svcudp_create (int sock)
Define Documentation
#define rpc_buffer(xprt) ((xprt) $\rightarrow$ xp_p1)
Definition at line 16 of file Svc_udp.c.
Referenced by Svcudp_bufcreate().
#define Su_data(xprt) ((struct Svcudp_data *)(xprt $\rightarrow$ xp_p2))
Definition at line 44 of file Svc_udp.c.
#define UDPMSGSIZE 8800
Definition at line 13 of file Svc_udp.c.
Referenced by Clnt_broadcast(), Clntraw_create(), Clntudp_create(), Svcraw_create(), and Svcudp_create().
Function Documentation
SVCXPRT* Svcudp_bufcreate (register int sock, u_int sendsz, u_int recvsz)
Definition at line 60 of file Svc_udp.c.
References rpc_buffer, Svcudp_data::su_iosz, Svcudp_data::su_verfbody, Xdrmem_create(), and Xprt_register().
Referenced by Svcudp_create().
SVCXPRT* Svcudp_create (int sock)
Definition at line 146 of file Svc_udp.c.
References Svcudp_bufcreate(), and UDPMSGSIZE.