Svc.c File Reference
#include <stdlib.h>
#include <string.h>
#include <sys/errno.h>
#include `Rpc.h`
#include `Clnt.h`
#include `Pmap_clnt.h`
#include `Svc.h`
Classes
struct svc_callout
Defines
#define NULL_SVC ((struct svc_callout *)0)
#define RQCRED_SIZE 400
#define max(a, b) (a > b ? a : b)
Functions
void Xprt_register (SVCXPRT *xprt)
void Xprt_unregister (SVCXPRT *xprt)
bool_t Svc_register (SVCXPRT *xprt, u_long prog, u_long vers, void(*dispatch)(), int protocol)
void Svc_unregister (u_long prog, u_long vers)
void Svc_getreqset (fd_set *readfds)
bool_t Svc_sendreply (register SVCXPRT *xprt, Xdrproc_t xdr_results, caddr_t xdr_location)
void Svcerr_noproc (register SVCXPRT *xprt)
void Svcerr_decode (register SVCXPRT *xprt)
void Svcerr_systemerr (register SVCXPRT *xprt)
void Svcerr_auth (SVCXPRT *xprt, enum Auth_stat why)
void Svcerr_weakauth (SVCXPRT *xprt)
void Svcerr_noprog (register SVCXPRT *xprt)
void Svcerr_progvers (register SVCXPRT *xprt, u_long low_vers, u_long high_vers)
Variables
SVCXPRT ** Xports
unsigned int svc_maxfd
fd_set Svc_fdset
Define Documentation
#define max(a, b) (a > b ? a : b)
Definition at line 16 of file Svc.c.
Referenced by Xprt_register().
#define NULL_SVC ((struct svc_callout *)0)
Definition at line 13 of file Svc.c.
#define RQCRED_SIZE 400
Definition at line 14 of file Svc.c.
Function Documentation
void Svc_getreqset (fd_set * readfds)
Definition at line 171 of file Svc.c.
References Svc_authenticate(), and Xports.
Referenced by Svc_run().
bool_t Svc_register (SVCXPRT * xprt, u_long prog, u_long vers, void(*)() dispatch, int protocol)
Definition at line 103 of file Svc.c.
References Pmap_set().
Referenced by main().
bool_t Svc_sendreply (register SVCXPRT * xprt, Xdrproc_t xdr_results, caddr_t xdr_location)
Definition at line 271 of file Svc.c.
Referenced by dispatch().
void Svc_unregister (u_long prog, u_long vers)
Definition at line 134 of file Svc.c.
References Pmap_unset().
void Svcerr_auth (SVCXPRT * xprt, enum Auth_stat why)
Definition at line 330 of file Svc.c.
void Svcerr_decode (register SVCXPRT * xprt)
Definition at line 302 of file Svc.c.
Referenced by dispatch().
void Svcerr_noproc (register SVCXPRT * xprt)
Definition at line 287 of file Svc.c.
void Svcerr_noprog (register SVCXPRT * xprt)
Definition at line 353 of file Svc.c.
void Svcerr_progvers (register SVCXPRT * xprt, u_long low_vers, u_long high_vers)
Definition at line 367 of file Svc.c.
void Svcerr_systemerr (register SVCXPRT * xprt)
Definition at line 316 of file Svc.c.
void Svcerr_weakauth (SVCXPRT * xprt)
Definition at line 344 of file Svc.c.
Referenced by dispatch().
void Xprt_register (SVCXPRT * xprt)
Definition at line 51 of file Svc.c.
References max, Svc_fdset, svc_maxfd, and Xports.
Referenced by Svctcp_create(), and Svcudp_bufcreate().
void Xprt_unregister (SVCXPRT * xprt)
Definition at line 76 of file Svc.c.
References Svc_fdset, svc_maxfd, and Xports.
Variable Documentation
fd_set Svc_fdset
Definition at line 43 of file Svc.c.
Referenced by Xprt_register(), and Xprt_unregister().
unsigned int svc_maxfd
Definition at line 41 of file Svc.c.
Referenced by Xprt_register(), and Xprt_unregister().
SVCXPRT** Xports
Definition at line 11 of file Svc.c.
Referenced by Svc_getreqset(), Xprt_register(), and Xprt_unregister().