tools-gss.c File Reference
#include <sys/time.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <signal.h>
#include <sys/socket.h>
#include <netdb.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <gssapi/gssapi.h>
#include <gssapi/gssapi_generic.h>
Defines
#define gss_wrap gss_seal
#define gss_unwrap gss_unseal
#define gss_get_mic gss_sign
#define gss_verify_mic gss_verify
#define gss_qop_t OM_uint32
#define TOKEN_NOOP (1<<0)
#define TOKEN_CONTEXT (1<<1)
#define TOKEN_DATA (1<<2)
#define TOKEN_MIC (1<<3)
#define TOKEN_CONTEXT_NEXT (1<<4)
#define TOKEN_WRAPPED (1<<5)
#define TOKEN_ENCRYPTED (1<<6)
#define TOKEN_SEND_MIC (1<<7)
#define TOKEN_NOOP (1<<0)
#define TOKEN_CONTEXT (1<<1)
#define TOKEN_DATA (1<<2)
#define TOKEN_MIC (1<<3)
#define TOKEN_CONTEXT_NEXT (1<<4)
#define TOKEN_WRAPPED (1<<5)
#define TOKEN_ENCRYPTED (1<<6)
#define TOKEN_SEND_MIC (1<<7)
Functions
void sperror_gss_1 (char *str, OM_uint32 code, int type)
void sperror_gss (char *str, OM_uint32 maj_stat, OM_uint32 min_stat)
int send_token (int s, int flags, gss_buffer_t tok)
int recv_token (int s, int *flags, gss_buffer_t tok)
int send_msg (int fd, char *msg, gss_ctx_id_t context, char *errbuff)
int recv_msg (int fd, char *msg, gss_ctx_id_t context, char *errbuff)
Variables
char rcsid_tools [] = `$Id: tools-gss.c,v 1.1 2005/04/13 13:45:49 deniel Exp $`
Define Documentation
#define gss_get_mic gss_sign
Definition at line 29 of file tools-gss.c.
#define gss_qop_t OM_uint32
Definition at line 31 of file tools-gss.c.
#define gss_unwrap gss_unseal
Definition at line 28 of file tools-gss.c.
#define gss_verify_mic gss_verify
Definition at line 30 of file tools-gss.c.
#define gss_wrap gss_seal
Definition at line 27 of file tools-gss.c.
#define TOKEN_CONTEXT (1<<1)
Definition at line 42 of file tools-gss.c.
#define TOKEN_CONTEXT (1<<1)
Definition at line 42 of file tools-gss.c.
#define TOKEN_CONTEXT_NEXT (1<<4)
Definition at line 45 of file tools-gss.c.
#define TOKEN_CONTEXT_NEXT (1<<4)
Definition at line 45 of file tools-gss.c.
#define TOKEN_DATA (1<<2)
Definition at line 43 of file tools-gss.c.
#define TOKEN_DATA (1<<2)
Definition at line 43 of file tools-gss.c.
#define TOKEN_ENCRYPTED (1<<6)
Definition at line 47 of file tools-gss.c.
#define TOKEN_ENCRYPTED (1<<6)
Definition at line 47 of file tools-gss.c.
#define TOKEN_MIC (1<<3)
Definition at line 44 of file tools-gss.c.
#define TOKEN_MIC (1<<3)
Definition at line 44 of file tools-gss.c.
#define TOKEN_NOOP (1<<0)
Definition at line 41 of file tools-gss.c.
#define TOKEN_NOOP (1<<0)
Definition at line 41 of file tools-gss.c.
#define TOKEN_SEND_MIC (1<<7)
Definition at line 48 of file tools-gss.c.
#define TOKEN_SEND_MIC (1<<7)
Definition at line 48 of file tools-gss.c.
#define TOKEN_WRAPPED (1<<5)
Definition at line 46 of file tools-gss.c.
#define TOKEN_WRAPPED (1<<5)
Definition at line 46 of file tools-gss.c.
Function Documentation
int recv_msg (int fd, char * msg, gss_ctx_id_t context, char * errbuff)
Definition at line 348 of file tools-gss.c.
References gss_get_mic, gss_unwrap, recv_token(), send_token(), sperror_gss(), and TOKEN_MIC.
int recv_token (int s, int * flags, gss_buffer_t tok)
Definition at line 218 of file tools-gss.c.
Referenced by negociation_client(), negociation_server(), recv_msg(), and send_msg().
int send_msg (int fd, char * msg, gss_ctx_id_t context, char * errbuff)
Definition at line 285 of file tools-gss.c.
References gss_qop_t, gss_verify_mic, gss_wrap, recv_token(), send_token(), sperror_gss(), TOKEN_DATA, TOKEN_ENCRYPTED, and TOKEN_WRAPPED.
int send_token (int s, int flags, gss_buffer_t tok)
Definition at line 149 of file tools-gss.c.
Referenced by negociation_client(), negociation_server(), recv_msg(), and send_msg().
void sperror_gss (char * str, OM_uint32 maj_stat, OM_uint32 min_stat)
Definition at line 80 of file tools-gss.c.
References sperror_gss_1().
Referenced by negociation_client(), negociation_server(), obtention_creds(), recv_msg(), and send_msg().
void sperror_gss_1 (char * str, OM_uint32 code, int type)
Definition at line 54 of file tools-gss.c.
Referenced by sperror_gss().
Variable Documentation
char rcsid_tools[] = `$Id: tools-gss.c,v 1.1 2005/04/13 13:45:49 deniel Exp $`
Definition at line 7 of file tools-gss.c.