tools-gss.h File Reference
#include <sys/time.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <signal.h>
#include <sys/socket.h>
#include <netdb.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include `aglae.h`
#include <dce/gssapi.h>
Defines
#define TOKEN_NOOP (1<<0)
#define TOKEN_CONTEXT (1<<1)
#define TOKEN_DATA (1<<2)
#define TOKEN_MIC (1<<3)
#define TOKEN_CONTEXT_NEXT (1<<4)
#define TOKEN_WRAPPED (1<<5)
#define TOKEN_ENCRYPTED (1<<6)
#define TOKEN_SEND_MIC (1<<7)
#define TOKEN_NOOP (1<<0)
#define TOKEN_CONTEXT (1<<1)
#define TOKEN_DATA (1<<2)
#define TOKEN_MIC (1<<3)
#define TOKEN_CONTEXT_NEXT (1<<4)
#define TOKEN_WRAPPED (1<<5)
#define TOKEN_ENCRYPTED (1<<6)
#define TOKEN_SEND_MIC (1<<7)
Functions
void sperror_gss (char *str, OM_uint32 major, OM_uint32 minor)
int write_tok (int s, gss_buffer_t tok)
int read_tok (int s, gss_buffer_t tok)
int recv_msg (int fd, char *msg, gss_ctx_id_t context, char *errbuf)
int send_msg (int fd, char *msg, gss_ctx_id_t context, char *errbuf)
int recv_token (int s, int *flags, gss_buffer_t tok)
Define Documentation
#define TOKEN_CONTEXT (1<<1)
Definition at line 31 of file tools-gss.h.
#define TOKEN_CONTEXT (1<<1)
Definition at line 31 of file tools-gss.h.
#define TOKEN_CONTEXT_NEXT (1<<4)
Definition at line 34 of file tools-gss.h.
#define TOKEN_CONTEXT_NEXT (1<<4)
Definition at line 34 of file tools-gss.h.
#define TOKEN_DATA (1<<2)
Definition at line 32 of file tools-gss.h.
#define TOKEN_DATA (1<<2)
Definition at line 32 of file tools-gss.h.
#define TOKEN_ENCRYPTED (1<<6)
Definition at line 36 of file tools-gss.h.
#define TOKEN_ENCRYPTED (1<<6)
Definition at line 36 of file tools-gss.h.
#define TOKEN_MIC (1<<3)
Definition at line 33 of file tools-gss.h.
#define TOKEN_MIC (1<<3)
Definition at line 33 of file tools-gss.h.
#define TOKEN_NOOP (1<<0)
Definition at line 30 of file tools-gss.h.
#define TOKEN_NOOP (1<<0)
Definition at line 30 of file tools-gss.h.
#define TOKEN_SEND_MIC (1<<7)
Definition at line 37 of file tools-gss.h.
#define TOKEN_SEND_MIC (1<<7)
Definition at line 37 of file tools-gss.h.
#define TOKEN_WRAPPED (1<<5)
Definition at line 35 of file tools-gss.h.
#define TOKEN_WRAPPED (1<<5)
Definition at line 35 of file tools-gss.h.
Function Documentation
int read_tok (int s, gss_buffer_t tok)
int recv_msg (int fd, char * msg, gss_ctx_id_t context, char * errbuf)
Definition at line 348 of file tools-gss.c.
References gss_get_mic, gss_unwrap, recv_token(), send_token(), sperror_gss(), and TOKEN_MIC.
int recv_token (int s, int * flags, gss_buffer_t tok)
Definition at line 218 of file tools-gss.c.
Referenced by negociation_client(), negociation_server(), recv_msg(), and send_msg().
int send_msg (int fd, char * msg, gss_ctx_id_t context, char * errbuf)
Definition at line 285 of file tools-gss.c.
References gss_qop_t, gss_verify_mic, gss_wrap, recv_token(), send_token(), sperror_gss(), TOKEN_DATA, TOKEN_ENCRYPTED, and TOKEN_WRAPPED.
void sperror_gss (char * str, OM_uint32 major, OM_uint32 minor)
Definition at line 80 of file tools-gss.c.
References sperror_gss_1().
Referenced by negociation_client(), negociation_server(), obtention_creds(), recv_msg(), and send_msg().
int write_tok (int s, gss_buffer_t tok)