Xdr_mem.c File Reference
#include <string.h>
#include `Types.h`
#include `Xdr.h`
#include <netinet/in.h>
Functions
void Xdrmem_create (XDR *xdrs, caddr_t addr, u_int size, enum Xdr_op op)
Function Documentation
void Xdrmem_create (XDR * xdrs, caddr_t addr, u_int size, enum Xdr_op op)
Definition at line 90 of file Xdr_mem.c.
Referenced by Authnone_create(), Authunix_create(), Clnt_broadcast(), Clntraw_create(), Clnttcp_create(), Clntudp_bufcreate(), Svcraw_create(), and Svcudp_bufcreate().