Xdr.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include `Types.h`
#include `Xdr.h`
Defines
#define XDR_FALSE ((long) 0)
#define XDR_TRUE ((long) 1)
#define LASTUNSIGNED ((u_int) 0-1)
Functions
void Xdr_free (Xdrproc_t proc, char *objp)
bool_t Xdr_void ()
bool_t Xdr_int (XDR *xdrs, int *ip)
bool_t Xdr_u_int (XDR *xdrs, u_int *up)
bool_t Xdr_long (XDR *xdrs, long *lp)
bool_t Xdr_u_long (XDR *xdrs, u_long *ulp)
bool_t Xdr_int_32_t (XDR *xdrs, int32_t *int32_p)
bool_t Xdr_u_int_32_t (XDR *xdrs, u_int32_t *u_int32_p)
bool_t Xdr_short (XDR *xdrs, short *sp)
bool_t Xdr_u_short (XDR *xdrs, u_short *usp)
bool_t Xdr_int16_t (XDR *xdrs, int16_t *int16_p)
bool_t Xdr_u_int16_t (XDR *xdrs, u_int16_t *u_int16_p)
bool_t Xdr_char (XDR *xdrs, char *cp)
bool_t Xdr_u_char (XDR *xdrs, u_char *cp)
bool_t Xdr_bool (XDR *xdrs, bool_t *bp)
bool_t Xdr_enum (XDR *xdrs, enum_t *ep)
bool_t Xdr_opaque (XDR *xdrs, caddr_t cp, u_int cnt)
bool_t Xdr_bytes (XDR *xdrs, char **cpp, u_int *sizep, u_int maxsize)
bool_t Xdr_netobj (XDR *xdrs, struct netobj *np)
bool_t Xdr_union (XDR *xdrs, enum_t *dscmp, char *unp, struct Xdr_discrim *choices, Xdrproc_t dfault)
bool_t Xdr_string (XDR *xdrs, char **cpp, u_int maxsize)
bool_t Xdr_wrapstring (XDR *xdrs, char **cpp)
bool_t Xdr_u_longlong_t (register XDR *xdrs, u_longlong_t *objp)
bool_t Xdr_longlong_t (register XDR *xdrs, longlong_t *objp)
Define Documentation
#define LASTUNSIGNED ((u_int) 0-1)
Definition at line 52 of file Xdr.c.
Referenced by Xdr_wrapstring().
#define XDR_FALSE ((long) 0)
Definition at line 50 of file Xdr.c.
#define XDR_TRUE ((long) 1)
Definition at line 51 of file Xdr.c.
Referenced by Xdr_bool().
Function Documentation
bool_t Xdr_bool (XDR * xdrs, bool_t * bp)
Definition at line 407 of file Xdr.c.
References XDR_TRUE.
Referenced by Pmap_set(), Pmap_unset(), and Xdr_pointer().
bool_t Xdr_bytes (XDR * xdrs, char ** cpp, u_int * sizep, u_int maxsize)
Definition at line 526 of file Xdr.c.
References Xdr_opaque(), and Xdr_u_int().
Referenced by Xdr_netobj(), and Xdr_opaque_auth().
bool_t Xdr_char (XDR * xdrs, char * cp)
Definition at line 371 of file Xdr.c.
References Xdr_int().
bool_t Xdr_enum (XDR * xdrs, enum_t * ep)
Definition at line 436 of file Xdr.c.
References Xdr_int(), Xdr_long(), and Xdr_short().
Referenced by Xdr_accepted_reply(), Xdr_callhdr(), Xdr_callmsg(), Xdr_opaque_auth(), Xdr_rejected_reply(), Xdr_replymsg(), and Xdr_union().
void Xdr_free (Xdrproc_t proc, char * objp)
Definition at line 64 of file Xdr.c.
bool_t Xdr_int (XDR * xdrs, int * ip)
Definition at line 91 of file Xdr.c.
Referenced by dispatch(), main(), Xdr_char(), and Xdr_enum().
bool_t Xdr_int16_t (XDR * xdrs, int16_t * int16_p)
Definition at line 312 of file Xdr.c.
bool_t Xdr_int_32_t (XDR * xdrs, int32_t * int32_p)
Definition at line 193 of file Xdr.c.
bool_t Xdr_long (XDR * xdrs, long * lp)
Definition at line 151 of file Xdr.c.
Referenced by Xdr_enum().
bool_t Xdr_longlong_t (register XDR * xdrs, longlong_t * objp)
Definition at line 787 of file Xdr.c.
References Xdr_u_longlong_t().
bool_t Xdr_netobj (XDR * xdrs, struct netobj * np)
Definition at line 596 of file Xdr.c.
References Xdr_bytes().
bool_t Xdr_opaque (XDR * xdrs, caddr_t cp, u_int cnt)
Definition at line 468 of file Xdr.c.
Referenced by Xdr_bytes(), Xdr_callmsg(), Xdr_des_block(), and Xdr_string().
bool_t Xdr_short (XDR * xdrs, short * sp)
Definition at line 253 of file Xdr.c.
Referenced by Xdr_enum().
bool_t Xdr_string (XDR * xdrs, char ** cpp, u_int maxsize)
Definition at line 665 of file Xdr.c.
References Xdr_opaque(), and Xdr_u_int().
Referenced by Xdr_Authunix_parms(), and Xdr_wrapstring().
bool_t Xdr_u_char (XDR * xdrs, u_char * cp)
Definition at line 389 of file Xdr.c.
References Xdr_u_int().
bool_t Xdr_u_int (XDR * xdrs, u_int * up)
Definition at line 120 of file Xdr.c.
Referenced by Xdr_array(), Xdr_Authunix_parms(), Xdr_bytes(), Xdr_callmsg(), Xdr_string(), and Xdr_u_char().
bool_t Xdr_u_int16_t (XDR * xdrs, u_int16_t * u_int16_p)
Definition at line 341 of file Xdr.c.
bool_t Xdr_u_int_32_t (XDR * xdrs, u_int32_t * u_int32_p)
Definition at line 223 of file Xdr.c.
bool_t Xdr_u_long (XDR * xdrs, u_long * ulp)
Definition at line 172 of file Xdr.c.
Referenced by Xdr_Authunix_parms(), Xdr_callmsg(), Xdr_Pmap(), Xdr_Rmtcall_args(), and Xdr_Rmtcallres().
bool_t Xdr_u_longlong_t (register XDR * xdrs, u_longlong_t * objp)
Definition at line 745 of file Xdr.c.
Referenced by Xdr_longlong_t().
bool_t Xdr_u_short (XDR * xdrs, u_short * usp)
Definition at line 282 of file Xdr.c.
Referenced by Pmap_getport(), and Xdr_Authunix_parms().
bool_t Xdr_union (XDR * xdrs, enum_t * dscmp, char * unp, struct Xdr_discrim * choices, Xdrproc_t dfault)
Definition at line 616 of file Xdr.c.
References Xdr_enum().
Referenced by Xdr_replymsg().
bool_t Xdr_void ()
Definition at line 78 of file Xdr.c.
Referenced by dispatch().
bool_t Xdr_wrapstring (XDR * xdrs, char ** cpp)
Definition at line 737 of file Xdr.c.
References LASTUNSIGNED, and Xdr_string().