Xdr_reference.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include `Types.h`
#include `Xdr.h`
Functions
bool_t Xdr_reference (XDR *xdrs, caddr_t *pp, u_int size, Xdrproc_t proc)
bool_t Xdr_pointer (XDR *xdrs, char **objpp, u_int obj_size, Xdrproc_t xdr_obj)
Function Documentation
bool_t Xdr_pointer (XDR * xdrs, char ** objpp, u_int obj_size, Xdrproc_t xdr_obj)
Definition at line 123 of file Xdr_reference.c.
References Xdr_bool(), and Xdr_reference().
bool_t Xdr_reference (XDR * xdrs, caddr_t * pp, u_int size, Xdrproc_t proc)
Definition at line 59 of file Xdr_reference.c.
Referenced by Xdr_pointer(), and Xdr_Rmtcallres().