nfs_main.c File Reference
The file that contain the 'main' routine for the nfsd.
#include `nfs_init.h`
#include `fsal.h`
#include <stdio.h>
#include <string.h>
#include <pthread.h>
#include <signal.h>
#include <errno.h>
Functions
int main (int argc, char *argv[])
Variables
nfs_start_info_t nfs_start_info
char config_path [MAXPATHLEN] = `/etc/ganesha/ganesha_nfsd.conf`
char log_path [MAXPATHLEN] = `/tmp/ganesha_nfsd.log`
char exec_name [MAXPATHLEN] = `ganesha-nfsd`
char host_name [MAXHOSTNAMELEN] = `localhost`
int debug_level = NIV_EVENT
int detach_flag = FALSE
char options [] = `h@RdS:F:S:f:L:N:`
char usage []
Detailed Description
The file that contain the 'main' routine for the nfsd.
Author:
Author deniel
nfs_main.c(p.) : The file that contain the 'main' routine for the nfsd.
Definition in file nfs_main.c.
Function Documentation
int main (int argc, char * argv[])
main: simply the main function.
The 'main' function as in every C program.
Parameters:
argc number of arguments
argv array of arguments
Returns: status to calling program by calling the exit(3C) function.
Definition at line 173 of file nfs_main.c.
References config_path, debug_level, detach_flag, __nfs_start_info::enable_rpcsec_gss, exec_name, __nfs_start_info::flush_behaviour, __nfs_start_info::flush_datacache_mode, host_name, log_path, __nfs_start_info::nb_flush_threads, nfs_check_param_consistency(), nfs_param, nfs_prereq_init(), nfs_set_param_default(), nfs_set_param_from_conf(), nfs_start(), nfs_start_info, options, and usage.
Variable Documentation
char config_path[MAXPATHLEN] = `/etc/ganesha/ganesha_nfsd.conf`
Definition at line 108 of file nfs_main.c.
int debug_level = NIV_EVENT
Definition at line 112 of file nfs_main.c.
int detach_flag = FALSE
Definition at line 113 of file nfs_main.c.
char exec_name[MAXPATHLEN] = `ganesha-nfsd`
Definition at line 110 of file nfs_main.c.
char host_name[MAXHOSTNAMELEN] = `localhost`
Definition at line 111 of file nfs_main.c.
char log_path[MAXPATHLEN] = `/tmp/ganesha_nfsd.log`
Definition at line 109 of file nfs_main.c.
nfs_start_info_t nfs_start_info
Initial value:
{
   .flush_datacache_mode = FALSE,
   .nb_flush_threads     = 1,
   .flush_behaviour      = CACHE_CONTENT_FLUSH_AND_DELETE,
   .enable_rpcsec_gss    = FALSE
}
Definition at line 100 of file nfs_main.c.
char options[] = `h@RdS:F:S:f:L:N:`
Definition at line 118 of file nfs_main.c.
char usage[]
Initial value:
 
    "Usage: %s [-hd][-L <logfile>][-N <dbg_lvl>][-f <config_file>]\n"
    "\t[-h]                display this help\n"
    "\t[-L <logfile>]      set the default logfile for the daemon\n"
    "\t[-N <dbg_lvl>]      set the verbosity level\n"
    "\t[-f <config_file>]  set the config file to be used\n"
    "\t[-d]                the daemon starts in background, in a new process group\n"
    "\t[-R]                daemon will manage RPCSEC_GSS (default is no RPCSEC_GSS)\n"
    "\t[-F] <nb_flushers>  flushes the data cache with purge, but do not answer to requests\n"
    "\t[-S] <nb_flushers>  flushes the data cache without purge, but do not answer to requests\n"
    "----------------- Signals ----------------\n"
    "SIGUSR1    : Enable/Disable File Content Cache forced flush\n" 
    "------------- Default Values -------------\n"
    "LogFile    : /tmp/ganesha_nfsd.log\n"
    "DebugLevel : NIV_EVENT\n"
    "ConfigFile : /etc/ganesha_nfsd.conf\n"
Definition at line 119 of file nfs_main.c.