nfs_rpc_dispatcher_thread.c File Reference
#include <stdio.h>
#include <string.h>
#include <pthread.h>
#include <fcntl.h>
#include <sys/file.h>
#include <gssapi/gssapi.h>
#include <sys/select.h>
#include `HashData.h`
#include `HashTable.h`
#include <rpc/rpc.h>
#include <rpc/svc.h>
#include <rpc/pmap_clnt.h>
#include `log_functions.h`
#include `stuff_alloc.h`
#include `nfs23.h`
#include `nfs4.h`
#include `mount.h`
#include `nfs_core.h`
#include `cache_inode.h`
#include `cache_content.h`
#include `nfs_exports.h`
#include `nfs_creds.h`
#include `nfs_proto_functions.h`
#include `nfs_dupreq.h`
#include `nfs_file_handle.h`
#include `nfs_stat.h`
#include `SemN.h`
Classes
struct svc_callout
Defines
#define NULL_SVC ((struct svc_callout *)0)
#define NO_VALUE_CHOOSEN 1000000
Functions
SVCXPRT * Svcfd_create (int fd, u_int sendsize, u_int recvsize)
SVCXPRT * Svctcp_create (register int sock, u_int sendsize, u_int recvsize)
SVCXPRT * Svcudp_bufcreate (register int sock, u_int sendsz, u_int recvsz)
bool_t Svc_register (SVCXPRT *xprt, u_long prog, u_long vers, void(*dispatch)(), int protocol)
void socket_setoptions (int socketFd)
void nfs_rpc_dispatch_dummy (struct svc_req *ptr_req, SVCXPRT *ptr_svc)
int nfs_Init_svc ()
int nfs_rpc_get_worker_index (int mount_protocol_flag)
void nfs_rpc_getreq (fd_set *readfds, nfs_parameter_t *pnfs_para)
int clean_pending_request (LRU_entry_t *pentry, void *addparam)
int print_pending_request (LRU_data_t data, char *str)
void rpc_dispatcher_svc_run (nfs_parameter_t *pnfs_param)
void * rpc_dispatcher_thread (void *Arg)
int nfs_Init_request_data (nfs_request_data_t *pdata)
void constructor_nfs_request_data_t (void *ptr)
int nfs_Init_gc_counter (void)
Variables
fd_set Svc_fdset
nfs_worker_data_t * workers_data
nfs_parameter_t nfs_param
SVCXPRT ** Xports
hash_table_t * ht_dupreq
int rpcsec_gss_flag
pthread_mutex_t mutex_cond_xprt [FD_SETSIZE]
pthread_cond_t condvar_xprt [FD_SETSIZE]
int etat_xprt [FD_SETSIZE]
unsigned int nb_current_gc_workers
pthread_mutex_t lock_nb_current_gc_workers
Define Documentation
#define NO_VALUE_CHOOSEN 1000000
#define NULL_SVC ((struct svc_callout *)0)
Definition at line 135 of file nfs_rpc_dispatcher_thread.c.
Function Documentation
int clean_pending_request (LRU_entry_t * pentry, void * addparam)
clean_pending_request: cleans an entry in a nfs request LRU,
cleans an entry in a nfs request LRU.
Parameters:
pentry [INOUT] entry to be cleaned.
addparam [IN] additional parameter used for cleaning.
Returns: 0 if ok, other values mean an error.
Definition at line 1074 of file nfs_rpc_dispatcher_thread.c.
void constructor_nfs_request_data_t (void * ptr)
constructor_nfs_request_data_t: Constructor for a nfs_request_data_t structure
This function is used to init the nfs_request_data for a worker. These data are used by the worker for RPC processing.
Parameters:
ptr void pointer to the structure to be managed
Returns: nothing (void function) will exit the program if failed.
Definition at line 1265 of file nfs_rpc_dispatcher_thread.c.
References nfs_Init_request_data().
Referenced by nfs_rpc_getreq(), and rpc_tcp_socket_manager_thread().
int nfs_Init_gc_counter (void)
nfs_Init_gc_counter: Init the worker's gc counters.
This functions is used to init a mutex and a counter associated with it, to keep track of the number of worker currently performing the garbagge collection.
Parameters:
void No parameters
Returns: 0 if successfull, -1 otherwise.
Definition at line 1288 of file nfs_rpc_dispatcher_thread.c.
References lock_nb_current_gc_workers, and nb_current_gc_workers.
int nfs_Init_request_data (nfs_request_data_t * pdata)
nfs_Init_request_data: Init the data associated with a pending request
This function is used to init the nfs_request_data for a worker. These data are used by the worker for RPC processing.
Parameters:
param A structure of type nfs_worker_parameter_t with all the necessary information related to a worker
pdata Pointer to the data to be initialized.
Returns: 0 if successfull, -1 otherwise.
Definition at line 1231 of file nfs_rpc_dispatcher_thread.c.
References nfs_param, and Svcudp_bufcreate().
Referenced by constructor_nfs_request_data_t().
int nfs_Init_svc ()
nfs_Init_svc: Init the svc descriptors for the nfs daemon.
Perform all the required initialization for the SVCXPRT pointer.
Definition at line 336 of file nfs_rpc_dispatcher_thread.c.
References nfs_param, nfs_rpc_dispatch_dummy(), rpcsec_gss_flag, socket_setoptions(), Svc_fdset, Svc_register(), Svcauth_gss_acquire_cred(), Svcauth_gss_import_name(), Svctcp_create(), and Svcudp_bufcreate().
void nfs_rpc_dispatch_dummy (struct svc_req * ptr_req, SVCXPRT * ptr_svc)
nfs_rpc_dispatch_dummy: Function never called, but the symbol is necessary for Svc_register/
Parameters:
ptr_req the RPC request to be managed
ptr_svc SVCXPRT pointer to be used for managing this request
Returns: nothing (void function) and is never called indeed.
Definition at line 322 of file nfs_rpc_dispatcher_thread.c.
Referenced by nfs_Init_svc().
int nfs_rpc_get_worker_index (int mount_protocol_flag)
nfs_rpc_get_worker_index: Returns the index of the worker to be used
Parameters:
mount_protocol_flag a flag (TRUE of FALSE) to tell if the worker is to be used for mount protocol
Returns: the chosen worker index.
Definition at line 796 of file nfs_rpc_dispatcher_thread.c.
Referenced by nfs_rpc_getreq(), and rpc_tcp_socket_manager_thread().
void nfs_rpc_getreq (fd_set * readfds, nfs_parameter_t * pnfs_para)
nfs_rpc_getreq: Do half of the work done by svc_getreqset.
This function wait for an incoming ONC message by waiting on a 'select' statement. Then getting a request it perform the authentication and extracts the RPC message for the related socket. It then find the less busy worker (the one with the shortest pending queue) and put the msg in this queue.
Parameters:
readfds File Descriptor Set related to the socket used for RPC management.
Returns: Nothing (void function), but calls svcerr_* function to notify the client when an error occures.
Definition at line 826 of file nfs_rpc_dispatcher_thread.c.
References constructor_nfs_request_data_t(), nfs_param, nfs_rpc_get_worker_index(), workers_data, and Xports.
Referenced by rpc_dispatcher_svc_run().
int print_pending_request (LRU_data_t data, char * str)
print_pending_request: prints an entry related to a pending request in the LRU list.
prints an entry related to a pending request in the LRU list.
Parameters:
data [IN] data stored in a LRU entry to be printed.
str [OUT] string used to store the result.
Returns: 0 if ok, other values mean an error.
Definition at line 1097 of file nfs_rpc_dispatcher_thread.c.
void rpc_dispatcher_svc_run (nfs_parameter_t * pnfs_param)
nfs_rpc_dispatcher_svc_run: the same as svc_run.
The same as svc_run.
Parameters:
none
Returns: nothing (void function)
Definition at line 1113 of file nfs_rpc_dispatcher_thread.c.
References nfs_rpc_getreq().
Referenced by rpc_dispatcher_thread().
void* rpc_dispatcher_thread (void * Arg)
rpc_dispatcher_thread: thread used for RPC dispatching.
Thead used for RPC dispatching. It gets the requests and then spool it to one of the worker's LRU. The worker chosen is the one with the smaller load (its LRU is the shorter one).
Parameters:
IndexArg the index for the worker thread (unused)
Returns: Pointer to the result (but this function will mostly loop forever).
Definition at line 1190 of file nfs_rpc_dispatcher_thread.c.
References nfs_param, and rpc_dispatcher_svc_run().
void socket_setoptions (int socketFd)
Definition at line 245 of file nfs_tools.c.
bool_t Svc_register (SVCXPRT * xprt, u_long prog, u_long vers, void(*)() dispatch, int protocol)
Definition at line 107 of file Svc_oncrpc.c.
Referenced by nfs_Init_svc().
SVCXPRT* Svcfd_create (int fd, u_int sendsize, u_int recvsize)
Definition at line 219 of file Svc_tcp_gssrpc.c.
SVCXPRT* Svctcp_create (register int sock, u_int sendsize, u_int recvsize)
Definition at line 151 of file Svc_tcp_gssrpc.c.
References MAX_CONN, tcp_rendezvous::recvsize, tcp_rendezvous::sendsize, and Xprt_register().
Referenced by nfs_Init_svc().
SVCXPRT* Svcudp_bufcreate (register int sock, u_int sendsz, u_int recvsz)
Definition at line 113 of file Svc_udp_gssrpc.c.
References MAX, rpc_buffer, Svcudp_data::su_iosz, Svcudp_data::su_verfbody, and Xprt_register().
Referenced by nfs_Init_request_data(), nfs_Init_svc(), and Svcudp_create().
Variable Documentation
pthread_cond_t condvar_xprt[FD_SETSIZE]
Definition at line 73 of file Svc_tcp_gssrpc.c.
Referenced by rpc_tcp_socket_manager_thread(), and worker_thread().
int etat_xprt[FD_SETSIZE]
Definition at line 74 of file Svc_tcp_gssrpc.c.
Referenced by rpc_tcp_socket_manager_thread(), and worker_thread().
hash_table_t* ht_dupreq
Definition at line 136 of file nfs_dupreq.c.
pthread_mutex_t lock_nb_current_gc_workers
Definition at line 160 of file nfs_rpc_dispatcher_thread.c.
Referenced by nfs_Init_gc_counter(), and worker_thread().
pthread_mutex_t mutex_cond_xprt[FD_SETSIZE]
Definition at line 72 of file Svc_tcp_gssrpc.c.
Referenced by rpc_tcp_socket_manager_thread(), and worker_thread().
unsigned int nb_current_gc_workers
Definition at line 159 of file nfs_rpc_dispatcher_thread.c.
Referenced by nfs_Init_gc_counter(), and worker_thread().
nfs_parameter_t nfs_param
Definition at line 130 of file nfs_init.c.
int rpcsec_gss_flag
Referenced by nfs_Init_svc().
fd_set Svc_fdset
Definition at line 72 of file Svc_gssrpc.c.
Referenced by nfs_Init_svc(), Xprt_register(), and Xprt_unregister().
nfs_worker_data_t* workers_data
Definition at line 132 of file nfs_init.c.
SVCXPRT** Xports
Definition at line 66 of file Svc_gssrpc.c.
Referenced by nfs_rpc_getreq(), rpc_tcp_socket_manager_thread(), Svc_getreqset(), Xprt_register(), and Xprt_unregister().