.TH "nfs2_Writecache.c" 3 "15 Sep 2010" "Version 0.1" "NFS and Mount protocols layer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfs2_Writecache.c \- 
.PP
Implement NFSPROC2_WRITECACHE.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <pthread.h>\fP
.br
\fC#include <fcntl.h>\fP
.br
\fC#include <sys/file.h>\fP
.br
\fC#include 'HashData.h'\fP
.br
\fC#include 'HashTable.h'\fP
.br
\fC#include <rpc/types.h>\fP
.br
\fC#include <rpc/rpc.h>\fP
.br
\fC#include <rpc/auth.h>\fP
.br
\fC#include <rpc/pmap_clnt.h>\fP
.br
\fC#include 'log_macros.h'\fP
.br
\fC#include 'stuff_alloc.h'\fP
.br
\fC#include 'nfs23.h'\fP
.br
\fC#include 'nfs4.h'\fP
.br
\fC#include 'mount.h'\fP
.br
\fC#include 'nfs_core.h'\fP
.br
\fC#include 'cache_inode.h'\fP
.br
\fC#include 'cache_content.h'\fP
.br
\fC#include 'nfs_exports.h'\fP
.br
\fC#include 'nfs_creds.h'\fP
.br
\fC#include 'nfs_proto_functions.h'\fP
.br
\fC#include 'nfs_tools.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBnfs2_Writecache\fP (nfs_arg_t *parg, exportlist_t *pexport, fsal_op_context_t *pcontext, cache_inode_client_t *pclient, hash_table_t *ht, struct svc_req *preq, nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBnfs2_Writecache_Free\fP (nfs_res_t *pres)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implement NFSPROC2_WRITECACHE. 

\fBAuthor:\fP
.RS 4
.RE
.PP
\fBAuthor\fP.RS 4
deniel 
.RE
.PP
\fBDate:\fP
.RS 4
.RE
.PP
\fBDate\fP.RS 4
2005/11/28 17:02:49 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision\fP.RS 4
1.15 
.RE
.PP
Everything you wanted to know about NFSPROC2_WRITECACHE but were afraid to ask. 
.PP
Definition in file \fBnfs2_Writecache.c\fP.
.SH "Function Documentation"
.PP 
.SS "int nfs2_Writecache (nfs_arg_t * parg, exportlist_t * pexport, fsal_op_context_t * pcontext, cache_inode_client_t * pclient, hash_table_t * ht, struct svc_req * preq, nfs_res_t * pres)"nfs2_Writecache: Implements NFSPROC2_WRITECACHE.
.PP
Implements NFSPROC2_WRITECACHE
.PP
\fBParameters:\fP
.RS 4
\fIparg\fP [IN] pointer to nfs arguments union 
.br
\fIpexport\fP [IN] pointer to nfs export list 
.br
\fIpcontext\fP [IN] credentials to be used for this request 
.br
\fIpclient\fP [INOUT] client resource to be used 
.br
\fIpreq\fP [IN] pointer to SVC request related to this call 
.br
\fIht\fP [INOUT] cache inode hash table 
.br
\fIpres\fP [OUT] pointer to the structure to contain the result of the call
.RE
.PP
\fBReturns:\fP
.RS 4
always NFS_REQ_OK (this routine does nothing) 
.RE
.PP

.PP
Definition at line 93 of file nfs2_Writecache.c.
.SS "void nfs2_Writecache_Free (nfs_res_t * pres)"nfs2_Writecache_Free: Frees the result structure allocated for nfs2_Writecache.
.PP
Frees the result structure allocated for nfs2_Root.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 113 of file nfs2_Writecache.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for NFS and Mount protocols layer from the source code.
