.TH "nfs4_op_verify.c" 3 "31 Mar 2009" "Version 0.1" "NFS and Mount protocols layer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfs4_op_verify.c \- Routines used for managing the NFS4 COMPOUND functions.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <pthread.h>\fP
.br
\fC#include <fcntl.h>\fP
.br
\fC#include <sys/file.h>\fP
.br
\fC#include 'HashData.h'\fP
.br
\fC#include 'HashTable.h'\fP
.br
\fC#include <rpc/types.h>\fP
.br
\fC#include <rpc/rpc.h>\fP
.br
\fC#include <rpc/auth.h>\fP
.br
\fC#include <rpc/pmap_clnt.h>\fP
.br
\fC#include 'log_functions.h'\fP
.br
\fC#include 'stuff_alloc.h'\fP
.br
\fC#include 'nfs23.h'\fP
.br
\fC#include 'nfs4.h'\fP
.br
\fC#include 'mount.h'\fP
.br
\fC#include 'nfs_core.h'\fP
.br
\fC#include 'cache_inode.h'\fP
.br
\fC#include 'cache_content.h'\fP
.br
\fC#include 'nfs_exports.h'\fP
.br
\fC#include 'nfs_creds.h'\fP
.br
\fC#include 'nfs_proto_functions.h'\fP
.br
\fC#include 'nfs_tools.h'\fP
.br
\fC#include 'nfs_file_handle.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBarg_VERIFY4\fP   op->nfs_argop4_u.opverify"
.br
.ti -1c
.RI "#define \fBres_VERIFY4\fP   resp->nfs_resop4_u.opverify"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBnfs4_op_verify\fP (struct nfs_argop4 *op, compound_data_t *data, struct nfs_resop4 *resp)"
.br
.ti -1c
.RI "void \fBnfs4_op_verify_Free\fP (VERIFY4res *resp)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Routines used for managing the NFS4 COMPOUND functions. 

\fBAuthor:\fP
.RS 4
.RE
.PP
\fBAuthor\fP.RS 4
deniel 
.RE
.PP
\fBDate:\fP
.RS 4
.RE
.PP
\fBDate\fP.RS 4
2006/01/05 15:14:52 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision\fP.RS 4
1.14 
.RE
.PP
\fBnfs4_op_verify.c\fP : Routines used for managing the NFS4 COMPOUND functions. 
.PP
Definition in file \fBnfs4_op_verify.c\fP.
.SH "Define Documentation"
.PP 
.SS "#define arg_VERIFY4   op->nfs_argop4_u.opverify"
.PP
nfs4_op_verify: Implemtation of NFS4_OP_VERIFY
.PP
Implemtation of NFS4_OP_VERIFY. This is usually made for cache validator implementation.
.PP
\fBParameters:\fP
.RS 4
\fIop\fP [IN] pointer to nfs4_op arguments 
.br
\fIdata\fP [INOUT] Pointer to the compound request's data 
.br
\fIresp\fP [IN] Pointer to nfs4_op results
.RE
.PP
\fBReturns:\fP
.RS 4
NFS4_OK 
.RE
.PP

.PP
Definition at line 143 of file nfs4_op_verify.c.
.SS "#define res_VERIFY4   resp->nfs_resop4_u.opverify"
.PP
Definition at line 144 of file nfs4_op_verify.c.
.SH "Function Documentation"
.PP 
.SS "int nfs4_op_verify (struct nfs_argop4 * op, compound_data_t * data, struct nfs_resop4 * resp)"
.PP
Definition at line 146 of file nfs4_op_verify.c.
.SS "void nfs4_op_verify_Free (VERIFY4res * resp)"
.PP
nfs4_op_verify_Free: frees what was allocared to handle nfs4_op_verify.
.PP
Frees what was allocared to handle nfs4_op_verify.
.PP
\fBParameters:\fP
.RS 4
\fIresp\fP [INOUT] Pointer to nfs4_op results
.RE
.PP
\fBReturns:\fP
.RS 4
nothing (void function ) 
.RE
.PP

.PP
Definition at line 249 of file nfs4_op_verify.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for NFS and Mount protocols layer from the source code.
