.TH "nfs4_op_open_downgrade.c" 3 "9 Apr 2008" "Version 0.1" "NFS and Mount protocols layer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfs4_op_open_downgrade.c \- Routines used for managing the NFS4 COMPOUND functions. 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <pthread.h>\fP
.br
\fC#include <fcntl.h>\fP
.br
\fC#include <sys/file.h>\fP
.br
\fC#include 'HashData.h'\fP
.br
\fC#include 'HashTable.h'\fP
.br
\fC#include <rpc/types.h>\fP
.br
\fC#include <rpc/rpc.h>\fP
.br
\fC#include <rpc/auth.h>\fP
.br
\fC#include <rpc/pmap_clnt.h>\fP
.br
\fC#include 'log_functions.h'\fP
.br
\fC#include 'stuff_alloc.h'\fP
.br
\fC#include 'nfs23.h'\fP
.br
\fC#include 'nfs4.h'\fP
.br
\fC#include 'mount.h'\fP
.br
\fC#include 'nfs_core.h'\fP
.br
\fC#include 'cache_inode.h'\fP
.br
\fC#include 'cache_content.h'\fP
.br
\fC#include 'nfs_exports.h'\fP
.br
\fC#include 'nfs_creds.h'\fP
.br
\fC#include 'nfs_proto_functions.h'\fP
.br
\fC#include 'nfs_file_handle.h'\fP
.br
\fC#include 'nfs_tools.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBarg_OPEN_DOWNGRADE4\fP   op->nfs_argop4_u.opopen_downgrade"
.br
.ti -1c
.RI "#define \fBres_OPEN_DOWNGRADE4\fP   resp->nfs_resop4_u.opopen_downgrade"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBnfs4_op_open_downgrade\fP (struct nfs_argop4 *op, compound_data_t *data, struct nfs_resop4 *resp)"
.br
.ti -1c
.RI "void \fBnfs4_op_open_downgrade_Free\fP (OPEN_DOWNGRADE4res *resp)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Routines used for managing the NFS4 COMPOUND functions. 

\fBAuthor:\fP
.RS 4
\fBAuthor\fP.RS 4
deniel 
.RE
.PP
.RE
.PP
\fBDate:\fP
.RS 4
\fBDate\fP.RS 4
2005/11/28 17:02:51 
.RE
.PP
.RE
.PP
\fBVersion:\fP
.RS 4
\fBRevision\fP.RS 4
1.8 
.RE
.PP
.RE
.PP
\fBnfs4_op_open_downgrade.c\fP : Routines used for managing the NFS4 COMPOUND functions.
.PP
Definition in file \fBnfs4_op_open_downgrade.c\fP.
.SH "Define Documentation"
.PP 
.SS "#define arg_OPEN_DOWNGRADE4   op->nfs_argop4_u.opopen_downgrade"
.PP
nfs4_op_open_downgrade: The NFS4_OP_OPEN_DOWNGRADE
.PP
Implements the NFS4_OP_OPEN_DOWNGRADE
.PP
\fBParameters:\fP
.RS 4
\fIop\fP [IN] pointer to nfs4_op arguments 
.br
\fIdata\fP [INOUT] Pointer to the compound request's data 
.br
\fIresp\fP [IN] Pointer to nfs4_op results
.RE
.PP
\fBReturns:\fP
.RS 4
NFS4_OK if ok, any other value show an error. 
.RE
.PP

.PP
Definition at line 137 of file nfs4_op_open_downgrade.c.
.SS "#define res_OPEN_DOWNGRADE4   resp->nfs_resop4_u.opopen_downgrade"
.PP
Definition at line 138 of file nfs4_op_open_downgrade.c.
.PP
Referenced by nfs4_op_open_downgrade().
.SH "Function Documentation"
.PP 
.SS "int nfs4_op_open_downgrade (struct nfs_argop4 * op, compound_data_t * data, struct nfs_resop4 * resp)"
.PP
Definition at line 140 of file nfs4_op_open_downgrade.c.
.PP
References res_OPEN_DOWNGRADE4.
.SS "void nfs4_op_open_downgrade_Free (OPEN_DOWNGRADE4res * resp)"
.PP
nfs4_op_open_downgrade_Free: frees what was allocared to handle nfs4_op_open_downgrade.
.PP
Frees what was allocared to handle nfs4_op_open_downgrade.
.PP
\fBParameters:\fP
.RS 4
\fIresp\fP [INOUT] Pointer to nfs4_op results
.RE
.PP
\fBReturns:\fP
.RS 4
nothing (void function ) 
.RE
.PP

.PP
Definition at line 200 of file nfs4_op_open_downgrade.c.
.PP
Referenced by nfs4_Compound_Free().
.SH "Author"
.PP 
Generated automatically by Doxygen for NFS and Mount protocols layer from the source code.
