.TH "nfs4_op_desc__" 3 "31 Mar 2009" "Version 0.1" "NFS and Mount protocols layer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfs4_op_desc__ \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "unsigned int \fBval\fP"
.br
.ti -1c
.RI "int(* \fBfunct\fP )(struct nfs_argop4 *, compound_data_t *, struct nfs_resop4 *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 127 of file nfs4_Compound.c.
.SH "Member Data Documentation"
.PP 
.SS "int(* \fBnfs4_op_desc__::funct\fP)(struct nfs_argop4 *, compound_data_t *, struct nfs_resop4 *)"
.PP
.SS "char* \fBnfs4_op_desc__::name\fP"
.PP
Definition at line 129 of file nfs4_Compound.c.
.SS "unsigned int \fBnfs4_op_desc__::val\fP"
.PP
Definition at line 130 of file nfs4_Compound.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for NFS and Mount protocols layer from the source code.
