.TH "nfs_Null.c" 3 "31 Mar 2009" "Version 0.1" "NFS and Mount protocols layer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfs_Null.c \- NFSPROC_NULL in V2, V3 and V4.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <pthread.h>\fP
.br
\fC#include <fcntl.h>\fP
.br
\fC#include <sys/file.h>\fP
.br
\fC#include 'HashData.h'\fP
.br
\fC#include 'HashTable.h'\fP
.br
\fC#include <rpc/types.h>\fP
.br
\fC#include <rpc/rpc.h>\fP
.br
\fC#include <rpc/auth.h>\fP
.br
\fC#include <rpc/pmap_clnt.h>\fP
.br
\fC#include 'log_functions.h'\fP
.br
\fC#include 'stuff_alloc.h'\fP
.br
\fC#include 'nfs23.h'\fP
.br
\fC#include 'nfs4.h'\fP
.br
\fC#include 'mount.h'\fP
.br
\fC#include 'nfs_core.h'\fP
.br
\fC#include 'cache_inode.h'\fP
.br
\fC#include 'cache_content.h'\fP
.br
\fC#include 'nfs_exports.h'\fP
.br
\fC#include 'nfs_creds.h'\fP
.br
\fC#include 'nfs_proto_functions.h'\fP
.br
\fC#include 'nfs_tools.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBnfs_Null\fP (nfs_arg_t *parg, exportlist_t *pexport, fsal_op_context_t *pcontext, cache_inode_client_t *pclient, hash_table_t *ht, struct svc_req *preq, nfs_res_t *pres)"
.br
.ti -1c
.RI "void \fBnfs_Null_Free\fP (nfs_res_t *resp)"
.br
.in -1c
.SH "Detailed Description"
.PP 
NFSPROC_NULL in V2, V3 and V4. 

\fBAuthor:\fP
.RS 4
.RE
.PP
\fBAuthor\fP.RS 4
deniel 
.RE
.PP
\fBDate:\fP
.RS 4
.RE
.PP
\fBDate\fP.RS 4
2005/12/20 10:52:15 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision\fP.RS 4
1.10 
.RE
.PP
\fBnfs_Null.c\fP : NFSPROC_NULL in V2, V3 and V4. 
.PP
Definition in file \fBnfs_Null.c\fP.
.SH "Function Documentation"
.PP 
.SS "int nfs_Null (nfs_arg_t * parg, exportlist_t * pexport, fsal_op_context_t * pcontext, cache_inode_client_t * pclient, hash_table_t * ht, struct svc_req * preq, nfs_res_t * pres)"
.PP
nfs_Null: The NFS proc null function, for all versions.
.PP
The NFS proc null function, for all versions.
.PP
\fBParameters:\fP
.RS 4
\fIparg\fP [IN] ignored 
.br
\fIpexportlist\fP [IN] ignored 
.br
\fIpcontextp\fP [IN] ignored 
.br
\fIpclient\fP [INOUT] ignored 
.br
\fIht\fP [INOUT] ignored 
.br
\fIpreq\fP [IN] ignored 
.br
\fIpres\fP [OUT] ignored 
.RE
.PP

.PP
Definition at line 141 of file nfs_Null.c.
.SS "void nfs_Null_Free (nfs_res_t * resp)"
.PP
nfs_Null_Free: Frees the result structure allocated for nfs_Null.
.PP
Frees the result structure allocated for nfs_Null.
.PP
\fBParameters:\fP
.RS 4
\fIpres\fP [INOUT] Pointer to the result structure. 
.RE
.PP

.PP
Definition at line 161 of file nfs_Null.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for NFS and Mount protocols layer from the source code.
