.TH "test_mnt_proto.c" 3 "9 Apr 2008" "Version 0.1" "NFS and Mount protocols layer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_mnt_proto.c \- Tests for testing the mount protocol routines. 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <pthread.h>\fP
.br
\fC#include <fcntl.h>\fP
.br
\fC#include <sys/file.h>\fP
.br
\fC#include <sys/socket.h>\fP
.br
\fC#include 'HashData.h'\fP
.br
\fC#include 'HashTable.h'\fP
.br
\fC#include <rpc/types.h>\fP
.br
\fC#include <rpc/rpc.h>\fP
.br
\fC#include <rpc/auth.h>\fP
.br
\fC#include <rpc/pmap_clnt.h>\fP
.br
\fC#include 'log_functions.h'\fP
.br
\fC#include 'stuff_alloc.h'\fP
.br
\fC#include 'nfs23.h'\fP
.br
\fC#include 'nfs4.h'\fP
.br
\fC#include 'mount.h'\fP
.br
\fC#include 'nfs_core.h'\fP
.br
\fC#include 'cache_inode.h'\fP
.br
\fC#include 'cache_content.h'\fP
.br
\fC#include 'nfs_exports.h'\fP
.br
\fC#include 'nfs_creds.h'\fP
.br
\fC#include 'nfs_proto_functions.h'\fP
.br
\fC#include 'nfs_tools.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBNB_EXPORT_ENTRIES\fP   5"
.br
.ti -1c
.RI "#define \fBMaketest\fP(func, name)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprint_export_list\fP (exports export_list)"
.br
.ti -1c
.RI "int \fBtest_mnt_Null\fP ()"
.br
.ti -1c
.RI "int \fBtest_mnt_Export\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tests for testing the mount protocol routines. 

\fBAuthor:\fP
.RS 4
\fBAuthor\fP.RS 4
deniel 
.RE
.PP
.RE
.PP
\fBDate:\fP
.RS 4
\fBDate\fP.RS 4
2005/12/20 10:52:15 
.RE
.PP
.RE
.PP
\fBVersion:\fP
.RS 4
\fBRevision\fP.RS 4
1.8 
.RE
.PP
.RE
.PP

.PP
Definition in file \fBtest_mnt_proto.c\fP.
.SH "Define Documentation"
.PP 
.SS "#define Maketest(func, name)"
.PP
\fBValue:\fP
.PP
.nf
do {                      \
  int rc;                                             \
  printf('\n======== TEST %s =========\n\n',name);    \
  rc = func();                                        \
  if (rc)                                             \
    printf('\n-------- %s : %d ---------\n',name,rc); \
  else                                                \
    printf('\n-------- %s : OK ---------\n',name); \
  } while (0)
.fi
.PP
Definition at line 311 of file test_mnt_proto.c.
.PP
Referenced by main().
.SS "#define NB_EXPORT_ENTRIES   5"
.PP
Definition at line 165 of file test_mnt_proto.c.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"
.PP
Definition at line 321 of file test_mnt_proto.c.
.PP
References Maketest, test_mnt_Export(), and test_mnt_Null().
.SS "void print_export_list (exports export_list)"
.PP
Definition at line 124 of file test_mnt_proto.c.
.PP
Referenced by test_mnt_Export().
.SS "int test_mnt_Export ()"
.PP
Definition at line 166 of file test_mnt_proto.c.
.PP
References mnt_Export(), and print_export_list().
.PP
Referenced by main().
.SS "int test_mnt_Null ()"
.PP
Definition at line 148 of file test_mnt_proto.c.
.PP
References mnt_Null().
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for NFS and Mount protocols layer from the source code.
