.TH "todo" 3 "31 Mar 2009" "Version 0.1" "NFS and Mount protocols layer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
 
.IP "\fBMember \fBmnt_Export_Free\fP \fP" 1c
: BUGAZOMEU end this function 
.PP
.PP
 
.IP "\fBMember \fBnfs4_Compound\fP \fP" 1c
BUGAZOMEU: Reminder: Stats on NFSv4 operations are to be set here 
.PP
.PP
 
.IP "\fBMember \fBnfs4_op_access\fP \fP" 1c
make smater group ownership test 
.PP
.PP
 
.IP "\fBMember \fBnfs4_op_close\fP \fP" 1c
: BUGAZOMEU: check for lease use 
.PP
.PP
 
.IP "\fBMember \fBnfs4_op_lock\fP \fP" 1c
BUGAZOMEU: Manage the case if lock conflicts 
.PP
.PP
 
.IP "\fBMember \fBnfs4_op_open\fP \fP" 1c
.PP
.PP
 
.IP "\fBMember \fBnfs4_op_readdir_Free\fP \fP" 1c
Fixeme , bad Free here Mem_Free( (char *)entries->attrs.attr_vals.attrlist4_val ) ; 
.PP
.PP
 
.IP "\fBMember \fBnfs4_PseudoToFattr\fP \fP" 1c
: BUGAZOMEU: Allocation at NULL Adress here.... 
.PP
.PP
 
.IP "\fBMember \fBnfs4_PseudoToFattr\fP \fP" 1c
: not the right answer, actual quotas should be implemented 
.PP
.PP
 
.IP "\fBMember \fBnfs4_op_access_xattr\fP \fP" 1c
think about making this RW, it is RO for now 
.PP
.PP
 
.IP "\fBMember \fBnfs4_op_write_xattr\fP \fP" 1c
to be continued 
.PP
.PP
 
.IP "\fBMember \fBnfs4_XattrToFattr\fP \fP" 1c
: BUGAZOMEU: Allocation at NULL Adress here.... 
.PP
.PP
 
.IP "\fBMember \fBnfs4_XattrToFattr\fP \fP" 1c
: not the right answer, actual quotas should be implemented 
.PP
.PP
 
.IP "\fBMember \fBnfs2_FSALattr_To_Fattr\fP \fP" 1c
mode mask ? 
.PP
.PP
 
.IP "\fBMember \fBnfs3_Errno\fP \fP" 1c
: Check if this works by making stress tests 
.PP
.PP
 
.IP "\fBMember \fBnfs4_FSALattr_To_Fattr\fP \fP" 1c
: not the right answer, actual quotas should be implemented 
.PP
.PP
 
.IP "\fBMember \fBnfs_RetryableError\fP \fP" 1c
: Not implemented for NOW BUGAZEOMEU
.PP
.PP
.PP
 
.IP "\fBMember \fBnfs3_Write_Xattr\fP \fP" 1c
to be continued 
.PP

