log_functions.c File Reference
#include <stdlib.h>
#include <ctype.h>
#include <pthread.h>
#include <stdio.h>
#include <stdarg.h>
#include <unistd.h>
#include <fcntl.h>
#include <time.h>
#include <sys/types.h>
#include <sys/param.h>
#include <sys/stat.h>
#include <errno.h>
#include <string.h>
#include <signal.h>
#include `log_functions.h`
Classes
struct ThreadLogContext_t
Defines
#define STR_LEN_TXT 2048
#define PATH_LEN 1024
#define MAX_STR_LEN 1024
#define MAX_NUM_FAMILY 50
#define UNUSED_SLOT -1
#define P(_mutex_) pthread_mutex_lock(&_mutex_)
#define V(_mutex_) pthread_mutex_unlock(&_mutex_)
#define Localtime_r localtime_r
#define ONE_STEP do { iterformat +=1 ; len += 1; } while(0)
#define NO_TYPE 0
#define INT_TYPE 1
#define LONG_TYPE 2
#define CHAR_TYPE 3
#define STRING_TYPE 4
#define FLOAT_TYPE 5
#define DOUBLE_TYPE 6
#define POINTEUR_TYPE 7
#define EXTENDED_TYPE 8
#define STATUS_SHORT 1
#define STATUS_LONG 2
#define CONTEXTE_SHORT 3
#define CONTEXTE_LONG 4
#define ERREUR_SHORT 5
#define ERREUR_LONG 6
#define ERRNUM_SHORT 7
#define ERRNUM_LONG 8
#define ERRCTX_SHORT 9
#define ERRCTX_LONG 10
#define CHANGE_ERR_FAMILY 11
#define CHANGE_CTX_FAMILY 12
#define NO_LONG 0
#define SHORT_LG 1
#define LONG_LG 2
#define LONG_LONG_LG 3
#define MAX_STR_TOK 1024
#define VA_ARG_ERREUR_T numero = va_arg(arguments, long) ; label = va_arg(arguments, char *) ; msg = va_arg(arguments, char *)
Typedefs
typedef ThreadLogContext_t ThreadLogContext_t
Functions
int ReturnLevelAscii (char *LevelEnAscii)
char * ReturnLevelInt (int level)
int SetNamePgm (char *nom)
int SetNameHost (char *nom)
int SetNameFunction (char *nom)
int SetNameFileLog (char *nom)
char * ReturnNamePgm ()
char * ReturnNameHost ()
char * ReturnNameFunction ()
char * ReturnNameFileLog ()
int ReturnLevelDebug ()
int SetLevelDebug (int level_to_set)
int InitDebug (int level_to_set)
int DisplayLogString (char *chaine, char *format,...)
int DisplayLogFd (int fd, char *format,...)
int DisplayLogFlux (FILE *flux, char *format,...)
int DisplayLogPath (char *path, char *format,...)
int DisplayLog (char *format,...)
int DisplayLogStringLevel (char *tampon, int level, char *format,...)
int DisplayLogFluxLevel (FILE *flux, int level, char *format,...)
int DisplayLogFdLevel (int fd, int level, char *format,...)
int DisplayLogLevel (int level, char *format,...)
int DisplayLogPathLevel (char *path, int level, char *format,...)
int AddFamilyError (int num_family, char *name_family, family_error_t *tab_err)
int RemoveFamilyError (int num_family)
char * ReturnNameFamilyError (int num_family)
int DisplayErrorStringLine (char *tampon, int num_family, int num_error, int status, int ma_ligne)
int DisplayErrorFluxLine (FILE *flux, int num_family, int num_error, int status, int ma_ligne)
int DisplayErrorFdLine (int fd, int num_family, int num_error, int status, int ma_ligne)
int DisplayErrorLogLine (int num_family, int num_error, int status, int ma_ligne)
int AddLogStreamJd (log_t *pjd, type_log_stream_t type, desc_log_stream_t desc_voie, niveau_t niveau, aiguillage_t aiguillage)
int DisplayLogJdLevel (log_t jd, int level, char *format,...)
int DisplayLogJd (log_t jd, char *format,...)
int DisplayErrorJdLine (log_t jd, int num_family, int num_error, int status, int ma_ligne)
int log_vsnprintf (char *out, size_t taille, char *format, va_list arguments)
int log_sprintf (char *out, char *format,...)
int log_snprintf (char *out, size_t n, char *format,...)
int log_fprintf (FILE *file, char *format,...)
int log_vfprintf (FILE *file, char *format, va_list arguments)
int log_printf (char *format,...)
Define Documentation
#define CHANGE_CTX_FAMILY 12
Definition at line 1150 of file log_functions.c.
Referenced by log_vsnprintf().
#define CHANGE_ERR_FAMILY 11
Definition at line 1149 of file log_functions.c.
Referenced by log_vsnprintf().
#define CHAR_TYPE 3
Definition at line 1130 of file log_functions.c.
Referenced by log_vsnprintf().
#define CONTEXTE_LONG 4
Definition at line 1142 of file log_functions.c.
Referenced by log_vsnprintf().
#define CONTEXTE_SHORT 3
Definition at line 1141 of file log_functions.c.
Referenced by log_vsnprintf().
#define DOUBLE_TYPE 6
Definition at line 1133 of file log_functions.c.
Referenced by log_vsnprintf().
#define ERRCTX_LONG 10
Definition at line 1148 of file log_functions.c.
Referenced by log_vsnprintf().
#define ERRCTX_SHORT 9
Definition at line 1147 of file log_functions.c.
Referenced by log_vsnprintf().
#define ERREUR_LONG 6
Definition at line 1144 of file log_functions.c.
Referenced by log_vsnprintf().
#define ERREUR_SHORT 5
Definition at line 1143 of file log_functions.c.
Referenced by log_vsnprintf().
#define ERRNUM_LONG 8
Definition at line 1146 of file log_functions.c.
Referenced by log_vsnprintf().
#define ERRNUM_SHORT 7
Definition at line 1145 of file log_functions.c.
Referenced by log_vsnprintf().
#define EXTENDED_TYPE 8
Definition at line 1137 of file log_functions.c.
#define FLOAT_TYPE 5
Definition at line 1132 of file log_functions.c.
Referenced by log_vsnprintf().
#define INT_TYPE 1
Definition at line 1128 of file log_functions.c.
Referenced by log_vsnprintf().
#define Localtime_r localtime_r
Definition at line 176 of file log_functions.c.
#define LONG_LG 2
Definition at line 1155 of file log_functions.c.
Referenced by log_vsnprintf().
#define LONG_LONG_LG 3
Definition at line 1156 of file log_functions.c.
Referenced by log_vsnprintf().
#define LONG_TYPE 2
Definition at line 1129 of file log_functions.c.
Referenced by log_vsnprintf().
#define MAX_NUM_FAMILY 50
Definition at line 104 of file log_functions.c.
#define MAX_STR_LEN 1024
Definition at line 103 of file log_functions.c.
#define MAX_STR_TOK 1024
Definition at line 1158 of file log_functions.c.
Referenced by log_vsnprintf().
#define NO_LONG 0
Definition at line 1153 of file log_functions.c.
Referenced by log_vsnprintf().
#define NO_TYPE 0
Definition at line 1127 of file log_functions.c.
#define ONE_STEP do { iterformat +=1 ; len += 1; } while(0)
Definition at line 1125 of file log_functions.c.
#define P(_mutex_) pthread_mutex_lock(&_mutex_)
Definition at line 108 of file log_functions.c.
#define PATH_LEN 1024
Definition at line 102 of file log_functions.c.
#define POINTEUR_TYPE 7
Definition at line 1134 of file log_functions.c.
Referenced by log_vsnprintf().
#define SHORT_LG 1
Definition at line 1154 of file log_functions.c.
Referenced by log_vsnprintf().
#define STATUS_LONG 2
Definition at line 1140 of file log_functions.c.
Referenced by log_vsnprintf().
#define STATUS_SHORT 1
Definition at line 1139 of file log_functions.c.
Referenced by log_vsnprintf().
#define STR_LEN_TXT 2048
Definition at line 101 of file log_functions.c.
#define STRING_TYPE 4
Definition at line 1131 of file log_functions.c.
Referenced by log_vsnprintf().
#define UNUSED_SLOT -1
Definition at line 105 of file log_functions.c.
#define V(_mutex_) pthread_mutex_unlock(&_mutex_)
Definition at line 109 of file log_functions.c.
#define VA_ARG_ERREUR_T numero = va_arg(arguments, long) ; label = va_arg(arguments, char *) ; msg = va_arg(arguments, char *)
Typedef Documentation
typedef struct ThreadLogContext_t ThreadLogContext_t
Function Documentation
int AddFamilyError (int num_family, char * name_family, family_error_t * tab_err)
Definition at line 794 of file log_functions.c.
Referenced by main().
int AddLogStreamJd (log_t * pjd, type_log_stream_t type, desc_log_stream_t desc_voie, niveau_t niveau, aiguillage_t aiguillage)
Definition at line 966 of file log_functions.c.
Referenced by Test1().
int DisplayErrorFdLine (int fd, int num_family, int num_error, int status, int ma_ligne)
Definition at line 943 of file log_functions.c.
References DisplayLogFd().
int DisplayErrorFluxLine (FILE * flux, int num_family, int num_error, int status, int ma_ligne)
Definition at line 933 of file log_functions.c.
References DisplayLogFlux().
int DisplayErrorJdLine (log_t jd, int num_family, int num_error, int status, int ma_ligne)
Definition at line 1113 of file log_functions.c.
References DisplayLogJd().
int DisplayErrorLogLine (int num_family, int num_error, int status, int ma_ligne)
Definition at line 953 of file log_functions.c.
References DisplayLog().
int DisplayErrorStringLine (char * tampon, int num_family, int num_error, int status, int ma_ligne)
Definition at line 923 of file log_functions.c.
References DisplayLogString().
Referenced by Test1().
int DisplayLog (char * format, ...)
Definition at line 672 of file log_functions.c.
Referenced by DisplayErrorLogLine(), and Test1().
int DisplayLogFd (int fd, char * format, ...)
Definition at line 545 of file log_functions.c.
Referenced by DisplayErrorFdLine(), and Test1().
int DisplayLogFdLevel (int fd, int level, char * format, ...)
Definition at line 733 of file log_functions.c.
int DisplayLogFlux (FILE * flux, char * format, ...)
Definition at line 569 of file log_functions.c.
Referenced by DisplayErrorFluxLine(), and Test1().
int DisplayLogFluxLevel (FILE * flux, int level, char * format, ...)
Definition at line 714 of file log_functions.c.
int DisplayLogJd (log_t jd, char * format, ...)
Definition at line 1071 of file log_functions.c.
Referenced by DisplayErrorJdLine().
int DisplayLogJdLevel (log_t jd, int level, char * format, ...)
Definition at line 997 of file log_functions.c.
Referenced by Test1().
int DisplayLogLevel (int level, char * format, ...)
Definition at line 751 of file log_functions.c.
int DisplayLogPath (char * path, char * format, ...)
Definition at line 654 of file log_functions.c.
Referenced by Test1().
int DisplayLogPathLevel (char * path, int level, char * format, ...)
Definition at line 770 of file log_functions.c.
int DisplayLogString (char * chaine, char * format, ...)
Definition at line 523 of file log_functions.c.
Referenced by DisplayErrorStringLine(), and Test1().
int DisplayLogStringLevel (char * tampon, int level, char * format, ...)
Definition at line 693 of file log_functions.c.
int InitDebug (int level_to_set)
Definition at line 456 of file log_functions.c.
References SetLevelDebug().
Referenced by main().
int log_fprintf (FILE * file, char * format, ...)
Definition at line 1755 of file log_functions.c.
References log_vsnprintf().
int log_printf (char * format, ...)
Definition at line 1780 of file log_functions.c.
References log_vfprintf().
int log_snprintf (char * out, size_t n, char * format, ...)
Definition at line 1743 of file log_functions.c.
References log_vsnprintf().
int log_sprintf (char * out, char * format, ...)
Definition at line 1731 of file log_functions.c.
Referenced by Test1().
int log_vfprintf (FILE * file, char * format, va_list arguments)
Definition at line 1769 of file log_functions.c.
References log_vsnprintf().
Referenced by log_printf().
int log_vsnprintf (char * out, size_t taille, char * format, va_list arguments)
Definition at line 1161 of file log_functions.c.
References CHANGE_CTX_FAMILY, CHANGE_ERR_FAMILY, CHAR_TYPE, CONTEXTE_LONG, CONTEXTE_SHORT, DOUBLE_TYPE, ERRCTX_LONG, ERRCTX_SHORT, ERREUR_LONG, ERREUR_SHORT, ERRNUM_LONG, ERRNUM_SHORT, FLOAT_TYPE, INT_TYPE, LONG_LG, LONG_LONG_LG, LONG_TYPE, MAX_STR_TOK, NO_LONG, POINTEUR_TYPE, SHORT_LG, STATUS_LONG, STATUS_SHORT, and STRING_TYPE.
Referenced by log_fprintf(), log_snprintf(), and log_vfprintf().
int RemoveFamilyError (int num_family)
Definition at line 822 of file log_functions.c.
int ReturnLevelAscii (char * LevelEnAscii)
Definition at line 258 of file log_functions.c.
int ReturnLevelDebug ()
Definition at line 410 of file log_functions.c.
char* ReturnLevelInt (int level)
Definition at line 270 of file log_functions.c.
char* ReturnNameFamilyError (int num_family)
Definition at line 837 of file log_functions.c.
Referenced by main().
char* ReturnNameFileLog ()
Definition at line 368 of file log_functions.c.
char* ReturnNameFunction ()
Definition at line 357 of file log_functions.c.
References ThreadLogContext_t::nom_fonction.
Referenced by Test1().
char* ReturnNameHost ()
Definition at line 347 of file log_functions.c.
Referenced by Test1().
char* ReturnNamePgm ()
Definition at line 338 of file log_functions.c.
int SetLevelDebug (int level_to_set)
Definition at line 415 of file log_functions.c.
Referenced by InitDebug().
int SetNameFileLog (char * nom)
Definition at line 325 of file log_functions.c.
Referenced by main().
int SetNameFunction (char * nom)
Definition at line 311 of file log_functions.c.
References ThreadLogContext_t::nom_fonction.
Referenced by Test1().
int SetNameHost (char * nom)
Definition at line 300 of file log_functions.c.
Referenced by main().
int SetNamePgm (char * nom)
Definition at line 286 of file log_functions.c.
Referenced by main().