test_liblog_functions.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include `log_functions.h`
Defines
#define ERR_PIPO_1 0
#define ERR_PIPO_2 1
#define NB_THREADS 20
Functions
void * Test1 (void *arg)
int main (int argc, char *argv[])
Define Documentation
#define ERR_PIPO_1 0
Referenced by Test1().
#define ERR_PIPO_2 1
Referenced by Test1().
#define NB_THREADS 20
Definition at line 174 of file test_liblog_functions.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 176 of file test_liblog_functions.c.
References AddFamilyError(), InitDebug(), ReturnNameFamilyError(), SetNameFileLog(), SetNameHost(), SetNamePgm(), and Test1().
void* Test1 (void * arg)
Tests about Log streams and special printf functions.
Definition at line 104 of file test_liblog_functions.c.
References AddLogStreamJd(), DisplayErrorStringLine(), DisplayLog(), DisplayLogFd(), DisplayLogFlux(), DisplayLogJdLevel(), DisplayLogPath(), DisplayLogString(), ERR_PIPO_1, ERR_PIPO_2, log_sprintf(), ReturnNameFunction(), ReturnNameHost(), and SetNameFunction().
Referenced by main().