HashTableExportedFunctions
Functions
hash_table_t * HashTable_Init (hash_parameter_t hparam)
int HashTable_Test_And_Set (hash_table_t *ht, hash_buffer_t *buffkey, hash_buffer_t *buffval, hashtable_set_how_t how)
int HashTable_Get (hash_table_t *ht, hash_buffer_t *buffkey, hash_buffer_t *buffval)
int HashTable_Del (hash_table_t *ht, hash_buffer_t *buffkey, hash_buffer_t *p_usedbuffkey, hash_buffer_t *p_usedbuffdata)
void HashTable_GetStats (hash_table_t *ht, hash_stat_t *hstat)
unsigned int HashTable_GetSize (hash_table_t *ht)
void HashTable_Print (hash_table_t *ht)
Function Documentation
int HashTable_Del (hash_table_t * ht, hash_buffer_t * buffkey, hash_buffer_t * p_usedbuffkey, hash_buffer_t * p_usedbuffdata)
HashTable_Del: Remove a (key,val) couple from the hashtable.
Remove a (key,val) couple from the hashtable. The parameter buffkey contains the key which describes the object to be removed from the hash table.
Parameters:
ht the hashtable to be used.
buffkey a pointeur to an object of type hash_buffer_t which describe the key location in memory.
pusedbuffkeydata the key data buffer that was associated with this entry. Not considered if equal to NULL.
Returns: HASHTABLE_SUCCESS if successfull
.
HASHTABLE_ERROR_NO_SUCH_KEY is the key was not found.
See also: HashTable_Set
HashTable_Init(p.)
HashTable_Get(p.)
Definition at line 816 of file HashTable.c.
Referenced by do_del(), and main().
int HashTable_Get (hash_table_t * ht, hash_buffer_t * buffkey, hash_buffer_t * buffval)
HashTable_Get: Try to retrieve the value associated with a key.
Try to retrieve the value associated with a key. The structure buffval will point to the object found if successfull.
Parameters:
ht the hashtable to be used.
buffkey a pointeur to an object of type hash_buffer_t which describe the key location in memory.
buffval a pointeur to an object of type hash_buffer_t which describe the value location in memory.
Returns: HASHTABLE_SUCCESS if successfull
.
HASHTABLE_ERROR_NO_SUCH_KEY is the key was not found.
See also: HashTable_Set
HashTable_Init(p.)
HashTable_Del(p.)
Definition at line 754 of file HashTable.c.
Referenced by do_get(), and main().
unsigned int HashTable_GetSize (hash_table_t * ht)
HashTable_GetSize: Gets the number of entries in the hashtable.
Gets the number of entries in the hashtable.
Parameters:
ht the hashtable to be used.
Returns: the number of found entries
See also: HashTable_Set
HashTable_Init(p.)
HashTable_Get(p.)
Definition at line 986 of file HashTable.c.
void HashTable_GetStats (hash_table_t * ht, hash_stat_t * hstat)
HashTable_GetStats: Computes statistiques on the hashtable
Print information about the hashtable (mostly for debugging purpose).
Parameters:
ht the hashtable to be used.
hstat pointer to the result
Returns: none (returns void).
See also: HashTable_Set
HashTable_Init(p.)
HashTable_Get(p.)
Definition at line 908 of file HashTable.c.
Referenced by main().
hash_table_t* HashTable_Init (hash_parameter_t hparam)
HashTable_Init: Init the Hash Table.
Init the Hash Table .
Parameters:
hparam A structure of type hash_parameter_t which contains the values used to init the hash table.
Returns: NULL if init failed, the pointeur to the hashtable otherwise.
See also: HashTable_Get(p.)
HashTable_Set
HashTable_Del(p.)
Definition at line 515 of file HashTable.c.
References Mem_Alloc.
Referenced by main().
void HashTable_Print (hash_table_t * ht)
HashTable_Print: Print information about the hashtable (mostly for debugging purpose).
Print information about the hashtable (mostly for debugging purpose).
Parameters:
ht the hashtable to be used.
Returns: none (returns void).
See also: HashTable_Set
HashTable_Init(p.)
HashTable_Get(p.)
Definition at line 1015 of file HashTable.c.
Referenced by main().
int HashTable_Test_And_Set (hash_table_t * ht, hash_buffer_t * buffkey, hash_buffer_t * buffval, hashtable_set_how_t how)
HashTable_Test_And_Set: set a pair (key,value) into the Hash Table.
Set a (key,val) couple in the hashtable .
Parameters:
ht the hashtable to be used.
buffkey a pointeur to an object of type hash_buffer_t which describe the key location in memory.
buffval a pointeur to an object of type hash_buffer_t which describe the value location in memory.
how a switch to tell if the entry is to be tested or overwritten or not
Returns: HASHTABLE_SUCCESS if successfull
.
HASHTABLE_INSERT_MALLOC_ERROR if an error occured during the insertion process.
See also: HashTable_Get(p.)
HashTable_Init(p.)
HashTable_Del(p.)
Definition at line 617 of file HashTable.c.
Referenced by do_new(), do_test(), and main().