test_configurable_hash.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <strings.h>
#include <string.h>
#include <errno.h>
#include `HashTable.h`
#include `MesureTemps.h`
#include `BuddyMalloc.h`
Defines
#define LENBUF 256
#define STRSIZE 10
#define MAXTEST 10000
#define MAXDESTROY 5
#define MAXGET 3
#define NB_PREALLOC 10000
#define PRIME 3
#define CRITERE 12
#define CRITERE_2 14
#define Mem_Alloc(a) BuddyMalloc(a)
#define Mem_Free(a) BuddyFree(a)
Functions
int compare_string_buffer (hash_buffer_t *buff1, hash_buffer_t *buff2)
int display_buff (hash_buffer_t *pbuff, char *str)
unsigned long simple_hash_func (hash_parameter_t *p_hparam, hash_buffer_t *buffclef)
unsigned long double_hash_func (hash_parameter_t *p_hparam, hash_buffer_t *buffclef)
unsigned long rbt_hash_func (hash_parameter_t *p_hparam, hash_buffer_t *buffclef)
int do_get (hash_table_t *ht, int key, int *pval)
int do_set (hash_table_t *ht, int key, int val)
int do_new (hash_table_t *ht, int key, int val)
int do_del (hash_table_t *ht, int key)
int do_test (hash_table_t *ht, int key)
int main (int argc, char *argv[])
Define Documentation
#define CRITERE 12
Definition at line 146 of file test_configurable_hash.c.
#define CRITERE_2 14
Definition at line 147 of file test_configurable_hash.c.
#define LENBUF 256
Definition at line 139 of file test_configurable_hash.c.
Referenced by main().
#define MAXDESTROY 5
Definition at line 142 of file test_configurable_hash.c.
#define MAXGET 3
Definition at line 143 of file test_configurable_hash.c.
#define MAXTEST 10000
Definition at line 141 of file test_configurable_hash.c.
#define Mem_Alloc(a) BuddyMalloc(a)
Definition at line 155 of file test_configurable_hash.c.
Referenced by do_set(), HashTable_Init(), and main().
#define Mem_Free(a) BuddyFree(a)
Definition at line 156 of file test_configurable_hash.c.
#define NB_PREALLOC 10000
Definition at line 144 of file test_configurable_hash.c.
#define PRIME 3
Definition at line 145 of file test_configurable_hash.c.
#define STRSIZE 10
Definition at line 140 of file test_configurable_hash.c.
Referenced by do_set(), and main().
Function Documentation
int compare_string_buffer (hash_buffer_t * buff1, hash_buffer_t * buff2)
Definition at line 159 of file test_configurable_hash.c.
int display_buff (hash_buffer_t * pbuff, char * str)
Definition at line 174 of file test_configurable_hash.c.
int do_del (hash_table_t * ht, int key)
Definition at line 244 of file test_configurable_hash.c.
References HashTable_Del().
Referenced by main().
int do_get (hash_table_t * ht, int key, int * pval)
Definition at line 183 of file test_configurable_hash.c.
References HashTable_Get().
Referenced by main().
int do_new (hash_table_t * ht, int key, int val)
Definition at line 225 of file test_configurable_hash.c.
References HashTable_Test_And_Set().
Referenced by main().
int do_set (hash_table_t * ht, int key, int val)
Definition at line 203 of file test_configurable_hash.c.
References Mem_Alloc, and STRSIZE.
Referenced by main().
int do_test (hash_table_t * ht, int key)
Definition at line 257 of file test_configurable_hash.c.
References HashTable_Test_And_Set().
Referenced by main().
int main (int argc, char * argv[])
Definition at line 272 of file test_configurable_hash.c.
References do_del(), do_get(), do_new(), do_set(), do_test(), HashTable_Init(), HashTable_Print(), LENBUF, MAXTEST, Mem_Alloc, and STRSIZE.