test_cmchash_bugdelete.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <strings.h>
#include <string.h>
#include `BuddyMalloc.h`
#include `HashTable.h`
#include `MesureTemps.h`
Defines
#define MAXTEST 10000
#define MAXDESTROY 50
#define MAXGET 30
#define NB_PREALLOC 10000
#define PRIME 109
#define CRITERE 12
#define CRITERE_2 14
Functions
int compare_string_buffer (hash_buffer_t *buff1, hash_buffer_t *buff2)
int display_buff (hash_buffer_t *pbuff, char *str)
unsigned long simple_hash_func (hash_parameter_t *p_hparam, hash_buffer_t *buffclef)
unsigned long double_hash_func (hash_parameter_t *p_hparam, hash_buffer_t *buffclef)
unsigned long rbt_hash_func (hash_parameter_t *p_hparam, hash_buffer_t *buffclef)
int main (int argc, char *argv[])
Variables
int bugdelete_key_array []
Define Documentation
#define CRITERE 12
Definition at line 146 of file test_cmchash_bugdelete.c.
#define CRITERE_2 14
Definition at line 147 of file test_cmchash_bugdelete.c.
#define MAXDESTROY 50
Definition at line 142 of file test_cmchash_bugdelete.c.
#define MAXGET 30
Definition at line 143 of file test_cmchash_bugdelete.c.
#define MAXTEST 10000
Definition at line 141 of file test_cmchash_bugdelete.c.
#define NB_PREALLOC 10000
Definition at line 144 of file test_cmchash_bugdelete.c.
#define PRIME 109
Definition at line 145 of file test_cmchash_bugdelete.c.
Function Documentation
int compare_string_buffer (hash_buffer_t * buff1, hash_buffer_t * buff2)
Definition at line 203 of file test_cmchash_bugdelete.c.
int display_buff (hash_buffer_t * pbuff, char * str)
Definition at line 218 of file test_cmchash_bugdelete.c.
int main (int argc, char * argv[])
Definition at line 227 of file test_cmchash_bugdelete.c.
References bugdelete_key_array, CRITERE_2, HashTable_Del(), HashTable_Get(), HashTable_GetStats(), HashTable_Init(), HashTable_Print(), HashTable_Test_And_Set(), MAXDESTROY, MAXGET, MAXTEST, rbt_hash_func(), and simple_hash_func().
Variable Documentation
int bugdelete_key_array[]
Definition at line 148 of file test_cmchash_bugdelete.c.
Referenced by main().