.TH "cache_content_crash_recover.c" 3 "15 Sep 2010" "Version 0.1" "File Content layer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cache_content_crash_recover.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'LRU_List.h'\fP
.br
\fC#include 'log_macros.h'\fP
.br
\fC#include 'HashData.h'\fP
.br
\fC#include 'HashTable.h'\fP
.br
\fC#include 'fsal.h'\fP
.br
\fC#include 'cache_inode.h'\fP
.br
\fC#include 'cache_content.h'\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <sys/types.h>\fP
.br
\fC#include <sys/param.h>\fP
.br
\fC#include <time.h>\fP
.br
\fC#include <pthread.h>\fP
.br
\fC#include <errno.h>\fP
.br
\fC#include <dirent.h>\fP
.br
\fC#include <string.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "cache_content_status_t \fBcache_content_crash_recover\fP (unsigned short exportid, unsigned int index, unsigned int mod, cache_content_client_t *pclient_data, cache_inode_client_t *pclient_inode, hash_table_t *ht, fsal_op_context_t *pcontext, cache_content_status_t *pstatus)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "cache_content_status_t cache_content_crash_recover (unsigned short exportid, unsigned int index, unsigned int mod, cache_content_client_t * pclient_data, cache_inode_client_t * pclient_inode, hash_table_t * ht, fsal_op_context_t * pcontext, cache_content_status_t * pstatus)"cache_content_crash_recover: recovers the data cache and the associated inode after a crash.
.PP
\fBParameters:\fP
.RS 4
\fIpclient\fP [IN] ressource allocated by the client for the nfs management.  [OUT] returned status.
.RE
.PP
\fBReturns:\fP
.RS 4
CACHE_CONTENT_SUCCESS is successful. 
.RE
.PP

.PP
Definition at line 72 of file cache_content_crash_recover.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for File Content layer from the source code.
