.TH "cache_content_truncate.c" 3 "15 Sep 2010" "Version 0.1" "File Content layer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cache_content_truncate.c \- 
.PP
Management of the file content cache: truncate operation.  

.SH SYNOPSIS
.br
.PP
\fC#include 'LRU_List.h'\fP
.br
\fC#include 'log_macros.h'\fP
.br
\fC#include 'HashData.h'\fP
.br
\fC#include 'HashTable.h'\fP
.br
\fC#include 'fsal.h'\fP
.br
\fC#include 'cache_inode.h'\fP
.br
\fC#include 'cache_content.h'\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <sys/types.h>\fP
.br
\fC#include <sys/param.h>\fP
.br
\fC#include <time.h>\fP
.br
\fC#include <pthread.h>\fP
.br
\fC#include <string.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "cache_content_status_t \fBcache_content_truncate\fP (cache_content_entry_t *pentry, fsal_size_t length, cache_content_client_t *pclient, cache_content_status_t *pstatus)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Management of the file content cache: truncate operation. 

\fBAuthor:\fP
.RS 4
.RE
.PP
\fBAuthor\fP.RS 4
deniel 
.RE
.PP
\fBDate:\fP
.RS 4
.RE
.PP
\fBDate\fP.RS 4
2005/11/28 17:02:33 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision\fP.RS 4
1.5 
.RE
.PP
\fBcache_content_truncate.c\fP : Management of the file content cache, truncate operation. 
.PP
Definition in file \fBcache_content_truncate.c\fP.
.SH "Function Documentation"
.PP 
.SS "cache_content_status_t cache_content_truncate (cache_content_entry_t * pentry, fsal_size_t length, cache_content_client_t * pclient, cache_content_status_t * pstatus)"
.PP
Definition at line 60 of file cache_content_truncate.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for File Content layer from the source code.
