.TH "cache_content_gc.c" 3 "15 Sep 2010" "Version 0.1" "File Content layer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cache_content_gc.c \- 
.PP
Management of the file content cache: initialisation.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stuff_alloc.h'\fP
.br
\fC#include 'LRU_List.h'\fP
.br
\fC#include 'log_macros.h'\fP
.br
\fC#include 'HashData.h'\fP
.br
\fC#include 'HashTable.h'\fP
.br
\fC#include 'fsal.h'\fP
.br
\fC#include 'cache_inode.h'\fP
.br
\fC#include 'cache_content.h'\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <sys/types.h>\fP
.br
\fC#include <sys/param.h>\fP
.br
\fC#include <time.h>\fP
.br
\fC#include <pthread.h>\fP
.br
\fC#include <errno.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcache_content_set_gc_policy\fP (cache_content_gc_policy_t policy)"
.br
.ti -1c
.RI "cache_content_gc_policy_t \fBcache_content_get_gc_policy\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "cache_content_gc_policy_t \fBcache_content_gc_policy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Management of the file content cache: initialisation. 

\fBAuthor:\fP
.RS 4
.RE
.PP
\fBAuthor\fP.RS 4
deniel 
.RE
.PP
\fBDate:\fP
.RS 4
.RE
.PP
\fBDate\fP.RS 4
2005/11/28 17:02:33 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision\fP.RS 4
1.8 
.RE
.PP
cache_content.c : Management of the file content cache: initialisation. 
.PP
Definition in file \fBcache_content_gc.c\fP.
.SH "Function Documentation"
.PP 
.SS "cache_content_gc_policy_t cache_content_get_gc_policy (void)"cache_content_get_gc_policy: Set the cache_content garbagge collecting policy.
.PP
\fBReturns:\fP
.RS 4
the current policy. 
.RE
.PP

.PP
Definition at line 92 of file cache_content_gc.c.
.SS "void cache_content_set_gc_policy (cache_content_gc_policy_t policy)"cache_content_set_gc_policy: Set the cache_content garbagge collecting policy.
.PP
\fBParameters:\fP
.RS 4
\fIpolicy\fP [IN] policy to be set.
.RE
.PP
\fBReturns:\fP
.RS 4
nothing (void function) 
.RE
.PP

.PP
Definition at line 80 of file cache_content_gc.c.
.SH "Variable Documentation"
.PP 
.SS "cache_content_gc_policy_t \fBcache_content_gc_policy\fP"
.PP
Definition at line 69 of file cache_content_gc.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for File Content layer from the source code.
