.TH "todo" 3 "9 Apr 2008" "Version 0.1" "File Content layer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List
 
.IP "\fBMember \fBcache_content_refresh\fP(cache_content_entry_t *pentry, cache_content_client_t *pclient, fsal_op_context_t *pcontext, cache_content_refresh_how_t how, cache_content_status_t *pstatus) \fP" 1c
: BUGAZOMEU: gestion de coherence de date a mettre en place 
.PP
.PP
 
.IP "\fBMember \fBcache_content_read_conf_client_parameter\fP(config_file_t in_config, cache_content_client_parameter_t *pparam) \fP" 1c
: BUGAZOMEU: to be removed 
.PP
: BUGAZOMEU: to be removed 
.PP
: BUGAZOMEU: to be removed
.PP

