.TH "HashTable.c" 3 "9 Apr 2008" "Version 0.1" "Hash Table Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HashTable.c \- Gestion des tables de hachage a base de Red/Black Trees. 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <pthread.h>\fP
.br
\fC#include 'RW_Lock.h'\fP
.br
\fC#include 'BuddyMalloc.h'\fP
.br
\fC#include 'HashTable.h'\fP
.br
\fC#include 'stuff_alloc.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBTRUE\fP   1"
.br
.ti -1c
.RI "#define \fBFALSE\fP   0"
.br
.ti -1c
.RI "#define \fBP\fP(a)   pthread_mutex_lock( &a )"
.br
.ti -1c
.RI "#define \fBV\fP(a)   pthread_mutex_unlock( &a )"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned long \fBsimple_hash_func\fP (hash_parameter_t *p_hparam, hash_buffer_t *buffclef)"
.br
.ti -1c
.RI "unsigned long \fBdouble_hash_func\fP (hash_parameter_t *p_hparam, hash_buffer_t *buffclef)"
.br
.ti -1c
.RI "unsigned int \fBrbt_hash_func\fP (hash_parameter_t *p_hparam, hash_buffer_t *buffclef)"
.br
.ti -1c
.RI "hash_table_t * \fBHashTable_Init\fP (hash_parameter_t hparam)"
.br
.ti -1c
.RI "int \fBHashTable_Test_And_Set\fP (hash_table_t *ht, hash_buffer_t *buffkey, hash_buffer_t *buffval, hashtable_set_how_t how)"
.br
.ti -1c
.RI "int \fBHashTable_Get\fP (hash_table_t *ht, hash_buffer_t *buffkey, hash_buffer_t *buffval)"
.br
.ti -1c
.RI "int \fBHashTable_Del\fP (hash_table_t *ht, hash_buffer_t *buffkey, hash_buffer_t *p_usedbuffkey, hash_buffer_t *p_usedbuffdata)"
.br
.ti -1c
.RI "void \fBHashTable_GetStats\fP (hash_table_t *ht, hash_stat_t *hstat)"
.br
.ti -1c
.RI "unsigned int \fBHashTable_GetSize\fP (hash_table_t *ht)"
.br
.ti -1c
.RI "void \fBHashTable_Print\fP (hash_table_t *ht)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Gestion des tables de hachage a base de Red/Black Trees. 

\fBAuthor:\fP
.RS 4
\fBAuthor\fP.RS 4
deniel 
.RE
.PP
.RE
.PP
\fBDate:\fP
.RS 4
\fBDate\fP.RS 4
2006/01/31 09:12:06 
.RE
.PP
.RE
.PP
\fBVersion:\fP
.RS 4
\fBRevision\fP.RS 4
1.41 
.RE
.PP
.RE
.PP
\fBHashTable.c\fP : gestion d'une table de hachage
.PP
\fBHeader\fP.RS 4
/cea/home/cvs/cvs/SHERPA/BaseCvs/GANESHA/src/HashTable/HashTable.c,v 1.41 2006/01/31 09:12:06 deniel Exp 
.RE
.PP
.PP
\fBLog\fP.RS 4
\fBHashTable.c\fP,v 
.RE
.PP
Revision 1.41 2006/01/31 09:12:06 deniel First step in efence debugging
.PP
Revision 1.40 2006/01/27 10:28:36 deniel Now support rpm
.PP
Revision 1.39 2006/01/24 13:47:31 leibovic Disabling prealloc checks when _NO_BLOCK_PREALLOC falg is set.
.PP
Revision 1.38 2006/01/20 07:39:22 leibovic Back to the previous version.
.PP
Revision 1.36 2005/11/28 17:02:37 deniel Added CeCILL headers
.PP
Revision 1.35 2005/11/10 07:53:24 deniel Corrected some memory leaks
.PP
Revision 1.34 2005/08/12 07:11:14 deniel Corrected cache_inode_readdir semantics
.PP
Revision 1.33 2005/08/03 08:51:43 deniel Added file exports.c in libsupport.a
.PP
Revision 1.32 2005/08/03 07:22:17 deniel Added dependence management for SemN
.PP
Revision 1.31 2005/07/28 08:25:10 deniel Adding different ifdef statemement for additional debugging
.PP
Revision 1.30 2005/07/19 14:43:40 deniel Added mnt_export support, add cache inode client init for each worker
.PP
Revision 1.29 2005/07/11 15:30:06 deniel Mount udp/tcp ok with NFSv4 on pseudo fs on kernel 2.6.11
.PP
Revision 1.28 2005/05/10 11:43:57 deniel Datacache and metadatacache are noewqw bounded
.PP
Revision 1.27 2005/04/28 14:04:17 deniel Modified HashTabel_Del prototype
.PP
Revision 1.26 2005/04/14 14:43:09 deniel Corrected a bug in HashTable_Test_And_Set (when several nodes have the same rbt value)
.PP
Revision 1.25 2005/03/02 10:56:59 deniel Corrected a bug in pdata management
.PP
Revision 1.24 2005/03/01 09:17:09 deniel Added doxygen tags
.PP
Revision 1.23 2005/02/18 09:35:49 deniel Garbagge collection is ok for file (directory gc is not yet implemented)
.PP
Revision 1.22 2004/12/15 16:18:35 deniel DEBUG behaviour in HashTable_Print is now the default behaviour
.PP
Revision 1.21 2004/11/23 16:44:58 deniel Plenty of bugs corrected
.PP
Revision 1.20 2004/11/15 16:46:16 deniel Integration of pseudo fs
.PP
Revision 1.19 2004/10/25 06:34:54 deniel Multiples preallocated pool to avoid thread conflict whem inserting new entries in MT environment
.PP
Revision 1.18 2004/10/13 13:01:35 deniel Now using the stuff allocator
.PP
Revision 1.17 2004/10/11 07:05:44 deniel Protection des tables de hachage par des mutex (un par RBT)
.PP
Revision 1.16 2004/09/23 08:19:16 deniel Cleaning
.PP
Revision 1.15 2004/08/26 06:52:58 deniel Bug tres con dans \fBHashTable.c\fP, au niveau de hashTabel_Test_And_Set (mauvaise enclosure de #ifdef)
.PP
Revision 1.14 2004/08/25 06:21:24 deniel Mise en place du test configurable ok
.PP
Revision 1.13 2004/08/24 10:41:14 deniel Avant re-ecriture d'un autre test.
.PP
Revision 1.12 2004/08/23 16:05:20 deniel Mise en palce d'un test and set a la place du set pure
.PP
Revision 1.11 2004/08/23 09:14:35 deniel Ajout de tests de non-regression (pour le delete)
.PP
Revision 1.10 2004/08/23 08:20:55 deniel Mise en place de RBT_FIND_LEFT
.PP
Revision 1.9 2004/08/23 07:57:10 deniel Injection des nouveaux rbt de Jacques
.PP
Revision 1.8 2004/08/20 08:55:13 deniel Rajout du support des statistique Doxygenisation des sources
.PP
Revision 1.7 2004/08/19 09:19:12 deniel des allocations groupees par chunk
.PP
Revision 1.6 2004/08/19 08:08:04 deniel Mise au carre des tests sur les libs dynamiques et insertions des mesures de temps dans les tests
.PP
Revision 1.5 2004/08/18 14:26:18 deniel La table de hachage est clean
.PP
Revision 1.4 2004/08/18 13:49:37 deniel Table de Hash avec RBT, qui marche, mais pas clean au niveau des headers
.PP
Revision 1.3 2004/08/18 09:14:25 deniel Ok pour les nouvelles tables de hash plus generiques avec des listes chaines
.PP
Revision 1.2 2004/08/16 12:15:22 deniel Premiere mise en place simple des tables de hash (mais sans RBTree)
.PP
Revision 1.1 2004/08/16 09:35:05 deniel Population de la repository avec les Hashtables et les RW_Lock
.PP
Revision 1.4 2004/01/12 15:24:40 deniel Version finalisee
.PP
Revision 1.2 2004/01/12 14:52:08 deniel Version presque finale (le del, le set et le get fonctionnent)
.PP
Revision 1.1 2004/01/12 12:31:15 deniel Premiere version des fichiers de gestion de la table de hachage, en debug
.PP
Definition in file \fBHashTable.c\fP.
.SH "Define Documentation"
.PP 
.SS "#define FALSE   0"
.PP
Definition at line 242 of file HashTable.c.
.SS "#define P(a)   pthread_mutex_lock( &a )"
.PP
Definition at line 246 of file HashTable.c.
.SS "#define TRUE   1"
.PP
Definition at line 238 of file HashTable.c.
.SS "#define V(a)   pthread_mutex_unlock( &a )"
.PP
Definition at line 250 of file HashTable.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hash Table Library from the source code.
