.TH "HashTableInternalFunctions" 3 "9 Apr 2008" "Version 0.1" "Hash Table Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HashTableInternalFunctions \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "group \fBHashTableExportedFunctions\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned long \fBsimple_hash_func\fP (hash_parameter_t *p_hparam, hash_buffer_t *buffclef)"
.br
.ti -1c
.RI "unsigned long \fBdouble_hash_func\fP (hash_parameter_t *p_hparam, hash_buffer_t *buffclef)"
.br
.ti -1c
.RI "unsigned int \fBrbt_hash_func\fP (hash_parameter_t *p_hparam, hash_buffer_t *buffclef)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "unsigned long double_hash_func (hash_parameter_t * p_hparam, hash_buffer_t * buffclef)"
.PP
double_hash_func: This function is used for double hashing, based on another hash function.
.PP
This functions uses the hash function contained in hparam to compute a first hash value, then use it to compute a second value like this: h = ( firsthash + ( 8 - ( firsthash  8 ) ) )  hparam.index_size This operation just changes the last 3 bits, but it can be demonstrated that this produced a more efficient and better balanced hash function (See 'Algorithm in C', Robert Sedjewick for more detail on this).
.PP
\fBParameters:\fP
.RS 4
\fIhparam\fP the parameter structure that was used to define the hashtable 
.br
\fIbuffclef\fP the key to compute the hash value on
.RE
.PP
\fBReturns:\fP
.RS 4
the hash value
.RE
.PP
\fBSee also:\fP
.RS 4
\fBdouble_hash_func\fP 
.RE
.PP

.PP
Definition at line 315 of file HashTable.c.
.SS "unsigned int rbt_hash_func (hash_parameter_t * p_hparam, hash_buffer_t * buffclef)"
.PP
rbt_hash_func: Another hash junction, but to be used for the red-black trees managed internally.
.PP
This library uses red-black trees to store data. RB trees use key data too. The hash function has to be different than the one used for find the RB Tree, if not all the entry in the tree will have the same hash value which will lead to a very unbalanced tree
.PP
\fBParameters:\fP
.RS 4
\fIhparam\fP the parameter structure that was used to define the hashtable 
.br
\fIbuffclef\fP the key to compute the hash value on
.RE
.PP
\fBReturns:\fP
.RS 4
the hash value 
.RE
.PP

.PP
Definition at line 345 of file HashTable.c.
.PP
Referenced by main().
.SS "unsigned long simple_hash_func (hash_parameter_t * p_hparam, hash_buffer_t * buffclef)"
.PP
simple_hash_func: A template hash function, which considers the hash key as a polynom
.PP
A template hash function, which considers the hash key as a polynom. we are supposed to managed string written with ht->alphabet_length different characters We turn the string into a binary by computing str[0]+str[1]*ht->alphabet_length+str[2]*ht->alphabet_length**2 + ... ... + str[N]*ht->alphabet_length**N Then we keep the modulo by index_size. This size has to be a prime integer for performance reason The polynome is computed with the Horner's method.
.PP
\fBParameters:\fP
.RS 4
\fIhparam\fP the parameter structure that was used to define the hashtable 
.br
\fIbuffclef\fP the key to compute the hash value on
.RE
.PP
\fBReturns:\fP
.RS 4
the hash value
.RE
.PP
\fBSee also:\fP
.RS 4
\fBdouble_hash_func\fP 
.RE
.PP

.PP
Definition at line 278 of file HashTable.c.
.PP
Referenced by main().
