.TH "test_configurable_hash.c" 3 "9 Apr 2008" "Version 0.1" "Hash Table Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_configurable_hash.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <strings.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <errno.h>\fP
.br
\fC#include 'HashTable.h'\fP
.br
\fC#include 'MesureTemps.h'\fP
.br
\fC#include 'BuddyMalloc.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBLENBUF\fP   256"
.br
.ti -1c
.RI "#define \fBSTRSIZE\fP   10"
.br
.ti -1c
.RI "#define \fBMAXTEST\fP   10000"
.br
.ti -1c
.RI "#define \fBMAXDESTROY\fP   5"
.br
.ti -1c
.RI "#define \fBMAXGET\fP   3"
.br
.ti -1c
.RI "#define \fBNB_PREALLOC\fP   10000"
.br
.ti -1c
.RI "#define \fBPRIME\fP   3"
.br
.ti -1c
.RI "#define \fBCRITERE\fP   12"
.br
.ti -1c
.RI "#define \fBCRITERE_2\fP   14"
.br
.ti -1c
.RI "#define \fBMem_Alloc\fP(a)   BuddyMalloc( a )"
.br
.ti -1c
.RI "#define \fBMem_Free\fP(a)   BuddyFree( a )"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcompare_string_buffer\fP (hash_buffer_t *buff1, hash_buffer_t *buff2)"
.br
.ti -1c
.RI "int \fBdisplay_buff\fP (hash_buffer_t *pbuff, char *str)"
.br
.ti -1c
.RI "unsigned long \fBsimple_hash_func\fP (hash_parameter_t *p_hparam, hash_buffer_t *buffclef)"
.br
.ti -1c
.RI "unsigned long \fBdouble_hash_func\fP (hash_parameter_t *p_hparam, hash_buffer_t *buffclef)"
.br
.ti -1c
.RI "unsigned long \fBrbt_hash_func\fP (hash_parameter_t *p_hparam, hash_buffer_t *buffclef)"
.br
.ti -1c
.RI "int \fBdo_get\fP (hash_table_t *ht, int key, int *pval)"
.br
.ti -1c
.RI "int \fBdo_set\fP (hash_table_t *ht, int key, int val)"
.br
.ti -1c
.RI "int \fBdo_new\fP (hash_table_t *ht, int key, int val)"
.br
.ti -1c
.RI "int \fBdo_del\fP (hash_table_t *ht, int key)"
.br
.ti -1c
.RI "int \fBdo_test\fP (hash_table_t *ht, int key)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define CRITERE   12"
.PP
Definition at line 146 of file test_configurable_hash.c.
.SS "#define CRITERE_2   14"
.PP
Definition at line 147 of file test_configurable_hash.c.
.SS "#define LENBUF   256"
.PP
Definition at line 139 of file test_configurable_hash.c.
.PP
Referenced by main().
.SS "#define MAXDESTROY   5"
.PP
Definition at line 142 of file test_configurable_hash.c.
.SS "#define MAXGET   3"
.PP
Definition at line 143 of file test_configurable_hash.c.
.SS "#define MAXTEST   10000"
.PP
Definition at line 141 of file test_configurable_hash.c.
.SS "#define Mem_Alloc(a)   BuddyMalloc( a )"
.PP
Definition at line 155 of file test_configurable_hash.c.
.PP
Referenced by do_set(), HashTable_Init(), and main().
.SS "#define Mem_Free(a)   BuddyFree( a )"
.PP
Definition at line 156 of file test_configurable_hash.c.
.SS "#define NB_PREALLOC   10000"
.PP
Definition at line 144 of file test_configurable_hash.c.
.SS "#define PRIME   3"
.PP
Definition at line 145 of file test_configurable_hash.c.
.SS "#define STRSIZE   10"
.PP
Definition at line 140 of file test_configurable_hash.c.
.PP
Referenced by do_set(), and main().
.SH "Function Documentation"
.PP 
.SS "int compare_string_buffer (hash_buffer_t * buff1, hash_buffer_t * buff2)"
.PP
Definition at line 159 of file test_configurable_hash.c.
.SS "int display_buff (hash_buffer_t * pbuff, char * str)"
.PP
Definition at line 174 of file test_configurable_hash.c.
.SS "int do_del (hash_table_t * ht, int key)"
.PP
Definition at line 244 of file test_configurable_hash.c.
.PP
References HashTable_Del().
.PP
Referenced by main().
.SS "int do_get (hash_table_t * ht, int key, int * pval)"
.PP
Definition at line 183 of file test_configurable_hash.c.
.PP
References HashTable_Get().
.PP
Referenced by main().
.SS "int do_new (hash_table_t * ht, int key, int val)"
.PP
Definition at line 225 of file test_configurable_hash.c.
.PP
References HashTable_Test_And_Set().
.PP
Referenced by main().
.SS "int do_set (hash_table_t * ht, int key, int val)"
.PP
Definition at line 203 of file test_configurable_hash.c.
.PP
References Mem_Alloc, and STRSIZE.
.PP
Referenced by main().
.SS "int do_test (hash_table_t * ht, int key)"
.PP
Definition at line 257 of file test_configurable_hash.c.
.PP
References HashTable_Test_And_Set().
.PP
Referenced by main().
.SS "int main (int argc, char * argv[])"
.PP
Definition at line 272 of file test_configurable_hash.c.
.PP
References do_del(), do_get(), do_new(), do_set(), do_test(), HashTable_Init(), HashTable_Print(), LENBUF, MAXTEST, Mem_Alloc, and STRSIZE.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hash Table Library from the source code.
