.TH "test_cmchash.c" 3 "31 Mar 2009" "Version 0.1" "Hash Table Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_cmchash.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <strings.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include 'BuddyMalloc.h'\fP
.br
\fC#include 'HashTable.h'\fP
.br
\fC#include 'MesureTemps.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMAXTEST\fP   10000"
.br
.ti -1c
.RI "#define \fBMAXDESTROY\fP   50"
.br
.ti -1c
.RI "#define \fBMAXGET\fP   30"
.br
.ti -1c
.RI "#define \fBNB_PREALLOC\fP   10000"
.br
.ti -1c
.RI "#define \fBPRIME\fP   109"
.br
.ti -1c
.RI "#define \fBCRITERE\fP   12"
.br
.ti -1c
.RI "#define \fBCRITERE_2\fP   14"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcompare_string_buffer\fP (hash_buffer_t *buff1, hash_buffer_t *buff2)"
.br
.ti -1c
.RI "int \fBdisplay_buff\fP (hash_buffer_t *pbuff, char *str)"
.br
.ti -1c
.RI "unsigned long \fBsimple_hash_func\fP (hash_parameter_t *p_hparam, hash_buffer_t *buffclef)"
.br
.ti -1c
.RI "unsigned long \fBdouble_hash_func\fP (hash_parameter_t *p_hparam, hash_buffer_t *buffclef)"
.br
.ti -1c
.RI "unsigned long \fBrbt_hash_func\fP (hash_parameter_t *p_hparam, hash_buffer_t *buffclef)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define CRITERE   12"
.PP
Definition at line 146 of file test_cmchash.c.
.SS "#define CRITERE_2   14"
.PP
Definition at line 147 of file test_cmchash.c.
.SS "#define MAXDESTROY   50"
.PP
Definition at line 142 of file test_cmchash.c.
.SS "#define MAXGET   30"
.PP
Definition at line 143 of file test_cmchash.c.
.SS "#define MAXTEST   10000"
.PP
Definition at line 141 of file test_cmchash.c.
.SS "#define NB_PREALLOC   10000"
.PP
Definition at line 144 of file test_cmchash.c.
.SS "#define PRIME   109"
.PP
Definition at line 145 of file test_cmchash.c.
.SH "Function Documentation"
.PP 
.SS "int compare_string_buffer (hash_buffer_t * buff1, hash_buffer_t * buff2)"
.PP
Definition at line 149 of file test_cmchash.c.
.SS "int display_buff (hash_buffer_t * pbuff, char * str)"
.PP
Definition at line 164 of file test_cmchash.c.
.SS "int main (int argc, char * argv[])"
.PP
Definition at line 174 of file test_cmchash.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hash Table Library from the source code.
