/* SPDX-License-Identifier: LGPL-3.0-or-later */
/*
 * vim:noexpandtab:shiftwidth=8:tabstop=8:
 *
 * Copyright (C) 2025, IBM . All rights reserved.
 * Author: Naresh Chillarege<Naresh.Chillarege@ibm.com>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.  see <http://www.gnu.org/licenses/
 *
 * ---------------------------------------
 */

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CQOS_H_RPCGEN
#define _CQOS_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef int int32_t;

typedef u_int uint32_t;

typedef quad_t int64_t;

typedef u_quad_t uint64_t;

typedef enum {
	CQOS_PUBLISH = 1,
	CQOS_SUBSCRIBE,
	CQOS_UNSUBSCRIBE
} cqos_cmd_type_t;

struct cluster_qos_msg {
	cqos_cmd_type_t cqos_cmd;
	int32_t cqos_ops;
	uint16_t export_id;
	uint64_t export_rbw;
	uint64_t export_wbw;
	uint64_t export_riops;
	uint64_t export_wiops;
	uint64_t client_rbw;
	uint64_t client_wbw;
	uint64_t client_riops;
	uint64_t client_wiops;
	sockaddr_t node_addr;
	sockaddr_t client_addr;
};
typedef struct cluster_qos_msg cluster_qos_msg;

#define CQOSPROG 100062
#define CQOS_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CQOSPROC_PUBSUB_NULL 0
extern enum clnt_stat cqosproc_pubsub_null_1(void *, CLIENT *);
extern bool_t cqosproc_pubsub_null_1_svc(void *, struct svc_req *);
#define CQOSPROC_PUBSUB_MSG 1
extern enum clnt_stat cqosproc_pubsub_msg_1(cluster_qos_msg, void *, CLIENT *);
extern bool_t cqosproc_pubsub_msg_1_svc(cluster_qos_msg, void *,
					struct svc_req *);
extern int cqosprog_1_freeresult(SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CQOSPROC_PUBSUB_NULL 0
extern enum clnt_stat cqosproc_pubsub_null_1(void);
extern bool_t cqosproc_pubsub_null_1_svc(void);
#define CQOSPROC_PUBSUB_MSG 1
extern enum clnt_stat cqosproc_pubsub_msg_1(void);
extern bool_t cqosproc_pubsub_msg_1_svc(void);
extern int cqosprog_1_freeresult(void);
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern bool xdr_cluster_qos_msg(XDR *, cluster_qos_msg *);

#else /* K&R C */
extern bool xdr_cluster_qos_msg(void);

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CQOS_H_RPCGEN */
