LRUExportedFunctions
Functions
LRU_list_t * LRU_Init (LRU_parameter_t lru_param, LRU_status_t *pstatus)
int LRU_invalidate (LRU_list_t *plru, LRU_entry_t *pentry)
LRU_entry_t * LRU_new_entry (LRU_list_t *plru, LRU_status_t *pstatus)
int LRU_gc_invalid (LRU_list_t *plru, void *cleanparam)
int LRU_invalidate_by_function (LRU_list_t *plru, int(*testfunc)(LRU_entry_t *, void *addparam), void *addparam)
int LRU_apply_function (LRU_list_t *plru, int(*myfunc)(LRU_entry_t *, void *addparam), void *addparam)
void LRU_Print (LRU_list_t *plru)
Function Documentation
int LRU_apply_function (LRU_list_t * plru, int(*)(LRU_entry_t *, void *addparam) myfunc, void * addparam)
LRU_apply_function: apply the same function to every LRU entry, but do not change their states.
apply the same function to every LRU entry, but do not change their states.
Parameters:
plru [INOUT] LRU list to be managed.
myfunc [IN] function used to be runned on every entry. If this function return FALSE, the loop stops.
addparam [IN] parameter for the input function.
Returns: LRU_LIST_SUCCESS if ok, other values shows an error
See also: LRU_invalidate(p.)
LRU_gc_invalid(p.)
Definition at line 447 of file LRU_List.c.
int LRU_gc_invalid (LRU_list_t * plru, void * cleanparam)
LRU_gc_invalid : garbagge collection for invalid entries.
Read the whole LRU list and put the invalid entries back to the pool.
Parameters:
plru Pointer to the list to be managed.
Returns: An integer to contain the status for the operation.
See also: LRU_invalidate(p.)
Definition at line 318 of file LRU_List.c.
Referenced by do_gc(), and main().
LRU_list_t* LRU_Init (LRU_parameter_t lru_param, LRU_status_t * pstatus)
LRU_Init: Init the LRU list.
Init the Hash Table .
Parameters:
lru_param A structure of type lru_parameter_t which contains the values used to init the LRU.
pstatus Pointer to an integer to contain the status for the operation.
Returns: NULL if init failed, the pointeur to the hashtable otherwise.
See also: PreAllocEntry
Definition at line 180 of file LRU_List.c.
Referenced by main().
int LRU_invalidate (LRU_list_t * plru, LRU_entry_t * pentry)
LRU_invalidate: Tag an entry as invalid.
Tag an entry as invalid, this kind of entry will be put off the LRU (and sent back to the pool) when a garbagge collection will be performed.
Parameters:
plru Pointer to the list to be managed.
pentry Pointer to the entry to be tagged.
Returns: LRU_LIST_SUCCESS if successfull, other values show an error.
See also: LRU_gc_invalid(p.)
Definition at line 236 of file LRU_List.c.
Referenced by do_invalidate(), LRU_invalidate_by_function(), and main().
int LRU_invalidate_by_function (LRU_list_t * plru, int(*)(LRU_entry_t *, void *addparam) testfunc, void * addparam)
LRU_invalidate_by_function: Browse the lru to test if entries should ne invalidated.
Browse the lru to test if entries should ne invalidated. This function is used for garbagge collection
Parameters:
plru [INOUT] LRU list to be managed.
testfunc [IN] function used to identify an entry to be tagged invalid. This function returns TRUE if entry will be tagged invalid
addparam [IN] parameter for the input function.
Returns: LRU_LIST_SUCCESS if ok, other values shows an error
See also: LRU_invalidate(p.)
LRU_gc_invalid(p.)
Definition at line 394 of file LRU_List.c.
References LRU_invalidate().
LRU_entry_t* LRU_new_entry (LRU_list_t * plru, LRU_status_t * pstatus)
LRU_new_entry : acquire a new entry from the pool.
acquire a new entry from the pool. If pool is empty, a new chunck is added to complete the operation.
Parameters:
plru Pointer to the list to be managed.
pstatus Pointer to an integer to contain the status for the operation.
Returns: NULL if init failed, the pointeur to the hashtable otherwise.
See also: PreAllocEntry
Definition at line 260 of file LRU_List.c.
Referenced by do_new(), and main().
void LRU_Print (LRU_list_t * plru)
HashTable_Print: Print information about the LRU (mostly for debugging purpose).
Print information about the LRU (mostly for debugging purpose).
Parameters:
plru the LRU to be used.
Returns: none (returns void).
Definition at line 493 of file LRU_List.c.
Referenced by main().