test_lru.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <strings.h>
#include <string.h>
#include `BuddyMalloc.h`
#include `LRU_List.h`
Defines
#define PREALLOC 10000
#define MAXTEST 10
#define KEPT_ENTRY 5
Functions
int print_entry (LRU_data_t data, char *str)
int clean_entry (LRU_entry_t *pentry, void *addparam)
int main (int argc, char *argv[])
Define Documentation
#define KEPT_ENTRY 5
Definition at line 123 of file test_lru.c.
#define MAXTEST 10
Definition at line 122 of file test_lru.c.
#define PREALLOC 10000
Definition at line 121 of file test_lru.c.
Function Documentation
int clean_entry (LRU_entry_t * pentry, void * addparam)
Definition at line 130 of file test_lru.c.
int main (int argc, char * argv[])
Definition at line 135 of file test_lru.c.
References LRU_gc_invalid(), LRU_Init(), LRU_invalidate(), LRU_new_entry(), and LRU_Print().
int print_entry (LRU_data_t data, char * str)
Definition at line 125 of file test_lru.c.