test_configurable_lru.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <strings.h>
#include <string.h>
#include `BuddyMalloc.h`
#include `LRU_List.h`
Defines
#define LENBUF 256
#define STRSIZE 10
#define PREALLOC 1000000
#define MAXTEST 1000000
Functions
int do_invalidate (LRU_list_t *plru, int key)
int do_new (LRU_list_t *plru, int key)
int do_gc (LRU_list_t *plru)
int main (int argc, char *argv[])
Variables
LRU_entry_t * tabentry [MAXTEST]
Define Documentation
#define LENBUF 256
Definition at line 117 of file test_configurable_lru.c.
Referenced by main().
#define MAXTEST 1000000
Definition at line 120 of file test_configurable_lru.c.
#define PREALLOC 1000000
Definition at line 119 of file test_configurable_lru.c.
#define STRSIZE 10
Definition at line 118 of file test_configurable_lru.c.
Referenced by do_new().
Function Documentation
int do_gc (LRU_list_t * plru)
Definition at line 166 of file test_configurable_lru.c.
References LRU_gc_invalid().
Referenced by main().
int do_invalidate (LRU_list_t * plru, int key)
Definition at line 134 of file test_configurable_lru.c.
References LRU_invalidate(), and tabentry.
Referenced by main().
int do_new (LRU_list_t * plru, int key)
Definition at line 143 of file test_configurable_lru.c.
References LRU_new_entry(), STRSIZE, and tabentry.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 172 of file test_configurable_lru.c.
References do_gc(), do_invalidate(), do_new(), LENBUF, LRU_Init(), and LRU_Print().
Variable Documentation
LRU_entry_t* tabentry[MAXTEST]
Definition at line 122 of file test_configurable_lru.c.
Referenced by do_invalidate(), and do_new().